// Chapter 2 Endnotes
endnotes['loma371-ch2-en1'] = '<p class="endnote"><span class="en-num">1.</span> National Association of Insurance Commissioners, Risk Based Capital (National Association of Insurance Commissioners, 2019), 1, https://www.naic.org/<wbr />cipr_topics/<wbr />topic_risk_based_capital.htm (13 March 2019) <a href="#loma371-ch2-span-25" class="return">Return to text.</a></p>';
endnotes['loma371-ch2-en3'] = '<p class="endnote"><span class="en-num">3.</span> David M. Pooser and Paul L. Walker, "Own Risk and Solvency Assessment: Origins and Implications for Enterprise Risk Management," Journal of Insurance Regulation 34, no. 9 (2015): 4-11, https://www.naic.org/<wbr />prod_serv/<wbr />JIR-ZA-34-09-EL.pdf (28 March 2019). <a href="#loma371-ch2-span-31" class="return">Return to text.</a></p>';
endnotes['loma371-ch2-en4'] = '<p class="endnote"><span class="en-num">4.</span> Diazreus, Dodd-Frank and Basel III: Implementation in the U.S., 1, https://diazreus.com/<wbr />dodd-frank-and-basel-iii-implementation-in-the-u-s/<wbr /> (16 April 2019)  <a href="#loma371-ch2-span-49" class="return">Return to text.</a></p>';
endnotes['loma371-ch2-en2'] = '<p class="endnote"><span class="en-num">2.</span> American Academy of Actuaries, Regulatory Capital Requirements of U.S. Life Insurers (American Academy of Actuaries, © 2014), 13-20, https://www.actuary.org/<wbr />sites/<wbr />default/<wbr />files/<wbr />files/<wbr />Regulatory_Capital_Requirements_US_Life_Insurers_6-17-14.pdf (13 March 2019). <a href="#loma371-ch2-span-27" class="return">Return to text.</a></p>';
// Chapter 3 Endnotes
endnotes['loma371-ch3-en3'] = '<p class="endnote"><span class="en-num">3.</span> Committee of Sponsoring Organizations of the Treadway Commission (COSO), <em>Enterprise Risk Management—Integrating with Strategy and Performance, Executive Summary</em>, June 2017, 6, https://www.coso.org/<wbr />Documents/<wbr />2017-COSO-ERM-Integrating-with-Strategy-and-Performance-Executive-Summary.pdf (3 June 2019). <a href="#loma371-ch3-span-35" class="return">Return to text.</a></p>';
endnotes['loma371-ch3-en5'] = '<p class="endnote"><span class="en-num">5.</span> Institute of Operational Risk, “Operational Risk Sound Practice Guidance, Key Risk Indicators,” (Institute of Risk Management, 2010), 3-8, 17-18, https://www.ior-institute.org/<wbr />public/<wbr />IORKRIGuidanceNov2010.pdf (20 September 2019) <a href="#loma371-ch3-span-72" class="return">Return to text.</a></p>';
endnotes['loma371-ch3-en4'] = '<p class="endnote"><span class="en-num">4.</span> Institute of Risk Management, <em>A Risk Practitioners Guide to ISO 31000: 2018</em> (London, England: Institute of Risk Management, 2018), 10, https://www.theirm.org/<wbr />media/<wbr />3513119/<wbr />IRM-Report-ISO-31000-2018-v3.pdf (4 June 2019). <a href="#loma371-ch3-span-37" class="return">Return to text.</a></p>';
endnotes['loma371-ch3-en2'] = '<p class="endnote"><span class="en-num">2.</span> David M. Pooser and Paul L. Walker, Own Risk and Solvency Assessment: Origins and Implications for Enterprise Risk Management, <em>Journal of Insurance Regulation </em>34, no. 9 (2015): 10, https://www.naic.org/<wbr />prod_serv/<wbr />JIR-ZA-34-09-EL.pdf (3 June 2019). <a href="#loma371-ch3-span-33" class="return">Return to text.</a></p>';
endnotes['loma371-ch3-en1'] = '<p class="endnote"><span class="en-num">1.</span> The Institute of Internal Auditors, <em>IIA Position Paper: The Three Lines of Defense in Effective Risk Management and Control</em> (Altamonte Springs, Florida: The Institute of Internal Auditors, 2013), https://na.theiia.org/standards-guidance/Public%20Documents/PP%20The%20Three%20Lines%20of%20Defense%20in%20Effective%20Risk%20Management%20and%20Control.pdf (18 July 2019).  <a href="#loma371-ch3-span-11" class="return">Return to text.</a></p>';
