var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2021';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 371 Practice Questions, Chapter 3";
var coursename = 'LOMA 371';
var modulenumber = 1;
var title = "LOMA_371_PPQ2021_0_3";
var intNumPools = 1;
var numQ = 12;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Risk Management and Product Design for Insurance Companies, Third Edition (2020)";
arrNumChap[0] = 1;
var thisChap = '3';

objPool = new Object(); 
objPool.intSelectCount = 12;
objPool.formID = 2617;
objPool.formName = 'PPQ2021_0_3';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_371_PQ_018';
arrPoolQuestions[1] = 'LOMA_371_PQ_019';
arrPoolQuestions[2] = 'LOMA_371_PQ_020';
arrPoolQuestions[3] = 'LOMA_371_PQ_021';
arrPoolQuestions[4] = 'LOMA_371_PQ_022';
arrPoolQuestions[5] = 'LOMA_371_PQ_023';
arrPoolQuestions[6] = 'LOMA_371_PQ_024';
arrPoolQuestions[7] = 'LOMA_371_PQ_025';
arrPoolQuestions[8] = 'LOMA_371_PQ_026';
arrPoolQuestions[9] = 'LOMA_371_PQ_027';
arrPoolQuestions[10] = 'LOMA_371_PQ_028';
arrPoolQuestions[11] = 'LOMA_371_PQ_029';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_018';
objQuestion.questionID = 121295;
objQuestion.item = 'LOMA_371_PPQ2021_018';
objQuestion.primaryLO = '3A';
objQuestion.textref = 'c. 3, pp. 4-5';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">If a proposed insured represents a higher-than-average risk, the Mica Life Insurance Company charges a higher premium than it would charge a similar proposed insured who represents an average risk. With regard to the five basic risk management strategies—avoiding risk, accepting risk, controlling risk, transferring risk, and exploiting risk—Mica’s charging a higher premium to a proposed insured who represents a higher-than-average risk best describes the strategy known as</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "avoiding risk";
arrAnsChoices[1] = "accepting risk";
arrAnsChoices[2] = "controlling risk";
arrAnsChoices[3] = "transferring risk";
arrAnsChoices[4] = "exploiting risk";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490525;
arrAnsIDs[1] = 490526;
arrAnsIDs[2] = 490527;
arrAnsIDs[3] = 490528;
arrAnsIDs[4] = 490529;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Avoidance is a good strategy for risks that are likely to have a large impact or cause large losses. Insurers can avoid some product risks by rejecting applications for life insurance from proposed life insureds who do not meet insurability standards. However, because insurers are in the business of assuming risk, avoiding risk is not always a practical risk management strategy. In this situation, Mica’s approval of the life insurance policy and charging a higher premium are not examples of avoiding the risk.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Accepting risk requires recognition of a risk and the explicit choice not to avoid, control, transfer, or exploit the risk. In this situation, Mica did accept the risk by approving coverage for the proposed insured. However, Mica’s charging a higher premium for this policy best describes the risk management strategy known as controlling the risk.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Because insurance companies are in the business of assuming risk, avoiding risk is not always a practical risk management strategy. An insurer can accept a risk and retain some or all of the financial responsibility for that risk. The insurer also may control the risk to reduce or eliminate the potential losses associated with that risk, as Mica demonstrates in this situation. Mica charges a higher premium to control part of the risk that it has accepted. Controlling risk and accepting risk are not mutually exclusive events.</p><p class=\"explanations\">Typically, as a direct writer, an insurer can transfer risk through reinsurance, but also must accept the risk that the reinsurer will fail to perform its part of the agreement. The insurer controls risk by sharing the contract’s liability. In this situation, controlling risk, accepting risk, and transferring risk are not mutually exclusive events.</p><p class=\"explanations\">An insurer also can exploit risk by taking advantage of an opportunity presented by a risk. As with other risks, an insurer typically also chooses to accept and control an exploited risk. The insurer must be confident the potential losses are an acceptable hazard in light of the potential gains in this situation.</p><p class=\"explanations\"><b>Learning Objective: 3A. Describe five basic risk management strategies and provide examples of each.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The most common way for most individuals and businesses to transfer risk is to purchase insurance coverage. Insurers transfer their risk under insurance and annuity contracts by purchasing reinsurance. In this situation, Mica did not purchase reinsurance.</p>";
arrAnswerFeedback[4] = "<p class=\"explanations\">Insurers can exploit risk by taking advantage of an opportunity—such as a competitive advantage that allows it to develop a new product that satisfies a customer need—presented by a risk. Like accepting risk, exploiting risk does not mitigate potential losses; rather, it increases the possibility of gain. Like other basic risk management strategies, exploiting risk is not an exclusive strategy. When exploiting a risk, an insurer typically also controls the risk, as the insurer would for other risks it has accepted.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_018'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_019';
objQuestion.questionID = 121296;
objQuestion.item = 'LOMA_371_PPQ2021_019';
objQuestion.primaryLO = '3B';
objQuestion.textref = 'c. 3, pp. 7-9';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">For this question, if answer choices (1) through (3) are all correct, select answer choice (4). Otherwise, select the one correct response.</p><p class=\"stem\">Generally, effective risk management programs in life insurance companies have an established governance structure, a risk taxonomy, and a system of internal controls. When combined, these practices contribute to a risk management approach called the three lines of defense, which include</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "operational management";
arrAnsChoices[1] = "risk management and compliance";
arrAnsChoices[2] = "internal audit";
arrAnsChoices[3] = "all of the above";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490530;
arrAnsIDs[1] = 490531;
arrAnsIDs[2] = 490532;
arrAnsIDs[3] = 490533;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that operational management is one of the three lines of defense in risk management. However, this is <b>not</b> the correct answer choice.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that risk management and compliance is one of the three lines of defense. However, this is <b>not</b> the correct answer&nbsp;choice.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that internal audit is one of the three lines of defense. However, this is <b>not</b> the correct answer&nbsp;choice.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The three lines of defense is a comprehensive, systematic approach to enhancing communication on risk management and controls by assigning clear responsibilities and roles to each line. The first line of defense is operational management, which owns and manages the risks under its supervision. Operational, or “frontline,” managers are responsible for identifying and assessing risk within their unit daily, ensuring controls are in place, and taking corrective actions when needed.</p><p class=\"explanations\">The second line of defense is risk management and compliance, which consists of the internal monitoring and oversight functions—such as a risk committee and compliance function—that oversees risks throughout the company.</p><p class=\"explanations\">The third line of defense is internal audit. Internal auditors provide independent assurance to the board of directors and senior management on the effectiveness of the company’s governance, its risk management practices, and its internal controls, including the level of performance for the first two lines of defense achieved. The main difference between the third line of defense and the first two lines is its high level of independence and objectivity.</p><p class=\"explanations\"><b>Learning Objective: 3B. Describe the risk management approach known as the three lines of defense.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_019'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_020';
objQuestion.questionID = 121297;
objQuestion.item = 'LOMA_371_PPQ2021_020';
objQuestion.primaryLO = '3C';
objQuestion.textref = 'c. 3, p. 8';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">A governance structure provides guidance so that a life insurer can achieve its strategic objectives. Common approaches that life insurers use for the governance of a risk management function include:</p><ol type=\"A\" class=\"combo\"><li>Employing a chief risk officer (CRO), who is responsible for all risk management activities</li><li>Relying entirely on a risk committee, without employing a CRO</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490534;
arrAnsIDs[1] = 490535;
arrAnsIDs[2] = 490536;
arrAnsIDs[3] = 490537;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Statement A is correct. The CRO usually reports to the company’s chief executive officer (CEO) and board of directors. An insurer’s CRO, risk committee, or some combination of the two must establish the insurer’s risk management culture. In addition, an insurer’s Own Risk and Solvency Assessment (ORSA) Annual Summary Report must be signed by the CRO or an equivalent person.</p><p class=\"explanations\">Statement B is correct. A cross-functional risk committee, which reports to the board of directors, is the heart of most insurance companies’ internal control system and is a key part of the second line of defense. The primary role of the risk committee is to provide overall guidance and control of an insurer’s risk management efforts. This committee is responsible for identifying, measuring, and managing all the significant risks to which an insurer is exposed, including operational risks.</p><p class=\"explanations\"><b>Learning Objective: 3C. Explain how insurers use governance, a risk taxonomy, internal controls, and the three lines of defense to manage risk.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct. However, Statement B is also correct.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is correct. However, Statement A is also correct.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_020'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_021';
objQuestion.questionID = 121298;
objQuestion.item = 'LOMA_371_PPQ2021_021';
objQuestion.primaryLO = '3D';
objQuestion.textref = 'c. 3, pp. 12-13';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Insurers can use traditional risk management or enterprise risk management (ERM) to manage risks. One difference between traditional risk management and ERM is that <I>ERM</I></p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "defines risk as the potential for losses, and primarily focuses on preventing or minimizing such&nbsp;losses";
arrAnsChoices[1] = "adopts a “silo” approach to managing risks in which separate departments or areas do not necessarily communicate with one&nbsp;another";
arrAnsChoices[2] = "encompasses all significant risks that an insurer faces";
arrAnsChoices[3] = "assumes that the responsibility for risk management is confined to specific employees";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490538;
arrAnsIDs[1] = 490539;
arrAnsIDs[2] = 490540;
arrAnsIDs[3] = 490541;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\"><b>Traditional risk management</b> defines risk as the potential for loss and primarily focuses on preventing or minimizing such losses. ERM expands the definition of risk to include not only the potential for loss but also the potential for failing to take advantage of an opportunity.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\"><b>Traditional risk management</b> uses a “silo” approach to managing risks in which separate departments or areas do not necessarily communicate with one another. ERM adopts a holistic approach to managing risks in which risks are integrated across an insurer into a corporate portfolio of risks.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">ERM and traditional risk management share many specific practices in common, such as employing a CRO, maintaining a risk committee, and establishing a risk taxonomy. The key differences between the two systems are the number of risks encompassed and ERM’s inclusion of risk as an opportunity for gain.</p><p class=\"explanations\">Traditional risk management emphasizes only certain risks that an insurer faces, whereas ERM works to improve an insurer’s overall risk-return profile. ERM takes a top-down, enterprise-wide approach to viewing all of the significant risks that could affect an insurer’s strategic objectives. According to ERM, risk is any negative consequence a company faces as it conducts its operations, including the failure to meet objectives or to exploit profitable opportunities.</p><p class=\"explanations\"><b>Learning Objective: 3D. Describe the components of an effective enterprise risk management (ERM) program, including a risk management culture, strategic risk management, a risk control process, a risk management framework, and catastrophic event management.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\"><b>Traditional risk management</b> assumes that the responsibility for risk management is confined to specific employees. ERM proposes that risk management is everyone’s responsibility.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_021'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_022';
objQuestion.questionID = 121299;
objQuestion.item = 'LOMA_371_PPQ2021_022';
objQuestion.primaryLO = '3D';
objQuestion.textref = 'c. 3, pp. 14-16';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Various authorities have developed risk management frameworks to be used as guides for implementing risk management. The following statement(s) can correctly be made about three of the most well-known risk management frameworks—the ORSA ERM framework, the COSO ERM framework, and the ISO 31000 standard:</p><ol type=\"A\" class=\"combo\"><li>According to the ORSA ERM framework, an effective risk management framework should incorporate a minimum of five key principles.</li><li>The premise of the COSO ERM framework is that internal controls should help organizations achieve their objectives in the areas of operations, reporting, and compliance.</li><li>The ISO 31000 standard lists eight principles of risk management believed to be crucial for a company to manage its risk exposures successfully.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A, B, and C";
arrAnsChoices[1] = "A and B only";
arrAnsChoices[2] = "A and C only";
arrAnsChoices[3] = "B and C only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490542;
arrAnsIDs[1] = 490543;
arrAnsIDs[2] = 490544;
arrAnsIDs[3] = 490545;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Statement A is correct. The five key principles that should be incorporated in the ORSA ERM framework are risk culture and governance; risk identification and prioritization; risk appetite, tolerances, and limits; risk management and controls; and risk reporting and communications.</p><p class=\"explanations\">Statement B is correct. The COSO ERM framework is sorted into five components supported by twenty principles that can be used to enhance performance and meet strategic objectives.</p><p class=\"explanations\">Statement C is correct. All three frameworks contain similar approaches to managing risk, although there are some key differences. For example, ORSA requires each insurer to evaluate its risk management framework on an annual basis, whereas neither the COSO ERM framework nor the ISO 31000 standard contains such a requirement (each is voluntary). Each insurer selects a risk management framework that best fits its strategic objectives and individual risk exposures.</p><p class=\"explanations\"><b>Learning Objective: 3D. Describe the components of an effective enterprise risk management (ERM) program, including a risk management culture, strategic risk management, a risk control process, a risk management framework, and catastrophic event management.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A and Statement B are correct. However, Statement C is also correct.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement A and Statement C are correct. However, Statement B is also correct.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Statement B and Statement C are correct. However, Statement A is also correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_022'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_023';
objQuestion.questionID = 121300;
objQuestion.item = 'LOMA_371_PPQ2021_023';
objQuestion.primaryLO = '3D';
objQuestion.textref = 'c. 3, pp. 18-19';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">For some purposes, risks can be divided into diversifiable risk and nondiversifiable risk. For an insurer, examples of <i>nondiversifiable</i> risk include</p><ol type=\"A\" class=\"combo\"><li>An economic recession</li><li>A party with which the insurer has a financial arrangement entirely fails to fulfill its debt obligations to the insurer</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490546;
arrAnsIDs[1] = 490547;
arrAnsIDs[2] = 490548;
arrAnsIDs[3] = 490549;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these examples is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A is correct. An economic recession is an example of nondiversifiable risk, also known as systematic risk, which is the risk that affects all assets in an economic system, and is therefore not specific to an individual asset or issuer.</p><p class=\"explanations\">B is incorrect. Most financial risks are diversifiable risks. Diversifiable risk, also known as nonsystematic risk or specific risk, is specific to an individual asset or issuer. In the context of investing, default risk is a type of credit risk in which an insurer will not receive the cash flows to which it is entitled because a party with which the insurer has a financial arrangement is late with payments or entirely fails to fulfill its debt obligations. By definition, credit risk is the risk that (1) a borrower defaults on debt obligations by failing to make payments of principal or interest on time, or (2) a lender sustains a financial loss based on an adverse change in a borrower’s creditworthiness.</p><p class=\"explanations\"><b>Learning Objective: 3D. Describe the components of an effective enterprise risk management (ERM) program, including a risk management culture, strategic risk management, a risk control process, a risk management framework, and catastrophic event management.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">B is incorrect. Most financial risks are <b>diversifiable</b> risks. Diversifiable risk, also known as nonsystematic risk or specific risk, is specific to an individual asset or issuer. In the context of investing, default risk is a type of credit risk in which an insurer will not receive the cash flows to which it is entitled because a party with which the insurer has a financial arrangement is late with payments or entirely fails to fulfill its debt obligations. By definition, credit risk is the risk that (1) a borrower defaults on debt obligations by failing to make payments of principal or interest on time, or (2) a lender sustains a financial loss based on an adverse change in a borrower’s creditworthiness.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these examples is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_023'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_024';
objQuestion.questionID = 121301;
objQuestion.item = 'LOMA_371_PPQ2021_024';
objQuestion.primaryLO = '3D';
objQuestion.textref = 'c. 3, pp. 18-19';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">When assets are assembled in a portfolio, their combined risks can have desirable or undesirable interactions. A (<b>risk augmentation / risk offset</b>) effect is present if the combination of specific risks is less than the sum of those risks. Insurers need to balance risks incurred with potential returns. When returns move in opposite directions, correlation is (<b>positive / negative</b>).</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "risk augmentation / positive";
arrAnsChoices[1] = "risk augmentation / negative";
arrAnsChoices[2] = "risk offset / positive";
arrAnsChoices[3] = "risk offset / negative";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490550;
arrAnsIDs[1] = 490551;
arrAnsIDs[2] = 490552;
arrAnsIDs[3] = 490553;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A risk augmentation effect is present if the combination of specific risks is <b>greater</b> than the sum of those risks. In addition, when returns move in the <b>same direction</b>, correlation is positive.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that, when returns move in opposite directions, correlation is negative. However, a risk augmentation effect is present if the combination of specific risks is <b>greater</b> than the sum of those risks.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that a risk offset effect is present if the combination of specific risks is less than the sum of those risks. However, when returns move in the <b>same direction</b>, correlation is positive.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Correlation among the returns of portfolio assets means that the returns tend to move together. When returns move in the same direction, correlation is positive; when returns move in opposite directions, correlation is negative.</p><p class=\"explanations\">High positive correlation occurs when the amount and direction of the movement in returns are nearly the same for all assets in the portfolio. Portfolio risk management approaches support the safety in a portfolio of risks by avoiding high positive correlation among the portfolio’s risks.</p><p class=\"explanations\"><b>Learning Objective: 3D. Describe the components of an effective enterprise risk management (ERM) program, including a risk management culture, strategic risk management, a risk control process, a risk management framework, and catastrophic event management.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_024'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_025';
objQuestion.questionID = 121302;
objQuestion.item = 'LOMA_371_PPQ2021_025';
objQuestion.primaryLO = '3E';
objQuestion.textref = 'c. 3, p. 21';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">One internal asset-liability management (ALM) report within an insurer’s ALM reporting system specifies the details of all investment portfolio transactions, including all asset acquisitions and all dispositions of assets from the investment portfolio through sales, prepayments (redemptions), or repayment at maturity. Though narrow in scope, this report, which typically is the most detailed and the most frequently produced report in a formal ALM reporting system, is known&nbsp;as</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "a duration gap report";
arrAnsChoices[1] = "an investment portfolio performance review";
arrAnsChoices[2] = "a crediting-rate resolution";
arrAnsChoices[3] = "an investment activity report";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490554;
arrAnsIDs[1] = 490555;
arrAnsIDs[2] = 490556;
arrAnsIDs[3] = 490557;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A <b>duration gap report</b> is an internal ALM report that discusses an insurer’s current exposure to portfolio cash flow mismatches caused by changes in market interest rates. Information in this report is time-sensitive because changes in market interest rates can produce dramatic changes in the asset-liability gap.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The <b>investment portfolio performance review</b> is a quarterly internal ALM report that summarizes the company’s investment performance for the board of directors and the ALM committee. This report is usually the broadest in scope of any ALM report, and it covers much of the information in summary form.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A <b>crediting-rate resolution</b>, an external ALM report, is a formal declaration by the board of directors of the rate of interest the insurer will credit on customers’ money held in interest-bearing products.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Internal ALM reports support sound ALM within a company. Because of the company-specific nature of ALM reports, they vary from one company to another. Common internal ALM reports are the investment activity report, investment portfolio performance review, and duration gap report.</p><p class=\"explanations\">Insurers commonly use two formal ALM reports for external reporting: (1) an Actuarial Opinion and Memorandum (AOM), with supporting documentation, and (2) a crediting-rate resolution.</p><p class=\"explanations\"><b>Learning Objective: 3E. Describe insurers’ use of asset-liability management (ALM) and the various types of ALM reports.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_025'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_026';
objQuestion.questionID = 121303;
objQuestion.item = 'LOMA_371_PPQ2021_026';
objQuestion.primaryLO = '3E';
objQuestion.textref = 'c. 3, p. 22';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">An annual crediting-rate resolution is a common ALM report. Typically, the (<b>investment / actuarial</b>) staff drafts crediting-rate resolutions, one for each product. Crediting rates vary (<b>widely / little</b>) by product and by insurer.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "investment / widely";
arrAnsChoices[1] = "investment / little";
arrAnsChoices[2] = "actuarial / widely";
arrAnsChoices[3] = "actuarial / little";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490558;
arrAnsIDs[1] = 490559;
arrAnsIDs[2] = 490560;
arrAnsIDs[3] = 490561;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that crediting rates vary widely by product and by insurer. However, the investment staff typically does <b>not</b> draft crediting-rate resolutions.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The investment staff typically does <b>not</b> draft crediting-rate resolutions. In addition, crediting rates vary <b>widely</b> by product and by insurer.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A crediting-rate resolution typically presents details about an insurer’s interest-crediting strategies. Interest-crediting strategies are the formulas and criteria an insurer uses to set the interest rates it will credit for interest-sensitive products. Crediting rates vary widely by product and by insurer. The crediting-rate drafts are presented for approval and adoption by the ALM steering committee on behalf of the board of directors.</p><p class=\"explanations\"><b>Learning Objective: 3E. Describe insurers’ use of asset-liability management (ALM) and the various types of ALM reports.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that the actuarial staff typically drafts crediting-rate resolutions. However, crediting rates vary <b>widely</b> by product and by insurer.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_026'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_027';
objQuestion.questionID = 121304;
objQuestion.item = 'LOMA_371_PPQ2021_027';
objQuestion.primaryLO = '3F';
objQuestion.textref = 'c. 3, pp. 19-20';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">ALM typically uses four primary portfolio management strategies: hedging, duration matching, cash-flow matching, and diversification. The strategy of holding an asset with characteristics that counterbalance one or more of the risks in an investor’s risk array—such as holding other assets with offsetting risk characteristics—is known as</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "hedging";
arrAnsChoices[1] = "duration matching";
arrAnsChoices[2] = "cash-flow matching";
arrAnsChoices[3] = "diversification";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490562;
arrAnsIDs[1] = 490563;
arrAnsIDs[2] = 490564;
arrAnsIDs[3] = 490565;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The success of these portfolio risk management strategies, or approaches, depends on the insurer’s ability to balance assets and liabilities so that (1) total assets exceed total liabilities; (2) total cash inflows exceed or are reasonably close to total cash outflows over any time period; (3) the interactions between the asset and liability portfolios are likely to reduce or eliminate some risks through risk offsets or hedges; and (4) the interactions between the asset and liability portfolios produce residual risks—the lesser risks that remain after balancing—that insurers can actively manage.</p><p class=\"explanations\">These portfolio risk management strategies are not exclusive to one another; for instance, an insurer uses duration matching in addition to other strategies to achieve proper ALM.</p><p class=\"explanations\"><b>Learning Objective: 3F. Define portfolio risk management strategies—such as diversification, hedging, cash-flow matching, and duration matching—and explain their use.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\"><b>Duration matching</b> involves matching the duration statistics for fixed-income assets such as bonds with the duration statistics for the insurer’s liabilities that the assets support. In an actuarial context, duration is a statistic that measures the price sensitivity of an asset or liability to changes in interest rates. Duration is the time-weighted value of expected cash inflows, expressed in years. Actual duration statistics vary widely from one insurer to another.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\"><b>Cash-flow matching</b> involves identifying the patterns of cash outflows for insurance products and matching those cash outflows with a selection of assets that will produce a similar pattern of cash inflows. In general, cash-flow matching works well for life insurance companies because their liabilities are fairly predictable and occur over relatively long time periods.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\"><b>Diversification</b> is a technique for spreading risk by investing in different assets having different risk profiles. To diversify their investments, insurers carefully spread their investment selections among the securities of different issuers in different business categories.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_027'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_028';
objQuestion.questionID = 121305;
objQuestion.item = 'LOMA_371_PPQ2021_028';
objQuestion.primaryLO = '3G';
objQuestion.textref = 'c. 3, p. 25';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">One way for a company to eliminate expenses is through rightsizing. Some rightsizing can be achieved through attrition, which, by definition, occurs when a company</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "elects purposefully to not replace employees who leave their jobs because of retirement, resignation, death, or disability";
arrAnsChoices[1] = "eliminates employee positions through early retirement programs, closing regional offices, and&nbsp;layoffs";
arrAnsChoices[2] = "implements the best practices that other companies use to improve operating efficiency";
arrAnsChoices[3] = "hires an external vendor to perform specified operations or functions";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490566;
arrAnsIDs[1] = 490567;
arrAnsIDs[2] = 490568;
arrAnsIDs[3] = 490569;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Rightsizing, also known as downsizing, is the elimination of nonessential jobs within an organization. To be successful, rightsizing must be accompanied by careful redesign of work processes to determine the number and types of employee positions that are essential for effective business operations. Other methods that companies can use to eliminate employee positions include early retirement programs, closing regional offices, and layoffs.</p><p class=\"explanations\"><b>Learning Objective: 3G. Explain how insurers can eliminate or reduce expense risk through outsourcing certain functions and benchmarking.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Although rightsizing can be achieved through attrition, early retirement programs, closing regional offices, and&nbsp;layoffs are other methods of rightsizing—<b>not</b> attrition—that companies can use to eliminate employee positions.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\"><b>Benchmarking</b> consists of (1) identifying the best outcomes that other companies have achieved for a specific activity or process and the practices that produced those outcomes and (2) implementing the best practices to equal or surpass the best outcomes.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\"><b>Outsourcing</b> is the practice of hiring an external vendor to perform specified operations or functions. An outsourcing arrangement may cover all or only part of the functions for an area.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_028'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_029';
objQuestion.questionID = 121306;
objQuestion.item = 'LOMA_371_PPQ2021_029';
objQuestion.primaryLO = '3H';
objQuestion.textref = 'c. 3, pp. 28-29';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3H';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Ranger Life Insurance Company is concerned about the risk of financial losses resulting from inadequate or failed internal processes, controls, systems, and people. To evaluate each department’s exposure to this risk, Ranger is asking each department manager to submit a detailed report that compiles and captures the area’s key risks, controls, and management implications. Select the answer choice that correctly identifies this type of risk and the type of report that Ranger has requested from its department managers in this situation.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[-1] = "<u>Type of risk</u></div><div class=\"anshead\"><u>Type of report</u>";
arrAnsChoices[0] = "strategy risk</div><div class=\"anscell\" onclick=\"recordAns(1);\">loss-incident database";
arrAnsChoices[1] = "strategy risk</div><div class=\"anscell\" onclick=\"recordAns(2);\">control self-assessment";
arrAnsChoices[2] = "operational risk</div><div class=\"anscell\" onclick=\"recordAns(3);\">loss-incident database";
arrAnsChoices[3] = "operational risk</div><div class=\"anscell\" onclick=\"recordAns(4);\">control self-assessment";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490571;
arrAnsIDs[1] = 490572;
arrAnsIDs[2] = 490573;
arrAnsIDs[3] = 490574;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">In this situation, the type of risk that is of concern to Ranger is <b>not</b> strategy risk, which is the risk that a particular strategy selected by an insurer to grow sales, market share, profits, or distribution will not produce the desired results and instead lead to losses. In addition, Ranger has <b>not</b> requested its department managers to submit a loss-incident database, which records every loss that an insurer has experienced, and allows the insurer to analyze its performance and make recommendations for improvements.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that Ranger has requested its department managers to submit a control self-assessment. However, the type of risk that is of concern to Ranger in this situation is <b>not</b> strategy risk, which is the risk that a particular strategy selected by an insurer to grow sales, market share, profits, or distribution will not produce the desired results and instead lead to losses.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that operational risk is of concern to Ranger in this situation. However, Ranger is <b>not</b> asking its department managers to submit a loss-incident database, which records every loss that an insurer has experienced, and allows the insurer to analyze its performance and make recommendations for&nbsp;improvements.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Ideally, insurers take a comprehensive approach to operational risk measurement that includes a variety of tools, which range from key risk indicators, risk maps, loss-incident databases, and control self-assessments to scenario testing and simulation modeling. </p><p class=\"explanations\">A key risk indicator (KRI) indicates the level of operational risk exposures at a given point of time in order to help insurers forecast future occurrences. By monitoring KRIs and checking them against agreed limits and thresholds, insurers see if their operational risk exposures are within stated risk tolerances.</p><p class=\"explanations\">A risk map, also called a risk heat map,<i><b> </b></i>categorizes each risk identified for a particular operational or business process along two dimensions—(1) impact or significance and (2) likelihood. Risk maps typically classify individual risks as minor (green), moderate (yellow), major (orange), or severe (red), based on the impact or significance of the risk and the likelihood that the risk will occur.</p><p class=\"explanations\">A loss-incident database records every loss and allows insurers to review operational activities from a single system and then identify incidents or activities that create or have the potential to create losses, analyze the company’s performance during those incidents, create summaries, and make recommendations for improvements.</p><p class=\"explanations\">An insurer might use a control self-assessment to (1) collect data—from underwriting, claims, and sales divisions—related to risks, inefficient or failed control processes, and performance gaps, and (2) propose actions to improve performance.</p><p class=\"explanations\"><b>Learning Objective: 3H. Describe some of the tools insurers use to manage operational risk, such as key risk indicators, risk maps, loss-incident databases, and control self-assessments..</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_029'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['3A'] = "3A. Describe five basic risk management strategies and provide examples of each.";
arrlotext['3B'] = "3B. Describe the risk management approach known as the three lines of defense.";
arrlotext['3C'] = "3C. Explain how insurers use governance, a risk taxonomy, internal controls, and the three lines of defense to manage risk.";
arrlotext['3D'] = "3D. Describe the components of an effective enterprise risk management (ERM) program, including a risk management culture, strategic risk management, a risk control process, a risk management framework, and catastrophic event management.";
arrlotext['3E'] = "3E. Describe insurers’ use of asset-liability management (ALM) and the various types of ALM reports.";
arrlotext['3F'] = "3F. Define portfolio risk management strategies—such as diversification, hedging, cash-flow matching, and duration matching—and explain their use.";
arrlotext['3G'] = "3G. Explain how insurers can eliminate or reduce expense risk through outsourcing certain functions and benchmarking.";
arrlotext['3H'] = "3H. Describe some of the tools insurers use to manage operational risk, such as key risk indicators, risk maps, loss-incident databases, and control self-assessments.";
