var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2020';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 357 Practice Questions, Chapter 4";
var coursename = 'LOMA 357';
var modulenumber = 1;
var title = "LOMA_357_PPQ2019_0_4";
var intNumPools = 1;
var numQ = 20;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Institutional Investing: Principles and Practices (2019)";
arrNumChap[0] = 1;
var thisChap = '4';

objPool = new Object(); 
objPool.intSelectCount = 20;
objPool.formID = 2139;
objPool.formName = 'PPQ2019_0_4';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_357_PQ_030';
arrPoolQuestions[1] = 'LOMA_357_PQ_031';
arrPoolQuestions[2] = 'LOMA_357_PQ_032';
arrPoolQuestions[3] = 'LOMA_357_PQ_033';
arrPoolQuestions[4] = 'LOMA_357_PQ_034';
arrPoolQuestions[5] = 'LOMA_357_PQ_035';
arrPoolQuestions[6] = 'LOMA_357_PQ_036';
arrPoolQuestions[7] = 'LOMA_357_PQ_037';
arrPoolQuestions[8] = 'LOMA_357_PQ_038';
arrPoolQuestions[9] = 'LOMA_357_PQ_039';
arrPoolQuestions[10] = 'LOMA_357_PQ_040';
arrPoolQuestions[11] = 'LOMA_357_PQ_041';
arrPoolQuestions[12] = 'LOMA_357_PQ_042';
arrPoolQuestions[13] = 'LOMA_357_PQ_043';
arrPoolQuestions[14] = 'LOMA_357_PQ_044';
arrPoolQuestions[15] = 'LOMA_357_PQ_045';
arrPoolQuestions[16] = 'LOMA_357_PQ_046';
arrPoolQuestions[17] = 'LOMA_357_PQ_047';
arrPoolQuestions[18] = 'LOMA_357_PQ_048';
arrPoolQuestions[19] = 'LOMA_357_PQ_049';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_030';
objQuestion.questionID = 111037;
objQuestion.item = 'LOMA_357_PPQ2019_030';
objQuestion.primaryLO = '4A';
objQuestion.textref = 'c. 4, p. 4';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '4A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Investors can receive payments of interest, dividends, or rental income from certain investments. One investment that produces dividend payments, but not interest payments or rental income, is</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "real estate properties";
arrAnsChoices[1] = "stocks";
arrAnsChoices[2] = "bonds";
arrAnsChoices[3] = "mortgages";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448774;
arrAnsIDs[1] = 448775;
arrAnsIDs[2] = 448776;
arrAnsIDs[3] = 448777;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Investors that own real estate properties can collect income in the form of <b>rent and lease payments</b>.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Investors may receive dividend payments from companies that choose to distribute a portion of their profits directly to shareholders of their stocks. The amount of a particular dividend payment depends on the number of shares held by the investor and the declared dividend rate.</p><p class=\"explanations\">How much income an individual real estate property generates depends on the type of property and economic factors, such as market interest rates. For fixed-income securities and other debt assets, individual interest payments depend on factors unique to the asset—such as the issuer’s credit rating, the amount of the debt, and the debt’s interest rate.</p><p class=\"explanations\"><b>Learning Objective: 4A. Explain how investors earn investment returns from capital gains and income payments.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Investors that own fixed-income securities and other debt assets, such as bonds and mortgages, collect income in the form of <b>interest payments</b>.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Investors that own fixed-income securities and other debt assets, such as bonds and mortgages, collect income in the form of <b>interest payments</b>.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_030'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_031';
objQuestion.questionID = 111038;
objQuestion.item = 'LOMA_357_PPQ2019_031';
objQuestion.primaryLO = '4B';
objQuestion.textref = 'c. 4, pp. 7-8';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '4B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">A bond with a $1,000 par value pays a 3% coupon rate. If the bond has a $1,050 market price, then its current yield is equal to</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "2.86%";
arrAnsChoices[1] = "3.15%";
arrAnsChoices[2] = "4.76%";
arrAnsChoices[3] = "5.00%";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448778;
arrAnsIDs[1] = 448779;
arrAnsIDs[2] = 448780;
arrAnsIDs[3] = 448781;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Bond investors do not always hold their bonds until maturity. An investor may want to calculate a bond’s yield for a shorter length of time, such as one year. To determine a bond’s one-year yield, investors calculate its current yield: the formula is Annual coupon payment ÷ Current market price = Current yield. In this situation, ($1,000 ×.03) ÷ $1,050 = 2.86%.</p><p class=\"explanations\">Note that the bond’s coupon rate and coupon payments do not change, although the current yield changes each time the bond’s market price changes. When the bond is trading at a premium to par value, the current yield is lower than the 3% coupon rate, as in this situation. Conversely, when the bond is trading at a discount to par value, the current yield is higher than the 3% coupon rate.</p><p class=\"explanations\"><b>Learning Objective: 4B. Describe how certain factors—such as prices, market interest rates, inflation, and the stages of the business cycle—can affect investment returns.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The formula for the current yield of a bond is Annual coupon payment ÷ Current market price = Current yield. In this situation, ($1,000 ×.03) ÷ $1,050 = 2.86%.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The formula for the current yield of a bond is Annual coupon payment ÷ Current market price = Current yield. In this situation, ($1,000 ×.03) ÷ $1,050 = 2.86%.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The formula for the current yield of a bond is Annual coupon payment ÷ Current market price = Current yield. In this situation, ($1,000 ×.03) ÷ $1,050 = 2.86%.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_031'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_032';
objQuestion.questionID = 111039;
objQuestion.item = 'LOMA_357_PPQ2019_032';
objQuestion.primaryLO = '4B';
objQuestion.textref = 'c. 4, pp. 10-11';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '4B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Yield curves generally take on one of several shapes. When the yield curve shows an upward slope from left to right, indicating that yields on long-term debt securities are higher than yields on short-term debt securities, the yield curve is known as</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "an inverted yield curve";
arrAnsChoices[1] = "a downward-slope curve";
arrAnsChoices[2] = "a normal yield curve";
arrAnsChoices[3] = "a flat yield curve";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448782;
arrAnsIDs[1] = 448783;
arrAnsIDs[2] = 448784;
arrAnsIDs[3] = 448785;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">An inverted yield curve shows a <b>downward</b> slope from left to right, which indicates that yields on short-term debt securities are higher than yields on long-term debt securities.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A downward slope from left to right shows an <b>inverted yield curve</b>, which indicates that yields on short-term debt securities are higher than yields on long-term debt securities.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Higher long-term yields signal that investors expect interest rates to rise, which will decrease bond market values and increase bond yields. A normal yield curve also signals expectations of healthy economic growth, as rising interest rates are generally associated with periods of rising economic growth. A flat or practically flat yield curve signals that investors do not expect future interest-rate increases or cannot determine the direction of future interest-rate changes.</p><p class=\"explanations\">Many investors see an inverted yield curve as a sign of an impending economic recession—a period of significant decline in economic activity, lasting more than a few months—because interest rates fall when an economy is weak. Bonds with longer terms to maturity become more desirable than bonds with shorter terms. Decreased demand for short-term bonds decreases their market values, thus increasing their yields.</p><p class=\"explanations\"><b>Learning Objective: 4B. Describe how certain factors—such as prices, market interest rates, inflation, and the stages of the business cycle—can affect investment returns.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A flat yield curve shows a <b>horizontal straight line</b>, which indicates that yields on debt securities are not responsive to varying terms to maturity.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_032'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_033';
objQuestion.questionID = 111040;
objQuestion.item = 'LOMA_357_PPQ2019_033';
objQuestion.primaryLO = '4B';
objQuestion.textref = 'c. 4, pp. 12-14';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '4B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The relationship between certain factors—such as prices, market interest rates, inflation, and the stages of the business cycle—is complex and can affect investment returns. The stated rate of return on an investment without adjustment for inflation or other factors is called the <b>(nominal / real)</b> rate of return. Generally, the business cycle indicates whether a given economy is increasing or decreasing its production of goods and services. Economic activity grows during the <b>(expansion / peak)</b> phase and shrinks during the <b>(contraction / trough)</b> phase of the business cycle.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "nominal / expansion/ contraction";
arrAnsChoices[1] = "nominal / peak / trough";
arrAnsChoices[2] = "real / expansion / contraction";
arrAnsChoices[3] = "real / peak / trough";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448786;
arrAnsIDs[1] = 448787;
arrAnsIDs[2] = 448788;
arrAnsIDs[3] = 448789;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The value of an investment return is affected by the value of money. As such, an investment’s rate of return in a particular year can be adjusted by the rate of inflation in that year. The relationship between the nominal rate of return, the inflation rate, and the real rate of return, is expressed in the formula, solving for the nominal rate of return: Real rate of return + Inflation rate = Nominal rate of return.</p><p class=\"explanations\">The business cycle is a recurring pattern of fluctuations in economic activity that is characterized as expansion, peak, contraction, and trough. During the expansion phase, security valuations usually rise as businesses profit from increases in economic activity. The market values of some assets—such as stocks and real estate—can appreciate significantly, which makes them more appealing to investors. During the contraction phase, the weakening economy usually prompts investors to seek out conservative investments, such as bonds and dividend-paying stocks.</p><p class=\"explanations\"><b>Learning Objective: 4B. Describe how certain factors—such as prices, market interest rates, inflation, and the stages of the business cycle—can affect investment returns.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is correct to say that the nominal rate of return does not adjust for inflation or other factors. However, the economic growth rate stabilizes and then changes direction at the peak and trough phases. Growth begins to <b>fall after the peak phase</b> and begins to <b>rise after the trough phase</b>.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is correct to say that economic activity grows during the expansion phase and shrinks during the contraction phase of the business cycle. However, the real rate of return <b>adjusts</b> for inflation and other factors.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\"></p><p class=\"explanations\">The real rate of return is the rate of return on an investment <b>after</b> adjustment for inflation and other factors. In addition, economic growth begins to <b>fall after the peak phase</b> and begins to <b>rise after the trough phase</b>.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_033'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_034';
objQuestion.questionID = 111041;
objQuestion.item = 'LOMA_357_PPQ2019_034';
objQuestion.primaryLO = '4C';
objQuestion.textref = 'c. 4, pp. 14-15';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '4C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Cora Lamar invested a principal amount of $40,000. At the end of the year, her investment earned a $1,200 return. This information indicates that the rate of return on Ms.&nbsp;Lamar’s investment is equal to</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "3.0%";
arrAnsChoices[1] = "3.3%";
arrAnsChoices[2] = "4.0%";
arrAnsChoices[3] = "12.0%";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448790;
arrAnsIDs[1] = 448791;
arrAnsIDs[2] = 448792;
arrAnsIDs[3] = 448793;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">An investment return for a specific period can be expressed as a monetary amount or a percentage. To calculate the rate of return, which is expressed as a percentage, the formula is: Amount of return ÷ Principal amount × 100 = Rate of return. In this situation, the rate of return on Ms.&nbsp;Lamar’s investment is calculated as $1,200 ÷ $40,000 × 100 = 3.0%.</p><p class=\"explanations\"><b>Learning Objective: 4C. Define and describe different ways that investors can measure investment returns.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">An investment return for a specific period can be expressed as a monetary amount or a percentage. To calculate the rate of return, which is expressed as a percentage, the formula is: Amount of return ÷ Principal amount × 100 = Rate of return. In this situation, the rate of return on Ms.&nbsp;Lamar’s investment is calculated as $1,200 ÷ $40,000 × 100 = 3.0%.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">An investment return for a specific period can be expressed as a monetary amount or a percentage. To calculate the rate of return, which is expressed as a percentage, the formula is: Amount of return ÷ Principal amount × 100 = Rate of return. In this situation, the rate of return on Ms.&nbsp;Lamar’s investment is calculated as $1,200 ÷ $40,000 × 100 = 3.0%.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">An investment return for a specific period can be expressed as a monetary amount or a percentage. To calculate the rate of return, which is expressed as a percentage, the formula is: Amount of return ÷ Principal amount × 100 = Rate of return. In this situation, the rate of return on Ms.&nbsp;Lamar’s investment is calculated as $1,200 ÷ $40,000 × 100 = 3.0%.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_034'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_035';
objQuestion.questionID = 111042;
objQuestion.item = 'LOMA_357_PPQ2019_035';
objQuestion.primaryLO = '4C';
objQuestion.textref = 'c. 4, pp. 16-17';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '4C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The required rate of return for an investment is correctly defined as the</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "known investment performance result—expressed as a monetary amount or a percentage rate of return—for a given period";
arrAnsChoices[1] = "annual rate of investment return an investor requires as reasonable compensation for a given level of risk and to satisfy the investor’s objectives";
arrAnsChoices[2] = "estimated future return—expressed as a monetary amount or a percentage rate of return—that an investor anticipates earning from an investment";
arrAnsChoices[3] = "rate of return on the least risky investment opportunity available in the market";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448794;
arrAnsIDs[1] = 448795;
arrAnsIDs[2] = 448796;
arrAnsIDs[3] = 448797;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The <b>historical return </b>is a known investment performance result for a given period. A historical return can be expressed as a monetary amount or a percentage rate of return.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The formula for the required rate of return is Inflation rate + Risk-free rate of return + Risk premium = Required rate of return. Based on their objectives, investors can have different values for required rates of return. For an institutional investor, an organizational value for the required rate of return takes into account the organization’s growth goals and the minimum rate of return needed to sustain the business.</p><p class=\"explanations\">The risk-free rate of return is the rate of return on a “risk-free” investment—that is, the least risky investment opportunity available in the market.</p><p class=\"explanations\">The risk premium is the portion of the rate of return in excess of the risk-free rate of return that is required to compensate an investor for taking the extra risk associated with a specific type of investment. The risk premium for an equity security typically is higher than the risk premium for a debt security.</p><p class=\"explanations\"><b>Learning Objective: 4C. Define and describe different ways that investors can measure investment returns.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The <b>expected return</b> is the estimated future return—expressed as a monetary amount or a percentage rate of return—that an investor anticipates earning from an investment.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The <b>risk-free rate </b>is the rate of return on the least risky investment opportunity available in the market.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_035'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_036';
objQuestion.questionID = 111043;
objQuestion.item = 'LOMA_357_PPQ2019_036';
objQuestion.primaryLO = '4C';
objQuestion.textref = 'c. 4, pp. 18-19';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '4C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">An investment has the following annual rates of return over a holding period of three years:</p><table class=\"tbexam\" align=\"center\"><tr><td style=\"vertical-align: middle; text-align: left; background-color: transparent; border: none;\"></td><td style=\"vertical-align: top; text-align: center; background-color: #DCDCDC;\"><b>Year 1</b></td><td style=\"vertical-align: top; text-align: center; background-color: #DCDCDC;\"><b>Year 2</b></td><td style=\"vertical-align: top; text-align: center; background-color: #DCDCDC;\"><b>Year 3</b></td></tr><tr><td style=\"vertical-align: top; text-align: left;\">Yearly Return</td><td style=\"vertical-align: top; text-align: center;\">3%</td><td style=\"vertical-align: top; text-align: center;\">4%</td><td style=\"vertical-align: top; text-align: center;\">5%</td></tr></table><p class=\"stem\">This information indicates that, over three years, the arithmetic mean annual return of this investment is equal to</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "3.0%";
arrAnsChoices[1] = "4.0%";
arrAnsChoices[2] = "5.0%";
arrAnsChoices[3] = "12.0%";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448798;
arrAnsIDs[1] = 448799;
arrAnsIDs[2] = 448800;
arrAnsIDs[3] = 448801;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The arithmetic mean annual return is the average return—usually expressed as a percentage rate of return—of a series of annual investment returns during a multiyear holding period. The formula for calculating arithmetic mean annual return for an investment is (Year 1 return + Year 2 return + ... Final year<i> </i>return) ÷ Total number of years = Arithmetic mean annual return. In this situation, the arithmetic mean annual return for the investment over three years is (3% + 4% + 5%) ÷ 3 = 4%.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The arithmetic mean annual return is the average return—usually expressed as a percentage rate of return—of a series of annual investment returns during a multiyear holding period. The formula for calculating arithmetic mean annual return for an investment is (Year 1 return + Year 2 return + ... Final year<i> </i>return) ÷ Total number of years = Arithmetic mean annual return. In this situation, the arithmetic mean annual return for the investment over three years is (3% + 4% + 5%) ÷ 3 = 4%.</p><p class=\"explanations\">The arithmetic mean annual return can be misleading because the calculated value implies a steady rate of return for each year. This simple calculation does not indicate the variability of returns in relation to the calculated average. Thus, the measure is not commonly used in investment performance calculations.</p><p class=\"explanations\"><b>Learning Objective: 4C. Define and describe different ways that investors can measure investment returns.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The arithmetic mean annual return is the average return—usually expressed as a percentage rate of return—of a series of annual investment returns during a multiyear holding period. The formula for calculating arithmetic mean annual return for an investment is (Year 1 return + Year 2 return + ... Final year<i> </i>return) ÷ Total number of years = Arithmetic mean annual return. In this situation, the arithmetic mean annual return for the investment over three years is (3% + 4% + 5%) ÷ 3 = 4%.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The arithmetic mean annual return is the average return—usually expressed as a percentage rate of return—of a series of annual investment returns during a multiyear holding period. The formula for calculating arithmetic mean annual return for an investment is (Year 1 return + Year 2 return + ... Final year<i> </i>return) ÷ Total number of years = Arithmetic mean annual return. In this situation, the arithmetic mean annual return for the investment over three years is (3% + 4% + 5%) ÷ 3 = 4%.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_036'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_037';
objQuestion.questionID = 111044;
objQuestion.item = 'LOMA_357_PPQ2019_037';
objQuestion.primaryLO = '4D';
objQuestion.textref = 'c. 4, pp. 21-22';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '4D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">To measure investment volatility, investment professionals refer to the standard deviation of asset prices over time. The higher the standard deviation of the historical returns on an asset, the (<b>less</b> / <b>more</b>) an investor can expect the actual return for a given year to vary from the mean historical return, and, therefore, the (<b>less</b> / <b>greater</b>) the risk that an asset’s future returns will not be consistent with the average returns it has earned in the past.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "less / less";
arrAnsChoices[1] = "less / greater";
arrAnsChoices[2] = "more / less";
arrAnsChoices[3] = "more / greater";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448802;
arrAnsIDs[1] = 448803;
arrAnsIDs[2] = 448804;
arrAnsIDs[3] = 448805;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The higher the standard deviation of the historical returns on an asset, the <b>more</b> an investor can expect the actual return for a given year to vary from the mean historical return. Also, a higher standard deviation indicates a <b>greater</b> risk that an asset’s future returns will not be consistent with the average returns it has earned in the past.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is correct to say that a higher standard deviation indicates a greater risk that an asset’s future returns will not be consistent with the average returns it has earned in the past. However, the higher the standard deviation of the historical returns on an asset, the <b>more</b> an investor can expect the actual return for a given year to vary from the mean historical return.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is correct to say that, the higher the standard deviation of the historical returns on an asset, the more an investor can expect the actual return for a given year to vary from the mean historical return. However, a higher standard deviation indicates a <b>greater</b> risk that an asset’s future returns will not be consistent with the average returns it has earned in the past.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Volatility introduces investment risk in the form of uncertainty. Asset volatility means that an investor might not receive the average return in a given year, although the investor does receive the potential to earn above-average returns in any given year. For investment returns, the preferred measure of volatility is standard deviation.</p><p class=\"explanations\">Investors can compare the volatility and riskiness of two investments by comparing their standard deviations. Using historical return data for each investment, investors can (1) find the mean of a data set consisting of multiple annual rates of return during a specific time period and (2) calculate the standard deviation for the data set. Investors also use standard deviation to create a range of expected return values for a given investment by (1) subtracting the standard deviation from the mean to get the lower end of the range and (2) adding the standard deviation from the mean to get the upper end of the range.</p><p class=\"explanations\"><b>Learning Objective: 4D. Explain how investors use volatility and standard deviation to estimate investment risks and returns.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_037'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_038';
objQuestion.questionID = 111045;
objQuestion.item = 'LOMA_357_PPQ2019_038';
objQuestion.primaryLO = '4D';
objQuestion.textref = 'c. 4, pp. 22-24';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '4D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">An investor calculated the range of expected returns and the confidence interval for a group of large U.S. company stocks over a 20-year period. The stocks had a mean historical return of 9% and a standard deviation of returns of 8%. Last year, the stocks had an annual rate of return of 5%. Select the answer choice that correctly indicates the range of expected rates of return and the confidence interval for these stocks, plus or minus <i>one</i> standard deviation from the mean.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[-1] = "<u>Range: expected rates of return</u></div><div class=\"anshead\"><u>Confidence interval</u>";
arrAnsChoices[0] = "–3% to 13%</div><div class=\"anscell\" onclick=\"recordAns(1);\">67%";
arrAnsChoices[1] = "–3% to 13%</div><div class=\"anscell\" onclick=\"recordAns(2);\">95%";
arrAnsChoices[2] = "1% to 17%</div><div class=\"anscell\" onclick=\"recordAns(3);\">67%";
arrAnsChoices[3] = "1% to 17%</div><div class=\"anscell\" onclick=\"recordAns(4);\">95%";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448807;
arrAnsIDs[1] = 448808;
arrAnsIDs[2] = 448809;
arrAnsIDs[3] = 448810;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is correct to say that, when the relationship between the number of standard deviations and the confidence interval is one standard deviation, the confidence interval is approximately 67%. However, in this situation, the range of expected returns is from <b>1% to 17%</b>, calculated as (9% – 8%) to (9% + 8%).</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">In this situation, the range of expected returns is from <b>1% to 17%</b>, calculated as (9% – 8%) to (9%&nbsp;+&nbsp;8%). Also, when the relationship between the number of standard deviations and the confidence interval is one standard deviation, the confidence interval is approximately <b>67%</b>.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Typically, if investors know the mean and standard deviation of historical returns, they can calculate ranges of expected returns. When investors can attach a confidence estimate to the range of estimated outcomes, the range is called a confidence interval. A confidence interval signifies the level of confidence that an investor has that an actual return will fall within the range of expected returns for that measure of deviation.</p><p class=\"explanations\">In a normal distribution, the relationship between the number of standard deviations and the confidence interval is as follows: at one standard deviation, the confidence interval is approximately 67%; at two standard deviations, the confidence interval is approximately 95%; and at three standard deviations, the confidence interval is approximately 99%. For example, at one standard deviation, about 67% of actual returns are expected to fall within the range of the mean minus one standard deviation and the mean plus one standard deviation.</p><p class=\"explanations\"><b>Learning Objective: 4D. Explain how investors use volatility and standard deviation to estimate investment risks and returns.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is correct to say that, in this situation, the range of expected returns is from 1% to 17%, calculated as (9% – 8%) to (9% + 8%). However, when the relationship between the number of standard deviations and the confidence interval is one standard deviation, the confidence interval is approximately <b>67%</b>.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_038'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_039';
objQuestion.questionID = 111046;
objQuestion.item = 'LOMA_357_PPQ2019_039';
objQuestion.primaryLO = '4D';
objQuestion.textref = 'c. 4, pp. 23-24';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '4D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Tail risk is one risk concept in the normal curve for the historical returns of an investment. The type of risk signified by tail risks include</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "low-probability and low-impact occurrences";
arrAnsChoices[1] = "low-probability but high-impact occurrences";
arrAnsChoices[2] = "high-probability but low-impact occurrences";
arrAnsChoices[3] = "high-probability and high-impact occurrences";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448811;
arrAnsIDs[1] = 448812;
arrAnsIDs[2] = 448813;
arrAnsIDs[3] = 448814;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Tail risks generally signify low-probability but <b>high-impact</b> occurrences.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">In a normal distribution curve, the areas containing values that are more than three standard distributions from the mean are called tails. Because three standard deviations from the mean encompasses approximately 99% of the estimated outcomes in a normal distribution, a low probability exists that a return will fall outside the expected range of outcomes.</p><p class=\"explanations\">Such extreme return outcomes are tail risks, which generally signify risks of low-probability but high-impact occurrences. Return values that are far above the mean—indicating huge gains—are welcome, while values that are far less than the mean—indicating huge losses—are undesirable. Thus, tail risks have the potential to result in large financial losses on investments.</p><p class=\"explanations\"><b>Learning Objective: 4D. Explain how investors use volatility and standard deviation to estimate investment risks and returns.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Tail risks generally signify <b>low-probability</b> but<b> high-impact occurrences</b>.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Tail risks generally signify <b>low-probability</b> and high-impact occurrences.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_039'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_040';
objQuestion.questionID = 111047;
objQuestion.item = 'LOMA_357_PPQ2019_040';
objQuestion.primaryLO = '4E';
objQuestion.textref = 'c. 4, pp. 25-26';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '4E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">In investing, the risk-return trade-off is the relationship between risk and return in which higher risks offer the possibility of higher returns and lower risks tend to produce lower returns. All other factors remaining equal, one investment that generally has <i>lower</i> risks associated with <i>lower</i> expected returns is</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "a loan that is unsecured by collateral rather than a loan that is secured by collateral";
arrAnsChoices[1] = "an asset with a steady market value rather than an asset with a volatile market value";
arrAnsChoices[2] = "a long-term asset rather than a short-term asset";
arrAnsChoices[3] = "a low-rated bond rather than a highly-rated bond";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448815;
arrAnsIDs[1] = 448816;
arrAnsIDs[2] = 448817;
arrAnsIDs[3] = 448818;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A loan that is unsecured by collateral typically has <b>higher</b> risks associated with <b>higher</b> expected returns.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Risk-return trade-off decisions involve exchanging safety for the possibility of larger returns. Generally, the greater the risk associated with an investment, the greater the expected return. Characteristics that indicate higher risk associated with higher expected returns for an investment include lending to a borrower with a lower credit rating, and owning a long-term asset, a bond with a low rating, a loan that is unsecured by collateral, an unsecured loan, or owning an asset that is difficult to sell, has a volatile market value, or pays returns in a currency other than the investor’s domestic currency.</p><p class=\"explanations\"><b>Learning Objective: 4E. Explain the risk-return trade-off for investors, and describe the types of trade-off decisions that insurance companies make.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A long-term asset typically has <b>higher</b> risks associated with <b>higher</b> expected returns.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A low-rated bond typically has <b>higher</b> risks associated with <b>higher</b> expected returns.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_040'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_041';
objQuestion.questionID = 111048;
objQuestion.item = 'LOMA_357_PPQ2019_041';
objQuestion.primaryLO = '4F';
objQuestion.textref = 'c. 4, pp. 26-28, 34';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '4F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">In the context of portfolio management, investment risks can be categorized into two types of risks: specific risks and systematic risks. Select the answer choice that correctly identifies an example of specific risk and an example of systematic risk.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[-1] = "<u>Specific risk</u></div><div class=\"anshead\"><u>Systematic risk</u>";
arrAnsChoices[0] = "credit risk</div><div class=\"anscell\" onclick=\"recordAns(1);\">liquidity risk";
arrAnsChoices[1] = "currency risk</div><div class=\"anscell\" onclick=\"recordAns(2);\">inflation";
arrAnsChoices[2] = "inflation</div><div class=\"anscell\" onclick=\"recordAns(3);\">credit risk";
arrAnsChoices[3] = "liquidity risk</div><div class=\"anscell\" onclick=\"recordAns(4);\">currency risk";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448820;
arrAnsIDs[1] = 448821;
arrAnsIDs[2] = 448822;
arrAnsIDs[3] = 448823;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Credit risk and liquidity risk are examples of <b>specific</b> <b>risks</b>.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The difference between systematic risk and specific risk hinges on whether the relevant risk can be reduced in an investment portfolio through diversification. A systematic risk—also known as a nondiversifiable risk or market risk—has a broad, similar effect on all elements in an economic system and cannot be eliminated through diversification. Within a given market, every investment is exposed to a systematic risk. Systematic risks include asset bubbles, monetary policy changes, inflation, business cycles, and natural disasters.</p><p class=\"explanations\">A specific risk—also known as a diversifiable risk or unsystematic risk—only affects certain assets or asset classes, and can be substantially reduced by diversification. A specific risk is associated with an individual company or industry, but not an entire market. Specific risks include interest-rate risk, credit risk, real estate risk, liquidity risk, and currency risk.</p><p class=\"explanations\"><b>Learning Objective: 4F. Define systematic risk and specific risk and explain how investors can reduce each type of risk in their investment portfolios.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Inflation is an example of a <b>systematic risk</b>. Also, credit risk is an example of a <b>specific risk</b>.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Liquidity risk and currency risk are examples of <b>specific</b> <b>risks</b>.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_041'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_042';
objQuestion.questionID = 111049;
objQuestion.item = 'LOMA_357_PPQ2019_042';
objQuestion.primaryLO = '4F';
objQuestion.textref = 'c. 4, pp. 26-29';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '4F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about systematic risks and specific risks. Select the answer choice containing the correct statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A systematic crisis is a series of adverse events occurring in a significant number of financial institutions or markets that has a catastrophic effect.";
arrAnsChoices[1] = "One benefit of portfolio diversification is that the impact of the specific risks associated with a single asset is reduced as more assets are included.";
arrAnsChoices[2] = "Systematic risk can be substantially reduced by diversification.";
arrAnsChoices[3] = "Estimates of expected investment returns incorporate a risk premium for specific risks but not systematic risks.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448824;
arrAnsIDs[1] = 448825;
arrAnsIDs[2] = 448826;
arrAnsIDs[3] = 448827;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A systemic risk is a risk that (1) affects securities markets, banking systems, and currencies and (2) can result in a <b>systemic crisis</b>, which is a series of adverse events occurring in a significant number of financial institutions or markets that has a catastrophic effect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Systemic risks are related to systematic risks, but the terms are not interchangeable. A systemic risk is a risk that (1) affects securities markets, banking systems, and currencies and (2) can result in a systemic crisis, which is a series of adverse events occurring in a significant number of financial institutions or markets that has a catastrophic effect.</p><p class=\"explanations\">A systematic risk can affect an entire market, but a systemic risk threatens to take down an entire interconnected financial system. Thus, only a particular type of systematic risk—such as an asset bubble in real estate prices—can also be a systemic risk.</p><p class=\"explanations\">The “price of admission” to participate in a given market is exposure to its systematic risks; thus, investors need risk premiums as incentives to participate in markets. However, because well-managed investment portfolios mitigate exposure to specific risks, investors do not require risk premiums to invest in assets that are subject to those risks.</p><p class=\"explanations\"><b>Learning Objective: 4F. Define systematic risk and specific risk and explain how investors can reduce each type of risk in their investment portfolios.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Systematic risk has a broad, similar effect on all elements in an economic system and <b>cannot</b> be eliminated through diversification. Within a given market, every investment is exposed to a systematic risk.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Estimates of expected investment returns incorporate a risk premium for systematic risks but <b>not</b> specific risks. Because well-managed investment portfolios mitigate exposure to specific risks, investors do <b>not</b> require risk premiums to invest in assets that are subject to those risks.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_042'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_043';
objQuestion.questionID = 111050;
objQuestion.item = 'LOMA_357_PPQ2019_043';
objQuestion.primaryLO = '4F';
objQuestion.textref = 'c. 4, pp. 29-30';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '4F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Interest-rate risk is the risk that the market value of an investment will change due to a change in nominal market interest rates. For example, as market interest rates increase, the market value of an existing bond generally (<b>decreases</b> / <b>increases</b>), and the market value of an existing mortgage generally (<b>decreases</b> /<b> increases</b>).</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "decreases / decreases";
arrAnsChoices[1] = "decreases / increases";
arrAnsChoices[2] = "increases / decreases";
arrAnsChoices[3] = "increases / increases";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448828;
arrAnsIDs[1] = 448829;
arrAnsIDs[2] = 448830;
arrAnsIDs[3] = 448831;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">In general, for interest-bearing investments—such as bonds and mortgage loans—the market value of an existing investment will decrease as market interest rates increase, and increase as market interest rates decrease. For instance, in rising interest-rate environments, current issues of bonds typically fall in market value because new issues will be offered at higher coupon rates, which are more attractive to investors. In such cases, an investor can hold existing bonds to maturity, rather than selling them at unfavorable market values. Note that life insurance companies generally purchase bonds and other debt securities with the intention of holding them to maturity.</p><p class=\"explanations\"><b>Learning Objective: 4F. Define systematic risk and specific risk and explain how investors can reduce each type of risk in their investment portfolios.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is correct to say that, as market interest rates increase, the market value of an existing bond generally decreases. However, as market interest rates increase, the market value of an existing mortgage generally <b>decreases</b>.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is correct to say that, as market interest rates increase, the market value of an existing mortgage generally decreases. However, as market interest rates increase, the market value of an existing bond generally <b>decreases</b>.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">As market interest rates increase, the market value of <b>both</b> existing bonds and existing mortgages generally <b>decreases</b>.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_043'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_044';
objQuestion.questionID = 111051;
objQuestion.item = 'LOMA_357_PPQ2019_044';
objQuestion.primaryLO = '4G';
objQuestion.textref = 'c. 4, pp. 30-31';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '4G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Duration is a statistic that measures the interest-rate sensitivity of an interest-bearing security. The following statements are about duration. Select the answer choice containing the correct statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Investors calculate duration of an interest-bearing security only through measuring and emphasizing the security’s cash flows.";
arrAnsChoices[1] = "Generally, as the value of duration increases, interest-rate risk decreases.";
arrAnsChoices[2] = "Higher coupon rates and shorter terms to maturity are typical characteristics of bonds with greater sensitivity to interest-rate changes.";
arrAnsChoices[3] = "If two bonds are similar but have different durations, then the one with the lower duration is less risky and has less potential for price appreciation.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448832;
arrAnsIDs[1] = 448833;
arrAnsIDs[2] = 448834;
arrAnsIDs[3] = 448835;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Investors can calculate duration of an interest-bearing security in <b>multiple</b> ways, with different calculations emphasizing cash flows or price changes.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">As the value of duration increases, interest-rate risk <b>increases</b>.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Bonds with <b>lower</b> coupon rates generally take longer to generate cash flows that cover the original cost of purchase than bonds with higher coupon rates. Cash flows from bonds with <b>longer</b> terms to maturity generally take more time to cover the investor’s original cost than those of bonds with shorter terms to maturity. Bonds with greater sensitivity to interest-rate changes experience greater market value volatility.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Investors can calculate duration in multiple ways, with different calculations emphasizing cash flows or price changes. A duration statistic of <i>n</i> years indicates that, for a change of 1 percent in interest rates, the price or market value of a security will change by approximately <i>n</i> percent in the opposite direction. Thus, as the value of duration increases, interest-rate risk increases.</p><p class=\"explanations\"><b>Learning Objective: 4G. Explain how interest-rate risk affects bond investments, interpret interest-rate sensitivity using bond duration, and explain how market interest-rate changes can result in margin compression or margin expansion for insurers.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_044'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_045';
objQuestion.questionID = 111052;
objQuestion.item = 'LOMA_357_PPQ2019_045';
objQuestion.primaryLO = '4G';
objQuestion.textref = 'c. 4, pp. 30-31';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '4G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">If a security’s duration statistic is 7 years, then, for a change of 1 percent in interest rates, the market value of the security will change by approximately</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "1 percent in the same direction";
arrAnsChoices[1] = "1 percent in the opposite direction";
arrAnsChoices[2] = "7 percent in the same direction";
arrAnsChoices[3] = "7 percent in the opposite direction";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448836;
arrAnsIDs[1] = 448837;
arrAnsIDs[2] = 448838;
arrAnsIDs[3] = 448839;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A duration statistic of <i>n</i> years indicates that, for a change of 1 percent in interest rates, the price or market value of a security will change by approximately <i>n</i> percent in the opposite direction. In this situation, <i>n</i> = 7 years; therefore, for a change in 1 percent in interest rates, the market value of the security will change by approximately <b>7 percent </b>in the<b> opposite </b>direction.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A duration statistic of <i>n</i> years indicates that, for a change of 1 percent in interest rates, the price or market value of a security will change by approximately <i>n</i> percent in the opposite direction. In this situation, <i>n</i> = 7 years; therefore, for a change in 1 percent in interest rates, the market value of the security will change by approximately <b>7 percent</b> in the opposite direction.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A duration statistic of <i>n</i> years indicates that, for a change of 1 percent in interest rates, the price or market value of a security will change by approximately <i>n</i> percent in the opposite direction. In this situation, <i>n</i> = 7 years; therefore, for a change in 1 percent in interest rates, the market value of the security will change by approximately 7 percent in the <b>opposite</b> direction.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A duration statistic of <i>n</i> years indicates that, for a change of 1 percent in interest rates, the price or market value of a security will change by approximately <i>n</i> percent in the opposite direction. In this situation, <i>n</i> = 7 years; therefore, for a change in 1 percent in interest rates, the market value of the security will change by approximately 7 percent in the opposite direction.</p><p class=\"explanations\"><b>Learning Objective: 4G. Explain how interest-rate risk affects bond investments, interpret interest-rate sensitivity using bond duration, and explain how market interest-rate changes can result in margin compression or margin expansion for insurers.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_045'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_046';
objQuestion.questionID = 111053;
objQuestion.item = 'LOMA_357_PPQ2019_046';
objQuestion.primaryLO = '4G';
objQuestion.textref = 'c. 4, pp. 31-32';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '4G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Changes in market interest rates can have an impact on insurers. If an insurer reduces the interest-crediting rates it pays to customers while continuing to earn a higher overall rate of return on its existing invested assets, the result is known as margin (<b>compression / expansion</b>). The narrowing of an insurer’s interest margin, potentially because of market interest-rate changes, is known as margin (<b>compression / expansion</b>).</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "compression / compression";
arrAnsChoices[1] = "compression / expansion";
arrAnsChoices[2] = "expansion / compression";
arrAnsChoices[3] = "expansion / expansion";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448840;
arrAnsIDs[1] = 448841;
arrAnsIDs[2] = 448842;
arrAnsIDs[3] = 448843;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is correct to say that the narrowing of an insurer’s interest margin, potentially because of market interest-rate changes, is known as margin compression. However, <b>margin</b> <b>expansion</b> occurs if the insurer reduces the interest-crediting rates it pays to customers while continuing to earn a higher overall rate of return on its existing invested assets.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\"><b>Margin</b> <b>expansion</b> occurs if the insurer reduces the interest-crediting rates it pays to customers while continuing to earn a higher overall rate of return on its existing invested assets. Also, the narrowing of an insurer’s interest margin, potentially because of market interest-rate changes, is known as <b>margin</b> <b>compression</b>.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">In a period of increasing market interest rates, insurance companies can experience margin compression, which refers to the narrowing of an insurer’s interest margin. Typically, when market interest rates are rising, policyowners immediately demand a higher crediting rate on their accounts. If the company immediately pays the new higher rate on its products, the company’s interest margin will narrow.</p><p class=\"explanations\">If the company does not pay the new higher rate, the company will likely lose customers and business from financial professionals. To minimize the risk of margin compression, insurers typically try to issue products that limit customer withdrawal rights during early years. Margin compression also comes into play during periods of decreasing market interest rates if asset maturities are not properly aligned with the average life of the liabilities.</p><p class=\"explanations\">Margin expansion refers to an increase in an insurer’s interest margin, potentially because of market interest-rate changes. Margin expansion can also occur when a company experiences an increase in the market value of its existing assets after market interest rates fall.</p><p class=\"explanations\"><b>Learning Objective: 4G. Explain how interest-rate risk affects bond investments, interpret interest-rate sensitivity using bond duration, and explain how market interest-rate changes can result in margin compression or margin expansion for insurers.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is correct to say that margin expansion occurs if the insurer reduces the interest-crediting rates it pays to customers while continuing to earn a higher overall rate of return on its existing invested assets. However, the narrowing of an insurer’s interest margin, potentially because of market interest-rate changes, is known as <b>margin</b> <b>compression</b>.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_046'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_047';
objQuestion.questionID = 111054;
objQuestion.item = 'LOMA_357_PPQ2019_047';
objQuestion.primaryLO = '4H';
objQuestion.textref = 'c. 4, pp. 32-33';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '4H';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about credit risk. Three statements are true, and one statement is false. Select the answer choice containing the <B>FALSE</B> statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Default risk affects all types of debt securities, and it affects corporate equity securities.";
arrAnsChoices[1] = "A credit downgrade does not affect payments of principal or interest to investors.";
arrAnsChoices[2] = "The main threat of credit risk is that, when an investment goes into default or is downgraded, its market value also decreases.";
arrAnsChoices[3] = "Typically, sovereign debt is the most risky investment one can make in a given economy.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448844;
arrAnsIDs[1] = 448845;
arrAnsIDs[2] = 448846;
arrAnsIDs[3] = 448847;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response. Default risk affects all debt securities and corporate equity securities, which lose substantial market value if the issuing company defaults on its debt obligations and becomes insolvent.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response. Market value decreases usually accompany credit downgrades. However, a credit downgrade does not affect payments of principal or interest to investors.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response. As part of their evaluations, credit analysts assess the risk of default or downgrade by issuers of debt securities. Typically, defaults cause larger market value drops than downgrades.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">This statement is false; therefore, it is the correct response. Default risk and downgrade risk are relevant credit risks to investors. Typically, sovereign debt is the least risky investment one can make in a given economy, but it still carries risks. When analysts evaluate a sovereign credit risk, the sovereign government’s ability and willingness to repay borrowed money are both important factors to consider.</p><p class=\"explanations\"><b>Learning Objective: 4H. Define some of the specific risks that are particularly important to insurance company investments.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_047'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_048';
objQuestion.questionID = 111055;
objQuestion.item = 'LOMA_357_PPQ2019_048';
objQuestion.primaryLO = '4H';
objQuestion.textref = 'c. 4, p. 33';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '4H';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statement(s) can correctly be made about real estate risk:</p><ol type=\"A\" class=\"combo\"><li>In the context of the loan-to-value (LTV) ratio, the risk of mortgage default typically increases as the value of the property decreases.</li><li>The higher the debt service coverage ratio, the easier the borrower is able to meet its mortgage loan obligations.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448848;
arrAnsIDs[1] = 448849;
arrAnsIDs[2] = 448850;
arrAnsIDs[3] = 448851;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Statement A is correct. Exposure to real estate risk can come from directly owning real estate properties or from owning assets—such as mortgages and mortgage-backed securities—whose value depends on real estate property values.</p><p class=\"explanations\">Statement B is correct. For mortgage analysis, investors consider the LTV ratio and the debt service coverage ratio.</p><p class=\"explanations\"><b>Learning Objective: 4H. Define some of the specific risks that are particularly important to insurance company investments.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct; however, Statement B is also correct.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is correct; however, Statement A is also correct.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_048'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_049';
objQuestion.questionID = 111056;
objQuestion.item = 'LOMA_357_PPQ2019_049';
objQuestion.primaryLO = '4H';
objQuestion.textref = 'c. 4, pp. 33-34';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '4H';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">For this question, if answer choices (1) through (3) are all correct, select answer choice (4). Otherwise, select the one correct answer choice.</p><p class=\"stem\">In the context of investing, liquidity risk is the risk that an asset might not be easily sold for its underlying value. An investment is likely to have limited liquidity if it is</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "traded privately or in OTC markets instead of on public exchanges";
arrAnsChoices[1] = "issued in relatively small outstanding quantities";
arrAnsChoices[2] = "subject to regulatory or policy restrictions that limit institutional investor involvement";
arrAnsChoices[3] = "all of the above";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448852;
arrAnsIDs[1] = 448853;
arrAnsIDs[2] = 448854;
arrAnsIDs[3] = 448855;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">An investment is likely to have limited liquidity if it is not traded on public exchanges. Liquidity risk can also arise from a lack of buyers or the structure of the investment—as is often the case in alternative investments. An investment also is likely to have limited liquidity if it contains restrictions that limit the frequency or timing of ownership transactions.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">An investment is likely to have limited liquidity if it is issued in relatively small outstanding quantities. Liquidity risk can also arise from a lack of buyers, lack of secondary markets, or the structure of the investment—as is often the case in alternative investments. An investment also is likely to have limited liquidity if it contains restrictions that limit the frequency or timing of ownership transactions.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">An investment is likely to have limited liquidity if it is subject to regulatory or policy restrictions that limit institutional investor involvement, such as the frequency or timing of ownership transactions. Liquidity risk also can arise from a lack of buyers, lack of secondary markets, or the structure of the investment—as is often the case in alternative investments.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Liquidity risk can arise from a lack of buyers, lack of secondary markets, or the structure of the investment—as is often the case in alternative investments. An investment also is likely to have limited liquidity if it contains restrictions that limit the frequency or timing of ownership transactions.</p><p class=\"explanations\"><b>Learning Objective: 4H. Define some of the specific risks that are particularly important to insurance company investments.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_049'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['4A'] = "4A. Explain how investors earn investment returns from capital gains and income payments.";
arrlotext['4B'] = "4B. Describe how certain factors—such as prices, market interest rates, inflation, and the stages of the business cycle—can affect investment returns.";
arrlotext['4C'] = "4C. Define and describe different ways that investors can measure investment returns.";
arrlotext['4D'] = "4D. Explain how investors use volatility and standard deviation to estimate investment risks and returns.";
arrlotext['4E'] = "4E. Explain the risk-return trade-off for investors, and describe the types of trade-off decisions that insurance companies make.";
arrlotext['4F'] = "4F. Define systematic risk and specific risk and explain how investors can reduce each type of risk in their investment portfolios.";
arrlotext['4G'] = "4G. Explain how interest-rate risk affects bond investments, interpret interest-rate sensitivity using bond duration, and explain how market interest-rate changes can result in margin compression or margin expansion for insurers.";
arrlotext['4H'] = "4H. Define some of the specific risks that are particularly important to insurance company investments.";
