var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2020';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 357 Practice Questions, Chapter 3";
var coursename = 'LOMA 357';
var modulenumber = 1;
var title = "LOMA_357_PPQ2019_0_3";
var intNumPools = 1;
var numQ = 12;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Institutional Investing: Principles and Practices (2019)";
arrNumChap[0] = 1;
var thisChap = '3';

objPool = new Object(); 
objPool.intSelectCount = 12;
objPool.formID = 2139;
objPool.formName = 'PPQ2019_0_3';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_357_PQ_018';
arrPoolQuestions[1] = 'LOMA_357_PQ_019';
arrPoolQuestions[2] = 'LOMA_357_PQ_020';
arrPoolQuestions[3] = 'LOMA_357_PQ_021';
arrPoolQuestions[4] = 'LOMA_357_PQ_022';
arrPoolQuestions[5] = 'LOMA_357_PQ_023';
arrPoolQuestions[6] = 'LOMA_357_PQ_024';
arrPoolQuestions[7] = 'LOMA_357_PQ_025';
arrPoolQuestions[8] = 'LOMA_357_PQ_026';
arrPoolQuestions[9] = 'LOMA_357_PQ_027';
arrPoolQuestions[10] = 'LOMA_357_PQ_028';
arrPoolQuestions[11] = 'LOMA_357_PQ_029';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_018';
objQuestion.questionID = 111025;
objQuestion.item = 'LOMA_357_PPQ2019_018';
objQuestion.primaryLO = '3A';
objQuestion.textref = 'c. 3, pp. 3-5';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">A loan originator created a special purpose entity (SPE), which purchased a package of loans to be securitized. As part of the credit enhancement process to securitize the debt, the SPE divided the securities into several ownership classes, known as tranches—the AAA debt tranche, AA debt tranche, A debt tranche, and the equity tranche—and then issued and sold the tranches to institutional investors. With regard to the order of payment priority to investors, the <I>AAA </I>debt tranche most likely would pay AAA tranche investors</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "first";
arrAnsChoices[1] = "second";
arrAnsChoices[2] = "third";
arrAnsChoices[3] = "last";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448726;
arrAnsIDs[1] = 448727;
arrAnsIDs[2] = 448728;
arrAnsIDs[3] = 448729;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Most securitized debt has four tranches, in order of seniority: the AAA debt tranche, AA debt tranche, A debt tranche, and the equity tranche.</p><p class=\"explanations\">The AAA debt tranche is the most senior tranche, meaning it has the highest claim priority on the debt pool’s cash flows. It is the most creditworthy tranche, the first to collect payments from borrowers, and the first to make payments to investors. For these reasons, the interest rate for this tranche tends to be lower than on lower tranches of the same security.</p><p class=\"explanations\">The equity tranche is the lowest tranche in a structured security. It has last priority for payment relative to other tranches. The equity tranche is considered the riskiest tranche; however, it also has the potential to earn the highest rate of return because it receives all remaining cash after the other tranches have received their payments.</p><p class=\"explanations\"><b>Learning Objective: 3A. Explain the process of securitization and describe the four types of tranches typically found in structured products.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Most securitized debt has four tranches, in order of seniority: the AAA debt tranche, AA debt tranche, A debt tranche, and the equity tranche. The <b>AA debt tranche</b> is the second-most-senior tranche. It is second to collect payments from borrowers, and second to make payments to investors.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Most securitized debt has four tranches, in order of seniority: the AAA debt tranche, AA debt tranche, A debt tranche, and the equity tranche. The <b>A debt tranche</b>, also known as the subordinated debt tranche, is the third tranche and has the lowest priority of the three debt tranches. It is third to collect payments from borrowers, and third to make payments to investors.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Most securitized debt has four tranches, in order of seniority: the AAA debt tranche, AA debt tranche, A debt tranche, and the equity tranche. The <b>equity tranche</b> is the lowest tranche in a structured security. It has last priority for payment relative to other tranches.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_018'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_019';
objQuestion.questionID = 111026;
objQuestion.item = 'LOMA_357_PPQ2019_019';
objQuestion.primaryLO = '3B';
objQuestion.textref = 'c. 3, p. 5';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">An asset-backed security (ABS) is a type of structured security that can include amortizing and nonamortized loans. Loans for which each repayment reflects both principal and interest are known as <b>(amortizing / nonamortized)</b> loans. A type of ABS that securitizes a pool of corporate debt, such as leveraged loans and other business loans, is known as a <b>(collateralized loan obligation or CLO / collateralized mortgage obligation or CMO)</b>.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "amortizing / CLO";
arrAnsChoices[1] = "amortizing / CMO";
arrAnsChoices[2] = "nonamortized / CLO";
arrAnsChoices[3] = "nonamortized / CMO";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448730;
arrAnsIDs[1] = 448731;
arrAnsIDs[2] = 448732;
arrAnsIDs[3] = 448733;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">An ABS is backed by debt instruments other than real estate mortgages. ABS amortizing loans include auto loans and home loans. Nonamortized loans—for which minimum repayments typically consist only of interest, with repayment of principal required by the end of the loan’s term—include credit card debts and commercial mortgage loans with balloon payments.</p><p class=\"explanations\">A CLO securitizes a pool of corporate debt, such as leveraged loans and other business loans. A leveraged loan, also called a bank loan or a syndicated loan, is a commercial loan characterized by high yields and floating interest rates. Banks give leveraged loans to businesses with a higher risk of default.</p><p class=\"explanations\"><b>Learning Objective: 3B. Distinguish between asset-backed securities, residential mortgage-backed securities, and commercial mortgage-backed securities.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is correct to say that amortizing loans have loan repayments that reflect both principal and interest. However, a CMO is a type of <b>mortgage-backed security (MBS)</b> that is backed by a pool of residential mortgage loans, which are organized into classes based on their risk profile. ABSs are backed by debt instruments <b>other</b> than real estate mortgages.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is correct to say that a CLO is a type of ABS that securitizes a pool of corporate debt. However, a nonamortized loan is an ABS for which minimum repayments typically <b>consist only of interest</b>, with repayment of principal required by the end of the loan’s term.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A CMO is a type of <b>mortgage-backed security (MBS)</b> that is backed by a pool of residential mortgage loans, which are organized into classes based on their risk profile. ABSs are backed by debt instruments <b>other</b> than real estate loans. Also, a nonamortized loan is an ABS for which minimum repayments typically <b>consist only of interest</b>, with repayment of principal required by the end of the loan’s term.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_019'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_020';
objQuestion.questionID = 111027;
objQuestion.item = 'LOMA_357_PPQ2019_020';
objQuestion.primaryLO = '3B';
objQuestion.textref = 'c. 3, pp. 5-6';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Two primary types of residential mortgage-backed securities (MBSs or RMBSs) are agency MBSs and nonagency MBSs. The following statement(s) can correctly be made about agency and nonagency MBSs:</p><ol type=\"A\" class=\"combo\"><li>Agency MBSs are securities based on portfolios of residential mortgages that meet the guidelines as to credit quality, underwriting standards, and other risk factors set by one of several U.S. government agencies.</li><li>The loans held by nonagency MBSs usually have a higher—sometimes, significantly higher—risk of default than those held by agency MBSs.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448734;
arrAnsIDs[1] = 448735;
arrAnsIDs[2] = 448736;
arrAnsIDs[3] = 448737;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Statement A is correct. The three main agencies that participate in the creation of agency MBSs are the Government National Mortgage Association (GNMA), known as Ginnie Mae; the Federal National Mortgage Association (FNMA), known as Fannie Mae; and the Federal Home Loan Mortgage Corporation (FHLMA), known as Freddie Mac.</p><p class=\"explanations\">Ginnie Mae explicitly backs its MBSs with the full faith and credit of the U.S. government. Because Ginnie Mae guarantees the payment of principal and interest, its MBSs are considered safer than other agency MBSs. Although agency MBSs from Fannie Mae and Freddie Mac are less secure than Ginnie Mae MBSs, the U.S. government has signaled that it will not allow the two entities to fail, thus ensuring they will satisfy their obligations to investors. Because of this “implicit guarantee,” investors consider Fannie Mae and Freddie Mac to be government-sponsored enterprises (GSEs).</p><p class=\"explanations\">Statement B is correct. Nonagency MBSs, also known as nonagency mortgage-backed securities or private-label MBSs, are securities based on portfolios of residential mortgages that do not qualify for agency MBSs. Nonagency MBSs are issued by private business entities, such as investment banks, financial institutions, and home builders.</p><p class=\"explanations\"><b>Learning Objective: 3B. Distinguish between asset-backed securities, residential mortgage-backed securities, and commercial mortgage-backed securities.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct; however, Statement B is also correct.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is correct; however, Statement A is also correct.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_020'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_021';
objQuestion.questionID = 111028;
objQuestion.item = 'LOMA_357_PPQ2019_021';
objQuestion.primaryLO = '3B';
objQuestion.textref = 'c. 3, p. 7';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Commercial mortgage-backed securities (CMBSs) are a type of structured mortgage security. Correct statements about CMBSs issued in the United States include</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "that insurers typically hold a larger percentage of CMBSs in their portfolios than MBSs";
arrAnsChoices[1] = "that CMBSs encourage borrowers to prepay both principal and interest";
arrAnsChoices[2] = "that CMBSs can be categorized as either agency or nonagency";
arrAnsChoices[3] = "all of the above";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448738;
arrAnsIDs[1] = 448739;
arrAnsIDs[2] = 448740;
arrAnsIDs[3] = 448741;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Insurance companies are major investors in CMBSs. However, insurers typically hold a <b>larger percentage of MBSs</b> in their portfolios than CMBSs.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">CMBSs issued in the United States have limited prepayment risk because they include make-whole provisions that <b>discourage prepayments</b>.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A CMBS is secured by a pool of commercial mortgages of varying size, property type, and location, that are pooled and transferred to a SPE. CMBSs can be categorized as either agency or nonagency, depending on whether the underlying mortgages meet an agency’s guidelines. Although insurers are major investors in CMBSs, they typically hold a larger percentage of MBSs in their portfolios than CMBSs.</p><p class=\"explanations\">A make-whole provision, which limits prepayment risk, compensates CMBS holders by requiring the borrower to (1) purchase substitute collateral—usually a portfolio of high-quality securities, such as Treasuries—for the CMBS that generates enough cash to replace the cash flows lost because of prepayment, or (2) pay the holders a penalty. As a result, cash flows associated with CMBSs are reasonably predictable.</p><p class=\"explanations\"><b>Learning Objective:3B. Distinguish between asset-backed securities, residential mortgage-backed securities, and commercial mortgage-backed securities.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these answer choices is incorrect.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_021'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_022';
objQuestion.questionID = 111029;
objQuestion.item = 'LOMA_357_PPQ2019_022';
objQuestion.primaryLO = '3C';
objQuestion.textref = 'c. 3, pp. 10-11';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Derivatives used by insurers and other institutional investors include swaps, options, futures contracts, and forward contracts. Derivatives contracts in which two parties agree to exchange one asset, liability, security, or cash flow for another are known as <b>(swaps / options)</b>. Derivatives that are limited-time agreements in which a seller promises to deliver a specified asset to a buyer sometime in the future for a price specified in the agreement are known, by definition, as <b>(futures contracts / forward&nbsp;contracts)</b>.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "swaps / futures contracts";
arrAnsChoices[1] = "swaps / forward contracts";
arrAnsChoices[2] = "options / futures contracts";
arrAnsChoices[3] = "options / forward contracts";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448742;
arrAnsIDs[1] = 448743;
arrAnsIDs[2] = 448744;
arrAnsIDs[3] = 448745;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is correct to say that swaps are derivatives contracts in which two parties agree to exchange one asset, liability, security, or cash flow for another. However, <b>futures contracts</b> are limited-time agreements that give the owner of the agreement the right to buy or sell a certain asset at a specified future date and price.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Common swaps include credit-default swaps, interest-rate swaps, and currency swaps. Although institutional face counterparty risk in all financial contracts, counterparty risk is an especially important concern in swap contracts due to the direct negotiation between the parties. Forward contracts are also negotiated between parties; thus, they expose each party to more counterparty risk than other types of investments.</p><p class=\"explanations\"><b>Learning Objective: 3C. Distinguish between options, swaps, futures, and forwards and explain how investors use each type of derivative.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\"><b>Options</b> are derivatives that give the holder the right to either buy or sell a specified security—such as a stock or bond—at a stated price on or before a specified expiration date. In addition, <b>futures contracts</b> are limited-time agreements that give the owner of the agreement the right to buy or sell a certain asset at a specified future date and price.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is correct to say that forward contracts are limited-time agreements in which a seller promises to deliver a specified asset to a buyer sometime in the future for a price specified in the agreement. However, <b>options</b> are derivatives that give the holder the right to either buy or sell a specified security—such as a stock or bond—at a stated price on or before a specified expiration date.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_022'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_023';
objQuestion.questionID = 111030;
objQuestion.item = 'LOMA_357_PPQ2019_023';
objQuestion.primaryLO = '3D';
objQuestion.textref = 'c. 3, pp. 12-13';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Institutional investors include alternative investments—such as hedge funds, private equity funds, and infrastructure investments—in their portfolios to benefit from advantages, including:</p><ol type=\"A\" class=\"combo\"><li>Higher liquidity than traditional investments</li><li>Unique risk and return characteristics</li><li>Access to strategies or securities not available elsewhere</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A, B, and C";
arrAnsChoices[1] = "A and B only";
arrAnsChoices[2] = "A and C only";
arrAnsChoices[3] = "B and C only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448746;
arrAnsIDs[1] = 448747;
arrAnsIDs[2] = 448748;
arrAnsIDs[3] = 448749;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is <b>not</b> an advantage of including alternative investments in the portfolios of institutional investors.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement B is an advantage—and Statement A is a <b>disadvantage</b>—of including alternative investments in the portfolios of institutional investors. Many alternative investments have potential disadvantages, including <b>less</b> liquidity than traditional investments, as a result of multiyear commitments.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement C is an advantage—and Statement A is a <b>disadvantage</b>—of including alternative investments in the portfolios of institutional investors. Many alternative investments have potential disadvantages, including <b>less</b> liquidity than traditional investments, as a result of multiyear commitments.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Statement A is a disadvantage of including alternative investments in the portfolios of institutional investors. Another potential disadvantage includes demanding requirements for participation—such as a high minimum for the minimum assets under management (AUM), which is the amount of money that an advisor or company manages on behalf of a client.</p><p class=\"explanations\">Statement B is an advantage of including alternative investments in the portfolios of institutional investors. Unique risk and return characteristics, which offer increased opportunities for diversification, is a potential advantage of investing in alternative investments.</p><p class=\"explanations\">Statement C is an advantage of including alternative investments in the portfolios of institutional investors. Access to strategies or securities not available elsewhere is a potential advantage of investing in alternative investments. Alternative investments also offer higher potential returns than institutional investors can expect from traditional investments.</p><p class=\"explanations\"><b>Learning Objective: 3D. Describe the advantages and disadvantages of alternative investments and distinguish between hedge funds, private equity funds, and infrastructure investments.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_023'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_024';
objQuestion.questionID = 111031;
objQuestion.item = 'LOMA_357_PPQ2019_024';
objQuestion.primaryLO = '3D';
objQuestion.textref = 'c. 3, pp. 13-14';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about hedge funds. Three statements are true, and one statement is false. Select the answer choice containing the <B>FALSE</B> statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A hedge fund is an alternative investment vehicle that is often structured as a limited partnership.";
arrAnsChoices[1] = "Typically, hedge funds are available only to wealthy individuals and institutional investors and require large initial minimum investments.";
arrAnsChoices[2] = "Currently, hedge fund managers focus their investment style exclusively on hedging the risks from holding stocks in the fund.";
arrAnsChoices[3] = "Hedge funds generally face less regulatory oversight and fewer disclosure requirements than other types of investment vehicles.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448750;
arrAnsIDs[1] = 448751;
arrAnsIDs[2] = 448752;
arrAnsIDs[3] = 448753;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response. A hedge fund is an alternative investment vehicle that often is structured as a limited partnership, which consists of (1) one or more general partners who manage and control a business and are legally liable for all the debts and obligations of the business, and (2) one or more limited partners whose main function is to provide investment capital.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response. Hedge fund participation is limited to sophisticated investors that need less regulatory protection than other investors. Also, hedge funds usually restrict the investor’s ability to get out of the fund, particularly during the period immediately after the investor purchases shares.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">This statement is false; therefore, it is the correct response. Hedge funds started out as a means to hedge the risk from holding stocks, hence the fund type’s name. Over time, hedge funds increased their use of leverage to amplify returns. Now hedge funds can use derivatives and leverage to aggressively pursue investment gains and even speculate in markets.</p><p class=\"explanations\">Hedge funds can deliver exceptional returns relative to other types of investments. However, their concentrated bets can expose investors to significant losses. Because concentrated portfolios are less diversified, one investment loss could have a large effect on a concentrated hedge fund’s overall return.</p><p class=\"explanations\"><b>Learning Objective: 3D. Describe the advantages and disadvantages of alternative investments and distinguish between hedge funds, private equity funds, and infrastructure investments.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response. Hedge fund participation is limited to sophisticated investors that need less regulatory protection than other investors. Because they have fewer regulatory restrictions, hedge funds have the flexibility to engage in a wide range of investment strategies.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_024'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_025';
objQuestion.questionID = 111032;
objQuestion.item = 'LOMA_357_PPQ2019_025';
objQuestion.primaryLO = '3D';
objQuestion.textref = 'c. 3, p. 14';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Mantle Life Insurance Company invested in a private equity fund that uses debt financing to buy the outstanding equity of target companies and uses their cash flows to make loan payments on outstanding debt until the debt is repaid. This information indicates that Mantle invests in the type of private equity fund known as a</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "mezzanine debt fund";
arrAnsChoices[1] = "leveraged buyout fund";
arrAnsChoices[2] = "distressed debt fund";
arrAnsChoices[3] = "venture capital fund";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448754;
arrAnsIDs[1] = 448755;
arrAnsIDs[2] = 448756;
arrAnsIDs[3] = 448757;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Mantle does <b>not</b> invest in a mezzanine debt fund. Mezzanine debt is a type of subordinated debt that also gives the lender an equity stake in the borrowing company.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Like hedge funds, private equity funds are typically structured as limited partnerships and are available only to wealthy individuals and institutional investors. Types of private equity funds include mezzanine debt funds, leveraged buyout funds, distressed debt funds, and venture capital funds.</p><p class=\"explanations\"><b>Learning Objective: 3D. Describe the advantages and disadvantages of alternative investments and distinguish between hedge funds, private equity funds, and infrastructure investments.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Mantle does <b>not</b> invest in a distressed debt fund, also known as a vulture fund. Distressed debt funds search for securities that are undervalued because of a high risk of default, but possess the potential for significant future returns if default is avoided.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Mantle does <b>not</b> invest in a venture capital fund, which typically takes an active role in the growth of the target company by providing advice to management and setting goals for the company to achieve.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_025'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_026';
objQuestion.questionID = 111033;
objQuestion.item = 'LOMA_357_PPQ2019_026';
objQuestion.primaryLO = '3E';
objQuestion.textref = 'c. 3, pp. 18-19';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Drum Mutual Fund is organized as an open-end mutual fund. This information indicates that Drum</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "issues more shares as investors request them";
arrAnsChoices[1] = "trades shares at a discount or premium to net asset value (NAV)";
arrAnsChoices[2] = "does not redeem outstanding shares";
arrAnsChoices[3] = "trades shares on securities exchanges or in the over-the-counter (OTC) market";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448758;
arrAnsIDs[1] = 448759;
arrAnsIDs[2] = 448760;
arrAnsIDs[3] = 448761;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Open-end mutual funds establish a portfolio of securities with a flexible number of outstanding shares. When an investor invests in an open-end fund, the investment company issues more shares, which increases the total number of outstanding shares. When an investor redeems shares, the company buys back the investor’s shares, which decreases the total number of outstanding shares. The price per share is equal to the NAV that was calculated at the end of the day when the order is received.</p><p class=\"explanations\">In contrast, closed-end mutual funds establish a portfolio of securities with a fixed number of outstanding shares that are traded on securities exchanges or in the OTC market. Investment companies do not issue new shares and do not redeem outstanding shares in the funds. Investors can trade shares in a closed-end mutual fund at any time while the market is open. Share prices are determined by market forces instead of by NAV calculations.</p><p class=\"explanations\"><b>Learning Objective: 3E. Describe the basic characteristics of investment funds and distinguish between open-end mutual funds, closed-end mutual funds, unit investment trusts, and exchange-traded funds.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">For an open-end mutual fund, the price the investors receives per share is <b>equal to the NAV</b> that was calculated at the end of the day when the order is received. For a closed-end mutual fund, share prices are determined by market forces instead of by NAV calculations. Therefore, fund shares can trade at a (1) discount when the current market price is below its NAV, or at a (2) premium when the current market price is above its NAV.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">An open-end mutual fund <b>redeems</b> outstanding shares—the investment company buys back the investor’s shares—which decreases the total number of outstanding shares. When an investor invests in an open-end fund, the company issues more shares—which increases the total number of outstanding shares. In contrast, a closed-end mutual fund does <b>not</b> issue new shares and does not redeem outstanding shares.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">An open-end mutual fund establishes a portfolio of securities with a flexible number of outstanding shares and <b>trades shares directly with investors</b>. A <b>closed-end</b> mutual fund establishes a portfolio of securities with a fixed number of outstanding shares that are traded on securities exchanges or in the OTC market.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_026'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_027';
objQuestion.questionID = 111034;
objQuestion.item = 'LOMA_357_PPQ2019_027';
objQuestion.primaryLO = '3F';
objQuestion.textref = 'c. 3, pp. 22-24';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">In capital markets, participants—including suppliers, users, and facilitators—play a direct role, while influencers affect the markets without playing a direct role. In this context, retirement plans typically function as capital market <b>(facilitators / suppliers)</b>, and insurance regulators typically function as capital market <b>(users / influencers)</b>.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "facilitators / users";
arrAnsChoices[1] = "facilitators / influencers";
arrAnsChoices[2] = "suppliers / users";
arrAnsChoices[3] = "suppliers / influencers";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448762;
arrAnsIDs[1] = 448763;
arrAnsIDs[2] = 448764;
arrAnsIDs[3] = 448765;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Retirement plans typically do <b>not</b> function as capital market facilitators, which enable buyers and sellers to complete securities transactions. In addition, insurance regulators typically do <b>not</b> function as capital market users, which draw funds from the capital markets through their securities sales.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is correct to say that insurance regulators typically function as capital market influencers. However, retirement plans typically do <b>not</b> function as capital market facilitators, which enable buyers and sellers to complete securities transactions.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is correct to say that institutional investors such as retirement plans typically function as capital market suppliers. However, insurance regulators typically do <b>not</b> function as capital market users, which are entities that draw funds from the capital markets through their securities sales.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The three main participants in capital markets are capital market suppliers, capital market users, and capital market facilitators. Capital market suppliers (asset buyers) include governments, charitable trusts, insurance companies, banks, investment funds, endowment funds, retirement plans, pension funds, sovereign wealth funds, and retail investors.</p><p class=\"explanations\">Capital market users (asset sellers) include stock insurance companies, businesses, governments, and government agencies. Capital market facilitators include investment banks, broker-dealers, custodians, securities exchanges, and settlement agents. In addition, capital market influencers, such as rating agencies and regulators, affect the markets without playing a direct role.</p><p class=\"explanations\"><b>Learning Objective: 3F. Describe the three main roles for participants in capital markets and distinguish between primary and secondary markets.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_027'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_028';
objQuestion.questionID = 111035;
objQuestion.item = 'LOMA_357_PPQ2019_028';
objQuestion.primaryLO = '3F';
objQuestion.textref = 'c. 3, pp. 24-25, 26';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">To help with the sale of its new bond issue to the public, the Verde Corporation hired the Homage Group, an investment bank. Homage purchased the bond issue from Verde at a specified price and then sold the bonds to the public at a somewhat higher price. This information indicates that the initial sale of the Verde bond issue occurred in the <b>(primary / secondary) </b>market. In helping Verde with the sale of its new bond issue to the public, Homage most likely provided Verde the investment bank service known as a <b>(firm commitment contract / best efforts basis)</b>.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "primary / firm commitment contract";
arrAnsChoices[1] = "primary / best efforts basis";
arrAnsChoices[2] = "secondary / firm commitment contract";
arrAnsChoices[3] = "secondary / best efforts basis";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448766;
arrAnsIDs[1] = 448767;
arrAnsIDs[2] = 448768;
arrAnsIDs[3] = 448769;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Although the bulk of securities trading takes place in secondary markets, issuers sell new issues of debt and equity securities directly to investors—mostly institutional investors and financial intermediaries—through the primary market. In a public offering, the security issuer makes a new security available for sale to the public, usually through the services of an investment bank.</p><p class=\"explanations\">In a firm commitment contract, an investment bank enters into an agreement to buy all newly issued securities from the issuer, and accepts the risk that it may sell the issue at a price below the price that it paid. When the investment bank sells issues of securities on a best efforts basis, the bank does not first purchase the bonds or shares from the issuer. The best efforts basis protects the bank in the event that it cannot sell all of the issue. Any unsold shares or bonds are returned to the issuer.</p><p class=\"explanations\"><b>Learning Objective: 3F. Describe the three main roles for participants in capital markets and distinguish between primary and secondary markets.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is correct to say that the sale of the Verde bond issue occurred in the primary market. However, Homage did <b>not</b> sell Verde’s bonds on a best efforts basis. When an investment bank sells issues of securities on a best efforts basis, the bank attempts to sell the new issue on behalf of the issuer on the best terms obtainable, but does <b>not</b> first purchase the bonds or shares from the issuer. In this situation, Homage purchased the Verde bond issue.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is correct to say that Homage most likely entered into a firm commitment contract to buy all of Verde’s newly-issued bonds. However, new issues of securities, including the Verde bond issue, are sold to the public for the first time in the <b>primary </b>market. A secondary market is a market in which issues of securities are subsequently traded after the initial sale.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">New issues of securities, including the Verde bond issue, are sold to the public for the first time in the <b>primary </b>market. A secondary market is a market in which issues of securities are subsequently traded after the initial sale. In addition, Homage did <b>not</b> provide the type of service known as a best efforts basis. When an investment bank sells issues of securities on a best efforts basis, the bank attempts to sell the new issue on behalf of the issuer on the best terms obtainable, but does <b>not</b> first purchase the bonds or shares from the issuer. In this situation, Homage purchased the Verde bond issue.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_028'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_029';
objQuestion.questionID = 111036;
objQuestion.item = 'LOMA_357_PPQ2019_029';
objQuestion.primaryLO = '3G';
objQuestion.textref = 'c. 3, pp. 26-27';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about different types of stock exchanges. For this question, if statements (1) through (3) are all correct, select answer choice (4). Otherwise, select the one correct statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A trade occurs in an auction-based market if the highest bid price equals the lowest ask price.";
arrAnsChoices[1] = "A market maker holds an inventory of a particular stock and stands ready to buy and sell shares of that stock.";
arrAnsChoices[2] = "Large institutions can use alternative electronic markets to resell private placement securities to other qualified institutions.";
arrAnsChoices[3] = "all of the above";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448770;
arrAnsIDs[1] = 448771;
arrAnsIDs[2] = 448772;
arrAnsIDs[3] = 448773;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">This statement is correct, but it is <b>not</b> the only correct statement.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">This statement is correct, but it is <b>not</b> the only correct statement.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">This statement is correct, but it is <b>not</b> the only correct statement.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The bid<i> </i>price is the price a buyer is willing to pay for a share. The ask price is the price at which a seller is willing to sell a share. If the highest bid price is less than the lowest ask price, no trade occurs. In the United States, the New York Stock Exchange (NYSE) is primarily an auction-based network.</p><p class=\"explanations\">In a dealer-based market, dealers act as market makers. Dealers publicly post bid and ask prices for the securities in their inventory. Buyers and sellers can conduct trades immediately because market makers agree to trade at published bid and ask prices. In the United States, the National Association of Securities Dealers Automated Quotations (NASDAQ) is an example of a dealer-based market.</p><p class=\"explanations\">Alternative electronic markets allow buyers and sellers to conduct trades directly with each other. Traders place orders in an electronic trading network, and the network automatically matches buy and sell orders whenever possible. Stocks not listed on any type of organized exchange are traded in OTC market. Alternative electronic markets trade in OTC stocks and in stocks on organized exchanges.</p><p class=\"explanations\"><b>Learning Objective: 3G. Explain the different methods that stock exchanges use to match buyers with sellers.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_029'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['3A'] = "3A. Explain the process of securitization and describe the four types of tranches typically found in structured products.";
arrlotext['3B'] = "3B. Distinguish between asset-backed securities, residential mortgage-backed securities, and commercial mortgage-backed securities.";
arrlotext['3C'] = "3C. Distinguish between options, swaps, futures, and forwards and explain how investors use each type of derivative.";
arrlotext['3D'] = "3D. Describe the advantages and disadvantages of alternative investments and distinguish between hedge funds, private equity funds, and infrastructure investments.";
arrlotext['3E'] = "3E. Describe the basic characteristics of investment funds and distinguish between open-end mutual funds, closed-end mutual funds, unit investment trusts, and exchange-traded funds.";
arrlotext['3F'] = "3F. Describe the three main roles for participants in capital markets and distinguish between primary and secondary markets.";
arrlotext['3G'] = "3G. Explain the different methods that stock exchanges use to match buyers with sellers.";
