var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2021';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 371 Practice Questions, Chapter 7";
var coursename = 'LOMA 371';
var modulenumber = 3;
var title = "LOMA_371_PPQ2021_0_7";
var intNumPools = 1;
var numQ = 14;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Risk Management and Product Design for Insurance Companies, Third Edition (2020)";
arrNumChap[0] = 1;
var thisChap = '7';

objPool = new Object(); 
objPool.intSelectCount = 14;
objPool.formID = 2617;
objPool.formName = 'PPQ2021_0_7';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_371_PQ_061';
arrPoolQuestions[1] = 'LOMA_371_PQ_062';
arrPoolQuestions[2] = 'LOMA_371_PQ_063';
arrPoolQuestions[3] = 'LOMA_371_PQ_064';
arrPoolQuestions[4] = 'LOMA_371_PQ_065';
arrPoolQuestions[5] = 'LOMA_371_PQ_066';
arrPoolQuestions[6] = 'LOMA_371_PQ_067';
arrPoolQuestions[7] = 'LOMA_371_PQ_068';
arrPoolQuestions[8] = 'LOMA_371_PQ_069';
arrPoolQuestions[9] = 'LOMA_371_PQ_070';
arrPoolQuestions[10] = 'LOMA_371_PQ_071';
arrPoolQuestions[11] = 'LOMA_371_PQ_072';
arrPoolQuestions[12] = 'LOMA_371_PQ_073';
arrPoolQuestions[13] = 'LOMA_371_PQ_074';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_061';
objQuestion.questionID = 121338;
objQuestion.item = 'LOMA_371_PPQ2021_061';
objQuestion.primaryLO = '7A';
objQuestion.textref = 'c. 7, pp. 2-3';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">An insurer typically divides its assets into two main types of accounts: a general account and one or more separate accounts. Select the answer choice that correctly identifies which account supports products, such as variable life insurance and variable annuities, and whether the insurer or the customer bears the investment risks associated with variable products funded by this account.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[-1] = "<u>Supports variable products</u></div><div class=\"anshead\"><u>Bears risk of variable products</u>";
arrAnsChoices[0] = "separate account</div><div class=\"anscell\" onclick=\"recordAns(1);\">insurer";
arrAnsChoices[1] = "separate account</div><div class=\"anscell\" onclick=\"recordAns(2);\">customer";
arrAnsChoices[2] = "general account</div><div class=\"anscell\" onclick=\"recordAns(3);\">insurer";
arrAnsChoices[3] = "general account</div><div class=\"anscell\" onclick=\"recordAns(4);\">customer";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490701;
arrAnsIDs[1] = 490702;
arrAnsIDs[2] = 490703;
arrAnsIDs[3] = 490704;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that insurers that offer variable products maintain one or more separate accounts, also known as<i> </i>separate account portfolios or segregated account portfolios, for assets that support the insurer’s variable products. However, the <b>customer</b>, rather than the insurer, bears the investment risks associated with a variable product that is funded by a separate account.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">All insurers have a general account, also known as a general account<b> </b>portfolio,<i> </i>for assets that support the insurer’s contractual obligations to owners of the insurer’s guaranteed products and any guarantees found in variable products.</p><p class=\"explanations\">Insurers that offer variable products maintain one or more separate accounts, also known as<i> </i>separate account portfolios or segregated account portfolios, for assets that support the insurer’s variable products. An insurer typically divides separate account portfolios into smaller subaccounts; each subaccount consists of a pool of investments with a distinct risk-return profile, or fund style.</p><p class=\"explanations\">The insurer bears the investment risks associated with the general account. The customer, rather than the insurer, determines how premiums are applied to subaccounts. The customer also bears the investment risks associated with a variable product that is funded by a separate account.</p><p class=\"explanations\"><b>Learning Objective: 7A: Describe how an insurer’s general account portfolio and separate account portfolios affect the insurer’s investment earnings.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The <b>customer</b>, rather than the insurer, bears the investment risks associated with a variable product that is funded by a separate account. In addition, insurers that offer variable products maintain one or more <b>separate</b> accounts, also known as<i> </i>separate account portfolios or segregated account portfolios, for assets that support the insurer’s variable products.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that customers bear the investment risks associated with a variable product that is funded by a separate account. However, insurers that offer variable products maintain one or more <b>separate</b> accounts, also known as<i> </i>separate account portfolios or segregated account portfolios, for assets that support the insurer’s variable products.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_061'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_062';
objQuestion.questionID = 121339;
objQuestion.item = 'LOMA_371_PPQ2021_062';
objQuestion.primaryLO = '7B';
objQuestion.textref = 'c. 7, pp. 3-4';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Last year, the Magnolia Life Insurance Company purchased 100 shares of JKL common stock at $45 per share. Magnolia held the JKL stock for one year, then sold all 100 JKL shares at $52 per share. During the year that Magnolia owned JKL, Magnolia received $4 per share in dividends. The following statement(s) can correctly be made about Magnolia’s investment in JKL:</p><ol type=\"A\" class=\"combo\"><li>Magnolia realized a gain on JKL as a result of price appreciation.</li><li>Magnolia correctly calculated its total rate of return on JKL by dividing $700 by $4,500.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490705;
arrAnsIDs[1] = 490706;
arrAnsIDs[2] = 490707;
arrAnsIDs[3] = 490708;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct. An investor realizes a gain when an asset’s selling price is higher than the asset’s purchase price. Gains generally result from price appreciation. In this situation, Magnolia’s investment in JKL experienced price appreciation by increasing $7 per share, from $45 to $52, for a $700 gain.</p><p class=\"explanations\">Statement B is incorrect. The total return on an investment is the sum of all the investment’s earnings. The total rate of return is determined by summing all of an asset’s earnings—such as gains and dividends—and dividing this sum by the asset’s price at purchase, or principal.</p><p class=\"explanations\">In this situation, Magnolia’s total return on JKL common stock consists of price appreciation and dividends: [($52 – $45) × 100] + ($4&nbsp;×&nbsp;100)] = $1,100. JKL’s purchase price equals ($45 × 100) = $4,500. Therefore, the total rate of return on JKL equals $1,100 ÷ $4,500 = 24.44%.</p><p class=\"explanations\"><b>Learning Objective: 7B. Define investment concepts such as <i>price appreciation</i>, <i>price depreciation</i>, and <i>rate of return</i>.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is incorrect. The total return on an investment is the sum of all the investment’s earnings. The total rate of return is determined by summing all of an asset’s earnings—such as gains and dividends—and dividing this sum by the asset’s price at purchase, or principal.</p><p class=\"explanations\">In this situation, Magnolia’s total return on JKL common stock consists of price appreciation and dividends: [($52 – $45) × 100] + ($4&nbsp;×&nbsp;100)] = $1,100. JKL’s purchase price equals ($45 × 100) = $4,500. Therefore, the total rate of return on JKL equals $1,100 ÷ $4,500 = 24.44%.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_062'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_063';
objQuestion.questionID = 121340;
objQuestion.item = 'LOMA_371_PPQ2021_063';
objQuestion.primaryLO = '7C';
objQuestion.textref = 'c. 7, pp. 4-5';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">In terms of the time value of money, a sum of money has both a present value (PV) and a future value (FV). The following statement(s) can correctly be made about PV and FV:</p><ol type=\"A\" class=\"combo\"><li>The PV of a sum of money is defined as the amount that the original sum is expected to be worth at a specified future date, given a specified interest rate.</li><li>The FV of a sum of money is defined as the amount that, if invested at a specified interest rate on a specified date, would grow to equal a specified future amount.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490709;
arrAnsIDs[1] = 490710;
arrAnsIDs[2] = 490711;
arrAnsIDs[3] = 490712;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is incorrect. It is the definition of the <b>future value (FV)</b> of a sum of money.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is incorrect. It is the definition of the <b>present value (PV)</b> of a sum of money.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Statement A is incorrect. The present value (PV of a sum of money is the amount that, if invested at a specified interest rate on a specified date, would grow to equal a specified future amount. The periods used in PV calculations are known as discounting periods.</p><p class=\"explanations\">Statement B is incorrect. The future value (FV) of a sum of money is the amount that the original sum is expected to be worth at a specified future date, given a specified interest rate. The periods used in FV calculations are known as compounding periods.</p><p class=\"explanations\">The present value of an investment is the principal—the original amount invested before it earns interest—and the future value is the invested principal plus the accumulated earnings. These calculations also assume compound interest; therefore, compounding periods and discounting periods are relevant.</p><p class=\"explanations\"><b>Learning Objective: 7C. Explain the time value of money and the relationship between present value and future value.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_063'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_064';
objQuestion.questionID = 121341;
objQuestion.item = 'LOMA_371_PPQ2021_064';
objQuestion.primaryLO = '7C';
objQuestion.textref = 'c. 7, pp. 4-6';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statement(s) can correctly be made about the rules associated with the time value of money and the relationship between present value and future value:</p><ol type=\"A\" class=\"combo\"><li>The future value of a principal sum invested at interest is always greater than the sum’s present&nbsp;value.</li><li>When calculating the present value of a future sum, given a stated rate of positive interest for a specified period, an increase in the interest rate results in a decrease in the present value.</li><li>For money earning a stated rate of interest for a specified period, an increase in the number of periods will result in an increase in the future value of a present sum.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A, B, and C";
arrAnsChoices[1] = "A and B only";
arrAnsChoices[2] = "A and C only";
arrAnsChoices[3] = "B and C only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490713;
arrAnsIDs[1] = 490714;
arrAnsIDs[2] = 490715;
arrAnsIDs[3] = 490716;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Investment growth is based on a concept known as the time value of money, which states that the value of a sum of money changes over time as a result of the effects of interest. The time value of money concept also assumes that interest earnings are positive. The effects of the time value of money are calculated using one of two values: future value and present value.</p><p class=\"explanations\">Future value calculations are useful when an insurer knows the specific sum it intends to invest and needs to know how much the investment is likely to earn. Present value calculations are useful when an insurer has identified a specific sum as a future goal and needs to know how much to invest to achieve that goal.</p><p class=\"explanations\"><b>Learning Objective: 7C. Explain the time value of money and the relationship between present value and future value.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A and Statement B are correct; however, Statement C is also correct.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement A and Statement C are correct; however, Statement B is also correct.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Statement B and Statement C are correct; however, Statement A is also correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_064'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_065';
objQuestion.questionID = 121342;
objQuestion.item = 'LOMA_371_PPQ2021_065';
objQuestion.primaryLO = '7D';
objQuestion.textref = 'c. 7, pp. 5-7';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Hal Spoth wants to determine the future value (FV) of a $10,000 single amount, or principal, invested for four years at a 5% interest rate, compounded annually. Mr.&nbsp;Spoth correctly determined that the formula for the FV of this sum of money is</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "($10,000 ÷ 5) × 1.05<sup style=\"vertical-align: baseline; position: relative; top: -0.4em; line-height: 0em; font-size: 0.8em;\">4</sup>";
arrAnsChoices[1] = "$10,000 × (1.05)<sup style=\"vertical-align: baseline; position: relative; top: -0.4em; line-height: 0em; font-size: 0.8em;\">4</sup>";
arrAnsChoices[2] = "$10,000 × 1.05 × 4";
arrAnsChoices[3] = "$10,000 ÷ (0.5 × 4)";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490717;
arrAnsIDs[1] = 490718;
arrAnsIDs[2] = 490719;
arrAnsIDs[3] = 490720;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">When a sum or money is invested for more than one interest period, the interest is compounded: that is, the present value (PV) is multiplied by one plus the interest rate—(1&nbsp;+&nbsp;<i>i</i>)—one time for each interest period (<i>n</i>) in which interest (<i>i</i>) is applied. In Mr.&nbsp;Spoth’s situation, <i>i</i> equals 5% or 0.05, and <i>n</i> equals 4. Therefore, he would multiply $10,000&nbsp;×&nbsp;(1.05)<sup style=\"vertical-align: baseline; position: relative; top: -0.4em; line-height: 0em; font-size: 0.8em;\">4</sup>, which results in a future value of $12,155.06.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Insurers often calculate the future value of a single amount over multiple periods—as with a single-premium life insurance or annuity product. Insurer applications for calculating the future value of a sum of money include matching projected earnings with projected liabilities, projecting benefits for products that credit an interest rate to customers, calculating cash values, tracking investment performance, and projecting the future value of premium payments.</p><p class=\"explanations\">When a sum or money is invested for more than one interest period, the interest is compounded: that is, the present value (PV) is multiplied by one plus the interest rate—(1&nbsp;+&nbsp;<i>i</i>)—one time for each interest period (<i>n</i>) in which interest (<i>i</i>) is applied. In the formula for Mr.&nbsp;Spoth’s calculation, <i>i</i> equals 0.05, and <i>n</i> equals 4. Therefore, he would multiply $10,000&nbsp;×&nbsp;(1.05)<sup style=\"vertical-align: baseline; position: relative; top: -0.4em; line-height: 0em; font-size: 0.8em;\">4</sup>, which results in a future value of $12,155.06.</p><p class=\"explanations\"><b>Learning Objective: 7D. Explain the applications for future values and present values.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">When a sum or money is invested for more than one interest period, the interest is compounded: that is, the present value (PV) is multiplied by one plus the interest rate—(1&nbsp;+&nbsp;<i>i</i>)—one time for each interest period (<i>n</i>) in which interest (<i>i</i>) is applied. In Mr.&nbsp;Spoth’s situation, <i>i</i> equals 5% or 0.05, and <i>n</i> equals 4. Therefore, he would multiply $10,000&nbsp;×&nbsp;(1.05)<sup style=\"vertical-align: baseline; position: relative; top: -0.4em; line-height: 0em; font-size: 0.8em;\">4</sup>, which results in a future value of $12,155.06.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">When a sum or money is invested for more than one interest period, the interest is compounded: that is, the present value (PV) is multiplied by one plus the interest rate—(1&nbsp;+&nbsp;<i>i</i>)—one time for each interest period (<i>n</i>) in which interest (<i>i</i>) is applied. In Mr.&nbsp;Spoth’s situation, <i>i</i> equals 5% or 0.05, and <i>n</i> equals 4. Therefore, he would multiply $10,000&nbsp;×&nbsp;(1.05)<sup style=\"vertical-align: baseline; position: relative; top: -0.4em; line-height: 0em; font-size: 0.8em;\">4</sup>, which results in a future value of $12,155.06.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_065'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_066';
objQuestion.questionID = 121343;
objQuestion.item = 'LOMA_371_PPQ2021_066';
objQuestion.primaryLO = '7D';
objQuestion.textref = 'c. 7, pp. 7-8';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">An (<b>ordinary annuity / annuity due</b>) is a series of periodic payments for which the payment occurs at the end of each specified payment period. A level series of whole life insurance premiums is an example of an (<b>ordinary annuity / annuity due</b>).</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "ordinary annuity / ordinary annuity";
arrAnsChoices[1] = "ordinary annuity / annuity due";
arrAnsChoices[2] = "annuity due / ordinary annuity";
arrAnsChoices[3] = "annuity due / annuity due";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490721;
arrAnsIDs[1] = 490722;
arrAnsIDs[2] = 490723;
arrAnsIDs[3] = 490724;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that an ordinary annuity is a series of periodic payments for which the payment occurs at the end of each specified payment period. However, a level series of whole life insurance premiums is an example of an <b>annuity due</b>.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Two examples of an ordinary annuity are an employee’s paycheck paid at the end of each work period and a bond interest payment received one period after the bond is issued. When calculating the future value of an ordinary annuity, the final payment earns no interest because it is paid at the end of the last compounding&nbsp;period.</p><p class=\"explanations\">An annuity due is a series of periodic payments for which the payment occurs at the beginning of each specified payment period. Another example of an ordinary annuity is a series of rent payments. When calculating the future value of an annuity due, all payments, including the final payment, earn interest for at least one compounding period.</p><p class=\"explanations\"><b>Learning Objective: 7D. Explain the applications for future values and present values.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">An <b>ordinary annuity</b> is a series of periodic payments for which the payment occurs at the end of each specified payment period. In addition, a level series of whole life insurance premiums is an example of an <b>annuity&nbsp;due</b>.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that a level series of whole life insurance premiums is an example of an annuity due. However, an <b>ordinary annuity</b> is a series of periodic payments for which the payment occurs at the end of each specified payment period.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_066'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_067';
objQuestion.questionID = 121344;
objQuestion.item = 'LOMA_371_PPQ2021_067';
objQuestion.primaryLO = '7D';
objQuestion.textref = 'c. 7, pp. 9-10';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Use the following portion of a present value interest factor table, PVIF (<i>n</i>, <i>i</i>), to answer this question.</p><table class=\"tbexam\" align=\"center\"><tr><td style=\"vertical-align: middle; text-align: left; background-color: #DCDCDC;\"><b>Periods (n)</b></td><td style=\"vertical-align: middle; text-align: center; background-color: #DCDCDC;\"><b>4%</b></td><td style=\"vertical-align: middle; text-align: center; background-color: #DCDCDC;\"><b>5%</b></td></tr><tr><td style=\"vertical-align: middle; text-align: center;\">9</td><td style=\"vertical-align: middle; text-align: center;\">0.703</td><td style=\"vertical-align: middle; text-align: center;\">0.645</td></tr><tr><td style=\"vertical-align: middle; text-align: center;\">10</td><td style=\"vertical-align: middle; text-align: center;\">0.676</td><td style=\"vertical-align: middle; text-align: center;\">0.614</td></tr><tr><td style=\"vertical-align: middle; text-align: center;\">11</td><td style=\"vertical-align: middle; text-align: center;\">0.650</td><td style=\"vertical-align: middle; text-align: center;\">0.585</td></tr></table><p class=\"stem\">The formula to calculate the present value of $75,000, discounted at 4% for 10 years, is</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "$75,000 × (1 – 0.676)";
arrAnsChoices[1] = "$75,000 + ($3,000 × 10) × 0.676";
arrAnsChoices[2] = "$75,000 × 0.676";
arrAnsChoices[3] = "$75,000 × (0.676 + 1)";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490725;
arrAnsIDs[1] = 490726;
arrAnsIDs[2] = 490727;
arrAnsIDs[3] = 490728;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The basic calculation for present value involves multiplying the future value (or desired goal) by 1 divided by the sum of 1 + the interest rate, often represented as 1 ÷ (1 + <i>i</i>). Insurers can use this calculation as the basis for determining present values for a single amount over one or more periods or for an annuity. In this situation, the present value of $75,000, discounted at 4% for 10 years, is calculated by multiplying $75,000 by 0.676, or PVIF(10,&nbsp;4%), which equals $50,700.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The basic calculation for present value involves multiplying the future value (or desired goal) by 1 divided by the sum of 1 + the interest rate, often represented as 1 ÷ (1 + <i>i</i>). Insurers can use this calculation as the basis for determining present values for a single amount over one or more periods or for an annuity. In this situation, the present value of $75,000, discounted at 4% for 10 years, is calculated by multiplying $75,000 by 0.676, or PVIF(10,&nbsp;4%), which equals $50,700.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The basic calculation for present value involves multiplying the future value (or desired goal) by 1 divided by the sum of 1 + the interest rate, often represented as 1 ÷ (1 + <i>i</i>). Insurers can use this calculation as the basis for determining present values for a single amount over one or more periods or for an annuity. Insurer applications for calculating the present value of a sum of money include setting premium rates, developing an investment budget, calculating cash values, and measuring profitability.</p><p class=\"explanations\">As when calculating future value, software and financial calculators are common tools for determining the present value for single amounts or annuities. Present value interest factors (PVIFs) and present value interest factor tables are also available, both separately and incorporated into such electronic tools. In this situation, the present value of $75,000, discounted at 4% for 10 years, is calculated by multiplying $75,000 by 0.676, or PVIF(10,&nbsp;4%), which equals $50,700.</p><p class=\"explanations\"><b>Learning Objective: 7D. Explain the applications for future values and present values.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The basic calculation for present value involves multiplying the future value (or desired goal) by 1 divided by the sum of 1 + the interest rate, often represented as 1 ÷ (1 + <i>i</i>). Insurers can use this calculation as the basis for determining present values for a single amount over one or more periods or for an annuity. In this situation, the present value of $75,000, discounted at 4% for 10 years, is calculated by multiplying $75,000 by 0.676, or PVIF(10,&nbsp;4%), which equals $50,700.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_067'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_068';
objQuestion.questionID = 121345;
objQuestion.item = 'LOMA_371_PPQ2021_068';
objQuestion.primaryLO = '7E';
objQuestion.textref = 'c. 7, pp. 13-14';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Niko Gesta owns a fixed annuity contract with the following values:</p><ul class=\"examul\"><li>Guaranteed interest-crediting rate = 2.4%</li><li>Rate of return the insurer earned on the product = 5.2%</li><li>Current interest-crediting rate = 3.9%</li></ul><p class=\"stem\">This information indicates that the interest spread on Mr.&nbsp;Gesta’s annuity contract is (<b>1.3% / 2.8%</b>). The (<b>higher / lower</b>) the interest spread on a product such as Mr.&nbsp;Gesta’s annuity contract, the more profitable the product is likely to be for an insurer.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "1.3% / higher";
arrAnsChoices[1] = "1.3% / lower";
arrAnsChoices[2] = "2.8% / higher";
arrAnsChoices[3] = "2.8% / lower";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490729;
arrAnsIDs[1] = 490730;
arrAnsIDs[2] = 490731;
arrAnsIDs[3] = 490732;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Interest rates affect both how much money an insurer expects to receive from its customers and how much it expects to pay to its customers. The interest spread, also known as the interest margin or interest-rate margin, which is one measure of a product’s potential rate of return, is the difference between the rate of return an insurer earns on its investments and the interest-crediting rate. The interest spread for a fixed annuity contract is equal to the difference between the rate of return the insurer actually earns and the interest-crediting rate. In this situation, the interest spread for Mr.&nbsp;Gesta’s contract is 5.2%&nbsp;–&nbsp;3.9% =&nbsp;1.3%.</p><p class=\"explanations\">During product design, an insurer must set a premium amount that, along with investment earnings, will produce enough money to cover the cost of promised benefits when due. The interest rate used in product design generally is known as the interest-rate assumption, or the assumed interest rate. The insurer projects an expected interest rate on the product’s associated investments and sets a lower assumed interest rate in order to earn an expected level of profit on the product.</p><p class=\"explanations\"><b>Learning Objective: 7E. Define a product’s crediting rates and interest spread and explain how an insurer determines these elements for life insurance and annuity products.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that the interest spread for Mr.&nbsp;Gesta’s contract is 5.2%&nbsp;–&nbsp;3.9% = 1.3%. However, the <b>higher</b> the interest spread on the product, the more profitable the product is likely to be for the insurer.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that the higher the interest spread on the product, the more profitable the product is likely to be for the insurer. However, the interest spread for Mr.&nbsp;Gesta’s contract is 5.2%&nbsp;–&nbsp;3.9% = <b>1.3%.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The interest spread for Mr.&nbsp;Gesta’s contract is 5.2%&nbsp;–&nbsp;3.9% = <b>1.3%</b>. In addition, the <b>higher</b> the interest spread on the product, the more profitable the product is likely to be for the insurer.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_068'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_069';
objQuestion.questionID = 121346;
objQuestion.item = 'LOMA_371_PPQ2021_069';
objQuestion.primaryLO = '7F';
objQuestion.textref = 'c. 7, pp. 13-14, 15-16';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Permanent life insurance products are often referred to as cash value insurance products because they offer the additional feature of the contract owner’s equity in the form of a cash value, which contract owners can access in the form of policy loans, withdrawal and surrender benefits, or nonforfeiture benefits. One true statement about the cash values of these products is that</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "the prospective valuation formula for determining the cash value of a fixed life insurance product is the present value of future benefits minus the present value of future premiums";
arrAnsChoices[1] = "insurers use the same formula to calculate the cash values of fixed life insurance products, flexible-premium life products, universal life products, and variable life products";
arrAnsChoices[2] = "insurers allocate the premiums of fixed annuity contracts to separate account subaccounts, and then purchase accumulation units, which have a minimum guaranteed value";
arrAnsChoices[3] = "both the cash value of a fixed life insurance contract and the accumulated value of a deferred annuity contract are equal to the current value of the contract owner’s equity in the contract";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490733;
arrAnsIDs[1] = 490734;
arrAnsIDs[2] = 490735;
arrAnsIDs[3] = 490736;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Insurers set a cash value for fixed life insurance products based on the amount of premiums paid on the policy, the face amount of the policy, and the amount of time the policy has been in force. Insurers can use either prospective or retrospective valuation methods to calculate this cash value. The great majority of insurers use the prospective valuation method, which looks at a product’s future cash flows.</p><p class=\"explanations\">By contrast, a retrospective valuation method looks at a product’s past cash flows. This method uses future value, or accumulated value, techniques to base cash value on past performance. Though prospective and retrospective valuation both arrive at the same cash values, regulations require most insurers to use prospective valuation for new products.</p><p class=\"explanations\"><b>Learning Objective: 7F. Explain how actuaries account for cash values and accumulated values in product design.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The formulas for fixed products do <b>not</b> readily apply to flexible-premium life products, such as universal life products and variable life products. For these forms of life insurance, an insurer calculates cash value by subtracting the remaining unamortized first-year expenses from the policy’s account value. In effect, the cash value is essentially the value of the account once all first-year expenses have been paid.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The fixed account directs premium payments to the insurer’s <b>general account</b>. If the contract specifies a current interest-crediting rate, the insurer credits interest to the contract using that rate. Otherwise, the insurer credits the contract with the guaranteed interest-crediting rate. The insurer uses premiums allocated to subaccounts to purchase accumulation units, which represent ownership shares in the selected subaccounts. The value of a contract owner’s accumulation units is <b>not</b> guaranteed. Accumulation units increase or decrease in value based on the performance of subaccount investments.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Like the cash value of a life insurance policy, the accumulated value represents the owner’s equity in the contract. However, while the accumulated value represents the current value of the annuity contract, a life insurance policy’s cash value generally is <b>separate</b> from the policy’s face amount.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_069'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_070';
objQuestion.questionID = 121347;
objQuestion.item = 'LOMA_371_PPQ2021_070';
objQuestion.primaryLO = '7G';
objQuestion.textref = 'c. 7, pp. 17-19';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Dignity Life Insurance Company currently earns 8% on the investments supporting its fixed deferred annuity products. Dignity credits these products with 5% interest. Economic conditions have caused a rise in market interest rates. However, because Dignity owns many investments that were purchased at lower interest rates, the average rate of return on Dignity’s existing invested assets is rising more slowly than market interest rates. Because Dignity’s customers immediately demand the higher market interest rate applied to Dignity’s fixed-rate deferred annuities, Dignity has chosen to increase interest-crediting rates. Dignity’s situation illustrates a condition known as</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "spread expansion";
arrAnsChoices[1] = "discounting";
arrAnsChoices[2] = "refinancing";
arrAnsChoices[3] = "spread compression";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490737;
arrAnsIDs[1] = 490738;
arrAnsIDs[2] = 490739;
arrAnsIDs[3] = 490740;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Spread expansion is the widening of an insurer’s interest spread. Spread expansion occurs when market interest rates <b>fall</b> and the insurer <b>reduces</b> interest-crediting rates to the new market level while continuing to earn a higher overall rate of return on its existing invested assets.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">In the context of the time value of money, discounting refers to each of the interest <b>periods</b> used in present value calculations.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Refinancing occurs when borrowers make new borrowing arrangements at the new <b>lower</b> prevailing market interest rates.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Spread compression does not occur automatically, because an insurer can offer lower interest rates to keep its spread constant instead of offering customers a higher rate. But, by refusing to offer customers the higher market interest rate, existing customers are less likely to continue business with the insurer, and new customers may be harder to attract.</p><p class=\"explanations\">Spread expansion, which is a widening of an insurer’s interest spread, occurs when market interest rates fall and the insurer reduces interest-crediting rates to the new market level while continuing to earn a higher overall rate of return on its existing invested assets. Decreasing market interest rates create the opportunity for spread expansion, but they do not guarantee it. Borrowers who are paying older and higher interest rates may refinance to repay their debts in full before repayment is due.</p><p class=\"explanations\"><b>Learning Objective: 7G. Describe the effects on insurers when market interest rates are decreasing, increasing, or remaining at a sustained low level.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_070'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_071';
objQuestion.questionID = 121348;
objQuestion.item = 'LOMA_371_PPQ2021_071';
objQuestion.primaryLO = '7H';
objQuestion.textref = 'c. 7, pp. 21-22';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7H';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">To manage interest-rate risk associated with the general account, life insurance companies rely on asset-liability management (ALM) programs and a simple control cycle of steering controls, concurrent controls, and feedback controls. Methods of managing interest-rate risk that can be implemented during product design include</p><ol type=\"A\" class=\"combo\"><li>Employing floating interest rates for policy loans</li><li>Designing a lower minimum guaranteed interest-crediting rate, where regulations permit</li><li>Shortening the guarantee period for minimum guaranteed interest-crediting rates</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A, B, and C";
arrAnsChoices[1] = "A and B only";
arrAnsChoices[2] = "A and C only";
arrAnsChoices[3] = "B and C only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490741;
arrAnsIDs[1] = 490742;
arrAnsIDs[2] = 490743;
arrAnsIDs[3] = 490744;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Incorporating nonguaranteed elements (NGEs) in product design, such as policy dividends on participating fixed premium life insurance policies, is another method of managing interest-rate risk that can be implemented during product design. Insurers can take a number of corrective actions, such as offsetting specified interest-rate risks with purchases of derivative securities, to address potential deviations from the company’s interest-rate risk standards.</p><p class=\"explanations\">A typical steering control for interest-rate risk is the initial interest-crediting rate on a product. A typical concurrent control is the automatic checks in a system. A typical feedback control is an internal audit. Concurrent and feedback controls monitor and compare actual performance or output with established standards such as the policies, procedures, risk tolerances, and codes of conduct that were established as steering controls. Ultimately, insurers must use a wide variety of controls to manage interest-rate risk, with the understanding that market interest rates are beyond an insurer’s control.</p><p class=\"explanations\"><b>Learning Objective: 7H. Describe common strategies for managing interest-rate risk.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that employing floating interest rates for policy loans and designing a lower minimum guaranteed interest-crediting rate, where regulations permit, are methods of managing interest-rate risk that can be implemented during product design. However, this is <b>not</b> the correct answer choice.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that employing floating interest rates for policy loans and shortening the guarantee period for minimum guaranteed interest-crediting rates are methods of managing interest-rate risk that can be implemented during product design. However, this is <b>not</b> the correct answer choice.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that designing a lower minimum guaranteed interest-crediting rate, where regulations permit, and shortening the guarantee period for minimum guaranteed interest-crediting rates are methods of managing interest-rate risk that can be implemented during product design. However, this is <b>not</b> the correct answer&nbsp;choice.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_071'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_072';
objQuestion.questionID = 121349;
objQuestion.item = 'LOMA_371_PPQ2021_072';
objQuestion.primaryLO = '7I';
objQuestion.textref = 'c. 7, pp. 25-26';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7I';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Sania Rashid is calculating the net present value (NPV) of a proposed investment project at the Accolade Life Insurance Company. Ms.&nbsp;Rashid selected a 10% interest rate, which reflects the risk associated with the project’s financial results over the life of the project. The project has an initial investment of $175,000 and is expected to provide earnings of $50,000 at the end of each of the next 5 years. Below is a portion of a present value interest factors (PVIF) table that shows 5 interest periods (<i>n</i>) at a 10% interest rate (<i>i</i>). Ms.&nbsp;Rashid used this table to calculate the NPV of this&nbsp;project.</p><table class=\"tbexam\" align=\"center\"><tr><td style=\"vertical-align: middle; text-align: left; background-color: #DCDCDC;\"><b>Periods (n)</b></td><td style=\"vertical-align: middle; text-align: left; background-color: #DCDCDC;\"><b>10% Interest rate (i)</b></td></tr><tr><td style=\"vertical-align: middle; text-align: center;\">1</td><td style=\"vertical-align: middle; text-align: center;\">0.909</td></tr><tr><td style=\"vertical-align: middle; text-align: center;\">2</td><td style=\"vertical-align: middle; text-align: center;\">0.826</td></tr><tr><td style=\"vertical-align: middle; text-align: center;\">3</td><td style=\"vertical-align: middle; text-align: center;\">0.751</td></tr><tr><td style=\"vertical-align: middle; text-align: center;\">4</td><td style=\"vertical-align: middle; text-align: center;\">0.683</td></tr><tr><td style=\"vertical-align: middle; text-align: center;\">5</td><td style=\"vertical-align: middle; text-align: center;\">0.621</td></tr></table><p class=\"stem\">This information indicates that Ms.&nbsp;Rashid correctly determined that the NPV of this project equals</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "–$113,625";
arrAnsChoices[1] = "–$77,625";
arrAnsChoices[2] = "$14,500";
arrAnsChoices[3] = "$75,000";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490745;
arrAnsIDs[1] = 490746;
arrAnsIDs[2] = 490747;
arrAnsIDs[3] = 490748;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The NPV of an investment project is calculated by subtracting the project’s initial investment from the present value of the project’s earnings over a certain period, usually the entire expected life of the product. In this situation, the project’s initial investment is $175,000, and the present value of the project’s earnings is calculated as [($50,000&nbsp;×&nbsp;0.909) + ($50,000&nbsp;×&nbsp;0.826) + ($50,000&nbsp;×&nbsp;0.751) + ($50,000&nbsp;×&nbsp;0.683) + ($50,000&nbsp;×&nbsp;0.621)] = $45,450 + $41,300 + $37,550 + $34,150 + $31,050 = $186,126. In this situation, the project’s NPV equals $189,500&nbsp;–&nbsp;$175,000 = $14,500.</p><p class=\"explanations\">If NPV is a positive number, then the product is expected to earn a profit as long as the assumptions are accurate. The general rule for NPV is that as long as a proposed product’s NPV is positive, the insurer should consider pursuing the product. Because this project’s NPV is positive, Ms.&nbsp;Rashid most likely would recommend that Accolade accept the project.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The NPV of an investment project is calculated by subtracting the project’s initial investment from the present value of the project’s earnings over a certain period, usually the entire expected life of the product. In this situation, the project’s initial investment is $175,000, and the present value of the project’s earnings is calculated as [($50,000&nbsp;×&nbsp;0.909) + ($50,000&nbsp;×&nbsp;0.826) + ($50,000&nbsp;×&nbsp;0.751) + ($50,000&nbsp;×&nbsp;0.683) + ($50,000&nbsp;×&nbsp;0.621)] = $45,450 + $41,300 + $37,550 + $34,150 + $31,050 = $186,126. In this situation, the project’s NPV equals $189,500&nbsp;–&nbsp;$175,000 = $14,500.</p><p class=\"explanations\">If NPV is a positive number, then the product is expected to earn a profit as long as the assumptions are accurate. The general rule for NPV is that as long as a proposed product’s NPV is positive, the insurer should consider pursuing the product. Because this project’s NPV is positive, Ms.&nbsp;Rashid most likely would recommend that Accolade accept the project.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The NPV of an investment project is calculated by subtracting the project’s initial investment from the present value (PV) of the project’s earnings over a certain period, usually the entire expected life of the product. An insurer selects an interest rate, <i>i</i>, that reflects the return the insurer believes would be necessary to accept the risk inherent in the project. If an insurer selects a 10% interest rate, the insurer has decided it is willing to accept the risk the new product represents as long as the product’s estimated return over the period is at least 10%. Insurers generally select lower interest rates for products that represent lower risks and higher interest rates for products that represent higher risks.</p><p class=\"explanations\">In this situation, the project’s initial investment is $175,000, and the present value of the project’s earnings is calculated as [($50,000&nbsp;×&nbsp;0.909) + ($50,000&nbsp;×&nbsp;0.826) + ($50,000&nbsp;×&nbsp;0.751) + ($50,000&nbsp;×&nbsp;0.683) + ($50,000&nbsp;×&nbsp;0.621)] = $45,450 + $41,300 + $37,550 + $34,150 + $31,050 = $186,126. In this situation, the project’s NPV equals $189,500&nbsp;–&nbsp;$175,000 = $14,500.</p><p class=\"explanations\">If NPV is a positive number, then the product is expected to earn a profit as long as the assumptions are accurate. The general rule for NPV is that as long as a proposed product’s NPV is positive, the insurer should consider pursuing the product. Because this project’s NPV is positive, Ms.&nbsp;Rashid most likely would recommend that Accolade accept the project.</p><p class=\"explanations\"><b>Learning Objective: 7I. Define and calculate profitability measures such as net present value, internal rate of return, and profit margin.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The NPV of an investment project is calculated by subtracting the project’s initial investment from the present value of the project’s earnings over a certain period, usually the entire expected life of the product. In this situation, the project’s initial investment is $175,000, and the present value of the project’s earnings is calculated as [($50,000&nbsp;×&nbsp;0.909) + ($50,000&nbsp;×&nbsp;0.826) + ($50,000&nbsp;×&nbsp;0.751) + ($50,000&nbsp;×&nbsp;0.683) + ($50,000&nbsp;×&nbsp;0.621)] = $45,450 + $41,300 + $37,550 + $34,150 + $31,050 = $186,126. In this situation, the project’s NPV equals $189,500&nbsp;–&nbsp;$175,000 = $14,500.</p><p class=\"explanations\">If NPV is a positive number, then the product is expected to earn a profit as long as the assumptions are accurate. The general rule for NPV is that as long as a proposed product’s NPV is positive, the insurer should consider pursuing the product. Because this project’s NPV is positive, Ms.&nbsp;Rashid most likely would recommend that Accolade accept the project.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_072'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_073';
objQuestion.questionID = 121350;
objQuestion.item = 'LOMA_371_PPQ2021_073';
objQuestion.primaryLO = '7I';
objQuestion.textref = 'c. 7, pp. 26-27';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7I';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Tiller Life Insurance Company is evaluating the internal rate of return (IRR) of two life insurance products that Tiller is considering developing. Product X has a projected IRR of 17% and Product Y has a projected IRR of 12%. Each product has a risk-adjusted minimum IRR of 14%. Select the answer choice that correctly identifies whether Tiller most likely would proceed with developing Product X and Product Y.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[-1] = "<u>Product X</u></div><div class=\"anshead\"><u>Product Y</u>";
arrAnsChoices[0] = "yes</div><div class=\"anscell\" onclick=\"recordAns(1);\">yes";
arrAnsChoices[1] = "yes</div><div class=\"anscell\" onclick=\"recordAns(2);\">no";
arrAnsChoices[2] = "no</div><div class=\"anscell\" onclick=\"recordAns(3);\">yes";
arrAnsChoices[3] = "no</div><div class=\"anscell\" onclick=\"recordAns(4);\">no";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490750;
arrAnsIDs[1] = 490751;
arrAnsIDs[2] = 490752;
arrAnsIDs[3] = 490753;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that, in this situation, Tiller most likely would proceed with developing Product X. However, Tiller most likely would <b>not</b> proceed with developing Product Y.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Insurers that wish to account for the level of risk in a product’s cash flows set a risk-adjusted minimum IRR<i> </i>for a product and then compare the product’s projected IRR to the risk-adjusted minimum&nbsp;IRR. A simple decision rule is to require that the projected IRR be greater than or equal to the insurer’s risk-adjusted minimum IRR for the product. If the projected IRR is less than the risk-adjusted minimum IRR, then the insurer will likely not proceed with developing the product as is.</p><p class=\"explanations\">In Tiller’s situation, Product X has a 17% projected IRR, which is greater than the product’s risk-adjusted minimum IRR of 14%. Product Y has a 12% projected IRR, which is less than the product’s risk-adjusted minimum IRR of 14%. Thus, Tiller most likely will develop Product X but not Product Y.</p><p class=\"explanations\">Some insurers refer to the IRR as the return on investment (ROI). For example, an insurer determines that the NPV for its proposed new product would be equal to zero when the interest rate is 12%; therefore, the projected IRR for the product is 12%.</p><p class=\"explanations\">An insurer can instead use its hurdle rate as the required IRR. A hurdle rate, or required return, is a minimum percentage rate of return on capital that an insurer must earn to cover its cost of capital. Although the methods used to calculate the cost of capital vary, they generally involve a combination of the various interest costs, transaction costs, and cost of equity an insurer pays for funds. An insurer’s hurdle rate is independent of product risk, and typically applies to all products and all lines of business.</p><p class=\"explanations\"><b>Learning Objective: 7I. Define and calculate profitability measures such as net present value, internal rate of return, and profit margin.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">In this situation, Tiller most likely <b>would</b> proceed with developing Product X. However, Tiller most likely would <b>not</b> proceed with developing Product Y.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that, in this situation, Tiller most likely would not proceed with developing Product Y. However, Tiller most likely <b>would</b> proceed with developing Product X.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_073'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_074';
objQuestion.questionID = 121351;
objQuestion.item = 'LOMA_371_PPQ2021_074';
objQuestion.primaryLO = '7I';
objQuestion.textref = 'c. 7, pp. 27-28';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7I';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Wei Huang calculated the profit margin for a new insurance product developed by the Anchor Life Insurance Company. Mr.&nbsp;Huang, who used a 5% interest rate in his calculation, gathered the following PVIFs:</p><ul class=\"examul\"><li>PVIF (0, 5%) = 1.000</li><li>PVIF (1, 5%) = 0.952</li><li>PVIF (2, 5%) = 0.907</li><li>PVIF (3, 5%) = 0.864</li></ul><p class=\"stem\">The new product has the following expected premiums and profits for the next 3 policy years:</p><table class=\"tbexam\" align=\"center\"><tr><td style=\"vertical-align: middle; text-align: left; background-color: #DCDCDC;\"><b>Policy Year</b></td><td style=\"vertical-align: middle; text-align: left; background-color: #DCDCDC;\"><b>Premiums</b></td><td style=\"vertical-align: middle; text-align: left; background-color: #DCDCDC;\"><b>Profit</b></td></tr><tr><td style=\"vertical-align: middle; text-align: left;\">1</td><td style=\"vertical-align: middle; text-align: left;\">$75,000</td><td style=\"vertical-align: middle; text-align: left;\">$25,000</td></tr><tr><td style=\"vertical-align: middle; text-align: left;\">2</td><td style=\"vertical-align: middle; text-align: left;\">$60,000</td><td style=\"vertical-align: middle; text-align: left;\">$15,000</td></tr><tr><td style=\"vertical-align: middle; text-align: left;\">3</td><td style=\"vertical-align: middle; text-align: left;\">$55,000</td><td style=\"vertical-align: middle; text-align: left;\">$10,000</td></tr></table><p class=\"stem\">Mr.&nbsp;Huang assumed that Anchor will receive premium income at the beginning of each year and will earn profits at the end of each year. This information indicates that Mr.&nbsp;Huang correctly determined that, at an interest rate of 5%, the profit margin on this product equals</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "3.95%";
arrAnsChoices[1] = "12.75%";
arrAnsChoices[2] = "25.30%";
arrAnsChoices[3] = "27.89%";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490754;
arrAnsIDs[1] = 490755;
arrAnsIDs[2] = 490756;
arrAnsIDs[3] = 490757;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">For a multiple-premium life insurance or an annuity product, the product’s profit margin equals the PV of the product’s profits divided by the PV of the product’s premiums. Because Mr. Huang assumes that profits are earned at the end of each year, he calculates the PV of profits using the PVIFs for period <i>n</i> and interest rate <i>i</i>. Therefore, the PV of the product’s profits equals ($25,000 × 0.952) + ($15,000 × 0.907) + ($10,000 × 0.864) = $23,800 + $13,605 + $8,640 = $46,045. </p><p class=\"explanations\">Because Mr. Huang assumes that premiums are received at the beginning of each year, he calculates the PV of premiums using the PVIFs for period (<i>n</i> – 1) and interest rate <i>i</i>. Therefore, the PV of the product’s premiums equals: ($75,000 × 1.000) + ($60,000 × 0.952) + ($55,000 × 0.907) = $75,000 + $57,120 + $49,885 = $182,005. The product’s profit margin equals: $46,045 ÷ $182,005 = 25.30%.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">For a multiple-premium life insurance or an annuity product, the product’s profit margin equals the PV of the product’s profits divided by the PV of the product’s premiums. Because Mr. Huang assumes that profits are earned at the end of each year, he calculates the PV of profits using the PVIFs for period <i>n</i> and interest rate <i>i</i>. Therefore, the PV of the product’s profits equals ($25,000 × 0.952) + ($15,000 × 0.907) + ($10,000 × 0.864) = $23,800 + $13,605 + $8,640 = $46,045. </p><p class=\"explanations\">Because Mr. Huang assumes that premiums are received at the beginning of each year, he calculates the PV of premiums using the PVIFs for period (<i>n</i> – 1) and interest rate <i>i</i>. Therefore, the PV of the product’s premiums equals: ($75,000 × 1.000) + ($60,000 × 0.952) + ($55,000 × 0.907) = $75,000 + $57,120 + $49,885 = $182,005. The product’s profit margin equals: $46,045 ÷ $182,005 = 25.30%.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">For a multiple-premium life insurance or an annuity product, the product’s profit margin equals the PV of the product’s profits divided by the PV of the product’s premiums. Because Mr. Huang assumes that profits are earned at the end of each year, he calculates the PV of profits using the PVIFs for period <i>n</i> and interest rate <i>i</i>. Therefore, the PV of the product’s profits equals ($25,000 × 0.952) + ($15,000 × 0.907) + ($10,000 × 0.864) = $23,800 + $13,605 + $8,640 = $46,045. </p><p class=\"explanations\">Because Mr. Huang assumes that premiums are received at the beginning of each year, he calculates the PV of premiums using the PVIFs for period (<i>n</i> – 1) and interest rate <i>i</i>. Therefore, the PV of the product’s premiums equals: ($75,000 × 1.000) + ($60,000 × 0.952) + ($55,000 × 0.907) = $75,000 + $57,120 + $49,885 = $182,005. The product’s profit margin equals: $46,045 ÷ $182,005 = 25.30%.</p><p class=\"explanations\"><b>Learning Objective: 7I. Define and calculate profitability measures such as net present value, internal rate of return, and profit margin.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">For a multiple-premium life insurance or an annuity product, the product’s profit margin equals the PV of the product’s profits divided by the PV of the product’s premiums. Because Mr. Huang assumes that profits are earned at the end of each year, he calculates the PV of profits using the PVIFs for period <i>n</i> and interest rate <i>i</i>. Therefore, the PV of the product’s profits equals ($25,000 × 0.952) + ($15,000 × 0.907) + ($10,000 × 0.864) = $23,800 + $13,605 + $8,640 = $46,045. </p><p class=\"explanations\">Because Mr. Huang assumes that premiums are received at the beginning of each year, he calculates the PV of premiums using the PVIFs for period (<i>n</i> – 1) and interest rate <i>i</i>. Therefore, the PV of the product’s premiums equals: ($75,000 × 1.000) + ($60,000 × 0.952) + ($55,000 × 0.907) = $75,000 + $57,120 + $49,885 = $182,005. The product’s profit margin equals: $46,045 ÷ $182,005 = 25.30%.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_074'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['7A'] = "7A. Describe how an insurer’s general account and separate account affect the insurer’s investment earnings.";
arrlotext['7B'] = "7B. Define investment concepts such as <i>price appreciation</i>, <i>price depreciation</i>, and <i>rate of return</i>.";
arrlotext['7C'] = "7C. Explain the time value of money and the relationship between present value and future value.";
arrlotext['7D'] = "7D. Explain the applications for future values and present values.";
arrlotext['7E'] = "7E. Define a product’s crediting rates and interest spread and explain how an insurer determines these elements for life insurance and annuity products.";
arrlotext['7F'] = "7F. Explain how actuaries account for cash values and accumulated values in product design.";
arrlotext['7G'] = "7G. Describe the effects on insurers when market interest rates are decreasing, increasing, or remaining at a sustained low level.";
arrlotext['7H'] = "7H. Describe common strategies for managing interest-rate risk.";
arrlotext['7I'] = "7I. Define and calculate profitability measures such as net present value, internal rate of return, and profit margin.";
