var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2021';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 371 Practice Questions, Chapter 8";
var coursename = 'LOMA 371';
var modulenumber = 3;
var title = "LOMA_371_PPQ2021_0_8";
var intNumPools = 1;
var numQ = 10;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Risk Management and Product Design for Insurance Companies, Third Edition (2020)";
arrNumChap[0] = 1;
var thisChap = '8';

objPool = new Object(); 
objPool.intSelectCount = 10;
objPool.formID = 2617;
objPool.formName = 'PPQ2021_0_8';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_371_PQ_075';
arrPoolQuestions[1] = 'LOMA_371_PQ_076';
arrPoolQuestions[2] = 'LOMA_371_PQ_077';
arrPoolQuestions[3] = 'LOMA_371_PQ_078';
arrPoolQuestions[4] = 'LOMA_371_PQ_079';
arrPoolQuestions[5] = 'LOMA_371_PQ_080';
arrPoolQuestions[6] = 'LOMA_371_PQ_081';
arrPoolQuestions[7] = 'LOMA_371_PQ_082';
arrPoolQuestions[8] = 'LOMA_371_PQ_083';
arrPoolQuestions[9] = 'LOMA_371_PQ_084';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_075';
objQuestion.questionID = 121352;
objQuestion.item = 'LOMA_371_PPQ2021_075';
objQuestion.primaryLO = '8A';
objQuestion.textref = 'c. 8, pp. 2-3';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '8A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">For this question, if answer choices (1) through (3) are all correct, select answer choice (4). Otherwise, select the one correct response.</p><p class=\"stem\">To estimate the amount and timing of future annuity benefit payments as accurately as possible, an insurer must make assumptions regarding mortality, which affects the timing and amount of benefit payments. For life annuities in the payout phase, calculating mortality helps an insurer to determine</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "its cost to set annuity payout factors";
arrAnsChoices[1] = "its cost to establish annuity reserves";
arrAnsChoices[2] = "its cost to provide periodic annuity benefit payments";
arrAnsChoices[3] = "all of the above";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490758;
arrAnsIDs[1] = 490759;
arrAnsIDs[2] = 490760;
arrAnsIDs[3] = 490761;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that, for life annuities in the payout phase, calculating mortality helps an insurer to determine its cost to set annuity payout factors, which are used to determine the periodic payment. However, this is <b>not</b> the correct answer choice.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that, for life annuities in the payout phase, calculating mortality helps an insurer to determine its cost to establish annuity reserves. However, this is <b>not</b> the correct answer choice.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that, for life annuities in the payout phase, calculating mortality helps an insurer to determine its cost to provide periodic payments. However, this is <b>not</b> the correct answer choice.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Mortality affects the timing and amount of benefit payments in a variety of ways. For annuities in the accumulation phase, contract terminations from all causes influence the cost of benefits. In general, the effect of mortality on the cost of benefits is limited to any account values payable on the death of the contract owner. Mortality estimates affect the payout factors guaranteed in the contract and affect the pricing of death benefit options under optional rider benefits and guaranteed death benefits.</p><p class=\"explanations\">For life insurance policies, mortality determines when an insurer must make benefit payments. Insurers project death benefits using historical mortality data to estimate the pattern of deaths in an insured group. They also project life insurance terminations for causes other than death using historical lapse data.</p><p class=\"explanations\"><b>Learning Objective: 8A. Describe how mortality affects the cost of benefits for life insurance and annuity products and define terms related to mortality.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_075'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_076';
objQuestion.questionID = 121353;
objQuestion.item = 'LOMA_371_PPQ2021_076';
objQuestion.primaryLO = '8A';
objQuestion.textref = 'c. 8, pp. 3-4';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '8A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">By definition, the <i>number</i> of deaths that actually occurs in a given group of people is known as</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "tabular mortality";
arrAnsChoices[1] = "assumed mortality";
arrAnsChoices[2] = "mortality experience";
arrAnsChoices[3] = "expected mortality";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490762;
arrAnsIDs[1] = 490763;
arrAnsIDs[2] = 490764;
arrAnsIDs[3] = 490765;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The mortality rates that are shown in mortality tables are known as <b>tabular mortality rates</b>.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Assumed mortality refers to the <b>hypothetical or assumed </b>number or rate of deaths in a given group of&nbsp;people.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Mortality rates are used to calculate mortality. A mortality rate is the rate at which death occurs among a defined group, or cohort, of people during a specified period, usually one year. Cohorts may be classified by age, gender, tobacco use (smoking) status, or other characteristics.</p><p class=\"explanations\"><b>Learning Objective: 8A. Describe how mortality affects the cost of benefits for life insurance and annuity products and define terms related to mortality.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Expected mortality refers to the number or rate of deaths <b>statistically likely to occur</b> in a group of people at a given age.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_076'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_077';
objQuestion.questionID = 121354;
objQuestion.item = 'LOMA_371_PPQ2021_077';
objQuestion.primaryLO = '8B';
objQuestion.textref = 'c. 8, pp. 3-4';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '8B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Actuaries develop mortality assumptions for a variety of purposes, including pricing, reserving, and product modeling for a life insurance or annuity product. As part of the basic process for developing mortality assumptions, actuaries develop mortality rates that have been adjusted to reflect a hypothetical number of rate of deaths in a given block of people. These mortality rates, which are entered into the actuarial models of products, are known as</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "basic mortality rates";
arrAnsChoices[1] = "expected mortality rates";
arrAnsChoices[2] = "experience mortality rates";
arrAnsChoices[3] = "assumed mortality rates";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490766;
arrAnsIDs[1] = 490767;
arrAnsIDs[2] = 490768;
arrAnsIDs[3] = 490769;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">As part of the basic process for developing mortality assumptions, an actuary first calculates experience mortality rates and then creates a table of basic mortality rates. From this table, the actuary creates a curve of expected mortality rates, and, if necessary, may adjust this curve to create useful mortality assumptions in the form of assumed mortality rates.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">As part of the basic process for developing mortality assumptions, an actuary first calculates experience mortality rates and then creates a table of basic mortality rates. From this table, the actuary creates a curve of expected mortality rates, and, if necessary, may adjust this curve to create useful mortality assumptions in the form of assumed mortality rates.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">As part of the basic process for developing mortality assumptions, an actuary first calculates experience mortality rates and then creates a table of basic mortality rates. From this table, the actuary creates a curve of expected mortality rates, and, if necessary, may adjust this curve to create useful mortality assumptions in the form of assumed mortality rates.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">An actuary begins estimating mortality costs for a given purpose by identifying appropriate mortality experience and calculating experience mortality rates. Next, the actuary develops a basic mortality table that best fits the experience mortality rates. Extrapolating from the basic mortality rates, the actuary creates a curve of expected mortality rates.</p><p class=\"explanations\">The actuary may be able to use the curve of expected mortality rates without further adjustment. However, adjustments may be necessary to ensure that the data is credible enough for the insurer to rely on it. By adjusting expected mortality, the actuary creates useful mortality assumptions in the form of assumed mortality rates, which are entered into actuarial models of products.</p><p class=\"explanations\"><b>Learning Objective: 8B. Describe a basic process for developing mortality assumptions.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_077'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_078';
objQuestion.questionID = 121355;
objQuestion.item = 'LOMA_371_PPQ2021_078';
objQuestion.primaryLO = '8C';
objQuestion.textref = 'c. 8, pp. 6-7';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '8C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statement(s) can correctly be made about performing calculations on data from a mortality table:</p><ol type=\"A\" class=\"combo\"><li>Even if an insured in the cohort surrenders, lapses, or otherwise ends her policy, the insurer tracks that individual’s mortality after the policy ends.</li><li>For a given age and cohort, the sum of the mortality rate and the survival rate always equals 1.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490770;
arrAnsIDs[1] = 490771;
arrAnsIDs[2] = 490772;
arrAnsIDs[3] = 490773;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is incorrect. A mortality table begins with a cohort of 100,000 members. The size of the cohort decreases each year as cohort members die. The number representing the size of the cohort is based on the concept of exposure, or how many individuals in the age group were “exposed” to death during the time period in question. If an insured in the cohort surrenders, lapses, or otherwise ends her policy, the insurer can <b>no</b> longer accurately track that individual’s mortality after the policy ends.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement A is incorrect. A mortality table begins with a cohort of 100,000 members. The size of the cohort decreases each year as cohort members die. The number representing the size of the cohort is based on the concept of exposure, or how many individuals in the age group were “exposed” to death during the time period in question. If an insured in the cohort surrenders, lapses, or otherwise ends her policy, the insurer can no longer accurately track that individual’s mortality after the policy ends.</p><p class=\"explanations\">Statement B is correct. Actuaries calculate the mortality rate by dividing the number of deaths by a number representing the size of the cohort. Mortality tables can also provide survival rates for each age, which are particularly useful for designing annuities. Calculate the survival rate either by dividing the number of survivors by the size of the cohort or by subtracting the equivalent mortality rate from 1.</p><p class=\"explanations\"><b>Learning Objective: 8C. Identify and perform calculations on data from a mortality table.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_078'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_079';
objQuestion.questionID = 121356;
objQuestion.item = 'LOMA_371_PPQ2021_079';
objQuestion.primaryLO = '8C';
objQuestion.textref = 'c. 8, pp. 5-7';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '8C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Use the following portion of a basic annuity mortality table for men to answer this question.</p><table class=\"tbexam\" align=\"center\"><tr><td style=\"vertical-align: middle; text-align: left; background-color: #DCDCDC;\"><b>Age</b></td><td style=\"vertical-align: middle; text-align: center; background-color: #DCDCDC;\"><b>Mortality rate<br />per 1,000</b></td><td style=\"vertical-align: middle; text-align: center; background-color: #DCDCDC;\"><b>Number<br />Living</b></td><td style=\"vertical-align: middle; text-align: center; background-color: #DCDCDC;\"><b>Number<br />Dying</b></td></tr><tr><td style=\"vertical-align: middle; text-align: left;\">65</td><td style=\"vertical-align: middle; text-align: center;\">8.25</td><td style=\"vertical-align: middle; text-align: center;\">100,000</td><td style=\"vertical-align: middle; text-align: center;\">825</td></tr><tr><td style=\"vertical-align: middle; text-align: left;\">66</td><td style=\"vertical-align: middle; text-align: center;\">9.13</td><td style=\"vertical-align: middle; text-align: center;\">99,175</td><td style=\"vertical-align: middle; text-align: center;\">905</td></tr><tr><td style=\"vertical-align: middle; text-align: left;\">67</td><td style=\"vertical-align: middle; text-align: center;\">??</td><td style=\"vertical-align: middle; text-align: center;\">??</td><td style=\"vertical-align: middle; text-align: center;\">985</td></tr></table><p class=\"stem\">According to this mortality table, the number of men who are expected to survive to age 67 is</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "97,687";
arrAnsChoices[1] = "98,190";
arrAnsChoices[2] = "98,270";
arrAnsChoices[3] = "99,175";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490774;
arrAnsIDs[1] = 490775;
arrAnsIDs[2] = 490776;
arrAnsIDs[3] = 490777;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Determine the number of men who are expected to survive to age 67 by subtracting the number dying at age 66 from the number living at age 66 at the beginning of the year. The mortality table shows the number living at age 66 is 99,175, and the number expected to die at age 66 is 905. Therefore, the number of men who are expected to survive to age 67 is 98,270.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Determine the number of men who are expected to survive to age 67 by subtracting the number dying at age 66 from the number living at age 66 at the beginning of the year. The mortality table shows the number living at age 66 is 99,175, and the number expected to die at age 66 is 905. Therefore, the number of men who are expected to survive to age 67 is 98,270</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Determine the number of men who are expected to survive to age 67 by subtracting the number dying at age 66 from the number living at age 66 at the beginning of the year. The mortality table shows the number living at age 66 is 99,175, and the number expected to die at age 66 is 905. Therefore, the number of men who are expected to survive to age 67 is 98,270.</p><p class=\"explanations\">Another way to calculate the number of men who are expected to survive to age 67 is to subtract the mortality rate of men age 66, which we know is 9.13 per thousand or 0.00913, from 1, to determine the survival rate: 1 – 0.00913 = 0.99087. Then, multiply the survival rate for men age 66 by the number of men living at the beginning of the year: 0.99087 × 99,175 = 98,270.</p><p class=\"explanations\"><b>Learning Objective: 8C. Identify and perform calculations on data from a mortality table.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Determine the number of men who are expected to survive to age 67 by subtracting the number dying at age 66 from the number living at age 66 at the beginning of the year. The mortality table shows the number living at age 66 is 99,175, and the number expected to die at age 66 is 905. Therefore, the number of men who are expected to survive to age 67 is 98,270.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_079'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_080';
objQuestion.questionID = 121357;
objQuestion.item = 'LOMA_371_PPQ2021_080';
objQuestion.primaryLO = '8D';
objQuestion.textref = 'c. 8, pp. 10-11';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '8D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Trio Life Insurance Company is a large insurance company. Trio developed mortality tables that are based primarily on its experience with its own customers and that show the expected mortality rates of people who have recently been underwritten for insurance policies. Trio’s mortality tables can best be described as</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "proprietary, ultimate mortality tables";
arrAnsChoices[1] = "proprietary, select mortality tables";
arrAnsChoices[2] = "published, ultimate mortality tables";
arrAnsChoices[3] = "published, select mortality tables";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490778;
arrAnsIDs[1] = 490779;
arrAnsIDs[2] = 490780;
arrAnsIDs[3] = 490781;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that Trio developed proprietary mortality tables. However, ultimate mortality tables show the expected mortality rates of people who have <b>not</b> recently been underwritten for insurance&nbsp;policies.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Insurers choose the mortality table to use depending on the product type, the purpose of the calculation, the characteristics of the population being studied, and the availability of appropriate statistics based on insurer experience. Mortality tables can be very specific; they also frequently overlap. A single table might be classified as a select mortality table, sex-distinct mortality table, and valuation mortality table.</p><p class=\"explanations\">The use of principles-based reserving (PBR), in which actuarial assumptions and reserve levels change as risk factors change, favors proprietary mortality tables, as they better capture the risks specific to a company. Larger insurance companies are more likely to develop proprietary mortality tables than are smaller insurance companies.</p><p class=\"explanations\">People whose risk characteristics have been evaluated recently are likely to have better mortality risk characteristics during a specified select mortality period following the underwriting evaluation than do people who have not recently undergone an underwriting selection process. Better mortality risk characteristics for life insurance are risk characteristics that indicate lower mortality.</p><p class=\"explanations\"><b>Learning Objective: 8D. Identify the purposes and characteristics of different types of mortality tables.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Published mortality tables, also called public mortality tables, are made available to the <b>general public</b> through printed documents and electronic sources. In addition, ultimate mortality tables show the expected mortality rates of people who have <b>not</b> recently been underwritten for insurance&nbsp;policies.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that Trio developed select mortality tables. However, published mortality tables, also called public mortality tables, are made available to the <b>general public</b> through printed documents and electronic&nbsp;sources.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_080'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_081';
objQuestion.questionID = 121358;
objQuestion.item = 'LOMA_371_PPQ2021_081';
objQuestion.primaryLO = '8E';
objQuestion.textref = 'c. 8, pp. 8-9';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '8E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Insurers do not use the same sets of mortality data for life insurance as they use for annuities because life insureds and annuitants exhibit different mortality patterns. The mortality patterns of life insureds and annuitants are such that, compared to annuitants, <i>life insureds</i> tend to have</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "longer lives, and insurers use lower mortality rates for death benefit pricing than for annuity benefit design";
arrAnsChoices[1] = "longer lives, and insurers use higher mortality rates for death benefit pricing than for annuity benefit design";
arrAnsChoices[2] = "shorter lives, and insurers use lower mortality rates for annuity benefit design than for death benefit pricing";
arrAnsChoices[3] = "shorter lives, and insurers use higher mortality rates for annuity benefit design than for death benefit pricing";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490782;
arrAnsIDs[1] = 490783;
arrAnsIDs[2] = 490784;
arrAnsIDs[3] = 490785;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Life insureds tend to have <b>shorter</b> lives than do annuitants. In addition, insurers use <b>higher</b> mortality rates for death benefit pricing than for annuity benefit design.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that insurers use higher mortality rates for death benefit pricing than for annuity benefit design. However, life insureds tend to have <b>shorter</b> lives than do annuitants.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">When life expectancy increases for the general population, or for a subset of the population, insurers experience a decrease in benefit costs for associated life insurance policies, but an increase in benefit costs for associated life annuities. The risk this trend poses for issuers of life annuities is sometimes called longevity risk.</p><p class=\"explanations\">Insurers sometimes use different sets of mortality data for different products within a line of business and for different classes of underwriting risk within a product. For example, insurers often use lower mortality rates for individual annuities than they do for group annuities, because annuitants of individual annuities tend to live longer than do annuitants of group annuities.</p><p class=\"explanations\"><b>Learning Objective: 8E. Describe the difference between the mortality patterns of different groups and explain the effect these differences have on product design.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that life insureds tend to have shorter lives than do annuitants. However, insurers use <b>lower</b> mortality rates for annuity benefit design than for death benefit pricing.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_081'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_082';
objQuestion.questionID = 121359;
objQuestion.item = 'LOMA_371_PPQ2021_082';
objQuestion.primaryLO = '8F';
objQuestion.textref = 'c. 8, pp. 13-15';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '8F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Two simple methods for modifying tabular mortality rates to reflect mortality changes are the projection method and the setback method. If an actuary used the <i>projection</i> method when pricing a product for a particular group of insureds age 46, then the actuary most likely would</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "multiply the tabular mortality rate for age 46 by a chosen percentage, such as 95% or 102%";
arrAnsChoices[1] = "forecast the mortality rate for age 46 by using the tabular mortality rate for insureds who are at a younger age, such as age 43";
arrAnsChoices[2] = "calculate the product’s premium using the tabular mortality rate for age 46 and then increase the premium by a specified dollar amount";
arrAnsChoices[3] = "build an expected mortality margin into the premium for insureds age 46";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490786;
arrAnsIDs[1] = 490787;
arrAnsIDs[2] = 490788;
arrAnsIDs[3] = 490789;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Tables that have been adjusted using the projection method to account for future changes in mortality are called mortality tables with projection. If an insurer expects people in the specified group to live longer than the tabular mortality rates indicate, the insurer would multiply the tabular rates by a factor less than 100 percent. If the insurer expects people in the specified group to die sooner than the tabular rates indicate, the insurer would multiply the tabular rates by a factor greater than 100 percent.</p><p class=\"explanations\">The setback method of adjusting tabular mortality rates consists of showing future decreases in mortality for people of a given age by using the tabular mortality rate for a younger age, typically values of one to five years younger. A larger age setback could distort the mortality curve.</p><p class=\"explanations\">Building an expected mortality margin into a product’s technical design may help the insurer meet its benefit obligations if actual mortality rates turn out to be different from what was expected. A positive mortality margin can be a source of company profits. For a life insurance death benefit, this results from applying a higher mortality rate than would be found in a basic mortality table. For a life annuity payout results, this results from applying a lower mortality rate than would be found in a basic mortality table.</p><p class=\"explanations\"><b>Learning Objective: 8F. Describe the projection method and the setback method for modifying tabular mortality rates.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The <b>setback </b>method consists of showing future decreases in mortality for people of a given age by using the tabular mortality rate for a younger age.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The projection method involves <b>multiplying</b> the tabular mortality rates by a chosen percentage.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">For insurance companies, a mortality margin is a provision for conservatism in <b>mortality risk projections</b>. Building an expected mortality margin into a product’s technical design may help the insurer meet its benefit obligations if actual mortality rates turn out to be different from what was expected.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_082'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_083';
objQuestion.questionID = 121360;
objQuestion.item = 'LOMA_371_PPQ2021_083';
objQuestion.primaryLO = '8G';
objQuestion.textref = 'c. 8, pp. 15-17';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '8G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Bren Gryce, an actuary at the Sumac Life Insurance Company, calculated the one-year annuity benefit cost for a single life annuity with a $10,000 yearly income payment issued to 71-year-old male annuitant. The tabular mortality rate indicates that the probability of an annuitant’s dying at age 71 is 0.0252. Ms.&nbsp;Gryce correctly determined that the one-year annuity benefit cost for this single life annuity is (<b>$252 / $9,748</b>). Ms.&nbsp;Gryce can build a mortality margin into this annuity product by applying a (<b>lower / higher</b>) mortality rate than would be found in a basic mortality table.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "$252 / lower";
arrAnsChoices[1] = "$252 / higher";
arrAnsChoices[2] = "$9,748 / lower";
arrAnsChoices[3] = "$9,748 / higher";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490790;
arrAnsIDs[1] = 490791;
arrAnsIDs[2] = 490792;
arrAnsIDs[3] = 490793;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that Ms.&nbsp;Gryce can build a mortality margin into this annuity product by applying a lower mortality rate than would be found in a basic mortality table. However, the one-year annuity benefit cost for this single life annuity is <b>not</b> $252.</p><p class=\"explanations\">For a given age and cohort, the sum of the mortality rate and the survival rate always equals 1. If the probability of an annuitant’s dying at age 71 is 0.0252, then the probability of an annuitant’s surviving to age 72 is 1&nbsp;–&nbsp;0.0252 = 0.9748. Therefore, for a yearly income payment of $10,000, the one-year annuity benefit cost is $10,000&nbsp;×&nbsp;0.9748 = $9,748. Another way to calculate the one-year annuity benefit cost is to subtract the yearly income payment times the mortality rate from the yearly income payment: $10,000 – ($10,000 × 0.0252) = $9,748.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Ms.&nbsp;Gryce can build a mortality margin into this annuity product by applying a <b>higher</b> mortality rate than would be found in a basic mortality table. In addition, the one-year annuity benefit cost for this single life annuity is <b>not</b> $252.</p><p class=\"explanations\">For a given age and cohort, the sum of the mortality rate and the survival rate always equals 1. If the probability of an annuitant’s dying at age 71 is 0.0252, then the probability of an annuitant’s surviving to age 72 is 1&nbsp;–&nbsp;0.0252 = 0.9748. Therefore, for a yearly income payment of $10,000, the one-year annuity benefit cost is $10,000&nbsp;×&nbsp;0.9748 = $9,748. Another way to calculate the one-year annuity benefit cost is to subtract the yearly income payment times the mortality rate from the yearly income payment: $10,000 – ($10,000 × 0.0252) = $9,748.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">For a given age and cohort, the sum of the mortality rate and the survival rate always equals 1. If the probability of an annuitant’s dying at age 71 is 0.0252, then the probability of an annuitant’s surviving to age 72 is 1&nbsp;–&nbsp;0.0252 = 0.9748. Therefore, for a yearly income payment of $10,000, the one-year annuity benefit cost is $10,000&nbsp;×&nbsp;0.9748 = $9,748. Another way to calculate the one-year annuity benefit cost is to subtract the yearly income payment times the mortality rate from the yearly income payment: $10,000 – ($10,000 × 0.0252) = $9,748.</p><p class=\"explanations\">A positive mortality margin for a life annuity payout results from applying a lower mortality rate than would be found in a basic mortality table. The insurer assumes that more annuitants will survive to collect benefits, and prepares for potential low-mortality scenarios where its annuity cost of benefits is high. If actual mortality rates are higher than the margin-adjusted mortality rates, then the product’s profits will be&nbsp;higher.</p><p class=\"explanations\"><b>Learning Objective: 8G. Describe a process for setting a mortality charge for a life insurance or annuity product and calculate the mortality cost for a life insurance product and an annuity benefit cost for a life annuity.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that the one-year annuity benefit cost for this single life annuity is $9,748. However, Ms.&nbsp;Gryce can build a mortality margin into this annuity product by applying a <b>higher</b> mortality rate than would be found in a basic mortality table.</p><p class=\"explanations\">For a given age and cohort, the sum of the mortality rate and the survival rate always equals 1. If the probability of an annuitant’s dying at age 71 is 0.0252, then the probability of an annuitant’s surviving to age 72 is 1&nbsp;–&nbsp;0.0252 = 0.9748. Therefore, for a yearly income payment of $10,000, the one-year annuity benefit cost is $10,000&nbsp;×&nbsp;0.9748 = $9,748. Another way to calculate the one-year annuity benefit cost is to subtract the yearly income payment times the mortality rate from the yearly income payment: $10,000 – ($10,000 × 0.0252) = $9,748.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_083'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_084';
objQuestion.questionID = 121361;
objQuestion.item = 'LOMA_371_PPQ2021_084';
objQuestion.primaryLO = '8H';
objQuestion.textref = 'c. 8, pp. 17-18';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '8H';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The relationship between mortality profits and mortality rates is such that, when an insurer has applied a positive margin for life insurance death benefits, mortality profits tend to <i>increase </i>as actual mortality rates (<b>decrease / increase</b>). When an insurer has applied a positive margin for life annuity payout benefits, mortality profits tend to <i>decrease </i>as actual mortality rates (<b>decrease /&nbsp;increase</b>).</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "decrease / decrease";
arrAnsChoices[1] = "decrease / increase";
arrAnsChoices[2] = "increase / decrease";
arrAnsChoices[3] = "increase / increase";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490794;
arrAnsIDs[1] = 490795;
arrAnsIDs[2] = 490796;
arrAnsIDs[3] = 490797;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A positive mortality margin can be a source of company profits. A positive mortality margin for a life insurance death benefit results from applying a higher mortality rate than would be found in a basic mortality table. By assuming that more insureds will die, the insurer prepares for potential high-mortality scenarios where it would have to pay more claims. If actual mortality turns out to be lower than the margin-adjusted mortality rates, the product’s profits will be higher.</p><p class=\"explanations\">A positive mortality margin for a life annuity payout results from applying a lower mortality rate than would be found in a basic mortality table. By assuming that more annuitants will survive to collect benefits, the insurer prepares for potential low-mortality scenarios where the insurer’s cost of benefits is high. If actual mortality rates are higher than the margin-adjusted mortality rates, the product’s profits will be higher.</p><p class=\"explanations\"><b>Learning Objective: 8H. Define a mortality margin and describe its use in life insurance and annuity products.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that, for life insurance death benefits, mortality profits tend to increase as actual mortality rates decrease. A positive mortality margin for a life annuity payout results from applying a lower mortality rate than would be found in a basic mortality table. If actual mortality rates are higher than the margin-adjusted mortality rates, the product’s profits will be higher. Therefore, for life annuity payout benefits, mortality profits tend to decrease as actual mortality rates <b>decrease</b>.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that, for life annuity payout benefits, mortality profits tend to decrease as actual mortality rates decrease. A positive mortality margin for a life insurance death benefit results from applying a higher mortality rate than would be found in a basic mortality table. If actual mortality turns out to be lower than the margin-adjusted mortality rates, the product’s profits will be higher. Therefore, for life insurance death benefits, mortality profits tend to increase as actual mortality rates <b>decrease</b>.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A positive mortality margin for a life insurance death benefit results from applying a higher mortality rate than would be found in a basic mortality table. If actual mortality turns out to be lower than the margin-adjusted mortality rates, the product’s profits will be higher. Therefore, for life insurance death benefits, mortality profits tend to increase as actual mortality rates <b>decrease</b>. A positive mortality margin for a life annuity payout results from applying a lower mortality rate than would be found in a basic mortality table. If actual mortality rates are higher than the margin-adjusted mortality rates, the product’s profits will be higher. Therefore, for life annuity payout benefits, mortality profits tend to decrease as actual mortality rates <b>decrease</b>.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_084'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['8A'] = "8A. Describe how mortality affects the cost of benefits for life insurance and annuity products and define terms related to mortality.";
arrlotext['8B'] = "8B. Describe a basic process for developing mortality assumptions.";
arrlotext['8C'] = "8C. Identify and perform calculations on data from a mortality table.";
arrlotext['8D'] = "8D. Identify the purposes and characteristics of different types of mortality tables.";
arrlotext['8E'] = "8E. Describe the difference between the mortality patterns of different groups and explain the effect these differences have on product design.";
arrlotext['8F'] = "8F. Describe the projection method and the setback method for modifying tabular mortality rates.";
arrlotext['8G'] = "8G. Describe a process for setting a mortality charge for a life insurance or annuity product and calculate the mortality cost for a life insurance product and an annuity benefit cost for a life annuity.";
arrlotext['8H'] = "8H. Define a mortality margin and describe its use in life insurance and annuity products.";
