var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2021';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 371 Practice Questions, Chapter 9";
var coursename = 'LOMA 371';
var modulenumber = 3;
var title = "LOMA_371_PPQ2021_0_9";
var intNumPools = 1;
var numQ = 14;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Risk Management and Product Design for Insurance Companies, Third Edition (2020)";
arrNumChap[0] = 1;
var thisChap = '9';

objPool = new Object(); 
objPool.intSelectCount = 14;
objPool.formID = 2617;
objPool.formName = 'PPQ2021_0_9';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_371_PQ_085';
arrPoolQuestions[1] = 'LOMA_371_PQ_086';
arrPoolQuestions[2] = 'LOMA_371_PQ_087';
arrPoolQuestions[3] = 'LOMA_371_PQ_088';
arrPoolQuestions[4] = 'LOMA_371_PQ_089';
arrPoolQuestions[5] = 'LOMA_371_PQ_090';
arrPoolQuestions[6] = 'LOMA_371_PQ_091';
arrPoolQuestions[7] = 'LOMA_371_PQ_092';
arrPoolQuestions[8] = 'LOMA_371_PQ_093';
arrPoolQuestions[9] = 'LOMA_371_PQ_094';
arrPoolQuestions[10] = 'LOMA_371_PQ_095';
arrPoolQuestions[11] = 'LOMA_371_PQ_096';
arrPoolQuestions[12] = 'LOMA_371_PQ_097';
arrPoolQuestions[13] = 'LOMA_371_PQ_098';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_085';
objQuestion.questionID = 121362;
objQuestion.item = 'LOMA_371_PPQ2021_085';
objQuestion.primaryLO = '9A';
objQuestion.textref = 'c. 9, pp. 3-4';
objQuestion.textbook = 0;
objQuestion.chapter = 9;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '9A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Operating expenses that are relevant to product design can be divided into four broad categories: development expenses, acquisition expenses, maintenance expenses, and overhead expenses. Product implementation costs that an insurer incurs to support a new product line are included in the category of operating expenses known as</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "development expenses";
arrAnsChoices[1] = "acquisition expenses";
arrAnsChoices[2] = "maintenance expenses";
arrAnsChoices[3] = "overhead expenses";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490798;
arrAnsIDs[1] = 490799;
arrAnsIDs[2] = 490800;
arrAnsIDs[3] = 490801;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">An insurer incurs development expenses, or research and development (R&D) expenses—such as product implementation costs—in starting a new product or product line.</p><p class=\"explanations\"><b>Learning Objective: 9A. Identify the primary internal and external sources from which insurance companies gather expense data.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">An insurer incurs acquisition expenses to obtain and issue new life insurance policies and annuity&nbsp;contracts.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">An insurer incurs maintenance expenses, or renewal expenses, while a contract is in force.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">An insurer incurs overhead expenses during normal business operations; overhead expenses are not directly connected to a specific product or service.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_085'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_086';
objQuestion.questionID = 121363;
objQuestion.item = 'LOMA_371_PPQ2021_086';
objQuestion.primaryLO = '9A';
objQuestion.textref = 'c. 9, p. 5';
objQuestion.textbook = 0;
objQuestion.chapter = 9;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '9A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statement(s) can correctly be made about the gathering of expense data and the establishing of expense projections:</p><ol type=\"A\" class=\"combo\"><li>To understand how known expenses are likely to behave and therefore affect profitability, insurers must collect and analyze both internal and external expense experience data.</li><li>Because insurers must include expense projections in all new product designs, all expenses that affect a company’s new products require extensive expense analysis and modeling.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490802;
arrAnsIDs[1] = 490803;
arrAnsIDs[2] = 490804;
arrAnsIDs[3] = 490805;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct. Experience data describe real-world observations of specified phenomena. Internal expense experience data reflect the characteristics and patterns of a company’s own historical expense experience, while external expense experience data reflect the characteristics and patterns of other companies’ historical expense experience.</p><p class=\"explanations\">Statement B is incorrect. Although insurers must include expense projections in all new product designs, not all of the expenses that affect a company’s new products require extensive expense analysis and&nbsp;modeling.</p><p class=\"explanations\"><b>Learning Objective: 9A. Identify the primary internal and external sources from which insurance companies gather expense data.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is incorrect. Although insurers must include expense projections in all new product designs, <b>not</b> all of the expenses that affect a company’s new products require extensive expense analysis and&nbsp;modeling.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_086'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_087';
objQuestion.questionID = 121364;
objQuestion.item = 'LOMA_371_PPQ2021_087';
objQuestion.primaryLO = '9B';
objQuestion.textref = 'c. 9, pp. 7, 8-9';
objQuestion.textbook = 0;
objQuestion.chapter = 9;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '9B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The expense profile of a particular life insurance product is as follows:</p><ul class=\"examul\"><li>Direct expenses (per contract) = $50</li><li>Allocated indirect expenses (per contract) = $30</li></ul><p class=\"stem\">For this product, the operating expense charge under marginal costing is</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "$20";
arrAnsChoices[1] = "$30";
arrAnsChoices[2] = "$50";
arrAnsChoices[3] = "$80";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490806;
arrAnsIDs[1] = 490807;
arrAnsIDs[2] = 490808;
arrAnsIDs[3] = 490809;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Marginal costing, or direct costing, is an accounting method for estimating product-related expenses in which <b>only</b> direct expenses are counted; indirect expenses are <b>not</b> allocated to products.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Marginal costing, or direct costing, is an accounting method for estimating product-related expenses in which <b>only</b> direct expenses are counted; indirect expenses are <b>not</b> allocated to products.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Insurers can use one of two cost accounting methods for life insurance and annuity products. Under full costing, or absorption costing, both direct and allocated indirect expenses are counted. Thus, full costing requires an insurer to allocate all operating expenses to each product line and potentially to each&nbsp;product.</p><p class=\"explanations\">Marginal costing, or direct costing, is an accounting method for estimating product-related expenses in which only direct expenses are counted; indirect expenses are not allocated to products. Marginal costing generally produces a smaller operating expense estimate than full costing produces. To offset this difference, insurers typically set margins that are designed to cover contingencies.</p><p class=\"explanations\"><b>Learning Objective: 9B. Distinguish between full costing and marginal costing and calculate expenses for a product using full costing and marginal costing.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Full costing, or absorption costing, is an accounting method for estimating product-related expenses in which direct and indirect expenses are both counted. However, marginal costing, or direct costing, is an accounting method for estimating product-related expenses in which <b>only</b> direct expenses are counted; indirect expenses are <b>not</b> allocated to products.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_087'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_088';
objQuestion.questionID = 121365;
objQuestion.item = 'LOMA_371_PPQ2021_088';
objQuestion.primaryLO = '9C';
objQuestion.textref = 'c. 9, pp. 7-8';
objQuestion.textbook = 0;
objQuestion.chapter = 9;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '9C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Solace Life Insurance Company issued 50,000 annuity contracts. The expenses associated with issuing these contracts were as follows:</p><ul class=\"examul\"><li>Employee-related expenses = $4,000,000</li><li>Other contract expenses = $10,000,000</li></ul><p class=\"stem\">This information indicates that the unit cost for Solace’s annuity contracts was</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "$80";
arrAnsChoices[1] = "$120";
arrAnsChoices[2] = "$200";
arrAnsChoices[3] = "$280";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490810;
arrAnsIDs[1] = 490811;
arrAnsIDs[2] = 490812;
arrAnsIDs[3] = 490813;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A unit cost, which is the amount of incurred expense attributable to a single measured amount of product, is found by dividing the total relevant cost by the number of designated units of products. In this situation, the unit cost is calculated by adding employee-related expenses to other contract expenses, and then dividing that sum by the number of contracts issued: ($4,000,000 + $10,000,000) ÷ 50,000 = $280.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A unit cost, which is the amount of incurred expense attributable to a single measured amount of product, is found by dividing the total relevant cost by the number of designated units of products. In this situation, the unit cost is calculated by adding employee-related expenses to other contract expenses, and then dividing that sum by the number of contracts issued: ($4,000,000 + $10,000,000) ÷ 50,000 = $280.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A unit cost, which is the amount of incurred expense attributable to a single measured amount of product, is found by dividing the total relevant cost by the number of designated units of products. In this situation, the unit cost is calculated by adding employee-related expenses to other contract expenses, and then dividing that sum by the number of contracts issued: ($4,000,000 + $10,000,000) ÷ 50,000 = $280.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A unit cost, which is the amount of incurred expense attributable to a single measured amount of product, is found by dividing the total relevant cost by the number of designated units of products. In this situation, the unit cost is calculated by adding employee-related expenses to other contract expenses, and then dividing that sum by the number of contracts issued: ($4,000,000 + $10,000,000) ÷ 50,000 = $280.</p><p class=\"explanations\"><b>Learning Objective: 9C. Describe some of the methods that insurance companies use to determine the amount of direct and indirect expenses to assign to a particular product or product line.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_088'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_089';
objQuestion.questionID = 121366;
objQuestion.item = 'LOMA_371_PPQ2021_089';
objQuestion.primaryLO = '9C';
objQuestion.textref = 'c. 9, pp. 9-10';
objQuestion.textbook = 0;
objQuestion.chapter = 9;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '9C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">An insurer categorizes an expense as either direct or indirect and either variable or fixed and then assigns the expense to a particular product or product line. Expenses that are categorized as <i>indirect</i> and <i>fixed</i> expenses for most products include</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "sales commissions";
arrAnsChoices[1] = "premium taxes";
arrAnsChoices[2] = "rent";
arrAnsChoices[3] = "product advertising expenses";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490814;
arrAnsIDs[1] = 490815;
arrAnsIDs[2] = 490816;
arrAnsIDs[3] = 490817;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Sales commissions are categorized as <b>direct</b> expenses and <b>variable</b> expenses for most products.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Premium taxes are categorized as <b>direct</b> expenses and <b>variable</b>&nbsp;expenses for most products.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">For expense control purposes, insurers divide operating expenses into controllable and noncontrollable expenses, direct and indirect expenses, and fixed and variable expenses. A<i> </i>controllable<i> </i>expense is a cost over which a specified manager or organizational unit has power and influence. A<i> </i>noncontrollable expense<i> </i>is a cost over which no specified manager or organizational unit has power or influence.</p><p class=\"explanations\">A direct expense, or traceable cost, is incurred for or physically traceable to a specified life insurance or annuity product. An indirect expense, or common cost, cannot be traced to or is not incurred for a specific product; this expense is incurred whether or not an insurer offers a specific product.</p><p class=\"explanations\">A<i> </i>fixed expense remains relatively constant regardless of the number of policies or contracts sold or the level of operating activity. A variable expense varies in direct proportion to some variation in a specified level of operating&nbsp;activity. A typical expense falls into multiple categories. For example, the cost of product advertising is an acquisition expense, a controllable expense, a direct expense, and a variable expense. Direct expenses often are variable expenses and indirect expenses often are fixed expenses.</p><p class=\"explanations\"><b>Learning Objective: 9C. Describe some of the methods that insurance companies use to determine the amount of direct and indirect expenses to assign to a particular product or product line.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Product advertising expenses are categorized as <b>direct</b> expenses and <b>variable</b> expenses for most products.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_089'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_090';
objQuestion.questionID = 121367;
objQuestion.item = 'LOMA_371_PPQ2021_090';
objQuestion.primaryLO = '9D';
objQuestion.textref = 'c. 9, p. 10';
objQuestion.textbook = 0;
objQuestion.chapter = 9;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '9D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">A heaped commission schedule is a common agent compensation schedule for life insurance sales. One characteristic of a heaped commission schedule is that it</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "features relatively low first-year commissions";
arrAnsChoices[1] = "incentivizes agents to encourage contract owners to keep their contracts in force";
arrAnsChoices[2] = "features relatively high renewal commissions";
arrAnsChoices[3] = "encourages agents to focus on generating new business";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490818;
arrAnsIDs[1] = 490819;
arrAnsIDs[2] = 490820;
arrAnsIDs[3] = 490821;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A heaped commission schedule features relatively <b>high</b> first-year commissions.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A heaped commission schedule <b>encourages</b> agents to focus on generating new&nbsp;business.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A heaped commission schedule features relatively <b>low</b> renewal commissions.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A heaped commission schedule features relatively high first-year commissions and lower renewal commissions. While expensive for the insurer, a heaped commission schedule encourages agents to focus on generating new business.</p><p class=\"explanations\">To stress the importance of persistency, an insurer may increase or decrease production bonuses paid to an agent, depending on whether the agent’s sales show higher or lower persistency, or offer the agent a separate persistency bonus for favorable persistency results.</p><p class=\"explanations\"><b>Learning Objective: 9D. Explain how insurers manage commission expenses for life insurance and annuity products.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_090'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_091';
objQuestion.questionID = 121368;
objQuestion.item = 'LOMA_371_PPQ2021_091';
objQuestion.primaryLO = '9D';
objQuestion.textref = 'c. 9, pp. 9-10';
objQuestion.textbook = 0;
objQuestion.chapter = 9;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '9D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">One type of renewal commission for individual life insurance products becomes vested only after an agent reaches a certain age or number of years with the life insurance company. This type of renewal commission is known, by definition, as a</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "vested commission";
arrAnsChoices[1] = "nonvested commission";
arrAnsChoices[2] = "trail commission";
arrAnsChoices[3] = "conditionally vested commission";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490822;
arrAnsIDs[1] = 490823;
arrAnsIDs[2] = 490824;
arrAnsIDs[3] = 490825;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A vested commission is guaranteed payable to an agent <b>whether or not</b> the agent represents the company when the commission becomes due.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A nonvested commission is payable <b>only if</b> the agent still represents the company when the commission becomes due.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Under an asset-based commission schedule, at regular intervals—usually yearly—<b>after premium payments stop</b>, the agent receives a commission payment known as a trail commission.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Renewal commissions are designed to encourage persistency by providing agents with a continuing stream of income from existing policies. The insurer benefits from steady premium income and less need to make surrender payments.</p><p class=\"explanations\">A vested commission is guaranteed payable to an agent whether or not the agent represents the company when the commission becomes due; a nonvested commission is payable only if the agent still represents the company when the commission becomes due. Under an asset-based commission schedule, at regular intervals—usually yearly—after premium payments stop, the agent receives a commission payment known as a trail commission.</p><p class=\"explanations\"><b>Learning Objective: 9D. Explain how insurers manage commission expenses for life insurance and annuity products.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_091'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_092';
objQuestion.questionID = 121369;
objQuestion.item = 'LOMA_371_PPQ2021_092';
objQuestion.primaryLO = '9D';
objQuestion.textref = 'c. 9, pp. 10-11';
objQuestion.textbook = 0;
objQuestion.chapter = 9;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '9D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">For this question, select the answer choice containing the terms that correctly complete the blanks labeled <B>A</B> and <B>B</B> in the paragraph below.</p><p class=\"stem\">For annuity products, commission schedules typically are either deposit-based or asset-based. Annuity commission schedules that calculate commissions as a percentage of the accumulated value of a deferred annuity contract’s funds are known as <u><b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</b></u> commission schedules. Commissions that are designed to improve persistency are known as <u><b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;B&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</b></u> commissions.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[-1] = "<u>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</u></div><div class=\"anshead\"><u>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;B&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</u>";
arrAnsChoices[0] = "deposit-based</div><div class=\"anscell\" onclick=\"recordAns(1);\">asset-based";
arrAnsChoices[1] = "deposit-based</div><div class=\"anscell\" onclick=\"recordAns(2);\">deposit-based";
arrAnsChoices[2] = "asset-based</div><div class=\"anscell\" onclick=\"recordAns(3);\">asset-based";
arrAnsChoices[3] = "asset-based</div><div class=\"anscell\" onclick=\"recordAns(4);\">deposit-based";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490827;
arrAnsIDs[1] = 490828;
arrAnsIDs[2] = 490829;
arrAnsIDs[3] = 490830;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that asset-based commissions improve persistency. However, deposit- based commissions usually are calculated as a percentage of the <b>annuity’s premium</b>.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Deposit-based commissions usually are calculated as a percentage of the <b>annuity’s premium</b>. In addition, <b>asset-based</b> commissions improve persistency.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Annuity commission schedules generally do not distinguish between first-year and renewal commissions, given that annuities usually feature large initial premiums and much smaller, if any, subsequent premiums. Most insurers today use a combination of deposit-based and asset-based commission schedules for annuity sales. Deposit-based commissions incentivize agents to generate new&nbsp;business. Asset-based commissions incentivize agents to encourage contract owners to keep their contracts in force.</p><p class=\"explanations\">Deposit-based commission schedules pay commissions only on premium payments; the commission is calculated as a percentage of the annuity’s premium. Increasingly, more insurers offer asset-based commission schedules; the commission is a percentage of the accumulated value of a deferred annuity contract’s funds and is payable as long as the contract remains in force.</p><p class=\"explanations\"><b>Learning Objective: 9D. Explain how insurers manage commission expenses for life insurance and annuity products.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that asset-based commissions are calculated as a percentage of the accumulation value of a deferred annuity contract’s funds. However, <b>asset-based</b> commissions improve persistency.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_092'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_093';
objQuestion.questionID = 121370;
objQuestion.item = 'LOMA_371_PPQ2021_093';
objQuestion.primaryLO = '9E';
objQuestion.textref = 'c. 9, pp. 16-17';
objQuestion.textbook = 0;
objQuestion.chapter = 9;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '9E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">When modeling the potential future behavior of policyholders, insurers primarily tend to use fixed and dynamic assumptions. Insurers may use stochastic assumptions if the risk being managed has specific characteristics. One such characteristic is that</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "the volatility of the outcomes is low";
arrAnsChoices[1] = "a given risk is nondiversifiable";
arrAnsChoices[2] = "the future outcomes are likely to have a normal distribution";
arrAnsChoices[3] = "an appropriate hedge is available for a given product risk";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490831;
arrAnsIDs[1] = 490832;
arrAnsIDs[2] = 490833;
arrAnsIDs[3] = 490834;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Traditionally, stochastic modeling is preferable if the underlying risks have specific characteristics, including that the volatility of the outcomes is <b>unknown or high</b>.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Traditionally, stochastic modeling is preferable if the underlying risks have the following characteristics: the volatility of the outcomes is unknown or high; a given risk is nondiversifiable; the future outcomes are likely to have a skewed distribution—that is, a skewed distribution or a “fat tail;” and the insurer lacks an appropriate hedge for a given product risk.</p><p class=\"explanations\">In the context of policyholder behavior, stochastic assumptions are useful when modeling products that contain nonguaranteed elements (NGEs). In life insurance and annuities, NGEs are product features that allow an insurer to reward customers when the insurer has experienced or anticipates it will experience favorable deviations from its assumptions, and to charge customers more when the insurer has experienced or anticipates it will experience unfavorable deviations from its assumptions.</p><p class=\"explanations\"><b>Learning Objective: 9E. Describe how policyholder behavior affects life insurance and annuity product design and modeling.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Traditionally, stochastic modeling is preferable if the underlying risks have specific characteristics, including that the future outcomes are likely to have a <b>skewed</b> distribution or a “fat tail.”</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Traditionally, stochastic modeling is preferable if the underlying risks have specific characteristics, including that the insurer <b>lacks</b> an appropriate hedge for a given product risk.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_093'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_094';
objQuestion.questionID = 121371;
objQuestion.item = 'LOMA_371_PPQ2021_094';
objQuestion.primaryLO = '9F';
objQuestion.textref = 'c. 9, pp. 17-18';
objQuestion.textbook = 0;
objQuestion.chapter = 9;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '9F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The relative size of a margin can be affected by a variety of insurance product characteristics. Generally, it is correct to say that product margins tend to be smaller if</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "investment risk to the insurer is high rather than low";
arrAnsChoices[1] = "marketplace competition is strong rather than weak";
arrAnsChoices[2] = "investment risk to the customer is low rather than high";
arrAnsChoices[3] = "contracts give the customer long-term, rather than short-term, interest-rate guarantees";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490835;
arrAnsIDs[1] = 490836;
arrAnsIDs[2] = 490837;
arrAnsIDs[3] = 490838;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Product margins tend to be smaller if investment risk to the insurer is <b>low</b> rather than high.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">In addition, product margins tend to be smaller if investment risk assumed by the insurer is low rather than high, investment risk assumed by the customer is high rather than low, and contracts give the customer short-term, rather than long-term, interest-rate guarantees.</p><p class=\"explanations\">To help protect against potential losses from adverse deviations from expense projections, insurers may base their expense charges on the results of pessimistic scenarios. If an expense charge is built on a pessimistic scenario, then it is more likely that any deviation from that expectation will be favorable. By basing expense charges on the results of pessimistic scenarios, an insurer essentially creates a margin.</p><p class=\"explanations\"><b>Learning Objective: 9F. Decide whether a given product characteristic is associated with a smaller or a larger margin.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Product margins tend to be smaller if investment risk to the customer is <b>high</b> rather than low.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Product margins tend to be smaller if contracts give the customer <b>short-term</b>, rather than long--term, interest-rate guarantees.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_094'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_095';
objQuestion.questionID = 121372;
objQuestion.item = 'LOMA_371_PPQ2021_095';
objQuestion.primaryLO = '9G';
objQuestion.textref = 'c. 9, pp. 22-23';
objQuestion.textbook = 0;
objQuestion.chapter = 9;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '9G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">For this question, select the answer choice containing the terms that correctly complete the blanks labeled <B>A</B> and <B>B</B> in the paragraph below.</p><p class=\"stem\">Insurers typically classify the explicit expense charges included in fixed insurance and annuity products as administrative charges and transaction charges. Administrative charges usually are assessed as a<b> <u>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</u></b> charge. A surrender charge is a type of <b><u>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;B&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</u></b> charge.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[-1] = "<u>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</u></div><div class=\"anshead\"><u>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;B&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</u>";
arrAnsChoices[0] = "periodic</div><div class=\"anscell\" onclick=\"recordAns(1);\">transaction";
arrAnsChoices[1] = "periodic</div><div class=\"anscell\" onclick=\"recordAns(2);\">administrative";
arrAnsChoices[2] = "one-time</div><div class=\"anscell\" onclick=\"recordAns(3);\">transaction";
arrAnsChoices[3] = "one-time</div><div class=\"anscell\" onclick=\"recordAns(4);\">administrative";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490840;
arrAnsIDs[1] = 490841;
arrAnsIDs[2] = 490842;
arrAnsIDs[3] = 490843;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">For universal life products, insurers typically calculate administrative charges as a flat amount per month based on the units of coverage. Administrative charges also can be calculated as a percentage of premium per period. For fixed immediate annuities, insurers factor administrative charges into the single premium payment. In fixed-rate deferred annuities, the interest spread covers applicable administrative expenses.</p><p class=\"explanations\">Transaction charges include sales charges and surrender charges. For fixed insurance products, sales charges typically are calculated as either a flat amount per transaction or a percentage of the amount of the transaction. Very few fixed-rate deferred annuities offered today assess sales charges.</p><p class=\"explanations\">Insurers use surrender charges to provide protection against surrender and withdrawal rates that exceed projections. For both fixed life insurance products and fixed-rate deferred annuities, surrender charges are a specified percentage of the amount received when the policy or contract is surrendered.</p><p class=\"explanations\"><b>Learning Objective: 9G. Explain how insurers incorporate operating expense charges into the product design of fixed and variable products.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that administrative charges usually are assessed as a periodic charge. However, a surrender charge is a type of <b>transaction </b>charge.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that a surrender charge is a type of transaction<b> </b>charge. However, administrative charges usually are assessed as a <b>periodic</b> charge.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Administrative charges usually are assessed as a <b>periodic</b> charge. In addition, a surrender charge is a type of <b>transaction </b>charge.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_095'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_096';
objQuestion.questionID = 121373;
objQuestion.item = 'LOMA_371_PPQ2021_096';
objQuestion.primaryLO = '9G';
objQuestion.textref = 'c. 9, pp. 22-23';
objQuestion.textbook = 0;
objQuestion.chapter = 9;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '9G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The expense charges included in variable, or unit-linked, products can be categorized as administrative charges and transaction charges. All of the following expense charges can be categorized as <i>administrative</i> charges for variable products <B>EXCEPT</B> for</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "mortality and expense (M&E) risk charges";
arrAnsChoices[1] = "contract maintenance charges";
arrAnsChoices[2] = "fund operating expense charges";
arrAnsChoices[3] = "back-end sales charges";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490844;
arrAnsIDs[1] = 490845;
arrAnsIDs[2] = 490846;
arrAnsIDs[3] = 490847;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">An M&E risk charge <b>is</b> a type of administrative charge assessed to compensate for the mortality and expense risks inherent in the assumptions made when designing the product.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A contract maintenance charge <b>is</b> a type of administrative charge. It is a periodic charge assessed to cover general maintenance costs, such as preparation of account and other statements.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A fund operating expense charge <b>is</b> a type of administrative charge. It is a periodic charge that a fund manager assesses to cover its costs of managing variable subaccount assets, buying and selling securities, and administering trades.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Transaction charges for variable products can be divided into three categories: sales charges, transfer charges, and surrender charges. Variable life insurance products generally include back-end sales charges. A back-end sales charge is a sales charge assessed when an investor sells a security. In the context of variable life insurance and annuity products, the securities sold are typically shares in a subaccount fund. Back-end sales charges are calculated as a percentage of the amount sold.</p><p class=\"explanations\">For variable annuity products, sales charges may be either front-end sales charges or, more commonly, back-end sales charges. A front-end sales charge is a one-time transaction charge imposed when an investor purchases shares in a subaccount. Front-end sales charges generally are calculated as a percentage of the amount invested.</p><p class=\"explanations\">Most insurers allow owners of variable contracts to transfer funds from one subaccount to another without charge, as long as the transfers fall within specified limits, such as amount or frequency. Transfer charges apply to transfers that exceed these limits. Surrender charges on variable products are designed to cover the costs of selling or redeeming fund shares to cover withdrawals or surrenders and are similar to the surrender charges assessed for fixed products.</p><p class=\"explanations\"><b>Learning Objective: 9G. Explain how insurers incorporate operating expense charges into the product design of fixed and variable products.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_096'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_097';
objQuestion.questionID = 121374;
objQuestion.item = 'LOMA_371_PPQ2021_097';
objQuestion.primaryLO = '9H';
objQuestion.textref = 'c. 9, pp. 24-25';
objQuestion.textbook = 0;
objQuestion.chapter = 9;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '9H';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Ace Life Insurance Company is making design adjustments that can help control product risks for its fixed and fixed-fund products, which include fixed-rate universal life insurance, fixed-rate deferred annuities, and variable products that offer fixed fund options. One design adjustment that Ace can make to help control these product risks is to</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "lengthen the guarantee period for minimum guaranteed interest-crediting rates";
arrAnsChoices[1] = "design a higher minimum guaranteed interest-crediting rate, where regulations permit";
arrAnsChoices[2] = "limit withdrawals of account values by monetary amount, frequency, and percentage of account&nbsp;value";
arrAnsChoices[3] = "increase the interval between declarations of new interest-crediting rates on fixed-interest asset&nbsp;accumulations";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490848;
arrAnsIDs[1] = 490849;
arrAnsIDs[2] = 490850;
arrAnsIDs[3] = 490851;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">One design adjustment that Ace can make to help control these product risks is to <b>shorten</b> the guarantee period for minimum guaranteed interest-crediting rates.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">One design adjustment that Ace can make to help control these product risks is to<b> </b>design a <b>lower</b> minimum guaranteed interest-crediting rate, where regulations permit.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Limiting withdrawals of account values by monetary amount, frequency, and percentage of account value also is a design adjustment for limiting product risks for variable universal life insurance and variable deferred&nbsp;annuities.</p><p class=\"explanations\">Other design adjustments to help control product risks for fixed and fixed-fund products include decreasing the interval between declarations of new interest-crediting rates on fixed-interest asset accumulations; decreasing the interval between declarations of new interest-crediting rates on fixed-interest asset accumulations; shortening the guarantee period for minimum guaranteed interest-crediting rates; and designing a lower minimum guaranteed interest-crediting rate, where regulations permit.</p><p class=\"explanations\"><b>Learning Objective: 9H. Describe the strategies that life insurance companies use for managing the risks in life insurance and annuity products.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">One design adjustment that Ace can make to help control these product risks is to <b>decrease</b> the interval between declarations of new interest-crediting rates on fixed-interest asset accumulations.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_097'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_098';
objQuestion.questionID = 121375;
objQuestion.item = 'LOMA_371_PPQ2021_098';
objQuestion.primaryLO = '9H';
objQuestion.textref = 'c. 9, pp. 25-26';
objQuestion.textbook = 0;
objQuestion.chapter = 9;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '9H';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">During product design, life insurers can establish some design features to help manage product risks, including certain forms of policyholder behavior risk. Insurers also can establish additional design adjustments to help manage product risks for fixed and fixed-fund products and variable products. One action that an insurer most likely would take to limit variable deferred annuity product risks is&nbsp;to</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "permit unlimited new premium additions to fixed accounts in a specified period";
arrAnsChoices[1] = "limit total fixed account allocations to a percentage of total allocations";
arrAnsChoices[2] = "eliminate restrictions on the kinds of investments that contract owners can select";
arrAnsChoices[3] = "set no limits on customers’ movements of contract values between subaccounts in a specified&nbsp;period";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490852;
arrAnsIDs[1] = 490853;
arrAnsIDs[2] = 490854;
arrAnsIDs[3] = 490855;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Design adjustments to mitigate risk for variable universal life insurance and variable deferred annuities include <b>limiting</b> new premium additions to fixed accounts in a specified period, such as per calendar&nbsp;quarter.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Examples of limiting total fixed account allocations to mitigate risk for variable universal life insurance and variable deferred annuities include limiting new premium additions to fixed accounts in a specified period, placing a maximum monetary amount limit per account, or limiting total fixed account allocations to a percentage of total allocations.</p><p class=\"explanations\">To address specific risks associated with variable deferred annuities, insurers have adjusted product designs in ways such as imposing restrictions on the kinds of investments that contract owners can select, requiring waiting periods before a contract owner can begin withdrawing guaranteed income from the contract, and using index-based guarantees, which help reduce an insurer’s capital market risk.</p><p class=\"explanations\"><b>Learning Objective: 9H. Describe the strategies that life insurance companies use for managing the risks in life insurance and annuity products.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">To address specific risks associated with variable deferred annuities, insurers have adjusted product designs in ways such as <b>imposing</b> restrictions on the kinds of investments that contract owners can select.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Design adjustments to mitigate risk for variable universal life insurance and variable deferred annuities include <b>limiting</b> customers’ movements of contract values between subaccounts in a specified period (by means of prohibition or assessing additional charges), which also would discourage market-timing abuses and control asset-trading costs.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_098'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['9A'] = "9A. Identify the primary internal and external sources from which insurance companies gather expense data.";
arrlotext['9B'] = "9B. Distinguish between full costing and marginal costing and calculate expenses for a product using full costing and marginal costing.";
arrlotext['9C'] = "9C. Describe some of the methods that insurance companies use to determine the amount of direct and indirect expenses to assign to a particular product or product line.";
arrlotext['9D'] = "9D. Explain how insurers manage commission expenses for life insurance and annuity products.";
arrlotext['9E'] = "9E. Describe how policyholder behavior affects life insurance and annuity product design and modeling.";
arrlotext['9F'] = "9F. Decide whether a given product characteristic is associated with a smaller or a larger margin.";
arrlotext['9G'] = "9G. Explain how insurers incorporate operating expense charges into the product design of fixed and variable products.";
arrlotext['9H'] = "9H. Describe the strategies that life insurance companies use for managing the risks in life insurance and annuity products.";
