var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2020';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 361 Practice Questions, Chapter 10";
var coursename = 'LOMA 361';
var modulenumber = 2;
var title = "LOMA_361_PPQ2019_0_10";
var intNumPools = 1;
var numQ = 12;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Accounting and Financial Reporting in Life Insurance Companies, Second Edition (2019)";
arrNumChap[0] = 1;
var thisChap = '10';

objPool = new Object(); 
objPool.intSelectCount = 12;
objPool.formID = 2103;
objPool.formName = 'PPQ2019_0_10';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_361_PQ_078';
arrPoolQuestions[1] = 'LOMA_361_PQ_079';
arrPoolQuestions[2] = 'LOMA_361_PQ_080';
arrPoolQuestions[3] = 'LOMA_361_PQ_081';
arrPoolQuestions[4] = 'LOMA_361_PQ_082';
arrPoolQuestions[5] = 'LOMA_361_PQ_083';
arrPoolQuestions[6] = 'LOMA_361_PQ_084';
arrPoolQuestions[7] = 'LOMA_361_PQ_085';
arrPoolQuestions[8] = 'LOMA_361_PQ_086';
arrPoolQuestions[9] = 'LOMA_361_PQ_087';
arrPoolQuestions[10] = 'LOMA_361_PQ_088';
arrPoolQuestions[11] = 'LOMA_361_PQ_089';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_078';
objQuestion.questionID = 110264;
objQuestion.item = 'LOMA_361_PPQ2019_078';
objQuestion.primaryLO = '10A';
objQuestion.textref = 'c. 10, pp. 2-3';
objQuestion.textbook = 0;
objQuestion.chapter = 10;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '10A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The annual premium for Karl Rojik’s life insurance policy was due on December 1, but Mr.&nbsp;Rojik had not paid the premium to his insurer as of December 31. Select the answer choice that correctly identifies whether Mr.&nbsp;Rojik’s insurer would classify this premium as unearned income or uncollected income and as an asset or a liability.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[-1] = "<u>Income classification</u></div><div class=\"anshead\"><u>Asset or liability</u>";
arrAnsChoices[0] = "unearned income</div><div class=\"anscell\" onclick=\"recordAns(1);\">liability";
arrAnsChoices[1] = "unearned income</div><div class=\"anscell\" onclick=\"recordAns(2);\">asset";
arrAnsChoices[2] = "uncollected income</div><div class=\"anscell\" onclick=\"recordAns(3);\">liability";
arrAnsChoices[3] = "uncollected income</div><div class=\"anscell\" onclick=\"recordAns(4);\">asset";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445637;
arrAnsIDs[1] = 445638;
arrAnsIDs[2] = 445639;
arrAnsIDs[3] = 445640;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Mr.&nbsp;Rojik’s unpaid premium is <b>not</b> an unearned premium. An unearned premium is a subset of collected income that is received in one reporting period but has not yet been earned; the premium is applicable to insurance coverage to be provided in the following period. In addition, Mr.&nbsp;Rojik’s unpaid premium is <b>not</b> classified as a liability.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that Mr.&nbsp;Rojik’s unpaid premium is classified as an asset. However, Mr.&nbsp;Rojik’s unpaid premium is <b>not</b> an unearned premium. An unearned premium is a subset of collected income that is received in one reporting period but has not yet been earned; the premium is applicable to insurance coverage to be provided in the following period.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that Mr.&nbsp;Rojik’s unpaid premium is classified as uncollected income. However, uncollected income is <b>not</b> classified as a liability.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Uncollected income is income, including uncollected premiums on individual life insurance, that is due before the financial reporting date, but which the insurer has not received as of the financial reporting date. Uncollected income is reported as an asset.</p><p class=\"explanations\">In this situation, Mr.&nbsp;Rojik’s unpaid premium is uncollected income, but it is not an unearned premium. An unearned premium is a subset of collected income that is received in one reporting period but has not yet been earned; the premium is applicable to insurance coverage to be provided in the following period. Unearned income is reported as a liability.</p><p class=\"explanations\"><b>Learning Objective: 10A. Identify the main sources of revenues for life insurance companies.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_078'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_079';
objQuestion.questionID = 110265;
objQuestion.item = 'LOMA_361_PPQ2019_079';
objQuestion.primaryLO = '10B';
objQuestion.textref = 'c. 10, pp. 2-3, 4-5';
objQuestion.textbook = 0;
objQuestion.chapter = 10;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '10B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Selena Yanez is the policyowner of a life insurance policy with the Bulwark Life Insurance Company. The policy anniversary date is October 31, and the $600 semiannual premium payments are due on April 30 and October 31. This year, Ms.&nbsp;Yanez made her first semiannual premium payment on October 31, and her second $600 semiannual premium payment on April 30 of the following year. The following statements are about Bulwark’s accounting and reporting associated with Ms.&nbsp;Yanez’s premium payments. Select the answer choice containing the correct statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Upon receiving Ms.&nbsp;Yanez’s October 31 semiannual payment, Bulwark recorded the $600 as deferred income.";
arrAnsChoices[1] = "If Ms.&nbsp;Yanez had not paid her $600 semiannual premium by October 31, Bulwark would have recorded $600 as deferred income as of that date.";
arrAnsChoices[2] = "On December 31, Bulwark reported $200 of Ms.&nbsp;Yanez’s October 31 semiannual payment as unearned income because this amount applies to insurance coverage after December 31.";
arrAnsChoices[3] = "Under U.S. SAP, Bulwark reported Ms.&nbsp;Yanez’s April 30 semiannual payment as deferred income, because it was due after the financial reporting date but before the next policy anniversary date.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445641;
arrAnsIDs[1] = 445642;
arrAnsIDs[2] = 445643;
arrAnsIDs[3] = 445644;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">When Ms.&nbsp;Yanez makes her first semiannual payment on October 31, Bulwark records all $600 as <b>collected income</b>.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">If Ms.&nbsp;Yanez had not paid her $600 semiannual premium by October 31, Bulwark would have recorded $600 as <b>uncollected income</b>—income that is due before the financial reporting date, but which the insurer has not received as of the financial reporting date—October 31, in this situation.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">On December 31, Bulwark reported <b>$400</b> of Ms.&nbsp;Yanez’s October 31 semiannual payment as <b>unearned income</b>, which is applicable to the portion of coverage that occurs after December 31.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Upon receiving Ms.&nbsp;Yanez’s October 31 semiannual payment, Bulwark records the $600 as collected income, which is the amount of income, including certain adjustments, received in cash during an accounting period.</p><p class=\"explanations\">Collected premium income can have both an earned portion and an unearned portion. In this situation, on December 31, Bulwark reported $200 as earned income and $400 as unearned income from Ms.&nbsp;Yanez’s $600 October 31 payment. Unearned income applies to insurance coverage after December 31.</p><p class=\"explanations\">If Ms.&nbsp;Yanez had not paid her premium by October 31, Bulwark would have recorded $600 as uncollected income—income that is due before the financial reporting date, but which the insurer has not received as of that date—October 31, in this situation. Under U.S. SAP, Bulwark reported Ms.&nbsp;Yanez’s April&nbsp;30 semiannual payment as deferred income, because it was due after the financial reporting date (December&nbsp;31) but before the next policy anniversary date (October 31).</p><p class=\"explanations\"><b>Learning Objective: 10B. Describe the accounting entries associated with typical premium income transactions and investment income transactions in life insurance companies.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_079'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_080';
objQuestion.questionID = 110266;
objQuestion.item = 'LOMA_361_PPQ2019_080';
objQuestion.primaryLO = '10A';
objQuestion.textref = 'c. 10, pp. 2-3';
objQuestion.textbook = 0;
objQuestion.chapter = 10;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '10A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">For an income statement prepared according to U.S. GAAP, insurers report income that has been earned during the accounting period. Other types of income that have not yet been earned or received are reported as assets or liabilities on the balance sheet. The following statement(s) can correctly be made about two of these types of income:</p><ol type=\"A\" class=\"combo\"><li>Accrued income, which is income the insurer has already earned but which is receivable after the end of the accounting period, typically applies to premium income accounts.</li><li>For individual life insurance policies, deferred premiums are premiums that are due after the statutory reporting date but before the next policy anniversary date.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445645;
arrAnsIDs[1] = 445646;
arrAnsIDs[2] = 445647;
arrAnsIDs[3] = 445648;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is incorrect. Accrued income typically applies to <b>investment income</b>—interest or dividends on an insurer’s invested assets that is <b>legally collectible</b> by the insurer. Premium income typically is not classified as accrued income because individual policyowners have no legal obligation to pay premiums.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement A is incorrect. Accrued income typically applies to investment income—interest or dividends on an insurer’s invested assets that is legally collectible by the insurer. Premium income typically is not classified as accrued income because individual policyowners have no legal obligation to pay premiums. Accrued income has been earned by the insurer, but it has not yet been received; it is classified as an asset on the insurer’s balance sheet.</p><p class=\"explanations\">Statement B is correct. Deferred premiums typically apply to premium payments that are made more frequently than annually—for example, monthly or quarterly. Deferred premiums have not been received nor have they been earned by the insurer; they are classified as an asset on the insurer’s balance sheet.</p><p class=\"explanations\"><b>Learning Objective: 10A. Identify the main sources of revenues for life insurance companies.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_080'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_081';
objQuestion.questionID = 110267;
objQuestion.item = 'LOMA_361_PPQ2019_081';
objQuestion.primaryLO = '10A';
objQuestion.textref = 'c. 10, p. 5';
objQuestion.textbook = 0;
objQuestion.chapter = 10;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '10A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">An insurer’s investments typically provide three types of investment income: interest income, dividend income, and rental income. Invested assets that are a source of <i>dividend</i> income, but not interest income or rental income, for the insurer include</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "stocks";
arrAnsChoices[1] = "bonds";
arrAnsChoices[2] = "mortgages";
arrAnsChoices[3] = "real estate";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445649;
arrAnsIDs[1] = 445650;
arrAnsIDs[2] = 445651;
arrAnsIDs[3] = 445652;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A company’s investment income consists of the earnings the company receives on the invested assets it owns. Typical sources of investment income for insurers include interest income on policy loans, bonds, and mortgages; rental income on real estate; and dividend income on stock owned by the insurer. Note that investment income does not include realized or unrealized gains or losses associated with the insurer’s invested assets.</p><p class=\"explanations\"><b>Learning Objective: 10A. Identify the main sources of revenues for life insurance companies.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Bonds are a source of <b>interest </b>income, not dividend income.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Mortgages and mortgage-backed securities are a source of <b>interest </b>income, not dividend income.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Real estate is a source of <b>rental </b>income, not dividend income.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_081'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_082';
objQuestion.questionID = 110268;
objQuestion.item = 'LOMA_361_PPQ2019_082';
objQuestion.primaryLO = '10B';
objQuestion.textref = 'c. 10, pp. 4-5';
objQuestion.textbook = 0;
objQuestion.chapter = 10;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '10B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The primary function of an insurer’s premium accounting system is to apply premiums to the appropriate accounts as soon as the insurer receives the premiums. The following statement(s) can correctly be made about an insurer’s typical premium income transactions:</p><ol type=\"A\" class=\"combo\"><li>The basic accounting entry to record the receipt of premium income on most insurance products is a debit to <i>Premium Income</i> and a credit to <i>Cash</i>.</li><li>Premium accounting systems calculate premium income on an accrual basis in order to determine the amount of premium income that the insurer earned during the fiscal year.</li><li>Generally, the receipt of policy premiums increases both an insurer’s revenues and its assets.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A, B, and C";
arrAnsChoices[1] = "A and B only";
arrAnsChoices[2] = "A and C only";
arrAnsChoices[3] = "B and C only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445653;
arrAnsIDs[1] = 445654;
arrAnsIDs[2] = 445655;
arrAnsIDs[3] = 445656;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement B is correct; however, Statement A is incorrect.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement C is correct; however, Statement A is incorrect.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Statement A is incorrect. The basic accounting entry to record the receipt of premium income on most insurance products is a debit to <i>Cash</i>, an asset account, and a credit to a revenue account, such as <i>Premium Income</i>.</p><p class=\"explanations\">Statement B is correct. The amount of premium income an insurer earned during the fiscal year generally differs from the amount of premium income the insurer collected during the same period. This difference is due to various adjustments to income resulting from unearned premiums and premium income that is due but has not been received by the financial reporting date. In addition, premium income may in some cases be classified as a liability under U.S. SAP and U.S. GAAP.</p><p class=\"explanations\">Statement C is correct. The basic accounting entry to record the receipt of premium income on most insurance products is a debit to <i>Cash</i>, an asset account, and a credit to a revenue account, such as <i>Premium Income</i>. A debit to a cash account increases an insurer’s assets and a credit to an income account increases an insurer’s revenues.</p><p class=\"explanations\"><b>Learning Objective: 10B. Describe the accounting entries associated with typical premium income transactions and investment income transactions in life insurance companies.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_082'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_083';
objQuestion.questionID = 110269;
objQuestion.item = 'LOMA_361_PPQ2019_083';
objQuestion.primaryLO = '10B';
objQuestion.textref = 'c. 10, pp. 5-6';
objQuestion.textbook = 0;
objQuestion.chapter = 10;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '10B';
arrLOs[1] = '10C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Insurers recognize investment income on <b>(an accrual / a cash)</b> basis to comply with U.S. GAAP financial reporting requirements. Under U.S. GAAP, the amount of investment income, representing the total amount of income an insurer earned during the reporting period, before deducting expenses and amortization, is known as <b>(gross&nbsp;/&nbsp;net)</b> investment income.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "an accrual / gross";
arrAnsChoices[1] = "an accrual / net";
arrAnsChoices[2] = "a cash / gross";
arrAnsChoices[3] = "a cash / net";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445657;
arrAnsIDs[1] = 445658;
arrAnsIDs[2] = 445659;
arrAnsIDs[3] = 445660;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A typical accounting entry to record the receipt of investment income is a debit to <i>Cash</i>, an asset account, and a credit to one or more investment income (revenue) accounts, such as <i>Interest Income—Bonds</i>. Under U.S. GAAP, net investment income is the accrual-basis amount of investment income that remains after deducting expenses and amortization from an insurer’s gross investment income.</p><p class=\"explanations\">Under U.S. SAP, insurers report the amount of earned investment income that has not yet been received under <i>Investment Income Due and Accrued</i>, an asset account. When the insurer receives the income, it records the amount of the income as a debit to <i>Cash</i> and a credit to <i>Investment Income Due and Accrued</i>.</p><p class=\"explanations\"><b>Learning Objective: (1) 10B. Describe the accounting entries associated with typical premium income transactions and investment income transactions in life insurance companies; (2) 10C. Differentiate between gross investment income and net investment income.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that insurers recognize investment income on an accrual basis to comply with U.S. GAAP financial reporting requirements. However, <b>gross investment income</b> is the accrual-basis amount of investment income, representing the total amount of income an insurer earned during the reporting period, before deducting expenses and amortization.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that gross investment income is the accrual-basis amount of investment income, representing the total amount of income an insurer earned during the reporting period, before deducting expenses and amortization. However, insurers recognize investment income on an <b>accrual</b> basis to comply with U.S. GAAP financial reporting requirements.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Insurers recognize investment income on an <b>accrual</b> basis to comply with U.S. GAAP financial reporting requirements. In addition, <b>gross investment income</b> is the accrual-basis amount of investment income, representing the total amount of income an insurer earned during the reporting period, before deducting expenses and amortization.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_083'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_084';
objQuestion.questionID = 110270;
objQuestion.item = 'LOMA_361_PPQ2019_084';
objQuestion.primaryLO = '10D';
objQuestion.textref = 'c. 10, pp. 7-8';
objQuestion.textbook = 0;
objQuestion.chapter = 10;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '10D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The largest expense for life insurance companies typically is</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "agent commissions";
arrAnsChoices[1] = "premium taxes";
arrAnsChoices[2] = "contractual benefit expenses";
arrAnsChoices[3] = "operating expenses";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445661;
arrAnsIDs[1] = 445662;
arrAnsIDs[2] = 445663;
arrAnsIDs[3] = 445664;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Most life insurance companies have a distribution system that relies primarily on commissioned agents. For these companies, agent commissions are typically the <b>second</b> largest expense after contractual benefit expenses. However, for insurers that rely on salaried agents—such as direct response companies and group life insurers—agent commissions are not a large expense.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Premium taxes, which are taxes on the paid premium income an insurer receives within a particular jurisdiction, are typically <b>not</b> the largest expense for insurance companies.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Contractual benefit expenses, which are typically the largest expense for insurers, include death benefit payments, cash surrender payments, and annuity benefit payments. When an insurer sells an insurance policy or annuity contract, the insurer becomes legally obligated to pay the benefit amount associated with that product if certain conditions are met.</p><p class=\"explanations\">Insurers also incur operating expenses that are similar to those incurred by noninsurance companies. Operating expenses, such as acquisition, development, maintenance, and overhead expenses, arise in the normal course of conducting business.</p><p class=\"explanations\"><b>Learning Objective: 10D. Identify and differentiate among an insurer’s major expenses.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Operating expenses, which arise in the normal course of conducting business, are major expenses for insurance companies, but they typically are <b>not</b> the largest expense.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_084'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_085';
objQuestion.questionID = 110271;
objQuestion.item = 'LOMA_361_PPQ2019_085';
objQuestion.primaryLO = '10D';
objQuestion.textref = 'c. 10, pp. 8-9';
objQuestion.textbook = 0;
objQuestion.chapter = 10;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '10D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Two types of insurance company expenses are acquisition expenses and maintenance expenses. Select the answer choice that correctly identifies an example of an acquisition expense and an example of a maintenance expense.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[-1] = "<u>Acquisition expense</u></div><div class=\"anshead\"><u>Maintenance expense</u>";
arrAnsChoices[0] = "renewal commissions</div><div class=\"anscell\" onclick=\"recordAns(1);\">advertising expenses";
arrAnsChoices[1] = "first-year agent commissions</div><div class=\"anscell\" onclick=\"recordAns(2);\">customer service operating expenses";
arrAnsChoices[2] = "customer service operating expenses</div><div class=\"anscell\" onclick=\"recordAns(3);\">renewal commissions";
arrAnsChoices[3] = "advertising expenses</div><div class=\"anscell\" onclick=\"recordAns(4);\">contract issue expenses";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445666;
arrAnsIDs[1] = 445667;
arrAnsIDs[2] = 445668;
arrAnsIDs[3] = 445669;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Renewal commissions are <b>maintenance </b>expenses; advertising expenses are <b>acquisition </b>expenses.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Acquisition expenses, which are the costs for obtaining and issuing new business, include first-year agent commissions, contract issue expenses, advertising expenses, and underwriting expenses. Maintenance expenses, which are the product-related costs incurred on in-force policies and contracts, include customer service operating expenses, renewal commissions, and some agency or branch office expenses.</p><p class=\"explanations\">Two other types of operating expenses are development expenses and overhead expenses. Development expenses, which are the costs related to designing, testing, and implementing a new product, include new administrative software expenses and new business license fees. Overhead expenses, which are the costs of normal business operations that are not directly connected with any product, include utility expenses, some agency or branch office expenses, and some information systems expenses.</p><p class=\"explanations\"><b>Learning Objective: 10D. Identify and differentiate among an insurer’s major expenses.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that renewal commissions are maintenance expenses. However, customer service operating expenses are also <b>maintenance </b>expenses.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that advertising expenses are acquisition expenses. However, contract issue expenses are also <b>acquisition </b>expenses.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_085'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_086';
objQuestion.questionID = 110272;
objQuestion.item = 'LOMA_361_PPQ2019_086';
objQuestion.primaryLO = '10E';
objQuestion.textref = 'c. 10, pp. 9-10';
objQuestion.textbook = 0;
objQuestion.chapter = 10;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '10E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Paragon Life Insurance Company made the following accounting entry:</p><table align=\"center\" cols=\"3\" cellspacing=\"0\" cellpadding=\"1\" width=\"80%\" style=\"margin-top:0.5em; margin-bottom:0em\"><tr><td class=\"acctentry_d\"><i>Commissions Expense</i></td><td class=\"debit_credit\">1,500</td><td class=\"debit_credit\">&nbsp;</td></tr><tr><td class=\"acctentry_c\"><i>Agents Ledger Control</i></td><td class=\"debit_credit\">&nbsp;</td><td class=\"debit_credit\">1,500</td></tr></table><p class=\"stem\">Paragon most likely made this accounting entry to record the</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "payment of agent commissions";
arrAnsChoices[1] = "payment of federal income taxes from an agent’s salary";
arrAnsChoices[2] = "establishment of a liability for an agent’s salary and the appropriate tax withholdings";
arrAnsChoices[3] = "establishment of a liability for the commission owed to an agent";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445670;
arrAnsIDs[1] = 445671;
arrAnsIDs[2] = 445672;
arrAnsIDs[3] = 445673;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Upon paying an agent commission, Paragon most likely would debit <i>Agents Ledger Control </i>and credit <i>Cash</i>.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">To record the payment of federal income taxes withheld from an agent’s salary, Paragon most likely would debit <i>Federal Income Taxes Payable </i>and credit <i>Cash</i>.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">To record the establishment of a liability for an agent’s salary and the appropriate tax withholdings, Paragon most likely would debit <i>Salaries Expense </i>and credit <i>Federal Income Taxes Payable</i>, <i>Social Security and Medicare Taxes Payable</i>, <i>State Income Taxes Payable</i>, and <i>Salaries Payable</i>.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">An insurer’s income statement typically contains summary information that shows the total amount of commissions earned by and paid to all agents. For financial reporting purposes, an insurer establishes a control account that summarizes accounting entries and monitors the expenses that are reported in a company’s financial statements. A typical control account, called <i>Agents Ledger Control</i> or <i>Producers Ledger Control</i>, includes commissions owed to agents as well as amounts agents owe to the insurer.</p><p class=\"explanations\">The amount of the agent commission is an account payable, which is a short-term liability because the insurer expects to pay the agent within the current accounting period. In this situation, upon payment of the earned commission to the agent, Paragon debits <i>Agents Ledger Control </i>and credits <i>Cash</i>. The combined effect of both transactions is an increase in <i>Commissions Expense</i> (an expense account) and a decrease in <i>Cash</i> (an asset account).</p><p class=\"explanations\"><b>Learning Objective: 10E. Describe the accounting entries associated with typical expenses incurred in life insurance companies.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_086'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_087';
objQuestion.questionID = 110273;
objQuestion.item = 'LOMA_361_PPQ2019_087';
objQuestion.primaryLO = '10E';
objQuestion.textref = 'c. 10, pp. 10-11';
objQuestion.textbook = 0;
objQuestion.chapter = 10;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '10E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">A salaried agent for the Sustainable Life Insurance Company earns a salary of $600. From this salary, Sustainable withholds $60 in federal income taxes, $50 in Social Security and Medicare taxes, and $20 for state income taxes. When Sustainable establishes the initial liability for the amount payable to the salaried agent, Sustainable most likely would include in its accounting entry a</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "debit to <i>Salaries Expense</i> in the amount of $600";
arrAnsChoices[1] = "debit to <i>Salaries Payable </i>in the amount of $470";
arrAnsChoices[2] = "credit to <i>Salaries Expense </i>in the amount of $470";
arrAnsChoices[3] = "credit to <i>Salaries Payable </i>in the amount of $600";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445674;
arrAnsIDs[1] = 445675;
arrAnsIDs[2] = 445676;
arrAnsIDs[3] = 445677;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Sustainable’s accounting entry to establish liabilities for federal and state taxes and the amount payable to the agent most likely would include a $600 debit to <i>Salaries Expense</i>, a $60 credit to <i>Federal Income Taxes Payable</i>, a $50 credit to <i>Social Security and Medicare Taxes Payable</i>, a $20 credit to <i>State Income Taxes Payable</i>, and a $470 credit to <i>Salaries Payable</i>.</p><p class=\"explanations\"><b>Learning Objective: 10E. Describe the accounting entries associated with typical expenses incurred in life insurance companies.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">In this situation, Sustainable most likely would record a $470 <b>credit</b> to <i>Salaries Payable</i> to establish the initial liability for the amount payable to the agent. Upon payment of the agent’s salary, Sustainable most likely would record a $470 debit to <i>Salaries Payable </i>and a corresponding $470 credit to <i>Cash</i>.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">In this situation, the correct accounting entry most likely would include a <b>debit</b> to <i>Salaries Expense </i>in the amount of<b> $600</b>.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">In this situation, the correct accounting entry most likely would include a credit to <i>Salaries Payable </i>in the amount of <b>$470</b>.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_087'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_088';
objQuestion.questionID = 110274;
objQuestion.item = 'LOMA_361_PPQ2019_088';
objQuestion.primaryLO = '10E';
objQuestion.textref = 'c. 10, pp. 11-12';
objQuestion.textbook = 0;
objQuestion.chapter = 10;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '10E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Merry Life Insurance Company ceded $400,000 of the risk on a block of ordinary life insurance policies to a reinsurer. The reinsurance agreement specifies a reinsurance premium of $900 and a reinsurance allowance of $750. The accounting entry that Merry most likely would make to record payment of the reinsurance premium is</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "<table cols=\"3\" cellspacing=\"0\" cellpadding=\"1\" style=\"width: 90%; margin-top:0em; margin-bottom:0em\"><tr><td class=\"acctentry_d\"><i>Reinsurance Ceded—First-Year Premium Expense</i></td><td class=\"debit_credit\">900</td><td class=\"debit_credit\">&nbsp;</td></tr><tr><td class=\"acctentry_c\"><i>Reinsurance Allowance—Ceded</i></td><td class=\"debit_credit\">&nbsp;</td><td class=\"debit_credit\">900</td></tr></table>";
arrAnsChoices[1] = "<table cols=\"3\" cellspacing=\"0\" cellpadding=\"1\" style=\"width: 90%; margin-top:0em; margin-bottom:0em\"><tr><td class=\"acctentry_d\"><i>Reinsurance Allowance—Ceded</i></td><td class=\"debit_credit\">750</td><td class=\"debit_credit\">&nbsp;</td></tr><tr><td class=\"acctentry_c\"><i>Reinsurance Ceded—First-Year Premium Expense</i></td><td class=\"debit_credit\">&nbsp;</td><td class=\"debit_credit\">750</td></tr></table>";
arrAnsChoices[2] = "<table cols=\"3\" cellspacing=\"0\" cellpadding=\"1\" style=\"width: 90%; margin-top:0em; margin-bottom:0em\"><tr><td class=\"acctentry_d\"><i>Reinsurance Ceded—First-Year Premium Expense</i></td><td class=\"debit_credit\">900</td><td class=\"debit_credit\">&nbsp;</td></tr><tr><td class=\"acctentry_c\"><i>Reinsurance Allowance—Ceded</i></td><td class=\"debit_credit\">&nbsp;</td><td class=\"debit_credit\">750</td></tr><tr><td class=\"acctentry_c\"><i>Cash</i></td><td class=\"debit_credit\">&nbsp;</td><td class=\"debit_credit\">150</td></tr></table>";
arrAnsChoices[3] = "<table cols=\"3\" cellspacing=\"0\" cellpadding=\"1\" style=\"width: 90%; margin-top:0em; margin-bottom:0em\"><tr><td class=\"acctentry_d\"><i>Reinsurance Allowance—Assumed</i></td><td class=\"debit_credit\">750</td><td class=\"debit_credit\">&nbsp;</td></tr><tr><td class=\"acctentry_d\"><i>Cash</i></td><td class=\"debit_credit\">150</td><td class=\"debit_credit\">&nbsp;</td></tr><tr><td class=\"acctentry_c\"><i>Reinsurance Assumed—First-Year Premium Income</i></td><td class=\"debit_credit\">&nbsp;</td><td class=\"debit_credit\">900</td></tr></table>";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445678;
arrAnsIDs[1] = 445679;
arrAnsIDs[2] = 445680;
arrAnsIDs[3] = 445681;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">In this situation, Merry would reduce the amount of the $900 reinsurance premium by the $750 reinsurance allowance, which results in $150, the amount of money Merry pays to the reinsurer. The accounting entry that Merry most likely would make to record payment of the reinsurance premium is a $900 debit to <i>Reinsurance Ceded—First-Year Premium Expense</i>, a $750 credit to <i>Reinsurance Allowance—Ceded</i>, and a $150 credit to <i>Cash</i>.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">In this situation, Merry would reduce the amount of the $900 reinsurance premium by the $750 reinsurance allowance, which results in $150, the amount of money Merry pays to the reinsurer. The accounting entry that Merry most likely would make to record payment of the reinsurance premium is a $900 debit to <i>Reinsurance Ceded—First-Year Premium Expense</i>, a $750 credit to <i>Reinsurance Allowance—Ceded</i>, and a $150 credit to <i>Cash</i>.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A direct writer pays periodic premiums to the reinsurer when ceding part of the insurance risk on a block of insurance policies to a reinsurer. Commissions that the reinsurer pays to the direct writer are called reinsurance allowances, also known as reinsurance commissions, which are payments intended to cover all or part of the direct writer’s acquisition costs and other costs related to the reinsured business. In effect, the reinsurer pays a commission on this new business to the direct writer, rather than to an agent.</p><p class=\"explanations\">In this situation, Merry would reduce the amount of the $900 reinsurance premium by the $750 reinsurance allowance, which results in $150, the amount of money Merry pays to the reinsurer.</p><p class=\"explanations\"><b>Learning Objective: 10E. Describe the accounting entries associated with typical expenses incurred in life insurance companies.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">In this situation, Merry would reduce the amount of the $900 reinsurance premium by the $750 reinsurance allowance, which results in $150, the amount of money Merry pays to the reinsurer. The accounting entry that Merry most likely would make to record payment of the reinsurance premium is a $900 debit to <i>Reinsurance Ceded—First-Year Premium Expense</i>, a $750 credit to <i>Reinsurance Allowance—Ceded</i>, and a $150 credit to <i>Cash</i>.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_088'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_089';
objQuestion.questionID = 110275;
objQuestion.item = 'LOMA_361_PPQ2019_089';
objQuestion.primaryLO = '10E';
objQuestion.textref = 'c. 10, pp. 12-13';
objQuestion.textbook = 0;
objQuestion.chapter = 10;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '10E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">One true statement about the premium taxes that life insurers pay in the United States is that</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "premium taxes are calculated as a percentage of each insurer’s premium income received within a particular jurisdiction";
arrAnsChoices[1] = "premium taxes are calculated at the same rate for both life insurance premiums and annuity considerations (premiums)";
arrAnsChoices[2] = "all states use a uniform definition of what constitutes paid premium income for tax purposes";
arrAnsChoices[3] = "all states apply premium taxes equally to all types of insurers, including fraternal benefit societies";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445682;
arrAnsIDs[1] = 445683;
arrAnsIDs[2] = 445684;
arrAnsIDs[3] = 445685;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The definition of what constitutes paid premium income for tax purposes varies among jurisdictions. Some U.S. states impose the tax on gross premiums. Most states allow insurers to deduct policyowner dividends from their gross premiums before calculating premium taxes. </p><p class=\"explanations\">The formula that determines premium taxes due from an insurer typically excludes investment income and reinsurance premiums. Many U.S. states do not impose premium taxes on annuity considerations (premiums). Some states require that the insurer pay the larger of the premium tax or the state income tax. Fraternal benefit societies are typically exempt from premium taxes.</p><p class=\"explanations\">An insurer’s typical accounting entry to record the liability for incurred premium taxes is to debit <i>Premium Tax Expense</i> and credit <i>Premium Taxes Payable</i>. To record the payment of premium taxes, the insurer would debit <i>Premium Taxes Payable</i> and credit <i>Cash</i>.</p><p class=\"explanations\"><b>Learning Objective: 10E. Describe the accounting entries associated with typical expenses incurred in life insurance companies.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Some U.S. states do <b>not</b> impose taxes on annuity considerations (premiums). Annuity considerations are sometimes taxed at a <b>lower</b> rate than insurance premiums in those states that impose premium taxes on annuity considerations. In addition, reinsurance premiums are typically <b>excluded</b> from the formula that determines the amount of premium taxes due from an insurer.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The definition of what constitutes paid premium income for tax purposes <b>varies</b> among jurisdictions. For example, some U.S. states impose the tax on <b>gross</b> premiums. Most states allow insurers to <b>deduct</b> policyowner dividends from their gross premiums before calculating premium taxes. Some states require that the insurer pay the larger of the premium tax or the state income tax. State governments impose premium taxes on life insurance policies issued in that state.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Fraternal benefit societies typically are <b>exempt</b> from premium taxes. In addition, the formula that determines premium taxes due from an insurer typically <b>excludes</b> investment income and reinsurance premiums, and many U.S. states do <b>not</b> impose premium taxes on annuity considerations (premiums). Insurers that sell only annuity products, for example, may be exempt from premium taxes in those states.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_089'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['10A'] = "10A. Identify the main sources of revenues for life insurance companies.";
arrlotext['10B'] = "10B. Describe the accounting entries associated with typical premium income transactions and investment income transactions in life insurance companies.";
arrlotext['10C'] = "10C. Differentiate between gross investment income and net investment income.";
arrlotext['10D'] = "10D. Identify and differentiate among an insurer’s major expenses.";
arrlotext['10E'] = "10E. Describe the accounting entries associated with typical expenses incurred in life insurance companies.";
