var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2019';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 361 Practice Questions, Chapter 8";
var coursename = 'LOMA 361';
var modulenumber = 2;
var title = "LOMA_361_PPQ2019_0_8";
var intNumPools = 1;
var numQ = 11;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Accounting and Financial Reporting in Life Insurance Companies, Second Edition (2019)";
arrNumChap[0] = 1;
var thisChap = '8';

objPool = new Object(); 
objPool.intSelectCount = 11;
objPool.formID = 2103;
objPool.formName = 'PPQ2019_0_8';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_361_PQ_058';
arrPoolQuestions[1] = 'LOMA_361_PQ_059';
arrPoolQuestions[2] = 'LOMA_361_PQ_060';
arrPoolQuestions[3] = 'LOMA_361_PQ_061';
arrPoolQuestions[4] = 'LOMA_361_PQ_062';
arrPoolQuestions[5] = 'LOMA_361_PQ_063';
arrPoolQuestions[6] = 'LOMA_361_PQ_064';
arrPoolQuestions[7] = 'LOMA_361_PQ_065';
arrPoolQuestions[8] = 'LOMA_361_PQ_066';
arrPoolQuestions[9] = 'LOMA_361_PQ_067';
arrPoolQuestions[10] = 'LOMA_361_PQ_068';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_058';
objQuestion.questionID = 110244;
objQuestion.item = 'LOMA_361_PPQ2019_058';
objQuestion.primaryLO = '8A';
objQuestion.textref = 'c. 8, pp. 3-5';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '8A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">In addition to establishing contractual reserves, each life insurer in the United States also must establish two statutory reserves—the asset valuation reserve (AVR) and the interest maintenance reserve (IMR)—designed to absorb capital gains and losses on the insurer’s invested assets in the general account. Each reserve has several distinct characteristics. However, one characteristic of <i>both</i> the AVR and the IMR is that they minimize the effects of</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "fluctuations in value on an insurer’s invested assets in equity securities and debt securities";
arrAnsChoices[1] = "interest-rate risk on the insurer’s net gain from operations";
arrAnsChoices[2] = "realized capital gains and losses on the insurer’s capital and surplus accounts";
arrAnsChoices[3] = "both realized and unrealized gains and losses on the insurer’s invested assets";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445555;
arrAnsIDs[1] = 445556;
arrAnsIDs[2] = 445557;
arrAnsIDs[3] = 445558;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The AVR minimizes the effects of both realized and unrealized gains and losses on an insurer’s invested assets—such as bonds, preferred stock, derivatives, mortgages, common stock, and real estate—when those gains and losses are related to the credit quality of the assets (credit risk), or fluctuations in the prices of equity securities (equity risk). However, the <B>IMR</B> helps absorb only the realized capital gains and losses on an insurer’s <b>debt securities</b>—such as bonds, mortgages, mortgage-backed securities, and preferred stock—when those gains or losses are caused by changes in market interest rates.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The IMR helps to protect an insurer’s net gain from operations and its capital and surplus from the effects of interest-rate risk. However, the <B>AVR</B> minimizes the effects of both <b>realized and unrealized gains and losses on an insurer’s invested assets</b>—such as bonds, preferred stock, derivatives, mortgages, common stock, and real estate—when those gains and losses are related to the credit quality of the assets <b>(credit risk)</b>, or fluctuations in the prices of equity securities <b>(equity risk)</b>.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The AVR minimizes the effects of both realized and unrealized gains and losses on an insurer’s invested assets—such as bonds, preferred stock, derivatives, mortgages, common stock, and real estate—when those gains and losses are related to the credit quality of the assets (credit risk), or fluctuations in the prices of equity securities (equity risk). The IMR helps absorb only the realized capital gains and losses on an insurer’s debt securities—such as bonds, mortgages, mortgage-backed securities, and preferred stock—when those gains or losses are caused by changes in market interest rates. In doing so, the IMR helps to protect an insurer’s net gain from operations and capital and surplus from the effects of interest-rate risk.</p><p class=\"explanations\">The market values of an insurer’s invested assets can fluctuate widely. Both the AVR and the IMR act as a buffer to minimize the effects of these fluctuations on an insurer’s capital and surplus accounts. An insurer’s capital and surplus accounts are affected gradually by realized capital gains and losses, thus helping to ensure the stability of these accounts.</p><p class=\"explanations\"><b>Learning Objective: 8A. Differentiate between the asset valuation reserve (AVR) and the interest maintenance reserve (IMR) and explain the purpose of these two statutory reserves.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that the AVR minimizes the effects of both realized and unrealized gains and losses on an insurer’s invested assets—such as bonds, preferred stock, derivatives, mortgages, common stock, and real estate—when those gains and losses are related to the credit quality of the assets (credit risk), or fluctuations in the prices of equity securities (equity risk). However, the <B>IMR</B> helps absorb <b>only the realized capital gains and losses</b> on an insurer’s <b>debt securities</b>—such as bonds, mortgages, mortgage-backed securities, and preferred stock—when those gains or losses are caused by changes in market interest rates.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_058'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_059';
objQuestion.questionID = 110245;
objQuestion.item = 'LOMA_361_PPQ2019_059';
objQuestion.primaryLO = '8B';
objQuestion.textref = 'c. 8, pp. 7-8';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '8B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">An insurer’s liabilities for policyowner dividends include policyowner dividends due and unpaid, policyowner dividends payable in the following calendar year, and dividend accumulations. The following statement(s) can correctly be made about these policyowner dividend liabilities:</p><ol type=\"A\" class=\"combo\"><li>Policyowner dividends due and unpaid result when a policyowner elects to leave policyowner dividends on deposit with the insurer, and the insurer establishes a liability for the dividend and its accrued interest.</li><li>Policyowner dividends payable in the following calendar year represent those dividends payable to the policyowner in the current year that have not been disbursed or otherwise applied as of the financial reporting date for the current year.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445559;
arrAnsIDs[1] = 445560;
arrAnsIDs[2] = 445561;
arrAnsIDs[3] = 445562;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is incorrect. <b>Policyowner dividends</b> <b>due and unpaid</b> represent those dividends payable to the policyowner in the current year that have not been disbursed or otherwise applied as of the financial reporting date for the current year. <b>Dividend accumulations</b>, also known as dividends left on deposit, result when a policyowner elects to leave policyowner dividends on deposit at interest with the insurer, and the insurer establishes a liability for any dividend accumulations, as well as for the accrued interest on those accumulations.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is incorrect. <b>Policyowner dividends payable in the following calendar year</b> include two categories of dividends: (1) dividends apportioned for payment, which are the estimated amounts of all policyowner dividends declared by an insurance company’s board of directors prior to the end of the statement year that are not yet paid or due at the end of the year; and (2) dividends not yet apportioned for payment, which are all dividends payable in the following calendar year that have not been declared. <b>Policyowner dividends</b> <b>due and unpaid</b> represent those dividends payable to the policyowner in the current year that have not been disbursed or otherwise applied as of the financial reporting date for the current year.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Statement A and Statement B are incorrect. Policyowner dividends due and unpaid represent those dividends payable to the policyowner in the current year that have not been disbursed or otherwise applied as of the financial reporting date for the current year.</p><p class=\"explanations\">Policyowner dividends payable in the following calendar year include two categories of dividends: (1) dividends apportioned for payment, which are the estimated amounts of all policyowner dividends declared by an insurance company’s board of directors prior to the end of the statement year that are not yet paid or due at the end of the year; and (2) dividends not yet apportioned for payment, which are all dividends payable in the following calendar year that have not been declared.</p><p class=\"explanations\">Dividend accumulations, also known as dividends left on deposit, result when a policyowner elects to leave policyowner dividends on deposit with the insurer. The insurer establishes a liability for any dividend accumulations, as well as for the accrued interest on those accumulations.</p><p class=\"explanations\"><b>Learning Objective: 8B. List and describe the three types of policyowner dividend liabilities.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_059'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_060';
objQuestion.questionID = 110246;
objQuestion.item = 'LOMA_361_PPQ2019_060';
objQuestion.primaryLO = '8C';
objQuestion.textref = 'c. 8, pp. 8-10';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '8C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Owners of participating life insurance policies typically can select one of five policyowner dividend payment options, or dividend payment options, which enable participating policyowners to select the manner in which they want their policyowner dividends disbursed. A typical accounting entry that an insurer would make to record a policyowner dividend applied to pay a current premium is</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "<table cols=\"3\" cellspacing=\"0\" cellpadding=\"1\" style=\"width: 90%; margin-top:0em; margin-bottom:0em\"><tr><td class=\"acctentry_d\"><i>Policyowner Dividends Applied to Purchase PUAs</i></td><td class=\"debit_credit\">xxx</td><td class=\"debit_credit\">&nbsp;</td></tr><tr><td class=\"acctentry_c\"><i>Single Premiums for PUAs</i></td><td class=\"debit_credit\">&nbsp;</td><td class=\"debit_credit\">xxx</td></tr></table>";
arrAnsChoices[1] = "<table cols=\"3\" cellspacing=\"0\" cellpadding=\"1\" style=\"width: 90%; margin-top:0em; margin-bottom:0em\"><tr><td class=\"acctentry_d\"><i>Policyowner Dividends Applied to Premiums</i></td><td class=\"debit_credit\">xxx</td><td class=\"debit_credit\">&nbsp;</td></tr><tr><td class=\"acctentry_c\"><i>Premium Income</i></td><td class=\"debit_credit\">&nbsp;</td><td class=\"debit_credit\">xxx</td></tr></table>";
arrAnsChoices[2] = "<table cols=\"3\" cellspacing=\"0\" cellpadding=\"1\" style=\"width: 90%; margin-top:0em; margin-bottom:0em\"><tr><td class=\"acctentry_d\"><i>Policyowner Dividends Paid in Cash</i></td><td class=\"debit_credit\">xxx</td><td class=\"debit_credit\">&nbsp;</td></tr><tr><td class=\"acctentry_c\"><i>Cash</i></td><td class=\"debit_credit\">&nbsp;</td><td class=\"debit_credit\">xxx</td></tr></table>";
arrAnsChoices[3] = "<table cols=\"3\" cellspacing=\"0\" cellpadding=\"1\" style=\"width: 90%; margin-top:0em; margin-bottom:0em\"><tr><td class=\"acctentry_d\"><i>Policyowner Dividends Applied to Dividend Accumulations</i></td><td class=\"debit_credit\">xxx</td><td class=\"debit_credit\">&nbsp;</td></tr><tr><td class=\"acctentry_c\"><i>Dividend Accumulations</i></td><td class=\"debit_credit\">&nbsp;</td><td class=\"debit_credit\">xxx</td></tr></table>";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445563;
arrAnsIDs[1] = 445564;
arrAnsIDs[2] = 445565;
arrAnsIDs[3] = 445566;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">This accounting entry is a typical entry to record the <b>payment of policyowner dividends to purchase paid-up additions (PUAs)</b>. When a policyowner uses a dividend to purchase paid-up insurance, the insurer determines the amount of the additional insurance purchased. The insurer then adds a rider to the basic policy to indicate the additional insurance coverage or treats the paid-up insurance as a separate policy.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">When a policyowner uses a dividend to reduce a policy premium, the insurer deducts the policyowner dividend from the premium due to determine the amount owed by the policyowner. The insurer records the accounting entry on the policy anniversary date. If the dividend is greater than the premium due, the policyowner can receive the excess in cash or apply it to another dividend payment option.</p><p class=\"explanations\"><b>Learning Objective: 8C. Explain how an insurer accounts for common types of policyowner dividend payment options.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">This accounting entry is a typical entry to record the <b>payment of policyowner dividends in cash</b>. When a policyowner elects to receive a dividend in cash, an insurer typically updates the dividend record—which is part of the policyowner master file—and records the appropriate accounting entry upon payment of the dividend.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">This accounting entry is a typical entry to record <b>policyowner dividends applied to accumulate at interest</b>. Note that this accounting entry records the initial deposit of the dividend. Separate accounting entries would record the interest earned on the dividend. For dividend accumulations, most insurers record the policyowner dividend and its accrued interest on the policy anniversary date—that is, the date on which the dividend becomes payable—provided the policy premiums have been paid to that date.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_060'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_061';
objQuestion.questionID = 110247;
objQuestion.item = 'LOMA_361_PPQ2019_061';
objQuestion.primaryLO = '8D';
objQuestion.textref = 'c. 8, pp. 12-13';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '8D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = 2;
objQuestion.strStem = "<p class=\"stem\">The accounting entry that Pillar most likely would make to record Ms.&nbsp;Harrod’s cash surrender of her policy includes a</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "debit to <i>Surrenders Paid—Life Insurance</i> and a credit to <i>Cash</i>";
arrAnsChoices[1] = "debit to <i>Surrenders Paid—Life Insurance</i>, a credit to <i>Policy Reserves</i>, and a credit to <i>Cash</i>";
arrAnsChoices[2] = "debit to <i>Cash</i>, a credit to <i>Surrenders Paid—Life Insurance</i>, and a credit to <i>Policy Reserves</i>";
arrAnsChoices[3] = "debit to <i>Policy Reserves</i>, a credit to <i>Surrenders Paid—Life Insurance</i>, and a credit to <i>Cash</i>";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445567;
arrAnsIDs[1] = 445568;
arrAnsIDs[2] = 445569;
arrAnsIDs[3] = 445570;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">When a policyowner has elected the cash surrender value option, insurance protection stops and the insurer calculates the cash surrender value owed to the policyowner. The insurer then remits this amount to the policyowner, and the company has no further obligation under the policy.</p><p class=\"explanations\">Insurers usually do not make accounting entries each time transactions affect policy reserves. In this situation, the changes caused by the reserve released by Ms.&nbsp;Harrod’s cash surrender of her policy will not be recorded until Pillar’s actuaries calculate actual reserves at the end of the accounting period.</p><p class=\"explanations\"><b>Learning Objective: 8D. Explain the accounting treatment of various nonforfeiture options.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that the accounting entry that Pillar would make to record Ms.&nbsp;Harrod’s cash surrender of her policy most likely would include a debit to <i>Surrenders Paid—Life Insurance</i> and a credit to <i>Cash</i>. However, insurers usually do not make accounting entries each time transactions affect policy reserves. In this situation, the changes caused by the reserve released by Ms.&nbsp;Harrod’s cash surrender of her policy will <b>not</b> be recorded until Pillar’s actuaries calculate actual reserves at the end of the accounting period.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The accounting entry that Pillar would make to record Ms.&nbsp;Harrod’s cash surrender of her policy most likely would include a <b>debit</b> to <i>Surrenders Paid—Life Insurance</i> and a <b>credit</b> to <i>Cash</i>. In addition, insurers usually do <b>not</b> make accounting entries each time transactions affect policy reserves. In this situation, the changes caused by the reserve released by Ms.&nbsp;Harrod’s cash surrender of her policy will not be recorded until Pillar’s actuaries calculate actual reserves at the end of the accounting period.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The accounting entry that Pillar would make to record Ms.&nbsp;Harrod’s cash surrender of her policy most likely would include a <b>debit</b> to <i>Surrenders Paid—Life Insurance</i> and a <b>credit</b> to <i>Cash</i>. In addition, insurers usually do <b>not</b> make accounting entries each time transactions affect policy reserves. In this situation, the changes caused by the reserve released by Ms.&nbsp;Harrod’s cash surrender of her policy will not be recorded until Pillar’s actuaries calculate actual reserves at the end of the accounting period.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_061'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_062';
objQuestion.questionID = 110248;
objQuestion.item = 'LOMA_361_PPQ2019_062';
objQuestion.primaryLO = '8D';
objQuestion.textref = 'c. 8, pp. 12-13';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '8D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = 2;
objQuestion.strStem = "<p class=\"stem\">One net effect of this transaction on Pillar’s balance sheet at the end of the accounting period, all other factors remaining equal, would be</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "an increase in assets";
arrAnsChoices[1] = "an increase in liabilities";
arrAnsChoices[2] = "a decrease in surplus";
arrAnsChoices[3] = "an increase in surplus";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445571;
arrAnsIDs[1] = 445572;
arrAnsIDs[2] = 445573;
arrAnsIDs[3] = 445574;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The reserve for a policy must equal or exceed the policy’s cash surrender value. If the reserve equals the cash surrender value, the net effect of the surrender is an equal decrease in <i>Cash</i>, an asset account, and in <i>Reserves</i>, a liability account. In this situation, because the reserve is greater than Ms.&nbsp;Harrod’s cash surrender value, the net effect is an increase in surplus.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The reserve for a policy must equal or exceed the policy’s cash surrender value. If the reserve equals the cash surrender value, the net effect of the surrender is an equal decrease in <i>Cash</i>, an asset account, and in <i>Reserves</i>, a liability account. In this situation, because the reserve is greater than Ms.&nbsp;Harrod’s cash surrender value, the net effect is an increase in surplus.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The reserve for a policy must equal or exceed the policy’s cash surrender value. If the reserve equals the cash surrender value, the net effect of the surrender is an equal decrease in <i>Cash</i>, an asset account, and in <i>Reserves</i>, a liability account. In this situation, because the reserve is greater than Ms.&nbsp;Harrod’s cash surrender value, the net effect is an increase in surplus.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The reserve for a policy must equal or exceed the policy’s cash surrender value. If the reserve equals the cash surrender value, the net effect of the cash surrender is an equal decrease in <i>Cash</i>, an asset account, and in <i>Reserves</i>, a liability account. The net effect of a cash surrender when the reserve is greater than the policy’s cash surrender value is an increase in surplus. In this situation, the changes caused by the reserve released from this policy will not be recorded until Pillar’s actuaries calculate the actual reserves at the end of the accounting period.</p><p class=\"explanations\"><b>Learning Objective: 8D. Explain the accounting treatment of various nonforfeiture options.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_062'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_063';
objQuestion.questionID = 110249;
objQuestion.item = 'LOMA_361_PPQ2019_063';
objQuestion.primaryLO = '8E';
objQuestion.textref = 'c. 8, pp. 14-15';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '8E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Lanyard Life Insurance Company received a death claim for payment upon the death of the insured, under the terms of a whole life insurance policy. Lanyard had not reinsured the policy. Lanyard approved payment of the death claim and calculated the amount payable to the policy’s beneficiary. The accounting entry that Lanyard most likely made to record payment of the death claim to the beneficiary was</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "<table cols=\"3\" cellspacing=\"0\" cellpadding=\"1\" style=\"width: 90%; margin-top:0em; margin-bottom:0em\"><tr><td class=\"acctentry_d\"><i>Cash</i></td><td class=\"debit_credit\">xxx</td><td class=\"debit_credit\">&nbsp;</td></tr><tr><td class=\"acctentry_c\"><i>Surrender Paid—Life Insurance</i></td><td class=\"debit_credit\">&nbsp;</td><td class=\"debit_credit\">xxx</td></tr></table>";
arrAnsChoices[1] = "<table cols=\"3\" cellspacing=\"0\" cellpadding=\"1\" style=\"width: 90%; margin-top:0em; margin-bottom:0em\"><tr><td class=\"acctentry_d\"><i>Amount Recoverable from Reinsurer</i></td><td class=\"debit_credit\">xxx</td><td class=\"debit_credit\">&nbsp;</td></tr><tr><td class=\"acctentry_c\"><i>Cash</i></td><td class=\"debit_credit\">&nbsp;</td><td class=\"debit_credit\">xxx</td></tr></table>";
arrAnsChoices[2] = "<table cols=\"3\" cellspacing=\"0\" cellpadding=\"1\" style=\"width: 90%; margin-top:0em; margin-bottom:0em\"><tr><td class=\"acctentry_d\"><i>Death Claims Paid</i></td><td class=\"debit_credit\">xxx</td><td class=\"debit_credit\">&nbsp;</td></tr><tr><td class=\"acctentry_c\"><i>Cash</i></td><td class=\"debit_credit\">&nbsp;</td><td class=\"debit_credit\">xxx</td></tr></table>";
arrAnsChoices[3] = "<table cols=\"3\" cellspacing=\"0\" cellpadding=\"1\" style=\"width: 90%; margin-top:0em; margin-bottom:0em\"><tr><td class=\"acctentry_d\"><i>Cash</i></td><td class=\"debit_credit\">xxx</td><td class=\"debit_credit\">&nbsp;</td></tr><tr><td class=\"acctentry_c\"><i>Death Claims Paid</i></td><td class=\"debit_credit\">&nbsp;</td><td class=\"debit_credit\">xxx</td></tr></table>";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445575;
arrAnsIDs[1] = 445576;
arrAnsIDs[2] = 445577;
arrAnsIDs[3] = 445578;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A typical accounting entry to record the payment of a death claim to a beneficiary on an approved claim on an ordinary life insurance policy that the insurer has not reinsured is a <b>debit</b> to <i>Death Claims Paid</i> and a <b>credit</b> to <i>Cash</i>. Accounts typically used to record and report death benefit payments include <i>Death Benefit Payments</i>, <i>Death Claims Paid</i>, or <i>Claim Settlements</i>.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A typical accounting entry to record the payment of a death claim to a beneficiary on an approved claim on an ordinary life insurance policy that the insurer has not reinsured is a <b>debit</b> to <i>Death Claims Paid</i> and a <b>credit</b> to <i>Cash</i>. Accounts typically used to record and report death benefit payments include <i>Death Benefit Payments</i>, <i>Death Claims Paid</i>, or <i>Claim Settlements</i>.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A death claim is a request for payment upon the death of the insured, under the terms and conditions of a life insurance policy. Most life insurance policies provide for payment of the policy’s face amount upon the insured’s death. However, in certain cases, the actual amount of the death benefit payable differs from the policy’s face amount. For example, universal life insurance policies may provide a benefit larger than the policy’s face amount. In these cases, the insurer makes adjustments to the amount payable to a policy beneficiary. Accounts typically used to record and report death benefit payments include <i>Death Benefit Payments</i>, <i>Death Claims Paid</i>, or <i>Claim Settlements</i>.</p><p class=\"explanations\"><b>Learning Objective: 8E. Describe the death benefit payment process, including the typical accounting entries that an insurer records at each step of the process.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A typical accounting entry to record the payment of a death claim to a beneficiary on an approved claim on an ordinary life insurance policy that the insurer has not reinsured is a <b>debit</b> to <i>Death Claims Paid</i> and a <b>credit</b> to <i>Cash</i>. Accounts typically used to record and report death benefit payments include <i>Death Benefit Payments</i>, <i>Death Claims Paid</i>, or <i>Claim Settlements</i>.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_063'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_064';
objQuestion.questionID = 110250;
objQuestion.item = 'LOMA_361_PPQ2019_064';
objQuestion.primaryLO = '8F';
objQuestion.textref = 'c. 8, pp. 15-16';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '8F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Milepost Life Insurance Company issued a $300,000 ordinary life insurance policy. Upon the death of the insured, the policy’s beneficiary decided to leave the policy proceeds on deposit with Milepost under a supplementary contract that will provide the beneficiary with a monthly income for life. The accounting entry that Milepost would make to establish this supplementary contract is</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "<table cols=\"3\" cellspacing=\"0\" cellpadding=\"1\" style=\"width: 90%; margin-top:0em; margin-bottom:0em\"><tr><td class=\"acctentry_d\"><i>Death Claims Paid—Ordinary</i></td><td class=\"debit_credit\">300,000</td><td class=\"debit_credit\">&nbsp;</td></tr><tr><td class=\"acctentry_c\"><i>Cash</i></td><td class=\"debit_credit\">&nbsp;</td><td class=\"debit_credit\">300,000</td></tr></table>";
arrAnsChoices[1] = "<table cols=\"3\" cellspacing=\"0\" cellpadding=\"1\" style=\"width: 90%; margin-top:0em; margin-bottom:0em\"><tr><td class=\"acctentry_d\"><i>Cash</i></td><td class=\"debit_credit\">300,000</td><td class=\"debit_credit\">&nbsp;</td></tr><tr><td class=\"acctentry_c\"><i>Death Claims Paid—Ordinary</i></td><td class=\"debit_credit\">&nbsp;</td><td class=\"debit_credit\">300,000</td></tr></table>";
arrAnsChoices[2] = "<table cols=\"3\" cellspacing=\"0\" cellpadding=\"1\" style=\"width: 90%; margin-top:0em; margin-bottom:0em\"><tr><td class=\"acctentry_d\"><i>Consideration for Supplementary Contracts with Life Contingencies</i></td><td class=\"debit_credit\">300,000</td><td class=\"debit_credit\">&nbsp;</td></tr><tr><td class=\"acctentry_c\"><i>Premium Income</i></td><td class=\"debit_credit\">&nbsp;</td><td class=\"debit_credit\">300,000</td></tr></table>";
arrAnsChoices[3] = "<table cols=\"3\" cellspacing=\"0\" cellpadding=\"1\" style=\"width: 90%; margin-top:0em; margin-bottom:0em\"><tr><td class=\"acctentry_d\"><i>Death Claims Paid—Ordinary</i></td><td class=\"debit_credit\">300,000</td><td class=\"debit_credit\">&nbsp;</td></tr><tr><td class=\"acctentry_c\"><i>Consideration for Supplementary Contracts with Life Contingencies</i></td><td class=\"debit_credit\">&nbsp;</td><td class=\"debit_credit\">300,000</td></tr></table>";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445579;
arrAnsIDs[1] = 445580;
arrAnsIDs[2] = 445581;
arrAnsIDs[3] = 445582;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A typical accounting entry to record the establishment of a life insurance policy settlement option is a debit to <i>Death Claims Paid—Ordinary</i> and a credit to <i>Consideration for Supplementary Contracts with Life Contingencies</i>.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A typical accounting entry to record the establishment of a life insurance policy settlement option is a debit to <i>Death Claims Paid—Ordinary</i> and a credit to <i>Consideration for Supplementary Contracts with Life Contingencies</i>.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A typical accounting entry to record the establishment of a life insurance policy settlement option is a debit to <i>Death Claims Paid—Ordinary</i> and a credit to <i>Consideration for Supplementary Contracts with Life Contingencies</i>.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A supplementary contract, also known as a settlement contract, typically arises from the election of a settlement option by a life insurance beneficiary. Payments on supplementary contracts typically are called contractual payments.</p><p class=\"explanations\">In addition to the typical lump-sum settlement of policy proceeds, insurers provide settlement options, which are alternative methods that the beneficiary can elect for receiving payment of the policy proceeds. Typical settlement options for individual life insurance policies are the interest option, fixed period option, fixed amount option, and life income option.</p><p class=\"explanations\"><b>Learning Objective: Explain how an insurer accounts for supplementary contract payments.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_064'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_065';
objQuestion.questionID = 110251;
objQuestion.item = 'LOMA_361_PPQ2019_065';
objQuestion.primaryLO = '8G';
objQuestion.textref = 'c. 8, pp. 16-17';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '8G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">When the Staunch Life Insurance Company receives an application and an initial premium payment for a life insurance policy, Staunch typically posts the premium payment to a liability account, because Staunch either lacks critical information about the premium payment or cannot accept the premium immediately as income until a particular event occurs. This information indicates that Staunch most likely would record receipt of the initial premium payment as a debit to</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "<i>Cash</i> and a credit to <i>Premium Suspense</i>";
arrAnsChoices[1] = "<i>Cash</i> and a credit to <i>Premium Incom</i>e";
arrAnsChoices[2] = "<i>Premium Suspense</i> and a credit to <i>Premium Income</i>";
arrAnsChoices[3] = "<i>Premium Income</i> and a credit to <i>Premium Suspense</i>";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445583;
arrAnsIDs[1] = 445584;
arrAnsIDs[2] = 445585;
arrAnsIDs[3] = 445586;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The accounting entry to record an insurer’s receipt of a premium typically includes a debit to <i>Cash</i>. and a credit to <i>Premium Income</i>. Sometimes the insurer is not able to determine immediately the credit entry to offset the debit to <i>Cash</i>. In this situation, many insurers credit a premium suspense account, such as <i>Premium Suspense</i>, which is a liability account.</p><p class=\"explanations\">Premium suspense accounts are used to record transactions that are intended as premiums, but that the insurer cannot accept as income until a particular event occurs, such as premium payment amounts (1) for renewal premiums, (2) that differ from the amounts in the insurer’s records, or (3) that lack critical information—a policy number or an underwriting decision on a new policy.</p><p class=\"explanations\">In this situation, upon underwriting and approval of the application, Staunch would debit <i>Premium Suspense</i> and credit <i>Premium Income</i> to record a suspensed premium to a premium income account. The end result of these two accounting entries is a debit to <i>Cash</i> and a credit to <i>Premium Income</i>—the typical accounting entry to record an insurer’s receipt of a premium.</p><p class=\"explanations\"><b>Learning Objective: 8G. Describe an insurer’s typical liabilities relating to premiums and expenses due or accrued.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The accounting entry to record an insurer’s receipt of a premium typically includes a debit to <i>Cash</i>. and a credit to <i>Premium Income</i>. However, sometimes an insurer cannot determine immediately the credit entry to offset the debit to <i>Cash</i>. In this situation, many insurers use <b>premium suspense</b> accounts, such as <i>Premium Suspense</i>, which is a liability account used to record transactions that are intended as premiums, but that the insurer cannot accept as income until a particular event occurs.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">This answer choice is the accounting entry that Staunch most likely would make upon underwriting and approval of the application <b>to record a suspense premium to a premium income account</b>. Note that the end result here is a debit to <i>Cash</i> and a credit to <i>Premium Income</i>.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The accounting entry to record an insurer’s receipt of a premium typically includes a debit to <i>Cash</i>. and a credit to <i>Premium Income</i>. However, sometimes an insurer cannot determine immediately the credit entry to offset the debit to <i>Cash</i>. In this situation, many insurers use <b>premium suspense</b> accounts, such as <i>Premium Suspense</i>, which is a liability account used to record transactions that are intended as premiums, but that the insurer cannot accept as income until a particular event occurs.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_065'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_066';
objQuestion.questionID = 110252;
objQuestion.item = 'LOMA_361_PPQ2019_066';
objQuestion.primaryLO = '8G';
objQuestion.textref = 'c. 8, p. 17';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '8G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">In the United States, when an insurer receives premiums before they are due, but which are due on or after the next policy anniversary date, the insurer reports these premiums as premiums paid in advance on the insurer’s U.S. GAAP and statutory financial statements. <i>Premiums Paid in Advance</i> is (<b>an&nbsp;asset / a liability</b>) account. This account (<b>differs from / is the same as</b>) the account known as a premium deposit fund.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "an asset / differs from";
arrAnsChoices[1] = "an asset / is the same as";
arrAnsChoices[2] = "a liability / differs from";
arrAnsChoices[3] = "a liability / is the same as";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445587;
arrAnsIDs[1] = 445588;
arrAnsIDs[2] = 445589;
arrAnsIDs[3] = 445590;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that <i>Premiums Paid in Advance </i>differs from the account known as the premium deposit fund. However, <i>Premiums Paid in Advance </i>is a <b>liability </b>account.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\"><i>Premiums Paid in Advance </i>is <b>not </b>an asset account. In addition, this account <b>differs from</b> the account known as the premium deposit fund.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">In the United States, when an insurer receives premiums before they are due, it reports a liability for premiums paid in advance on its U.S. GAAP and statutory financial statements. For life insurance contracts, premiums paid in advance, also called advance premiums, are premiums that an insurer has received but that are due on or after the next policy anniversary date.</p><p class=\"explanations\">Sometimes included in the category of premiums paid in advance are premium deposits, which, in this context, are amounts that an insurer’s policyowners leave on deposit with the insurer to pay for several years of premiums at one time. Because the insurer has the use of these policyowner funds before they are due, it typically discounts the premiums—in effect, receiving a smaller amount in cash.</p><p class=\"explanations\">However, a more common approach is to place premium deposits in a liability account known as a premium deposit fund. Under this approach, when an individual premium becomes due, the insurer pays it from the premium deposit fund and credits <i>Premium Income</i>.</p><p class=\"explanations\"><b>Learning Objective: 8G. Describe an insurer’s typical liabilities relating to premiums and expenses due or accrued.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that <i>Premiums Paid in Advance</i> is a liability account. However, this account <b>differs from</b> the account known as the premium deposit fund.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_066'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_067';
objQuestion.questionID = 110253;
objQuestion.item = 'LOMA_361_PPQ2019_067';
objQuestion.primaryLO = '8G';
objQuestion.textref = 'c. 8, pp. 18-20';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '8G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Under both SAP and GAAP, special rules apply to payments received for deposit-type contracts and investment contracts. Under SAP, contracts that do not expose the insurer to mortality risk or morbidity risk are known as <b>(deposit-type contracts / investment contracts)</b>. Under GAAP, long-duration contracts that do not expose the insurer to significant risks arising from policyowner or contract owner mortality are classified as<b> (deposit-type contracts / investment&nbsp;contracts)</b>.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "deposit-type contracts / deposit-type contracts";
arrAnsChoices[1] = "deposit-type contracts / investment contracts";
arrAnsChoices[2] = "investment contracts / deposit-type contracts";
arrAnsChoices[3] = "investment contracts / investment contracts";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445591;
arrAnsIDs[1] = 445592;
arrAnsIDs[2] = 445593;
arrAnsIDs[3] = 445594;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that, under SAP, contracts that do not expose the insurer to mortality risk or morbidity risk are known as deposit-type contracts. However, under GAAP, long-duration contracts that do not expose the insurer to significant risks arising from policyowner or contract owner mortality are <b>not</b> classified as deposit-type contracts.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Under SAP, deposit-type contracts that lack a mortality risk component—meaning, contracts that provide benefit payments that do not depend upon the death or continued survival of an individual or group of individuals—include GICs, annuities certain, supplemental contracts without life contingencies, and dividend accumulations. For deposit-type contracts, amounts received as payments are not considered premium income (revenue) but instead are reported directly to the appropriate liability account on the insurer’s statutory balance sheet, known as <i>Liability for deposit-type contracts</i>.</p><p class=\"explanations\">Under GAAP, accounting for investment contracts—examples include GICs and most deferred annuity contracts during the accumulation phase—is similar to accounting for interest-bearing or other financial instruments where the balance accrues to the benefit of the policyowner or contract owner. Under this approach, premiums or deposits received for investment contracts are recorded as a deposit liability rather than as revenue. A typical GAAP account title for this liability is <i>Funds held under deposit contracts</i>.</p><p class=\"explanations\"><b>Learning Objective: 8G. Describe an insurer’s typical liabilities relating to premiums and expenses due or accrued.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Under SAP, contracts that do not expose the insurer to mortality risk or morbidity risk are <b>not</b> known as investment contracts. In addition, under GAAP, long-duration contracts that do not expose the insurer to significant risks arising from policyowner or contract owner mortality are <b>not</b> classified as deposit-type contracts.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that, under GAAP, long-duration contracts are classified as investment contracts. However, under SAP, contracts that do not expose the insurer to mortality risk or morbidity risk are <b>not</b> known as investment contracts.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_067'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_068';
objQuestion.questionID = 110254;
objQuestion.item = 'LOMA_361_PPQ2019_068';
objQuestion.primaryLO = '8G';
objQuestion.textref = 'c. 8, pp. 21-22';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '8G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">An agent’s commission is considered due or accrued when the insurer receives a premium too late in the accounting period to process the commission payment to the agent by the financial reporting date. In this situation, most insurers maintain a separate file for each agent to track unpaid and owed agent commissions, and insurers report the cumulative amount to an account such as <i>Agent Commissions Due or Accrued</i>, which is an example of the type of account known as</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "an expense account";
arrAnsChoices[1] = "a suspense account";
arrAnsChoices[2] = "a liability account";
arrAnsChoices[3] = "a contra liability account";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445595;
arrAnsIDs[1] = 445596;
arrAnsIDs[2] = 445597;
arrAnsIDs[3] = 445598;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The account <i>Agent Commissions Due or Accrued</i> is <b>not </b>example of an expense<b> </b>account.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The account <i>Agent Commissions Due or Accrued</i> is <b>not </b>an example of a suspense<b> </b>account.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Agent commissions that are due or accrued are a significant liability for most insurers. Commissions are generally due or accrued only on premiums that have been received. Commissions are reported on the balance sheet as <i>Agent Commissions Due</i> <i>or Accrued </i>or <i>Producer Commissions Due or Accrued.</i></p><p class=\"explanations\">Most insurers maintain a separate file for each agent to track unpaid but owed commissions, and report the cumulative amount to an aggregate liability account such as <i>Agent Commissions Due or Accrued</i> or <i>Producer Commissions Due or Accrued</i>. When the insurer pays an agent accrued or due commissions, both the insurer’s cash and the aggregate liability account are decreased.</p><p class=\"explanations\"><b>Learning Objective: 8G. Describe an insurer’s typical liabilities relating to premiums and expenses due or accrued.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The account <i>Agent Commissions Due or Accrued</i> is <b>not </b>an example of a contra liability<b> </b>account.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_068'] = objQuestion;



arrMinicases[2] = "<p class=\"caseinfo\">Use the following information to answer questions 4 and 5.</p><p class=\"caseinfo\">When Darla Harrod decided to terminate her life insurance policy from the Pillar Life Insurance Company, she elected the cash surrender value nonforfeiture option. Ms.&nbsp;Harrod’s policy has a cash surrender value of $9,500, and the reserve released for this policy totals $10,000.</p>";


var arrlotext = new Array(); 
arrlotext['8A'] = "8A. Differentiate between the asset valuation reserve (AVR) and the interest maintenance reserve (IMR) and explain the purpose of these two statutory reserves.";
arrlotext['8B'] = "8B. List and describe the three types of policyowner dividend liabilities.";
arrlotext['8C'] = "8C. Explain how an insurer accounts for common types of policyowner dividend payment options.";
arrlotext['8D'] = "8D. Explain the accounting treatment of various nonforfeiture options.";
arrlotext['8E'] = "8E. Describe the death benefit payment process, including the typical accounting entries that an insurer records at each step of the process.";
arrlotext['8F'] = "8F. Explain how an insurer accounts for supplementary contract payments.";
arrlotext['8G'] = "8G. Describe an insurer’s typical liabilities relating to premiums and expenses due or accrued.";
