var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2019';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 361 Practice Questions, Chapter 7";
var coursename = 'LOMA 361';
var modulenumber = 2;
var title = "LOMA_361_PPQ2019_0_7";
var intNumPools = 1;
var numQ = 7;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Accounting and Financial Reporting in Life Insurance Companies, Second Edition (2019)";
arrNumChap[0] = 1;
var thisChap = '7';

objPool = new Object(); 
objPool.intSelectCount = 7;
objPool.formID = 2103;
objPool.formName = 'PPQ2019_0_7';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_361_PQ_051';
arrPoolQuestions[1] = 'LOMA_361_PQ_052';
arrPoolQuestions[2] = 'LOMA_361_PQ_053';
arrPoolQuestions[3] = 'LOMA_361_PQ_054';
arrPoolQuestions[4] = 'LOMA_361_PQ_055';
arrPoolQuestions[5] = 'LOMA_361_PQ_056';
arrPoolQuestions[6] = 'LOMA_361_PQ_057';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_051';
objQuestion.questionID = 110237;
objQuestion.item = 'LOMA_361_PPQ2019_051';
objQuestion.primaryLO = '7A';
objQuestion.textref = 'c. 7, p. 3';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '7A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statement(s) can correctly be made about life insurance company reserves:</p><ol type=\"A\" class=\"combo\"><li>Aggregate reserves are reserves for a block of insurance policies or contracts, a line of business, or an entire company.</li><li>Because the amount of an insurer’s future contractual obligations is known precisely in advance, determining the amount of a reserve is a relatively straightforward process.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445526;
arrAnsIDs[1] = 445527;
arrAnsIDs[2] = 445528;
arrAnsIDs[3] = 445529;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct. To determine the amount of reserves to record in its accounting records, insurers rely on actuaries, who are experts in financial risk management and who are responsible for ensuring that an insurer’s products are financially sound. Using mathematical probabilities, actuaries estimate the amounts needed to pay future benefits to the insurer’s customers. The insurer then records and reports these amounts as liabilities in its accounting records and on the insurer’s balance sheet.</p><p class=\"explanations\">Statement B is incorrect. For most insurance products, the amount of an insurer’s future contractual obligations is not known precisely in advance. Therefore, insurers must set adequate reserve amounts by identifying and consistently applying a reasonable set of actuarial assumptions and reserve valuation methods. In product design, insurers make actuarial assumptions with regard to many factors, such as future mortality rates, investment earnings, expenses, surrenders, and lapses.</p><p class=\"explanations\"><b>Learning Objective: 7A. Explain the importance of reserves and describe the role that actuaries play in establishing reserves.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is incorrect. For most insurance products, the amount of an insurer’s future contractual obligations is <b>not known</b> precisely in advance. Therefore, insurers must set adequate reserve amounts by identifying and consistently applying a reasonable set of actuarial assumptions and reserve valuation methods. In product design, insurers make actuarial assumptions with regard to many factors, such as future mortality rates, investment earnings, expenses, surrenders, and lapses.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_051'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_052';
objQuestion.questionID = 110238;
objQuestion.item = 'LOMA_361_PPQ2019_052';
objQuestion.primaryLO = '7B';
objQuestion.textref = 'c. 7, p. 4';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '7B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Reserves can vary depending on the type of accounting records an insurer uses. Common types of accounting records used by U.S. insurers include statutory accounting records, GAAP accounting records, internal accounting records, and tax accounting records. <b>(Statutory / GAAP)</b> accounting records are designed to comply with the financial reporting requirements established by state insurance regulators. <b>(Statutory / GAAP)</b> accounting records are a type of profitability-basis accounting.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Statutory / Statutory";
arrAnsChoices[1] = "Statutory / GAAP";
arrAnsChoices[2] = "GAAP / Statutory";
arrAnsChoices[3] = "GAAP / GAAP";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445530;
arrAnsIDs[1] = 445531;
arrAnsIDs[2] = 445532;
arrAnsIDs[3] = 445533;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that statutory accounting records are designed to comply with the financial reporting requirements established by state insurance regulators. However, <B>GAAP</B> accounting records are a type of profitability-basis accounting.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statutory accounting records, also called solvency-basis accounting records, are designed to comply with the financial reporting requirements established by state insurance regulators. Statutory accounting records are a type of solvency-basis accounting. Reserves calculated under statutory accounting are called statutory reserves, required reserves, and solvency-basis reserves.</p><p class=\"explanations\">GAAP accounting records are designed for financial reporting to investors, noninsurance regulators (such as the SEC in the United States), and the general public. In the United States, all stock insurance companies and many mutual insurance companies maintain accounting records and prepare financial statements according to GAAP. Because GAAP accounting records focus on showing a company’s financial stability and its profitability, GAAP is a type of profitability-basis accounting. The reserves calculated for GAAP-based financial statements are called GAAP reserves or profitability-basis reserves.</p><p class=\"explanations\"><b>Learning Objective: 7B. Identify the types of accounting records commonly used in life insurance companies and the category of reserves associated with each type.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\"><b>Statutory accounting records</b> are designed to comply with the financial reporting requirements established by state insurance regulators. Also, <B>GAAP</B> accounting records are a type of profitability-basis accounting.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that GAAP accounting records are a type of profitability-basis accounting. However, <b>statutory accounting records</b> are designed to comply with the financial reporting requirements established by state insurance regulators.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_052'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_053';
objQuestion.questionID = 110239;
objQuestion.item = 'LOMA_361_PPQ2019_053';
objQuestion.primaryLO = '7C';
objQuestion.textref = 'c. 7, p. 5';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '7C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">One type of reserve is a liability amount that an insurer estimates it will need to pay the insurer’s business obligations that are not directly attributable to benefits payable for a specified product. By definition, this type of reserve is a</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "contractual reserve";
arrAnsChoices[1] = "tabular reserve";
arrAnsChoices[2] = "legal reserve";
arrAnsChoices[3] = "noncontractual reserve";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445534;
arrAnsIDs[1] = 445535;
arrAnsIDs[2] = 445536;
arrAnsIDs[3] = 445537;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A <b>contractual reserve</b> is a liability that identifies the amount that, together with future premiums and investment earnings, represents the expected amount of future <b>benefits payable</b> on an insurer’s in-force business. In other words, contractual reserves are the insurer’s estimates for the amounts it needs on hand today to pay contractual benefits on a product as they come due.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A <b>tabular reserve</b> is a term for a contractual reserve, which is a liability that identifies the amount that, together with future premiums and investment earnings, represents the expected amount of future <b>benefits payable</b> on an insurer’s in-force business. In other words, contractual reserves are the insurer’s estimates for the amounts it needs on hand today to pay contractual benefits on a product as they come due.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A <b>legal reserve</b> is a term for a contractual reserve, which is a liability that identifies the amount that, together with future premiums and investment earnings, represents the expected amount of future <b>benefits payable</b> on an insurer’s in-force business. In other words, contractual reserves are the insurer’s estimates for the amounts it needs on hand today to pay contractual benefits on a product as they come due.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A contractual reserve is a liability that identifies the amount that, together with future premiums and investment earnings, represents the expected amount of future benefits payable on an insurer’s in-force business. In other words, contractual reserves are the insurer’s estimates for the amounts it needs on hand today to pay contractual benefits on a product as they come due. Other terms sometimes used for contractual reserves include policy reserves, legal reserves, and tabular reserves in the United States and similar terms in other countries.</p><p class=\"explanations\">All reserves that are not contractual reserves are classified as noncontractual reserves. Two examples of noncontractual reserves for life insurers are the asset valuation reserve (AVR) and the interest maintenance reserve (IMR), which are statutory accounts designed to absorb gains and losses on the insurer’s invested assets.</p><p class=\"explanations\"><b>Learning Objective: 7C. Differentiate between contractual reserves and noncontractual reserves.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_053'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_054';
objQuestion.questionID = 110240;
objQuestion.item = 'LOMA_361_PPQ2019_054';
objQuestion.primaryLO = '7D';
objQuestion.textref = 'c. 7, pp. 5-6';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '7D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about the differences between GAAP reserves and statutory reserves. Select the answer choice containing the correct statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A recent Accounting Standard Update (ASU) from the Financial Accounting Standards Board (FASB) requires U.S. GAAP reserves to be based on principles-based reserving.";
arrAnsChoices[1] = "Historically, U.S. GAAP did not allow an insurer to modify the actuarial assumptions on which it calculated its GAAP reserves, even if the assumptions at policy issue turned out to be wrong.";
arrAnsChoices[2] = "Statutory reserves permit insurers to include a provision for adverse deviation (PAD) in estimates of future policy benefits to allow for unfavorable variations from actuarial assumptions.";
arrAnsChoices[3] = "State regulators recently have endorsed rules-based reserving so that the reserves an insurer holds for a specific product are based on the insurer’s own experience and risks.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445538;
arrAnsIDs[1] = 445539;
arrAnsIDs[2] = 445540;
arrAnsIDs[3] = 445541;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">In June 2018, the FASB issued its ASU entitled <i>Targeted Improvements to the Accounting for Long-Duration Contracts</i>. According to this ASU, estimates of future policy benefits under U.S. GAAP <b>no longer will need to include a provision for adverse deviation (PAD)</b>, which is a safety margin that allowed for unfavorable variations from actuarial assumptions.</p><p class=\"explanations\">In recent years, <b>state regulators</b> have endorsed <b>principles-based reserving (PBR)</b>, which attempts to “right-size” an insurer’s statutory reserves, so that the reserves an insurer holds for a specific product are based on the insurer’s own experience and risks.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Under U.S. GAAP, although insurers had not been allowed to modify the actuarial assumptions on which GAAP reserves were calculated, they were allowed to include a provision for adverse deviation (PAD), a safety margin that allowed for unfavorable variations from actuarial assumptions. Recently, the FASB issued ASU <i>Targeted Improvements to the Accounting for Long-Duration Contracts</i> ASU, which allows insurers to update actuarial assumptions. As a result of this ASU, estimates of future policy benefits under GAAP will no longer need to include a PAD.</p><p class=\"explanations\">State regulators had mandated that life insurers establish statutory reserves based on prescribed formulas and assumptions. Under this approach, typically known as rules-based reserving, all life insurers that sold a specific product were required to use the same formula for reserve valuation and the same estimates of future mortality and investment experience. Rules-based reserving created situations in which some insurers were holding either too little or too much in statutory reserves for a given product. To address this imbalance, state regulators have endorsed principles-based<b> </b>reserving (PBR) for most individual life insurance products. PBR attempts to “right-size” an insurer’s reserves; an insurer holds reserves for a product based on the insurer’s experience and risks. PBR is expected to be developed for additional product lines.</p><p class=\"explanations\"><b>Learning Objective: 7D. Describe changes in how insurers estimate their GAAP reserves and statutory reserves.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Under <B>U.S. GAAP</B>, estimates of future policy benefits traditionally have been allowed to include a <b>provision for adverse deviation (PAD)</b>, a safety margin that allowed for unfavorable variations from actuarial assumptions. Recent regulatory changes allow insurers to update actuarial assumptions, so future policy benefits under GAAP will no longer need to include a PAD.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">State regulators had mandated that life insurers establish statutory reserves based on prescribed formulas and assumptions. Under this approach, typically known as rules-based reserving, all life insurers that sold a specific product were required to use the same formula for reserve valuation and the same estimates of future mortality and investment experience. Rules-based reserving created situations in which some insurers were holding either too little or too much in statutory reserves for a given product. To address this imbalance, state regulators have endorsed <b>principles-based reserving (PBR)</b> for most individual life insurance products. PBR attempts to “right-size” an insurer’s reserves; an insurer holds reserves for a product based on the insurer’s experience and risks.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_054'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_055';
objQuestion.questionID = 110241;
objQuestion.item = 'LOMA_361_PPQ2019_055';
objQuestion.primaryLO = '7E';
objQuestion.textref = 'c. 7, pp. 8-9';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '7E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Maze Life Insurance Company established a reserve for a $700,000 block of life insurance policies. At the time when $700,000 in policy benefits was paid, the balance in the reserve account for this block of policies was $300,000. Maze paid no policy dividends or cash dividends on this block of policies. Upon payment of the $700,000 policy benefits, Maze would release the $300,000 reserve amount. As a result of these transactions, Maze’s net income and surplus would</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "decrease by $300,000";
arrAnsChoices[1] = "decrease by $400,000";
arrAnsChoices[2] = "decrease by $700,000";
arrAnsChoices[3] = "remain the same";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445542;
arrAnsIDs[1] = 445543;
arrAnsIDs[2] = 445544;
arrAnsIDs[3] = 445545;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Upon the payment of the $700,000 in policy benefits, Maze would release $300,000 of reserves. Maze’s net income would decrease by $400,000, calculated as $700,000 – $300,000, which is the difference between the amount of the benefit payments and the amount of the released reserve for this block of policies, all other factors remaining equal. When it closes out the accounting period, Maze adds net income to surplus. All other factors remaining equal, the impact on Maze’s surplus also is a decrease of $400,000 instead of $700,000, because of the released reserve.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Upon the payment of the $700,000 in policy benefits, Maze would release $300,000 of reserves. Maze’s net income would decrease by $400,000, calculated as $700,000 – $300,000, which is the difference between the amount of the benefit payments and the amount of the released reserve for this block of policies, all other factors remaining equal. When it closes out the accounting period, Maze adds net income to surplus. All other factors remaining equal, the impact on Maze’s surplus also is a decrease of $400,000 instead of $700,000, because of the released reserve.</p><p class=\"explanations\"><b>Learning Objective: 7E. Explain how insurers account for reserves in their accounting records and financial statements.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Upon the payment of the $700,000 in policy benefits, Maze would release $300,000 of reserves. Maze’s net income would decrease by $400,000, calculated as $700,000 – $300,000, which is the difference between the amount of the benefit payments and the amount of the released reserve for this block of policies, all other factors remaining equal. When it closes out the accounting period, Maze adds net income to surplus. All other factors remaining equal, the impact on Maze’s surplus also is a decrease of $400,000 instead of $700,000, because of the released reserve.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Upon the payment of the $700,000 in policy benefits, Maze would release $300,000 of reserves. Maze’s net income would decrease by $400,000, calculated as $700,000 – $300,000, which is the difference between the amount of the benefit payments and the amount of the released reserve for this block of policies, all other factors remaining equal. When it closes out the accounting period, Maze adds net income to surplus. All other factors remaining equal, the impact on Maze’s surplus also is a decrease of $400,000 instead of $700,000, because of the released reserve.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_055'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_056';
objQuestion.questionID = 110242;
objQuestion.item = 'LOMA_361_PPQ2019_056';
objQuestion.primaryLO = '7F';
objQuestion.textref = 'c. 7, pp. 9-10';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '7F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Hardy Life Insurance Company decided that the reserves for its whole life insurance product were too low and decided to strengthen its reserves. Select the answer choice that correctly identifies whether reserve strengthening would result in an increase or a decrease in Hardy’s capital and surplus and whether Hardy would be using actuarial assumptions that are more or less favorable to the company than those used in the original reserve valuation.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[-1] = "<u>Increase/Decrease?</u></div><div class=\"anshead\"><u>More/Less favorable?</u>";
arrAnsChoices[0] = "increase</div><div class=\"anscell\" onclick=\"recordAns(1);\">more";
arrAnsChoices[1] = "increase</div><div class=\"anscell\" onclick=\"recordAns(2);\">less";
arrAnsChoices[2] = "decrease</div><div class=\"anscell\" onclick=\"recordAns(3);\">more";
arrAnsChoices[3] = "decrease</div><div class=\"anscell\" onclick=\"recordAns(4);\">less";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445547;
arrAnsIDs[1] = 445548;
arrAnsIDs[2] = 445549;
arrAnsIDs[3] = 445550;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Reserve <b>strengthening</b> results in a <b>decrease</b> in the insurer’s capital and surplus. In addition, when an insurer <b>strengthens</b> reserves, the insurer uses actuarial assumptions that are <b>less</b> favorable to the company than those used in the original reserve valuation.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that, in reserve strengthening, an insurer uses actuarial assumptions that are less favorable to the company than those used in the original reserve valuation. However, reserve <b>strengthening</b> results in a <b>decrease</b> in the insurer’s capital and surplus.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that Hardy’s reserve strengthening would result in a decrease in its capital and surplus. However, when an insurer <b>strengthens </b>reserves, the insurer uses actuarial assumptions that are <b>less</b> favorable to the company than those used in the original reserve valuation.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">An insurer’s liabilities consist primarily of its reserves for contractual benefits. If a reserve is too low, an insurer may consider strengthening it. Typically, this situation occurs if the insurer’s experience with a product reveals that the assumptions used to calculate contractual reserves were too optimistic. Insurers strengthen reserves by using actuarial assumptions that are less favorable to the company than those used in the original reserve valuation.</p><p class=\"explanations\">Conversely, an insurer may decide, based on its experience with a product, that the product’s reserves are too high, calling for reserve destrengthening. Insurers destrengthen reserves by using actuarial assumptions that are more favorable to the company than those used in the original reserve valuation. For insurers that operate in the United States, reserve destrengthening requires regulatory permission from the insurance commissioner in the insurer’s state of domicile. In practice, insurers rarely destrengthen their contractual reserves.</p><p class=\"explanations\">Think of the effects of reserve strengthening and reserve destrengthening in terms of the basic accounting equation: Assets = Liabilities + Capital and Surplus. Strengthening reserves increases Reserves (Liabilities) on the right side of the basic accounting equation, but results in no change in Assets on the left side of the equation. Because the basic accounting equation must balance, Capital and Surplus must decrease. In contrast, reserve destrengthening means a decrease in Reserves (Liabilities), and an increase in Capital and Surplus, all other factors remaining equal.</p><p class=\"explanations\"><b>Learning Objective: 7F. Explain the effect of reserve strengthening and reserve destrengthening on an insurer’s surplus.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_056'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_057';
objQuestion.questionID = 110243;
objQuestion.item = 'LOMA_361_PPQ2019_057';
objQuestion.primaryLO = '7G';
objQuestion.textref = 'c. 7, pp. 10-11';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '7G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about surplus strain and surplus relief. Three statements are true, and one statement is false. Select the answer choice containing the <B>FALSE </B>statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Surplus strain is the increase in an insurer’s surplus caused by the high first-year costs and the reserve requirements associated with new products.";
arrAnsChoices[1] = "Under U.S. statutory accounting, insurers use specially adjusted reserves, known as modified reserves, to spread out the impact of surplus strain.";
arrAnsChoices[2] = "Under U.S. GAAP, insurers can reduce surplus strain by using deferred acquisition costs (DAC) to spread out, through amortization, the reporting of acquisition costs and issue costs over several years.";
arrAnsChoices[3] = "The reduction in surplus strain that is achieved by using reinsurance is a type of surplus relief.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445551;
arrAnsIDs[1] = 445552;
arrAnsIDs[2] = 445553;
arrAnsIDs[3] = 445554;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">This statement is false; therefore, it is the correct response. For a new product, first-year costs of contract issue, sales commissions, and the creation of new reserves typically combine to produce a negative first-year surplus, which is an aspect of surplus strain. Surplus strain, also known as issue strain or new business strain, is the <b>decrease</b> in an insurer’s surplus caused by the high first-year costs and the reserve requirements associated with new products. Surplus relief is a decrease in potential surplus strain that strengthens an insurer’s financial position.</p><p class=\"explanations\"><b>Learning Objective: 7G. Describe how surplus strain can be relieved by the use of deferred acquisition costs (DAC), modified reserves, and reinsurance.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response. Under statutory accounting, life insurers can use modified reserve valuation, in which an insurer sets a lower-than-level first-year contractual reserve in recognition of a product’s high first-year expenses. This first-year reserve adjustment affects contractual reserve values for all subsequent years of the product’s existence.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response. When analysts study U.S. GAAP financial statements to evaluate an insurer’s strength, they typically adjust GAAP reserves for DAC to produce a measure known as net GAAP reserves: GAAP Reserves – DAC = Net GAAP Reserves.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response. A reserve credit is the solvency-basis accounting entry the direct writer uses to record a reduction of reserves due to the use of reinsurance. Despite its name, a reserve credit is actually posted as a debit; this means that a reserve credit decreases the amount of reserves as a result of reinsurance.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_057'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['7A'] = "7A. Explain the importance of reserves and describe the role that actuaries play in establishing reserves.";
arrlotext['7B'] = "7B. Identify the types of accounting records commonly used in life insurance companies and the category of reserves associated with each type.";
arrlotext['7C'] = "7C. Differentiate between contractual reserves and noncontractual reserves.";
arrlotext['7D'] = "7D. Describe changes in how insurers estimate their GAAP reserves and statutory reserves.";
arrlotext['7E'] = "7E. Explain how insurers account for reserves in their accounting records and financial statements.";
arrlotext['7F'] = "7F. Explain the effect of reserve strengthening and reserve destrengthening on an insurer’s surplus.";
arrlotext['7G'] = "7G. Describe how surplus strain can be relieved by the use of deferred acquisition costs (DAC), modified reserves, and reinsurance.";
