var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2020';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 361 Practice Questions, Chapter 11";
var coursename = 'LOMA 361';
var modulenumber = 2;
var title = "LOMA_361_PPQ2019_0_11";
var intNumPools = 1;
var numQ = 9;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Accounting and Financial Reporting in Life Insurance Companies, Second Edition (2019)";
arrNumChap[0] = 1;
var thisChap = '11';

objPool = new Object(); 
objPool.intSelectCount = 9;
objPool.formID = 2103;
objPool.formName = 'PPQ2019_0_11';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_361_PQ_090';
arrPoolQuestions[1] = 'LOMA_361_PQ_091';
arrPoolQuestions[2] = 'LOMA_361_PQ_092';
arrPoolQuestions[3] = 'LOMA_361_PQ_093';
arrPoolQuestions[4] = 'LOMA_361_PQ_094';
arrPoolQuestions[5] = 'LOMA_361_PQ_095';
arrPoolQuestions[6] = 'LOMA_361_PQ_096';
arrPoolQuestions[7] = 'LOMA_361_PQ_097';
arrPoolQuestions[8] = 'LOMA_361_PQ_098';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_090';
objQuestion.questionID = 110276;
objQuestion.item = 'LOMA_361_PPQ2019_090';
objQuestion.primaryLO = '11A';
objQuestion.textref = 'c. 11, pp. 2-3';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '11A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">A ratio is a comparison of two numeric values expressed in the form of a fraction or a percentage. The following statements are about the general characteristics of ratios. Select the answer choice containing the correct statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "The value of a ratio will increase if the value of the numerator increases while the value of the denominator remains unchanged.";
arrAnsChoices[1] = "When a ratio is expressed in fraction form, the number in the bottom part of the fraction is known as the numerator.";
arrAnsChoices[2] = "The value of a ratio will increase if the denominator increases while the numerator remains unchanged.";
arrAnsChoices[3] = "When a financial ratio is expressed in fraction form, the number in the top part of the fraction is known as the denominator.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445686;
arrAnsIDs[1] = 445687;
arrAnsIDs[2] = 445688;
arrAnsIDs[3] = 445689;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">When a ratio is expressed in fraction form, the number on the top part of the fraction is the numerator and the number in the bottom part of the fraction is the denominator. The rules for interpreting changes in ratios when the ratios are expressed in fractions are as follows:</p><p class=\"explanations\">The value of a ratio will increase if the value of the (1) numerator increases while the value of the denominator remains unchanged or the (2) denominator decreases while the value of the numerator remains unchanged.</p><p class=\"explanations\">The value of a ratio will decrease if the value of the (1) numerator decreases while the value of the denominator remains unchanged or the (2) denominator increases while the value of the numerator remains unchanged.</p><p class=\"explanations\"><b>Learning Objective: 11A. Interpret the results of various financial ratios.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">When a ratio is expressed in fraction form, the number on the <b>top </b>part of the fraction is the numerator and the number in the bottom part of the fraction is the denominator.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The value of a ratio will <b>decrease </b>if the value of the numerator decreases while the value of the denominator remains unchanged.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">When a ratio is expressed in fraction form, the number on the top part of the fraction is the <b>numerator </b>and the number in the bottom part of the fraction is the denominator.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_090'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_091';
objQuestion.questionID = 110277;
objQuestion.item = 'LOMA_361_PPQ2019_091';
objQuestion.primaryLO = '11A';
objQuestion.textref = 'c. 11, pp. 6-7';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '11A';
arrLOs[1] = '11C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = 3;
objQuestion.strStem = "<p class=\"stem\">Vista’s nonadmitted assets ratio at the end of last year is equal to</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "1.0%";
arrAnsChoices[1] = "1.7%";
arrAnsChoices[2] = "7.3%";
arrAnsChoices[3] = "13.6%";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445690;
arrAnsIDs[1] = 445691;
arrAnsIDs[2] = 445692;
arrAnsIDs[3] = 445693;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Under SAP, an insurance-specific liquidity ratio is the nonadmitted assets ratio, which compares an insurer’s nonadmitted assets to its surplus: Nonadmitted Assets ÷ Surplus. Vista’s nonadmitted assets ratio at the end of last year is equal to $22,000 ÷ $300,000 = 0.0733 or 7.3%.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Under SAP, an insurance-specific liquidity ratio is the nonadmitted assets ratio, which compares an insurer’s nonadmitted assets to its surplus: Nonadmitted Assets ÷ Surplus. Vista’s nonadmitted assets ratio at the end of last year is equal to $22,000 ÷ $300,000 = 0.0733 or 7.3%.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Under SAP, an insurance-specific liquidity ratio is the nonadmitted assets ratio, which compares an insurer’s nonadmitted assets to its surplus: Nonadmitted Assets ÷ Surplus. Nonadmitted assets comprise an insurer’s highly illiquid assets. In general, the lower the value for this ratio, the better, because a lower value indicates that the insurer has a smaller amount of nonadmitted assets. Vista’s nonadmitted assets ratio at the end of last year is equal to $22,000 ÷ $300,000 = 0.0733 or 7.3%.</p><p class=\"explanations\"><b>Learning Objectives: (1) 11A. Interpret the results of various financial ratios; (2) 11C. Distinguish among common financial ratios that fall into each of these categories: liquidity, operating performance, leverage, capital and surplus adequacy, and profitability.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Under SAP, an insurance-specific liquidity ratio is the nonadmitted assets ratio, which compares an insurer’s nonadmitted assets to its surplus: Nonadmitted Assets ÷ Surplus. Vista’s nonadmitted assets ratio at the end of last year is equal to $22,000 ÷ $300,000 = 0.0733 or 7.3%.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_091'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_092';
objQuestion.questionID = 110278;
objQuestion.item = 'LOMA_361_PPQ2019_092';
objQuestion.primaryLO = '11A';
objQuestion.textref = 'c. 11, pp. 15-16';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '11A';
arrLOs[1] = '11C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = 3;
objQuestion.strStem = "<p class=\"stem\">Vista’s insurance leverage ratio at the end of last year is equal to</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "0.29";
arrAnsChoices[1] = "0.74";
arrAnsChoices[2] = "1.08";
arrAnsChoices[3] = "3.48";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445694;
arrAnsIDs[1] = 445695;
arrAnsIDs[2] = 445696;
arrAnsIDs[3] = 445697;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The insurance leverage ratio, also called the gross leverage ratio, compares an insurer’s contractual reserves to its capital and surplus: Contractual Reserves ÷ Capital and Surplus. Vista’s insurance leverage ratio at the end of last year is equal to $1,600,000 ÷ $460,000 = 3.48.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The insurance leverage ratio, also called the gross leverage ratio, compares an insurer’s contractual reserves to its capital and surplus: Contractual Reserves ÷ Capital and Surplus. Vista’s insurance leverage ratio at the end of last year is equal to $1,600,000 ÷ $460,000 = 3.48.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The insurance leverage ratio, also called the gross leverage ratio, compares an insurer’s contractual reserves to its capital and surplus: Contractual Reserves ÷ Capital and Surplus. Vista’s insurance leverage ratio at the end of last year is equal to $1,600,000 ÷ $460,000 = 3.48.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The basic leverage ratio focuses on a company’s debt obligations in relation to its ability to meet those obligations: Liabilities ÷ Capital. Life insurance companies typically have little or no debt in the form of borrowed money that must be repaid with interest. Instead, they have a significant amount of their liabilities in the form of reserves for contractual benefits.</p><p class=\"explanations\">Thus, a more meaningful leverage ratio for insurers replaces (1) liabilities with contractual reserves and (2) capital with capital and surplus. The insurance leverage ratio, also called the gross leverage ratio, compares an insurer’s contractual reserves to its capital and surplus: Contractual Reserves ÷ Capital and Surplus. Vista’s insurance leverage ratio at the end of last year is equal to $1,600,000 ÷ $460,000 = 3.48.</p><p class=\"explanations\"><b>Learning Objectives: (1) 11A. Interpret the results of various financial ratios; (2) 11C. Distinguish among common financial ratios that fall into each of these categories: liquidity, operating performance, leverage, capital and surplus adequacy, and profitability.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_092'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_093';
objQuestion.questionID = 110279;
objQuestion.item = 'LOMA_361_PPQ2019_093';
objQuestion.primaryLO = '11A';
objQuestion.textref = 'c. 11, pp. 21-22, 23';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '11A';
arrLOs[1] = '11C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = 3;
objQuestion.strStem = "<p class=\"stem\">Vista’s investment yield ratio for last year is equal to</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "5.9%";
arrAnsChoices[1] = "7.4%";
arrAnsChoices[2] = "10.0%";
arrAnsChoices[3] = "11.1%";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445698;
arrAnsIDs[1] = 445699;
arrAnsIDs[2] = 445700;
arrAnsIDs[3] = 445701;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The investment yield ratio, also called the net yield, shows how efficiently the insurer used its invested assets to earn a return. This ratio compares the insurer’s net investment income to the insurer’s average invested assets for the reporting period: Investment Income ÷ Average Invested Assets. Vista’s investment yield ratio for last year is equal to $127,500 ÷ $1,725,000 = 0.0739 or 7.4%.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The investment yield ratio, also called the net yield, shows how efficiently the insurer used its invested assets to earn a return. This ratio compares the insurer’s net investment income to the insurer’s average invested assets for the reporting period: Investment Income ÷ Average Invested Assets. Vista’s investment yield ratio for last year is equal to $127,500 ÷ $1,725,000 = 0.0739 or 7.4%.</p><p class=\"explanations\"><b>Learning Objectives: (1) 11A. Interpret the results of various financial ratios; (2) 11C. Distinguish among common financial ratios that fall into each of these categories: liquidity, operating performance, leverage, capital and surplus adequacy, and profitability.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The investment yield ratio, also called the net yield, shows how efficiently the insurer used its invested assets to earn a return. This ratio compares the insurer’s net investment income to the insurer’s average invested assets for the reporting period: Investment Income ÷ Average Invested Assets. Vista’s investment yield ratio for last year is equal to $127,500 ÷ $1,725,000 = 0.0739 or 7.4%.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The investment yield ratio, also called the net yield, shows how efficiently the insurer used its invested assets to earn a return. This ratio compares the insurer’s net investment income to the insurer’s average invested assets for the reporting period: Investment Income ÷ Average Invested Assets. Vista’s investment yield ratio for last year is equal to $127,500 ÷ $1,725,000 = 0.0739 or 7.4%.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_093'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_094';
objQuestion.questionID = 110280;
objQuestion.item = 'LOMA_361_PPQ2019_094';
objQuestion.primaryLO = '11A';
objQuestion.textref = 'c. 11, pp. 8-9';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '11A';
arrLOs[1] = '11C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Lotus Life Insurance Company is using the following ratio as part of an analysis of its performance over time:</p><p class=\"stem\" style=\"text-align: center\"><b>General Insurance Expenses ÷ Premiums and Considerations</b></p><p class=\"stem\">In this situation, Lotus is calculating a type of ratio called the</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "return on assets ratio (ROA), which is an operating performance ratio";
arrAnsChoices[1] = "return on assets ratio (ROA), which is a leverage ratio";
arrAnsChoices[2] = "general expense ratio, which is an operating performance ratio";
arrAnsChoices[3] = "general expense ratio, which is a leverage ratio";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445702;
arrAnsIDs[1] = 445703;
arrAnsIDs[2] = 445704;
arrAnsIDs[3] = 445705;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that Lotus is using an operating performance ratio. However, Lotus is <b>not</b> using ROA, which is a type of <b>profitability</b> ratio.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Lotus is <b>not</b> using a <b>leverage ratio</b> or ROA, which is a type of <b>profitability</b> ratio.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Insurers use several types of ratios to measure their operating performance, such as the general expense ratio, the benefits ratio, and the lapse and surrender ratio. Insurers generally use statutory data to calculate these ratios, because this data is more conservative than is GAAP data. The general expense ratio expresses, for a given reporting period, an insurer’s general insurance expenses as a percentage of premiums, annuity considerations, and considerations on supplementary contracts with life contingencies.</p><p class=\"explanations\">General insurance expenses include rent, salaries and wages, legal fees, medical examination fees, advertising, and rental of equipment, but they do not include contractual benefit expenses. The lower the general expense ratio, the better. A general expense ratio below 100 percent indicates that the insurer is collecting more premiums and considerations than it is paying out in general insurance expenses.</p><p class=\"explanations\"><b>Learning Objective: (1) 11A. Interpret the results of various financial ratios; (2) 11C. Distinguish among common financial ratios that fall into each of these categories: liquidity, operating performance, leverage, capital and surplus adequacy, and profitability.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that Lotus is using the general expense ratio. However, the general expense ratio is <b>not </b>a type of leverage ratio.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_094'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_095';
objQuestion.questionID = 110281;
objQuestion.item = 'LOMA_361_PPQ2019_095';
objQuestion.primaryLO = '11B';
objQuestion.textref = 'c. 11, pp. 13-14';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '11B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Stateside Company borrowed funds at a fixed interest rate of 7%, and used the borrowed funds to invest in securities that earned an 8% return. In this situation, Stateside experienced the type of leverage known as</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "negative operating leverage";
arrAnsChoices[1] = "negative financial leverage";
arrAnsChoices[2] = "positive operating leverage";
arrAnsChoices[3] = "positive financial leverage";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445706;
arrAnsIDs[1] = 445707;
arrAnsIDs[2] = 445708;
arrAnsIDs[3] = 445709;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Stateside did <b>not</b> experience <b>operating</b> leverage, which is the effect whereby incurring fixed operating costs automatically magnifies a company’s risks and potential returns. In addition, Stateside did <b>not</b> experience a <b>negative</b> leverage effect, which occurs when a company earns a smaller profit, lower potential returns, or incurs a loss as a result of leverage.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that Stateside experienced financial leverage. However, Stateside did <b>not</b> experience a <b>negative</b> leverage effect, which occurs when a company earns a smaller profit, lower potential returns, or incurs a loss as a result of leverage.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that Stateside experienced a positive leverage effect. However, Stateside did not experience <b>operating</b> leverage, which is the effect whereby incurring fixed operating costs automatically magnifies a company’s risks and potential returns.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The relationship between leverage, risk, and returns (earnings) is such that, as a company’s leverage increases, the company’s exposure to risk of loss increases, and the company’s potential for earnings also increases. Similarly, as a company’s leverage decreases, the company’s exposure to risk of loss decreases, and the company’s potential for earnings also decreases.</p><p class=\"explanations\">The three main types of leverage are operating leverage, financial leverage, and total leverage. Operating leverage is the effect whereby incurring fixed operating costs automatically magnifies a company’s risks and potential returns. Financial leverage is the effect whereby incurring fixed financing costs—usually borrowed funds—automatically magnifies a company’s risks and potential returns. Total leverage is the combined effect of operating leverage and financial leverage.</p><p class=\"explanations\">Leverage can be either positive or negative. The effect of earning a larger profit or higher potential returns as a result of leverage is called a positive leverage effect. The effect of earning a smaller profit, lower potential returns, or incurring a loss as a result of leverage is called a negative leverage effect. When a company experiences negative leverage, it finds itself in a worse position than if it had not taken on the additional fixed costs in the first place. In this situation, Stateside earned a return on its invested funds that was greater than the interest rate Stateside paid on its borrowed funds; therefore, Stateside experienced positive financial leverage.</p><p class=\"explanations\"><b>Learning Objective: 11B. Compare and contrast operating leverage, financial leverage, positive leverage effects, and negative leverage effects.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_095'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_096';
objQuestion.questionID = 110282;
objQuestion.item = 'LOMA_361_PPQ2019_096';
objQuestion.primaryLO = '11C';
objQuestion.textref = 'c. 11, pp. 17-19';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '11C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">One type of financial ratio expresses the relationship between two amounts: (1) the amount of money invested in an insurer by its owners plus the cumulative amount of money that remains in the insurer over time and (2) the insurer’s liabilities. This type of financial ratio is known as a</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "leverage ratio";
arrAnsChoices[1] = "liquidity ratio";
arrAnsChoices[2] = "capital and surplus ratio";
arrAnsChoices[3] = "profitability ratio";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445710;
arrAnsIDs[1] = 445711;
arrAnsIDs[2] = 445712;
arrAnsIDs[3] = 445713;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\"><b>Leverage</b> ratios compare the amount of an insurer’s obligations with the insurer’s ability to meet those obligations.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\"><b>Liquidity ratios</b> measure a company’s ability to meet its maturing short-term obligations. The basic liquidity ratio contains assets in the numerator and liabilities in the denominator.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Insurers measure their financial strength using capital and surplus ratios. Capital and surplus ratios, also called capitalization ratios, are financial ratios used to express the relationship between an insurer’s capital and surplus and its liabilities: Capital and Surplus ÷ Total Liabilities. In general, the higher the value of capital and surplus ratios, the stronger the insurer’s financial position.</p><p class=\"explanations\">One drawback of the basic capital and surplus ratio is that it is based on unweighted values, which result in unweighted ratios. To account for different risk levels, financial analysts typically apply weighted values. One example of a weighted ratio is the risk-based capital (RBC) ratio.</p><p class=\"explanations\"><b>Learning Objective: 11C. Distinguish among common financial ratios that fall into each of these categories: liquidity, operating performance, leverage, capital and surplus adequacy, and profitability.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\"><b>Profitability ratios</b> measure how efficiently a company uses its assets and equity to generate net income or a net gain from operations. The basic profitability ratio consists of net income or a gain from operations in the numerator, divided by the assets invested or equity used to earn that net income or gain in the denominator.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_096'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_097';
objQuestion.questionID = 110283;
objQuestion.item = 'LOMA_361_PPQ2019_097';
objQuestion.primaryLO = '11A';
objQuestion.textref = 'c. 11, pp. 4-6, 7, 26';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '11A';
arrLOs[1] = '11C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Earnest Life Insurance Company conducted financial ratio analysis over a five-year period and compared its ratio results to the average results for Earnest’s top five competitors over the same five-year period. The following information is a summary of those results:</p><table class=\"tbexam\" align=\"center\"><tr><td style=\"vertical-align: bottom; text-align: left; background-color: #DCDCDC;\"><b>Ratio</b></td><td style=\"vertical-align: bottom; text-align: left; background-color: #DCDCDC;\"><b>Year 1</b></td><td style=\"vertical-align: bottom; text-align: left; background-color: #DCDCDC;\"><b>Year 2</b></td><td style=\"vertical-align: bottom; text-align: left; background-color: #DCDCDC;\"><b>Year 3</b></td><td style=\"vertical-align: bottom; text-align: left; background-color: #DCDCDC;\"><b>Year 4</b></td><td style=\"vertical-align: bottom; text-align: left; background-color: #DCDCDC;\"><b>Year 5</b></td><td style=\"vertical-align: middle; text-align: left; background-color: #DCDCDC;\"><b>Average for<br />Top Five<br />Competitors</b></td></tr><tr><td style=\"vertical-align: middle; text-align: left;\">Current Ratio</td><td style=\"vertical-align: middle; text-align: left;\">1.90</td><td style=\"vertical-align: middle; text-align: left;\">2.10</td><td style=\"vertical-align: middle; text-align: left;\">1.50</td><td style=\"vertical-align: middle; text-align: left;\">1.00</td><td style=\"vertical-align: middle; text-align: left;\">0.88</td><td style=\"vertical-align: middle; text-align: left;\">2.00</td></tr></table><p class=\"stem\">One action that Earnest could take to increase its current ratio, all other factors remaining equal, is to</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "sell some of its long-term invested assets and use the money to invest in shorter-term, more liquid assets";
arrAnsChoices[1] = "sell some of its shorter-term, more liquid assets and use the money to invest in long-term invested assets to earn a return";
arrAnsChoices[2] = "borrow shorter-term funds and use the money to invest in long-term invested assets to earn a return";
arrAnsChoices[3] = "maintain the existing balance between its shorter-term, more liquid assets and long-term invested assets";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445714;
arrAnsIDs[1] = 445715;
arrAnsIDs[2] = 445716;
arrAnsIDs[3] = 445717;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The current ratio indicates an insurer’s ability to satisfy short-term obligations without having to sell long-term investments or borrow money: Current Assets ÷ Current Liabilities.</p><p class=\"explanations\">An increase in the value of the current ratio results when there is (1) an increase in the value of current assets in the numerator or (2) a decrease in the value of current liabilities in the denominator. In this situation, Earnest’s selling long-term invested assets and using the money to invest in shorter-term, more liquid assets would increase current assets, and, therefore, increase the current ratio.</p><p class=\"explanations\"><b>Learning Objectives: (1) 11A. Interpret the results of various financial ratios; (2) 11C. Distinguish among common financial ratios that fall into each of these categories: liquidity, operating performance, leverage, capital and surplus adequacy, and profitability.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The current ratio indicates an insurer’s ability to satisfy short-term obligations without having to sell long-term investments or borrow money: Current Assets ÷ Current Liabilities.</p><p class=\"explanations\">An increase in the value of the current ratio results when there is (1) an increase in the value of current assets in the numerator or (2) a decrease in the value of current liabilities in the denominator. In this situation, Earnest’s selling shorter-term funds would decrease the value of its current assets. The result is a <b>decrease</b> in the value of the current ratio.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The current ratio indicates an insurer’s ability to satisfy short-term obligations without having to sell long-term investments or borrow money: Current Assets ÷ Current Liabilities.</p><p class=\"explanations\">An increase in the value of the current ratio results when there is (1) an increase in the value of current assets in the numerator or (2) a decrease in the value of current liabilities in the denominator. In this situation, Earnest’s borrowing shorter-term funds would increase the value of its current liabilities. The result is a <b>decrease</b> in the value of the current ratio.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The current ratio indicates an insurer’s ability to satisfy short-term obligations without having to sell long-term investments or borrow money: Current Assets ÷ Current Liabilities.</p><p class=\"explanations\">An increase in the value of the current ratio results when there is (1) an increase in the value of current assets in the numerator or (2) a decrease in the value of current liabilities in the denominator. In this situation, Earnest’s maintaining the existing balance between shorter-term, more liquid assets and long-term invested assets would neither increase the value of its current assets nor decrease the value or its current liabilities. The result is <b>no</b> increase in the value of the current ratio.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_097'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_098';
objQuestion.questionID = 110284;
objQuestion.item = 'LOMA_361_PPQ2019_098';
objQuestion.primaryLO = '11C';
objQuestion.textref = 'c. 11, pp. 10-11, 15-16, 26-27';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '11C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statement(s) can correctly be made about this chart, which shows a sample of the five-year ratio results for the Macro Life Insurance Company, a U.S. stock insurance company:</p><table class=\"tbexam\" align=\"center\"><tr><td style=\"vertical-align: top; text-align: left; background-color: #DCDCDC;\"><b>Five-Year Ratio Results<br />for the Macro Life <br />Insurance Company</b></td><td style=\"vertical-align: bottom; text-align: center; background-color: #DCDCDC;\"><b>2014</b></td><td style=\"vertical-align: bottom; text-align: center; background-color: #DCDCDC;\"><b>2015</b></td><td style=\"vertical-align: bottom; text-align: center; background-color: #DCDCDC;\"><b>2016</b></td><td style=\"vertical-align: bottom; text-align: center; background-color: #DCDCDC;\"><b>2017</b></td><td style=\"vertical-align: bottom; text-align: center; background-color: #DCDCDC;\"><b>2018</b></td><td style=\"vertical-align: bottom; text-align: center; background-color: #DCDCDC;\"><b>Average for<br />Top Five<br />Competitors</b></td></tr><tr><td style=\"vertical-align: top; text-align: left;\"><b>Insurance Leverage Ratio</b></td><td style=\"vertical-align: top; text-align: center;\">5.00</td><td style=\"vertical-align: top; text-align: center;\">5.20</td><td style=\"vertical-align: top; text-align: center;\">5.30</td><td style=\"vertical-align: top; text-align: center;\">5.10</td><td style=\"vertical-align: top; text-align: center;\">5.10</td><td style=\"vertical-align: top; text-align: center;\">4.00</td></tr><tr><td style=\"vertical-align: top; text-align: left;\"><b>Debt-to-Surplus Ratio</b></td><td style=\"vertical-align: top; text-align: center;\">4.00</td><td style=\"vertical-align: top; text-align: center;\">4.20</td><td style=\"vertical-align: top; text-align: center;\">4.30</td><td style=\"vertical-align: top; text-align: center;\">4.25</td><td style=\"vertical-align: top; text-align: center;\">4.20</td><td style=\"vertical-align: top; text-align: center;\">5.50</td></tr><tr><td style=\"vertical-align: top; text-align: left;\"><b>Lapse and Surrender Ratio</b></td><td style=\"vertical-align: top; text-align: center;\">6.00%</td><td style=\"vertical-align: top; text-align: center;\">6.25%</td><td style=\"vertical-align: top; text-align: center;\">6.50%</td><td style=\"vertical-align: top; text-align: center;\">6.50%</td><td style=\"vertical-align: top; text-align: center;\">6.25%</td><td style=\"vertical-align: top; text-align: center;\">5.50%</td></tr><tr><td style=\"vertical-align: top; text-align: left;\"><B>ROA</B></td><td style=\"vertical-align: top; text-align: center;\">0.90%</td><td style=\"vertical-align: top; text-align: center;\">0.80%</td><td style=\"vertical-align: top; text-align: center;\">0.75%</td><td style=\"vertical-align: top; text-align: center;\">0.80%</td><td style=\"vertical-align: top; text-align: center;\">0.80%</td><td style=\"vertical-align: top; text-align: center;\">0.80%</td></tr></table><ol type=\"A\" class=\"combo\"><li>Macro’s insurance leverage ratio results are more desirable than the average results of its top five competitors, because a high result is generally more desirable than a low result for this ratio.</li><li>Macro’s debt-to-surplus ratio results are less desirable than the average results of its top five competitors, because a high result is generally more desirable than a low result for this ratio.</li><li>Macro most likely would improve its lapse and surrender ratio results by focusing on decreasing the numerator of this ratio.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A, B, and C";
arrAnsChoices[1] = "A and B only";
arrAnsChoices[2] = "A and C only";
arrAnsChoices[3] = "B only";
arrAnsChoices[4] = "C only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445718;
arrAnsIDs[1] = 445719;
arrAnsIDs[2] = 445720;
arrAnsIDs[3] = 445721;
arrAnsIDs[4] = 445722;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 5;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Both Statement A and Statement B are incorrect.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement C is correct; however, Statement B is incorrect.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Statement B is incorrect. The debt-to-surplus ratio measures the relationship between an insurer’s total liabilities and its surplus: Debt-to-Surplus = Total Liabilities ÷ Surplus. This ratio is especially important for mutual insurers and fraternal insurers, because they have no capital accounts but do have surplus. In general, insurers aim to have a low debt-to-surplus ratio, such as between 4.0 and 6.5.</p>";
arrAnswerFeedback[4] = "<p class=\"explanations\">Statement A is incorrect. The insurance leverage ratio, also called the gross leverage ratio, compares an insurer’s contractual reserves to its capital and surplus: Insurance Leverage Ratio = Contractual Reserves ÷ Capital and Surplus. For this ratio, a low result, such as a range of 4.0 to 6.5, is generally more desirable than a high result.</p><p class=\"explanations\">Statement B is incorrect. The debt-to-surplus ratio measures the relationship between an insurer’s total liabilities and its surplus: Debt-to-Surplus = Total Liabilities ÷ Surplus. This ratio is especially important for mutual insurers and fraternal insurers, because they have no capital accounts but do have surplus. In general, insurers aim to have a low debt-to-surplus ratio, such as between 4.0 and 6.5.</p><p class=\"explanations\">Statement C is correct. The lapse and surrender ratio compares the number of life insurance policies or annuity contracts that either lapsed or were surrendered during the current year to the average number of policies in force during the current year: Lapse and Surrender Ratio = # of Policies Lapse or Surrendered during Current Year ÷ Average Number of Policies in Force during Current Year. Lapse and surrender ratios can vary from product to product. Generally, an insurer wants its lapse and surrender ratios to match those specified by actuaries when they priced the product. In recent years, the industry average for this ratio has been between 5 and 6 percent.</p><p class=\"explanations\"><b>Learning Objectives: (1) 11A. Interpret the results of various financial ratios; (2) 11C. Distinguish among common financial ratios that fall into each of these categories: liquidity, operating performance, leverage, capital and surplus adequacy, and profitability.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_098'] = objQuestion;



arrMinicases[3] = "<p class=\"caseinfo\">Use the following information extracted from the year-end financial statements of the Vista Life Insurance Company to answer questions 2 through 4.</p><table class=\"tbplain\" cellspacing=\"0\" align=\"center\"><tr><td style=\"vertical-align: top; text-align: left;\"><b>Balance Sheet</b></td><td style=\"vertical-align: top; text-align: right; background-color: transparent; border: none;\"></td></tr><tr><td style=\"vertical-align: top; text-align: left;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Assets:</td><td style=\"vertical-align: top; text-align: right; background-color: transparent; border: none;\"></td></tr><tr><td style=\"vertical-align: top; text-align: left;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cash and other liquid assets</td><td style=\"vertical-align: top; text-align: right;\">$&nbsp;&nbsp;&nbsp;435,000</td></tr><tr><td style=\"vertical-align: top; text-align: left;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Average invested assets</td><td style=\"vertical-align: top; text-align: right;\"><u>&nbsp;&nbsp;&nbsp;1,725,000</u></td></tr><tr><td style=\"vertical-align: top; text-align: left;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Total assets</td><td style=\"vertical-align: top; text-align: right;\"><span style=\"border-bottom: 1px solid #000000\"><u>$2,160,000</u></span></td></tr><tr><td style=\"vertical-align: top; text-align: left;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Liabilities:</td><td style=\"vertical-align: top; text-align: right; background-color: transparent; border: none;\"></td></tr><tr><td style=\"vertical-align: top; text-align: left;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Contractual reserves</td><td style=\"vertical-align: top; text-align: right;\">$&nbsp;&nbsp;&nbsp;1,600,000</td></tr><tr><td style=\"vertical-align: top; text-align: left;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Other reserves</td><td style=\"vertical-align: top; text-align: right;\"><u>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;100,000</u></td></tr><tr><td style=\"vertical-align: top; text-align: left;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Total liabilities</td><td style=\"vertical-align: top; text-align: right;\">$&nbsp;&nbsp;&nbsp;1,700,000</td></tr><tr><td style=\"vertical-align: top; text-align: left;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Capital and Surplus</td><td style=\"vertical-align: top; text-align: right;\"><u>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;460,000</u></td></tr><tr><td style=\"vertical-align: top; text-align: left;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Total liabilities and capital and surplus</td><td style=\"vertical-align: top; text-align: right;\"><span style=\"border-bottom: 1px solid #000000\"><u>$2,160,000</u></span></td></tr><tr><td style=\"vertical-align: top; text-align: left;\"><b>Income Statement</b></td><td style=\"vertical-align: top; text-align: right; background-color: transparent; border: none;\"></td></tr><tr><td style=\"vertical-align: top; text-align: left;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Income from sales of products</td><td style=\"vertical-align: top; text-align: right;\">$1,147,500</td></tr><tr><td style=\"vertical-align: top; text-align: left;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Investment income</td><td style=\"vertical-align: top; text-align: right;\"><u>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;127,500</u></td></tr><tr><td style=\"vertical-align: top; text-align: left;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Total income</td><td style=\"vertical-align: top; text-align: right;\"><span style=\"border-bottom: 1px solid #000000\"><u>$1,275,000</u></span></td></tr></table><p class=\"caseinfo\">Last year, Vista reported $22,000 of Nonadmitted Assets and $300,000 of Surplus on its Annual Statement.</p>";


var arrlotext = new Array(); 
arrlotext['11A'] = "11A. Interpret the results of various financial ratios.";
arrlotext['11B'] = "11B. Compare and contrast operating leverage, financial leverage, positive leverage effects, and negative leverage effects.";
arrlotext['11C'] = "11C. Distinguish among common financial ratios that fall into each of these categories: liquidity, operating performance, leverage, capital and surplus adequacy, and profitability.";
