var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2019';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 361 Practice Questions, Chapter 9";
var coursename = 'LOMA 361';
var modulenumber = 2;
var title = "LOMA_361_PPQ2019_0_9";
var intNumPools = 1;
var numQ = 9;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Accounting and Financial Reporting in Life Insurance Companies, Second Edition (2019)";
arrNumChap[0] = 1;
var thisChap = '9';

objPool = new Object(); 
objPool.intSelectCount = 9;
objPool.formID = 2103;
objPool.formName = 'PPQ2019_0_9';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_361_PQ_069';
arrPoolQuestions[1] = 'LOMA_361_PQ_070';
arrPoolQuestions[2] = 'LOMA_361_PQ_071';
arrPoolQuestions[3] = 'LOMA_361_PQ_072';
arrPoolQuestions[4] = 'LOMA_361_PQ_073';
arrPoolQuestions[5] = 'LOMA_361_PQ_074';
arrPoolQuestions[6] = 'LOMA_361_PQ_075';
arrPoolQuestions[7] = 'LOMA_361_PQ_076';
arrPoolQuestions[8] = 'LOMA_361_PQ_077';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_069';
objQuestion.questionID = 110255;
objQuestion.item = 'LOMA_361_PPQ2019_069';
objQuestion.primaryLO = '9A';
objQuestion.textref = 'c. 9, pp. 3-4';
objQuestion.textbook = 0;
objQuestion.chapter = 9;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '9A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Broadway Life Insurance Company received proceeds from the issue (sale) of its common stock at par value. One balance sheet effect from Broadway’s sale of its common stock, all other factors remaining equal, is</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "a decrease in assets";
arrAnsChoices[1] = "an increase in capital";
arrAnsChoices[2] = "a decrease in liabilities";
arrAnsChoices[3] = "an increase in liabilities";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445599;
arrAnsIDs[1] = 445600;
arrAnsIDs[2] = 445601;
arrAnsIDs[3] = 445602;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A typical accounting entry to record the issue and sale of an insurer’s common stock at par value—the designated legal value assigned to each outstanding share of stock—is a debit to <i>Cash</i> and a credit to <i>Common Stock</i>. In this situation, Broadway’s sale of its common stock <b>increases</b> both its assets (cash) and owners’ equity (common stock, a capital account); Broadway’s liabilities remain unchanged.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A typical accounting entry to record the issue and sale of an insurer’s common stock at par value—the designated legal value assigned to each outstanding share of stock—is a debit to <i>Cash</i> and a credit to <i>Common Stock</i>. In this situation, Broadway’s sale of its common stock increases both its assets (cash) and owners’ equity (common stock, a capital account); Broadway’s liabilities remain unchanged.</p><p class=\"explanations\"><b>Learning Objective: 9A. Describe the major capital and surplus accounts of life insurers.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A typical accounting entry to record the issue and sale of an insurer’s common stock at par value—the designated legal value assigned to each outstanding share of stock—is a debit to <i>Cash</i> and a credit to <i>Common Stock</i>. In this situation, Broadway’s sale of its common stock increases both its assets (cash) and owners’ equity (common stock, a capital account); Broadway’s liabilities remain <b>unchanged</b>.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A typical accounting entry to record the issue and sale of an insurer’s common stock at par value—the designated legal value assigned to each outstanding share of stock—is a debit to <i>Cash</i> and a credit to <i>Common Stock</i>. In this situation, Broadway’s sale of its common stock increases both its assets (cash) and owners’ equity (common stock, a capital account); Broadway’s liabilities remain <b>unchanged</b>.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_069'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_070';
objQuestion.questionID = 110256;
objQuestion.item = 'LOMA_361_PPQ2019_070';
objQuestion.primaryLO = '9A';
objQuestion.textref = 'c. 9, p. 5';
objQuestion.textbook = 0;
objQuestion.chapter = 9;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '9A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Under U.S. GAAP, a typical accounting entry that an insurer would make to record the issue (sale) of the insurer’s common stock at greater than par value is</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "<table cols=\"3\" cellspacing=\"0\" cellpadding=\"1\" style=\"width: 90%; margin-top:0em; margin-bottom:0em\"><tr><td class=\"acctentry_d\"><i>Common Stock</i></td><td class=\"debit_credit\">xxx</td><td class=\"debit_credit\">&nbsp;</td></tr><tr><td class=\"acctentry_c\"><i>Cash</i></td><td class=\"debit_credit\">&nbsp;</td><td class=\"debit_credit\">xxx</td></tr></table>";
arrAnsChoices[1] = "<table cols=\"3\" cellspacing=\"0\" cellpadding=\"1\" style=\"width: 90%; margin-top:0em; margin-bottom:0em\"><tr><td class=\"acctentry_d\"><i>Cash</i></td><td class=\"debit_credit\">xxx</td><td class=\"debit_credit\">&nbsp;</td></tr><tr><td class=\"acctentry_c\"><i>Common Stock</i></td><td class=\"debit_credit\">&nbsp;</td><td class=\"debit_credit\">xxx</td></tr></table>";
arrAnsChoices[2] = "<table cols=\"3\" cellspacing=\"0\" cellpadding=\"1\" style=\"width: 90%; margin-top:0em; margin-bottom:0em\"><tr><td class=\"acctentry_d\"><i>Common Stock</i></td><td class=\"debit_credit\">x</td><td class=\"debit_credit\">&nbsp;</td></tr><tr><td class=\"acctentry_d\"><i>Additional Paid-In Capital</i></td><td class=\"debit_credit\">xx</td><td class=\"debit_credit\">&nbsp;</td></tr><tr><td class=\"acctentry_c\"><i>Cash</i></td><td class=\"debit_credit\">&nbsp;</td><td class=\"debit_credit\">xxx</td></tr></table>";
arrAnsChoices[3] = "<table cols=\"3\" cellspacing=\"0\" cellpadding=\"1\" style=\"width: 90%; margin-top:0em; margin-bottom:0em\"><tr><td class=\"acctentry_d\"><i>Cash</i></td><td class=\"debit_credit\">xxx</td><td class=\"debit_credit\">&nbsp;</td></tr><tr><td class=\"acctentry_c\"><i>Common Stock</i></td><td class=\"debit_credit\">&nbsp;</td><td class=\"debit_credit\">x</td></tr><tr><td class=\"acctentry_c\"><i>Additional Paid-In Capital</i></td><td class=\"debit_credit\">&nbsp;</td><td class=\"debit_credit\">xx</td></tr></table>";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445603;
arrAnsIDs[1] = 445604;
arrAnsIDs[2] = 445605;
arrAnsIDs[3] = 445606;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">This accounting entry records an insurer’s <b>purchase of another company’s common stock at par value</b> for investment purposes.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">This accounting entry records an insurer’s <b>sale of another company’s common stock at par value</b> that the insurer originally purchased for investment purposes.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Under U.S. GAAP, a typical accounting entry to record the sale of an insurer’s common stock at greater than par value is a <b>debit</b> to <i>Cash</i>, a <b>credit</b> to <i>Common Stock</i>, and a <b>credit</b> to <i>Additional Paid-In Capital</i>.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A typical accounting entry to record the sale of an insurer’s common stock at par value is a debit to <i>Cash</i> and a credit to <i>Common Stock</i>. If the selling price of the stock issue is greater than the stock’s par value, insurers in the United States also credit <i>Additional Paid-In Capital</i> (U.S. GAAP) or <i>Gross Paid-In and Contributed Surplus </i>(U.S. SAP) for the excess of the selling price over the par value.</p><p class=\"explanations\"><b>Learning Objective: 9A. Describe the major capital and surplus accounts of life insurers.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_070'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_071';
objQuestion.questionID = 110257;
objQuestion.item = 'LOMA_361_PPQ2019_071';
objQuestion.primaryLO = '9A';
objQuestion.textref = 'c. 9, pp. 5, 10';
objQuestion.textbook = 0;
objQuestion.chapter = 9;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '9A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Several key capital accounts and surplus accounts differ under U.S. GAAP and U.S. SAP. Select the answer choice that correctly identifies an example of a capital and surplus account under U.S. GAAP and U.S. SAP.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[-1] = "<U>U.S. GAAP</U></div><div class=\"anshead\"><U>U.S. SAP</U>";
arrAnsChoices[0] = "<i>Additional Paid-In Capital</i></div><div class=\"anscell\" onclick=\"recordAns(1);\"><i>Retained Earnings</i>";
arrAnsChoices[1] = "<i>Additional Paid-In Capital</i></div><div class=\"anscell\" onclick=\"recordAns(2);\"><i>Unassigned Surplus</i>";
arrAnsChoices[2] = "<i>Special Surplus</i></div><div class=\"anscell\" onclick=\"recordAns(3);\"><i>Additional Paid-In Capital</i>";
arrAnsChoices[3] = "<i>Special Surplus</i></div><div class=\"anscell\" onclick=\"recordAns(4);\"><i>Gross Paid-In and Contributed Surplus</i>";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445608;
arrAnsIDs[1] = 445609;
arrAnsIDs[2] = 445610;
arrAnsIDs[3] = 445611;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Both <i>Additional Paid-In Capital</i> and <i>Retained Earnings</i> are <B>U.S. GAAP</B> accounts.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">An insurer’s typical capital accounts under U.S. GAAP include <i>Common Stock</i>, <i>Preferred Stock</i>, <i>Additional Paid-in Capital</i>, <i>Retained Earnings</i>, <i>Accumulated Other Comprehensive Income</i>, and <i>Treasury Stock</i>. Stock insurers in the United States also have statutory capital accounts, such as <i>Common Stock</i>, <i>Preferred Stock</i>, <i>Gross Paid-In and Contributed Surplus</i>, and <i>Treasury Stock</i>. Two important statutory surplus accounts for insurers are <i>Special Surplus</i> and <i>Unassigned Surplus</i>.</p><p class=\"explanations\">Several differently-named U.S. GAAP accounts are similar to SAP accounts. For example, if the selling price of an insurer’s stock issue is greater than the stock’s par value, insurers in the United States also credit <i>Additional Paid-In Capital</i> (U.S. GAAP) or <i>Gross Paid-In and Contributed Surplus </i>(SAP) for the excess of the selling price over the par value. Also, the <i>Unassigned Surplus</i> account under statutory accounting is similar to the <i>Retained Earnings</i> account under U.S. GAAP in that both accounts represent the accumulation of income not paid out in dividends.</p><p class=\"explanations\"><b>Learning Objective: 9A. Describe the major capital and surplus accounts of life insurers.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\"><i>Special Surplus</i> is a <B>U.S. SAP</B> account, and <i>Additional Paid-In Capital</i> is a <B>U.S. GAAP </B>account.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Both <i>Gross Paid-In and Contributed Surplus</i> and <i>Special Surplus </i>are <B>U.S. SAP</B> accounts.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_071'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_072';
objQuestion.questionID = 110258;
objQuestion.item = 'LOMA_361_PPQ2019_072';
objQuestion.primaryLO = '9A';
objQuestion.textref = 'c. 9, pp. 6-7';
objQuestion.textbook = 0;
objQuestion.chapter = 9;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '9A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Under U.S. GAAP, increases in the <i>Treasury Stock </i>account <b>(decrease / increase) </b>an insurer’s capital because <i>Treasury Stock </i>is a type of contra equity account. The companion account to <i>Treasury Stock </i>is <b>(<i>Common Stock </i>/ <i>Retained Earnings</i>)</b>.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "decrease / <i>Common Stock</i>";
arrAnsChoices[1] = "decrease / <i>Retained Earnings</i>";
arrAnsChoices[2] = "increase / <i>Common Stock</i>";
arrAnsChoices[3] = "increase / <i>Retained Earnings</i>";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445612;
arrAnsIDs[1] = 445613;
arrAnsIDs[2] = 445614;
arrAnsIDs[3] = 445615;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\"><i>Treasury Stock</i> is a contra equity account, because its companion account—<i>Common Stock</i>—is an owners’ equity account. Because amounts in a contra account typically decrease the amount in the companion account, under U.S. GAAP, increases in the amount in <i>Treasury Stock</i> decrease the amount in <i>Common Stock</i>, thus decreasing an insurer’s capital.</p><p class=\"explanations\">Under statutory accounting, the purchase of treasury stock reduces an insurer’s total surplus. For this reason, an insurer typically must obtain regulatory approval to purchase treasury stock. On the Annual Statement, an insurer reports treasury stock at the bottom of the <i>Liabilities, Surplus and Other Funds</i> page, in the special section on capital and surplus.</p><p class=\"explanations\"><b>Learning Objective: 9A. Describe the major capital and surplus accounts of life insurers.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that, under U.S. GAAP, increases in the amount in <i>Treasury Stock </i>decrease an insurer’s total capital. However, the companion account to <i>Treasury Stock </i>is <b>not</b> <i>Retained Earnings</i>, which, under GAAP, represents the net income that an insurance company holds to reinvest in the company instead of paying the money out in dividends to its stockholders.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that the companion account to <i>Treasury Stock </i>is <i>Common Stock</i>. However, under GAAP, increases in the amount in <i>Treasury Stock</i> <b>decrease </b>an insurer’s total capital.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Under GAAP, increases in the amount in <i>Treasury Stock </i><b>decrease </b>an insurer’s total capital. In addition, the companion account to <i>Treasury Stock </i>is <b>not</b> <i>Retained Earnings</i>, which, under GAAP, represents the net income that an insurance company holds to reinvest in the company instead of paying the money out in dividends to its stockholders.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_072'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_073';
objQuestion.questionID = 110259;
objQuestion.item = 'LOMA_361_PPQ2019_073';
objQuestion.primaryLO = '9A';
objQuestion.textref = 'c. 9, p. 7';
objQuestion.textbook = 0;
objQuestion.chapter = 9;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '9A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Reputable Life Insurance Company recently repurchased at market price common stock that it had previously issued. Reputable does not intend to reissue this stock. In this situation, the stock that Reputable repurchased is known as</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "retired stock";
arrAnsChoices[1] = "capitalized stock";
arrAnsChoices[2] = "preferred stock";
arrAnsChoices[3] = "contra account stock";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445616;
arrAnsIDs[1] = 445617;
arrAnsIDs[2] = 445618;
arrAnsIDs[3] = 445619;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Treasury stock is stock that an insurer in the United States had previously issued (sold) and then later repurchased at its market price. Under U.S. GAAP, the basic accounting entry to record the purchase of treasury stock, when the insurer intends to retire the stock, is a debit to <i>Treasury Stock</i>, a debit to <i>Additional Paid-In Capital</i>—<i>Treasury Stock</i>, and a credit to <i>Cash</i>. In the case of retired stock, the insurer deducts the number of shares and their monetary value from the capital account.</p><p class=\"explanations\"><b>Learning Objective: 9A. Describe the major capital and surplus accounts of life insurers.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Reputable did <b>not</b> purchase capitalized stock. In the context of accounting for foreclosure costs, to capitalize means to record the costs of property taxes, for example, as an asset.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Reputable did <b>not</b> repurchase preferred stock, which is a type of stock that usually carries a stated dividend rate that is paid before any payment of common stock dividends by the same company.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Reputable did <b>not</b> repurchase contra account stock. A contra account is an account that accompanies a specified “companion” account—typically an asset account—and has a normal balance that is the opposite of the companion account.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_073'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_074';
objQuestion.questionID = 110260;
objQuestion.item = 'LOMA_361_PPQ2019_074';
objQuestion.primaryLO = '9A';
objQuestion.textref = 'c. 9, pp. 9-10';
objQuestion.textbook = 0;
objQuestion.chapter = 9;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '9A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">For this question, if answer choices (1) through (3) are all correct, select answer choice (4). Otherwise, select the one correct answer choice.</p><p class=\"stem\">For insurers in the United States, special surplus consists of the part of the insurer’s surplus that the insurer’s board of directors has set aside to</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "replace the insurer’s obligation to establish liabilities for expected occurrences";
arrAnsChoices[1] = "pay for certain extraordinary expenses";
arrAnsChoices[2] = "distribute to the insurer’s stockholders and policyowners";
arrAnsChoices[3] = "all of the above";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445620;
arrAnsIDs[1] = 445621;
arrAnsIDs[2] = 445622;
arrAnsIDs[3] = 445623;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Amounts in the <i>Special Surplus</i> account are <b>not</b> available to replace an insurer’s obligation to establish liabilities for expected occurrences.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Special surplus, also called special surplus funds, assigned surplus, appropriated surplus, earmarked surplus, or contingency reserves, consists of the part of the insurer’s surplus that the insurer’s board of directors has set aside to (1) meet unforeseen contingencies or (2) pay for certain extraordinary expenses. Amounts in the <i>Special Surplus</i> account are not available for distribution to owners, nor do they replace an insurer’s obligation to establish liabilities for expected occurrences.</p><p class=\"explanations\">Unassigned surplus, also called unassigned surplus funds, divisible surplus, or free surplus, is the total amount of undistributed and unapportioned surplus remaining in the insurance company since the company began operations. Unassigned surplus is available to meet any contingency that arises, including new business, outstanding debt, or the purchase of treasury stock or retired stock. The <i>Unassigned Surplus</i> account under SAP is similar to the <i>Retained Earnings</i> account under U.S. GAAP.</p><p class=\"explanations\"><b>Learning Objective: 9A. Describe the major capital and surplus accounts of life insurers.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Amounts in the <i>Special Surplus</i> account are <b>not</b> available for distribution to stockowners or policyowners.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these answer choices is incorrect.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_074'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_075';
objQuestion.questionID = 110261;
objQuestion.item = 'LOMA_361_PPQ2019_075';
objQuestion.primaryLO = '9B';
objQuestion.textref = 'c. 9, p. 12';
objQuestion.textbook = 0;
objQuestion.chapter = 9;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '9B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The statements below describe financial transactions of insurers. Select the answer choice that describes a transaction that represents an internal source of funds for capital and surplus.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "The Abacus Life Insurance Company ceded insurance risk to a reinsurer, which established reserves for the reinsured portion of the risk.";
arrAnsChoices[1] = "The Basil Life Insurance Company repaid interest and principal on surplus notes.";
arrAnsChoices[2] = "The Cerulean Life Insurance Company experienced net income from a net gain from operations.";
arrAnsChoices[3] = "The Daylight Life Insurance Company strengthened its reserves.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445624;
arrAnsIDs[1] = 445625;
arrAnsIDs[2] = 445626;
arrAnsIDs[3] = 445627;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Under the terms of some types of reinsurance arrangements, the reinsurer assumes some of the direct writer’s liability for benefit payments and agrees to establish reserves for the reinsured portion of the risk. Because this use of reinsurance allows a direct writer to establish a lower amount of contractual reserves than it otherwise would, the direct writer’s surplus is higher than it would have been without the reinsurance. In this situation, Abacus is the direct writer, and this use of reinsurance is an <b>external source of funds</b> for capital and surplus.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The effect of repaying interest and principal on surplus notes is a decrease in assets (<i>Cash</i>) and a decrease in owners’ equity (<i>Surplus Notes</i>) under U.S. statutory accounting or liabilities (<i>Surplus Notes</i>) under U.S. GAAP. Repaying surplus notes is an <b>external use of funds</b> for capital and surplus.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Internal sources of funds for capital and surplus, which increase an insurer’s capital and surplus, result from financial transactions that originate in the insurer’s core business operations, including sales of life insurance policies and annuity contracts. Typical internal sources of funds for life insurers include net income (gains from core insurance operations and gains from the sale of invested assets), increases in admitted assets (U.S. SAP), and reserve destrengthening.</p><p class=\"explanations\"><b>Learning Objective: 9B. List and describe several internal sources and uses of funds for an insurer’s capital and surplus.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Generally, an inverse relationship exists between changes in an insurer’s contractual reserves and changes in its surplus. Therefore, in general, an increase in the insurer’s contractual reserves decreases the insurer’s surplus, and an increase in an insurer’s contractual reserves decreases surplus. In this situation, Daylight strengthened its reserves. Because reserve strengthening decreases the insurer’s capital and surplus, it is an <b>internal use of funds</b> for capital and surplus.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_075'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_076';
objQuestion.questionID = 110262;
objQuestion.item = 'LOMA_361_PPQ2019_076';
objQuestion.primaryLO = '9B';
objQuestion.textref = 'c. 9, pp. 12-13';
objQuestion.textbook = 0;
objQuestion.chapter = 9;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '9B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Insurers have both internal uses of funds and external uses of funds for capital and surplus. One example of an <i>internal use</i> <i>of funds</i> for capital and surplus is a financial transaction in which an insurer reported</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "a decrease in admitted assets";
arrAnsChoices[1] = "a net gain from the sale of an invested asset";
arrAnsChoices[2] = "the retirement of its own stock";
arrAnsChoices[3] = "a gain on the sale of in-force business";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445628;
arrAnsIDs[1] = 445629;
arrAnsIDs[2] = 445630;
arrAnsIDs[3] = 445631;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Typical internal uses of funds for an insurer include a net loss from operations or a net loss from the sale of an invested asset, a decrease in admitted assets (U.S. SAP), and reserve strengthening. For a given reporting period, an insurer accounts for the total change in its nonadmitted assets as either a net increase or a net decrease. A net increase in nonadmitted assets decreases the insurer’s capital and surplus; a net decrease in nonadmitted assets increases the insurer’s capital and surplus.</p><p class=\"explanations\"><b>Learning Objective: 9B. List and describe several internal sources and uses of funds for an insurer’s capital and surplus.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A net gain from the sale of an invested asset is an <b>internal source of funds</b> that results in an increase in an insurer’s capital and surplus.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The insurer’s retirement of its own stock is an <b>external use of funds</b> that results in a decrease in the insurer’s capital and surplus.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A gain on the sale of in-force business is an <b>external source of funds</b> that results in an increase in an insurer’s capital and surplus.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_076'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_077';
objQuestion.questionID = 110263;
objQuestion.item = 'LOMA_361_PPQ2019_077';
objQuestion.primaryLO = '9C';
objQuestion.textref = 'c. 9, pp. 14-15';
objQuestion.textbook = 0;
objQuestion.chapter = 9;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '9C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements describe financial transactions of insurers:</p><ul class=\"examul\"><li>The Quail Life Insurance Company purchased in-force business from another insurer.</li><li>The Robin Life Insurance Company assumed part of the risk in a reinsurance transaction.</li><li>The Swan Life Insurance Company demutualized and issued common stock to investors.</li><li>The Tanager Life Insurance Company earned profits from selling life insurance policies and annuity contracts to its customers.</li></ul><p class=\"stem\">The insurers that most likely experienced a <i>decrease</i> in capital and surplus that resulted from <i>external uses</i> <i>of funds</i> for capital and surplus included</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Quail, Robin, Swan, and Tanager";
arrAnsChoices[1] = "Quail, Robin, and Swan only";
arrAnsChoices[2] = "Quail and Robin only";
arrAnsChoices[3] = "Swan and Tanager only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445632;
arrAnsIDs[1] = 445633;
arrAnsIDs[2] = 445634;
arrAnsIDs[3] = 445635;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these insurers did <b>not</b> experience a decrease in capital and surplus from an external use of funds for capital and surplus.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that Quail and Robin experienced a decrease in capital and surplus from an external use of funds. However, Swan experienced an <b>increase</b> in capital and surplus from an <b>external source of funds</b>.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Some typical external sources and uses of funds for life insurers include ceding or assuming reinsurance, selling or purchasing in-force business, issuing and retiring stock, issuing and repaying surplus notes, and changing corporate form.</p><p class=\"explanations\">External uses of funds for capital and surplus decrease an insurer’s capital and surplus. Quail’s and Robin’s transactions occurred outside core insurance operations and decreased capital and surplus.</p><p class=\"explanations\">Although Swan’s transaction was external, it is a source of funds because the result was an increase in capital and surplus. Tanager’s transaction also resulted in an increase in capital and surplus. However, Tanager’s transaction is an internal source of funds for capital and surplus.</p><p class=\"explanations\"><b>Learning Objective: 9C. List and describe several external sources and uses of funds for an insurer’s capital and surplus.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Swan experienced an <b>increase</b> in capital and surplus from an <b>external source of funds</b>. In addition, Tanager experienced an in <b>increase</b> in capital and surplus from an <b>internal source of funds</b>.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_077'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['9A'] = "9A. Describe the major capital and surplus accounts of life insurers.";
arrlotext['9B'] = "9B. List and describe several internal sources and uses of funds for an insurer’s capital and surplus.";
arrlotext['9C'] = "9C. List and describe several external sources and uses of funds for an insurer’s capital and surplus.";
