var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2020';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 311 Practice Questions, Chapter 7";
var coursename = 'LOMA 311';
var modulenumber = 3;
var title = "LOMA_311_PPQ2020_0_7";
var intNumPools = 1;
var numQ = 17;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Business Law for Insurance Professionals (2020)";
arrNumChap[0] = 1;
var thisChap = '7';

objPool = new Object(); 
objPool.intSelectCount = 17;
objPool.formID = 2380;
objPool.formName = 'PPQ2020_0_7';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_311_PQ_086';
arrPoolQuestions[1] = 'LOMA_311_PQ_087';
arrPoolQuestions[2] = 'LOMA_311_PQ_088';
arrPoolQuestions[3] = 'LOMA_311_PQ_089';
arrPoolQuestions[4] = 'LOMA_311_PQ_090';
arrPoolQuestions[5] = 'LOMA_311_PQ_091';
arrPoolQuestions[6] = 'LOMA_311_PQ_092';
arrPoolQuestions[7] = 'LOMA_311_PQ_093';
arrPoolQuestions[8] = 'LOMA_311_PQ_094';
arrPoolQuestions[9] = 'LOMA_311_PQ_095';
arrPoolQuestions[10] = 'LOMA_311_PQ_096';
arrPoolQuestions[11] = 'LOMA_311_PQ_097';
arrPoolQuestions[12] = 'LOMA_311_PQ_098';
arrPoolQuestions[13] = 'LOMA_311_PQ_099';
arrPoolQuestions[14] = 'LOMA_311_PQ_100';
arrPoolQuestions[15] = 'LOMA_311_PQ_101';
arrPoolQuestions[16] = 'LOMA_311_PQ_102';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_086';
objQuestion.questionID = 117051;
objQuestion.item = 'LOMA_311_PPQ2020_086';
objQuestion.primaryLO = '7A';
objQuestion.textref = 'c. 7, pp. 3-4';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statement(s) can correctly be made about U.S. federal and state regulation of insurance companies:</p><ol type=\"A\" class=\"combo\"><li>In the United States, insurance companies are subject to dual regulation.</li><li>The federal government has the power to regulate interstate commerce.</li><li>The federal McCarran-Ferguson Act gives the states primary authority to regulate insurance as long as Congress finds such state regulation to be adequate.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A, B, and C";
arrAnsChoices[1] = "A and B only";
arrAnsChoices[2] = "A and C only";
arrAnsChoices[3] = "B and C only";
arrAnsChoices[4] = "B only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473278;
arrAnsIDs[1] = 473279;
arrAnsIDs[2] = 473280;
arrAnsIDs[3] = 473281;
arrAnsIDs[4] = 473282;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">All the statements are correct. The states and the federal government each play a role in regulating insurance. One of the powers the Constitution gives to the federal government is the power to regulate interstate commerce, which is commerce across state lines. The states, on the other hand, have the power to regulate intrastate commerce, which is commerce within a state. Because insurers typically conduct business across state lines, the federal government has authority to regulate insurance activities. According to the McCarran-Ferguson Act, the regulation of insurance by the states is in the public interest. Congress retains the right to enact insurance legislation if it decides that state regulation is inadequate or not in the public interest.  </p><p class=\"explanations\"><b>Learning Objective: 7A. Explain the preemption legal doctrine and describe the relationship between federal and state regulation in the United States.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statements A and B are correct. However, Statement C is also correct.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statements A and C are correct. However, Statement B is also correct.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Statements B and C are correct. However, Statement A is also correct.</p>";
arrAnswerFeedback[4] = "<p class=\"explanations\">Statement B is correct, but it is not the only correct response.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_086'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_087';
objQuestion.questionID = 117052;
objQuestion.item = 'LOMA_311_PPQ2020_087';
objQuestion.primaryLO = '7B';
objQuestion.textref = 'c. 7, p. 5';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">State insurance laws can be classified into two broad types of laws: solvency laws and market conduct laws. Select the answer choice that correctly identifies an area of insurance company operations that is regulated by solvency laws and an area of insurance company operations that is regulated by market conduct laws.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[-1] = "<u>Solvency laws</u></div><div class=\"anshead\"><u>Market conduct laws</u>";
arrAnsChoices[0] = "policy reserves</div><div class=\"anscell\" onclick=\"recordAns(1);\">claims";
arrAnsChoices[1] = "policy reserves</div><div class=\"anscell\" onclick=\"recordAns(2);\">policy design";
arrAnsChoices[2] = "underwriting</div><div class=\"anscell\" onclick=\"recordAns(3);\">claims";
arrAnsChoices[3] = "underwriting</div><div class=\"anscell\" onclick=\"recordAns(4);\">advertising";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473284;
arrAnsIDs[1] = 473285;
arrAnsIDs[2] = 473286;
arrAnsIDs[3] = 473287;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Solvency laws are enacted to make sure that insurers are financially able to meet their debts and to pay policy benefits when they come due. Solvency laws regulate an insurer’s capitalization, policy design, and policy reserves. Market conduct laws are enacted to make sure that insurers conduct businesses fairly and ethically. Market conduct laws set mandated benefits and regulate most of the nonfinancial operations of insurers, such as management, marketing, sales, underwriting, policyowner service, complaint handling, and claims.</p><p class=\"explanations\"><b>Learning Objective: 7B. Classify an insurance law as either a solvency law or a market conduct law.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that solvency laws regulate policy reserves. However, solvency laws, <b>not</b> market conduct laws, regulate an insurer’s policy design.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that market conduct laws regulate claims. However, market conduct laws, <b>not</b> solvency laws, regulate underwriting.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that market conduct laws regulate advertising. However, market conduct laws, <b>not</b> solvency laws, regulate underwriting.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_087'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_088';
objQuestion.questionID = 117053;
objQuestion.item = 'LOMA_311_PPQ2020_088';
objQuestion.primaryLO = '7B';
objQuestion.textref = 'c. 7, pp. 5, 14-15';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7B';
arrLOs[1] = '7D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statement(s) can correctly be made about financial condition examinations of insurers:</p><ol type=\"A\" class=\"combo\"><li>The NAIC Model Law on Examinations requires each insurer domiciled in the state to undergo a financial condition examination on an annual basis.</li><li>The NAIC Model Law on Examinations requires that the examination report be filed with the state insurance department no later than 30 days after completion of the examination.</li><li>A financial condition examination is designed to identify and monitor threats to an insurer’s solvency.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A, B, and C";
arrAnsChoices[1] = "A and B only";
arrAnsChoices[2] = "B and C only";
arrAnsChoices[3] = "C only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473288;
arrAnsIDs[1] = 473289;
arrAnsIDs[2] = 473290;
arrAnsIDs[3] = 473291;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is incorrect. The NAIC Model Law on Examinations requires each insurer domiciled in the state to undergo a financial condition examination at least every<b> five years</b>.</p><p class=\"explanations\">Statement B is incorrect. The NAIC Model Law on Examinations requires that the examination report be filed with the state insurance department no later than <b>60</b> days after completion of the examination.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement C is correct. However, Statement B is incorrect. The NAIC Model Law on Examinations requires that the examination report be filed with the state insurance department no later than <b>60</b> days after completion of the examination.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Statement C is correct. Financial condition examinations may be carried out by one or more state insurance departments. States conduct two types of financial condition examinations. A full-scope examination reports on an insurer’s financial position taken as a whole. A limited-scope examination focuses on one or more specific areas of an insurer’s finances, such as its reserves or its ability to pay claims. </p><p class=\"explanations\">Statement A is incorrect. The NAIC Model Law on Examinations requires each insurer domicile in the state to undergo a financial condition examination at least every five years.</p><p class=\"explanations\">Statement B is incorrect. The NAIC Model Law on Examinations requires that the examination report be filed with the state insurance department no later than 60 days after completion of the examination.</p><p class=\"explanations\"><b>Learning Objective: (1) 7B. Classify an insurance law as either a solvency law or a market conduct law; (2) 7D. Identify and describe the tools available to state insurance regulators to monitor the solvency of insurers.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_088'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_089';
objQuestion.questionID = 117054;
objQuestion.item = 'LOMA_311_PPQ2020_089';
objQuestion.primaryLO = '7C';
objQuestion.textref = 'c. 7, pp. 6, 7, 8';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statement(s) can correctly be made about various services that the National Association of Insurance Commissioners (NAIC) provides to assist state insurance regulators:</p><ol type=\"A\" class=\"combo\"><li>The NAIC develops model insurance laws and regulations.</li><li>The NAIC maintains an Examination Tracking System that enables state insurance departments to schedule and coordinate on-site examinations of insurers.</li><li>Insurers are required to file their Annual Statements with the NAIC, and the NAIC maintains a financial database in which it stores information from the Annual Statements.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A, B, and C";
arrAnsChoices[1] = "A and B only";
arrAnsChoices[2] = "A and C only";
arrAnsChoices[3] = "B and C only";
arrAnsChoices[4] = "B only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473292;
arrAnsIDs[1] = 473293;
arrAnsIDs[2] = 473294;
arrAnsIDs[3] = 473295;
arrAnsIDs[4] = 473296;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">All the statements are correct. States respond to model laws and regulations in one of the following ways: (1) they may adopt the model exactly as written, (2) they may use the model as the basis for developing legislation or regulation, or (3) they may ignore the model. However, for a state’s insurance department to maintain accreditation with the NAIC, the department must have adequate statutory and administrative authority to regulate an insurer’s corporate and financial affairs. The NAIC provides several computerized databases to insurance department. These databases, for example, enable the departments to simplify the licensing process for insurance agents, screen insurers that apply for a certificate of authority, and exchange information about licensed insurers and insurance agents. </p><p class=\"explanations\"><b>Learning Objective: 7C. Describe the actions a state insurance department may take if it finds that an insurer is in financial difficulty or is not complying with regulatory requirements.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statements A and B are correct. However, Statement C is also correct.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statements A and C are correct. However, Statement B is also correct.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Statements B and C are correct. However, Statement A is also correct.</p>";
arrAnswerFeedback[4] = "<p class=\"explanations\">Statement B is correct, but it is not the only correct response.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_089'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_090';
objQuestion.questionID = 117055;
objQuestion.item = 'LOMA_311_PPQ2020_090';
objQuestion.primaryLO = '7C';
objQuestion.textref = 'c. 7, p. 7';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statement(s) can correctly be made about the right of state insurance departments to take actions against insurers:</p><ol type=\"A\" class=\"combo\"><li> A state insurance department may suspend or revoke an insurance company’s certificate of authority if the insurer is financially unsound or knowingly fails to comply with state laws, regulations, or an order issued by the state insurance department. </li><li>A state insurance department cannot take action against an insurer without an administrative hearing, under any circumstances. </li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473297;
arrAnsIDs[1] = 473298;
arrAnsIDs[2] = 473299;
arrAnsIDs[3] = 473300;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct. If the insurance department suspends an insurer’s certificate of authority, the insurer must cease operating. The insurance department may impose a suspension for a stated period of time or until the insurer corrects the violation. If the insurance department revokes the insurer’s certificate of authority, the certificate is no longer valid. The insurer cannot conduct business in the state until the insurance department issues a new certificate of authority. </p><p class=\"explanations\">Statement B is incorrect. The state insurance department may not take action against an insurer without an administering hearing, unless the insurer consents to the action. </p><p class=\"explanations\"><b>Learning Objective: 7C. Describe the actions a state insurance department may take if it finds that an insurer is in financial difficulty or is not complying with regulatory requirements.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is incorrect. The state insurance department may not take action against an insurer without an administering hearing, <b>unless</b> <b>the insurer consents to the action</b>.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_090'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_091';
objQuestion.questionID = 117056;
objQuestion.item = 'LOMA_311_PPQ2020_091';
objQuestion.primaryLO = '7D';
objQuestion.textref = 'c. 7, p. 12';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">An insurer’s assets are classified as admitted assets or nonadmitted assets. One example of nonadmitted assets is</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "real estate";
arrAnsChoices[1] = "a bond";
arrAnsChoices[2] = "furniture";
arrAnsChoices[3] = "a corporate stock";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473301;
arrAnsIDs[1] = 473302;
arrAnsIDs[2] = 473303;
arrAnsIDs[3] = 473304;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Real estate is an example of <b>admitted</b> assets</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A bond is an example of <b>admitted</b> assets.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The states define which assets an insurer may include on its Annual Statement. The assets that an insurer may report as statutory assets are known as admitted assets. All other assets are known as nonadmitted assets. An insurer must report nonadmitted assets, such as furniture and fixtures, separately and may not use them to support its required reserves. The admitted assets held by U.S. life and health insurers primarily consist of corporate stocks and bonds, government securities, mortgages, and real estate.</p><p class=\"explanations\"><b>Learning Objective: 7D. Identify and describe the tools available to state insurance regulators to monitor the solvency of insurers.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A corporate stock is an example of <b>admitted</b> assets.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_091'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_092';
objQuestion.questionID = 117057;
objQuestion.item = 'LOMA_311_PPQ2020_092';
objQuestion.primaryLO = '7D';
objQuestion.textref = 'c. 7, pp. 12-13';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">State insurance regulators use various tools to monitor the solvency of insurers. The following statements are about these tools. Select the answer choice containing the correct statement. </p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "The NAIC Investments of Insurers Model Act (Defined Limits Version) provides a prudent person standard that establishes statutory guidelines insurers are to follow in making investment decisions.";
arrAnsChoices[1] = "Most states require insurers to meet risk-based capital (RBC) ratio requirements.";
arrAnsChoices[2] = "The NAIC Risk Management and Own Risk Solvency Assessment Model Act requires large- and medium-size insurers, or their insurance holding companies, to conduct a self-evaluation at least every five years.";
arrAnsChoices[3] = "Enterprise risk management (ERM) programs do not include formal reporting systems for insurers to use to report the status of their risks to regulators and rating agencies.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473305;
arrAnsIDs[1] = 473306;
arrAnsIDs[2] = 473307;
arrAnsIDs[3] = 473308;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The NAIC <b>Investments of Insurers Model Act (Defined Standards </b>Version<b>)</b> provides a prudent person standard that establishes statutory guidelines insurers are to follow in making investment decisions. </p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">These RBC ratio requirements enable regulators to evaluate the adequacy of an insurer’s capital compared to the riskiness of its operations. Thus, an insurer that exposes itself to more risk must maintain more capital and surplus than an insurer that exposed itself to less risk. </p><p class=\"explanations\"><b>Learning Objective: 7D. Identify and describe the tools available to state insurance regulators to monitor the solvency of insurers.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The NAIC Risk Management and Own Risk Solvency Assessment Model Act requires large- and medium-size insurers, or their insurance holding companies, to conduct a self-evaluation <b>at least annually</b>.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Enterprise risk management (ERM) programs <b>include</b> formal reporting systems that insurers use to report the status of their risks to regulators and rating agencies.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_092'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_093';
objQuestion.questionID = 117058;
objQuestion.item = 'LOMA_311_PPQ2020_093';
objQuestion.primaryLO = '7D';
objQuestion.textref = 'c. 7, p. 16';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">If the state insurance department determines that an insurer’s financial problems are severe, the insurance department may ask a court to place the insurer in receivership. The following statement(s) can correctly be made about receiverships:</p><ol type=\"A\" class=\"combo\"><li>When an insurer is placed in receivership, the state takes control of and administers the insurer’s assets and liabilities.</li><li>In the receivership outcome known as rehabilitation, the insurer continues to exist as a corporation, and the state insurance department may try to find an investor to invest capital in the insurer if it appears that the financial condition of the insurer can be repaired.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473309;
arrAnsIDs[1] = 473310;
arrAnsIDs[2] = 473311;
arrAnsIDs[3] = 473312;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Both statements are correct. In an insurance receivership, a person acting as the receiver is responsible for formulating a plan to conserve and control the insurer’s assets and for making sure that the insurer’s obligations to customers are met to the extent possible. Impaired insurers generally are first placed into rehabilitation, which is one possible outcome of an insurance receivership. If it appears that the financial condition of the insurer can be repaired, the state insurance department may look for an investor to invest capital in the insurer. However, investors seldom are willing to participate in a rehabilitation.</p><p class=\"explanations\"><b>Learning Objective: 7D. Identify and describe the tools available to state insurance regulators to monitor the solvency of insurers.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct. However, Statement B is also correct.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is correct. However, Statement A is also correct.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_093'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_094';
objQuestion.questionID = 117059;
objQuestion.item = 'LOMA_311_PPQ2020_094';
objQuestion.primaryLO = '7E';
objQuestion.textref = 'c. 7, p. 21';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Dodd-Frank Wall Street Reform and Consumer Protection Act (Dodd-Frank) is a U.S federal law that provides oversight of the financial services industry. Dodd-Frank created a new regulatory system, including the Financial Stability Oversight Council (FSOC), the Consumer Financial Protection Bureau (CFPB), and the Federal Insurance Office (FIO). One true statement about Dodd-Frank is that the</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "law provides for the functional regulation of financial services ";
arrAnsChoices[1] = "FSOC members include federal financial regulators, state regulators, and an insurance expert ";
arrAnsChoices[2] = "CFPB has the authority to identify systemically important financial institutions (SIFIs)";
arrAnsChoices[3] = "FIO is responsible for monitoring all lines of insurance, including both life insurance and health insurance";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473313;
arrAnsIDs[1] = 473314;
arrAnsIDs[2] = 473315;
arrAnsIDs[3] = 473316;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The <b>Gramm-Leach-Bliley (GLB) Act</b>, a U.S. federal law that permits financial firms to affiliate in ways that result in a more competitive and integrated financial services industry, provides for the functional regulation of financial services.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The FSOC is an independent agency, created by Dodd-Frank, that monitors the safety and stability of the U.S. financial system, identifies systemic risks, and coordinates regulatory responses to any threats to the system. The FSOC is a collaborative body chaired by the head of the Treasury Department. It consists of voting members and nonvoting members.</p><p class=\"explanations\"><b>Learning Objectives: 7E. Give examples of how the U.S. federal government regulates the life insurance industry in the United States.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The <B>FSOC</B>, not the CFPB, has the authority to identify systemically important financial institutions (SIFIs), which are institutions—banks and nonbanks, including insurers—whose failure could potentially pose a risk to the financial system.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The Dodd-Frank Act created the FIO, an administrative agency within the Treasury Department, to monitor the U.S. insurance industry. The FIO monitors all lines of insurance <b>except</b> health insurance, some long-term care insurance, and crop insurance.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_094'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_095';
objQuestion.questionID = 117060;
objQuestion.item = 'LOMA_311_PPQ2020_095';
objQuestion.primaryLO = '7E';
objQuestion.textref = 'c. 7, p. 22';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">U.S. insurers that sell products with features that can be used to launder money must have an anti-money laundering program. Such products include</p><ol type=\"A\" class=\"combo\"><li>Individual annuities</li><li>Individual permanent life insurance</li><li>Individual products that have a cash value or an investment feature</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A, B, and C";
arrAnsChoices[1] = "A and B only";
arrAnsChoices[2] = "B and C only";
arrAnsChoices[3] = "A only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473317;
arrAnsIDs[1] = 473318;
arrAnsIDs[2] = 473319;
arrAnsIDs[3] = 473320;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">An insurer that sells any of these products must have an anti-money laundering program. The program must include (1) a compliance officer responsible for ensuring that the program is implemented effectively, (2) policies, procedures, and internal controls to prevent the insurer’s products from being used by money launderers, (3) ongoing training of appropriate persons within the company to ensure that they understand their responsibilities for implementing the program, and (4) a person or organization that does not work for the compliance office to test and monitor the program to determine whether it complies with the regulatory requirements and functions as intended. </p><p class=\"explanations\"><b>Learning Objective: 7E. Give examples of how the U.S. federal government regulates the life insurance industry in the United States.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">An insurer that sells individual annuities and individual permanent life insurance must have an anti-money laundering program. However, an insurer that sells individual products that have a cash value or an investment feature also must have an anti-money laundering program.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">An insurer that sells individual permanent life insurance and individual products that have cash value or an investment feature must have an anti-money laundering program. However, an insurer that sells individual annuities also must have an anti-money laundering program.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">An insurer that sells individual products that have cash value or an investment feature must have an anti-money laundering program. However, an insurer that sells individual annuities and individual permanent life insurance also must have an anti-money laundering program.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_095'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_096';
objQuestion.questionID = 117061;
objQuestion.item = 'LOMA_311_PPQ2020_096';
objQuestion.primaryLO = '7F';
objQuestion.textref = 'c. 7, p. 24';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Insurers place the premiums they receive for life insurance and annuities in either a general account or a separate account. The asset account that an insurer maintains for the purpose of recording assets that back the reserves for traditional life insurance and fixed annuity products is known as a (<b>general account</b> / <b>separate account</b>). Premiums for variable life insurance and variable annuity products are held in a (<b>general account</b> / <b>separate account</b>). </p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "general account / general account";
arrAnsChoices[1] = "general account / separate account";
arrAnsChoices[2] = "separate account / general account";
arrAnsChoices[3] = "separate account / separate account";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473321;
arrAnsIDs[1] = 473322;
arrAnsIDs[2] = 473323;
arrAnsIDs[3] = 473324;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that the asset account that an insurer maintains for the purpose of recording assets that back the reserves for traditional life insurance and fixed annuity products is known as a general account. However, premiums for variable life insurance and variable annuity products are held in a <b>separate account</b>.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Regardless of the investment performance of general account assets, the insurer pays the benefit amounts guaranteed by these products, and thus the insurer takes on the financial risks. To ensure they have the funds on hand to pay the contractually guaranteed benefits, insurers invest their general account assets in relatively secure investments. The assets in a separate account may be divided among various investment funds or subaccounts. Variable products do not guarantee the exact amount of benefits payable, so the policyowner, not the insurer, takes on the financial risk of the investments. </p><p class=\"explanations\"><b>Learning Objective: 7F. Identify life insurance and annuity products that qualify as securities and describe the types of regulatory requirements that federal securities laws impose on individuals and companies that issue and sell securities.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The asset account that an insurer maintains for the purpose of recording assets that back the reserves for traditional life insurance and fixed annuity products is known as a <b>general account</b>. Premiums for variable life insurance and variable annuity products are held in a <b>separate account</b>. </p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that premiums for variable life insurance and variable annuity products are held in a separate account. However, the asset account that an insurer maintains for the purpose of recording assets that back the reserves for traditional life insurance and fixed annuity products is known as a <b>general account</b>.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_096'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_097';
objQuestion.questionID = 117062;
objQuestion.item = 'LOMA_311_PPQ2020_097';
objQuestion.primaryLO = '7F';
objQuestion.textref = 'c. 7, p. 25';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Some individual variable annuity contracts are used to fund group retirement plans. With regard to federal securities laws, federal tax laws, and employee benefits laws, it generally is correct to say that individual variable annuity contracts used to fund group retirement plans are subject to</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "federal securities laws, federal tax laws, and employee benefits laws";
arrAnsChoices[1] = "federal securities laws and federal tax laws only";
arrAnsChoices[2] = "federal tax laws and employee benefits laws only";
arrAnsChoices[3] = "employee benefits laws only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473325;
arrAnsIDs[1] = 473326;
arrAnsIDs[2] = 473327;
arrAnsIDs[3] = 473328;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Individual variable annuity contracts used to fund group retirement plans are not subject to at least one of these laws.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that individual variable annuity contracts used to fund group retirement plans are subject to federal tax laws. However, individual variable annuity contracts used to fund group retirement plans are <b>exempt</b> from federal securities laws.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Individual variable annuity contracts used to fund group retirement plans are exempt from federal securities laws, but they are subject to federal tax laws and employee benefits laws, such as the Employee Retirement Income Security Act (ERISA). ERISA is a U.S. federal law designed to ensure that employee pension and welfare benefit plans meet certain minimum requirements to protect covered employees. </p><p class=\"explanations\"><b>Learning Objective: 7F. Identify life insurance and annuity products that qualify as securities and describe the types of regulatory requirements that federal securities laws impose on individuals and companies that issue and sell securities.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that individual variable annuity contracts used to fund group retirement plans are subject to employee benefits laws. However, employee benefits laws are not the only laws to which these contracts are subject.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_097'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_098';
objQuestion.questionID = 117063;
objQuestion.item = 'LOMA_311_PPQ2020_098';
objQuestion.primaryLO = '7F';
objQuestion.textref = 'c. 7, p. 27';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The separate accounts of most life insurers are registered with the Securities and Exchange Commission (SEC) as (<b>closed-end investment companies </b>/ <b>unit investment trusts</b>), which own and hold assets for the participants in variable life insurance and variable annuity contracts. Each separate account may be divided into subaccounts, and each subaccount may invest in a different (<b>open-end </b>/ <b>closed-end</b>) investment company.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "closed-end investment companies / open-end";
arrAnsChoices[1] = "closed-end investment companies / closed-end";
arrAnsChoices[2] = "unit investment trusts / open-end";
arrAnsChoices[3] = "unit investment trusts / closed-end";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473329;
arrAnsIDs[1] = 473330;
arrAnsIDs[2] = 473331;
arrAnsIDs[3] = 473332;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that each subaccount of a given separate account may be invested in a different open-end investment company. However, most insurers’ separate accounts are <b>not </b>registered with the SEC as closed-end investment companies.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Most insurers’ separate accounts are <b>not </b>registered with the SEC as closed-end investment companies. In addition, each subaccount of a given separate account is <b>not </b>invested in a closed-end investment company, but may be invested in a different <b>open-end</b> investment company.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A unit investment trust is an investment company that owns and holds assets for the participants in variable life insurance and variable annuity contracts. An open-end investment company is an investment company that establishes a portfolio of securities and issues shares in the portfolio to the public. Mutual funds are a primary type of open-end investment company.</p><p class=\"explanations\"><b>Learning Objective: 7F. Identify life insurance and annuity products that qualify as securities and describe the types of regulatory requirements that federal securities laws impose on individuals and companies that issue and sell securities.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that most insurers’ separate accounts are registered with the SEC as unit investment trusts. However, each subaccount of a given separate account is <b>not </b>invested in a different closed-end investment company, but rather may be invested in a different <b>open-end</b> investment company.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_098'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_099';
objQuestion.questionID = 117064;
objQuestion.item = 'LOMA_311_PPQ2020_099';
objQuestion.primaryLO = '7F';
objQuestion.textref = 'c. 7, pp. 27-28';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Registration requirements apply to individuals and firms that market securities, such as securities brokers and dealers. The following statement(s) can correctly be made about securities brokers and dealers:</p><ol type=\"A\" class=\"combo\"><li>A securities broker is defined as a person, corporation, or other legal entity that is engaged in the business of buying and selling securities for its own account.</li><li>A securities dealer is defined as a person, corporation, or other legal entity that is engaged in the business of buying and selling securities for the accounts of others.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473333;
arrAnsIDs[1] = 473334;
arrAnsIDs[2] = 473335;
arrAnsIDs[3] = 473336;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is incorrect. A securities broker is defined as a person, corporation, or other legal entity that is engaged in the business of buying and selling securities <b>for the</b> <b>accounts of others</b>.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is incorrect. A securities dealer is defined as a person, corporation, or other legal entity that is engaged in the business of buying and selling securities <b>for its own account</b>.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Both statements are incorrect. A securities broker is defined as a person, corporation, or other legal entity that is engaged in the business of buying and selling securities for the accounts of others. A securities dealer is defined as a person, corporation, or other legal entity that is engaged in the business of buying and selling securities for its own account. Securities brokers often operate as both brokers and dealers, and the term broker-dealer is often used to refer to individuals and firms that transact securities businesses.</p><p class=\"explanations\"><b>Learning Objective: 7F. Identify life insurance and annuity products that qualify as securities and describe the types of regulatory requirements that federal securities laws impose on individuals and companies that issue and sell securities.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_099'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_100';
objQuestion.questionID = 117065;
objQuestion.item = 'LOMA_311_PPQ2020_100';
objQuestion.primaryLO = '7F';
objQuestion.textref = 'c. 7, p. 29';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The FINRA Rules impose a number of requirements on the materials that broker-dealers and registered persons use to communicate with the public. One true statement about the FINRA Rules on public communication materials is that</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "such materials are permitted to contain promises of specific investment results";
arrAnsChoices[1] = "the FINRA rules apply to advertisements and sales literature, but correspondence is excluded from FINRA’s definition of public communication materials";
arrAnsChoices[2] = "all broker-dealers must file all such materials annually with FINRA prior to using them";
arrAnsChoices[3] = "broker-dealers must maintain a file of all such materials and must keep these materials for at least three years after every use";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473337;
arrAnsIDs[1] = 473338;
arrAnsIDs[2] = 473339;
arrAnsIDs[3] = 473340;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">According to the FINRA Rules, public communication materials must <b>not </b>contain promises of specific investment results.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The FINRA rules apply to communications that broker-dealers and registered persons use to communicate with the public, including advertisements, sales literature, <b>and</b> correspondence.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Broker-dealers must file certain public communication materials with FINRA for review. During the first year a broker-dealer is a FINRA member, the broker-dealer must submit all such materials to FINRA before use. After the first year, the broker-dealer must submit certain public communications to FINRA within 10 days of their first use.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Before advertisements and sales materials are used, a principal must review them. The principal must initial or sign such materials to indicate that approval. The broker-dealer then must maintain a file and keep materials for at least three years after every use.</p><p class=\"explanations\"><b>Learning Objective: 7F. Identify life insurance and annuity products that qualify as securities and describe the types of regulatory requirements that federal securities laws impose on individuals and companies that issue and sell securities.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_100'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_101';
objQuestion.questionID = 117066;
objQuestion.item = 'LOMA_311_PPQ2020_101';
objQuestion.primaryLO = '7F';
objQuestion.textref = 'c. 7, pp. 29, 31';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Registered members of the Financial Industry Regulatory Authority (FINRA), including broker-dealers and the registered persons affiliated with broker-dealers, must conduct business in compliance with all statutory requirements and FINRA rules. The following statement(s) can correctly be made about FINRA rules:</p><ol type=\"A\" class=\"combo\"><li>Broker-dealers must maintain a system to supervise the activities of the registered persons who work under their control.</li><li>When making an investment recommendation to a customer, a registered person must have reasonable grounds to believe the recommendation is suitable for the customer.</li><li>FINRA conducts annual compliance inspections of all broker-dealers to ensure that they comply with FINRA requirements.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A, B, and C";
arrAnsChoices[1] = "A and B only";
arrAnsChoices[2] = "A and C only";
arrAnsChoices[3] = "B only";
arrAnsChoices[4] = "C only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473341;
arrAnsIDs[1] = 473342;
arrAnsIDs[2] = 473343;
arrAnsIDs[3] = 473344;
arrAnsIDs[4] = 473345;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statements A and B are correct. The system must reasonably ensure compliance with regulatory requirements. A principal must directly supervise the activities of each registered representative. Suitability is the principle that the sale of a financial product must be consistent with a customer’s investment objectives and financial situation.</p><p class=\"explanations\">Statement C is incorrect. FINRA carries out its regulatory responsibilities by conducting periodic compliance inspections of all broker-dealers, but the <b>frequency</b> of such inspections <b>varies</b> depending on the nature of the broker-dealer’s activities. </p><p class=\"explanations\"><b>Learning Objective: 7F. Identify life insurance and annuity products that qualify as securities and describe the types of regulatory requirements that federal securities laws impose on individuals and companies that issue and sell securities.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statements A is correct. However, Statement C is incorrect. FINRA conducts periodic compliance inspections of all broker-dealers, but the <b>frequency</b> of such inspections <b>varies</b> depending on the nature of the broker-dealer’s activities.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Statement B is correct. However, it is not the only correct statement.</p>";
arrAnswerFeedback[4] = "<p class=\"explanations\">Statement C is incorrect. FINRA conducts periodic compliance inspections of all broker-dealers, but the <b>frequency</b> of such inspections <b>varies</b> depending on the nature of the broker-dealer’s activities.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_101'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_102';
objQuestion.questionID = 117067;
objQuestion.item = 'LOMA_311_PPQ2020_102';
objQuestion.primaryLO = '7G';
objQuestion.textref = 'c. 7, pp. 31-32';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Insurance regulation varies by country. Most countries (<b>impose</b> / <b>do not impose</b>) continuing minimum capital requirements. In today’s global economy, insurance has become increasingly subject to international oversight and coordination. The International Association of Insurance Supervisors (IAIS) is a (<b>voluntary</b> / <b>mandatory</b>) membership organization of insurance supervisors and regulators from more than 200 jurisdictions in nearly 140 countries.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "impose / voluntary";
arrAnsChoices[1] = "impose / mandatory";
arrAnsChoices[2] = "do not impose / voluntary";
arrAnsChoices[3] = "do not impose / mandatory";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473346;
arrAnsIDs[1] = 473347;
arrAnsIDs[2] = 473348;
arrAnsIDs[3] = 473349;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Regulators in most countries monitor and assess the solvency of all licensed insurers on an ongoing basis. Regulators require each life insurer to file periodic financial reports which are analyzed to assess the insurer’s solvency. Most countries also impose some type of restrictions on insurers’ investments. The IAIS, a voluntary membership organization, promotes effective and globally consistent supervision of the insurance industry. The mission of the IAIS is to (1) improve regulatory supervision of the industry, (2) develop and maintain fair, safe and stable insurance markets for the protection of policyholders, and (3) support global financial stability.</p><p class=\"explanations\"><b>Learning Objective: 7G. Give examples of the types of regulatory requirements that apply to insurers around the world.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that most countries impose continuing minimum capital requirements. However, the International Association of Insurance Supervisors (IAIS) is a <b>voluntary</b> membership organization of insurance supervisors and regulators from more than 200 jurisdictions in nearly 140 countries.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that the International Association of Insurance Supervisors (IAIS) is a voluntary membership organization of insurance supervisors and regulators from more than 200 jurisdictions in nearly 140 countries. However, most countries do <b>impose</b> continuing minimum capital requirements.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Most countries <b>impose</b> continuing minimum capital requirements. The International Association of Insurance Supervisors (IAIS) is a <b>voluntary</b> membership organization of insurance supervisors and regulators from more than 200 jurisdictions in nearly 140 countries.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_102'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['7A'] = "7A. Explain the preemption legal doctrine and describe the relationship between federal and state regulation in the United States.";
arrlotext['7B'] = "7B. Classify an insurance law as either a solvency law or a market conduct law.";
arrlotext['7C'] = "7C. Describe the actions a state insurance department may take if it finds that an insurer is in financial difficulty or is not complying with regulatory requirements.";
arrlotext['7D'] = "7D. Identify and describe the tools available to state insurance regulators to monitor the solvency of insurers.";
arrlotext['7E'] = "7E. Give examples of how the U.S. federal government regulates the life insurance industry in the United States.";
arrlotext['7F'] = "7F. Identify life insurance and annuity products that qualify as securities and describe the types of regulatory requirements that federal securities laws impose on individuals and companies that issue and sell securities.";
arrlotext['7G'] = "7G. Give examples of the types of regulatory requirements that apply to insurers around the world.";
