var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2020';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 311 Practice Questions, Chapter 4";
var coursename = 'LOMA 311';
var modulenumber = 2;
var title = "LOMA_311_PPQ2020_0_4";
var intNumPools = 1;
var numQ = 15;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Business Law for Insurance Professionals (2020)";
arrNumChap[0] = 1;
var thisChap = '4';

objPool = new Object(); 
objPool.intSelectCount = 15;
objPool.formID = 2380;
objPool.formName = 'PPQ2020_0_4';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_311_PQ_039';
arrPoolQuestions[1] = 'LOMA_311_PQ_040';
arrPoolQuestions[2] = 'LOMA_311_PQ_041';
arrPoolQuestions[3] = 'LOMA_311_PQ_042';
arrPoolQuestions[4] = 'LOMA_311_PQ_043';
arrPoolQuestions[5] = 'LOMA_311_PQ_044';
arrPoolQuestions[6] = 'LOMA_311_PQ_045';
arrPoolQuestions[7] = 'LOMA_311_PQ_046';
arrPoolQuestions[8] = 'LOMA_311_PQ_047';
arrPoolQuestions[9] = 'LOMA_311_PQ_048';
arrPoolQuestions[10] = 'LOMA_311_PQ_049';
arrPoolQuestions[11] = 'LOMA_311_PQ_050';
arrPoolQuestions[12] = 'LOMA_311_PQ_051';
arrPoolQuestions[13] = 'LOMA_311_PQ_052';
arrPoolQuestions[14] = 'LOMA_311_PQ_053';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_039';
objQuestion.questionID = 117004;
objQuestion.item = 'LOMA_311_PPQ2020_039';
objQuestion.primaryLO = '4A';
objQuestion.textref = 'c. 4, p. 4';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '4A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Bayview Corporation, which is located in State A, entered into a contract with the Decatur Company, which is located in State B. Bayview and Decatur began writing the contract in State A, but they finished writing the contract and signed it in State B. Neither party selected a jurisdiction to govern the contract. Both State A and State B follow the conflict of law rule known as the center of gravity rule. This information indicates that the contract most likely will be governed by</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "State A, because that is where the first act to create the contract occurred";
arrAnsChoices[1] = "State B, because that is where the contract was completed and signed";
arrAnsChoices[2] = "whichever state has the greatest interest in the contract";
arrAnsChoices[3] = "the federal government, because when a contract involves parties from two different states, the contract is always subject to federal jurisdiction";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473083;
arrAnsIDs[1] = 473084;
arrAnsIDs[2] = 473085;
arrAnsIDs[3] = 473086;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The center of gravity rule <b>does not</b> take into account the jurisdiction where the first act to create the contract occurred. </p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The center of gravity rule <b>does not</b> take into account the jurisdiction where the contract was completed and signed.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Many jurisdictions, including many states in the United States, follow the center of gravity rule. The center of gravity rule states that the law of the jurisdiction that has the greatest interest in the contract will govern the contract.</p><p class=\"explanations\"><b>Learning Objective: 4A. Analyze the sources of contract law and apply conflict of law rules in a given situation to determine which jurisdiction’s laws govern a contract.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">In the United States, the state governments are responsible for enacting laws that govern most contracts. When parties are in different states and have not selected a state to govern their contract, the conflict of law rules determine which state’s laws govern the contract.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_039'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_040';
objQuestion.questionID = 117005;
objQuestion.item = 'LOMA_311_PPQ2020_040';
objQuestion.primaryLO = '4B';
objQuestion.textref = 'c. 4, p. 5';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '4B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Contracts can be characterized as either formal or informal contracts and as either unilateral or bilateral contracts. The Geranium Corporation and the Meadow Leasing Company entered into a contract in which Geranium agreed to rent office space from Meadow with rent payable monthly. The contract is enforceable because Geranium and Meadow met requirements concerning the substance of the agreement, rather than requirements concerning the form of the agreement. With regard to types of contracts, it is correct to say that the contract between Geranium and Meadow is both</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "a formal contract and a bilateral contract";
arrAnsChoices[1] = "a formal contract and a unilateral contract";
arrAnsChoices[2] = "an informal contract and a bilateral contract";
arrAnsChoices[3] = "an informal contract and a unilateral contract";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473087;
arrAnsIDs[1] = 473088;
arrAnsIDs[2] = 473089;
arrAnsIDs[3] = 473090;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that the contract between Geranium and Meadow is a bilateral contract because both Geranium and Meadow made legally enforceable promises. However, a formal contract is enforceable because the parties meet certain formalities concerning the form of the agreement. In this situation, Geranium and Meadow met requirements concerning the <b>substance</b> of the agreement.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A formal contract is enforceable because the parties met certain formalities concerning the form of the agreement. In this situation, Geranium and Meadow met requirements concerning the<i> </i><b>substance</b><i> </i>of the agreement. In addition, under a unilateral contract, only one of the contracting parties makes a legally enforceable promise. In this situation, <b>both</b><i> </i>parties made legally enforceable promises—Geranium made a promise to pay monthly rent to Meadow, and Meadow promised to provide office space to Geranium.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The contract between Geranium and Meadow can correctly be described as an informal contract because Geranium and Meadow met requirements concerning the substance of the agreement, rather than requirements concerning the form of the agreement. The contract between Geranium and Meadow can also be described as a bilateral contract because both Geranium and Meadow made legally enforceable promises—Geranium to pay monthly rent to Meadow, and Meadow to provide office space to Geranium.</p><p class=\"explanations\"><b>Learning Objective: 4B. Distinguish between (1) formal and informal contracts, (2) bilateral and unilateral contracts, (3) commutative and aleatory contracts, and (4) bargaining contracts and contracts of adhesion.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that the contract between Geranium and Meadow is an informal contract because Geranium and Meadow met requirements concerning the substance of the agreement, rather than requirements concerning the form of the agreement. However, under a unilateral contract, only one of the contracting parties makes a legally enforceable promise. In this situation, <b>both</b><i> </i>parties made legally enforceable promises—Geranium made a promise to pay monthly rent to Meadow, and Meadow promised to provide office space to Meadow.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_040'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_041';
objQuestion.questionID = 117006;
objQuestion.item = 'LOMA_311_PPQ2020_041';
objQuestion.primaryLO = '4B';
objQuestion.textref = 'c. 4, p. 6';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '4B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">One type of contract is an aleatory contract. By definition, an aleatory contract is a contract in which</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "both parties specify in advance the values they will exchange";
arrAnsChoices[1] = "both parties to the contract, as equals, set the terms and conditions of the contract";
arrAnsChoices[2] = "one party provides something of value to another party in exchange for a conditional promise";
arrAnsChoices[3] = "one party prepares the contract and the other party must accept or reject the contract as a whole, without any bargaining as to the terms of the contract";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473091;
arrAnsIDs[1] = 473092;
arrAnsIDs[2] = 473093;
arrAnsIDs[3] = 473094;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Under a <b>commutative</b><i> </i>contract, both parties specify in advance the values that they will exchange.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Under a <b>bargaining</b><i> </i>contract, both parties, as equals, set the terms and conditions of the contract.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A conditional promise is a promise to perform a stated act if a specified, uncertain event occurs. Another feature of an aleatory contract is that, if the specified event occurs, then one party may receive something of greater value than what that party gave in exchange for the conditional promise.</p><p class=\"explanations\"><b>Learning Objective: 4B. Distinguish between (1) formal and informal contracts, (2) bilateral and unilateral contracts, (3) commutative and aleatory contracts, and (4) bargaining contracts and contracts of adhesion.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Under a <b>contract of adhesion</b>, one party prepares the contract, and the other party must accept or reject the contract as a whole, without any bargaining between the parties as to the terms of the contract.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_041'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_042';
objQuestion.questionID = 117007;
objQuestion.item = 'LOMA_311_PPQ2020_042';
objQuestion.primaryLO = '4C';
objQuestion.textref = 'c. 4, pp. 8, 16';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '4C';
arrLOs[1] = '4D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Andy Howard has been declared mentally incompetent by a court, and his mother, Madeline Howard, has been authorized by the court to take care of Andy and manage his property and affairs. Andy entered into a contract for goods that are not necessaries without Ms.&nbsp;Howard’s consent. Select the answer choice that correctly identifies whether Andy Howard or Madeline Howard is the ward in this situation and whether the contract into which Andy entered is enforceable by law.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[-1] = "<u>Ward</u></div><div class=\"anshead\"><u>Enforceable contract?</u>";
arrAnsChoices[0] = "Andy Howard</div><div class=\"anscell\" onclick=\"recordAns(1);\">yes";
arrAnsChoices[1] = "Andy Howard</div><div class=\"anscell\" onclick=\"recordAns(2);\">no";
arrAnsChoices[2] = "Madeline Howard</div><div class=\"anscell\" onclick=\"recordAns(3);\">yes";
arrAnsChoices[3] = "Madeline Howard</div><div class=\"anscell\" onclick=\"recordAns(4);\">no";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473096;
arrAnsIDs[1] = 473097;
arrAnsIDs[2] = 473098;
arrAnsIDs[3] = 473099;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that Andy Howard is the ward in this situation because he is a person for whom a court has appointed a guardian. However, any contract that a ward enters into without the consent of his guardian is void, which means the contract is <b>not</b> enforceable.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Andy Howard is the ward in this situation because he is a person for whom a court has appointed a guardian. Any contract a ward enters into without the consent of his guardian is void, which means the contract was never enforceable by law. The result is the same regardless of whether the other contracting party knew about the guardian.</p><p class=\"explanations\"><b>Learning Objectives: (1) 4C. Distinguish among valid contracts, void contracts, and voidable contracts; (2) 4D. Identify and explain the four general requirements for the formation of a valid informal contract in most of the United States.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A ward is a person for whom a court has appointed a guardian. Madeline Howard does not have a court-appointed guardian in this situation. In addition, any contract that a ward enters into without the consent of his guardian is void, which means the contract is <b>not</b> enforceable.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that Andy Howard’s contract is not enforceable because any contract a ward enters into without the consent of the guardian is void. However, a ward is a person for whom a court has appointed a guardian. Madeline Howard does not have a court-appointed guardian in this situation.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_042'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_043';
objQuestion.questionID = 117008;
objQuestion.item = 'LOMA_311_PPQ2020_043';
objQuestion.primaryLO = '4D';
objQuestion.textref = 'c. 4, pp. 10-11';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '4D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Jeff Whitcomb told a neighbor, Kay Andre, that he had concert tickets he needed to sell. Ms.&nbsp;Andre stated that she would buy the concert tickets for $75. This information indicates that Ms.&nbsp;Andre made (<b>an offer / a counteroffer</b>) to Mr.&nbsp;Whitcomb, and Ms.&nbsp;Andre is the (<b>offeror / offeree</b>) in this situation.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "an offer / offeror";
arrAnsChoices[1] = "an offer / offeree";
arrAnsChoices[2] = "a counteroffer / offeror";
arrAnsChoices[3] = "a counteroffer / offeree";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473100;
arrAnsIDs[1] = 473101;
arrAnsIDs[2] = 473102;
arrAnsIDs[3] = 473103;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">An offer is a proposal that, if accepted by another according to its terms, will constitute a binding contract. In this situation, Ms.&nbsp;Andre’s statement that she is willing to buy the concert tickets for $75 is an offer because, if accepted by Mr.&nbsp;Whitcomb on its terms, the statement constitutes a binding contract. Ms.&nbsp;Andre, the party that made the offer, is the offeror. Mr.&nbsp;Whitcomb is the offeree because he is the party to whom the offer was made.</p><p class=\"explanations\"><b>Learning Objective: 4D. Identify and explain the four general requirements for the formation of a valid informal contract in most of the United States.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that an offer is a proposal that, if accepted by another according to its terms, will constitute a binding contract. In this situation, Ms.&nbsp;Andre’s statement that she is willing to buy the concert tickets for $75 is an offer because, if accepted by Mr.&nbsp;Whitcomb on its terms, the statement will constitute a binding contract. However, Ms.&nbsp;Andre is <b>not</b> the offeree in this situation. The offeree is the party to whom the offer was made.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that Ms.&nbsp;Andre, as the person who made the offer, is the offeror in this situation. However, a counteroffer is made when an offeree tries to substitute new terms or to modify the terms of an original offer in any way. Because Ms.&nbsp;Andre’s statement was not an attempt to substitute new terms or to modify the terms of a prior offer, her statement is <b>not</b> a counteroffer.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A counteroffer is made when an offeree tries to substitute new terms or to modify the terms of an original offer in any way. Because Ms.&nbsp;Andre’s statement was not an attempt to substitute new terms or to modify the terms of a prior offer, her statement is <b>not</b> a counteroffer. Also, Ms.&nbsp;Andre is <b>not</b> the offeree in this situation. The offeree is the party to whom the offer was made.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_043'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_044';
objQuestion.questionID = 117009;
objQuestion.item = 'LOMA_311_PPQ2020_044';
objQuestion.primaryLO = '4D';
objQuestion.textref = 'c. 4, pp. 10-11';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '4D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about a typical offer to contract. Select the answer choice containing the correct statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "An offer to contract terminates if the offeree rejects the offer in whole or in part.";
arrAnsChoices[1] = "If an offeror does not specify a time limit for an individual to accept the offer, then the offer remains open indefinitely.";
arrAnsChoices[2] = "To be effective, an offer must be communicated in writing.";
arrAnsChoices[3] = "An offeror generally is prohibited by law from revoking an offer to contract before the offeree has responded to the offer.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473104;
arrAnsIDs[1] = 473105;
arrAnsIDs[2] = 473106;
arrAnsIDs[3] = 473107;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Once an offeree has rejected an offer, the offeree cannot later accept that offer unless the offeror agrees to reopen the offer.</p><p class=\"explanations\"><b>Learning Objective: 4D. Identify and explain the four general requirements for the formation of a valid informal contract in most of the United States.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">If an offeror does not specify a time limit for the offer, then the offer is treated as if it remains open for a reasonable length of time. What constitutes a reasonable time is a question of fact that depends on the circumstances of the particular situation.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">An offer may be communicated orally or in writing.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Most offers are revocable, meaning the offeror can withdraw or revoke the offer at any time before it has been accepted.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_044'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_045';
objQuestion.questionID = 117010;
objQuestion.item = 'LOMA_311_PPQ2020_045';
objQuestion.primaryLO = '4D';
objQuestion.textref = 'c. 4, p. 11';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '4D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">One general principle of contract law in the United States and in many other jurisdictions states that parties have the right to contract with whomever they choose and on whatever lawful terms they choose. This principle of law is known as the principle of</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "accord and satisfaction";
arrAnsChoices[1] = "past consideration";
arrAnsChoices[2] = "gratuitous promise";
arrAnsChoices[3] = "freedom of contract";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473108;
arrAnsIDs[1] = 473109;
arrAnsIDs[2] = 473110;
arrAnsIDs[3] = 473111;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Accord and satisfaction is a type of agreement between the parties of a contract in which one party agrees to accept something other than what he was entitled to receive under the original contract.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Past consideration is a promise made in exchange for actions or events that have already taken place.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A gratuitous promise is a promise not supported by consideration. A gratuitous promise is unenforceable.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Under the principle of freedom of contract, the offeror controls the offer and has the right to decide with whom he or she will contract.</p><p class=\"explanations\"><b>Learning Objective: 4D. Identify and explain the four general requirements for the formation of a valid informal contract in most of the United States.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_045'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_046';
objQuestion.questionID = 117011;
objQuestion.item = 'LOMA_311_PPQ2020_046';
objQuestion.primaryLO = '4D';
objQuestion.textref = 'c. 4, p. 13';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '4D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">By definition, whatever a promisor asks for and receives in exchange for his contractual promise is known as</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "preexisting duty";
arrAnsChoices[1] = "disaffirmance";
arrAnsChoices[2] = "a waiver";
arrAnsChoices[3] = "consideration";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473112;
arrAnsIDs[1] = 473113;
arrAnsIDs[2] = 473114;
arrAnsIDs[3] = 473115;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A preexisting duty is a promise to do what one has a legal duty to do.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Disaffirmance is a minor’s exercise of his or her right to avoid a contract.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A waiver is the voluntary relinquishment of a known right.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">To be enforceable, a contract must be supported by legally adequate consideration. According to general contact law, consideration can consist of either a promise or an act.</p><p class=\"explanations\"><b>Learning Objective: 4D. Identify and explain the four general requirements for the formation of a valid informal contract in most of the United States.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_046'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_047';
objQuestion.questionID = 117012;
objQuestion.item = 'LOMA_311_PPQ2020_047';
objQuestion.primaryLO = '4D';
objQuestion.textref = 'c. 4, pp. 14-15';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '4D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Moore Milam, a 15-year-old United States resident, entered into a contract for goods that are not considered necessaries. With regard to the validity of this contract, it is correct to say that the contract most likely is</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "void because Moore has not reached the age of majority";
arrAnsChoices[1] = "valid and binding because Moore has reached the age of majority";
arrAnsChoices[2] = "valid and binding because the contract was for goods that are not considered necessaries";
arrAnsChoices[3] = "voidable by Moore at any time before he reaches the age of majority and within a reasonable time after he attains the age of majority";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473116;
arrAnsIDs[1] = 473117;
arrAnsIDs[2] = 473118;
arrAnsIDs[3] = 473119;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A void contract is an agreement that was never enforceable by law because the parties did not create a contract. In this situation, Moore was a party to a contract that was <b>enforceable</b> by him.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Although traditional common law stated that the age of majority was 21, most legislatures have now enacted laws that make the age of majority age 18. Because Moore has <b>not</b> reached the age of majority, he is a minor and does not have full contractual capacity.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Because Moore is under age 18, he is considered to be a minor. Under common law, a contract generally is considered to be voidable by the minor unless the contract is for <b>necessaries</b>. Necessaries are goods and services that a minor or other incapacitated person actually requires to sustain her well-being.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A minor’s exercise of his right to avoid a contract is known as disaffirmance. A minor can disaffirm—or avoid—most contracts other than contracts for necessaries at any time before reaching the age of majority and within a reasonable time after attaining the age of majority.</p><p class=\"explanations\"><b>Learning Objective: 4D. Identify and explain the four general requirements for the formation of a valid informal contract in most of the United States.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_047'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_048';
objQuestion.questionID = 117013;
objQuestion.item = 'LOMA_311_PPQ2020_048';
objQuestion.primaryLO = '4D';
objQuestion.textref = 'c. 4, pp. 16-17';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '4D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about the contractual capacity of insurance companies. Three statements are true, and one statement is false. Select the answer choice containing the <B>FALSE </B>statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "The specific limits placed on the contractual capacity of a life insurance company are spelled out in the insurer’s articles of incorporation.";
arrAnsChoices[1] = "Life insurance companies have the power to enter into life insurance contracts, but they generally do not have the power to enter into other types of contracts.";
arrAnsChoices[2] = "As a general rule, an insurance company is considered to be a legal person that has the necessary capacity to enter into contracts.";
arrAnsChoices[3] = "An insurer’s capacity to issue life insurance contracts within a given jurisdiction depends, in part, on whether the insurer has obtained a license to offer life insurance contracts in that jurisdiction.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473120;
arrAnsIDs[1] = 473121;
arrAnsIDs[2] = 473122;
arrAnsIDs[3] = 473123;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">This is a true statement; therefore, it is <b>not</b> the correct response.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">This is a false statement; therefore, it is the correct response. According to laws in most jurisdictions, corporations, including life insurance companies, have certain implied powers to conduct their businesses. They generally have the power to enter into any kind of contract that would allow them to conduct normal operations. For example, corporations can contract for office space, supplies, and services they need to operate their businesses.</p><p class=\"explanations\"><b>Learning Objective: 4D. Identify and explain the four general requirements for the formation of a valid informal contract in most of the United States.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">This is a true statement; therefore, it is <b>not</b> the correct response.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">This is a true statement; therefore, it is <b>not</b> the correct response.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_048'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_049';
objQuestion.questionID = 117014;
objQuestion.item = 'LOMA_311_PPQ2020_049';
objQuestion.primaryLO = '4E';
objQuestion.textref = 'c. 4, p. 20';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '4E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">When Cindy Sack applied for a life insurance policy from the Azalea Insurance Company, she made a material misrepresentation in her application for coverage. Azalea issued the policy with a typical two-year contestable period. One year later, Azalea discovered the material misrepresentation. With regard to the validity of this insurance contract, it is correct to say that the contract most likely is</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "void, because all contracts that contain a material misrepresentation are considered to be void contracts";
arrAnsChoices[1] = "valid, as long as the misrepresentation was made with the belief that it was true";
arrAnsChoices[2] = "voidable by Azalea, regardless of whether the misrepresentation was made with the belief that it was true";
arrAnsChoices[3] = "voidable by Azalea, but only if Ms.&nbsp;Sack made the misrepresentation knowingly";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473124;
arrAnsIDs[1] = 473125;
arrAnsIDs[2] = 473126;
arrAnsIDs[3] = 473127;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A void contract is an agreement that was never enforceable by law because the parties did not create a contract. In this situation, Ms.&nbsp;Sack and Azalea created a contract, even though it contained a material misrepresentation.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A contract that contains a material misrepresentation is not considered to be a valid contract, regardless of whether the misrepresentation was made with the belief that it was true.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">As a general rule, when one party makes a material misrepresentation—that is, a misrepresentation that induces the other party to enter into a contract that it would not have entered into had it known the truth—the contract is voidable by the innocent party. Such a contract is voidable even if the misrepresentation was made with the belief that it was true.</p><p class=\"explanations\"><b>Learning Objective: 4E. Identify some of the legal defenses that a defendant may have against a lawsuit for breach of contract.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">As a general rule, when one party makes a material misrepresentation—that is, a misrepresentation that induces the other party to enter into a contract that it would not have entered into had it known the truth—the contract is voidable by the innocent party. Such a contract is voidable even if the person did not knowingly make the misrepresentation.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_049'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_050';
objQuestion.questionID = 117015;
objQuestion.item = 'LOMA_311_PPQ2020_050';
objQuestion.primaryLO = '4F';
objQuestion.textref = 'c. 4, p. 21';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '4F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">One method the parties to a contract can use to discharge the contract is known as an accord and satisfaction. By definition, an accord and satisfaction occurs when</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "both parties mutually agree to discharge the contract";
arrAnsChoices[1] = "one party agrees to accept something other than what he or she was entitled to receive under the original contract";
arrAnsChoices[2] = "one party has performed his or her contractual obligations";
arrAnsChoices[3] = "one party substantially breaches the contract";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473128;
arrAnsIDs[1] = 473129;
arrAnsIDs[2] = 473130;
arrAnsIDs[3] = 473131;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Another way in which a contract can be discharged occurs when both parties mutually agree to discharge the contract. This method of discharge, however, is not an accord and satisfaction.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The parties to a contract can discharge the contract by entering into an agreement known as an accord and satisfaction, in which one party agrees to accept something other than what he or she was entitled to receive under the original contract.</p><p class=\"explanations\"><b>Learning Objective: 4F. Identify methods for discharging a contract and describe the remedies available for a breach of contract.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Typically, a party is discharged from further contractual obligations after he or she performs the contractual obligations. This method of discharge, however, is not an accord and satisfaction.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">When one party substantially breaches a contract, one course of action available to the innocent party is to treat the contract as if it were terminated, which then excuses the innocent party from performing any remaining contractual obligations. This method of discharge, however, is not an accord and satisfaction.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_050'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_051';
objQuestion.questionID = 117016;
objQuestion.item = 'LOMA_311_PPQ2020_051';
objQuestion.primaryLO = '4G';
objQuestion.textref = 'c. 4, p. 23';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '4G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Most states in the United States and other common law jurisdictions have enacted some form of the common law Statute of Frauds. The Statute of Frauds is a law that requires certain types of contracts to be in writing to be enforceable. One example of a contract that most likely would <B>NOT </B>be subject to the Statute of Frauds is</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "an insurance contract";
arrAnsChoices[1] = "an agreement made in consideration of marriage";
arrAnsChoices[2] = "a contract concerning an interest in land";
arrAnsChoices[3] = "a promise to be responsible for the debt or default of another";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473132;
arrAnsIDs[1] = 473133;
arrAnsIDs[2] = 473134;
arrAnsIDs[3] = 473135;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">If it is at all possible for the parties to perform a contract within one year, then the contract is not subject to the Statute of Frauds and need not be in writing to be enforceable. Because insurance contracts generally can be performed within one year, the Statute of Frauds does not require them to be in writing. However, many states and other common law jurisdictions have passed laws that do require insurance contracts to be in written form.</p><p class=\"explanations\"><b>Learning Objective: 4G. Explain the purpose and effect of the Statute of Frauds.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">An agreement made in consideration of marriage typically is governed by the Statute of Frauds and, therefore, must be in writing to be enforceable.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A contract concerning an interest in land typically is governed by the Statute of Frauds and, therefore, must be in writing to be enforceable.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A promise to be responsible for the debt or default of another typically is governed by the Statute of Frauds and, therefore, must be in writing to be enforceable.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_051'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_052';
objQuestion.questionID = 117017;
objQuestion.item = 'LOMA_311_PPQ2020_052';
objQuestion.primaryLO = '4H';
objQuestion.textref = 'c. 4, p. 24';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '4H';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Courts typically construe unclear or ambiguous language against the party who drafted or prepared a written contract, unless the use of unclear language was required by law. This rule is known as the</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "<i>rule of contra proferentem</i>";
arrAnsChoices[1] = "undue influence rule";
arrAnsChoices[2] = "adverse action rule";
arrAnsChoices[3] = "insurable interest rule";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473136;
arrAnsIDs[1] = 473137;
arrAnsIDs[2] = 473138;
arrAnsIDs[3] = 473139;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The<i> rule of contra proferentem</i> (or the <i>principle of against the offeror</i>) is applied most often to contracts of adhesion such as insurance policies. If an insurance policy contains ambiguous terms, then the courts will construe the contract against the insurer and in favor of the policyowner or beneficiary.</p><p class=\"explanations\"><b>Learning Objective: 4H. Analyze the rules that the courts follow when interpreting the meaning of a contract.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Undue influence is the misuse of a position of power or trust to overcome the free will of another person.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">An adverse action means a denial or revocation of credit or insurance coverage, a change in the terms of an existing credit arrangement or insurance coverage, or a refusal to grant credit or insurance in substantially the amount or on substantially the terms requested.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Insurable interest exists when a policyowner or beneficiary of a life insurance policy is likely to suffer a genuine loss or detriment should the event insured against occur.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_052'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_053';
objQuestion.questionID = 117018;
objQuestion.item = 'LOMA_311_PPQ2020_053';
objQuestion.primaryLO = '4I';
objQuestion.textref = 'c. 4, p. 25';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '4I';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The parol evidence rule is a procedural rule that governs the evidence that is admissible to aid a court in interpreting a contract. One true statement about the parol evidence rule is that it</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "prevents the admission of evidence to clarify the terms of a written agreement ";
arrAnsChoices[1] = "applies only to written contracts that are clear and unambiguous";
arrAnsChoices[2] = "prevents the introduction of evidence that is intended to prove that no contract was formed";
arrAnsChoices[3] = "applies regardless of whether the contract expresses the true intent of the parties";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473140;
arrAnsIDs[1] = 473141;
arrAnsIDs[2] = 473142;
arrAnsIDs[3] = 473143;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The parol evidence rule <b>allows</b> the introduction of evidence that explains the meaning of technical terms and terms that have a special trade meaning or special meaning in the locality where the contract was written.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The parol evidence rule applies only when the written contract is clear and unambiguous. In such cases, the courts will enforce the contract as written and will exclude parol evidence that contradicts the written contract.</p><p class=\"explanations\"><b>Learning Objective: 4I. Explain the purpose of the parol evidence rule and identify situations in which courts permit the use of parol evidence.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The parol evidence rule does <b>not </b>prevent the introduction of evidence that is intended to prove that no contract was formed.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">When the written contract does not express the true intent of the parties, the courts permit parol evidence concerning the actual intent of the parties.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_053'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['4A'] = "4A. Analyze the sources of contract law and apply conflict of law rules in a given situation to determine which jurisdiction’s laws govern a contract.";
arrlotext['4B'] = "4B. Distinguish between (1) formal and informal contracts, (2) bilateral and unilateral contracts, (3) commutative and aleatory contracts, and (4) bargaining contracts and contracts of adhesion.";
arrlotext['4C'] = "4C. Distinguish among valid contracts, void contracts, and voidable contracts.";
arrlotext['4D'] = "4D. Identify and explain the four general requirements for the formation of a valid informal contract in most of the United States.";
arrlotext['4E'] = "4E. Identify some of the legal defenses that a defendant may have against a lawsuit for breach of contract.";
arrlotext['4F'] = "4F. Identify methods for discharging a contract and describe the remedies available for a breach of contract.";
arrlotext['4G'] = "4G. Explain the purpose and effect of the Statute of Frauds.";
arrlotext['4H'] = "4H. Analyze the rules that the courts follow when interpreting the meaning of a contract.";
arrlotext['4I'] = "4I. Explain the purpose of the parol evidence rule and identify situations in which courts permit the use of parol evidence.";
