var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2020';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 311 Practice Questions, Chapter 5";
var coursename = 'LOMA 311';
var modulenumber = 2;
var title = "LOMA_311_PPQ2020_0_5";
var intNumPools = 1;
var numQ = 13;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Business Law for Insurance Professionals (2020)";
arrNumChap[0] = 1;
var thisChap = '5';

objPool = new Object(); 
objPool.intSelectCount = 13;
objPool.formID = 2380;
objPool.formName = 'PPQ2020_0_5';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_311_PQ_054';
arrPoolQuestions[1] = 'LOMA_311_PQ_055';
arrPoolQuestions[2] = 'LOMA_311_PQ_056';
arrPoolQuestions[3] = 'LOMA_311_PQ_057';
arrPoolQuestions[4] = 'LOMA_311_PQ_058';
arrPoolQuestions[5] = 'LOMA_311_PQ_059';
arrPoolQuestions[6] = 'LOMA_311_PQ_060';
arrPoolQuestions[7] = 'LOMA_311_PQ_061';
arrPoolQuestions[8] = 'LOMA_311_PQ_062';
arrPoolQuestions[9] = 'LOMA_311_PQ_063';
arrPoolQuestions[10] = 'LOMA_311_PQ_064';
arrPoolQuestions[11] = 'LOMA_311_PQ_065';
arrPoolQuestions[12] = 'LOMA_311_PQ_066';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_054';
objQuestion.questionID = 117019;
objQuestion.item = 'LOMA_311_PPQ2020_054';
objQuestion.primaryLO = '5A';
objQuestion.textref = 'c. 5, p. 3';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '5A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Andrew Morgan authorized Tina Brown to enter into a contract with the Mabry Company on his behalf. Select the answer choice that correctly identifies the party that is the agent and the party that is the principal in this situation.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[-1] = "<u>Agent</u></div><div class=\"anshead\"><u>Principal</u>";
arrAnsChoices[0] = "Ms.&nbsp;Brown</div><div class=\"anscell\" onclick=\"recordAns(1);\">Mr.&nbsp;Morgan";
arrAnsChoices[1] = "Ms.&nbsp;Brown</div><div class=\"anscell\" onclick=\"recordAns(2);\">Mabry";
arrAnsChoices[2] = "Mabry</div><div class=\"anscell\" onclick=\"recordAns(3);\">Mr.&nbsp;Morgan";
arrAnsChoices[3] = "Mabry</div><div class=\"anscell\" onclick=\"recordAns(4);\">Ms.&nbsp;Brown";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473145;
arrAnsIDs[1] = 473146;
arrAnsIDs[2] = 473147;
arrAnsIDs[3] = 473148;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The law defines an agent as a party who is authorized by another party, the principal, to act on the principal’s behalf. In this situation, Mr.&nbsp;Morgan, the principal, authorized Ms.&nbsp;Brown, the agent, to act on his behalf.</p><p class=\"explanations\"><b>Learning Objective: 5A. Describe and recognize an agency relationship between a principal and an agent.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The law defines an agent as a party who is authorized by another party, the principal, to act on the principal’s behalf. It is true that Ms.&nbsp;Brown is the agent in this situation because she was authorized by a principal to act on the principal’s behalf. However, Mabry did not authorize another party to act on its behalf; therefore, Mabry is <b>not </b>a principal. Rather, Mabry is a third party to the contract.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The law defines an agent as a party who is authorized by another party, the principal, to act on the principal’s behalf. It is true that Mr.&nbsp;Morgan is the principal in this situation because he is the party who authorized another party to act on his behalf. However, Mabry is a <b>third party </b>to the contract, not the agent.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The law defines an agent as a party who is authorized by another party, the principal, to act on the principal’s behalf. Mabry was not authorized to act on Mr.&nbsp;Morgan’s behalf; therefore, Mabry is <b>not </b>an agent in this situation. Rather, Mabry is a third party to the contract. Also, Ms.&nbsp;Brown did not authorize another party to act on her behalf; therefore, she is <b>not </b>a principal in this situation.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_054'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_055';
objQuestion.questionID = 117020;
objQuestion.item = 'LOMA_311_PPQ2020_055';
objQuestion.primaryLO = '5B';
objQuestion.textref = 'c. 5, pp. 4-5';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '5B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The authority to act on behalf of a principal that the principal intentionally confers on an agent and that the agent reasonably believes is conferred is known as (<b>apparent / actual</b>) authority. This type of authority can be either express or implied. (<b>Express / Implied</b>) authority is the authority that a principal explicitly confers on an agent.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "apparent / Express";
arrAnsChoices[1] = "apparent / Implied";
arrAnsChoices[2] = "actual / Express";
arrAnsChoices[3] = "actual / Implied";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473149;
arrAnsIDs[1] = 473150;
arrAnsIDs[2] = 473151;
arrAnsIDs[3] = 473152;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that express authority is the authority that a principal explicitly confers on an agent. However, apparent authority is authority that a principal either intentionally or negligently allows a third party to believe an agent possesses.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Apparent authority is authority that a principal either intentionally or negligently allows a third party to believe an agent possesses. Also, implied authority arises incidentally from an express grant of authority. Implied authority is <b>not</b> explicitly conferred<b> </b>on an agent.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">As part of an agency agreement, a principal confers actual authority on an agent. Actual authority is the authority to act on behalf of a principal that the principal intentionally confers on the agent and that the agent reasonably believes is conferred. Actual authority can be either express or implied.</p><p class=\"explanations\">Express authority is the authority that a principal explicitly confers on an agent. Implied authority is the authority that a principal intends an agent to have and that arises incidentally from an express grant of authority. Apparent authority is authority that the principal either intentionally or negligently allows a third party to believe the agent possesses. </p><p class=\"explanations\"><b>Learning Objective: 5B. Identify various types of authority an agent may possess to act on behalf of a principal.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that actual authority is the authority to act on behalf of a principal that the principal intentionally confers on an agent and that the agent reasonably believes is conferred. However, implied authority arises incidentally from an express grant of authority. Implied authority is <b>not </b>explicitly conferred<b> </b>on an agent.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_055'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_056';
objQuestion.questionID = 117021;
objQuestion.item = 'LOMA_311_PPQ2020_056';
objQuestion.primaryLO = '5B';
objQuestion.textref = 'c. 5, pp. 4-5';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '5B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about typical agency agreements. Three statements are true, and one statement is false. Select the answer choice containing the <B>FALSE</B> statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "The parties to an agency relationship generally may consent to the agency agreement either orally or in writing.";
arrAnsChoices[1] = "The scope of an agent’s actual authority is a question of fact.";
arrAnsChoices[2] = "Under a typical agency agreement, an agent generally has the actual authority to make a statement under oath for a principal.";
arrAnsChoices[3] = "As part of an agency agreement, the principal confers actual authority on the agent.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473153;
arrAnsIDs[1] = 473154;
arrAnsIDs[2] = 473155;
arrAnsIDs[3] = 473156;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">This is a true statement; therefore, it is <b>not</b> the correct response.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">This is a true statement; therefore, it is <b>not</b> the correct response.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">This is a false statement; therefore, it is the correct response. Generally, a principal may do anything through an agent that the principal can legally do for himself. However, some acts, such as making a statement under oath, are of such a personal nature that the law requires individuals to perform such acts themselves.</p><p class=\"explanations\"><b>Learning Objective: 5B. Identify various types of authority an agent may possess to act on behalf of a principal.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">This is a true statement; therefore, it is <b>not</b> the correct response.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_056'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_057';
objQuestion.questionID = 117022;
objQuestion.item = 'LOMA_311_PPQ2020_057';
objQuestion.primaryLO = '5B';
objQuestion.textref = 'c. 5, pp. 6-7';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '5B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The legal effect of a contract entered into by an agent on behalf of a principal depends in part on contractual capacity. Select the answer choice that correctly identifies whether an agent and a principal typically are required to have contractual capacity in order for a contract entered into by the agent to be valid and binding on the principal.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[-1] = "<u>Agent</u></div><div class=\"anshead\"><u>Principal</u>";
arrAnsChoices[0] = "required</div><div class=\"anscell\" onclick=\"recordAns(1);\">required";
arrAnsChoices[1] = "required</div><div class=\"anscell\" onclick=\"recordAns(2);\">not required";
arrAnsChoices[2] = "not required</div><div class=\"anscell\" onclick=\"recordAns(3);\">required";
arrAnsChoices[3] = "not required</div><div class=\"anscell\" onclick=\"recordAns(4);\">not required";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473158;
arrAnsIDs[1] = 473159;
arrAnsIDs[2] = 473160;
arrAnsIDs[3] = 473161;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that a principal must have contractual capacity in order for a contract entered into by its agent to be valid and binding on the principal. However, because an agent is not a party to such a contract, the agent generally does<b> not</b> need to have contractual capacity in order to form a contract that binds the principal.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A principal <b>must</b> have contractual capacity in order for a contract entered into by its agent to be valid and binding on the principal. Also, because an agent is not a party to such a contract, the agent generally does<b> not</b> need to have contractual capacity in order to form a contract that binds the principal.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Because an agent is not a party to such a contract, the agent generally does not need to have contractual capacity in order to form a contract that binds the principal. However, a principal must have contractual capacity in order for a contract entered into by its agent to be valid and binding on the principal.</p><p class=\"explanations\"><b>Learning Objective: 5B. Identify various types of authority an agent may possess to act on behalf of a principal.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that, because an agent generally is not a party to a contract binding the principal, the agent generally does not need to have contractual capacity in order to form the contract. However, a principal <b>must </b>have contractual capacity in order for a contract entered into by its agent to be valid and binding on the principal.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_057'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_058';
objQuestion.questionID = 117023;
objQuestion.item = 'LOMA_311_PPQ2020_058';
objQuestion.primaryLO = '5C';
objQuestion.textref = 'c. 5, pp. 8, 9';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '5C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">One fiduciary duty required of an agent is that the agent must use reasonable care, skill, and diligence in carrying out his or her agency duties. This fiduciary duty is known, by definition, as the duty of</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "accounting";
arrAnsChoices[1] = "competence";
arrAnsChoices[2] = "obedience";
arrAnsChoices[3] = "loyalty and good faith";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473162;
arrAnsIDs[1] = 473163;
arrAnsIDs[2] = 473164;
arrAnsIDs[3] = 473165;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Another fiduciary duty required of an agent is the duty to account to the principal for all money that comes into the agent’s possession as a result of the agency relationship.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The level of care required of an agent is that of a reasonably prudent person who has the same skills as the agent. An agent who fails to use reasonable care in carrying out agency duties has breached a fiduciary duty owed to the principal.</p><p class=\"explanations\"><b>Learning Objective: 5C. Describe an agent’s duties to the principal and the principal’s duties to the agent, and identify the remedies available if either party breaches the agency agreement.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Another fiduciary duty required of an agent is the duty to obey the principal’s lawful instructions and carry out those instructions according to the principal’s wishes.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Another fiduciary duty required of an agent is the duty of loyalty and good faith. This duty requires an agent acting within the scope of his authority to act primarily for the principal’s benefit, putting the interests of the principal above all other interests.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_058'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_059';
objQuestion.questionID = 117024;
objQuestion.item = 'LOMA_311_PPQ2020_059';
objQuestion.primaryLO = '5C';
objQuestion.textref = 'c. 5, p. 8';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '5C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements describe individuals who are agents of the Gable Company. Select the answer choice that correctly describes an individual who is <B>NOT </B>violating the fiduciary duty of loyalty and good faith.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Kim Tran, a Gable employee, is operating her own part-time business that competes with Gable’s business.";
arrAnsChoices[1] = "Grant Lowery sold a Gable product to a customer for $100, but Gable only charges $85 for the product. Mr.&nbsp;Lowery gave $85 to Gable and kept the remaining $15 for himself.";
arrAnsChoices[2] = "Jane Cobb had a financial interest in a transaction involving Gable. Ms.&nbsp;Cobb fully disclosed all material facts about her interest to Gable, and Gable authorized her to deal on her own behalf in the transaction.";
arrAnsChoices[3] = "Eric Allison received a secret commission from a third party as a result of a contract Mr.&nbsp;Allison created on Gable’s behalf.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473166;
arrAnsIDs[1] = 473167;
arrAnsIDs[2] = 473168;
arrAnsIDs[3] = 473169;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Under the duty of loyalty and good faith, an agent may not engage in any business that interferes or competes with the principal’s business. Because Ms.&nbsp;Tran’s business competes with Gable’s business, she has violated her fiduciary duty of loyalty and good faith.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Under the duty of loyalty and good faith, an agent may not make any secret profits<b> </b>from the agency relationship. Because Mr.&nbsp;Lowery secretly profited from the sale of a Gable product, he has violated his fiduciary duty of loyalty and good faith.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">When an agent has a financial interest in a transaction that involves the principal, the agent has a duty to fully disclose all material facts to the principal. The agent may deal on her own behalf in such a transaction only when the principal, with full knowledge of the material facts, consents to the transaction. Because Gable was fully informed of Ms.&nbsp;Cobb’s financial interest and consented to the transaction, Ms.&nbsp;Cobb did not violate her fiduciary duty of loyalty and good faith.</p><p class=\"explanations\"><b>Learning Objective: 5C. Describe an agent’s duties to the principal and the principal’s duties to the agent, and identify the remedies available if either party breaches the agency agreement.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Under the duty of loyalty and good faith, an agent may not receive secret commissions or other undisclosed payments from third parties. In this situation, Mr.&nbsp;Allison violated his fiduciary duty of loyalty and good faith.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_059'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_060';
objQuestion.questionID = 117025;
objQuestion.item = 'LOMA_311_PPQ2020_060';
objQuestion.primaryLO = '5C';
objQuestion.textref = 'c. 5, p. 10';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '5C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">A principal generally has a duty to compensate or reimburse an agent for any losses the agent incurs while performing his or her duties, as long as the loss was not the result of the agent’s negligence or misconduct. The compensation or reimbursement of another person’s loss is known as</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "indemnification";
arrAnsChoices[1] = "mutualization";
arrAnsChoices[2] = "a warranty";
arrAnsChoices[3] = "an agency at will";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473170;
arrAnsIDs[1] = 473171;
arrAnsIDs[2] = 473172;
arrAnsIDs[3] = 473173;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A principal’s duty to indemnify an agent usually arises in situations in which the agent’s liability results from no fault of the agent and while the agent is following the principal’s instructions.</p><p class=\"explanations\"><b>Learning Objective: 5C. Describe an agent’s duties to the principal and the principal’s duties to the agent, and identify the remedies available if either party breaches the agency agreement.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Mutualization is the process a stock insurer undertakes to convert to a mutual form of ownership.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A warranty is a promise or guarantee recognized by law that a statement of fact is true.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Agency at will is an agency relationship that is to continue for an unspecified amount of time.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_060'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_061';
objQuestion.questionID = 117026;
objQuestion.item = 'LOMA_311_PPQ2020_061';
objQuestion.primaryLO = '5D';
objQuestion.textref = 'c. 5, p. 13';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '5D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Taisheng Li is an agent for the Clubland Corporation. Acting within the scope of his actual authority, Mr.&nbsp;Li entered into a contract with the Eastside Company on Clubland’s behalf. However, Mr.&nbsp;Li purported to act on his own behalf and entered the contract in his own name. Mr.&nbsp;Li did not mention to Eastside the existence of Clubland as the principal in the transaction. With regard to types of principals and their contractual liability, it is correct to say that Clubland is the type of principal known as</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "a partially disclosed principal, and Eastside most likely cannot enforce the contract against Clubland";
arrAnsChoices[1] = "a partially disclosed principal, and Eastside most likely can enforce the contract against Clubland";
arrAnsChoices[2] = "an undisclosed principal, and Eastside most likely cannot enforce the contract against Clubland";
arrAnsChoices[3] = "an undisclosed principal, and Eastside most likely can enforce the contract against Clubland";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473174;
arrAnsIDs[1] = 473175;
arrAnsIDs[2] = 473176;
arrAnsIDs[3] = 473177;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">When an agent acknowledges the existence of a principal but does not identify that principal and contracts on behalf of that principal, the principal is known as a partially disclosed principal. In this case, Mr.&nbsp;Li purported to act on his own behalf and did not acknowledge the existence of a principal when he entered into the contract with Eastside; thus, Clubland is <b>not </b>a partially disclosed principal.</p><p class=\"explanations\">In addition, Eastside, the third party in this transaction, most likely <b>can</b> enforce the contract against Clubland because Mr.&nbsp;Li acted within the scope of his authority.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that Eastside, the third party in this transaction, most likely can enforce the contract against Clubland because Mr.&nbsp;Li acted within the scope of his authority.</p><p class=\"explanations\">However, Clubland is <b>not </b>a partially disclosed principal with respect to the contract. When an agent discloses that he is acting on behalf of a principal, contracts on behalf of a principal, but does not identify the principal, then the principal is a partially disclosed principal. In this situation, Mr.&nbsp;Li purported to act on his own behalf and did <b>not</b> acknowledge the existence of a principal when he entered into the contract with Eastside.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that, when Mr.&nbsp;Li purported to act on his own behalf and did not mention the existence of Clubland, Clubland became an undisclosed principal with respect to this contract.</p><p class=\"explanations\">However, Eastside, the third party in this transaction, most likely <b>can </b>enforce the contract against Clubland because Mr.&nbsp;Li acted within the scope of his authority.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">When an agent purports to act on his own behalf and does not mention the existence of a principal, the principal is known as an undisclosed principal. When an agent acknowledges the existence of a principal but does not identify the principal, the principal is known as a partially disclosed principal. Clubland is an undisclosed principal with respect to the contract.</p><p class=\"explanations\">In addition, Eastside, the third party in this situation, most likely can enforce the contract against Clubland because Mr.&nbsp;Li acted within the scope of his authority.</p><p class=\"explanations\"><b>Learning Objective: 5D. Identify situations in which a principal is liable to a third party with whom an agent deals on the principal’s behalf.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_061'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_062';
objQuestion.questionID = 117027;
objQuestion.item = 'LOMA_311_PPQ2020_062';
objQuestion.primaryLO = '5D';
objQuestion.textref = 'c. 5, p. 15';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '5D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">When an agent enters into a contract on a principal’s behalf without actual or apparent authority to bind the principal, the principal may choose to accept the contract by ratifying the agent’s unauthorized acts. One true statement about ratifying such a contract is that the</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "contract becomes effective as of the date when the principal agrees to ratify the contract";
arrAnsChoices[1] = "principal must have an existing agency relationship with the purported agent in order for the ratification to be effective";
arrAnsChoices[2] = "principal can choose to ratify only part of the contract";
arrAnsChoices[3] = "agent must have purported to act on behalf of the principal in order for the ratification to be effective";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473178;
arrAnsIDs[1] = 473179;
arrAnsIDs[2] = 473180;
arrAnsIDs[3] = 473181;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">By ratifying a contract, the principal affirms that he is a party to the contract. The contract is effective as of the date <b>it was originally entered into </b>by the agent and the third party.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A principal may ratify an unauthorized act even if there was no agency relationship with the purported agent. In such a case, ratification of the unauthorized act creates an agency relationship known as agency by ratification.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">In order for a ratification to be effective, the principal must ratify the <b>entire contract</b>, accepting both its favorable and unfavorable terms.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">For a ratification to be effective, the agent must have purported to act on behalf of the principal. If an agent purported to act on his own behalf without disclosing the existence of the principal, then the principal cannot ratify the agent’s unauthorized acts.</p><p class=\"explanations\"><b>Learning Objective: 5D. Identify situations in which a principal is liable to a third party with whom an agent deals on the principal’s behalf.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_062'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_063';
objQuestion.questionID = 117028;
objQuestion.item = 'LOMA_311_PPQ2020_063';
objQuestion.primaryLO = '5D';
objQuestion.textref = 'c. 5, pp. 16-17';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '5D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following individuals, all of whom committed tortious acts, worked for the Concept Finance Company. Of these individuals, the ones who most likely would subject Concept to vicarious liability for their torts include</p><ul class=\"examul\"><li>Emily Metso, an independent contractor, who committed a tort while performing administrative duties for Concept</li><li>Olga Garcia, an employee of Concept, who committed a tortious act while acting within the course of her employment with Concept</li><li>Zach Yang, an employee of Concept, who committed a tortious act while on vacation, and the tortious act was not related to Mr.&nbsp;Yang’s job duties</li></ul>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Ms.&nbsp;Metso, Ms.&nbsp;Garcia, and Mr.&nbsp;Yang";
arrAnsChoices[1] = "Ms.&nbsp;Metso only";
arrAnsChoices[2] = "Ms.&nbsp;Garcia only";
arrAnsChoices[3] = "Mr.&nbsp;Yang only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473182;
arrAnsIDs[1] = 473183;
arrAnsIDs[2] = 473184;
arrAnsIDs[3] = 473185;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Concept is <b>not </b>vicariously liable for the tort committed by at least one of these individuals.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">An employer generally is <b>not</b> vicariously liable for the torts of an independent contractor. Therefore, Concept most likely would not be vicariously liable for Ms.&nbsp;Metso’s tortious act.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">When an employee commits a tort while acting in the course of her employment, the employer is vicariously liable for the harm that resulted from the tort even though the employer was not at fault. Therefore, Concept would be vicariously liable for the tort Ms.&nbsp;Garcia committed.</p><p class=\"explanations\"><b>Learning Objective: 5D. Identify situations in which a principal is liable to a third party with whom an agent deals on the principal’s behalf.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">If an employee is not acting within the course of his or her employment at the time that the employee committed the tort, then the employer generally is not vicariously liable. Therefore, Concept most likely would <b>not </b>be liable for Mr.&nbsp;Yang’s tort because Mr.&nbsp;Yang was not acting within the course of his employment at the time that he committed the tort.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_063'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_064';
objQuestion.questionID = 117029;
objQuestion.item = 'LOMA_311_PPQ2020_064';
objQuestion.primaryLO = '5E';
objQuestion.textref = 'c. 5, p. 18';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '5E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Most common law jurisdictions require a showing of the following element(s) to prove a breach of warranty of authority:</p><ol type=\"A\" class=\"combo\"><li>An agent represents that he has authority to act on behalf of a principal.</li><li>An agent does not have the authority to represent the principal that he claims to represent.</li><li>A third party relies on the agent’s misrepresentation to the third party’s detriment.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A, B, and C";
arrAnsChoices[1] = "A and B only";
arrAnsChoices[2] = "B and C only";
arrAnsChoices[3] = "A only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473186;
arrAnsIDs[1] = 473187;
arrAnsIDs[2] = 473188;
arrAnsIDs[3] = 473189;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">All of these statements are correct. A third party has a cause of action against the agent for breach of warranty of authority when all three elements are present. A warranty of authority is a guarantee recognized by law that an agent is acting on behalf of a principal who has contractual capacity and that the agent has authority to act for the principal.</p><p class=\"explanations\"><b>Learning Objective: 5E. Identify situations in which an agent acting on behalf of a principal is liable to a third party.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statements A and B are correct. However, Statement C is also correct.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statements B and C are correct. However, Statement A is also correct.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Statement A is correct, but it is not the only correct response.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_064'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_065';
objQuestion.questionID = 117030;
objQuestion.item = 'LOMA_311_PPQ2020_065';
objQuestion.primaryLO = '5F';
objQuestion.textref = 'c. 5, pp. 21-22';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '5F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements describe situations in which a party to an agency relationship terminated the agency relationship. Select the answer choice that describes a situation in which the party terminating the relationship most likely did<b> NOT </b>have the legal right to terminate the agreement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Bert Gurskey and Sandy Liu entered into an agency agreement with a one-year term. One month later, Mr.&nbsp;Gurskey terminated the agreement. Neither Mr.&nbsp;Gurskey nor Ms.&nbsp;Liu had violated any of their duties at the time that the agreement ended.";
arrAnsChoices[1] = "The Origami Company authorized Jerry Watson to act on Origami’s behalf. Two months after they entered into a six-month agency agreement, Origami terminated the agreement because Mr.&nbsp;Watson failed to account for the money that he received while acting as Origami’s agent.";
arrAnsChoices[2] = "The Maple Company hired the Mondo Group as its agent to complete a business development project. Although the agreement included a termination provision stating that the agency relationship would end once the project was complete, both parties mutually agreed to terminate the relationship before that time.";
arrAnsChoices[3] = "Rebecca Rush was hired to act as an agent for the Sonnet Company for two years. After one year, Ms.&nbsp;Rush terminated the agreement because Sonnet failed to compensate her in accordance with the agreement.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473190;
arrAnsIDs[1] = 473191;
arrAnsIDs[2] = 473192;
arrAnsIDs[3] = 473193;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">An agency relationship requires the consent of both parties, and either party has the power to end the relationship at any time. However, because the term of this agreement is one year, Mr.&nbsp;Gurskey does not have the legal right to end the relationship prior to the end of the term without the consent of Ms.&nbsp;Liu. Thus, Mr.&nbsp;Gurskey is in breach of the agency agreement and is liable to Ms.&nbsp;Liu for any damages that result from the breach.</p><p class=\"explanations\"><b>Learning Objective: 5F. List the four methods by which an agency relationship can terminate, and explain when a principal has a duty to notify third parties of the termination.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Because Mr.&nbsp;Watson breached the fiduciary duty of an accounting, Origami has the legal right to terminate the agency relationship without liability to Mr.&nbsp;Watson.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">An agent and a principal have the legal right to mutually agree to end the relationship at any time without incurring further legal liability, even if the agency agreement does not include a termination provision.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">When a principal refuses to compensate<b> </b>an agent per the terms of the agency agreement, the agent typically has a legal right to end the agency relationship.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_065'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_066';
objQuestion.questionID = 117031;
objQuestion.item = 'LOMA_311_PPQ2020_066';
objQuestion.primaryLO = '5F';
objQuestion.textref = 'c. 5, p. 23';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '5F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">One true statement about the termination of an agency relationship by operation of law is</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "that, in order for the termination to be effective, both parties must mutually agree to terminate the agency relationship";
arrAnsChoices[1] = "that the agent may continue to have apparent authority after the termination even though her actual authority to bind the principal has ended";
arrAnsChoices[2] = "that the principal generally has a legal duty to notify third parties of the termination";
arrAnsChoices[3] = "that, if an agent contracts on behalf of a principal after the agency relationship has terminated, then the third party cannot enforce the contract against the principal";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473194;
arrAnsIDs[1] = 473195;
arrAnsIDs[2] = 473196;
arrAnsIDs[3] = 473197;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Termination by operation of law means that an agent’s authority to bind the principal automatically terminates as a result of the occurrence of certain events, rather than as the result of an action of the agent or of the principal.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">When an agency relationship terminates by operation of law, the agent’s authority—actual and apparent—to bind the principal also terminates by operation of law.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">When an agent’s authority terminates by operation of law, the principal generally has <b>no </b>duty to notify third parties of the termination.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">When an agent’s authority terminates by operation of law, the third party’s only recourse is to attempt to enforce the contract against the agent, who may be held liable for breach of the warranty of authority.</p><p class=\"explanations\"><b>Learning Objective: 5F. List the four methods by which an agency relationship can terminate, and explain when a principal has a duty to notify third parties of the termination.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_066'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['5A'] = "5A. Describe and recognize an agency relationship between a principal and an agent.";
arrlotext['5B'] = "5B. Identify various types of authority an agent may possess to act on behalf of a principal.";
arrlotext['5C'] = "5C. Describe an agent’s duties to the principal and the principal’s duties to the agent, and identify the remedies available if either party breaches the agency agreement.";
arrlotext['5D'] = "5D. Identify situations in which a principal is liable to a third party with whom an agent deals on the principal’s behalf.";
arrlotext['5E'] = "5E. Identify situations in which an agent acting on behalf of a principal is liable to a third party.";
arrlotext['5F'] = "5F. List the four methods by which an agency relationship can terminate, and explain when a principal has a duty to notify third parties of the termination.";
