var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2020';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 311 Practice Questions, Chapter 6";
var coursename = 'LOMA 311';
var modulenumber = 2;
var title = "LOMA_311_PPQ2020_0_6";
var intNumPools = 1;
var numQ = 19;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Business Law for Insurance Professionals (2020)";
arrNumChap[0] = 1;
var thisChap = '6';

objPool = new Object(); 
objPool.intSelectCount = 19;
objPool.formID = 2380;
objPool.formName = 'PPQ2020_0_6';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_311_PQ_067';
arrPoolQuestions[1] = 'LOMA_311_PQ_068';
arrPoolQuestions[2] = 'LOMA_311_PQ_069';
arrPoolQuestions[3] = 'LOMA_311_PQ_070';
arrPoolQuestions[4] = 'LOMA_311_PQ_071';
arrPoolQuestions[5] = 'LOMA_311_PQ_072';
arrPoolQuestions[6] = 'LOMA_311_PQ_073';
arrPoolQuestions[7] = 'LOMA_311_PQ_074';
arrPoolQuestions[8] = 'LOMA_311_PQ_075';
arrPoolQuestions[9] = 'LOMA_311_PQ_076';
arrPoolQuestions[10] = 'LOMA_311_PQ_077';
arrPoolQuestions[11] = 'LOMA_311_PQ_078';
arrPoolQuestions[12] = 'LOMA_311_PQ_079';
arrPoolQuestions[13] = 'LOMA_311_PQ_080';
arrPoolQuestions[14] = 'LOMA_311_PQ_081';
arrPoolQuestions[15] = 'LOMA_311_PQ_082';
arrPoolQuestions[16] = 'LOMA_311_PQ_083';
arrPoolQuestions[17] = 'LOMA_311_PQ_084';
arrPoolQuestions[18] = 'LOMA_311_PQ_085';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_067';
objQuestion.questionID = 117032;
objQuestion.item = 'LOMA_311_PPQ2020_067';
objQuestion.primaryLO = '6A';
objQuestion.textref = 'c. 6, p. 3';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '6A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">In most countries, property is characterized as either real property or personal property. One example of <i>real </i>property is</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "furniture";
arrAnsChoices[1] = "an insurance policy";
arrAnsChoices[2] = "a book";
arrAnsChoices[3] = "a barn";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473198;
arrAnsIDs[1] = 473199;
arrAnsIDs[2] = 473200;
arrAnsIDs[3] = 473201;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Real property consists of land and whatever is growing on or affixed to the land. Furniture is <b>not </b>an example of real property because it is not affixed to land.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Real property consists of land and whatever is growing on or affixed to the land. An insurance policy is <b>not </b>an example of real property because it is not affixed to land.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Real property consists of land and whatever is growing on or affixed to the land. A book is <b>not</b> an example of real property because it is not affixed to land.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Real property, sometimes referred to as real estate, consists of land and whatever is growing on or affixed to the land. Some jurisdictions refer to real property as immovable property.</p><p class=\"explanations\"><b>Learning Objective: 6A. Distinguish between real property and personal property.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_067'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_068';
objQuestion.questionID = 117033;
objQuestion.item = 'LOMA_311_PPQ2020_068';
objQuestion.primaryLO = '6B';
objQuestion.textref = 'c. 6, p. 4';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '6B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">One method in which people acquire ownership of property is to buy it from the party who owns it. In such a transaction, the party who <i>sells </i>the property is often referred to as the</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "transferor";
arrAnsChoices[1] = "transferee";
arrAnsChoices[2] = "donor";
arrAnsChoices[3] = "donee";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473202;
arrAnsIDs[1] = 473203;
arrAnsIDs[2] = 473204;
arrAnsIDs[3] = 473205;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">When people acquire ownership of property by buying it from another party who owns the property, the party who sells the property is known as the transferor. In any transfer of property ownership, the new owner generally can receive only those ownership interests that the transferor had to transfer.</p><p class=\"explanations\"><b>Learning Objective: 6B. Analyze common methods of acquiring property.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">When people acquire ownership of property by buying it from another party who owns the property, the party who <b>buys </b>the property is the transferee.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A donor is a party who makes a <b>gift </b>of property, rather than a sale of property.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A donee is a party who <b>receives </b>property as a gift.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_068'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_069';
objQuestion.questionID = 117034;
objQuestion.item = 'LOMA_311_PPQ2020_069';
objQuestion.primaryLO = '6B';
objQuestion.textref = 'c. 6, p. 4';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '6B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Linda Porter, a resident of State A, stole a computer from Jonathan Dave, who is also a resident of State A. Ms.&nbsp;Porter then sold the computer to Maggie Pornir. In this situation, title of the computer belongs to</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Ms.&nbsp;Porter";
arrAnsChoices[1] = "Mr.&nbsp;Dave";
arrAnsChoices[2] = "Ms.&nbsp;Pornir";
arrAnsChoices[3] = "State A, because all stolen property automatically becomes the property of the state in which it is stolen";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473206;
arrAnsIDs[1] = 473207;
arrAnsIDs[2] = 473208;
arrAnsIDs[3] = 473209;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Title means that a person has a claim to ownership of property that is superior to anyone else’s ownership claim. Ms.&nbsp;Porter did <b>not </b>receive title to the computer by stealing it.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">When property is stolen, the title remains the property of the original owner. Therefore, Mr.&nbsp;Dave is the rightful owner of the computer.</p><p class=\"explanations\"><b>Learning Objective: 6B. Analyze common methods of acquiring property.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">When someone buys property that was stolen, the transferee receives no title because the transferor did <b>not </b>have title to transfer. Thus, Ms.&nbsp;Porter, the transferor, did not have title to the computer to transfer to Ms.&nbsp;Pornir, the transferee.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">When property is stolen, the title remains the property of the <b>original owner</b>, and it does not belong to the state in which the property was stolen. In this case, Mr.&nbsp;Dave, not State A, has title to the computer.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_069'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_070';
objQuestion.questionID = 117035;
objQuestion.item = 'LOMA_311_PPQ2020_070';
objQuestion.primaryLO = '6C';
objQuestion.textref = 'c. 6, p. 5';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '6C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Nathan Gossett and Jackson Miller own property as tenants in common. Mr.&nbsp;Gossett has a 30% interest in the property, and Mr.&nbsp;Miller has a 70% interest in the property. One true statement about this situation is that</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Mr.&nbsp;Gossett and Mr.&nbsp;Miller each have a right of survivorship in the property";
arrAnsChoices[1] = "Mr.&nbsp;Gossett cannot transfer ownership of his interest in the property to a third party";
arrAnsChoices[2] = "Mr.&nbsp;Gossett and Mr.&nbsp;Miller do <i>not </i>have equal rights to possess and use the property";
arrAnsChoices[3] = "Mr.&nbsp;Gossett and Mr.&nbsp;Miller each have the right to decide who will receive his interest following his death";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473210;
arrAnsIDs[1] = 473211;
arrAnsIDs[2] = 473212;
arrAnsIDs[3] = 473213;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A right of survivorship means that, when one owner dies, his share automatically passes<b> </b>to the surviving owner. Tenancy in common does <b>not </b>include a right of survivorship.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Under the tenancy in common form of property ownership, each owner has the right to sell or otherwise transfer ownership of his undivided interest in the property.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Although Mr.&nbsp;Gossett and Mr.&nbsp;Miller do not have equal ownership interests in the property, each tenant in common has an <b>equal right </b>to possess and use the property.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Unlike joint tenancy, a tenancy in common form of property ownership does not include a right of survivorship. Therefore, each tenant has the right to decide who will receive his interest in the property following his death.</p><p class=\"explanations\"><b>Learning Objective: 6C. Identify the various forms of property ownership and restrictions that may be placed on property ownership rights.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_070'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_071';
objQuestion.questionID = 117036;
objQuestion.item = 'LOMA_311_PPQ2020_071';
objQuestion.primaryLO = '6C';
objQuestion.textref = 'c. 6, p. 6';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '6C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Matt and Nora Zamora, a married couple, are United States residents who reside in a community property state. Matt and Nora acquired the following property during their marriage:</p><ul class=\"examul\"><li>An automobile, which was purchased with shared funds they earned during their marriage</li><li>A house, which Nora inherited from her father</li><li>An insurance policy on Matt’s life, which Matt purchased during the marriage using money from their shared checking account</li></ul><p class=\"stem\">With regard to the property described above, it most likely is correct to say that the property considered to be <i>separate </i>property includes</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "the automobile, the house, and the insurance policy";
arrAnsChoices[1] = "the automobile and the insurance policy only";
arrAnsChoices[2] = "the house only";
arrAnsChoices[3] = "the insurance policy only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473214;
arrAnsIDs[1] = 473215;
arrAnsIDs[2] = 473216;
arrAnsIDs[3] = 473217;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these properties is an example of community property, <b>not </b>separate property.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Income earned during a marriage is community property, and any property purchased with community property—such as the Zamoras’ automobile and the insurance policy on Matt’s life—is considered to be <b>community </b>property, not separate property.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Under community property laws, property acquired by one spouse during a marriage as a gift or inheritance—such as the house Nora inherited from her father—is the separate property of that spouse. Income earned during a marriage is community property, and any property purchased with community property—such as the Zamoras’ automobile and the insurance policy on Matt’s life—is considered to be community property.</p><p class=\"explanations\"><b>Learning Objective: 6C. Identify the various forms of property ownership and restrictions that may be placed on property ownership rights.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Income earned during a marriage is community property, and any property purchased with community property—such as the insurance policy on Matt’s life—is considered to be <b>community </b>property, not separate property.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_071'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_072';
objQuestion.questionID = 117037;
objQuestion.item = 'LOMA_311_PPQ2020_072';
objQuestion.primaryLO = '6D';
objQuestion.textref = 'c. 6, p. 9';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '6D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about typical formalities required in the United States to create a valid will. Select the answer choice containing the correct statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "In all states, a valid will can be in either written or oral form.";
arrAnsChoices[1] = "A will generally must be signed by competent witnesses in the presence of the person who made the will.";
arrAnsChoices[2] = "A person generally need not understand the nature and character of the property he owns in order to make a valid will.";
arrAnsChoices[3] = "A person of any age generally can execute a valid will.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473218;
arrAnsIDs[1] = 473219;
arrAnsIDs[2] = 473220;
arrAnsIDs[3] = 473221;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">In order to be considered valid, a will generally must be <b>in writing</b>.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The testator—the person making the will—must sign the will in the presence of competent witnesses or must attest to the witnesses that it is his signature. Those witnesses must then sign the will in the presence of the testator. Other general requirements include that the will must be in writing and that the testator must have testamentary capacity.</p><p class=\"explanations\"><b>Learning Objective: 6D. Explain how property is distributed when the property owner dies with a valid will and when the property owner dies without a valid will.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A person generally must be of sound mind in order to have the legal capacity to make a will. For the purposes of making a will, one requirement of having a sound mind is the ability to understand the nature and character of the property owned.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">In order to create a valid will, the person making the will must have the legal capacity, or testamentary capacity, to make the will. As a general rule, a person must <b>attain a stated age</b>, typically 18, and be of sound mind in order to have testamentary capacity.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_072'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_073';
objQuestion.questionID = 117038;
objQuestion.item = 'LOMA_311_PPQ2020_073';
objQuestion.primaryLO = '6E';
objQuestion.textref = 'c. 6, pp. 9-10';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '6E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Albert Tillman, a United States resident, died without a valid will. The probate court appointed Sidney Balleu as the person who is responsible for settling Mr.&nbsp;Tillman’s estate. Select the answer choice that correctly identifies whether Mr.&nbsp;Tillman died testate or intestate and the role of Ms.&nbsp;Balleu with respect to Mr.&nbsp;Tillman’s estate.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[-1] = "<u>Mr.&nbsp;Tillman</u></div><div class=\"anshead\"><u>Ms.&nbsp;Balleu</u>";
arrAnsChoices[0] = "testate</div><div class=\"anscell\" onclick=\"recordAns(1);\">administrator";
arrAnsChoices[1] = "testate</div><div class=\"anscell\" onclick=\"recordAns(2);\">executor";
arrAnsChoices[2] = "intestate</div><div class=\"anscell\" onclick=\"recordAns(3);\">administrator";
arrAnsChoices[3] = "intestate</div><div class=\"anscell\" onclick=\"recordAns(4);\">executor";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473223;
arrAnsIDs[1] = 473224;
arrAnsIDs[2] = 473225;
arrAnsIDs[3] = 473226;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that Ms.&nbsp;Balleu was appointed as the administrator to settle Mr.&nbsp;Tillman’s estate. However, in the United States, a person who dies with a valid will is said to die testate. Mr.&nbsp;Tillman did not have a valid will.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">In the United States, a person who dies with a valid will is said to die testate. The personal representative appointed by the probate court is known as an executor when a decedent dies with a valid will. Mr.&nbsp;Tillman did not have a valid will; therefore, he did <b>not</b> die testate and it is incorrect to identify Ms.&nbsp;Balleu as an executor.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Mr.&nbsp;Tillman died intestate, and the personal representative of an intestate’s estate is typically known as an administrator. Ms.&nbsp;Balleu’s responsibilities as administrator of Mr.&nbsp;Tillman’s estate include collecting and completing an inventory of Mr.&nbsp;Tillman’s property, filing any required income tax returns, collecting all debts owed to Mr.&nbsp;Tillman, and paying all outstanding debts owed by him.</p><p class=\"explanations\"><b>Learning Objective: 6E. Interpret the probate process and identify the roles that people play in administering an estate.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that Mr.&nbsp;Tillman died intestate—that is, without a valid will. However, the personal representative is known as an executor when a decedent dies with a valid will; therefore, it is incorrect to identify Ms.&nbsp;Balleu as an executor.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_073'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_074';
objQuestion.questionID = 117039;
objQuestion.item = 'LOMA_311_PPQ2020_074';
objQuestion.primaryLO = '6F';
objQuestion.textref = 'c. 6, pp. 11-12';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '6F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">One true statement about copyrights in the United States is that</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "an employee is the owner of the copyright of a work completed in a work-for-hire arrangement";
arrAnsChoices[1] = "a copyright prohibits others from using portions of a copyrighted work for any reason";
arrAnsChoices[2] = "a copyright granted in the United States is enforceable throughout the world";
arrAnsChoices[3] = "copyright protection attaches when a work is created";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473227;
arrAnsIDs[1] = 473228;
arrAnsIDs[2] = 473229;
arrAnsIDs[3] = 473230;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Under U.S. federal copyright laws, the author or creator of a work owns the work unless it was created as a work for hire. A work for hire is a work prepared (1) by an employee within the course of his employment or (2) as a result of an agreement of the parties that it is a work for hire. The employer, <b>not </b>the employee, is the owner of the copyright of a work for hire.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">For works created after January 1, 1978, an author or originator has copyright protection in a work for his lifetime and for 70 years thereafter. However, a copyright does not grant unlimited ownership rights. The primary limitation on these rights is the fair use doctrine, which is a legal doctrine that permits others to use <b>limited </b>portions of a copyrighted work for purposes such as criticism, comment, news reporting, teaching, scholarship, or research.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A copyright granted under a given jurisdiction’s laws is enforceable only within that jurisdiction. For example, an author who publishes a novel in the United States and several other countries is granted a separate copyright in each<b> </b>country.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Because U.S. copyright protection attaches when a work is created, an author or originator does not need to take special actions to protect the work. However, the copyright holder is required to register her copyright before she can file a lawsuit for copyright infringement—the violation of the exclusive rights that belong to the owner of the intellectual property.</p><p class=\"explanations\"><b>Learning Objective: 6F. Distinguish between copyrights, patents, and trademarks or service marks, and explain how the owner of intellectual property can protect his rights in the property.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_074'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_075';
objQuestion.questionID = 117040;
objQuestion.item = 'LOMA_311_PPQ2020_075';
objQuestion.primaryLO = '6F';
objQuestion.textref = 'c. 6, p. 13';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '6F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">One true statement about patents is that a patent</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "obtained in the United States is automatically effective in the United States and in any other country in which that product is sold";
arrAnsChoices[1] = "attaches when an invention is created and no special action is required for an inventor to protect the work";
arrAnsChoices[2] = "generally is obtained through an inexpensive process that takes very little time to complete";
arrAnsChoices[3] = "typically is granted for a period of 20 years from the date the patent application was filed with the U.S. Patent and Trademark Office (USPTO)";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473231;
arrAnsIDs[1] = 473232;
arrAnsIDs[2] = 473233;
arrAnsIDs[3] = 473234;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Like copyrights, a patent generally is effective only <b>within the country </b>that granted the patent. To eliminate the potential time and expense of having to file multiple patent applications in several different countries, the Patent Cooperation Treaty (PCT) provides a method of obtaining international patent protection in more than 110 countries that have signed the treaty. </p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Unlike copyrights, which attach upon the creation of the work, a patent is effective only after the applicable government agency acts on an application<b> </b>for a patent. In the United States, the federal government has authority to issue patents, and federal laws specify the requirements an invention must meet to receive a patent.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Obtaining a patent is an <b>expensive and time-consuming</b> process that usually takes several years.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">In the United States, a patent gives its owner the right to exclude others from making, using, selling, offering to sell, or importing the patented invention during the 20-year term of the patent. Anyone who makes, uses, sells, offers to sell, or imports a patented invention within the United States during the term of the patent without permission from the patent owner has infringed the patent.</p><p class=\"explanations\"><b>Learning Objective: 6F. Distinguish between copyrights, patents, and trademarks or service marks, and explain how the owner of intellectual property can protect his rights in the property.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_075'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_076';
objQuestion.questionID = 117041;
objQuestion.item = 'LOMA_311_PPQ2020_076';
objQuestion.primaryLO = '6F';
objQuestion.textref = 'c. 6, p. 14';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '6F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Jade Company, a United States company, created a mark, “StoneCare,” to identify its jewelry cleaning product and to distinguish it from other products. Jade applied to register its mark with the U.S. Patent and Trademark Office (USPTO), and the USPTO subsequently approved Jade’s application. Select the answer choice that correctly identifies whether StoneCare is a trademark or a service mark and the length of time that Jade’s initial registration of StoneCare will remain in force.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[-1] = "<u>Type of mark</u></div><div class=\"anshead\"><u>Length of registration</u>";
arrAnsChoices[0] = "trademark</div><div class=\"anscell\" onclick=\"recordAns(1);\">10 years";
arrAnsChoices[1] = "trademark</div><div class=\"anscell\" onclick=\"recordAns(2);\">20 years";
arrAnsChoices[2] = "service mark</div><div class=\"anscell\" onclick=\"recordAns(3);\">10 years";
arrAnsChoices[3] = "service mark</div><div class=\"anscell\" onclick=\"recordAns(4);\">20 years";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473236;
arrAnsIDs[1] = 473237;
arrAnsIDs[2] = 473238;
arrAnsIDs[3] = 473239;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A trademark identifies and distinguishes the source of one party’s goods from those of other parties, whereas a service mark is used to identify and distinguish the source of a service. StoneCare can correctly be described as a trademark because it identifies and distinguishes the source of Jade’s jewelry cleaning product—a good—from the goods of other parties. Also, a U.S. trademark registration generally remains in force for 10 years. Registrations can be renewed for additional 10-year periods by paying the applicable fee and filing with the USPTO an affidavit attesting to the registrant’s continuing use of the mark.</p><p class=\"explanations\"><b>Learning Objective: 6F. Distinguish between copyrights, patents, and trademarks or service marks, and explain how the owner of intellectual property can protect his rights in the property.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that a trademark identifies and distinguishes the source of one party’s goods<i> </i>from those of other parties, whereas a service mark is used to identify and distinguish the source of a service. StoneCare can correctly be described as a trademark because it identifies and distinguishes the source of Jade’s jewelry cleaning product—a good—from the goods of other parties. However, the initial registration of Jade’s trademark on StoneCare is <b>not </b>valid for a period of 20 years.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that a U.S. trademark registration generally remains in force for a period of 10 years. However, StoneCare is <b>not </b>considered to be a service mark, which is a mark that identifies and distinguishes the source of a service, rather than a good.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">StoneCare is <b>not </b>considered to be a service mark, which is a mark that identifies and distinguishes the source of a service, rather than a good. Also, the initial registration of Jade’s trademark on StoneCare is <b>not </b>valid for a period of 20 years.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_076'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_077';
objQuestion.questionID = 117042;
objQuestion.item = 'LOMA_311_PPQ2020_077';
objQuestion.primaryLO = '6G';
objQuestion.textref = 'c. 6, p. 16';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '6G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Article 2 of the Uniform Commercial Code (UCC) most likely would govern a contract for the sale of</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "a stock certificate";
arrAnsChoices[1] = "real estate";
arrAnsChoices[2] = "an insurance policy";
arrAnsChoices[3] = "office furniture";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473240;
arrAnsIDs[1] = 473241;
arrAnsIDs[2] = 473242;
arrAnsIDs[3] = 473243;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Article 2 of the UCC does <b>not </b>apply to contracts involving the sale of intangible property, including stock certificates. The sale of such property is governed by general contract law principles, other Articles of the UCC, or other state and federal laws.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Article 2 of the UCC does <b>not </b>apply to contracts involving the sale of real estate. The sale of such property is governed by general contract law principles, other Articles of the UCC, or other state and federal laws.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Article 2 of the UCC does <b>not </b>apply to contracts involving the sale of intangible property, including insurance policies. The sale of such property is governed by general contract law principles, other Articles of the UCC, or other state and federal laws.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Article 2 of the UCC governs contracts for the sale of goods, or tangible personal property, such as office furniture, office supplies, telephones, and computers. It does not apply to contracts involving the sale of services, real estate, or intangible property, such as stock certificates, bonds, or insurance policies. The sale of such property is governed by general contract law principles, other Articles of the UCC, or other state and federal laws.</p><p class=\"explanations\"><b>Learning Objective: 6G. Describe how Article 2 of the Uniform Commercial Code governs the sale of goods.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_077'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_078';
objQuestion.questionID = 117043;
objQuestion.item = 'LOMA_311_PPQ2020_078';
objQuestion.primaryLO = '6H';
objQuestion.textref = 'c. 6, p. 17';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '6H';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Lydia Black wrote a personal check from her account at the Castle Bank. The check was payable to the order of Amy Leung. Select the answer choice that correctly identifies the party that is the drawee and the party that is the maker in this situation.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[-1] = "<u>Drawee</u></div><div class=\"anshead\"><u>Maker</u>";
arrAnsChoices[0] = "Castle</div><div class=\"anscell\" onclick=\"recordAns(1);\">Ms.&nbsp;Black";
arrAnsChoices[1] = "Castle</div><div class=\"anscell\" onclick=\"recordAns(2);\">Mr.&nbsp;Leung";
arrAnsChoices[2] = "Mr.&nbsp;Leung</div><div class=\"anscell\" onclick=\"recordAns(3);\">Ms.&nbsp;Black";
arrAnsChoices[3] = "Mr.&nbsp;Leung</div><div class=\"anscell\" onclick=\"recordAns(4);\">Castle";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473245;
arrAnsIDs[1] = 473246;
arrAnsIDs[2] = 473247;
arrAnsIDs[3] = 473248;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A check is a draft that instructs a financial institution to pay money from a specific account to a third person. The bank from which the money is to be withdrawn is the drawee, the person who writes the check is the maker or drawer, and the person who is specified to receive the money is the payee.</p><p class=\"explanations\"><b>Learning Objective: 6H. Compare common types of negotiable instruments and identify the four requirements to qualify as a negotiable instrument.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that Castle is the drawee, the bank from which the money for a check is to be withdrawn. However, Mr.&nbsp;Leung is not the maker in this situation. </p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that Ms.&nbsp;Black is the maker in this situation because she is the person who wrote the check. However, Mr.&nbsp;Leung is not the drawee in this situation. </p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Mr.&nbsp;Leung is not the drawee in this situation and Castle is not the maker.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_078'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_079';
objQuestion.questionID = 117044;
objQuestion.item = 'LOMA_311_PPQ2020_079';
objQuestion.primaryLO = '6H';
objQuestion.textref = 'c. 6, p. 17';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '6H';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">One type of negotiable instrument is a certificate of deposit. A certificate of deposit can correctly be defined as</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "a check issued on a financial institution’s own account and backed by the creditworthiness of the institution";
arrAnsChoices[1] = "a check purchased from a financial institution by a consumer, typically to use as a substitute for cash while traveling";
arrAnsChoices[2] = "a type of check that is issued by a financial institution, the U.S. Postal Service, or a retail store and that allows the party named on the check to receive the face amount in cash on demand";
arrAnsChoices[3] = "an instrument containing an acknowledgment by a bank that a sum of money has been received by the bank and a promise by the bank to repay the sum of money";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473249;
arrAnsIDs[1] = 473250;
arrAnsIDs[2] = 473251;
arrAnsIDs[3] = 473252;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">This answer choice describes a <b>cashier’s check</b>, which is a check issued on a financial institution’s own account and backed by the creditworthiness of the institution.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">This answer choice describes a <b>traveler’s check</b>, which is a check purchased from a financial institution by a consumer, typically to use as a substitute for cash while traveling.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">This answer choice describes a <b>money order</b>, which is a type of check issued by a financial institution, the U.S. Postal Service, and some retail stores that allows the party named on the order to receive the face amount in cash on demand.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A certificate of deposit is also a note of the bank. A note is an instrument that is a promise to pay a sum of money. Other examples of negotiable instruments include cashier’s checks, money orders, and traveler’s checks.</p><p class=\"explanations\"><b>Learning Objective: 6H. Compare common types of negotiable instruments and identify the four requirements to qualify as a negotiable instrument.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_079'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_080';
objQuestion.questionID = 117045;
objQuestion.item = 'LOMA_311_PPQ2020_080';
objQuestion.primaryLO = '6H';
objQuestion.textref = 'c. 6, pp. 17-18';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '6H';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">For this question, if answer choices (1) through (3) are all correct, select answer choice (4). Otherwise, select the one correct answer choice.</p><p class=\"stem\">The basic requirements that an instrument must meet to qualify as a negotiable instrument include</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "that the instrument must be in writing and signed by its maker";
arrAnsChoices[1] = "that the instrument must contain an unconditional promise to pay or an unconditional order to pay, and the amount promised or ordered to be paid must be a fixed amount of money";
arrAnsChoices[2] = "that the instrument must be payable on demand or at a definite time";
arrAnsChoices[3] = "all of the above";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473253;
arrAnsIDs[1] = 473254;
arrAnsIDs[2] = 473255;
arrAnsIDs[3] = 473256;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that the instrument must be in writing and signed by its maker. However, this is not<b> </b>the only correct response.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that the instrument must contain an unconditional promise or order to pay and that the amount must be a fixed amount of money. However, this is not<b> </b>the only correct response.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that the instrument must be payable on demand or at a definite time. However, this is not<b> </b>the only correct response.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">To be negotiable, an instrument must meet the four basic requirements described in the answer choices. Note that two of these requirements are combined in answer choice (2).</p><p class=\"explanations\"><b>Learning Objective: 6H. Compare common types of negotiable instruments and identify the four requirements to qualify as a negotiable instrument.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_080'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_081';
objQuestion.questionID = 117046;
objQuestion.item = 'LOMA_311_PPQ2020_081';
objQuestion.primaryLO = '6I';
objQuestion.textref = 'c. 6, pp. 18-19';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '6I';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Jasmine Decker wrote a check payable to the order of “David and Nicole Wim.” The check was written for $85, but the amount written out on the check said “seventy-five dollars.” One true statement about this situation is</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "that the check is bearer paper";
arrAnsChoices[1] = "that the check can be indorsed by either David or Nicole in order to be negotiated";
arrAnsChoices[2] = "that, according to Article 3 of the UCC, the check is payable for $75";
arrAnsChoices[3] = "that, according to Article 3 of the UCC, the check is not a valid instrument because of its contradictory terms";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473257;
arrAnsIDs[1] = 473258;
arrAnsIDs[2] = 473259;
arrAnsIDs[3] = 473260;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Bearer paper is an instrument that is payable to bearer and is negotiable by the holder without having to be signed by a specific payee. The check that Ms.&nbsp;Decker wrote is <b>order paper</b>, which is an instrument that is payable to the order of a specific payee and that must be indorsed by the named payee in order to be negotiable.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">An instrument made payable to two parties jointly, such as “David and Nicole Wim,” must be signed by <b>both</b> parties. By contrast, an instrument made payable to “David <b>or </b>Nicole Wim” could be negotiated if indorsed by either David or Nicole.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">According to Article 3 of the UCC, the words on a negotiable instrument prevail over numbers on the instrument. Therefore, the check that Ms.&nbsp;Decker wrote would be payable for $75, rather than $85.</p><p class=\"explanations\"><b>Learning Objective: 6I. Identify ways in which an instrument can be indorsed in the United States.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Article 3 of the UCC does not state that a negotiable instrument that contains contradictory terms is an invalid instrument. Instead, Article 3 specifies which terms prevail<b> </b>in the event that a negotiable instrument contains contradictory terms.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_081'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_082';
objQuestion.questionID = 117047;
objQuestion.item = 'LOMA_311_PPQ2020_082';
objQuestion.primaryLO = '6I';
objQuestion.textref = 'c. 6, p. 20';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '6I';
arrLOs[1] = '6J';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Daniel York received a check in the amount of $150 made payable to him. Mr.&nbsp;York indorsed the check with his signature and the notation “payable to the order of Natalia Henning.” Mr.&nbsp;York then gave the check to Ms.&nbsp;Henning as payment for a debt that he owed her. Ms.&nbsp;Henning accepted the check in good faith and without knowledge of defenses or claims against its payment. True statements about this situation include</p><ol type=\"A\" class=\"combo\"><li>That Mr.&nbsp;York indorsed the check using a restrictive indorsement</li><li>That Ms.&nbsp;Henning is a holder in due course</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473261;
arrAnsIDs[1] = 473262;
arrAnsIDs[2] = 473263;
arrAnsIDs[3] = 473264;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is incorrect. Mr.&nbsp;York used a <b>special indorsement</b>, rather than a restrictive indorsement, to indorse the check. A special indorsement indicates to whom the instrument should be paid, whereas a restrictive indorsement indicates how the instrument can be used.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is correct. Ms.&nbsp;Henning can correctly be described as a holder in due course—the holder of a negotiable instrument who (1) paid value for the instrument, (2) obtained it in good faith, and (3) obtained it without knowledge of defenses or claims against its payment.</p><p class=\"explanations\">Statement A is incorrect. Mr.&nbsp;York used a <b>special indorsement</b>, rather than a restrictive indorsement, to indorse the check. A special indorsement indicates to whom the instrument should be paid, whereas a restrictive indorsement indicates how the instrument can be used.</p><p class=\"explanations\"><b>Learning Objectives: (1) 6I. Identify ways in which an instrument can be indorsed in the United States; (2) 6J. Analyze the requirements that qualify the holder of a negotiable instrument as a holder in due course.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_082'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_083';
objQuestion.questionID = 117048;
objQuestion.item = 'LOMA_311_PPQ2020_083';
objQuestion.primaryLO = '6K';
objQuestion.textref = 'c. 6, pp. 22-23';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '6K';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about the parties who have liabilities under a negotiable instrument in a given situation. Three statements are true, and one statement is false. Select the answer choice containing the <B>FALSE </B>statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "The maker of a note has primary liability to pay the note.";
arrAnsChoices[1] = "The acceptor of a draft or note generally is liable when the instrument is made payable to a fictitious payee.";
arrAnsChoices[2] = "By accepting a check, a bank becomes liable to pay the stated amount on the check.";
arrAnsChoices[3] = "When several people indorse a negotiable instrument, they are liable to each other in the reverse order in which they indorsed the instrument.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473265;
arrAnsIDs[1] = 473266;
arrAnsIDs[2] = 473267;
arrAnsIDs[3] = 473268;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">This is a true statement; therefore, it is <b>not</b> the correct response.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">This is a false statement; therefore, it is the correct response. The <b>maker </b>of an instrument generally is liable when the instrument is made payable to a fictitious payee. A typical example of such a case occurs when a dishonest employee manages to get possession of a check drawn on the employer’s account, indorses the check by forging a signature, and negotiates the check.</p><p class=\"explanations\"><b>Learning Objective: 6K. Identify the parties who have liability under a negotiable instrument in a given situation.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">This is a true statement; therefore, it is <b>not</b> the correct response.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">This is a true statement; therefore, it is <b>not</b> the correct response.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_083'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_084';
objQuestion.questionID = 117049;
objQuestion.item = 'LOMA_311_PPQ2020_084';
objQuestion.primaryLO = '6L';
objQuestion.textref = 'c. 6, pp. 25-26';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '6L';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">When the Valley Manufacturing Company wanted to purchase new machinery, Valley obtained a loan from the Dial Finance Company to fund the purchase. In return for the loan, Dial received an interest in Valley’s machinery as a way to guarantee that Dial would be protected if Valley defaults on the loan. Once the loan process was complete, Dial filed with a specified government official a document that was signed by Valley and that contained both Valley’s and Dial’s names and addresses and a description of the machinery that was attached to the debt. Select the answer choice that correctly identifies whether this credit transaction is an unsecured transaction or a secured transaction and the type of document that Dial filed with the government official.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[-1] = "<u>Type of transaction</u></div><div class=\"anshead\"><u>Type of document filed</u>";
arrAnsChoices[0] = "unsecured transaction</div><div class=\"anscell\" onclick=\"recordAns(1);\">security agreement";
arrAnsChoices[1] = "unsecured transaction</div><div class=\"anscell\" onclick=\"recordAns(2);\">financing statement";
arrAnsChoices[2] = "secured transaction</div><div class=\"anscell\" onclick=\"recordAns(3);\">security agreement";
arrAnsChoices[3] = "secured transaction</div><div class=\"anscell\" onclick=\"recordAns(4);\">financing statement";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473270;
arrAnsIDs[1] = 473271;
arrAnsIDs[2] = 473272;
arrAnsIDs[3] = 473273;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">An unsecured transaction is a credit transaction in which a creditor extends credit and receives only the debtor’s promise to pay the debt. In this situation, the fact that Dial received a security interest in Valley’s machinery means that this transaction is <b>not </b>an unsecured transaction. Also, a security agreement is a contractual agreement in which the debtor gives the creditor a security interest in specific property that is identifiable. A security agreement is <b>not </b>filed with a government official.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that the document that Dial filed with the government official is a financing statement. However, this transaction is <b>not </b>an example of an unsecured transaction, which is a credit transaction in which a creditor extends credit and receives only the debtor’s promise to pay the debt. In this situation, Dial received a security interest in Valley’s machinery.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that this transaction is a secured transaction because Dial received a security interest in Valley’s machinery. However, a security agreement is a contractual agreement in which the debtor gives the creditor a security interest in specific property that is identifiable. A security agreement is <b>not </b>filed with a government official.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The transaction in this situation is a secured transaction because Dial received a security interest in Valley’s machinery. A creditor who obtains a security interest in a debtor’s property is referred to as a secured party. In order to perfect its security interest in Valley’s machinery, Dial filed a financing statement with the appropriate government official.</p><p class=\"explanations\"><b>Learning Objective: 6L. Distinguish between unsecured and secured credit transactions and describe the two basic requirements that must be met to gain a security interest in personal property.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_084'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_085';
objQuestion.questionID = 117050;
objQuestion.item = 'LOMA_311_PPQ2020_085';
objQuestion.primaryLO = '6M';
objQuestion.textref = 'c. 6, pp. 27-28';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '6M';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">On March 1, the Glenside Corporation obtained a loan from Summit Bank and gave Summit a security interest in some of its property. Summit perfected its security interest in the property on March 15. On May 1, Glenside obtained a loan from Epitome Bank and gave Epitome a security interest in the same property. Epitome perfected its security interest in the property on May 20.</p><p class=\"stem\">When Glenside defaulted on both loans, it owed $15,000 to Summit Bank and $10,000 to Epitome Bank. Summit and Epitome were Glenside’s only creditors. Summit foreclosed on the property, sold the property for $18,000, and incurred $1,000 in foreclosure costs. With regard to the sale of Glenside’s property, it is correct to say that Summit Bank is entitled to receive</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "$8,000 of the proceeds, and Epitome Bank is entitled to receive the remaining $10,000";
arrAnsChoices[1] = "$15,000 of the proceeds, and Epitome Bank is entitled to receive the remaining $3,000";
arrAnsChoices[2] = "$16,000 of the proceeds, and Epitome Bank is entitled to receive the remaining $2,000";
arrAnsChoices[3] = "the entire $18,000";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473274;
arrAnsIDs[1] = 473275;
arrAnsIDs[2] = 473276;
arrAnsIDs[3] = 473277;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The order in which creditors perfected their security interests determines which creditor has priority to the proceeds from the sale of the property. Summit perfected its security interest in Glenside’s property first, so Summit has priority over all other creditors and is entitled to receive full repayment of the unpaid debt from the proceeds from the sale of the property.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that Summit Bank is entitled to receive $15,000 from the proceeds from the sale of foreclosed property to satisfy Glenside’s loan. However, Summit is <b>also </b>entitled to retain the $1,000 it incurred in foreclosure costs. Any remaining proceeds may be paid to Epitome Bank, which perfected its security interest in the Glenside property after Summit perfected its security interest.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The proceeds from a sale of foreclosed property go to pay the expenses incurred in the foreclosure proceeding and to satisfy the debtor’s obligation to the creditor. If any proceeds remain, they may be used to pay other creditors that have a security interest in the property. In this case, Summit—as the first creditor to perfect its security interest—is entitled to receive $15,000 to satisfy the amount of Glenside’s loan. Summit is also entitled to retain the $1,000 in costs it incurred for the foreclosure proceeding. Epitome is entitled to the remaining $2,000 ($18,000 – $15,000 – $1,000) because it also has perfected a security interest in the sold property.</p><p class=\"explanations\"><b>Learning Objective: 6M. Identify the three primary methods of perfecting a security interest and describe the rights that the debtor and the secured party have in property that is subject to a security interest.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Because Summit was the first creditor to perfect a security interest in the property, Summit’s security interest has priority over that of Epitome and all other creditors. However, Summit is <b>not</b> entitled to the entire amount of the proceeds, because Epitome Bank also perfected a security interest in the same property. Summit is entitled to $15,000 to satisfy the amount of Glenside’s unpaid debt and $1,000 to recoup its foreclosure costs. Any remaining proceeds are payable to Epitome.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_085'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['6A'] = "6A. Distinguish between real property and personal property.";
arrlotext['6B'] = "6B. Analyze common methods of acquiring property.";
arrlotext['6C'] = "6C. Identify the various forms of property ownership and restrictions that may be placed on property ownership rights.";
arrlotext['6D'] = "6D. Explain how property is distributed when the property owner dies with a valid will and when the property owner dies without a valid will.";
arrlotext['6E'] = "6E. Interpret the probate process and identify the roles that people play in administering an estate.";
arrlotext['6F'] = "6F. Distinguish between copyrights, patents, and trademarks or service marks, and explain how the owner of intellectual property can protect his rights in the property.";
arrlotext['6G'] = "6G. Describe how Article 2 of the Uniform Commercial Code governs the sale of goods.";
arrlotext['6H'] = "6H. Compare common types of negotiable instruments and identify the four requirements to qualify as a negotiable instrument.";
arrlotext['6I'] = "6I. Identify ways in which an instrument can be indorsed in the United States.";
arrlotext['6J'] = "6J. Analyze the requirements that qualify the holder of a negotiable instrument as a holder in due course.";
arrlotext['6K'] = "6K. Identify the parties who have liability under a negotiable instrument in a given situation.";
arrlotext['6L'] = "6L. Distinguish between unsecured and secured credit transactions and describe the two basic requirements that must be met to gain a security interest in personal property.";
arrlotext['6M'] = "6M. Identify the three primary methods of perfecting a security interest and describe the rights that the debtor and the secured party have in property that is subject to a security interest.";
