var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2020';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 311 Practice Questions, Chapter 3";
var coursename = 'LOMA 311';
var modulenumber = 1;
var title = "LOMA_311_PPQ2020_0_3";
var intNumPools = 1;
var numQ = 16;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Business Law for Insurance Professionals (2020)";
arrNumChap[0] = 1;
var thisChap = '3';

objPool = new Object(); 
objPool.intSelectCount = 16;
objPool.formID = 2380;
objPool.formName = 'PPQ2020_0_3';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_311_PQ_023';
arrPoolQuestions[1] = 'LOMA_311_PQ_024';
arrPoolQuestions[2] = 'LOMA_311_PQ_025';
arrPoolQuestions[3] = 'LOMA_311_PQ_026';
arrPoolQuestions[4] = 'LOMA_311_PQ_027';
arrPoolQuestions[5] = 'LOMA_311_PQ_028';
arrPoolQuestions[6] = 'LOMA_311_PQ_029';
arrPoolQuestions[7] = 'LOMA_311_PQ_030';
arrPoolQuestions[8] = 'LOMA_311_PQ_031';
arrPoolQuestions[9] = 'LOMA_311_PQ_032';
arrPoolQuestions[10] = 'LOMA_311_PQ_033';
arrPoolQuestions[11] = 'LOMA_311_PQ_034';
arrPoolQuestions[12] = 'LOMA_311_PQ_035';
arrPoolQuestions[13] = 'LOMA_311_PQ_036';
arrPoolQuestions[14] = 'LOMA_311_PQ_037';
arrPoolQuestions[15] = 'LOMA_311_PQ_038';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_023';
objQuestion.questionID = 116988;
objQuestion.item = 'LOMA_311_PPQ2020_023';
objQuestion.primaryLO = '3A';
objQuestion.textref = 'c. 3, p. 4';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statement(s) can correctly be made about the characteristics of a corporation:</p><ol type=\"A\" class=\"combo\"><li>A corporation is a legal entity that is created by the authority of a governmental unit, such as a state or nation.</li><li>The owners of a corporation are personally responsible for the corporation’s debts.</li><li>A corporation continues beyond the death of any or all of its owners.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A, B, and C";
arrAnsChoices[1] = "A and B only";
arrAnsChoices[2] = "A and C only";
arrAnsChoices[3] = "C only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473017;
arrAnsIDs[1] = 473018;
arrAnsIDs[2] = 473019;
arrAnsIDs[3] = 473020;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct. However, Statement B is incorrect. The corporation’s debts and liabilities belong to the corporation itself. The owners are <b>not</b> personally responsible for the corporation’s debts.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Both Statements A and C are correct. Unlike sole proprietorships and partnerships, corporations are created by government action. A corporation continues beyond the death of any or all of its owners. This characteristic of corporations provides an element of stability and permanence. Such stability makes the corporation the ideal form of business organization for insurance companies. </p><p class=\"explanations\">Statement B is incorrect. A corporation is a legal entity that is separate from its owners. The corporation’s debts and liabilities belong to the corporation itself. The owners are not personally responsible for the corporation’s debts. Instead, the personal liability of an owner for the corporation’s debts generally is limited to the amount of the owner’s investment in the corporation. </p><p class=\"explanations\"><b>Learning Objective: 3A. Identify the characteristics of a corporation that make it the ideal form of business organization for an insurance company.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Statement C is correct. However, it is not the only correct statement. </p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_023'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_024';
objQuestion.questionID = 116989;
objQuestion.item = 'LOMA_311_PPQ2020_024';
objQuestion.primaryLO = '3B';
objQuestion.textref = 'c. 3, pp. 5-6';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about the typical process of incorporating a business in the United States. Three statements are true, and one statement is false. Select the answer choice containing the <B>FALSE </B>statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "To incorporate a business, a required number of adults usually must file specified documents with a state administrative agency.";
arrAnsChoices[1] = "A corporation’s existence always begins when the articles of incorporation are filed with the state agency.";
arrAnsChoices[2] = "A corporation’s name must include one of the following words or an abbreviation of one of them: <i>corporation, incorporated, company, </i>or <i>limited</i>.";
arrAnsChoices[3] = "A corporation’s articles of incorporation must contain the name of the corporation’s registered agent, who is an individual the corporation has appointed as its agent within the state for purposes of service of process.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473021;
arrAnsIDs[1] = 473022;
arrAnsIDs[2] = 473023;
arrAnsIDs[3] = 473024;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">This is a true statement; therefore, it is <b>not</b> the correct response.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">This is a false statement; therefore, it is the correct response. Unless the articles of incorporation indicate otherwise, the corporation’s existence begins when the articles of incorporation are filed with the state agency.</p><p class=\"explanations\"><b>Learning Objective: 3B. Explain the steps a life insurer must take to do business in the United States.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">This is a true statement; therefore, it is <b>not</b> the correct response.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">This is a true statement; therefore, it is <b>not</b> the correct response.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_024'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_025';
objQuestion.questionID = 116990;
objQuestion.item = 'LOMA_311_PPQ2020_025';
objQuestion.primaryLO = '3C';
objQuestion.textref = 'c. 3, pp. 6-7';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Most countries outside the United States classify insurers as either (<b>close </b>/ <b>domestic</b>) corporations incorporated within the country or (<b>alien </b>/ <b>foreign</b>) corporations incorporated under the laws of another country.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "close / alien";
arrAnsChoices[1] = "close / foreign";
arrAnsChoices[2] = "domestic / alien";
arrAnsChoices[3] = "domestic / foreign";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473025;
arrAnsIDs[1] = 473026;
arrAnsIDs[2] = 473027;
arrAnsIDs[3] = 473028;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Most countries outside the United States do <b>not </b>classify insurers incorporated within the country as close corporations. Also, these countries do <b>not </b>classify insurers incorporated under the laws of another country as alien corporations.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that most countries outside the United States classify insurers incorporated under the laws of another country as foreign corporations. However, these countries do <b>not </b>classify insurers incorporated within the country as close corporations.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that most countries outside the United States classify insurers as domestic corporations if they are incorporated within the country. However, these countries do <b>not </b>classify insurers incorporated under the laws of another country as alien corporations.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">In the United States, a foreign insurer is incorporated under the laws of another state, and an alien insurer is incorporated under the laws of another country. In contrast, most other countries classify insurers as either domestic corporations incorporated within the country or foreign corporations incorporated under the laws of another country.</p><p class=\"explanations\"><b>Learning Objective: 3C. Compare characteristics of corporations in the United States and other countries.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_025'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_026';
objQuestion.questionID = 116991;
objQuestion.item = 'LOMA_311_PPQ2020_026';
objQuestion.primaryLO = '3B';
objQuestion.textref = 'c. 3, p. 8';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The National Association of Insurance Commissioners (NAIC) is a nonprofit association of the insurance commissioners of all U.S. states and territories. The following statement(s) can correctly be made about the NAIC:</p><ol type=\"A\" class=\"combo\"><li>A primary function of the NAIC is to promote uniformity of state regulation by developing model insurance laws and regulations.</li><li>For a state insurance department to be accredited by the NAIC, the state must, among other things, adopt certain laws regarding financial standards and oversight that are substantially similar to those put forth by the NAIC.</li><li>Using the NAIC Uniform Certificate of Authority Application (UCAA), an insurer can submit the same application to all states where it intends to do business.  </li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A, B, and C";
arrAnsChoices[1] = "A and B only";
arrAnsChoices[2] = "A and C only";
arrAnsChoices[3] = "B and C only";
arrAnsChoices[4] = "B only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473029;
arrAnsIDs[1] = 473030;
arrAnsIDs[2] = 473031;
arrAnsIDs[3] = 473032;
arrAnsIDs[4] = 473033;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">All the statements are correct. Although insurance laws vary by state, some uniformity exists because many state laws are based on NAIC model laws. A state’s NAIC accreditation is important for insurers domiciled in that state because it allows insurance departments in other states where the insurer operates to rely on the domiciliary state’s oversight as primary. Although an insurer does not have to submit a different application to each insurance department, the specific requirements for a certificate of authority vary by state. </p><p class=\"explanations\"><b>Learning Objective: 3B. Explain the steps a life insurer must take to do business in the United States.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statements A and B are correct. However, Statement C is also correct.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statements A and C are correct. However, Statement B is also correct.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Statements B and C are correct. However, Statement A is also correct.</p>";
arrAnswerFeedback[4] = "<p class=\"explanations\">Statement B is correct, but it is not the only correct response. </p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_026'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_027';
objQuestion.questionID = 116992;
objQuestion.item = 'LOMA_311_PPQ2020_027';
objQuestion.primaryLO = '3C';
objQuestion.textref = 'c. 3, pp. 8-9';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Business organizations around the world, which generally are known as corporations or companies, depending on the jurisdiction, have many characteristics in common with U.S. corporations. One common characteristic of corporations around the world is that, in the United States and in other countries,</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "most types of corporations must meet minimum capital requirements";
arrAnsChoices[1] = "corporations have a life of only a specific number of years";
arrAnsChoices[2] = "a corporation’s owners are responsible for managing the affairs for the business";
arrAnsChoices[3] = "a corporation has the legal rights and liabilities of a natural person";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473034;
arrAnsIDs[1] = 473035;
arrAnsIDs[2] = 473036;
arrAnsIDs[3] = 473037;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Some countries do impose minimum capital requirements for all corporations. In the United States, insurance and financial services companies must meet minimum capital requirements; however, most other types of U.S. businesses are not subject to such requirements.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">In some countries, a business has a life of only a specific number of years. In most jurisdictions, however, a corporation continues to exist beyond the death of its owners.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A corporation’s <b>board of directors</b> is responsible for managing the affairs of the business.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A corporation exists as a legal entity that is separate from its owners, and it has the legal rights and liabilities of a natural person, including the right to sue and be sued and the right to own property.</p><p class=\"explanations\"><b>Learning Objective: 3C. Compare characteristics of corporations in the United States and other countries.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_027'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_028';
objQuestion.questionID = 116993;
objQuestion.item = 'LOMA_311_PPQ2020_028';
objQuestion.primaryLO = '3D';
objQuestion.textref = 'c. 3, pp. 9-10, 16';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3D';
arrLOs[1] = '3F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Forte Corporation, a financial services company, purchased a controlling interest in the Lakeside Insurance Company, and this transaction resulted in a linkage between Forte and Lakeside. After the transaction, Forte and Lakeside both still existed as separate legal entities. Select the answer choice that correctly identifies whether this transaction is an example of a joint venture or an acquisition and whether the insurance department of Lakeside’s domiciliary state most likely was required to approve this transaction.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[-1] = "<u>Joint venture or acquisition?</u></div><div class=\"anshead\"><u>Approval of state insurance department required?</u>";
arrAnsChoices[0] = "joint venture</div><div class=\"anscell\" onclick=\"recordAns(1);\">yes";
arrAnsChoices[1] = "joint venture</div><div class=\"anscell\" onclick=\"recordAns(2);\">no";
arrAnsChoices[2] = "acquisition</div><div class=\"anscell\" onclick=\"recordAns(3);\">yes";
arrAnsChoices[3] = "acquisition</div><div class=\"anscell\" onclick=\"recordAns(4);\">no";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473039;
arrAnsIDs[1] = 473040;
arrAnsIDs[2] = 473041;
arrAnsIDs[3] = 473042;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that the insurance department of Lakeside’s domiciliary state most likely was required to approve this transaction. However, the transaction between Forte and Lakeside is <b>not </b>an example of a joint venture, which is an arrangement between two or more otherwise independent businesses that agree to undertake a specific project together for a specified time period.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The transaction between Forte and Lakeside is <b>not </b>an example of a joint venture, which is an arrangement between two or more otherwise independent businesses that agree to undertake a specific project together for a specified time period. In addition, the insurance department of Lakeside’s domiciliary state most likely <b>was required</b> to approve this transaction.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The transaction between Forte and Lakeside is an example of an acquisition, which is a transaction in which one corporation purchases a controlling interest in another corporation, resulting in a linkage between formerly independent corporations. A transaction in which one entity will either acquire or merge with an insurer usually requires the approval of the insurance department of the insurer’s domiciliary state.</p><p class=\"explanations\"><b>Learning Objective: (1) 3D. Define a multinational corporation and describe ways in which companies can operate in a foreign country; (2) 3F. Identify methods by which corporations can change their corporate structures.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that the transaction between Forte and Lakeside is an example of an acquisition, which is a transaction in which one corporation purchases a controlling interest in another corporation, resulting in a linkage between formerly independent corporations. However, the insurance department of Lakeside’s domiciliary state most likely <b>was required</b> to approve this transaction.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_028'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_029';
objQuestion.questionID = 116994;
objQuestion.item = 'LOMA_311_PPQ2020_029';
objQuestion.primaryLO = '3E';
objQuestion.textref = 'c. 3, pp. 14-15';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following individuals are involved in the management of the Dogwood Corporation, a United States company:</p><ul class=\"examul\"><li>Sandra Davis, a member of Dogwood’s board of directors, was found to have abused her discretion as a board member</li><li>Mike Bright, the president of Dogwood, was found to have knowingly failed to fulfill legal duties to Dogwood</li></ul><p class=\"stem\">With regard to whether a U.S. court would be likely to apply the business judgment rule to these two individuals, it is correct to say that the business judgment rule would likely apply to</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "both Ms.&nbsp;Davis and Mr.&nbsp;Bright";
arrAnsChoices[1] = "Ms.&nbsp;Davis only";
arrAnsChoices[2] = "Mr.&nbsp;Bright only";
arrAnsChoices[3] = "neither Ms.&nbsp;Davis nor Mr.&nbsp;Bright";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473043;
arrAnsIDs[1] = 473044;
arrAnsIDs[2] = 473045;
arrAnsIDs[3] = 473046;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The business judgment rule does not apply to at least one of these individuals.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Corporate directors generally <b>will </b>be personally liable if they act in bad faith, abuse their discretion, are guilty of gross negligence, or commit fraud. Because Ms.&nbsp;Davis abused her discretion, a U.S. court would <b>not</b> be likely to apply the business judgment rule to her.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Officers of corporations generally are <b>not </b>afforded protection under the business judgment rule. Therefore, a U.S. court would not apply the business judgment rule to Mr.&nbsp;Bright.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The business judgment rule states that directors will not be held personally liable for making business decisions if there is a reasonable basis to believe that the directors acted in good faith and with due care. On the other hand, corporate directors generally will<b> </b>be personally liable if they act in bad faith, abuse their discretion, are guilty of gross negligence, or commit fraud. Because Ms.&nbsp;Davis abused her discretion, a U.S. court would not be likely to apply the business judgment rule to her. Officers of corporations are not<b> </b>afforded protection under the business judgment rule. Therefore, a U.S. court would not apply the business judgment rule to Mr.&nbsp;Bright because he is an officer of Dogwood.</p><p class=\"explanations\"><b>Learning Objective: 3E. Compare the three primary groups of people who are involved in the management of a corporation and explain each group’s legal rights and duties.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_029'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_030';
objQuestion.questionID = 116995;
objQuestion.item = 'LOMA_311_PPQ2020_030';
objQuestion.primaryLO = '3G';
objQuestion.textref = 'c. 3, p. 19';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">In the United States, all states have enacted laws to regulate holding company systems that include insurance companies. The following statement(s) can correctly be made about the requirements of these state insurance holding company laws:</p><ol type=\"A\" class=\"combo\"><li>To date, these laws do not impose limits on the amount that an insurer may invest in subsidiaries.</li><li>Transactions between companies affiliated with an insurer must be reported to the insurance department of the insurer’s domiciliary state.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473047;
arrAnsIDs[1] = 473048;
arrAnsIDs[2] = 473049;
arrAnsIDs[3] = 473050;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is incorrect. To protect insurers’ financial stability, state insurance holding company laws <b>impose</b> limits on the amount that an insurer may invest in subsidiaries.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is correct. A state insurance department will disapprove a transaction if the terms of the transaction are unreasonable or would threaten the insurer’s finances and ability to pay policy benefits. State insurance holding company laws also require that the insurance department of an insurer’s domiciliary state approve any transaction in which an entity will acquire control of the insurer or will merge with the insurer.</p><p class=\"explanations\">Statement A is incorrect. To protect insurers’ financial stability, state insurance holding company laws impose limits on the amount that an insurer may invest in subsidiaries.</p><p class=\"explanations\"><b>Learning Objective: 3G. Explain U.S. federal antitrust laws and the types of activities they typically prohibit, and compare U.S. federal antitrust laws to antitrust laws in other countries.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_030'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_031';
objQuestion.questionID = 116996;
objQuestion.item = 'LOMA_311_PPQ2020_031';
objQuestion.primaryLO = '3G';
objQuestion.textref = 'c. 3, p. 20';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">For any given product, the market operates somewhere on a continuum that ranges from pure competition to pure monopoly. The following statement(s) can correctly be made about pure competition and pure monopoly:</p><ol type=\"A\" class=\"combo\"><li>In theory, pure competition results in the production of the greatest output of a product at the lowest price.</li><li>Under a monopoly, prices tend to increase and producers are less responsive to consumer demand.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473051;
arrAnsIDs[1] = 473052;
arrAnsIDs[2] = 473053;
arrAnsIDs[3] = 473054;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Both statements are correct. Pure competition means there are many producers and consumers of the product, and prices are established by market forces with not interference from outside economic forces. In reality, no market operates in a state of pure competition. In a monopoly, one firm, or a group of firms acting together, controls the production and distribution of a produce. Under a monopoly, there is no competition. </p><p class=\"explanations\"><b>Learning Objective: 3G. Explain U.S. federal antitrust laws and the types of activities they typically prohibit, and compare U.S. federal antitrust laws to antitrust laws in other countries.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct. However, Statement B is also correct.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is correct. However, Statement A is also correct.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct. </p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_031'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_032';
objQuestion.questionID = 116997;
objQuestion.item = 'LOMA_311_PPQ2020_032';
objQuestion.primaryLO = '3G';
objQuestion.textref = 'c. 3, pp. 21, 23';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements describe company practices that may be prohibited by federal antitrust laws in the United States. Select the answer choice that describes a practice known as a <i>tying arrangement</i>.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "The Vista Company uses volume discounts as a basis for selling the same goods at different prices to different buyers.";
arrAnsChoices[1] = "The Crystal Company agreed to sell one of its products to the Prism Company only if Prism also bought a second different product from Willow.";
arrAnsChoices[2] = "The Pluto Company and its competitor, the Neptune Company, participated in a concerted effort in which they agreed not to do business with the Sope Company.";
arrAnsChoices[3] = "The Penhurst Company and its competitor, the Woodlawn Company, entered into an agreement to eliminate competitive bidding.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473055;
arrAnsIDs[1] = 473056;
arrAnsIDs[2] = 473057;
arrAnsIDs[3] = 473058;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Vista is practicing a form of <b>price discrimination</b>, which occurs when a seller agrees to sell goods to a buyer at a price that is lower than the price charged other buyers. However, a seller is not violating antitrust laws it if enters into price agreements administered fairly and in an otherwise nondiscriminatory fashion. For example, a seller has the right to give volume discounts to buyers.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Crystal’s agreement with Prism is a tying arrangement, which is an illegal arrangement under which a company will sell one of its products to a purchaser only if the purchaser also buys a second, different product from the company.</p><p class=\"explanations\"><b>Learning Objective: 3G. Explain U.S. federal antitrust laws and the types of activities they typically prohibit, and compare U.S. federal antitrust laws to antitrust laws in other countries.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Pluto and Neptune participated in a <b>boycott</b>, which occurs when competitors agree not to do business with another business.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The agreement between Penhurst and Woodlawn is an example of a <b>price-fixing agreement</b>, which also is a per se violation of antitrust laws. Price fixing occurs when competitors act together to affect the price of a product or service.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_032'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_033';
objQuestion.questionID = 116998;
objQuestion.item = 'LOMA_311_PPQ2020_033';
objQuestion.primaryLO = '3G';
objQuestion.textref = 'c. 3, p. 22';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statement(s) can correctly be made about activities that may violate federal antitrust laws in the United States:</p><ol type=\"A\" class=\"combo\"><li>A monopoly is an example of a per se violation of federal antitrust laws.</li><li>When courts perform a rule of reason analysis to evaluate a potential violation of antitrust laws, they evaluate the overall competitive effect of the parties’ conduct and weigh the competitive harm against the competitive benefits.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473059;
arrAnsIDs[1] = 473060;
arrAnsIDs[2] = 473061;
arrAnsIDs[3] = 473062;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is incorrect. The courts have identified certain activities that are so harmful to consumers that they are conclusively presumed to violate the antitrust laws. Such prohibited activities are referred to as per se violations. However, because a monopoly is not always illegal, it is not an example of a per se violation of antitrust laws. For example, a business that gained monopoly power through fair competition and legitimate tactics has not violated the antitrust laws. </p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is correct. Federal antitrust laws are written in very broad terms. They allow the courts to decide what specific activities are illegal based on the facts and circumstances of each case. The courts have identified certain activities that are so harmful to consumers that they are conclusively presumed to violate the antitrust laws. Such prohibited activities are referred to as per se violations. The courts evaluate all cases that are not per se violations under a rule of reason analysis, which evaluates the overall competitive effect of the parties’ conduct and weighs the competitive harm against the competitive benefits.</p><p class=\"explanations\">Statement A is incorrect. Because a monopoly is not always illegal, it is not an example of a per se violation of antitrust laws. For example, a business that gained monopoly power through fair competition and legitimate tactics has not violated the antitrust laws. </p><p class=\"explanations\"><b>Learning Objective: 3G. Explain U.S. federal antitrust laws and the types of activities they typically prohibit, and compare U.S. federal antitrust laws to antitrust laws in other countries.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_033'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_034';
objQuestion.questionID = 116999;
objQuestion.item = 'LOMA_311_PPQ2020_034';
objQuestion.primaryLO = '3G';
objQuestion.textref = 'c. 3, p. 23';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Federal Trade Commission (FTC) and the Department of Justice (DOJ) have each developed expertise in overseeing certain industries and businesses in the United States. One true statement about the regulatory authority of the FTC and the DOJ is that</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "antitrust issues are prosecuted through the FTC and the DOJ";
arrAnsChoices[1] = "some types of proposed mergers and acquisitions must be reported to both the FTC and the DOJ before the parties complete the proposed transaction";
arrAnsChoices[2] = "the DOJ is the federal agency that is responsible for enforcing federal consumer protection laws ";
arrAnsChoices[3] = "the FTC is the only federal agency authorized to enforce federal antitrust laws";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473063;
arrAnsIDs[1] = 473064;
arrAnsIDs[2] = 473065;
arrAnsIDs[3] = 473066;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Antitrust issues are prosecuted through the DOJ.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">When the FTC and the DOJ are notified of a proposed merger or acquisition, they have a stated time in which to evaluate the proposed transaction. Their evaluation is aimed at determining whether the transaction would substantially concentrate market power and make it difficult for new firms to enter the market.</p><p class=\"explanations\"><b>Learning Objective: 3G. Explain U.S. federal antitrust laws and the types of activities they typically prohibit, and compare U.S. federal antitrust laws to antitrust laws in other countries.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The <B>FTC</B>, not<b> </b>the DOJ<b>,</b> is the federal agency that is responsible for enforcing federal consumer protection laws.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\"><b>Both</b> the FTC and the DOJ are authorized to enforce federal antitrust laws. The two agencies generally consult before they begin an antitrust investigation and decide which agency will take primary responsibility for handling the case.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_034'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_035';
objQuestion.questionID = 117000;
objQuestion.item = 'LOMA_311_PPQ2020_035';
objQuestion.primaryLO = '3G';
objQuestion.textref = 'c. 3, p. 24';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements compare international antitrust regulation to antitrust regulation in the United States. Select the answer choice containing the correct statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Compared to the United States, other countries generally enforce their antitrust laws more vigorously.";
arrAnsChoices[1] = "Most countries outside the United States impose criminal, but not civil, penalties for violations of their antitrust laws.";
arrAnsChoices[2] = "Countries other than the United States typically attempt to regulate any anticompetitive conduct that affects their commerce, regardless of where such conduct occurs.";
arrAnsChoices[3] = "The antitrust laws of other countries generally prohibit the same types of activities that are prohibited by U.S. antitrust laws.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473067;
arrAnsIDs[1] = 473068;
arrAnsIDs[2] = 473069;
arrAnsIDs[3] = 473070;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">As a general rule, no other country has antitrust laws that are as strict as those in the United States, and the United States more vigorously enforces its antitrust laws than do most other countries.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Violation of most countries’ antitrust laws may lead to fines, but such violations typically are not considered crimes punishable by imprisonment as in the United States.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Anticompetitive conduct that affects U.S. domestic or foreign commerce may violate the U.S. antitrust laws regardless of where such conduct occurs or the nationality of the parties involved. Other countries generally do<b> not</b> try to regulate such conduct when it occurs beyond their own geographic borders.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Most countries outside the United States have enacted antitrust laws. Although the details of antitrust laws vary by jurisdiction, the same types of activities prohibited in the United States generally are prohibited in other countries.</p><p class=\"explanations\"><b>Learning Objective: 3G. Explain U.S. federal antitrust laws and the types of activities they typically prohibit, and compare U.S. federal antitrust laws to antitrust laws in other countries.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_035'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_036';
objQuestion.questionID = 117001;
objQuestion.item = 'LOMA_311_PPQ2020_036';
objQuestion.primaryLO = '3H';
objQuestion.textref = 'c. 3, p. 26';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3H';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Boxwood Insurance Company took the following actions on applications for life insurance based on information it obtained from the applicants’ consumer credit reports:</p><ul class=\"examul\"><li><b>Action A</b>: Boxwood denied life insurance coverage to Odette Lynch.</li><li><b>Action B</b>: Boxwood refused to grant life insurance coverage to Bill Walker in the amount that Mr.&nbsp;Walker applied for.</li></ul><p class=\"stem\">With regard to whether Action A and Action B would be considered adverse actions under the terms of the Fair Credit Reporting Act (FCRA), it is most likely correct to say that an adverse action is described in</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "both Action A and Action B";
arrAnsChoices[1] = "Action A only";
arrAnsChoices[2] = "Action B only";
arrAnsChoices[3] = "neither Action A nor Action B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473071;
arrAnsIDs[1] = 473072;
arrAnsIDs[2] = 473073;
arrAnsIDs[3] = 473074;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The FCRA regulates third parties, such as insurance companies, when they take adverse actions based on information contained in consumer credit reports. According to the FCRA, an adverse action means a denial or revocation of credit or insurance coverage, a change in the terms of an existing credit arrangement or insurance coverage, or a refusal to grant credit or insurance in substantially the amount or on substantially the terms requested. Because Boxwood denied life insurance coverage to Ms.&nbsp;Lynch, Action A is an example of an adverse action. Because Boxwood refused to grant life insurance coverage to Mr.&nbsp;Walker in the amount that he applied for, Action B also is an example of an adverse action.</p><p class=\"explanations\"><b>Learning Objective: 3H. Describe federal consumer protection laws that regulate trade practices.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The FCRA regulates third parties, such as insurance companies, when they take adverse actions based on information contained in consumer credit reports. According to the FCRA, an adverse action means a denial or revocation of credit or insurance coverage, a change in the terms of an existing credit arrangement or insurance coverage, or a refusal to grant credit or insurance in substantially the amount or on substantially the terms requested. Because Boxwood denied life insurance coverage to Ms.&nbsp;Lynch, Action A is an example of an adverse action. However, because Boxwood refused to grant life insurance coverage to Mr.&nbsp;Walker in the amount that he applied for, Action B also <b>is</b> an example of an adverse action.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The FCRA regulates third parties, such as insurance companies, when they take adverse actions based on information contained in consumer credit reports. According to the FCRA, an adverse action means a denial or revocation of credit or insurance coverage, a change in the terms of an existing credit arrangement or insurance coverage, or a refusal to grant credit or insurance in substantially the amount or on substantially the terms requested. Because Boxwood refused to grant life insurance coverage to Mr.&nbsp;Walker in the amount that he applied for, Action B is an example of an adverse action. However, because Boxwood denied life insurance coverage to Ms.&nbsp;Lynch, Action A also <b>is</b> an example of an adverse action.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The FCRA regulates third parties, such as insurance companies, when they take adverse actions based on information contained in consumer credit reports. At least one of these actions is an example of an adverse action.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_036'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_037';
objQuestion.questionID = 117002;
objQuestion.item = 'LOMA_311_PPQ2020_037';
objQuestion.primaryLO = '3I';
objQuestion.textref = 'c. 3, p. 28';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3I';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statement(s) can correctly be made about laws that govern the employment relationship in the United States and in other countries:</p><ol type=\"A\" class=\"combo\"><li>Employment laws in all countries outside the United States are based on the concept that employees are considered to be employees at will.</li><li>In the United States, most state employment laws are based on the idea that every employment relationship is a contractual relationship governed by the employment contract.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473075;
arrAnsIDs[1] = 473076;
arrAnsIDs[2] = 473077;
arrAnsIDs[3] = 473078;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is incorrect. Employment laws in many countries are based on the idea that every employment relationship is a <b>contractual relationship</b> governed by the employment contract.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is incorrect. In the United States, subject to limitations in some states, employees are considered to be employees <b>at will</b>, which means that either the employer or the employee can terminate the employment at any time for any lawful reason.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Both statements are incorrect. Laws in many countries do not provide for an employment-at-will relationship. Instead, laws in these countries are based on the idea that every employment relationship is a <b>contractual relationship</b> governed by the employment contract. </p><p class=\"explanations\">In the United States, subject to limitations in some states, employees are considered to be employees <b>at will</b>, which means that either the employer or the employee can terminate the employment at any time for any lawful reason.</p><p class=\"explanations\"><b>Learning Objective: 3I. List the nondiscrimination requirements that U.S. federal and state laws typically impose on employers.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_037'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_038';
objQuestion.questionID = 117003;
objQuestion.item = 'LOMA_311_PPQ2020_038';
objQuestion.primaryLO = '3I';
objQuestion.textref = 'c. 3, p. 29';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3I';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following individuals wish to file age-based discrimination charges against employers, all of which are subject to the federal Age Discrimination in Employment Act (ADEA):</p><ul class=\"examul\"><li>Todd Lee, age 58, believes he was recently fired from his job because of his age.</li><li>Elaine Alexander, age 23, believes she was not hired by a company because she was much younger than the other job candidates.</li><li>Judy Conway, age 60, believes she is being paid less than her coworkers only because she is older than they are.</li></ul><p class=\"stem\">Of these three individuals, the ones who would be considered protected workers under the ADEA include</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Mr.&nbsp;Lee, Ms.&nbsp;Alexander, and Ms.&nbsp;Conway";
arrAnsChoices[1] = "Mr.&nbsp;Lee and Ms.&nbsp;Alexander only";
arrAnsChoices[2] = "Mr.&nbsp;Lee and Ms.&nbsp;Conway only";
arrAnsChoices[3] = "Ms.&nbsp;Conway only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473079;
arrAnsIDs[1] = 473080;
arrAnsIDs[2] = 473081;
arrAnsIDs[3] = 473082;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these individuals would <b>not </b>be considered a protected worker under the ADEA.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The federal ADEA protects workers who are age <b>40 and older </b>from being discriminated against because of their age. Therefore, Mr.&nbsp;Lee would be considered a protected worker under the ADEA, but Ms.&nbsp;Alexander would <b>not </b>be considered a protected worker.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The federal ADEA protects workers who are age 40 and older from being discriminated against because of their age. It prohibits employers from refusing to hire and from firing individuals age 40 and older because of their age. Because Mr.&nbsp;Lee is age 58 and believes he was recently fired from his job because of his age, he would be considered a protected worker under the ADEA. The ADEA also prohibits employers from discriminating regarding compensation and other terms and conditions of employment because of an individual’s age. Because Ms.&nbsp;Conway age 60 and believes she is being paid less than her coworkers only because she is older than they are, she also would be considered a protected worker under the ADEA.</p><p class=\"explanations\"><b>Learning Objective: 3I. List the nondiscrimination requirements that U.S. federal and state laws typically impose on employers.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The federal ADEA protects workers who are <b>age 40 and older</b> from being discriminated against because of their age. The ADEA prohibits employers from discriminating regarding compensation and other terms and conditions of employment because of an individual’s age. Because Ms.&nbsp;Conway is age 60 and believes she is being paid less than her coworkers only because she is older than they are, she would be considered a protected worker under the ADEA. However, she is not the only one of these individuals who would be considered a protected worker under the ADEA.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_038'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['3A'] = "3A. Identify the characteristics of a corporation that make it the ideal form of business organization for an insurance company.";
arrlotext['3B'] = "3B. Explain the steps a life insurer must take to do business in the United States.";
arrlotext['3C'] = "3C. Compare characteristics of corporations in the United States and other countries.";
arrlotext['3D'] = "3D. Define a multinational corporation and describe ways in which companies can operate in a foreign country.";
arrlotext['3E'] = "3E. Compare the three primary groups of people who are involved in the management of a corporation and explain each group’s legal rights and duties.";
arrlotext['3F'] = "3F. Identify methods by which corporations can change their corporate structures.";
arrlotext['3G'] = "3G. Explain U.S. federal antitrust laws and the types of activities they typically prohibit, and compare U.S. federal antitrust laws to antitrust laws in other countries.";
arrlotext['3H'] = "3H. Describe federal consumer protection laws that regulate trade practices.";
arrlotext['3I'] = "3I. List the nondiscrimination requirements that U.S. federal and state laws typically impose on employers.";
