var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2020';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 311 Practice Questions, Chapter 8";
var coursename = 'LOMA 311';
var modulenumber = 3;
var title = "LOMA_311_PPQ2020_0_8";
var intNumPools = 1;
var numQ = 11;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Business Law for Insurance Professionals (2020)";
arrNumChap[0] = 1;
var thisChap = '8';

objPool = new Object(); 
objPool.intSelectCount = 11;
objPool.formID = 2380;
objPool.formName = 'PPQ2020_0_8';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_311_PQ_103';
arrPoolQuestions[1] = 'LOMA_311_PQ_104';
arrPoolQuestions[2] = 'LOMA_311_PQ_105';
arrPoolQuestions[3] = 'LOMA_311_PQ_106';
arrPoolQuestions[4] = 'LOMA_311_PQ_107';
arrPoolQuestions[5] = 'LOMA_311_PQ_108';
arrPoolQuestions[6] = 'LOMA_311_PQ_109';
arrPoolQuestions[7] = 'LOMA_311_PQ_110';
arrPoolQuestions[8] = 'LOMA_311_PQ_111';
arrPoolQuestions[9] = 'LOMA_311_PQ_112';
arrPoolQuestions[10] = 'LOMA_311_PQ_113';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_103';
objQuestion.questionID = 117068;
objQuestion.item = 'LOMA_311_PPQ2020_103';
objQuestion.primaryLO = '8A';
objQuestion.textref = 'c. 8, p. 5';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '8A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">State insurance laws require insurers to include certain provisions in individual life insurance and group insurance policy forms. One provision that is required in individual policies but not in group policies is the </p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "free look provision";
arrAnsChoices[1] = "incontestability provision";
arrAnsChoices[2] = "entire contract provision";
arrAnsChoices[3] = "grace period provision";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473350;
arrAnsIDs[1] = 473351;
arrAnsIDs[2] = 473352;
arrAnsIDs[3] = 473353;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">In addition to the free look provision, the reinstatement provision is another provision required in individual policies but not in group policies. In the United States, nearly all of the states have laws that specify standard provisions insures must include in individual life insurance policies. Furthermore, insurers must include most of these provisions in annuity contracts and group policies. </p><p class=\"explanations\"><b>Learning Objective: 8A. Identify and explain the provisions that state insurance laws require insurers to include in individual life insurance policy forms.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The incontestability provision <b>is</b> required in group policies. </p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The entire contract provision <b>is</b> required in group policies. </p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The grace period provision <b>is</b> required in group policies. </p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_103'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_104';
objQuestion.questionID = 117069;
objQuestion.item = 'LOMA_311_PPQ2020_104';
objQuestion.primaryLO = '8B';
objQuestion.textref = 'c. 8, pp. 8-9';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '8B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about the regulation of insurance advertising. Select the answer choice containing the correct statement. </p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Materials used to recruit and train insurance agents are subject to the NAIC Model Advertisements Regulation, even if the materials are not designed to be used to induce the public to purchase, increase, or modify a policy.";
arrAnsChoices[1] = "Most states have laws or regulations based on the NAIC Life Insurance Illustrations Model Regulation, which sets rules that insurers and insurance agents must follow when using illustrations in life insurance sales. ";
arrAnsChoices[2] = "Most states do not specifically address social media in advertising requirements and do not expect communications via social media to comply with advertising standards. ";
arrAnsChoices[3] = "Sales talks, presentations, and materials prepared for use by insurance agents are not subject to the NAIC Model Advertisements Regulation. ";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473354;
arrAnsIDs[1] = 473355;
arrAnsIDs[2] = 473356;
arrAnsIDs[3] = 473357;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Materials used to recruit and train insurance agents are subject to the regulation only <b>when</b> the materials are designed to be used to induce the public to purchase, increase, modify, reinstate, borrow on, surrender, replace, or retain a policy. </p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The purpose of this model regulation is to (1) ensure that illustrations do not mislead consumers and (2) make illustrations easier for consumers to understand. </p><p class=\"explanations\"><b>Learning Objective: 8B. Describe the state regulatory requirements that apply to life insurance and annuity advertisements.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Insurance departments have broad powers to regulate any type of communication, whether or not it is listed in the state’s advertising regulations. Most stated do not specifically address social media in advertising requirements. Yet insurance departments <b>expect</b> communications via social media to comply with advertising standards. </p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Sales talks, presentations, and materials prepared for use by insurance agents <b>are</b> subject to the NAIC Model Advertisements Regulation.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_104'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_105';
objQuestion.questionID = 117070;
objQuestion.item = 'LOMA_311_PPQ2020_105';
objQuestion.primaryLO = '8C';
objQuestion.textref = 'c. 8, p. 11';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '8C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Gene Poff, an insurance agent, offered an inducement to Janet Tripp to purchase a policy from him, but he did not offer the inducement to other applicants in her situation. The inducement is not stated in the policy itself. The sales practice employed by Mr.&nbsp;Poff in this situation, which is prohibited by state Unfair Trade Practices Acts, is known as</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "rebating";
arrAnsChoices[1] = "duress";
arrAnsChoices[2] = "defamation";
arrAnsChoices[3] = "disaffirmance";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473358;
arrAnsIDs[1] = 473359;
arrAnsIDs[2] = 473360;
arrAnsIDs[3] = 473361;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Most states have enacted as part of their insurance codes an Unfair Trade Practices Act. These insurance laws define certain practices, including sales practices, as unfair. Rebating is one such prohibited practice. These insurance laws generally apply to all people and legal entities that engage in the business of insurance, including insurers and insurance agents.</p><p class=\"explanations\"><b>Learning Objective: 8C. Give examples of common state regulatory requirements that apply to insurance agents and sales activities.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Duress is <b>not </b>a sales practice. Duress exists when a person acts wrongfully or threateningly to overpower the will of another so as to force that person to enter into a contract against her own free will.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Defamation is <b>not </b>a sales practice. Defamation is an intentional tort that occurs when a person makes false statements that injure the good name or reputation of another person.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Disaffirmance is <b>not </b>a sales practice. Disaffirmance is a minor’s exercise of his right to avoid a contract.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_105'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_106';
objQuestion.questionID = 117071;
objQuestion.item = 'LOMA_311_PPQ2020_106';
objQuestion.primaryLO = '8C';
objQuestion.textref = 'c. 8, pp. 11-12';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '8C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Most states impose requirements that agents and insurers must meet when a transaction involves the replacement of an inforce individual life insurance policy or annuity contract. The following statement(s) can correctly be made about these requirements:</p><ol type=\"A\" class=\"combo\"><li>According to the NAIC Model Replacement Regulation, an insurance agent must submit a replacement statement along with every application for a policy intended to replace an inforce individual life insurance policy or annuity contract. </li><li>If an applicant has an inforce policy that is subject to the Model Replacement Regulation, then the agent must give the applicant a written notice that includes information about the potential effect of the replacement, and that must be signed by both the applicant and the agent.</li><li>When another insurance company’s policy will be replaced, the replacing insurer is required by most states to send a written notice to the insurer that issued the policy that may be replaced. </li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A, B, and C";
arrAnsChoices[1] = "A and B only";
arrAnsChoices[2] = "B and C only";
arrAnsChoices[3] = "A only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473362;
arrAnsIDs[1] = 473363;
arrAnsIDs[2] = 473364;
arrAnsIDs[3] = 473365;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">All the statements are correct. The goal of the Model Replacement Regulation is to make sure that insurers and insurance agents provide consumers with fair and accurate information about policies so consumers can make informed decisions. </p><p class=\"explanations\"><b>Learning Objective: 8C. Give examples of common state regulatory requirements that apply to insurance agents and sales activities.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statements A and B are correct. However, Statement C is also correct. </p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B and C are correct. However, Statement A is also correct. </p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Statement A is correct, but it is not the only correct response. </p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_106'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_107';
objQuestion.questionID = 117072;
objQuestion.item = 'LOMA_311_PPQ2020_107';
objQuestion.primaryLO = '8D';
objQuestion.textref = 'c. 8, p. 14';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '8D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">To ensure that underwriting is fair and equitable, state insurance laws impose requirements to prevent insurers from unfairly discriminating against proposed insureds. The following statements are about these requirements. Select the answer choice containing the correct statement. </p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Most states do not permit different premium rates for men and women. ";
arrAnsChoices[1] = "Most states permit insurers to base an underwriting decision solely on a proposed insured’s sexual orientation. ";
arrAnsChoices[2] = "Most states prohibit insurers from basing an underwriting decision solely on whether a proposed insured has been the victim of domestic abuse. ";
arrAnsChoices[3] = "Underwriters may consider a proposed insured’s existing medical conditions, <i>excluding</i> those caused by domestic abuse. ";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473366;
arrAnsIDs[1] = 473367;
arrAnsIDs[2] = 473368;
arrAnsIDs[3] = 473369;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A few states prohibit insurers from charging different premium rates based on an insured’s sex. Most states, however, <b>permit</b> different premium rates for men and women as long as the rates are based on sound actuarial principles </p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Most states <b>prohibit</b> insurers from basing an underwriting decision solely on a proposed insured’s sexual orientation.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">People who are victims of domestic abuse tend to have increased mortality risk. Even so, most states prohibit insurers from basing an underwriting decision solely on whether a proposed insured has been the victim of domestic abuse. However, underwriters may consider a proposed insured’s existing medical conditions, including those caused by domestic abuse. Such laws attempt to balance the right of insurers to evaluate a proposed insured’s risk against the public interest in protecting the financial security of abuse victims. </p><p class=\"explanations\"><b>Learning Objective: 8D. Give examples of how state insurance laws regulate underwriting, claim practices, and complaint handling.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Underwriters may consider a proposed insured’s existing medical conditions, <b>including</b> those caused by domestic abuse</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_107'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_108';
objQuestion.questionID = 117073;
objQuestion.item = 'LOMA_311_PPQ2020_108';
objQuestion.primaryLO = '8E';
objQuestion.textref = 'c. 8, p. 20';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '8E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">After May Li was declined for individual life insurance coverage by the Uptown Insurance Company, she applied for coverage from the Midtown Insurance Company. Midtown offered to insure Ms.&nbsp;Li, but at a higher than standard premium rate. In these situations, according to the NAIC Insurance Information and Privacy Protection Model Act (Model Privacy Act), an adverse underwriting decision was made by</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "both Uptown and Midtown";
arrAnsChoices[1] = "Uptown only";
arrAnsChoices[2] = "Midtown only";
arrAnsChoices[3] = "neither Uptown nor Midtown";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473370;
arrAnsIDs[1] = 473371;
arrAnsIDs[2] = 473372;
arrAnsIDs[3] = 473373;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">For purposes of the Model Privacy Act, an adverse underwriting decision is (1) a declination of coverage, (2) a termination of coverage, or (3) an offer to insure at higher than standard premium rates. Because both Uptown and Midtown made adverse underwriting decisions with respect to Ms.&nbsp;Li, they must provide her with the reasons for their decisions and a summary of her right of access to personal information that they hold.</p><p class=\"explanations\"><b>Learning Objective: 8E. Compare and contrast U.S. privacy requirements and the privacy requirements in the European Union and other countries.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">For purposes of the Model Privacy Act, an adverse underwriting decision includes a declination of coverage. However, it also includes an offer to insure at higher than standard premium rates. Therefore, <b>both</b> Uptown and Midtown made an adverse underwriting decision with respect to Ms.&nbsp;Li.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">For purposes of the Model Privacy Act, an adverse underwriting decision includes an offer to insure at higher than standard premium rates. However, it also includes a declination of coverage. Therefore, <b>both</b> Uptown and Midtown made an adverse underwriting decision with respect to Ms.&nbsp;Li.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these insurers made an adverse underwriting decision with respect to Ms.&nbsp;Li.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_108'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_109';
objQuestion.questionID = 117074;
objQuestion.item = 'LOMA_311_PPQ2020_109';
objQuestion.primaryLO = '8E';
objQuestion.textref = 'c. 8, pp. 21-22';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '8E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Hillside Insurance Company plans to provide customers’ nonpublic personal information to the Widely Marketing Firm, a nonaffiliated third party, to be used in marketing Hillside’s own products. With regard to U.S. federal laws, Hillside (<b>is</b> / <b>is not</b>) permitted to disclose nonpublic personal information to Widely without giving customer an opportunity to opt out. Hillside (<b>is</b> / <b>is not</b>) required to have a confidentiality agreement with Widely to maintain the confidentiality of the information. </p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "is / is";
arrAnsChoices[1] = "is / is not";
arrAnsChoices[2] = "is not / is";
arrAnsChoices[3] = "is not / is not";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473374;
arrAnsIDs[1] = 473375;
arrAnsIDs[2] = 473376;
arrAnsIDs[3] = 473377;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Federal laws restrict how a financial firm shares information with nonaffiliated third parties. As a general rule, a financial firm is permitted to disclose nonpublic personal information to a nonaffiliated third party (either directly or through an affiliate) only after the firm has taken the following steps: (1) notified the customer that the information may be disclosed to such a third party, (2) given the consumer an opportunity to opt out of the disclosure by directing that the insurer not disclose the information, and (3) explained to the consumer how to opt out of the disclosure. </p><p class=\"explanations\">However, if the disclosure of nonpublic personal information is necessary to enable a nonaffiliated third party to perform services on behalf of the financial firm, then the firm is permitted to disclose such information to the third party without giving customers an opportunity to opt out. In such cases, the firm must (1) fully disclose to the customer that the information is going to be provided and (2) obtain a contractual commitment from the third party to maintain the confidentiality of the information.</p><p class=\"explanations\"><b>Learning Objective: 8E. Compare and contrast U.S. privacy requirements and the privacy requirements in the European Union and other countries.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that, in this situation, Hillside is permitted to disclose nonpublic personal information to Widely without giving customer an opportunity to opt out. However, Hillside <b>is</b> required to have a confidentiality agreement with Widely to maintain the confidentiality of the information.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that Hillside is required to have a confidentiality agreement with Widely to maintain the confidentiality of the information. However, in this situation, Hillside <b>is</b> permitted to disclose nonpublic personal information to Widely without giving customer an opportunity to opt out.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">In this situation, Hillside <b>is</b> permitted to disclose nonpublic personal information to Widely without giving customer an opportunity to opt out. However, Hillside <b>is</b> required to have a confidentiality agreement with Widely to maintain the confidentiality of the information.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_109'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_110';
objQuestion.questionID = 117075;
objQuestion.item = 'LOMA_311_PPQ2020_110';
objQuestion.primaryLO = '8E';
objQuestion.textref = 'c. 8, p. 22';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '8E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statement(s) can correctly be made about the European Union’s Directive on Privacy and Electronic Communications (EU Directive):</p><ol type=\"A\" class=\"combo\"><li>The EU Directive prohibits the transfer of personal information from the EU to a non-EU country unless the non-EU country provides adequate protection of the information.</li><li>The EU Directive’s privacy requirements are less stringent than U.S. requirements. </li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473378;
arrAnsIDs[1] = 473379;
arrAnsIDs[2] = 473380;
arrAnsIDs[3] = 473381;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect. </p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct. The EU Directive seeks to ensure the free flow of information while protecting the privacy of personal information. The EU Directive requires providers of publicly available electronic communications services to take specific steps to safeguard the security of their services and ensure the privacy of electronically transmitted information.</p><p class=\"explanations\">Statement B is incorrect. Other countries have privacy requirements that are stricter than U.S. requirements. Perhaps the most stringent requirements are in the European Union (EU).</p><p class=\"explanations\"><b>Learning Objective: 8E. Compare and contrast U.S. privacy requirements and the privacy requirements in the European Union and other countries.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is incorrect. Other countries have privacy requirements that are stricter than U.S. requirements. Perhaps the <b>most stringent</b> requirements are in the European Union (EU).</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct. </p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_110'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_111';
objQuestion.questionID = 117076;
objQuestion.item = 'LOMA_311_PPQ2020_111';
objQuestion.primaryLO = '8F';
objQuestion.textref = 'c. 8, p. 24';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '8F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">In the United States, companies that engage in electronic transactions must consider the requirements of the federal Electronic Signatures in Global and National Commerce Act (E-SIGN) and state laws based on the Uniform Electronic Transactions Act (UETA). One true statement about the provisions of E-SIGN and the UETA is that</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "they require consumers to use electronic records, signatures, and contracts for certain transactions";
arrAnsChoices[1] = "if a provision of a state law based on the UETA is inconsistent with E-SIGN, the state law provision preempts E-SIGN";
arrAnsChoices[2] = "certain legal documents and transactions, such as court orders and mortgage foreclosures, cannot be completed with electronic signatures";
arrAnsChoices[3] = "they set criteria for the technical reliability and adequacy of electronic signatures";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473382;
arrAnsIDs[1] = 473383;
arrAnsIDs[2] = 473384;
arrAnsIDs[3] = 473385;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Under E-SIGN and the UETA, consumers cannot be required to use electronic records, signatures, or contracts. Instead, a consumer must <b>affirmatively consent</b> to the use of electronic notices and records.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">If a provision of a state law based on the UETA is inconsistent with E-SIGN, then <b>E-SIGN preempts</b> that state law provision.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Under the provisions of E-SIGN and the UETA, certain legal documents and transactions cannot be completed with electronic signatures. Examples of such documents and transactions include court orders, mortgage foreclosures, wills and testamentary trusts, and notices of the cancellation of life or health insurance coverage.</p><p class=\"explanations\"><b>Learning Objective: 8F. Explain electronic commerce laws that are designed to facilitate electronic signatures, contracts, and documents.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">E-SIGN and the UETA do <b>not </b>directly address the reliability of electronic signatures. However, some countries have enacted laws that address the reliability and adequacy of electronic signatures. </p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_111'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_112';
objQuestion.questionID = 117077;
objQuestion.item = 'LOMA_311_PPQ2020_112';
objQuestion.primaryLO = '8G';
objQuestion.textref = 'c. 8, pp. 27-28';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '8G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about insurance fraud. Three statements are true, and one statement is false. Select the answer choice containing the <B>FALSE</B> statement. </p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Insurance fraud is a crime in every state.";
arrAnsChoices[1] = "Insurance fraud can be classified as internal or external.";
arrAnsChoices[2] = "The Insurance Fraud Prevention Model Act requires insurers to include a fraud warning statement on all insurance applications and claim forms.";
arrAnsChoices[3] = "All states require each licensed insurer to develop and maintain an antifraud plan and to file it with the state insurance department. ";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473386;
arrAnsIDs[1] = 473387;
arrAnsIDs[2] = 473388;
arrAnsIDs[3] = 473389;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">This is a true statement; therefore, it is <b>not</b> the correct response.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">This is a true statement; therefore, it is <b>not</b> the correct response. </p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">This is a true statement; therefore, it is <b>not</b> the correct response.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">This is a false statement; therefore, it is the correct response. Only <b>a number of</b> states require each licensed insurer to develop and maintain an antifraud plan and to file it with the state insurance department. </p><p class=\"explanations\"><b>Learning Objective: 8G. Give examples of measures that state insurance departments and insurers have taken to increase their capacity to detect and prevent insurance fraud.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_112'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_113';
objQuestion.questionID = 117078;
objQuestion.item = 'LOMA_311_PPQ2020_113';
objQuestion.primaryLO = '8H';
objQuestion.textref = 'c. 8, p. 32';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '8H';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about market conduct examinations. Select the answer choice containing the correct statements. </p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "According to the Market Conduct Surveillance Model Law, states conduct comprehensive examinations on an annual basis.";
arrAnsChoices[1] = "Market conduct examinations and applicable market conduct laws and regulations are as uniform as those for solvency examinations are.";
arrAnsChoices[2] = "Insurers that operate in more than one state are subject to market conduct oversight by each of those states. ";
arrAnsChoices[3] = "Multistate market conduct examinations are coordinated to the same extent as multistate solvency examinations.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473390;
arrAnsIDs[1] = 473391;
arrAnsIDs[2] = 473392;
arrAnsIDs[3] = 473393;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">According to the Market Conduct Surveillance Model Law, states will conduct comprehensive examinations <b>only in unusual circumstances</b>. </p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Market conduct examinations and applicable market conduct laws and regulations are <b>not</b> as uniform as are those for solvency examinations.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Market conduct examinations and applicable market conduct laws and regulations are not as uniform as are those for solvency examinations. Thus, multistate market conduct examinations are not coordinated to the same extent as multistate solvency examinations. </p><p class=\"explanations\"><b>Learning Objective: 8H. List the range of actions an insurance department can take based on market analysis findings.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Multistate market conduct examinations are <b>not</b> coordinated to the same extent as multistate solvency examinations.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_113'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['8A'] = "8A. Identify and explain the provisions that state insurance laws require insurers to include in individual life insurance policy forms.";
arrlotext['8B'] = "8B. Describe the state regulatory requirements that apply to life insurance and annuity advertisements.";
arrlotext['8C'] = "8C. Give examples of common state regulatory requirements that apply to insurance agents and sales activities.";
arrlotext['8D'] = "8D. Give examples of how state insurance laws regulate underwriting, claim practices, and complaint handling.";
arrlotext['8E'] = "8E. Compare and contrast U.S. privacy requirements and the privacy requirements in the European Union and other countries.";
arrlotext['8F'] = "8F. Explain electronic commerce laws that are designed to facilitate electronic signatures, contracts, and documents.";
arrlotext['8G'] = "8G. Give examples of measures that state insurance departments and insurers have taken to increase their capacity to detect and prevent insurance fraud.";
arrlotext['8H'] = "8H. List the range of actions an insurance department can take based on market analysis findings.";
