var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2019';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 335 Practice Questions, Chapter 7";
var coursename = 'LOMA 335';
var modulenumber = 0;
var title = "LOMA_335_PPQ2019_0_7";
var intNumPools = 1;
var numQ = 8;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Operational Excellence for Insurance Professionals (2019)";
arrNumChap[0] = 1;
var thisChap = '7';

objPool = new Object(); 
objPool.intSelectCount = 8;
objPool.formID = 2062;
objPool.formName = 'PPQ2019_0_7';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_335_PQ_065';
arrPoolQuestions[1] = 'LOMA_335_PQ_066';
arrPoolQuestions[2] = 'LOMA_335_PQ_067';
arrPoolQuestions[3] = 'LOMA_335_PQ_068';
arrPoolQuestions[4] = 'LOMA_335_PQ_069';
arrPoolQuestions[5] = 'LOMA_335_PQ_070';
arrPoolQuestions[6] = 'LOMA_335_PQ_071';
arrPoolQuestions[7] = 'LOMA_335_PQ_072';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_065';
objQuestion.questionID = 109353;
objQuestion.item = 'LOMA_335_PPQ2019_065';
objQuestion.primaryLO = '7A';
objQuestion.textref = 'c. 7, p. 3';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '7A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statement(s) can correctly be made about a company’s structure and decision-making in the insurance industry: </p><ol type=\"A\" class=\"combo\"><li>In small, simple organizational structures where information flows naturally among levels, having the majority of decisions made at the top or corporate level might work well.</li><li>Larger companies do not require a centralized repository of usable and current data from all company divisions in order to make effective decisions. </li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441946;
arrAnsIDs[1] = 441947;
arrAnsIDs[2] = 441948;
arrAnsIDs[3] = 441949;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect. </p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct; however, Statement B is incorrect. Without a centralized repository of data, the time needed to gather information and the potential for miscommunications and bad decisions increase. </p><p class=\"explanations\"><b>Learning Objective: 7A. Explain how an organization’s structure affects decision making.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is incorrect. Without a centralized repository of data, the time needed to gather information and the potential for miscommunications and bad decisions increase.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_065'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_066';
objQuestion.questionID = 109354;
objQuestion.item = 'LOMA_335_PPQ2019_066';
objQuestion.primaryLO = '7B';
objQuestion.textref = 'c. 7, pp. 5-6';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '7B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Experts at McKinsey & Company categorize decisions into four distinct types: ad hoc decisions, big-bet decisions, cross-cutting decisions, and delegated decisions. Creating a new version of an existing product is an example of </p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "an ad hoc decision";
arrAnsChoices[1] = "a big-bet decision";
arrAnsChoices[2] = "a cross-cutting decision";
arrAnsChoices[3] = "a delegated decision";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441950;
arrAnsIDs[1] = 441951;
arrAnsIDs[2] = 441952;
arrAnsIDs[3] = 441953;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Ad hoc decisions are decisions that can be made quickly at an individual level because the risks involved with these decisions are relatively small. Creating a new version of an existing product involves too big a risk to be an ad hoc decision.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Big-bet decisions are infrequent, unfamiliar decisions that can have a profound effect on a company’s operations and future success. Creating a new version of an existing product is too frequent and familiar to be a big-bet decision.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Cross-cutting decisions are familiar decisions that can have broad organizational impact. Cross-cutting decisions require effective collaboration among many different parts of an organization. As a result, companies often establish permanent cross-cutting teams for making cross-cutting decisions.</p><p class=\"explanations\"><b>Learning Objective: 7B. Identify and describe heuristics and the four primary types of decisions.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Delegated decisions are typically low in risk but they involve familiar and frequent decisions. Creating a new version of an existing product involves too big a risk to be a delegated decision.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_066'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_067';
objQuestion.questionID = 109355;
objQuestion.item = 'LOMA_335_PPQ2019_067';
objQuestion.primaryLO = '7C';
objQuestion.textref = 'c. 7, p. 8';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '7C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">By definition, when an individual identifies or defines a problem too narrowly because he assumes he knows what the issue is, the individual is </p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "choosing decision alternative";
arrAnsChoices[1] = "committing a framing error";
arrAnsChoices[2] = "subject to confirmation bias";
arrAnsChoices[3] = "using heuristics";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441954;
arrAnsIDs[1] = 441955;
arrAnsIDs[2] = 441956;
arrAnsIDs[3] = 441957;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Decision alternatives are the options a decision maker considers before selecting a future course of action.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The first step of the decision-making process is often subject to framing errors. Good decision makers explore all relevant aspects of a situation before making a decision.</p><p class=\"explanations\"><b>Learning Objective: 7C. Describe framing in decision making and biases that can occur during decision making.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Confirmation bias is the human tendency to seek, interpret, and remember information that confirms a pre-existing belief.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Heuristics are general rules that allow people to make decisions quickly without gathering extensive information.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_067'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_068';
objQuestion.questionID = 109356;
objQuestion.item = 'LOMA_335_PPQ2019_068';
objQuestion.primaryLO = '7D';
objQuestion.textref = 'c. 7, p. 9';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '7D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Dogwood Insurance Company uses knowledge management systems and informative updates across operations such that employees at every level of the company can access the information that is relevant and necessary for their roles. By definition, this information indicates that Dogwood engages in </p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "quality analysis";
arrAnsChoices[1] = "enterprise-wide reporting";
arrAnsChoices[2] = "control limits";
arrAnsChoices[3] = "quality assurance";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441958;
arrAnsIDs[1] = 441959;
arrAnsIDs[2] = 441960;
arrAnsIDs[3] = 441961;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Quality analysis is any type of research or investigation to understand an aspect of preventing defects or meeting customer needs. Dogwood does <b>not</b> engage in quality analysis in this situation. </p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Enterprise-wide reporting should be complete, accurate, and accessible to those needing the information. Companies often use dashboard systems that include values, projections, or analysis to help employees perform successfully for enterprise wide reporting. Beyond software, decision makers can contribute to knowledge sharing within the organization by conducting update meetings, sending notices to employees about new and crucial company information, and strategically placing need-to-know visuals in the office. </p><p class=\"explanations\"><b>Learning Objective: 7D. Describe enterprise-wide reporting of business information.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">In a control chart, the threshold values are control limits. Dogwood does <b>not</b> engage in control limits in this situation.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Quality assurance refers to the activities a company undertakes to make certain the company delivers satisfactory products and services to customers. Dogwood does <b>not</b> engage in quality assurance in this situation. </p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_068'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_069';
objQuestion.questionID = 109357;
objQuestion.item = 'LOMA_335_PPQ2019_069';
objQuestion.primaryLO = '7E';
objQuestion.textref = 'c. 7, p. 10';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '7E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Two types of conflict that can arise in a decision-making group are cooperative conflict and competitive conflict. One group characteristic that will lead to <i>competitive conflict</i> is that the group</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "has effective group communication and trust";
arrAnsChoices[1] = "has shared values and beliefs";
arrAnsChoices[2] = "prefers decision failure over loss in power struggles";
arrAnsChoices[3] = "recognizes the legitimacy of others’ interests";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441962;
arrAnsIDs[1] = 441963;
arrAnsIDs[2] = 441964;
arrAnsIDs[3] = 441965;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">This group characteristic will lead to <b>cooperative</b> conflict.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">This group characteristic will lead to <b>cooperative</b> conflict.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Other group characteristics that will lead to competitive conflict include lack of trust caused by misinformation and false promises, coercive tactics to impose one side’s view on others, and ongoing disagreement about and critical rejection of others’ ideas.</p><p class=\"explanations\"><b>Learning Objective: 7E. Distinguish between cooperative and competitive conflict and describe the role of the devil’s advocate in decision making.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">This group characteristic will lead to <b>cooperative</b> conflict.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_069'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_070';
objQuestion.questionID = 109358;
objQuestion.item = 'LOMA_335_PPQ2019_070';
objQuestion.primaryLO = '7F';
objQuestion.textref = 'c. 7, p. 11';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '7F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Analysis paralysis occurs when a team spends excessive time and energy in gathering information. The following statements are about analysis paralysis:</p><ol type=\"A\" class=\"combo\"><li>Analysis paralysis is most common in ad hoc decisions.</li><li>Higher-risk decisions should include a decision deadline to reduce the risk of analysis paralysis.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441966;
arrAnsIDs[1] = 441967;
arrAnsIDs[2] = 441968;
arrAnsIDs[3] = 441969;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is incorrect. Analysis paralysis is more common in <b>big-bet</b> decisions.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement A is incorrect. Analysis paralysis is more common in big-bet decisions.</p><p class=\"explanations\">Statement B is correct. If a decision cannot be made by a certain date, then the group needs to present valid reasons for extending the deadline or realize that the decision of the group is not to make a decision at all.</p><p class=\"explanations\"><b>Learning Objective: 7F. Explain the role of analysis paralysis in choosing a decision alternative.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_070'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_071';
objQuestion.questionID = 109359;
objQuestion.item = 'LOMA_335_PPQ2019_071';
objQuestion.primaryLO = '7G';
objQuestion.textref = 'c. 7, pp. 12-13';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '7G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">McKinsey & Company, a global management consulting firm, categorizes uncertainty into four levels. Level 1 of uncertainty means that a decision maker </p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "has relevant data available for reliably predicting a future outcome ";
arrAnsChoices[1] = "faces a range of possible future outcomes and cannot reliably limit the options to a small set of scenarios";
arrAnsChoices[2] = "can accurately predict the future to be one of a few scenarios but cannot identify which outcome will definitely occur ";
arrAnsChoices[3] = "faces so many potential outcomes that it is nearly impossible to identify relevant variables or construct viable scenarios";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441970;
arrAnsIDs[1] = 441971;
arrAnsIDs[2] = 441972;
arrAnsIDs[3] = 441973;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Level 1 of uncertainty means a decision maker has a single view of the future. At Level 2, the future can accurately be predicted to be one of a few scenarios, but decision makers cannot identify which outcome will definitely occur. At Level 3, a manager faces a range of possible outcomes and cannot reliably limit the options to a small set of scenarios because the outcome might lie anywhere in the range of possibilities. Level 4 indicates so many potential outcomes that it is nearly impossible to identify relevant variables or construct viable scenarios. </p><p class=\"explanations\"><b>Learning Objective:</b> <b>7G. Describe certainty in decision making and distinguish among risks in four levels of uncertainty.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\"><b>Level 3</b> of uncertainty means a decision maker faces a range of possible future outcomes and cannot reliably limit the options to a small set of scenarios because the outcome might lie anywhere in the range of possibilities.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\"><b>Level 2</b> of uncertainty means the future can accurately be predicted to be one of a few scenarios, but decision makers cannot identify which outcome will definitely occur. </p>";
arrAnswerFeedback[3] = "<p class=\"explanations\"><b>Level 4</b> of uncertainty indicates so many potential outcomes that it is nearly impossible to identify relevant variable or construct viable scenarios.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_071'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_072';
objQuestion.questionID = 109360;
objQuestion.item = 'LOMA_335_PPQ2019_072';
objQuestion.primaryLO = '7H';
objQuestion.textref = 'c. 7, p. 14';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '7H';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">After implementation, decision makers assess the decision outcomes in comparison to expected outcomes. Decision expert Franck Schuurmans suggests</p><ol type=\"A\" class=\"combo\"><li>looking at the decision process separately from the decision’s outcome to determine if anything should have been done differently</li><li>keeping a decision log that lists the names of all who have participated in the decision-making process and their views and comments throughout the process</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441974;
arrAnsIDs[1] = 441975;
arrAnsIDs[2] = 441976;
arrAnsIDs[3] = 441977;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Statement A is correct. Evaluating decisions without assessing blame allows for learning from mistakes and makes for better future decisions.</p><p class=\"explanations\">Statement B is correct. Schuurmans suggests that a big decision is actually a series of smaller decisions that lead to the big decision. Because big decisions may take years to accomplish, a decision log will help the group keep track of the various aspects of decisions that will be impossible to remember over time. A decision log can also reduce hindsight bias.</p><p class=\"explanations\"><b>Learning Objective: 7H. Describe the role of feedback in improving decision making.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct; however, it is not the only correct statement.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is correct; however, it is not the only correct statement.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_072'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['7A'] = "7A. Explain how an organization’s structure affects decision making.";
arrlotext['7B'] = "7B. Identify and describe heuristics and the four primary types of decisions.";
arrlotext['7C'] = "7C. Describe framing in decision making and biases that can occur during decision making.";
arrlotext['7D'] = "7D. Describe enterprise-wide reporting of business information.";
arrlotext['7E'] = "7E. Distinguish between cooperative and competitive conflict and describe the role of the devil’s advocate in decision making.";
arrlotext['7F'] = "7F. Explain the role of analysis paralysis in choosing a decision alternative.";
arrlotext['7G'] = "7G. Describe certainty in decision making and distinguish among risks in four levels of uncertainty.";
arrlotext['7H'] = "7H. Describe the role of feedback in improving decision making.";
