var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2019';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 335 Practice Questions, Chapter 8";
var coursename = 'LOMA 335';
var modulenumber = 0;
var title = "LOMA_335_PPQ2019_0_8";
var intNumPools = 1;
var numQ = 16;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Operational Excellence for Insurance Professionals (2019)";
arrNumChap[0] = 1;
var thisChap = '8';

objPool = new Object(); 
objPool.intSelectCount = 16;
objPool.formID = 2062;
objPool.formName = 'PPQ2019_0_8';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_335_PQ_073';
arrPoolQuestions[1] = 'LOMA_335_PQ_074';
arrPoolQuestions[2] = 'LOMA_335_PQ_075';
arrPoolQuestions[3] = 'LOMA_335_PQ_076';
arrPoolQuestions[4] = 'LOMA_335_PQ_077';
arrPoolQuestions[5] = 'LOMA_335_PQ_078';
arrPoolQuestions[6] = 'LOMA_335_PQ_079';
arrPoolQuestions[7] = 'LOMA_335_PQ_080';
arrPoolQuestions[8] = 'LOMA_335_PQ_081';
arrPoolQuestions[9] = 'LOMA_335_PQ_082';
arrPoolQuestions[10] = 'LOMA_335_PQ_083';
arrPoolQuestions[11] = 'LOMA_335_PQ_084';
arrPoolQuestions[12] = 'LOMA_335_PQ_085';
arrPoolQuestions[13] = 'LOMA_335_PQ_086';
arrPoolQuestions[14] = 'LOMA_335_PQ_087';
arrPoolQuestions[15] = 'LOMA_335_PQ_088';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_073';
objQuestion.questionID = 109361;
objQuestion.item = 'LOMA_335_PPQ2019_073';
objQuestion.primaryLO = '8A';
objQuestion.textref = 'c. 8, pp. 3-4';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '8A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = 3;
objQuestion.strStem = "<p class=\"stem\">The population <i>mean</i> for these monthly claims numbers is equal to</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "165";
arrAnsChoices[1] = "170";
arrAnsChoices[2] = "180";
arrAnsChoices[3] = "195";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441978;
arrAnsIDs[1] = 441979;
arrAnsIDs[2] = 441980;
arrAnsIDs[3] = 441981;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The mean refers to the numerical average of a series of values. It is calculated by adding all the values in a given population and then dividing the total by the number of values in the population. The sum of the values of this data set is equal to 100 + 150 + 180 + 160 + 210 + 190, or 990. There are 6 values in the data set, so the mean is equal to 990 ÷ 6, or 165.</p><p class=\"explanations\"><b>Learning Objective: 8A. Calculate measures of central tendency and dispersion.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The mean refers to the numerical average of a series of values. It is calculated by adding all the values in a given population and then dividing the total by the number of values in the population. The mean of this data set is <b>not</b> 170.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The mean refers to the numerical average of a series of values. It is calculated by adding all the values in a given population and then dividing the total by the number of values in the population. The mean of this data set is <b>not</b> 180.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The mean refers to the numerical average of a series of values. It is calculated by adding all the values in a given population and then dividing the total by the number of values in the population. The mean of this data set is <b>not</b> 195.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_073'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_074';
objQuestion.questionID = 109362;
objQuestion.item = 'LOMA_335_PPQ2019_074';
objQuestion.primaryLO = '8A';
objQuestion.textref = 'c. 8, pp. 4-5';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '8A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = 3;
objQuestion.strStem = "<p class=\"stem\">The population <i>median</i> for these monthly claims numbers is equal to</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "155";
arrAnsChoices[1] = "165";
arrAnsChoices[2] = "170";
arrAnsChoices[3] = "180";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441982;
arrAnsIDs[1] = 441983;
arrAnsIDs[2] = 441984;
arrAnsIDs[3] = 441985;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The median is the middle value in a set of values arranged in numerical order. The median of this data set is <b>not</b> 155.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The median is the middle value in a set of values arranged in numerical order. The median of this data set is <b>not</b> 165.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The median is the middle value in a set of values arranged in numerical order. For this question, the numerical order is 100, 150, 160, 180, 190, 210. Since this data set has an even number of values, the median is the average of the two middle values; this number is equal to (160 + 180) ÷ 2, or 170.</p><p class=\"explanations\"><b>Learning Objective: 8A. Calculate measures of central tendency and dispersion.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The median is the middle value in a set of values arranged in numerical order. The median of this data set is <b>not</b> 180.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_074'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_075';
objQuestion.questionID = 109363;
objQuestion.item = 'LOMA_335_PPQ2019_075';
objQuestion.primaryLO = '8A';
objQuestion.textref = 'c. 8, p. 6';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '8A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = 3;
objQuestion.strStem = "<p class=\"stem\">The population <i>range</i> for these monthly claims numbers is equal to</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "60";
arrAnsChoices[1] = "90";
arrAnsChoices[2] = "100";
arrAnsChoices[3] = "110";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441986;
arrAnsIDs[1] = 441987;
arrAnsIDs[2] = 441988;
arrAnsIDs[3] = 441989;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The range is the difference between the highest value and the lowest value in a particular population. The range of this population is <b>not</b> 60.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The range is the difference between the highest value and the lowest value in a particular population. The range of this population is <b>not</b> 90.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The range is the difference between the highest value and the lowest value in a particular population. The range of this population is <b>not</b> 100.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The range is the difference between the highest value and the lowest value in a particular population. The highest value in this population is 210 and the lowest value in the population is 100. Therefore, the range of this population is 110: (210 – 100) = 110.</p><p class=\"explanations\"><b>Learning Objective: 8A. Calculate measures of central tendency and dispersion.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_075'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_076';
objQuestion.questionID = 109364;
objQuestion.item = 'LOMA_335_PPQ2019_076';
objQuestion.primaryLO = '8A';
objQuestion.textref = 'c. 8, pp. 6-7';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '8A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The variance and the standard deviation are two measures of dispersion for a population. The following statements are about the characteristics of these two measures when they are applied to a population. Select the answer choice containing the correct statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "In general, larger variances indicate that the values in a population are farther from the mean and more dispersed.";
arrAnsChoices[1] = "The variance is the most accurate measure of the dispersion of values in a population.";
arrAnsChoices[2] = "Smaller standard deviations indicate that values in the population are farther from the mean and more dispersed.";
arrAnsChoices[3] = "The standard deviation assumes that values are not distributed normally.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441990;
arrAnsIDs[1] = 441991;
arrAnsIDs[2] = 441992;
arrAnsIDs[3] = 441993;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The variance is the average squared distance between the population mean and each individual item in the population. Smaller variances indicate that values in a population are closer to the mean and less dispersed. The variance is not the most accurate measure of the dispersion of values. Because the variance is based on squared distances, it is not on the same numerical scale as the raw data. Therefore, the variance does not provide information about the actual distance between different data items or between individual data values and the mean. </p><p class=\"explanations\"><b>Learning Objective: 8A. Calculate measures of central tendency and dispersion.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The variance is <b>not </b>the most accurate measure of the dispersion of values. Because the variance is based on squared distances, it is not on the same numerical scale as the raw data. Therefore, the variance does not provide information about the actual distance between different data items or between individual data values and the mean. </p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A smaller standard deviation indicates that values in the population are <b>closer to</b> the mean and <b>less</b> dispersed.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The standard deviation assumes that values <b>are</b> distributed normally, in other words, evenly dispersed.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_076'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_077';
objQuestion.questionID = 109365;
objQuestion.item = 'LOMA_335_PPQ2019_077';
objQuestion.primaryLO = '8B';
objQuestion.textref = 'c. 8, p. 9';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '8B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Decision makers can use two types of statistical analysis to develop conclusions: descriptive statistics and inferential statistics. Inferential statistics <b>(are / are not)</b> as precise as descriptive statistics and provide information using <b>(fewer / more)</b> resources.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "are / fewer";
arrAnsChoices[1] = "are / more";
arrAnsChoices[2] = "are not / fewer";
arrAnsChoices[3] = "are not / more";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441994;
arrAnsIDs[1] = 441995;
arrAnsIDs[2] = 441996;
arrAnsIDs[3] = 441997;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that inferential statistics provide information using fewer resources, but inferential statistics <b>are not</b> as precise as descriptive statistics.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Inferential statistics are<b> not</b> as precise as descriptive statistics. Also, inferential statistics provide information using <b>fewer</b> resources because of the use of sampling. </p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Descriptive statistics are statistics that summarize a population. Inferential statistics allow a decision maker to draw conclusions about a large population based on a sample group, which can provide important information using fewer resources.</p><p class=\"explanations\">The accuracy of inferential statistics depends in large part on whether the sample is representative of the population. The more representative the sample data is of the underlying population of data, the more accurate the conclusions drawn from sample data are likely to be.</p><p class=\"explanations\"><b>Learning Objective: 8B. Distinguish between descriptive and inferential statistics.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that inferential statistics are not as precise as descriptive statistics; however, inferential statistics provide information using <b>fewer</b> resources because of the use of sampling.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_077'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_078';
objQuestion.questionID = 109366;
objQuestion.item = 'LOMA_335_PPQ2019_078';
objQuestion.primaryLO = '8C';
objQuestion.textref = 'c. 8, p. 10';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '8C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">One important concept on which insurers rely is the law of large numbers. The following statement(s) can correctly be made about the law of large numbers:</p><ol type=\"A\" class=\"combo\"><li>The law of large numbers states that, under normal circumstances, the more times a person observes a particular event, the more likely the observations will approximate the “true” probability of the event.</li><li>Insurance companies rely on the law of large numbers when they use mortality tables, which predicts exactly when each individual within a given group of people will die. </li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441998;
arrAnsIDs[1] = 441999;
arrAnsIDs[2] = 442000;
arrAnsIDs[3] = 442001;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct. A coin toss is a prime example of this concept. The more times you toss a coin, the more likely you are to see an approximately equal number of heads and tails.</p><p class=\"explanations\">Statement B is incorrect. Mortality tables present <b>the number of deaths</b> projected to occur within a given group of people during a specified period of time. </p><p class=\"explanations\"><b>Learning Objective: 8C. Describe the importance of the law of large numbers to inferential statistics.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is incorrect. Mortality tables present <b>the number of deaths</b> projected to occur within a given group of people during a specified period of time.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_078'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_079';
objQuestion.questionID = 109367;
objQuestion.item = 'LOMA_335_PPQ2019_079';
objQuestion.primaryLO = '8D';
objQuestion.textref = 'c. 8, p. 12';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '8D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Insurers can use several types of random sampling. To address the problems created by segmented populations, companies often use</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "stratified random sampling";
arrAnsChoices[1] = "simple random sampling";
arrAnsChoices[2] = "systematic random sampling";
arrAnsChoices[3] = "outlier random sampling";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 442002;
arrAnsIDs[1] = 442003;
arrAnsIDs[2] = 442004;
arrAnsIDs[3] = 442005;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Stratified random sampling is a technique in which the user divides the population into segments, or strata, and then selects a proportional number of items from each segment at random. Accordingly, a stratified random sample is one found by dividing the population into a number of distinct segments and then selecting cases at random and in proportion to segment size.</p><p class=\"explanations\"><b>Learning Objective: 8D. Describe random sampling and distinguish between random and nonrandom sampling.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Simple random sampling is usually most effective when population elements are homogeneous—that is, when the elements in the population are similar.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Systematic random sampling is usually most effective when population elements are homogeneous—that is, when the elements in the population are similar.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">An outlier is <b>not</b> a type of random sampling. An outlier is an extremely high or low value that is not representative of the other values in a given data population. </p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_079'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_080';
objQuestion.questionID = 109368;
objQuestion.item = 'LOMA_335_PPQ2019_080';
objQuestion.primaryLO = '8D';
objQuestion.textref = 'c. 8, p. 14';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '8D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Two measures of the validity of sample results are the degree of confidence and the margin of error. With regard to the effect of sample size on these two measures, it generally is correct to say that, compared to a smaller sample, a larger sample tends to produce a</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "lower degree of confidence and a smaller margin of error";
arrAnsChoices[1] = "lower degree of confidence but a larger margin of error";
arrAnsChoices[2] = "higher degree of confidence but a smaller margin of error";
arrAnsChoices[3] = "higher degree of confidence and a larger margin of error";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 442006;
arrAnsIDs[1] = 442007;
arrAnsIDs[2] = 442008;
arrAnsIDs[3] = 442009;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is correct to say that a larger sample size generally produces a smaller margin of error. However, the larger the sample size, the <b>higher</b> the degree of confidence.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">In general, the larger the sample size, the<b> higher</b> the degree of confidence and the <b>smaller</b> the margin of error.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Degree of confidence refers to the likelihood that a calculated value accurately predicts the true value. Margin of error indicates the likely range of inaccuracy of a given sample result relative to a result based on the total population. In general, the larger the sample size, the higher the degree of confidence and the smaller the margin of error.</p><p class=\"explanations\"><b>Learning Objective: 8D. Describe random sampling and distinguish between random and nonrandom sampling.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is correct to say that a larger sample size generally produces a higher degree of confidence. However, the larger the sample size, the <b>smaller</b> the margin of error.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_080'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_081';
objQuestion.questionID = 109369;
objQuestion.item = 'LOMA_335_PPQ2019_081';
objQuestion.primaryLO = '8E';
objQuestion.textref = 'c. 8, pp. 17, 19';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '8E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The elements of a decision model include decision alternatives and states of nature. With regard to whether decision alternatives and states of nature are under the control of the decision maker, it is correct to say that</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "both decision alternatives and states of nature are under the decision maker’s control";
arrAnsChoices[1] = "decision alternatives <i>are</i> under the decision maker’s control, whereas states of nature <i>are not</i> under the decision maker’s control";
arrAnsChoices[2] = "decision alternatives <i>are not</i> under the decision maker’s control, whereas states of nature <i>are</i> under the decision maker’s control";
arrAnsChoices[3] = "neither decision alternatives nor states of nature are under the decision maker’s control";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 442010;
arrAnsIDs[1] = 442011;
arrAnsIDs[2] = 442012;
arrAnsIDs[3] = 442013;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these elements is <b>not</b> under the decision maker’s control.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Decision alternatives are the options a decision maker considers before selecting a future course of action. Decision alternatives refer to elements under the control of the decision maker. In a model, states of nature are potential influences on the outcome of a decision that are not under the decision maker’s control.</p><p class=\"explanations\"><b>Learning Objective: 8E. Explain decision criteria, decision constraints, and states of nature and provide examples of each.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Decision alternatives refer to elements <b>under the control</b> of the decision maker. States of nature are potential influences on the outcome of a decision that <b>are not</b> under the decision maker’s control.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these elements is under the decision maker’s control.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_081'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_082';
objQuestion.questionID = 109370;
objQuestion.item = 'LOMA_335_PPQ2019_082';
objQuestion.primaryLO = '8E';
objQuestion.textref = 'c. 8, pp. 18-19';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '8E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">A manager in an insurer’s customer contact center is deciding whether to recommend buying a new customer routing system or keeping the existing routing system. The manager must keep the following elements in mind as he evaluates these two decision alternatives:</p><ul class=\"examul\"><li><b>Statement A</b>—No customer should wait more than a minute on the phone before speaking with a customer service representative.</li><li><b>Statement B</b>—The insurer’s equipment supports up to 30 customer service representatives at one time.</li></ul><p class=\"stem\">With regard to whether these statements best represent decision criteria or decision constraints, it is correct to say that</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "both Statement A and Statement B represent decision criteria";
arrAnsChoices[1] = "Statement A represents a decision criterion and Statement B represents a decision constraint";
arrAnsChoices[2] = "Statement A represents a decision constraint and Statement B represents a decision criterion";
arrAnsChoices[3] = "both Statement A and Statement B represent decision constraints";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 442014;
arrAnsIDs[1] = 442015;
arrAnsIDs[2] = 442016;
arrAnsIDs[3] = 442017;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements does <b>not</b> best represent a decision criterion.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Decision criteria are the simple-to-understand rules a decision maker uses to evaluate decision alternatives. They describe what the decision should achieve. To select an appropriate decision alternative, a decision maker considers the criteria as well as objectives and potential risks and rewards.</p><p class=\"explanations\">Decision constraints are practical limitations that affect the selection of decision alternatives. In business, these limitations often are resource limitations, such as budgets and staff time, regulatory requirements, or concerns about the impact of stock price on profitability in both the short and long term.</p><p class=\"explanations\"><b>Learning Objective: 8E. Explain decision criteria, decision constraints, and states of nature and provide examples of each.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement A best represents a decision <b>criterion</b>—a simple-to-understand rule that a decision maker uses to evaluate decision alternatives. Statement B best represents a decision <b>constraint</b>—a practical limitation, such as budgets and staff time, that affects the selection of decision alternatives.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements does <b>not</b> best represent a decision constraint.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_082'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_083';
objQuestion.questionID = 109371;
objQuestion.item = 'LOMA_335_PPQ2019_083';
objQuestion.primaryLO = '8F';
objQuestion.textref = 'c. 8, p. 21';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '8F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = 4;
objQuestion.strStem = "<p class=\"stem\">If Treetop uses an <i>arithmetic average model </i>based on the past four months, then it most likely will expect the number of customers who withdraw funds in June to be</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "409";
arrAnsChoices[1] = "430";
arrAnsChoices[2] = "435";
arrAnsChoices[3] = "446";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 442018;
arrAnsIDs[1] = 442019;
arrAnsIDs[2] = 442020;
arrAnsIDs[3] = 442021;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The arithmetic average model uses the arithmetic average of a series of values (the <i>mean</i>) from previous periods as the forecast value for the next future period. In this situation, Treetop would calculate the arithmetic average as (423 + 446 + 439 + 432) ÷ 4. The result of this calculation is <b>not</b> 409. </p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The arithmetic average model uses the arithmetic average of a series of values (the <i>mean</i>) from previous periods as the forecast value for the next future period. In this situation, Treetop would calculate the arithmetic average as (423 + 446 + 439 + 432) ÷ 4. The result of this calculation is <b>not</b> 430.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The arithmetic average model uses the arithmetic average of a series of values (the <i>mean</i>) from previous periods as the forecast value for the next future period. In this situation, Treetop would calculate the arithmetic average as (423 + 446 + 439 + 432) ÷ 4, or 435 customers.</p><p class=\"explanations\">The arithmetic average model gives equal weight to all data periods, regardless of the age of those periods. In many situations, recent data periods are more representative of future data than are earlier periods. </p><p class=\"explanations\"><b>Learning Objective: 8F. Describe forecasting models and give examples of types of forecasting models.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The arithmetic average model uses the arithmetic average of a series of values (the <i>mean</i>) from previous periods as the forecast value for the next future period. In this situation, Treetop would calculate the arithmetic average as (423 + 446 + 439 + 432) ÷ 4. The result of this calculation is <b>not</b> 446.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_083'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_084';
objQuestion.questionID = 109372;
objQuestion.item = 'LOMA_335_PPQ2019_084';
objQuestion.primaryLO = '8F';
objQuestion.textref = 'c. 8, pp. 21-22';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '8F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = 4;
objQuestion.strStem = "<p class=\"stem\">If Treetop uses a <i>three-month simple moving average model</i>, then it most likely will expect the number of customers who withdraw funds in June to be</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "435";
arrAnsChoices[1] = "436";
arrAnsChoices[2] = "439";
arrAnsChoices[3] = "446";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 442022;
arrAnsIDs[1] = 442023;
arrAnsIDs[2] = 442024;
arrAnsIDs[3] = 442025;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The simple moving average model requires finding the arithmetic average (mean) of data values, but it considers only a specified number, <i>n</i>, of the most recent data values. Each time the model is used, the data value from the oldest period is eliminated, and the data value from the most recent period is included.</p><p class=\"explanations\">In this situation, Treetop uses the three most recent months of data: March, April, and May. The arithmetic average of the data for these three months is <b>not</b> 435.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The simple moving average model requires finding the arithmetic average (mean) of data values, but it considers only a specified number, <i>n</i>, of the most recent data values. Each time the model is used, the data value from the oldest period is eliminated, and the data value from the most recent period is included.</p><p class=\"explanations\">In this situation, Treetop uses the three most recent months of data: March, April, and May. The arithmetic average of the data for these three months is <b>not</b> 436.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The simple moving average model requires finding the arithmetic average (mean) of data values, but it considers only a specified number, <i>n</i>, of the most recent data values. Each time the model is used, the data value from the oldest period is eliminated, and the data value from the most recent period is included.</p><p class=\"explanations\">In this situation, Treetop uses the three most recent months of data: March, April, and May. The arithmetic average of the data for these months equals 439: (446 + 439 + 432) ÷ 3. For the month of July, Treetop would calculate the arithmetic average for April, May, and June. A simple moving average forecast can more accurately reflect changing conditions than can the arithmetic average model. </p><p class=\"explanations\"><b>Learning Objective: 8F. Describe forecasting models and give examples of types of forecasting models.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The simple moving average model requires finding the arithmetic average (mean) of data values, but it considers only a specified number, <i>n</i>, of the most recent data values. Each time the model is used, the data value from the oldest period is eliminated, and the data value from the most recent period is included.</p><p class=\"explanations\">In this situation, Treetop uses the three most recent months of data: March, April, and May. The arithmetic average of the data for these three months is <b>not</b> 446.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_084'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_085';
objQuestion.questionID = 109373;
objQuestion.item = 'LOMA_335_PPQ2019_085';
objQuestion.primaryLO = '8F';
objQuestion.textref = 'c. 8, p. 22';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '8F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = 4;
objQuestion.strStem = "<p class=\"stem\">If Treetop calculates the estimate for June using a <i>weighted moving average time-series model</i> and assigns weights to the data for each of the previous four months, then it most likely will assign the greatest weight to the data from</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "February";
arrAnsChoices[1] = "March";
arrAnsChoices[2] = "April";
arrAnsChoices[3] = "May";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 442026;
arrAnsIDs[1] = 442027;
arrAnsIDs[2] = 442028;
arrAnsIDs[3] = 442029;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The weighted moving average time-series model assigns relative weights to the data values used in the forecast. Typically, more recent data are assigned a greater weight or importance than are older data; therefore, Treetop most likely will <b>not</b> assign the greatest weight to the data from February. </p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The weighted moving average time-series model assigns relative weights to the data values used in the forecast. Typically, more recent data are assigned a greater weight or importance than are older data; therefore, Treetop most likely will <b>not</b> assign the greatest weight to the data from March.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The weighted moving average time-series model assigns relative weights to the data values used in the forecast. Typically, more recent data are assigned a greater weight or importance than are older data; therefore, Treetop most likely will <b>not</b> assign the greatest weight to the data from April.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The weighted moving average time-series model assigns relative weights to the data values used in the forecast. Typically, more recent data are assigned a greater weight or importance than are older data. In this situation, Treetop most likely will assign the greatest weight to the data from May.</p><p class=\"explanations\"><b>Learning Objective: 8F. Describe forecasting models and give examples of types of forecasting models.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_085'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_086';
objQuestion.questionID = 109374;
objQuestion.item = 'LOMA_335_PPQ2019_086';
objQuestion.primaryLO = '8G';
objQuestion.textref = 'c. 8, pp. 23-24';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '8G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">A causal model uses historical data and other relevant variables as a basis for describing unknown future data points. A decision maker can use a causal model when a change in one value is associated with a consistent and equivalent change in the other value. This measure of whether, and how strongly, two values are related is known as </p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "estimates, which prove causation";
arrAnsChoices[1] = "estimates, which do not prove causation";
arrAnsChoices[2] = "correlation, which proves causation";
arrAnsChoices[3] = "correlation, which does not prove causation";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 442030;
arrAnsIDs[1] = 442031;
arrAnsIDs[2] = 442032;
arrAnsIDs[3] = 442033;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Estimates are <b>not</b> a measure of whether two values are related. Estimates refer to approximate values that represent unknowns in a forecasting model.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Estimates are <b>not</b> a measure of whether two values are related. Estimates refer to approximate values that represent unknowns in a forecasting model.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is correct to say that correlation is a measure of whether, and how strongly, two values are related. However, correlation does <b>not</b> prove causation. </p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Decision makers can use causal models when values show correlation. Values correlate when a change in one value is associated with a consistent and equivalent change (positive or negative) in the other value. If two sets of values correlate, researchers are able to use the value of one dataset to project the value of the other dataset. </p><p class=\"explanations\">We should note that correlation does not prove causation. In other words, two factors occurring together does not always mean that one caused the other.</p><p class=\"explanations\"><b>Learning Objective: 8G. Describe how inputs, outputs, point estimates, and range estimates are used in financial models.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_086'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_087';
objQuestion.questionID = 109375;
objQuestion.item = 'LOMA_335_PPQ2019_087';
objQuestion.primaryLO = '8H';
objQuestion.textref = 'c. 8, p. 26';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '8H';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">A conditional payoff table is a type of payoff table showing two or more states of nature. With regard to the rules governing the construction of a conditional payoff table, it is correct to say that the</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "list of decision alternatives must be complete";
arrAnsChoices[1] = "decision alternatives cannot be mutually exclusive";
arrAnsChoices[2] = "list of the states of nature can be incomplete";
arrAnsChoices[3] = "states of nature cannot be mutually exclusive";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 442034;
arrAnsIDs[1] = 442035;
arrAnsIDs[2] = 442036;
arrAnsIDs[3] = 442037;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A payoff table must present all decision alternatives under consideration, and these decision alternatives must be mutually exclusive. In addition, the list of the states of nature directly relevant to the decision must be complete and must be mutually exclusive.</p><p class=\"explanations\"><b>Learning Objective: 8H. Explain payoffs, and describe how a company uses payoff tables to conduct payoff analysis.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The decision alternatives <b>must</b> be mutually exclusive. In other words, a decision maker can only implement one option in the table. </p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The list of the states of nature must be <b>complete</b>. A payoff table should include all relevant states of nature.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The states of nature <b>must</b> be mutually exclusive. A payoff table must express the states of nature in such a way that only one state can occur.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_087'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_088';
objQuestion.questionID = 109376;
objQuestion.item = 'LOMA_335_PPQ2019_088';
objQuestion.primaryLO = '8I';
objQuestion.textref = 'c. 8, p. 28';
objQuestion.textbook = 0;
objQuestion.chapter = 8;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '8I';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following payoff table shows a dominant decision alternative:</p><table class=\"tbexam\" align=\"center\"><tr><td style=\"vertical-align: top; text-align: left; background-color: transparent; border: none;\"></td><td colspan=\"3\" style=\"vertical-align: top; text-align: center; background-color: #B2B2B2;\"><b>State of Nature: Demand</b></td></tr><tr><td style=\"vertical-align: top; text-align: left; background-color: transparent; border: none;\"></td><td style=\"vertical-align: top; text-align: center; background-color: #DCDCDC;\"><b>1. Heavy</b></td><td style=\"vertical-align: top; text-align: center; background-color: #DCDCDC;\"><b>2. Moderate</b></td><td style=\"vertical-align: top; text-align: center; background-color: #DCDCDC;\"><b>3. Light</b></td></tr><tr><td style=\"vertical-align: top; text-align: left; background-color: #DCDCDC;\">Option A</td><td style=\"vertical-align: top; text-align: center;\">$15,000</td><td style=\"vertical-align: top; text-align: center;\">($20,000)</td><td style=\"vertical-align: top; text-align: center;\">$5,000</td></tr><tr><td style=\"vertical-align: top; text-align: left; background-color: #DCDCDC;\">Option B</td><td style=\"vertical-align: top; text-align: center;\">$25,000</td><td style=\"vertical-align: top; text-align: center;\">$40,000</td><td style=\"vertical-align: top; text-align: center;\">$30,000</td></tr><tr><td style=\"vertical-align: top; text-align: left; background-color: #DCDCDC;\">Option C</td><td style=\"vertical-align: top; text-align: center;\">$20,000</td><td style=\"vertical-align: top; text-align: center;\">($45,000)</td><td style=\"vertical-align: top; text-align: center;\">$15,000</td></tr><tr><td style=\"vertical-align: top; text-align: left; background-color: #DCDCDC;\">Option D</td><td style=\"vertical-align: top; text-align: center;\">($15,000)</td><td style=\"vertical-align: top; text-align: center;\">$10,000</td><td style=\"vertical-align: top; text-align: center;\">($50,000)</td></tr><tr><td colspan=\"4\" style=\"vertical-align: top; text-align: center;\">* Values in parentheses are negative numbers.</td></tr></table><p class=\"stem\">With regard to this table, it is correct to say that the dominant decision alternative is</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Option A";
arrAnsChoices[1] = "Option B";
arrAnsChoices[2] = "Option C";
arrAnsChoices[3] = "Option D";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 442038;
arrAnsIDs[1] = 442039;
arrAnsIDs[2] = 442040;
arrAnsIDs[3] = 442041;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A dominant decision alternative is one that consistently produces the best expected payoff for all states of nature. In this payoff table, <b>Option B </b>is the dominant decision alternative because Option B’s expected payoff for all three states of nature is greater than those for the other options.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A dominant decision alternative is one that consistently produces the best expected payoff for all states of nature. In this payoff table, Option B is the dominant decision alternative because Option B’s expected payoff for all three states of nature is greater than those for the other options.</p><p class=\"explanations\"><b>Learning Objective: 8I. Evaluate the limitations of modeling in business.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A dominant decision alternative is one that consistently produces the best expected payoff for all states of nature. In this payoff table, <b>Option B</b> is the dominant decision alternative because Option B’s expected payoff for all three states of nature is greater than those for the other options.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A dominant decision alternative is one that consistently produces the best expected payoff for all states of nature. In this payoff table, <b>Option B</b> is the dominant decision alternative because Option B’s expected payoff for all three states of nature is greater than those for the other options.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_088'] = objQuestion;



arrMinicases[3] = "<p class=\"caseinfo\">Use the following information to answer questions 1 through 3. </p><p class=\"caseinfo\">The Maple Insurance Company has the following report showing the number of life insurance claims processed in each month for the past six months:</p><ul class=\"examul\"><li>January = 100</li><li>February = 150</li><li>March = 180</li><li>April = 160</li><li>May = 210</li><li>June = 190</li></ul>";
arrMinicases[4] = "<p class=\"caseinfo\">Use the following information to answer questions 11 through 13.</p><p class=\"caseinfo\">Treetop Financial tracks the number of customers who withdraw funds from its products and uses those results to forecast the number of customers who will make withdrawals in future months. The following table shows the number of customers who withdrew funds in the past four months:</p><ul class=\"examul\"><li>February: 423 customers</li><li>March: 446 customers</li><li>April: 439 customers</li><li>May: 432 customers</li></ul>";


var arrlotext = new Array(); 
arrlotext['8A'] = "8A. Calculate measures of central tendency and dispersion.";
arrlotext['8B'] = "8B. Distinguish between descriptive and inferential statistics.";
arrlotext['8C'] = "8C. Describe the importance of the law of large numbers to inferential statistics.";
arrlotext['8D'] = "8D. Describe random sampling and distinguish between random and nonrandom sampling.";
arrlotext['8E'] = "8E. Explain decision criteria, decision constraints, and states of nature and provide examples of each.";
arrlotext['8F'] = "8F. Describe forecasting models and give examples of types of forecasting models.";
arrlotext['8G'] = "8G. Describe how inputs, outputs, point estimates, and range estimates are used in financial models.";
arrlotext['8H'] = "8H. Explain payoffs and describe how a company uses payoff tables to conduct payoff analysis.";
arrlotext['8I'] = "8I. Evaluate the limitations of modeling in business.";
