var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2019';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 361 Practice Questions, Chapter 15";
var coursename = 'LOMA 361';
var modulenumber = 3;
var title = "LOMA_361_PPQ2019_0_15";
var intNumPools = 1;
var numQ = 7;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Accounting and Financial Reporting in Life Insurance Companies, Second Edition (2019)";
arrNumChap[0] = 1;
var thisChap = '15';

objPool = new Object(); 
objPool.intSelectCount = 7;
objPool.formID = 2103;
objPool.formName = 'PPQ2019_0_15';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_361_PQ_122';
arrPoolQuestions[1] = 'LOMA_361_PQ_123';
arrPoolQuestions[2] = 'LOMA_361_PQ_124';
arrPoolQuestions[3] = 'LOMA_361_PQ_125';
arrPoolQuestions[4] = 'LOMA_361_PQ_126';
arrPoolQuestions[5] = 'LOMA_361_PQ_127';
arrPoolQuestions[6] = 'LOMA_361_PQ_128';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_122';
objQuestion.questionID = 110308;
objQuestion.item = 'LOMA_361_PPQ2019_122';
objQuestion.primaryLO = '15A';
objQuestion.textref = 'c. 15, pp. 2-3';
objQuestion.textbook = 0;
objQuestion.chapter = 15;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '15A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The budgeting process has many advantages, as well as some disadvantages. Among its <i>advantages</i>, the budgeting process enables a company to</p><ol type=\"A\" class=\"combo\"><li>Monitor and evaluate ongoing operations</li><li>Motivate employees</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445816;
arrAnsIDs[1] = 445817;
arrAnsIDs[2] = 445818;
arrAnsIDs[3] = 445819;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Budgeting enables a company to communicate information throughout the company, allocate scarce resources effectively, control and reduce expenses, prioritize necessary technological improvements, monitor and evaluate ongoing operations, evaluate managerial performance, and motivate employees.</p><p class=\"explanations\">Budgeting also has some possible disadvantages, including the potential for management to consume too much time, spend unnecessary amounts, overestimate costs, avoid innovation, and disregard quality and customer service.</p><p class=\"explanations\"><b>Learning Objective: 15A. Describe the advantages and disadvantages of budgeting.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct; however, Statement B is also correct.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is correct; however, Statement A is also correct.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_122'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_123';
objQuestion.questionID = 110309;
objQuestion.item = 'LOMA_361_PPQ2019_123';
objQuestion.primaryLO = '15B';
objQuestion.textref = 'c. 15, p. 4';
objQuestion.textbook = 0;
objQuestion.chapter = 15;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '15B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Most companies prefer to use one or more of the following approaches to the budgeting process: top-down budgeting, bottom-up budgeting, zero-based budgeting, and activity-based budgeting. In a comparison of top-up budgeting and bottom -down budgeting, it is correct to say that</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "top-down budgeting takes considerably more time to prepare than does bottom-up budgeting";
arrAnsChoices[1] = "top-down budgeting typically has more grassroots support among company employees than does bottom-up budgeting";
arrAnsChoices[2] = "bottom-up budgeting is more likely to reflect top management’s intentions for the company than is top-down budgeting";
arrAnsChoices[3] = "bottom-up budgeting is more likely to reflect the realities of a company’s core business operations than is top-down budgeting";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445820;
arrAnsIDs[1] = 445821;
arrAnsIDs[2] = 445822;
arrAnsIDs[3] = 445823;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Compared to top-down budgeting, <b>bottom-up budgeting</b> typically takes more time and includes a larger number of employees.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Compared to top-down budgeting, <b>bottom-up budgeting</b> typically includes a larger number of employees and often has more grassroots support among company employees.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Top-down budgeting is a method for developing a budget that begins with a company’s <b>senior management</b> and is passed down to lower-level management. Senior management bases a top-down budget’s monetary amounts both on the <b>strategic plan</b> and on financial information about the company’s activities in prior years.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Top-down budgeting begins with a company’s senior management and is passed down to lower-level management. Senior management bases a top-down budget’s monetary amounts both on the strategic plan and on financial information about the company’s activities in prior years.</p><p class=\"explanations\">Bottom-up budgeting starts at the bottom of a company, with lower-level managers generating budgets for their areas, which they then present in the form of recommendations to senior management. Bottom-up budgets reflect the input and participation of the area managers and employees who will be responsible for achieving the company’s goals.</p><p class=\"explanations\">Compared to top-down budgeting, bottom-up budgeting typically takes more time and includes a larger number of employees, is more likely to reflect the realities of the company’s core business operations, and often has more grassroots support among company employees.</p><p class=\"explanations\"><b>Learning Objective: 15B. Identify the relative strengths of top-down budgeting, bottom-up budgeting, zero-based budgeting, and activity-based budgeting.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_123'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_124';
objQuestion.questionID = 110310;
objQuestion.item = 'LOMA_361_PPQ2019_124';
objQuestion.primaryLO = '15B';
objQuestion.textref = 'c. 15, pp. 4-5';
objQuestion.textbook = 0;
objQuestion.chapter = 15;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '15B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about zero-based budgeting (ZBB). Select the answer choice containing the correct statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "ZBB generally applies only to a company’s revenue budgets.";
arrAnsChoices[1] = "ZBB assumes that current-year expense levels are reasonable starting points for developing a budget for the next accounting period.";
arrAnsChoices[2] = "Higher-level management typically provides all the details necessary to prepare a zero-based budget.";
arrAnsChoices[3] = "ZBB treats each activity and function as though it is a new project under consideration.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445824;
arrAnsIDs[1] = 445825;
arrAnsIDs[2] = 445826;
arrAnsIDs[3] = 445827;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Zero-based budgeting generally applies only to a company’s <b>expense</b> budgets.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Unlike the top-down and bottom-up budgeting approaches, ZBB does <b>not</b> automatically assume that current-year expense levels are reasonable starting points for developing the expense budget for the next accounting period. Instead, ZBB imposes cost analysis on all levels of management to evaluate each activity in terms of efficiency and need. In essence, ZBB treats each activity and function as though it is a new project under consideration. In other words, planners must begin each accounting period at “zero.” For every accounting period, each responsibility center must justify its continued existence and operation.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Unlike the top-down and bottom-up budgeting approaches, ZBB does not automatically assume that current-year expense levels are reasonable starting points for developing the expense budget for the next accounting period. Instead, ZBB imposes cost analysis on <b>all</b> levels of management to evaluate each activity in terms of efficiency and need. In essence, ZBB treats each activity and function as though it is a new project under consideration. In other words, planners must begin each accounting period at “zero.” For every accounting period, each responsibility center must justify its continued existence and operation.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Under ZBB, a company allocates resources only if expense amounts are linked to the company’s strategic and operational goals. ZBB generally applies only to a company’s expense budgets. Many companies use a modified ZBB process.</p><p class=\"explanations\">Unlike the top-down and bottom-up budgeting approaches, ZBB does not automatically assume that current-year expense levels are reasonable starting points for developing the expense budget for the next accounting period. In other words, planners must begin each accounting period at “zero.” For every accounting period, each responsibility center must justify its continued existence and operation.</p><p class=\"explanations\"><b>Learning Objective: 15B. Identify the relative strengths of top-down budgeting, bottom-up budgeting, zero-based budgeting, and activity-based budgeting.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_124'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_125';
objQuestion.questionID = 110311;
objQuestion.item = 'LOMA_361_PPQ2019_125';
objQuestion.primaryLO = '15C';
objQuestion.textref = 'c. 15, pp. 7-9';
objQuestion.textbook = 0;
objQuestion.chapter = 15;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '15C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Acacia Life Insurance Company recently prepared a quarterly budget for sales commissions for a new product. This budget provided alternative sets of budget estimates to use under different circumstances that may arise during the accounting period. This information indicates that Acacia used the type of budget known as a</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "static, long-term budget";
arrAnsChoices[1] = "static, short-term budget";
arrAnsChoices[2] = "flexible, long-term budget";
arrAnsChoices[3] = "flexible, short-term budget";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445828;
arrAnsIDs[1] = 445829;
arrAnsIDs[2] = 445830;
arrAnsIDs[3] = 445831;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Acacia’s budget is <b>not</b> a static budget. A static budget <b>lacks</b> the flexibility to provide alternate financial projections when a company’s experience differs from the assumptions underlying the budgeted figures. In addition, Acacia’s budget is <b>not</b> a long-term budget. A long-term budget, also called a strategic budget, generally covers periods of <b>more </b>than one year.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that Acacia’s budget is a short-term budget. However, Acacia’s budget is <b>not</b> a static budget, which <b>lacks</b> the flexibility to provide alternate financial projections when a company’s experience differs from the assumptions underlying the budgeted figures.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that Acacia’s budget is a flexible budget. However, Acacia’s budget is <b>not</b> a long-term budget, also called a strategic budget, which generally covers periods of <b>more </b>than one year.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A flexible budget, also known as a flexible-amount budget, a dynamic budget, or a variable budget, commonly focuses on the company’s projections for the best-case, worst-case, and expected levels of activity. The amounts in a static budget, also known as a fixed or a fixed-amount budget, are generally not subject to change unless management has approved the changes.</p><p class=\"explanations\">A period budget—which may be short-term or long-term—covers a specific time frame, and expires at the end of that time frame. A short-term budget, also called an operating budget, generally covers a period of one year or less and relates mainly to a company’s operations during that period. A long-term budget, also called a strategic budget, generally covers periods of more than one year.</p><p class=\"explanations\"><b>Learning Objective: 15C. Differentiate between static budgets and flexible budgets, short-term budgets and long-term budgets, and rolling budgets and period budgets.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_125'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_126';
objQuestion.questionID = 110312;
objQuestion.item = 'LOMA_361_PPQ2019_126';
objQuestion.primaryLO = '15D';
objQuestion.textref = 'c. 15, p. 11';
objQuestion.textbook = 0;
objQuestion.chapter = 15;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '15D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Portico Life Insurance Company is preparing expense budgets in order to complete the operational budget. One of Portico’s expense budgets indicates the amount of money Portico expects to pay for insurance policy or annuity contract benefits, such as claims, cash surrenders, and policyowner dividends, during the next accounting period. This expense budget is known as the</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "sales expense budget, and the expenses typically are fixed expenses";
arrAnsChoices[1] = "sales expense budget, and the expenses typically are variable expenses";
arrAnsChoices[2] = "benefits budget, and the expenses typically are fixed expenses";
arrAnsChoices[3] = "benefits budget, and the expenses typically are variable expenses";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445832;
arrAnsIDs[1] = 445833;
arrAnsIDs[2] = 445834;
arrAnsIDs[3] = 445835;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">This expense budget is <b>not</b> a sales expense budget, which indicates the costs incurred in selling insurance. In addition, the expenses described in Portico’s expense budget typically are <b>not</b> fixed expenses.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that the expenses described in Portico’s expense budget typically are variable expenses. However, this expense budget is <b>not</b> a sales expense budget, which indicates the costs incurred in selling insurance.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that Portico’s expense budget is a benefits budget. However, most expenses in benefits budgets are <b>variable</b> expenses, because these expenses vary with changes in sales volume.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">An operational budget covers part or all of a company’s core business operations, such as underwriting and claims. Two basic types of operational budgets are revenue budgets and expense budgets. An expense budget is a schedule of expenses expected during an accounting period. Common components of the expense budget for insurance companies include the benefits budget, the sales expense budget, and the general and administrative expense budget.</p><p class=\"explanations\">The sales expense budget indicates the costs incurred—commissions, advertising, promotions, travel, branch office operations, and salaries for marketing staff—in selling insurance. Most expenses in benefits and sales expense budgets are variable expenses, because these expenses vary with changes in sales volume. The general and administrative expense budget includes expenses—typically fixed expenses—needed for insurance company operations, such as administrative salaries, rent, and utilities.</p><p class=\"explanations\"><b>Learning Objective: 15D. Describe the key budgets that are part of a master budget.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_126'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_127';
objQuestion.questionID = 110313;
objQuestion.item = 'LOMA_361_PPQ2019_127';
objQuestion.primaryLO = '15D';
objQuestion.textref = 'c. 15, pp. 12-13';
objQuestion.textbook = 0;
objQuestion.chapter = 15;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '15D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">One piece of information contained in a company’s cash budget is the available cash for the period. Available cash for the period can be defined as the company’s</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "available cash minus cash needed for the period";
arrAnsChoices[1] = "excess cash or shortage of cash plus any borrowing or repayment activity";
arrAnsChoices[2] = "beginning cash balance plus cash receipts expected during the period";
arrAnsChoices[3] = "amount of cash that the company determines is necessary to pay all obligations in an accounting period without having excess cash";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445836;
arrAnsIDs[1] = 445837;
arrAnsIDs[2] = 445838;
arrAnsIDs[3] = 445839;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The <b>excess cash</b> <b>or cash shortage</b> is equal to the available cash minus cash needed for the period.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The <b>ending cash balance </b>is equal to the excess cash or shortage of cash plus any borrowing or repayment activity.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A cash budget projects a company’s beginning cash balance, cash inflows, cash outflows, and ending cash balance for a specified accounting period, typically by quarter. A cash budget consists of a cash receipts budget (cash inflows) and a cash disbursements budget (cash outflows).</p><p class=\"explanations\">Information contained in the cash budget includes the beginning cash balance; available cash for the period; minimum cash balance; cash needed for the period; excess cash or cash shortage; amount of any cash borrowed or repaid, including interest; and the ending cash balance. The minimum cash balance is the amount of cash that a company determines is necessary to pay all obligations in an accounting period without having excess cash.</p><p class=\"explanations\"><b>Learning Objective: 15D. Describe the key budgets that are part of a master budget.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The <b>minimum cash balance</b> is the amount of cash that a company determines is necessary to pay all obligations in an accounting period without having excess cash.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_127'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_128';
objQuestion.questionID = 110314;
objQuestion.item = 'LOMA_361_PPQ2019_128';
objQuestion.primaryLO = '15E';
objQuestion.textref = 'c. 15, p. 14';
objQuestion.textbook = 0;
objQuestion.chapter = 15;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '15E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">A company’s master budget typically consists of several key types of budgets, including a capital budget. A capital budget most likely would show</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "a company’s plans for the financial management of its long-term, high-cost investment proposals";
arrAnsChoices[1] = "an estimate of the timing and amount of cash inflows that a company expects to receive during the accounting period";
arrAnsChoices[2] = "an estimate of the timing and amount of cash outflows that a company expects to incur during the accounting period";
arrAnsChoices[3] = "an estimate of the expected amount of investment income of bonds, stocks, mortgages, and other invested assets that a company owns";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445840;
arrAnsIDs[1] = 445841;
arrAnsIDs[2] = 445842;
arrAnsIDs[3] = 445843;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">In the context of capital budgeting, the word “investment” typically does not refer to the direct purchase of bonds, mortgages, or stocks. Rather, these long-term, high-cost investments include: new investments in equipment or real estate; remodeling of or major repairs to existing capital investments; acquisitions of other companies or lines of business; mandated safety and environmental improvements; expense reduction projects; purchases of new computer systems and equipment; and revenue expansion projects. A common trait of capital budgeting is that these investments are expected to produce income or other benefits for more than one year.</p><p class=\"explanations\"><b>Learning Objective: 15E. Explain the purpose of capital budgeting and the purpose of pro forma financial statements.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A company plans for its cash inflows through a <b>cash receipts budget</b>, which is a schedule of cash receipts expected during the accounting period. To predict both the timing and amount of its cash receipts, a company constructs the cash receipts budget using data from both the sales and investment forecasts.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">In the <b>cash disbursements budget</b>, an insurer estimates the timing and amount of cash disbursements (cash outflows) expected during the accounting period. Estimating cash disbursements for fixed expenses such as salaries is relatively easy and accurate. Cash disbursements for variable expenses, such as contractual benefit payments and commissions, can be less predictable. The accuracy of these predictions depends in large part on the accuracy of the sales forecast.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">An <b>investment budget</b> is a revenue budget that projects the types of investments the insurer will make and the expected amount of investment income for each type of invested asset, such as bonds, mortgages, and stocks.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_128'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['15A'] = "15A. Describe the advantages and disadvantages of budgeting.";
arrlotext['15B'] = "15B. Identify the relative strengths of top-down budgeting, bottom-up budgeting, zero-based budgeting, and activity-based budgeting.";
arrlotext['15C'] = "15C. Differentiate between static budgets and flexible budgets, short-term budgets and long-term budgets, and rolling budgets and period budgets.";
arrlotext['15D'] = "15D. Describe the key budgets that are part of a master budget.";
arrlotext['15E'] = "15E. Explain the purpose of capital budgeting and the purpose of pro forma financial statements.";
