var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2019';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 361 Practice Questions, Chapter 12";
var coursename = 'LOMA 361';
var modulenumber = 3;
var title = "LOMA_361_PPQ2019_0_12";
var intNumPools = 1;
var numQ = 6;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Accounting and Financial Reporting in Life Insurance Companies, Second Edition (2019)";
arrNumChap[0] = 1;
var thisChap = '12';

objPool = new Object(); 
objPool.intSelectCount = 6;
objPool.formID = 2103;
objPool.formName = 'PPQ2019_0_12';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_361_PQ_099';
arrPoolQuestions[1] = 'LOMA_361_PQ_100';
arrPoolQuestions[2] = 'LOMA_361_PQ_101';
arrPoolQuestions[3] = 'LOMA_361_PQ_102';
arrPoolQuestions[4] = 'LOMA_361_PQ_103';
arrPoolQuestions[5] = 'LOMA_361_PQ_104';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_099';
objQuestion.questionID = 110285;
objQuestion.item = 'LOMA_361_PPQ2019_099';
objQuestion.primaryLO = '12A';
objQuestion.textref = 'c. 12, p. 3';
objQuestion.textbook = 0;
objQuestion.chapter = 12;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '12A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The exact classification of responsibility centers varies from company to company, but in general, responsibility centers take four specific forms: cost centers, revenue centers, profit centers, and investment centers. Of these centers, the type(s) of centers in which a responsibility manager has control over <i>both</i> costs (expenses) and revenues associated with the center include</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "cost centers, revenue centers, profit centers, and investment centers";
arrAnsChoices[1] = "revenue centers, profit centers, and investment centers only";
arrAnsChoices[2] = "revenue centers and profit centers only";
arrAnsChoices[3] = "profit centers and investment centers only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445723;
arrAnsIDs[1] = 445724;
arrAnsIDs[2] = 445725;
arrAnsIDs[3] = 445726;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that a responsibility manager has control over both costs (expenses) and revenues associated with the center in a profit center and in an investment center. However, responsibility managers of cost centers and revenue centers do <b>not</b> control both costs (expenses) and revenues.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that a responsibility manager has control over both costs (expenses) and revenues associated with the center in a profit center and in an investment center. However, responsibility managers of revenue centers do <b>not</b> control both costs (expenses) and revenues.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that a responsibility manager has control over both costs (expenses) and revenues associated with the center in a profit center. However, responsibility managers of revenue centers do <b>not</b> control both costs (expenses) and revenues.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A profit center is a department or other business segment to which both costs (expenses) and revenues can be traced. An investment center is a department or division to which costs (expenses), revenues, and capital or investment funds can be traced. Responsibility managers have control over both costs (expenses) and revenues associated with the center in a profit center and in an investment center.</p><p class=\"explanations\">A cost center is a department or division to which costs (expenses) can be traced; however, cost centers do not directly generate or control revenues. Similarly, a revenue center is a department or division to which revenues can be traced; revenue centers do not directly control costs (expenses).</p><p class=\"explanations\"><b>Learning Objective: 12A. Define <i>responsibility accounting</i> and identify the features of four types of responsibility centers: cost centers, revenue centers, profit centers, and investment centers.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_099'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_100';
objQuestion.questionID = 110286;
objQuestion.item = 'LOMA_361_PPQ2019_100';
objQuestion.primaryLO = '12A';
objQuestion.textref = 'c. 12, pp. 4-5; c. 13, pp. 3-4';
objQuestion.textbook = 0;
objQuestion.chapter = 12;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '12A';
arrLOs[1] = '13A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">To establish and evaluate distinct responsibility centers, a company must be able to separate a responsibility center’s expenses into (1) controllable costs and noncontrollable costs and (2) direct costs and indirect costs. A responsibility manager in an insurer’s underwriting department is considering two costs: the cost of a wellness program that the insurer has made available to all company employees, and the cost of overtime pay within the underwriting department. From the perspective of this responsibility manager, the cost of the wellness program for all company employees most likely would be classified as both a</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "controllable cost and a direct cost, and the cost of overtime pay within the underwriting department also would be classified as a controllable cost and a direct cost";
arrAnsChoices[1] = "controllable cost and a direct cost, but the cost of overtime pay within the underwriting department would be classified as a noncontrollable cost and an indirect cost";
arrAnsChoices[2] = "noncontrollable cost and an indirect cost, but the cost of overtime pay within the underwriting department would be classified as a controllable cost and a direct cost";
arrAnsChoices[3] = "noncontrollable cost and an indirect cost, and the cost of overtime pay within the underwriting department also would be classified as a noncontrollable cost and an indirect cost";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445727;
arrAnsIDs[1] = 445728;
arrAnsIDs[2] = 445729;
arrAnsIDs[3] = 445730;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that, from the perspective of the underwriting responsibility manager, the cost of overtime pay within the underwriting department most likely would be classified as both a controllable cost and a direct cost. However, the cost of the wellness program that the insurer has made available to all company employees most likely would <b>not</b> be classified as a controllable cost or a direct cost.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">From the perspective of the underwriting responsibility manager, the cost of the wellness program that the insurer has made available to all company employees most likely would <b>not</b> be classified as a controllable cost or a direct cost. In addition, the cost of overtime pay within the underwriting department most likely would <b>not</b> be classified as a noncontrollable cost and an indirect cost.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A controllable cost is a cost over which a responsibility manager has decision-making authority. For example, the costs of supplies, travel, and overtime pay are controllable costs within a department because the responsibility manager can decide whether or not these costs should be incurred.</p><p class=\"explanations\"></p><p class=\"explanations\">A direct cost is identified specifically with a single cost object. A cost object is any purpose for which a company measures costs. Sample cost objects include product lines, employee salaries, customer service, and so on. A simple way to determine whether a cost is a direct cost of a specified cost object is to ask: Would the cost disappear if the cost object disappeared? If the answer is yes, then the cost is a direct cost.</p><p class=\"explanations\"><b>Learning Objective: (1) 12A. Define <i>responsibility accounting</i> and identify the features of four types of responsibility centers: cost centers, revenue centers, profit centers, and investment centers; (2) 13A. Identify and distinguish costs that are classified by description, behavior, and measurement.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that, from the perspective of the underwriting responsibility manager, the cost of the wellness program that the insurer has made available to all company employees most likely would be classified as a noncontrollable cost and an indirect cost. However, the cost of overtime pay within the underwriting department most likely would <b>not</b> be classified as a noncontrollable cost and an indirect cost.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_100'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_101';
objQuestion.questionID = 110287;
objQuestion.item = 'LOMA_361_PPQ2019_101';
objQuestion.primaryLO = '12B';
objQuestion.textref = 'c. 12, pp. 6-7';
objQuestion.textbook = 0;
objQuestion.chapter = 12;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '12B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Variance analysis is the study of the difference between expected or assumed results and actual results. Variances can be categorized as positive variances or negative variances. With regard to the significance of variances, it is correct to say that <i>negative</i> variances typically are considered</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "unfavorable for both revenue items and expense items";
arrAnsChoices[1] = "favorable for expense items, but unfavorable for revenue items";
arrAnsChoices[2] = "favorable for revenue items, but unfavorable for expense items";
arrAnsChoices[3] = "favorable for both revenue items and expense items";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445731;
arrAnsIDs[1] = 445732;
arrAnsIDs[2] = 445733;
arrAnsIDs[3] = 445734;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that negative variances are considered unfavorable for revenues because actual revenues are lower than expected. However, negative variances are considered <b>favorable </b>for expenses because actual expenses are lower than expected.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A positive variance is generally one in which the actual amount or percentage of an amount is greater than expected. A positive variance is considered favorable for revenues because actual revenues are higher than expected, and unfavorable for expenses because actual expenses are higher than expected.</p><p class=\"explanations\">A negative variance is generally a variance in which the actual amount or percentage of an amount is less than expected. A negative variance is considered unfavorable for revenues because actual revenues are lower than expected, and favorable for expenses because actual expenses are lower than expected.</p><p class=\"explanations\"><b>Learning Objective: 12B. Describe how variance analysis is used to measure and evaluate the performance of responsibility centers.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Negative variances are considered <b>favorable</b> for expenses because actual expenses are lower than expected. Negative variances are considered <b>unfavorable </b>for revenues because actual revenues are lower than expected.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that negative variances are considered favorable for expense items because actual expenses are lower than expected. However, negative variances are considered <b>unfavorable </b>for revenues because actual revenues are lower than expected.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_101'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_102';
objQuestion.questionID = 110288;
objQuestion.item = 'LOMA_361_PPQ2019_102';
objQuestion.primaryLO = '12B';
objQuestion.textref = 'c. 12, pp. 8-9';
objQuestion.textbook = 0;
objQuestion.chapter = 12;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '12B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Analysts at the Indigo Life Insurance Company reviewed the following budget-to-actual results for the policy issue department:</p><table class=\"tbexam\" align=\"center\"><tr><td style=\"vertical-align: top; text-align: left; background-color: #DCDCDC; background-color: transparent; border: none;\">&nbsp;</td><td style=\"vertical-align: top; text-align: center; background-color: #DCDCDC;\"><b>Budget</b></td><td style=\"vertical-align: top; text-align: center; background-color: #DCDCDC;\"><b>Actual</b></td></tr><tr><td style=\"vertical-align: top; text-align: left;\">Unit cost of issuing one policy</td><td style=\"vertical-align: top; text-align: center;\">$25</td><td style=\"vertical-align: top; text-align: center;\">$22</td></tr><tr><td style=\"vertical-align: top; text-align: left;\">Number of policies issued</td><td style=\"vertical-align: top; text-align: center;\">2,300</td><td style=\"vertical-align: top; text-align: center;\">2,500</td></tr></table><p class=\"stem\">This information indicates that the <i>total</i> variance for Indigo’s policy issue department is equal to a</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "–$1,900 positive unfavorable total variance";
arrAnsChoices[1] = "$5,000 positive favorable total variance";
arrAnsChoices[2] = "–$2,500 negative favorable total variance";
arrAnsChoices[3] = "$5,000 negative unfavorable total variance";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445735;
arrAnsIDs[1] = 445736;
arrAnsIDs[2] = 445737;
arrAnsIDs[3] = 445738;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Indigo’s <b>–$2,500 negative favorable total variance</b> is calculated by adding the negative favorable rate variance of –&nbsp;7,500 [($22 – $25) × 2,500] to the positive unfavorable usage variance of $5,000 [(2,500 – 2,300) × $25].</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Indigo’s <b>–$2,500 negative favorable total variance</b> is calculated by adding the negative favorable rate variance of –&nbsp;7,500 [($22 – $25) × 2,500] to the positive unfavorable usage variance of $5,000 [(2,500 – 2,300) × $25].</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A product’s rate variance is the difference between the product’s actual rate (or unit cost or unit price) and the standard rate budgeted for that product, multiplied by the actual number of units sold or processed: Rate variance = (Actual rate – Standard rate) × Actual number of units sold or processed. Indigo’s rate variance is calculated as ($22 – $25), multiplied by 2,500 policies issued, which is equal to –&nbsp;$7,500. The rate variance is negative and favorable because Indigo’s actual cost is lower than its budgeted cost.</p><p class=\"explanations\">A product’s usage variance is the difference between the actual quantities sold or processed and the budgeted (standard) quantities to be sold or processed, multiplied by the standard rate or unit cost: Usage variance = (Actual quantities sold or processed – Standard quantities sold or processed) × Standard rate. Indigo’s usage variance is calculated as (2,500 – 2,300) multiplied by $25, which is equal to $5,000. The usage variance is positive and unfavorable because Indigo processed 200 more policies than budgeted.</p><p class=\"explanations\">Total variance = Rate variance + Usage variance. In this situation, Indigo’s –$2,500 negative favorable total variance is calculated by adding the negative favorable rate variance of –&nbsp;$7,500 [($22 – $25) × 2,500] to the positive unfavorable usage variance of $5,000 [(2,500 – 2,300) × $25].</p><p class=\"explanations\"><b>Learning Objective: 12B. Describe how variance analysis is used to measure and evaluate the performance of responsibility centers.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Indigo’s <b>–$2,500 negative favorable total variance</b> is calculated by adding the negative favorable rate variance of –&nbsp;7,500 [($22 – $25) × 2,500] to the positive unfavorable usage variance of $5,000 [(2,500 – 2,300) × $25].</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_102'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_103';
objQuestion.questionID = 110289;
objQuestion.item = 'LOMA_361_PPQ2019_103';
objQuestion.primaryLO = '12C';
objQuestion.textref = 'c. 12, p. 10';
objQuestion.textbook = 0;
objQuestion.chapter = 12;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '12C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">One type of responsibility report shows revenues and expenses—divided into fixed and variable components and direct and indirect costs—for a single responsibility center. By definition, this report is known as a</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "revenue allocation report";
arrAnsChoices[1] = "management by exception (MBE) report";
arrAnsChoices[2] = "segment report";
arrAnsChoices[3] = "management by objectives (MBO) report";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445739;
arrAnsIDs[1] = 445740;
arrAnsIDs[2] = 445741;
arrAnsIDs[3] = 445742;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">This report is <b>not</b> a revenue allocation report. Revenue allocation is the accounting process of assigning or distributing income or revenue items according to a specified method or formula.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">This report is <b>not</b> a management by exception (MBE) report. MBE is a management style that focuses on results that deviate from an established baseline. In MBE, managers are alerted only when actual results vary by a specified amount or percentage from expected results, so managers spend less time monitoring results and more time on other tasks.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Responsibility reports can serve to (1) assist senior management in controlling responsibility center performance and (2) enable each responsibility manager to uncover information about the center’s costs, including how to improve cost control during the current and next accounting periods.</p><p class=\"explanations\">For profit centers, a segment report generally takes the form of an income statement. Segment reports separate direct costs and indirect costs at each management level. Although segment reporting is primarily a management accounting tool, segment reports are sometimes required for financial reporting purposes.</p><p class=\"explanations\"><b>Learning Objective: 12C. Compare a responsibility report to the responsibility reports of the organizational level directly above and directly below the responsibility center.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">This report is <b>not</b> called a management by objectives (MBO) report. MBO is a management style that focuses on achieving specific goals commonly agreed upon by management and employees.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_103'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_104';
objQuestion.questionID = 110290;
objQuestion.item = 'LOMA_361_PPQ2019_104';
objQuestion.primaryLO = '12D';
objQuestion.textref = 'c. 12, p. 14';
objQuestion.textbook = 0;
objQuestion.chapter = 12;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '12D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Arcade Life Insurance Group allocates investment income to lines of business based on the reserves that are attributable to each line. For example, because 35% of Arcade’s reserves are attributable to the individual annuities line of business, Arcade allocates 35% of its investment income to the individual annuities responsibility center. This information indicates that Arcade uses the investment income allocation method known as the</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "transfer pricing method";
arrAnsChoices[1] = "investment segmentation method";
arrAnsChoices[2] = "investment year method";
arrAnsChoices[3] = "mean liabilities method";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445743;
arrAnsIDs[1] = 445744;
arrAnsIDs[2] = 445745;
arrAnsIDs[3] = 445746;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A <b>transfer price</b> is the price of a good or service that one function or line of business charges another of the same company. For example, the human resources department of an insurer may use transfer pricing to charge the insurer’s group life insurance line of business for employee recruitment or training expenses. Transfer pricing is especially important for insurance companies that have subsidiaries or are themselves subsidiaries.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">In the <b>investment segmentation method</b>, an insurer uses the cash flows of a line of business to purchase specific investments for that line. The insurer in turn allocates the investment income from each investment to the line that acquired the investment. Under this method, an insurer can develop separate investment strategies for different lines of business.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The <b>investment year method</b> forms separate investment pools that contain the investments made during each year, and then, a share of the investment pool for each calendar year is allocated to each line of business. Each line’s share of investment income is determined by the investable funds generated by that line each year. Investable funds consist of net income before taxes, investment income received on prior investments, and the maturities of principal on prior investments.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The mean liabilities method allocates investment income to lines of business based on the reserves that are attributable to each line. This method does not consider the impact of the surplus required to support a line of business. Newer lines of business may suffer from a lack of resources if they are not allocated a share of the investment income generated by older, high-yielding investments that were purchased before the new products existed. The mean liabilities method is used in preparing the U.S. Annual Statement.</p><p class=\"explanations\"><b>Learning Objective: 12D. Describe the issues that must be considered in evaluating the performance of a responsibility center.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_104'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['12A'] = "12A. Define <i>responsibility accounting</i> and identify the features of four types of responsibility centers: cost centers, revenue centers, profit centers, and investment centers.";
arrlotext['12B'] = "12B. Describe how variance analysis is used to measure and evaluate the performance of responsibility centers.";
arrlotext['12C'] = "12C. Compare a responsibility report to the responsibility reports of the organizational level directly above and directly below the responsibility center.";
arrlotext['12D'] = "12D. Describe the issues that must be considered in evaluating the performance of a responsibility center.";
arrlotext['13A'] = "13A. Identify and distinguish costs that are classified by description, behavior, and measurement.";
