var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2020';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 311 Practice Questions, Chapter 13";
var coursename = 'LOMA 311';
var modulenumber = 4;
var title = "LOMA_311_PPQ2020_0_13";
var intNumPools = 1;
var numQ = 11;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Business Law for Insurance Professionals (2020)";
arrNumChap[0] = 1;
var thisChap = '13';

objPool = new Object(); 
objPool.intSelectCount = 11;
objPool.formID = 2380;
objPool.formName = 'PPQ2020_0_13';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_311_PQ_159';
arrPoolQuestions[1] = 'LOMA_311_PQ_160';
arrPoolQuestions[2] = 'LOMA_311_PQ_161';
arrPoolQuestions[3] = 'LOMA_311_PQ_162';
arrPoolQuestions[4] = 'LOMA_311_PQ_163';
arrPoolQuestions[5] = 'LOMA_311_PQ_164';
arrPoolQuestions[6] = 'LOMA_311_PQ_165';
arrPoolQuestions[7] = 'LOMA_311_PQ_166';
arrPoolQuestions[8] = 'LOMA_311_PQ_167';
arrPoolQuestions[9] = 'LOMA_311_PQ_168';
arrPoolQuestions[10] = 'LOMA_311_PQ_169';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_159';
objQuestion.questionID = 117124;
objQuestion.item = 'LOMA_311_PPQ2020_159';
objQuestion.primaryLO = '13A';
objQuestion.textref = 'c. 13, pp. 3-4';
objQuestion.textbook = 0;
objQuestion.chapter = 13;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '13A';
arrLOs[1] = '13B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Consider the following situations with regard to whether the insurer is contesting the life insurance contract or performing the contract:</p><ul class=\"examul\"><li><b>Situation A:</b> The insurer denied a claim for life insurance policy proceeds on the grounds that the insured died as a result of suicide during the suicide exclusion period. The insurer returned the amount of the premiums paid for the policy.</li><li><b>Situation B: </b>While processing a life insurance claim, the insurer discovered a material misrepresentation in the application. The insurer denied payment of the claim and returned the premiums paid for the policy. The claimant refused to accept the premium refund, so the insurer initiated an action in court for rescission of the contract.</li></ul><p class=\"stem\">Select the answer choice that correctly identifies whether the insurer was contesting the life insurance contract or performing the contract in Situation A and in Situation B.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[-1] = "<u>Situation A</u></div><div class=\"anshead\"><u>Situation B</u>";
arrAnsChoices[0] = "contesting the contract</div><div class=\"anscell\" onclick=\"recordAns(1);\">contesting the contract";
arrAnsChoices[1] = "contesting the contract</div><div class=\"anscell\" onclick=\"recordAns(2);\">performing the contract";
arrAnsChoices[2] = "performing the contract</div><div class=\"anscell\" onclick=\"recordAns(3);\">contesting the contract";
arrAnsChoices[3] = "performing the contract</div><div class=\"anscell\" onclick=\"recordAns(4);\">performing the contract";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473579;
arrAnsIDs[1] = 473580;
arrAnsIDs[2] = 473581;
arrAnsIDs[3] = 473582;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that the insurer is contesting the validity of the life insurance contract in Situation B. A policy contest is a court action to determine the validity of a life insurance contract. However, the insurer is <b>performing </b>the contract in Situation A. When an insurer denies a claim based on a provision in the life insurance policy, the insurer is performing the contract according to its terms.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">In Situation A, the insurer is <b>performing </b>the life insurance contract. When an insurer denies a claim based on a provision in the life insurance policy, the insurer is performing the contract according to its terms. In Situation B, the insurer is <b>contesting </b>the validity of the policy on the grounds of material misrepresentation in the policy application. A policy contest is a court action to determine the validity of a life insurance contract.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">In Situation A, the insurer is performing the life insurance contract. When an insurer denies a claim based on a provision in the life insurance policy, the insurer is performing the contract according to its terms. A policy contest is a court action to determine the validity of a life insurance contract. In Situation B, the insurer is contesting the validity of the policy on the grounds of material misrepresentation in the policy application.</p><p class=\"explanations\"><b>Learning Objectives: (1) 13A. Distinguish between performance of a life insurance policy and contest of a life insurance policy; (2) 13B. Describe the grounds on which an insurer may contest the validity of a life insurance policy.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that the insurer is performing the life insurance contract in Situation A. When an insurer denies a claim based on a provision in the life insurance policy, the insurer is performing the contract according to its terms. However, in Situation B, the insurer is <b>contesting </b>the validity of the policy on the grounds of material misrepresentation in the application. A policy contest is a court action to determine the validity of a life insurance contract.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_159'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_160';
objQuestion.questionID = 117125;
objQuestion.item = 'LOMA_311_PPQ2020_160';
objQuestion.primaryLO = '13C';
objQuestion.textref = 'c. 13, pp. 5, 6, 7';
objQuestion.textbook = 0;
objQuestion.chapter = 13;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '13C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">In order to successfully challenge the validity of a life insurance contract based on a misrepresentation in an application for insurance, insurers in most jurisdictions in the United States are required to prove that a misrepresentation contains three elements. These elements include</p><ol type=\"A\" class=\"combo\"><li>That the applicant or proposed insured speculated on the proposed insured’s health status</li><li>That the fact was known by the applicant or proposed insured at the time of the misrepresentation or failure to disclose</li><li>That the fact was material—or relevant—to the insurer’s acceptance of the risk</li><li>That the applicant or proposed insured misrepresented or failed to disclose a fact</li><li>That the cause of the insured’s death was directly related to the misrepresentation</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A, B, and C only";
arrAnsChoices[1] = "A, B, and D only";
arrAnsChoices[2] = "B, C, and D only";
arrAnsChoices[3] = "B, C, and E only";
arrAnsChoices[4] = "B, D, and E only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473583;
arrAnsIDs[1] = 473584;
arrAnsIDs[2] = 473585;
arrAnsIDs[3] = 473586;
arrAnsIDs[4] = 473587;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is <b>not </b>an element that an insurer must prove to successfully challenge the validity of a contract based on a misrepresentation in the application.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">At least one of these statements is <b>not </b>an element that an insurer must prove to successfully challenge the validity of a contract based on a misrepresentation in the application.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Most jurisdictions in the United States require insurers to prove three elements in order to challenge the validity of a life insurance contract based on a misrepresentation in an application for insurance: (1) the applicant or proposed insured misrepresented or failed to disclose a fact; (2) the fact was known by the applicant or proposed insured at the time of the misrepresentation or failure to disclose; and (3) the fact was material—or relevant—to the insurer’s acceptance of the risk.</p><p class=\"explanations\">In a few states, an insurer can avoid a life insurance contract on the grounds of material misrepresentation only if the cause of the insured’s death was directly related to the misrepresentation. In most states, however, an insurer can avoid a life insurance contract on the grounds of material misrepresentation even if the cause of the insured’s death was not related to the fact that was misrepresented.</p><p class=\"explanations\"><b>Learning Objective: 13C. Describe the three elements of a material misrepresentation.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is <b>not </b>an element that an insurer must prove to successfully challenge the validity of a contract based on a misrepresentation in the application.</p>";
arrAnswerFeedback[4] = "<p class=\"explanations\">At least one of these statements is <b>not </b>an element that an insurer must prove to successfully challenge the validity of a contract based on a misrepresentation in the application.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_160'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_161';
objQuestion.questionID = 117126;
objQuestion.item = 'LOMA_311_PPQ2020_161';
objQuestion.primaryLO = '13C';
objQuestion.textref = 'c. 13, pp. 6-7';
objQuestion.textbook = 0;
objQuestion.chapter = 13;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '13C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">State laws in the United States specify that, in the absence of fraud, statements made in life insurance applications are (<b>representations</b> / <b>warranties</b>). One difference between a representation and a warranty is that a (<b>representation</b> / <b>warranty</b>) that is not <i>literally </i>true gives an injured party grounds to avoid the contract.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "representations / representation";
arrAnsChoices[1] = "representations / warranty";
arrAnsChoices[2] = "warranties / representation";
arrAnsChoices[3] = "warranties / warranty";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473588;
arrAnsIDs[1] = 473589;
arrAnsIDs[2] = 473590;
arrAnsIDs[3] = 473591;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that, in the absence of fraud, statements made in life insurance applications are representations rather than warranties. However, a representation can be used to invalidate a contract if the statement is not <b>substantially </b>true <b>and </b>the statement induced the other party to enter into the contract.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A representation can be used to invalidate a contract if the statement is not substantially true and the statement induced the other party to enter into the contract. In other words, if a party misrepresents a fact that is material to the insurance, the insurance contract is voidable by the insurer. A warranty is a promise or guarantee recognized by law that a statement of fact is true. A warranty that is not literally true gives an injured party grounds to avoid the contract.</p><p class=\"explanations\"><b>Learning Objective: 13C. Describe the three elements of a material misrepresentation.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">In the absence of fraud, statements made in life insurance applications are considered to be <b>representations</b>, not warranties. Also, a representation can be used to invalidate a contract if the statement is not <b>substantially </b>true <b>and </b>the statement induced the other party to enter into the contract.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that a warranty that is not literally true gives an injured party grounds to avoid a contract. However, in the absence of fraud, statements made in life insurance applications are considered to be <b>representations</b>, not warranties.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_161'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_162';
objQuestion.questionID = 117127;
objQuestion.item = 'LOMA_311_PPQ2020_162';
objQuestion.primaryLO = '13D';
objQuestion.textref = 'c. 13, p. 8';
objQuestion.textbook = 0;
objQuestion.chapter = 13;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '13D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">At age 47, John Cook applied to the Mimosa Insurance Company for insurance coverage on his life. On his application, he mistakenly stated his age as 41. Mimosa issued the policy as applied for and included a typical two-year incontestability provision and a typical misstatement of age or sex provision. Mr.&nbsp;Cook died five years later, and the policy beneficiary submitted a claim for the death benefit. During the claim review process, Mimosa discovered the misstatement of age on Mr.&nbsp;Cook’s application and determined that Mr.&nbsp;Cook had not been charged the correct premium based on his actual age. In this situation, Mimosa most likely will</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "declare the policy void because Mr.&nbsp;Cook’s misstatement of his age caused a defect in the formation of the contract";
arrAnsChoices[1] = "require the beneficiary to pay the premium amount difference caused by the misstatement of Mr.&nbsp;Cook’s age";
arrAnsChoices[2] = "adjust the face amount of the policy to the amount the premiums actually paid would have purchased if Mr.&nbsp;Cook’s age had been stated correctly on the application";
arrAnsChoices[3] = "be obligated to pay the policy proceeds in full because Mr.&nbsp;Cook died after the policy’s contestable period had expired";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473592;
arrAnsIDs[1] = 473593;
arrAnsIDs[2] = 473594;
arrAnsIDs[3] = 473595;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">In this situation, Mimosa most likely will enforce the misstatement of age or sex provision in the contract, <b>not </b>seek to avoid the contract. A misrepresentation of age is not a defect in the formation of a contract. An insurer can avoid a contract based on a defect in the formation of a contract if one of the requirements for the formation of a valid contract was missing: mutual assent, adequate consideration, contractual capacity, and lawful purpose.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">When an insurer discovers a misstatement of age or sex <b>before</b> the death of the insured, the insurer may grant the policyowner the option to pay, or receive as a refund, any premium amount difference caused by the misstatement. In this situation, Mimosa discovered the misstatement <b>after </b>the death of the insured; therefore, Mimosa would take a different action.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">When an insurer discovers a misstatement of age or sex in an application for insurance after the death of the insured, and the misstatement resulted in an incorrect premium amount for the amount of insurance purchased, the insurer will adjust the face amount of the policy to the correct amount the premiums actually paid would have purchased if the insured’s age had been stated correctly at the time of application. By taking this action, Mimosa is enforcing the misstatement of age or sex provision in the contract; therefore, this action is not prohibited by the incontestability provision.</p><p class=\"explanations\"><b>Learning Objective: 13D. Explain the actions an insurer may take when it discovers a misrepresentation of the insured’s age or sex.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">In this situation, Mimosa is enforcing the misstatement of age or sex provision in the contract. Mimosa is not attempting to avoid or contest the validity of the contract; therefore, its actions are not prohibited by the incontestability provision.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_162'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_163';
objQuestion.questionID = 117128;
objQuestion.item = 'LOMA_311_PPQ2020_163';
objQuestion.primaryLO = '13E';
objQuestion.textref = 'c. 13, pp. 10-11';
objQuestion.textbook = 0;
objQuestion.chapter = 13;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '13E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Altair Life Insurance Company issues life insurance policies that include a typical two-year incontestability provision. The provision specifies that the contestable period begins on the date of policy issue. Consider Altair’s ability to contest each of the following policies on the grounds of material misrepresentation in the insurance application that Altair discovered while processing each claim:</p><ul class=\"examul\"><li><b>Policy A:</b> Altair issued the life insurance policy on April 10. The insured died just before the second policy anniversary, on April 5, while the policy was still in force. The beneficiary filed a claim on May 25.</li><li><b>Policy B:</b> Altair issued the life insurance policy on January 5. The insured died more than two years later, on July 8, while the policy was still in force. The beneficiary filed a claim on July 15.</li></ul><p class=\"stem\">With regard to whether Altair has the right to contest the validity of these policies on the ground of a material misrepresentation in the application, it is correct to say that Altair can contest</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "both Policy A and Policy B";
arrAnsChoices[1] = "Policy A, but the incontestability provision prevents Altair from contesting Policy B";
arrAnsChoices[2] = "Policy B, but the incontestability provision prevents Altair from contesting Policy A";
arrAnsChoices[3] = "neither Policy A nor Policy B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473596;
arrAnsIDs[1] = 473597;
arrAnsIDs[2] = 473598;
arrAnsIDs[3] = 473599;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The incontestability provision <b>prevents </b>Altair from contesting the validity of at least one of these policies on the ground of a material misrepresentation in the application.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Altair has the right to contest the validity of Policy A. The insured died during the contestable period, which means that the policy will never become incontestable, even though Altair discovered the material misrepresentation after the end of the contestable period. Altair most likely cannot contest the validity of Policy B on the ground of a material misrepresentation, because the death of the insured occurred after the end of the contestable period.</p><p class=\"explanations\"><b>Learning Objective: 13E. Explain how the incontestability provision limits an insurer’s right to contest the validity of a life insurance policy, and identify other barriers to contesting a policy.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Altair most likely <b>cannot </b>contest the validity of Policy B because the death of the insured occurred after the end of contestable period. Altair <b>can </b>contest the validity of Policy A. The insured died during the contestable period, which means that the policy will never become incontestable, even though Altair discovered the material misrepresentation after the end of the two-year period.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Altair has the right to contest the validity of at least one of these policies on the ground of a material misrepresentation in the application.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_163'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_164';
objQuestion.questionID = 117129;
objQuestion.item = 'LOMA_311_PPQ2020_164';
objQuestion.primaryLO = '13E';
objQuestion.textref = 'c. 13, pp. 11-12';
objQuestion.textbook = 0;
objQuestion.chapter = 13;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '13E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Qiang Li was the policyowner-insured of a life insurance policy that contains a typical two-year incontestability provision. Three years after policy issue, the policy lapsed after Mr.&nbsp;Li failed to pay a premium when due. Two months after the lapse, Mr.&nbsp;Li submitted a reinstatement application and the insurer reinstated the policy. With regard to the insurer’s right to contest the validity of the policy based on statements made in the original application and statements made in the reinstatement application, it most likely is correct to say that the insurer</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "can contest the validity of the policy based on misrepresentations either in the original application or in the reinstatement application";
arrAnsChoices[1] = "can contest the validity of the policy based on misrepresentations in the original application but not on misrepresentations in the reinstatement application";
arrAnsChoices[2] = "can contest the validity of the policy based on misrepresentations in the reinstatement application but not on misrepresentations in the original application";
arrAnsChoices[3] = "cannot contest the validity of the policy based on misrepresentations in either the original or reinstatement application because the policy’s original contestable period had expired";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473600;
arrAnsIDs[1] = 473601;
arrAnsIDs[2] = 473602;
arrAnsIDs[3] = 473603;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The incontestability provision prevents the insurer from using statements made in at least one of these applications as a basis for contesting the validity of the policy.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Because the original contestable period had expired when the policy lapsed, the insurer <b>cannot </b>contest the validity of Mr.&nbsp;Li’s policy based on a misrepresentation in the original policy application. A new contestable period begins on the date of reinstatement and applies only to misrepresentations in the reinstatement application. Thus, the insurer <b>can </b>contest the validity of Mr.&nbsp;Li’s policy based on misrepresentations in the reinstatement application for two years from the date of reinstatement.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Because the original contestable period had expired when the policy lapsed, the insurer cannot<b> </b>contest the validity of Mr.&nbsp;Li’s policy based on a misrepresentation in the original policy application. A new contestable period begins on the date of reinstatement and applies only to misrepresentations in the reinstatement application. Thus, the insurer has the right to contest the validity of Mr.&nbsp;Li’s policy based on misrepresentations in the reinstatement application for two years from the date of reinstatement.</p><p class=\"explanations\"><b>Learning Objective: 13E. Explain how the incontestability provision limits an insurer’s right to contest the validity of a life insurance policy, and identify other barriers to contesting a policy.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Because the original contestable period had expired when the policy lapsed, it is correct to say that the insurer cannot<b> </b>contest the validity of Mr.&nbsp;Li’s policy based on a misrepresentation in the original policy application. However, a new contestable period begins on the date of reinstatement and applies only to misrepresentations in the reinstatement application. Thus, the insurer <b>can </b>contest the validity of Mr.&nbsp;Li’s policy based on misrepresentations in the reinstatement application for two years from the date of reinstatement.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_164'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_165';
objQuestion.questionID = 117130;
objQuestion.item = 'LOMA_311_PPQ2020_165';
objQuestion.primaryLO = '13E';
objQuestion.textref = 'c. 13, p. 13';
objQuestion.textbook = 0;
objQuestion.chapter = 13;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '13E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">When Wei Chen applied to the Lithia Insurance Company for an insurance policy on his life, he told Dan Howard, a Lithia agent, that he had a serious health condition. Mr.&nbsp;Howard agreed to falsify Mr.&nbsp;Chen’s application to conceal his health condition from Lithia. Lithia issued the policy to Mr.&nbsp;Chen at a standard premium rate. Several months later, Mr.&nbsp;Chen died as a result of the health condition. Select the answer choice that correctly identifies whether Mr.&nbsp;Howard engaged in collusion and whether Mr.&nbsp;Howard’s knowledge of Mr.&nbsp;Chen’s condition is considered to be the knowledge of Lithia.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[-1] = "<u>Collusion present?</u></div><div class=\"anshead\"><u>Lithia has knowledge of Mr.&nbsp;Chen’s condition?</u>";
arrAnsChoices[0] = "yes</div><div class=\"anscell\" onclick=\"recordAns(1);\">yes";
arrAnsChoices[1] = "yes</div><div class=\"anscell\" onclick=\"recordAns(2);\">no";
arrAnsChoices[2] = "no</div><div class=\"anscell\" onclick=\"recordAns(3);\">yes";
arrAnsChoices[3] = "no</div><div class=\"anscell\" onclick=\"recordAns(4);\">no";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473605;
arrAnsIDs[1] = 473606;
arrAnsIDs[2] = 473607;
arrAnsIDs[3] = 473608;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that Mr.&nbsp;Chen and Mr.&nbsp;Howard engaged in collusion, which is an agreement between two or more people to defraud another person or entity of certain rights. However, when an agent and an applicant engage in collusion, the agent’s knowledge is <b>not</b> considered to be the knowledge of the insurer.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Mr.&nbsp;Chen and Mr.&nbsp;Howard engaged in collusion, which is an agreement between two or more people to defraud another person or entity of certain rights. When an agent and an applicant engage in collusion, the agent’s knowledge is not considered to be the knowledge of the insurer. Thus, the insurer would have the right to contest the validity of the contract based on a material misrepresentation in the application.</p><p class=\"explanations\"><b>Learning Objective: 13E. Explain how the incontestability provision limits an insurer’s right to contest the validity of a life insurance policy, and identify other barriers to contesting a policy.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Mr.&nbsp;Chen and Mr.&nbsp;Howard <b>did </b>engage in collusion, which is an agreement between two or more people to defraud another person or entity of certain rights. Also, when an agent and an applicant engage in collusion, the agent’s knowledge is <b>not </b>considered to be the knowledge of the insurer.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is correct to say Mr.&nbsp;Howard’s knowledge of Mr.&nbsp;Chen’s condition is not considered to be the knowledge of Lithia in this situation. However, the reason for this fact is that Mr.&nbsp;Chen and Mr.&nbsp;Howard <b>did </b>engage in collusion, which is an agreement between two or more people to defraud another person or entity of certain rights.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_165'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_166';
objQuestion.questionID = 117131;
objQuestion.item = 'LOMA_311_PPQ2020_166';
objQuestion.primaryLO = '13E';
objQuestion.textref = 'c. 13, pp. 13, 15';
objQuestion.textbook = 0;
objQuestion.chapter = 13;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '13E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Sometimes an insurer is prevented from contesting the validity of a life insurance contract even when the insurer discovers during the contestable period that a material misrepresentation was made in the application. With regard to barriers to contesting the validity of a life insurance policy, the following statement(s) can correctly be made:</p><ol type=\"A\" class=\"combo\"><li>If an insurer learns of a misrepresentation but fails to act on that information within a reasonable time, the insurer is deemed to have waived its right to contest the contract.</li><li>As a general rule, an insurer has the right to use a material misrepresentation in an application for life insurance as a basis for avoiding a life insurance contract only if a copy of the application was attached to the policy when it was delivered to the applicant.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473609;
arrAnsIDs[1] = 473610;
arrAnsIDs[2] = 473611;
arrAnsIDs[3] = 473612;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Statement A is a correct statement. By failing to take action to contest the contract on a timely basis, the insurer is deemed to have waived its right to contest the contract.</p><p class=\"explanations\">Statement B is also correct. The application for insurance is not considered a part of the contract unless it is attached to the policy when the policy is issued. For policies that are issued electronically, the insurer must provide the policyowner with a copy of the application, but the application does not have to be physically attached to the policy.</p><p class=\"explanations\"><b>Learning Objective: 13E. Explain how the incontestability provision limits an insurer’s right to contest the validity of a life insurance policy, and identify other barriers to contesting a policy.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is a correct statement. However, Statement B is also correct.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is a correct statement. However, Statement A is also correct.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_166'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_167';
objQuestion.questionID = 117132;
objQuestion.item = 'LOMA_311_PPQ2020_167';
objQuestion.primaryLO = '13F';
objQuestion.textref = 'c. 13, p. 18';
objQuestion.textbook = 0;
objQuestion.chapter = 13;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '13F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Meredith Grishin purchased from the Camden Life Insurance Company an insurance policy on the life of her business partner, Tammy Brow. At the time of policy issue, both Camden and Ms.&nbsp;Grishin were unaware that Ms.&nbsp;Brow had just died. This information indicates that Ms.&nbsp;Grishin and Camden made a (<b>unilateral / bilateral</b>)<b> </b>mistake of fact that was also a (<b>common / mutual</b>) mistake.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "unilateral / common";
arrAnsChoices[1] = "unilateral / mutual";
arrAnsChoices[2] = "bilateral / common";
arrAnsChoices[3] = "bilateral / mutual";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473613;
arrAnsIDs[1] = 473614;
arrAnsIDs[2] = 473615;
arrAnsIDs[3] = 473616;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that Ms.&nbsp;Grinshin and Camden made a common mistake, which occurs when both parties to an agreement make the same mistake as to the identity or existence of the subject matter of the contract. However, the mistake was not a unilateral mistake, which occurs when only one of the parties to a contract makes a mistake. In this situation, <b>both </b>Camden and Ms.&nbsp;Grinshin made a mistake.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Ms.&nbsp;Grinshin and Camden did not make a unilateral mistake, which occurs when only one<b> </b>of the parties to a contract makes a mistake. In this situation, <b>both </b>Camden and Ms.&nbsp;Grishin made a mistake. Also, the mistake was not a mutual mistake, which occurs when both parties to a contract make a mistake, but they make different mistakes. In this situation, Camden and Ms.&nbsp;Grishin both made <b>the same </b>mistake.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A bilateral mistake occurs when both parties are mistaken when they enter into a contract. Bilateral mistakes can be either common mistakes or mutual mistakes. A common mistake occurs when both parties make the same mistake as to the identity or existence of the subject matter of the contract. A mutual mistake occurs when both parties to a contract make a mistake, but they make different mistakes.</p><p class=\"explanations\"><b>Learning Objective: 13F. Distinguish among the types of mistakes that can affect the validity of a life insurance policy.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that Ms.&nbsp;Grinshin and Camden made a bilateral mistake, which occurs when both parties to an agreement are mistaken when they enter into a contract. However, Ms.&nbsp;Grinshin and Camden did not make a mutual mistake, which occurs when both parties to a contract make a mistake, but they make different mistakes. In this situation, Camden and Ms.&nbsp;Grinshin both made <b>the same </b>mistake.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_167'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_168';
objQuestion.questionID = 117133;
objQuestion.item = 'LOMA_311_PPQ2020_168';
objQuestion.primaryLO = '13G';
objQuestion.textref = 'c. 13, pp. 22, 24';
objQuestion.textbook = 0;
objQuestion.chapter = 13;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '13G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Cactus Insurance Company could not determine the proper recipient of a life insurance policy’s proceeds. Cactus paid the policy proceeds to a court and asked the court to decide the proper recipient. In this situation, Cactus used an equitable remedy known as</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "interpleader, and Cactus is released from any further liability under the insurance contract";
arrAnsChoices[1] = "interpleader, and the claimants are still entitled to file a separate legal action against Cactus after this proceeding is complete";
arrAnsChoices[2] = "rescission, and Cactus is released from any further liability under the insurance contract";
arrAnsChoices[3] = "rescission, and the claimants are still entitled to file a separate legal action against Cactus after this proceeding is complete";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473617;
arrAnsIDs[1] = 473618;
arrAnsIDs[2] = 473619;
arrAnsIDs[3] = 473620;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Interpleader is a court proceeding under which an insurer that cannot determine the proper recipient of policy proceeds pays the proceeds to a court and asks the court to decide the proper recipient. After paying the money to the court, the insurer usually is released from any further liability under the policy.</p><p class=\"explanations\"><b>Learning Objective: 13G. Define common legal and equitable remedies available to the parties to a life insurance policy.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that interpleader is a court proceeding that allows an insurer to pay the policy proceeds to a court and ask the court to decide the proper recipient. However, after Cactus pays the policy proceeds to the court, the conflicting claimants are <b>prevented </b>from pursuing other legal action against Cactus to recover the proceeds.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that Cactus is released from any further liability under the policy after going through this court proceeding. However, Cactus did <b>not </b>use rescission in this situation. Rescission is an equitable remedy in which a contract is canceled and the parties are returned to the positions they would have been in had no contract ever been created.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Cactus did <b>not </b>use rescission in this situation. Rescission is an equitable remedy in which a contract is canceled and the parties are returned to the positions they would have been in had no contract ever been created.<b> </b>Also, after Cactus pays the policy proceeds to a court, the conflicting claimants are <b>prevented </b>from pursuing other legal action against Cactus to recover the proceeds.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_168'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_169';
objQuestion.questionID = 117134;
objQuestion.item = 'LOMA_311_PPQ2020_169';
objQuestion.primaryLO = '13G';
objQuestion.textref = 'c. 13, pp. 23-25';
objQuestion.textbook = 0;
objQuestion.chapter = 13;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '13G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about common equitable remedies—reformation, declaratory judgment, rescission, and restitution. Three statements are true, and one statement is false. Select the answer choice containing the <B>FALSE </B>statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A plaintiff who seeks reformation of a contract must present the court with clear and convincing evidence as to the terms of the parties’ actual agreement, which is a higher degree of proof than is a preponderance of the evidence.";
arrAnsChoices[1] = "A declaratory judgment is a judicial statement that declares or denies the parties’ legal rights but does not include specific relief or any means to enforce those rights.";
arrAnsChoices[2] = "When a life insurance contract is rescinded by a court due to a material misrepresentation in the application, the insurer has no obligation to pay anything to the policyowner.";
arrAnsChoices[3] = "Restitution sometimes is granted as a legal remedy and at other times it is granted as an equitable remedy.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473621;
arrAnsIDs[1] = 473622;
arrAnsIDs[2] = 473623;
arrAnsIDs[3] = 473624;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">This is a true statement; therefore, it is <b>not</b> the correct response.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">This is a true statement; therefore, it is <b>not</b> the correct response.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">This is a false statement; therefore, it is the correct response. When a contract is rescinded, each party must return to the other party whatever he has received under the contract. Thus, to rescind a life insurance contract, the insurer must return to the policyowner the total amount of premiums paid plus any interest, minus any withdrawals on the policy.</p><p class=\"explanations\"><b>Learning Objective: 13G. Define common legal and equitable remedies available to the parties to a life insurance policy.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">This is a true statement; therefore, it is <b>not</b> the correct response.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_169'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['13A'] = "13A. Distinguish between performance of a life insurance policy and contest of a life insurance policy.";
arrlotext['13B'] = "13B. Describe the grounds on which an insurer may contest the validity of a life insurance policy.";
arrlotext['13C'] = "13C. Describe the three elements of a material misrepresentation.";
arrlotext['13D'] = "13D. Explain the actions an insurer may take when it discovers a misrepresentation of the insured’s age or sex.";
arrlotext['13E'] = "13E. Explain how the incontestability provision limits an insurer’s right to contest the validity of a life insurance policy, and identify other barriers to contesting a policy.";
arrlotext['13F'] = "13F. Distinguish among the types of mistakes that can affect the validity of a life insurance policy.";
arrlotext['13G'] = "13G. Define common legal and equitable remedies available to the parties to a life insurance policy.";
