var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2020';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 311 Practice Questions, Chapter 11";
var coursename = 'LOMA 311';
var modulenumber = 4;
var title = "LOMA_311_PPQ2020_0_11";
var intNumPools = 1;
var numQ = 12;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Business Law for Insurance Professionals (2020)";
arrNumChap[0] = 1;
var thisChap = '11';

objPool = new Object(); 
objPool.intSelectCount = 12;
objPool.formID = 2380;
objPool.formName = 'PPQ2020_0_11';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_311_PQ_136';
arrPoolQuestions[1] = 'LOMA_311_PQ_137';
arrPoolQuestions[2] = 'LOMA_311_PQ_138';
arrPoolQuestions[3] = 'LOMA_311_PQ_139';
arrPoolQuestions[4] = 'LOMA_311_PQ_140';
arrPoolQuestions[5] = 'LOMA_311_PQ_141';
arrPoolQuestions[6] = 'LOMA_311_PQ_142';
arrPoolQuestions[7] = 'LOMA_311_PQ_143';
arrPoolQuestions[8] = 'LOMA_311_PQ_144';
arrPoolQuestions[9] = 'LOMA_311_PQ_145';
arrPoolQuestions[10] = 'LOMA_311_PQ_146';
arrPoolQuestions[11] = 'LOMA_311_PQ_147';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_136';
objQuestion.questionID = 117101;
objQuestion.item = 'LOMA_311_PPQ2020_136';
objQuestion.primaryLO = '11A';
objQuestion.textref = 'c. 11, pp. 4-5';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '11A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = 1;
objQuestion.strStem = "<p class=\"stem\">Ms.&nbsp;Marcum’s beneficiary designation can be correctly described as</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "a contingent beneficiary designation";
arrAnsChoices[1] = "a class designation";
arrAnsChoices[2] = "a recording method designation";
arrAnsChoices[3] = "an endorsement method designation";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473485;
arrAnsIDs[1] = 473486;
arrAnsIDs[2] = 473487;
arrAnsIDs[3] = 473488;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A contingent beneficiary is the party who will receive life insurance policy proceeds after the insured’s death if the primary beneficiary dies before the insured. Ms.&nbsp;Marcum’s beneficiary designation identifies a certain group of people, rather than naming each person individually as a primary beneficiary or a contingent beneficiary.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">By listing “my children” in her beneficiary designation, rather than naming them individually, Ms.&nbsp;Marcum made a class designation. The advantage to the policyowner of making a class designation is that the members of the class who will share in the policy proceeds are not determined until the insured dies. The disadvantage is that, before any proceeds are paid, the insurer must identify and locate all members of the beneficiary class.</p><p class=\"explanations\"><b>Learning Objective: 11A. Describe a policyowner’s rights to name and change the beneficiary of a life insurance policy.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The recording method is a method for changing the beneficiary<b> </b>that requires the policyowner to provide the insurer with a written and signed notification of the change in beneficiary. Ms.&nbsp;Marcum did <b>not</b> make a beneficiary change prior to her death.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The endorsement method is a method for changing the beneficiary that requires the policyowner to submit his policy to the insurer along with a beneficiary change request. Ms.&nbsp;Marcum did <b>not </b>make a beneficiary change prior to her death.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_136'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_137';
objQuestion.questionID = 117102;
objQuestion.item = 'LOMA_311_PPQ2020_137';
objQuestion.primaryLO = '11B';
objQuestion.textref = 'c. 11, pp. 4-5';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '11B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = 1;
objQuestion.strStem = "<p class=\"stem\">If the policy proceeds are distributed according to Ms.&nbsp;Marcum’s beneficiary designation, then the insurer most likely will pay</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "$200,000 each to Gina and Steve, and $100,000 each to Don and Kevin";
arrAnsChoices[1] = "$200,000 each to Gina, Steve, and Kevin";
arrAnsChoices[2] = "$300,000 each to Gina and Steve";
arrAnsChoices[3] = "$600,000 to Gina";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473489;
arrAnsIDs[1] = 473490;
arrAnsIDs[2] = 473491;
arrAnsIDs[3] = 473492;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The class members of Ms.&nbsp;Marcum’s beneficiary designation are her children, and, under a per capita designation, only those children who survive the insured share the policy proceeds. No descendants or heirs of a deceased class member share in the distribution. Although Gina is a beneficiary of Ms.&nbsp;Marcum’s life insurance policy, Steve, Don, and Kevin are <b>not </b>policy beneficiaries. Steve is Ms.&nbsp;Marcum’s stepson, and he would only qualify as a beneficiary if Ms.&nbsp;Marcum had legally adopted him. Don and Kevin are her grandsons and are not entitled to share in the policy proceeds under a per capita beneficiary designation.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The class members of Ms.&nbsp;Marcum’s beneficiary designation are her children, and, under a per capita designation, only those children who survive the insured share the policy proceeds. No descendants or heirs of a deceased class member share in the distribution. Although Gina is a beneficiary of Ms.&nbsp;Marcum’s life insurance policy, Steve and Kevin are <b>not </b>policy beneficiaries. Steve is Ms.&nbsp;Marcum’s stepson, and he would only qualify as a beneficiary if Ms.&nbsp;Marcum had legally adopted him. Kevin is not a class member of the beneficiary designation, and he would not share in the policy proceeds under a per capita beneficiary designation.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The class members of Ms.&nbsp;Marcum’s beneficiary designation are her children, and, under a per capita designation, only those children who survive the insured share the policy proceeds. It is true that Gina is a beneficiary of Ms.&nbsp;Marcum’s life insurance policy. However, Steve is not entitled to share in the policy proceeds under the class designation “my children” because Ms.&nbsp;Marcum did not legally adopt him.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A per capita beneficiary designation is a class designation in which the class members all stand in the same relationship to the policyowner, and the class members who survive the insured are entitled to share in the policy proceeds equally. No descendants or heirs of a deceased class member share in the distribution. Adopted children share in policy proceeds on the same basis as biological children in a class designation; however, stepchildren whom an insured did not legally adopt are not entitled to share in the policy proceeds under such a class designation. Thus, Gina, the only surviving class member under the per capita class designation of Ms.&nbsp;Marcum’s children, receives the entire policy proceeds.</p><p class=\"explanations\"><b>Learning Objective: 11B. In a given situation, identify the party to whom life insurance policy proceeds are payable following the insured’s death.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_137'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_138';
objQuestion.questionID = 117103;
objQuestion.item = 'LOMA_311_PPQ2020_138';
objQuestion.primaryLO = '11B';
objQuestion.textref = 'c. 11, p. 5';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '11B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Ten years ago, Tamara Hart purchased a $300,000 insurance policy on her life and made the following beneficiary designation: “to my children, per stirpes.” Ms.&nbsp;Hart had one son, Ashton; one daughter, Lina; and one legally adopted stepdaughter, Sarah. Ashton had one son, Corey, and one daughter, Maria. Lina had one daughter, Leigh. Sarah had two sons, Sean and Gene. While the policy was still in force, Ms.&nbsp;Hart died. At the time of Ms.&nbsp;Hart’s death, Sarah was living, but Ashton and Lina were not. In this situation, <i>Corey</i> is entitled to receive</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "$0";
arrAnsChoices[1] = "$50,000";
arrAnsChoices[2] = "$100,000";
arrAnsChoices[3] = "$300,000";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473493;
arrAnsIDs[1] = 473494;
arrAnsIDs[2] = 473495;
arrAnsIDs[3] = 473496;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Under a per stirpes beneficiary designation, the descendants of a deceased class member take the decedent’s share of the policy proceeds by representation. Therefore, Corey would be entitled to a share of the policy proceeds upon Ms.&nbsp;Hart’s death.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Under a per stirpes beneficiary designation, the descendants of a deceased class member take the decedent’s share of the policy proceeds by representation and share it equally. Ms.&nbsp;Hart was predeceased by two—Ashton and Lina—of her three children. Ashton’s children, Corey and Maria, are entitled to equal amounts of Ashton’s share of the policy proceeds. Ms.&nbsp;Hart was survived by three family branches, each of which will share $100,000, which is one-third of the $300,000 policy proceeds. Corey is entitled to $50,000, or one-half of $100,000, and his sister, Maria, is entitled to the other $50,000.</p><p class=\"explanations\"><b>Learning Objective: 11B. In a given situation, identify the party to whom life insurance policy proceeds are payable following the insured’s death.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Under a per stirpes beneficiary designation, the descendants of a deceased class member take the decedent’s share of the policy proceeds by representation. In this situation, Ms.&nbsp;Hart was predeceased by two—Ashton and Lina—of her three children. She was survived by three family branches, one of which is Ashton’s branch. Ashton’s two children, Corey and Maria, are entitled to share one-third of the policy proceeds equally. Thus, Corey will not receive $100,000, which is the entire amount of that branch’s share.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Under a per stirpes beneficiary designation, the descendants of a deceased class member take the decedent’s share of the policy proceeds by representation. In this situation, Ms.&nbsp;Hart was predeceased by two—Ashton and Lina—of her three children. She was survived by three family branches, one of which is Ashton’s branch. Ashton’s two children, Corey and Maria, are entitled to share one-third of the policy proceeds equally. Therefore, Corey will not receive the entire policy proceeds.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_138'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_139';
objQuestion.questionID = 117104;
objQuestion.item = 'LOMA_311_PPQ2020_139';
objQuestion.primaryLO = '11A';
objQuestion.textref = 'c. 11, pp. 5-7';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '11A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about revocable beneficiaries and irrevocable beneficiaries of individual life insurance policies. Three statements are true, and one statement is false. Select the answer choice containing the <B>FALSE</B> statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A revocable beneficiary’s rights to the proceeds of a life insurance policy vest when the beneficiary designation becomes effective.";
arrAnsChoices[1] = "An irrevocable beneficiary’s vested interest in policy proceeds usually continues as long as the policy remains in force, or until the beneficiary consents in writing to a beneficiary change or predeceases the insured.";
arrAnsChoices[2] = "During an insured’s lifetime, a revocable beneficiary cannot prohibit a policyowner from exercising any policy ownership rights.";
arrAnsChoices[3] = "When a minor is designated as an irrevocable beneficiary, the policyowner is unable to interact with the policy in any way that would require the beneficiary’s consent until the beneficiary reaches the age of majority and gives consent.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473497;
arrAnsIDs[1] = 473498;
arrAnsIDs[2] = 473499;
arrAnsIDs[3] = 473500;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">This is a false statement; therefore, it is the correct response. A revocable beneficiary’s interest in the proceeds of a life insurance policy vests <b>when the insured dies</b>. Until that time, a revocable beneficiary generally has neither a legal interest in the proceeds nor any involvement with the policy. Thus, during the insured’s lifetime, a revocable beneficiary’s interest in the life insurance policy is said to be a mere expectancy.</p><p class=\"explanations\"><b>Learning Objective: 11A. Describe a policyowner’s rights to name and change the beneficiary of a life insurance policy.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">This is a true statement; therefore, it is <b>not</b> the correct response.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">This is a true statement; therefore, it is <b>not</b> the correct response.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">This is a true statement; therefore, it is <b>not</b> the correct response.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_139'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_140';
objQuestion.questionID = 117105;
objQuestion.item = 'LOMA_311_PPQ2020_140';
objQuestion.primaryLO = '11B';
objQuestion.textref = 'c. 11, pp. 8-9';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '11B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Ted Litwin was the policyowner-insured of a life insurance policy. His policy contained the following beneficiary designation: “to my wife, Ruby, if living on the 31st day after the death of the insured; otherwise to my brother, Frank Litwin.” Four years after the policy was issued and while the policy was still in force, Ted and Ruby were involved in an automobile accident. Ted died immediately as a result of injuries sustained in the accident, and Ruby died 12 days after the accident. Shortly after Ruby’s death, Frank filed a claim for the policy proceeds with the insurer. In this situation, the insurer most likely was obligated to pay the proceeds of Ted’s life insurance policy to</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Ted’s estate and Ruby’s estate, in equal shares";
arrAnsChoices[1] = "Ted’s estate and Frank, in equal shares";
arrAnsChoices[2] = "Ted’s estate only";
arrAnsChoices[3] = "Frank only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473501;
arrAnsIDs[1] = 473502;
arrAnsIDs[2] = 473503;
arrAnsIDs[3] = 473504;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The proceeds of Ted’s life insurance policy would <b>not</b> be paid to Ted’s estate and Ruby’s estate in equal shares, because Ted did not designate his estate or Ruby’s estate as a contingent beneficiary of the insurance policy.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The proceeds of Ted’s life insurance policy would <b>not</b> be paid to Ted’s estate and Frank in equal shares, because Ruby did not survive Ted by 31 days, as required by the survivorship clause included in the insurance policy. Also, Ted did not designate his estate as a contingent beneficiary of the insurance policy.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The proceeds of Ted’s life insurance policy would <b>not</b> be paid to Ted’s estate because Ted did not designate his estate as a contingent beneficiary of the insurance policy.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The beneficiary designation in this policy included a survivorship clause. A survivorship clause requires the beneficiary of a life insurance policy to survive the insured for a stated number of days to be entitled to the policy proceeds. In this situation, the proceeds of Ted’s life insurance policy would be payable to Frank because Ruby did not survive Ted by 31 days, as required by the survivorship clause included in the policy.</p><p class=\"explanations\"><b>Learning Objective: 11B. In a given situation, identify the party to whom life insurance policy proceeds are payable following the insured’s death.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_140'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_141';
objQuestion.questionID = 117106;
objQuestion.item = 'LOMA_311_PPQ2020_141';
objQuestion.primaryLO = '11C';
objQuestion.textref = 'c. 11, p. 11';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '11C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Ashley Duncan purchased a whole life insurance policy on her life from the Kennesaw Insurance Company and named her husband, Paul, as the policy beneficiary. The policy contained a typical grace period provision, and renewal premiums were due every year on July 1. Several years after the policy was issued and while the policy was still in force, Ashley failed to pay a renewal premium on July 1 and died on July 27. In this situation, Kennesaw is obligated to pay to Paul</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "the full amount of policy proceeds, and Kennesaw is not entitled to deduct the amount of the unpaid premium because the grace period had not expired";
arrAnsChoices[1] = "the full amount of policy proceeds, but Kennesaw is entitled to deduct the amount of the unpaid premium from the policy proceeds";
arrAnsChoices[2] = "an amount equal to all premiums paid for the policy because the grace period had expired";
arrAnsChoices[3] = "nothing, because Ashley’s policy lapsed for nonpayment of premium on July 2";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473505;
arrAnsIDs[1] = 473506;
arrAnsIDs[2] = 473507;
arrAnsIDs[3] = 473508;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">If an insured dies during the grace period but before the premium is paid, the insurer is obligated to pay the policy proceeds to the appropriate beneficiary. The insurer, however, <b>is</b> <b>entitled </b>to deduct<b> </b>the amount of the unpaid premium from the policy proceeds before paying those proceeds.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Because Ashley died during the grace period but before the premium was paid, Kennesaw is obligated to pay the policy proceeds to Paul, the policy beneficiary. Kennesaw, however, is entitled to deduct the amount of the unpaid premium from the policy proceeds before paying those proceeds.</p><p class=\"explanations\"><b>Learning Objective: 11C. Distinguish among the types of premiums a policyowner may pay, the payment methods she may use, and the ways an insurer may respond when a premium is unpaid.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">In this situation, the grace period began on July 2 and had not expired at the time of Ashley’s death. In other words, Ashley’s policy had not lapsed for nonpayment of premium before her death. Therefore, Kennesaw <b>is obligated </b>to pay the policy proceeds to the appropriate beneficiary.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">In this situation, the grace period began on July 2 and had not expired at the time of Ashley’s death. In other words, Ashley’s policy had not lapsed for nonpayment of premium on July 2. Therefore, Kennesaw <b>is obligated </b>to pay the policy proceeds to the appropriate beneficiary.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_141'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_142';
objQuestion.questionID = 117107;
objQuestion.item = 'LOMA_311_PPQ2020_142';
objQuestion.primaryLO = '11C';
objQuestion.textref = 'c. 11, pp. 11-13';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '11C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about premium payments for life insurance policies. Select the answer choice containing the correct statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "If a policyowner rejects a life insurance contract during the contract’s free look period, the insurer is not obligated to return the initial premium to the policyowner.";
arrAnsChoices[1] = "When a policyowner pays a renewal premium by check, the premium is considered paid as soon as the insurer receives the check, even if the bank does not honor it immediately.";
arrAnsChoices[2] = "State insurance laws generally prohibit an insurer from lapsing a policy for nonpayment of premium if the insurer has policy dividends on deposit sufficient to pay a renewal premium and the policyowner has not elected another method of using policy dividends.";
arrAnsChoices[3] = "An insurer typically does not accept payment of renewal premiums from anyone other than the policyowner because payment of a premium by a third party gives that party contractual rights in the policy.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473509;
arrAnsIDs[1] = 473510;
arrAnsIDs[2] = 473511;
arrAnsIDs[3] = 473512;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">If a policyowner rejects a life insurance contract during the contract’s free look period, the insurer <b>is</b> obligated to return the initial premium to the policyowner.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">When a policyowner pays a renewal premium by check, the premium is considered paid upon receipt by the insurer. However, if the bank does not honor the check due to insufficient funds, the premium has <b>not</b> been paid.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The insurer must apply policy dividends to pay a renewal premium only if (1) the amount of dividends the insurer has is large enough to cover the full amount of the renewal premium that is due, and (2) the policyowner has not chosen another policy dividend option.</p><p class=\"explanations\"><b>Learning Objective: 11C. Distinguish among the types of premiums a policyowner may pay, the payment methods she may use, and the ways an insurer may respond when a premium is unpaid.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Typically, an insurer will accept payment of a premium from anyone who tenders the payment. Generally, payment of a premium by a third party does <b>not </b>give the third party any contractual rights in the policy.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_142'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_143';
objQuestion.questionID = 117108;
objQuestion.item = 'LOMA_311_PPQ2020_143';
objQuestion.primaryLO = '11D';
objQuestion.textref = 'c. 11, pp. 16-17';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '11D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements describe two life insurance policies issued by the Woodstock Life Insurance Company, both of which provide a cash surrender value after the policies have been in force for at least three years:</p><ul class=\"examul\"><li>When Monica Stanton submitted her application for insurance, she selected a nonforfeiture option which specifies that, if she discontinues premium payments, the net cash surrender value of her policy is to be used as a net single premium to purchase paid-up life insurance of the same plan as her original policy in an amount that is smaller than the policy’s face amount.</li><li>When Jared Henry submitted his application for insurance, he did not select a specific nonforfeiture option. If he discontinues premium payments, Mr.&nbsp;Henry’s policy provides an automatic nonforfeiture benefit which specifies that Woodstock will use the policy’s net cash surrender value as a net single premium to purchase term insurance for the full face amount provided under the original policy for as long a term as that net cash surrender value can provide.</li></ul><p class=\"stem\">Select the answer choice that correctly identifies the nonforfeiture benefit option that Ms.&nbsp;Stanton selected at the time of her application for insurance and the automatic nonforfeiture benefit that Woodstock will apply to Mr.&nbsp;Henry’s policy should he ever discontinue premium payments.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[-1] = "<u>Ms.&nbsp;Stanton</u></div><div class=\"anshead\"><u>Mr.&nbsp;Henry</u>";
arrAnsChoices[0] = "reduced paid-up insurance option</div><div class=\"anscell\" onclick=\"recordAns(1);\">automatic premium loan (APL) benefit";
arrAnsChoices[1] = "reduced paid-up insurance option</div><div class=\"anscell\" onclick=\"recordAns(2);\">extended term insurance benefit";
arrAnsChoices[2] = "extended term insurance option</div><div class=\"anscell\" onclick=\"recordAns(3);\">automatic premium loan (APL) benefit";
arrAnsChoices[3] = "cash surrender value option</div><div class=\"anscell\" onclick=\"recordAns(4);\">extended term insurance benefit";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473514;
arrAnsIDs[1] = 473515;
arrAnsIDs[2] = 473516;
arrAnsIDs[3] = 473517;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that Ms.&nbsp;Stanton selected the reduced paid-up insurance nonforfeiture option. However, the automatic nonforfeiture benefit specified in Mr.&nbsp;Henry’s policy is <b>not</b> the automatic premium loan (APL) benefit. Under an APL benefit, the insurer automatically pays an overdue premium by making a loan against the policy’s cash value if the cash value equals or exceeds the amount of the premium due.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Under the reduced paid-up insurance nonforfeiture option, if Ms.&nbsp;Stanton ever discontinues premium payments, Woodstock will use the net cash surrender value of her policy as a net single premium to purchase paid-up life insurance of the same plan as her original policy. The premium charged for the paid-up insurance is based on Ms.&nbsp;Stanton’s attained age when the option is exercised, and the coverage issued under this option continues to have and to build a cash value. In addition, Ms.&nbsp;Stanton will continue to have the same rights as the owner of any life insurance policy, including the right to surrender the policy for its cash value.</p><p class=\"explanations\">Under the extended term insurance benefit, Woodstock will use the net cash surrender value of Mr.&nbsp;Henry’s policy as a net single premium to purchase term insurance for the full face amount provided under the original policy—less the amount of any outstanding policy loans—for as long a term as that net cash surrender value can provide. The length of the term for which coverage is provided depends on the amount of the coverage, the amount of the net cash surrender value, and Mr.&nbsp;Henry’s attained age when the option is exercised.</p><p class=\"explanations\"><b>Learning Objective: 11D. Distinguish among the various nonforfeiture options that insurers provide to owners of cash value life insurance policies.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Ms.&nbsp;Stanton did <b>not</b> select the extended term insurance nonforfeiture option. Under the extended term option, an insurer uses a life insurance policy’s net cash surrender value as a net single premium to purchase <b>term</b> insurance for the full face amount provided under the original policy—less the amount of any outstanding policy loans—for as long a term as that net cash surrender value can provide.</p><p class=\"explanations\">In addition, the automatic nonforfeiture benefit specified in Mr.&nbsp;Henry’s policy is <b>not</b> the automatic premium loan (APL) benefit. Under an APL benefit, the insurer automatically pays an overdue premium by making a loan against the policy’s cash value if the cash value equals or exceeds the amount of the premium due.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that the automatic nonforfeiture benefit that Woodstock will apply to Mr.&nbsp;Henry’s policy should he ever discontinue premium payments is the extended term insurance benefit. However, Ms.&nbsp;Stanton did <b>not</b> select the cash surrender value nonforfeiture option. Under the cash surrender value option, a policyowner who discontinues premium payments can surrender the policy and receive its cash surrender value.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_143'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_144';
objQuestion.questionID = 117109;
objQuestion.item = 'LOMA_311_PPQ2020_144';
objQuestion.primaryLO = '11E';
objQuestion.textref = 'c. 11, p. 19';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '11E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Kat Shin is the policyowner-insured of an individual life insurance policy issued by the Plateau Life Insurance Company. Ms.&nbsp;Shin’s policy contains a typical policy loan provision. With regard to the policy loan provision contained in Ms.&nbsp;Shin’s policy, it most likely is correct to say that it</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "gives Ms.&nbsp;Shin the right to take out a loan from Plateau for an amount that does not exceed the policy’s cash value, less one year’s interest on the loan";
arrAnsChoices[1] = "legally requires Ms.&nbsp;Shin to repay any policy loan she takes out from Plateau during her lifetime";
arrAnsChoices[2] = "permits Plateau to defer granting the policy loan for a period up to 12 months";
arrAnsChoices[3] = "states that a policy loan taken out from Plateau creates a debtor-creditor relationship between Plateau and Ms.&nbsp;Shin";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473518;
arrAnsIDs[1] = 473519;
arrAnsIDs[2] = 473520;
arrAnsIDs[3] = 473521;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">An individual life insurance policy that accumulates a cash value typically gives the policyowner the right to borrow money from the insurer by using the cash value of the policy as security for a loan.</p><p class=\"explanations\"><b>Learning Objective: 11E. Describe the policy loan provision and the policy withdrawal provision in a life insurance policy and distinguish between a policy loan and a commercial loan.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A policy loan differs from a commercial loan in that a policyowner is <b>not legally obligated</b> to repay a policy loan. The policyowner has the right to repay any part or all of the loan at any time during the lifetime of the insured. If a policy loan has not been repaid when the insured dies, the insurer deducts the amount of the unpaid policy loan plus interest from the policy benefit that is payable.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Laws in most states permit insurers to defer granting a policy loan for a specified period, usually up to <b>six</b> months. An exception to these laws is when the loan is for the purpose of paying premiums on the policy. </p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Unlike a commercial loan, a policy loan does <b>not</b> create a debtor-creditor relationship between the borrower (policyowner) and the lender (insurer).</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_144'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_145';
objQuestion.questionID = 117110;
objQuestion.item = 'LOMA_311_PPQ2020_145';
objQuestion.primaryLO = '11F';
objQuestion.textref = 'c. 11, pp. 20-21';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '11F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The accelerated death benefit provision gives the policyowner the right to receive a portion of the policy benefit during the insured’s lifetime when the insured is terminally ill. Receiving the benefits (<b>may</b> / <b>will not</b>) adversely affect the policyowner’s eligibility for Medicaid and other governmental benefits. The insurer (<b>may</b> / <b>may not</b>) restrict how the recipient uses the money.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "may / may";
arrAnsChoices[1] = "may / may not";
arrAnsChoices[2] = "will not / may";
arrAnsChoices[3] = "will not / may not";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473522;
arrAnsIDs[1] = 473523;
arrAnsIDs[2] = 473524;
arrAnsIDs[3] = 473525;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that receiving the benefits may adversely affect the policyowner’s eligibility for Medicaid and other governmental benefits. However, the insurer <b>may not</b> restrict how the recipient uses the money. </p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">When the policyowner requests the accelerated death benefit payment, the insurer must inform her that receiving the benefits may adversely affect her eligibility for Medicaid and other governmental benefits. The insurer must give the policyowner the right to take the accelerated benefit as a lump sum and may not restrict how the recipient uses the money.</p><p class=\"explanations\"><b>Learning Objective: 11F. Describe the accelerated death benefit provision and identify conditions under which the provision may apply.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Receiving the benefits <b>may</b> adversely affect the policyowner’s eligibility for Medicaid and other governmental benefits. In addition, the insurer <b>may not</b> restrict how the recipient uses the money.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that the insurer may not restrict how the recipient uses the money. However, receiving the benefits <b>may</b> adversely affect the policyowner’s eligibility for Medicaid and other governmental benefits.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_145'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_146';
objQuestion.questionID = 117111;
objQuestion.item = 'LOMA_311_PPQ2020_146';
objQuestion.primaryLO = '11G';
objQuestion.textref = 'c. 11, pp. 22-23';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '11G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Lisa Sage was the policyowner-insured of an individual life insurance policy that contained a typical reinstatement provision. After paying fixed renewal premiums for several years, Ms.&nbsp;Sage allowed the policy to lapse. There were no outstanding policy loans at the time the policy lapsed. Ten months later, Ms.&nbsp;Sage requested to reinstate the lapsed policy. Consider whether Ms.&nbsp;Sage must meet the following conditions to reinstate her policy:</p><ul class=\"examul\"><li><b>Condition A</b>: Complete a reinstatement application within the time frame stated in the reinstatement provision</li><li><b>Condition B</b>: Provide satisfactory evidence of her continued insurability</li><li><b>Condition C</b>: Pay all unpaid back premiums plus interest on those premiums</li></ul><p class=\"stem\">According to the reinstatement provision, the conditions that Ms.&nbsp;Sage must meet to reinstate her policy most likely include Conditions</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A, B, and C";
arrAnsChoices[1] = "A and B only";
arrAnsChoices[2] = "A and C only";
arrAnsChoices[3] = "B and C only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473526;
arrAnsIDs[1] = 473527;
arrAnsIDs[2] = 473528;
arrAnsIDs[3] = 473529;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">To reinstate a policy, a policyowner must meet certain conditions, which are spelled out in the policy’s reinstatement provision. Had there been an outstanding policy loan at the time of policy lapse, in addition to complying with the above conditions, Ms.&nbsp;Sage would have had to pay back the policy loan or have the loan reinstated when the policy is reinstated.</p><p class=\"explanations\"><b>Learning Objective: 11G. Identify and explain the requirements for the reinstatement of a life insurance policy.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that Conditions A and B must be met for Ms.&nbsp;Sage to reinstate her policy. However, Ms.&nbsp;Sage must also meet Condition C. To reinstate a fixed-premium policy like Ms.&nbsp;Sage’s policy, the policyowner typically must pay all unpaid back premiums plus interest on those premiums. For a flexible-premium policy, the policyowner must pay an amount sufficient to cover the policy’s mortality and expense charges for at least two months.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that Conditions A and C must be met for Ms.&nbsp;Sage to reinstate her policy. However, Ms.&nbsp;Sage must also meet Condition B. Requiring satisfactory evidence of insurability protects the insurer against antiselection.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that Conditions B and C must be met for Ms.&nbsp;Sage to reinstate her policy. However, Ms.&nbsp;Sage must also meet Condition A. Thus, Ms.&nbsp;Sage must complete a reinstatement application within the period specified in the policy. Most states require policies to provide at least a three-year period during which the policyowner may reinstate a policy that has lapsed.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_146'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_147';
objQuestion.questionID = 117112;
objQuestion.item = 'LOMA_311_PPQ2020_147';
objQuestion.primaryLO = '11H';
objQuestion.textref = 'c. 11, p. 24';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '11H';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about an annuity contract owner’s ownership rights. Three statements are true, and one statement is false. Select the answer choice containing the <B>FALSE </B>statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Like a life insurance policy, an annuity contract is intangible personal property.";
arrAnsChoices[1] = "During the accumulation period, the owner of a deferred annuity has the right to withdraw all or part of the annuity’s accumulated value.";
arrAnsChoices[2] = "The owner of an individual retirement annuity (IRA) generally has the right to transfer ownership of the contract by means of an assignment.";
arrAnsChoices[3] = "An annuity contract owner has the right to designate the payee who will receive the periodic income payments.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473530;
arrAnsIDs[1] = 473531;
arrAnsIDs[2] = 473532;
arrAnsIDs[3] = 473533;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">This is a true statement; therefore, it is <b>not</b> the correct response.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">This is a true statement; therefore, it is <b>not</b> the correct response.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">This is a false statement; therefore, it is the correct response. Generally, an annuity contract owner has the right to transfer ownership of the contract, unless the annuity qualifies as an individual retirement arrangement (IRA). To satisfy requirements of the federal tax laws, an individual retirement annuity must be nontransferable by the contract owner. Individual retirement annuity contracts must contain a provision that spells out this limitation.</p><p class=\"explanations\"><b>Learning Objective: 11H. Identify the ownership rights that a contract owner has in an annuity.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">This is a true statement; therefore, it is <b>not</b> the correct response.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_147'] = objQuestion;



arrMinicases[1] = "<p class=\"caseinfo\">Use the following information to answer questions 1 and 2.</p><p class=\"caseinfo\">Nancy Marcum was the policyowner-insured of a $600,000 life insurance policy. The beneficiary designation in her policy states that the policy proceeds should be paid to her children, per capita, but does not list the children individually. When Ms.&nbsp;Marcum died, she was survived by</p><ul class=\"examul\"><li>Her adopted daughter, Gina, and Gina’s son, Don</li><li>Her stepson, Steve, whom she did not adopt</li><li>Her grandson, Kevin, the only child of her deceased daughter, Sue</li></ul>";


var arrlotext = new Array(); 
arrlotext['11A'] = "11A. Describe a policyowner’s rights to name and change the beneficiary of a life insurance policy.";
arrlotext['11B'] = "11B. In a given situation, identify the party to whom life insurance policy proceeds are payable following the insured’s death.";
arrlotext['11C'] = "11C. Distinguish among the types of premiums a policyowner may pay, the payment methods she may use, and the ways an insurer may respond when a premium is unpaid.";
arrlotext['11D'] = "11D. Distinguish among the various nonforfeiture options that insurers provide to owners of cash value life insurance policies.";
arrlotext['11E'] = "11E. Describe the policy loan provision and the policy withdrawal provision in a life insurance policy and distinguish between a policy loan and a commercial loan.";
arrlotext['11F'] = "11F. Describe the accelerated death benefit provision and identify conditions under which the provision may apply.";
arrlotext['11G'] = "11G. Identify and explain the requirements for the reinstatement of a life insurance policy.";
arrlotext['11H'] = "11H. Identify the ownership rights that a contract owner has in an annuity.";
