var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2020';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 311 Practice Questions, Chapter 12";
var coursename = 'LOMA 311';
var modulenumber = 4;
var title = "LOMA_311_PPQ2020_0_12";
var intNumPools = 1;
var numQ = 11;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Business Law for Insurance Professionals (2020)";
arrNumChap[0] = 1;
var thisChap = '12';

objPool = new Object(); 
objPool.intSelectCount = 11;
objPool.formID = 2380;
objPool.formName = 'PPQ2020_0_12';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_311_PQ_148';
arrPoolQuestions[1] = 'LOMA_311_PQ_149';
arrPoolQuestions[2] = 'LOMA_311_PQ_150';
arrPoolQuestions[3] = 'LOMA_311_PQ_151';
arrPoolQuestions[4] = 'LOMA_311_PQ_152';
arrPoolQuestions[5] = 'LOMA_311_PQ_153';
arrPoolQuestions[6] = 'LOMA_311_PQ_154';
arrPoolQuestions[7] = 'LOMA_311_PQ_155';
arrPoolQuestions[8] = 'LOMA_311_PQ_156';
arrPoolQuestions[9] = 'LOMA_311_PQ_157';
arrPoolQuestions[10] = 'LOMA_311_PQ_158';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_148';
objQuestion.questionID = 117113;
objQuestion.item = 'LOMA_311_PPQ2020_148';
objQuestion.primaryLO = '12A';
objQuestion.textref = 'c. 12, p. 3';
objQuestion.textbook = 0;
objQuestion.chapter = 12;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '12A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Collateral assignment is one method of transferring life insurance policy ownership rights during the lifetime of the insured. Collateral assignment agreements usually transfer to the assignee the following rights:</p><ol type=\"A\" class=\"combo\"><li>Obtain a policy loan</li><li>Surrender the policy for its cash surrender value</li><li>Select a settlement option</li><li>Designate and change the policy beneficiary</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A, B, C, and D";
arrAnsChoices[1] = "A and B only";
arrAnsChoices[2] = "C and D only";
arrAnsChoices[3] = "A only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473534;
arrAnsIDs[1] = 473535;
arrAnsIDs[2] = 473536;
arrAnsIDs[3] = 473537;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The policyowner retains at least one of these policy rights under a typical collateral assignment agreement.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Collateral assignment agreements usually transfer to the assignee the right to (1) obtain a policy loan; (2) surrender the policy for its cash surrender value; (3) exercise nonforfeiture options; and (4) receive policy dividends. In practice, however, assignees do not exercise these rights unless the assignor fails to repay the loan as required. The policyowner usually retains the right to designate and change the policy beneficiary and the right to select a settlement option.</p><p class=\"explanations\"><b>Learning Objective: 12A. Identify ways in which the owner of a life insurance policy can transfer ownership of the policy to another person.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Under a typical collateral assignment agreement, the assignee does <b>not</b> have<b> </b>the right to select a settlement option and the right to designate and change the policy beneficiary.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">This is not<b> </b>the only right listed that usually is transferred to the collateral assignee.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_148'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_149';
objQuestion.questionID = 117114;
objQuestion.item = 'LOMA_311_PPQ2020_149';
objQuestion.primaryLO = '12C';
objQuestion.textref = 'c. 12, p. 4';
objQuestion.textbook = 0;
objQuestion.chapter = 12;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '12C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">When a policyowner assigns his life insurance policy, the rights of the policy beneficiary vary depending on the type of assignment and on whether the beneficiary is revocable or irrevocable. The following statements are about assignments and the effects they may have on policy beneficiaries. Select the answer choice containing the correct statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "If a revocable beneficiary does not consent to the collateral assignment of a policy, the beneficiary’s rights in the policy are superior to the assignee’s rights.";
arrAnsChoices[1] = "When a life insurance policy that has a revocable beneficiary is absolutely assigned, all courts in the United States hold that the absolute assignment revokes the beneficiary designation.";
arrAnsChoices[2] = "A collateral assignee generally has a superior right to life insurance policy proceeds than does an irrevocable beneficiary who did not consent to the assignment.";
arrAnsChoices[3] = "When a life insurance policy that has an irrevocable beneficiary is absolutely assigned, the beneficiary remains the irrevocable beneficiary unless he consents to a change of beneficiary.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473538;
arrAnsIDs[1] = 473539;
arrAnsIDs[2] = 473540;
arrAnsIDs[3] = 473541;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Because a revocable beneficiary has no legal interest or involvement in a policy during the insured’s lifetime, the collateral assignee’s rights in the policy are superior to the rights of a revocable beneficiary. Thus, the collateral assignee is entitled to be repaid from the policy proceeds even if the revocable beneficiary did not consent to the assignment.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">In the United States, when a policy that has a revocable beneficiary is absolutely assigned, courts’ decisions concerning the beneficiary designation <b>vary</b>. Some courts hold that the absolute assignment revokes the beneficiary designation. Other courts have found that the designation remains in effect, but the absolute assignee has the right to change that designation.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">An irrevocable beneficiary who does not consent to a collateral assignment generally has a superior right to the policy proceeds over the rights of the assignee. Thus, in order for a collateral assignee to be repaid from the policy proceeds following the insured’s death, an irrevocable beneficiary must consent to the assignment.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">When a life insurance policy that has an irrevocable beneficiary is absolutely assigned, the beneficiary remains the irrevocable beneficiary unless he consents to a change of beneficiary. In addition, the assignee cannot take out a policy loan or surrender the policy for cash without the irrevocable beneficiary’s consent.</p><p class=\"explanations\"><b>Learning Objective: 12C. Describe how the rights of a policy beneficiary under an assignment vary according to the type of assignment and the type of beneficiary designation.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_149'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_150';
objQuestion.questionID = 117115;
objQuestion.item = 'LOMA_311_PPQ2020_150';
objQuestion.primaryLO = '12C';
objQuestion.textref = 'c. 12, p. 6';
objQuestion.textbook = 0;
objQuestion.chapter = 12;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '12C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Most individual life insurance policies include an assignment provision, which describes the roles of the insurer and the policyowner when the policy is assigned. With regard to an insurer’s role when a policy is assigned, it is correct to say</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "that an assignment is binding on an insurer even if the insurer is not notified in writing of the assignment";
arrAnsChoices[1] = "that an insurer is responsible for verifying an assignment’s validity";
arrAnsChoices[2] = "that an insurer is never obligated to pay an assignee an amount greater than the net policy proceeds regardless of whether this fact is explained in the policy";
arrAnsChoices[3] = "that an insurer cannot be held liable for acting in accordance with an assignment, even if the insurer had knowledge of circumstances that should have made it question the validity of the assignment";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473542;
arrAnsIDs[1] = 473543;
arrAnsIDs[2] = 473544;
arrAnsIDs[3] = 473545;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Life insurance policies typically state that an assignment is not binding on an insurer <b>unless</b> the insurer is notified in writing of the assignment. If the insurer does not know of an assignment and pays the proceeds of a policy in good faith, the insurer has no further liability under the policy, and the assignee cannot enforce a claim against the insurer.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The insurer is not a party to an assignment and has no control over the validity of such an agreement. The typical assignment provision in individual life insurance policies states that the insurer is not responsible for verifying the validity of an assignment of the policy.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Assignment provisions often state that the rights of the insurer take precedence over the rights of an assignee with regard to the policy proceeds. Such a statement highlights the fact that an assignee cannot receive an amount greater than the amount of the net policy proceeds—that is, the proceeds remaining after any overdue premiums and any outstanding policy loans and interest have been deducted. An insurer is never obligated to pay any claimant an amount greater than the net policy proceeds regardless of whether this fact is explained in the policy.</p><p class=\"explanations\"><b>Learning Objective: 12C. Describe how the rights of a policy beneficiary under an assignment vary according to the type of assignment and the type of beneficiary designation.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">An insurer typically cannot be held liable if it acts in good faith and in accordance with an assignment that is later declared invalid. However, if the insurer had knowledge of circumstances that should have made it question the validity of an assignment, then the insurer <b>may</b> be held liable if it acts in accordance with an invalid assignment.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_150'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_151';
objQuestion.questionID = 117116;
objQuestion.item = 'LOMA_311_PPQ2020_151';
objQuestion.primaryLO = '12B';
objQuestion.textref = 'c. 12, p. 6';
objQuestion.textbook = 0;
objQuestion.chapter = 12;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '12B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Sienna Ogletree owned a $200,000 insurance policy on her life. In October 2019, Ms.&nbsp;Ogletree assigned her policy to the Hinton Bank as security for a $150,000 loan. One year later, she assigned the same policy to the Bartow Bank as security for a $90,000 loan. Both banks notified the insurer of their assignments, but Bartow notified the insurer first. At the time of Ms.&nbsp;Ogletree’s death, she owed $130,000 to Hinton and $80,000 to Bartow. Ms.&nbsp;Ogletree resided in a state that follows the American rule to determine which assignee has a superior claim to the proceeds of a life insurance policy when both assignees have notified the insurer of their assignments. With regard to which bank has the superior claim in this situation, it is correct to say that</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Hinton’s claim to the policy proceeds is superior to Bartow’s claim, and Hinton is entitled to receive the full amount of the policy proceeds";
arrAnsChoices[1] = "Hinton’s claim to the policy proceeds is superior to Bartow’s claim, and Hinton is entitled to receive $130,000 of the policy proceeds";
arrAnsChoices[2] = "Bartow’s claim to the policy proceeds is superior to Hinton’s claim, and Bartow is entitled to receive the full amount of the policy proceeds";
arrAnsChoices[3] = "Bartow’s claim to the policy proceeds is superior to Hinton’s claim, and Bartow is entitled to receive $80,000 of the policy proceeds";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473546;
arrAnsIDs[1] = 473547;
arrAnsIDs[2] = 473548;
arrAnsIDs[3] = 473549;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">According to the American rule, the first assignment has priority over a later assignment. Thus, it is true that Hinton would have the superior claim to the policy proceeds. However, because an assignee is only entitled to receive an amount equal to the policyowner’s unpaid debt, Hinton is <b>not </b>entitled to receive the full amount of the policy proceeds.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">According to the American rule, the first assignment has priority over a later assignment. Thus, in this situation, Hinton would have the superior claim and would be entitled to receive $130,000 of the policy proceeds. The remaining $70,000 would be payable to Bartow.</p><p class=\"explanations\"><b>Learning Objective: 12B. Distinguish between an assignee’s rights under an absolute assignment and a collateral assignment.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">In states that follow the English rule to determine which assignee has a superior claim to the policy proceeds, the first assignee to notify the insurer of its assignment has priority over the other assignee. However, in this situation, Ms.&nbsp;Ogletree resided in a state that follows the American rule, which states that the first assignment has priority over a later assignment. Therefore, Bartow would <b>not</b> have the superior claim to the policy proceeds. In addition, an assignee is only entitled to receive an amount of policy proceeds equal to the policyowner’s<b> unpaid debt.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">In states that follow the English rule to determine which assignee has a superior claim to the policy proceeds, the first assignee to notify the insurer of its assignment has priority over the other assignee. However, in this situation, Ms.&nbsp;Ogletree resided in a state that follows the American rule, which states that the first assignment has priority over a later assignment. Therefore, Bartow would <b>not</b> have the superior claim and would <b>not </b>be entitled to receive $80,000 of the policy proceeds.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_151'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_152';
objQuestion.questionID = 117117;
objQuestion.item = 'LOMA_311_PPQ2020_152';
objQuestion.primaryLO = '12D';
objQuestion.textref = 'c. 12, pp. 7-8';
objQuestion.textbook = 0;
objQuestion.chapter = 12;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '12D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about life and viatical settlements. Select the answer choice containing the correct statement. </p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A policyowner cannot sell his rights in a policy if he is not terminally ill.";
arrAnsChoices[1] = "In most states, the lump sum payment for the sale of a policy is not taxable. ";
arrAnsChoices[2] = "Most states have passed laws to regulate life and viatical settlements. ";
arrAnsChoices[3] = "Viatical settlements carry risk for the seller, but not for the purchaser.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473550;
arrAnsIDs[1] = 473551;
arrAnsIDs[2] = 473552;
arrAnsIDs[3] = 473553;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A policyowner may be able to sell his rights in a policy even if he is not terminally ill. In general, the sale of an existing life insurance policy to a third party for more than its cash surrender value but less than its face value is known as a life settlement. </p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">One risk of viatical settlements for the seller is that the lump sum payment for the sale of the policy <b>may</b> be taxable, depending on the tax laws in the state where the seller resides. </p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">In most states, the seller of a policy must be both policyowner and insured. During the settlement process, typically an advisor and a broker act as facilitators between the seller and the purchaser. The purchaser is typically a viatical settlement company, or life settlement company, which is an organization that exists to buy life insurance policies from policyowners at a discount. An organization must meet state licensing requirements in order to legally purchase viatical or life settlements. </p><p class=\"explanations\"><b>Learning Objective: 12D. Distinguish between a viatical settlement and a life settlement.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Viatical settlements carry some risk for <b>both</b> the seller and the purchaser. The seller must be certain that a viatical settlement is the proper instrument to meet her needs; in some cases, an accelerated death benefit or policy loan might be more beneficial, as these options would allow the policyowner to receive some cash while retaining ownership of the policy. The risk to the purchaser is that the seller might live longer than expected, thus reducing or even eliminating the return on the purchaser’s investment. </p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_152'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_153';
objQuestion.questionID = 117118;
objQuestion.item = 'LOMA_311_PPQ2020_153';
objQuestion.primaryLO = '12E';
objQuestion.textref = 'c. 12, p. 11';
objQuestion.textbook = 0;
objQuestion.chapter = 12;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '12E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Each state has enacted laws that govern how a judgment creditor may enforce a judgment by looking to property owned by a debtor, and laws in all states provide exemptions for life insurance policies. The following statements are about these laws. Select the answer choice containing the correct statement. </p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "While a life insurance policy is in force, the policy death benefit, cash value, and accrued dividends are subject to the claims of the policyowner’s judgment creditors.";
arrAnsChoices[1] = "If a policyowner surrenders his life insurance policy for its cash surrender value, the money held by the policyowner is exempt from the claims of the policyowner’s judgment creditors.";
arrAnsChoices[2] = "While a life insurance policy is in force, a beneficiary’s judgment creditors are not able to claim the policy death benefit.";
arrAnsChoices[3] = "Exemption laws, which are the same in every state, protect life insurance policy proceeds from the claims of a policyowner’s judgment creditors but do not protect the proceeds from the claims of a beneficiary’s judgment creditors.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473554;
arrAnsIDs[1] = 473555;
arrAnsIDs[2] = 473556;
arrAnsIDs[3] = 473557;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Exemption laws in most states protect life insurance policy death benefits, cash values, and accrued dividends from the reach of judgment creditors. While a policy is in force, most such values are <b>exempt</b> from the claims of the policyowner’s judgment creditors.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Exemption laws in most states protect the cash value of a life insurance policy from the reach of the policyowner’s judgment creditors while the policy is in force. However, once an insurer pays a policy’s cash surrender value to the policyowner, that money held by the policyowner generally <b>loses its exemption </b>from his judgment creditors’ claims.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A beneficiary’s judgment creditors are not able to claim the policy death benefit while the policy is in force. However, upon the insured’s death, the policy proceeds are payable to the beneficiary and may be subject to the claims of the judgment beneficiary’s creditors. The applicable state’s exemption law determines the rights of the beneficiary’s judgment creditors, and statutes vary a great deal.</p><p class=\"explanations\"><b>Learning Objective: 12E. Explain the rights that creditors of a life insurance policyowner or beneficiary have in the policy.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Exemption laws in some states protect life insurance policy proceeds from the claims of the policyowner’s judgment creditors but do not protect the proceeds from the claims of the beneficiary’s judgment creditors. Laws in other<b> </b>states do<b> </b>protect policy proceeds from the judgment creditors of both the policyowner and the beneficiary.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_153'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_154';
objQuestion.questionID = 117119;
objQuestion.item = 'LOMA_311_PPQ2020_154';
objQuestion.primaryLO = '12E';
objQuestion.textref = 'c. 12, pp. 11-12';
objQuestion.textbook = 0;
objQuestion.chapter = 12;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '12E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">When Arnold Hagen purchased a $200,000 insurance policy on his life, he owed $100,000 to Jacob Nelson. In order to ensure that the debt would be repaid, Mr.&nbsp;Hagen named Mr.&nbsp;Nelson as the beneficiary of his policy. At the time of Mr.&nbsp;Hagen’s death, he had not repaid any part of his debt to Mr.&nbsp;Nelson, and Mr.&nbsp;Nelson had paid $2,000 in premiums to keep the policy in force. In this situation, it is correct to say that Mr.&nbsp;Nelson most likely was entitled to receive</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "nothing, because he did not have an insurable interest in Mr.&nbsp;Hagen’s life";
arrAnsChoices[1] = "$100,000 of the policy proceeds, but he is not entitled to recover the $2,000 that he paid in premiums to keep Mr.&nbsp;Hagen’s policy in force";
arrAnsChoices[2] = "$100,000 of the policy proceeds, and he also is entitled to recover the $2,000 that he paid in premiums, plus interest";
arrAnsChoices[3] = "the entire policy proceeds, because he had an insurable interest in Mr.&nbsp;Hagen’s life";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473558;
arrAnsIDs[1] = 473559;
arrAnsIDs[2] = 473560;
arrAnsIDs[3] = 473561;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">When a debtor owns an insurance policy on his own life and names a creditor as the policy beneficiary, the insurance contract is considered to be valid because a creditor always has an insurable interest in the life of his debtor. Thus, in this situation, Mr.&nbsp;Nelson <b>would</b> be entitled to a part of the policy proceeds because he was the policy beneficiary.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that Mr.&nbsp;Nelson would be entitled to receive $100,000, the amount of the unpaid debt. In most states, the creditor who is named as the beneficiary of a life insurance policy owned by the debtor can recover only the amount of the unpaid debt. However, Mr.&nbsp;Nelson also <b>is </b>entitled to recover the amount of all premiums, plus interest, that he paid to keep the policy in force.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">In most states, when a debtor owns an insurance policy on his own life and names a creditor as the policy beneficiary, the creditor can recover only the amount of the unpaid debt. Therefore, Mr.&nbsp;Nelson would be entitled to receive $100,000, the amount of the unpaid debt. If the creditor paid any premiums for the policy, he can recover those premiums plus interest. Any policy proceeds remaining after the creditor is paid are payable to the policyowner-insured’s estate.</p><p class=\"explanations\"><b>Learning Objective: 12E. Explain the rights that creditors of a life insurance policyowner or beneficiary have in the policy.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A creditor always has an insurable interest in the life of his debtor. In most states, the creditor can recover only the amount of the unpaid debt. In this case, the amount of the unpaid debt is $100,000, <b>not </b>the full amount of the policy proceeds.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_154'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_155';
objQuestion.questionID = 117120;
objQuestion.item = 'LOMA_311_PPQ2020_155';
objQuestion.primaryLO = '12F';
objQuestion.textref = 'c. 12, pp. 12-13';
objQuestion.textbook = 0;
objQuestion.chapter = 12;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '12F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Yan Wu created a trust document. According to the document, Cannon Bank holds legal title to the trust property and must manage the trust property for the benefit of Mr.&nbsp;Wu’s son, Jiansheng, who has equitable title to the property. In this situation, Cannon is the (<b>grantor / trustee</b>) of the trust, and Jiansheng is the (<b>trust beneficiary / settlor</b>) of the trust.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "grantor / trust beneficiary";
arrAnsChoices[1] = "grantor / settlor";
arrAnsChoices[2] = "trustee / trust beneficiary";
arrAnsChoices[3] = "trustee / settlor";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473562;
arrAnsIDs[1] = 473563;
arrAnsIDs[2] = 473564;
arrAnsIDs[3] = 473565;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that Jiansheng is the trust beneficiary because the trust was created for Jiansheng’s benefit. However, the settlor, or grantor, is the person who created the trust. Mr.&nbsp;Wu, not Cannon Bank, created the trust; therefore, Cannon is <b>not </b>the grantor.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The settlor, or grantor, is the person who created the trust. Mr.&nbsp;Wu, not Cannon Bank, created the trust; therefore, Cannon Bank is <b>not </b>the grantor. In addition, Jiansheng, for whose benefit the trust was created, is <b>not </b>the settlor in this situation.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A trust is created when the settlor (grantor)—Mr.&nbsp;Wu, in this situation—transfers ownership of property to a trustee—Cannon Bank—which has a duty to manage the property for the benefit of the trust beneficiary, Jiansheng. Ownership of trust property is split between the trustee and the trust beneficiary. In this case, Cannon Bank has formal legal title to the property and, thus, is the legal owner of the property. Jiansheng has equitable title to the trust property, which means that he has ownership rights based on considerations of fairness and equity.</p><p class=\"explanations\"><b>Learning Objective: 12F. Identify the parties to a trust agreement and describe the duties of the trustee and the rights of the trust beneficiary.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that Cannon Bank is the trustee in this situation because Cannon holds formal legal title to the property for the benefit of Jiansheng, Mr.&nbsp;Wu’s son. However, Jiansheng is the trust beneficiary, <b>not </b>the settlor, of the trust. The settlor, or grantor, is the person who created the trust.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_155'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_156';
objQuestion.questionID = 117121;
objQuestion.item = 'LOMA_311_PPQ2020_156';
objQuestion.primaryLO = '12G';
objQuestion.textref = 'c. 12, p. 15';
objQuestion.textbook = 0;
objQuestion.chapter = 12;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '12G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">One characteristic of an <i>inter vivos</i> trust is that</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "a signed, written document is always required to create an inter vivos trust";
arrAnsChoices[1] = "the settlor must establish an inter vivos trust as a revocable trust";
arrAnsChoices[2] = "the terms of an inter vivos trust must be included in the settlor’s will";
arrAnsChoices[3] = "an inter vivos trust takes effect during the settlor’s lifetime";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473566;
arrAnsIDs[1] = 473567;
arrAnsIDs[2] = 473568;
arrAnsIDs[3] = 473569;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">An inter vivos trust need <b>not</b> be signed, unless the trust property includes real property. In practice, however, the settlor usually drafts and signs a written document, known as a trust agreement, that spells out the terms of the trust, including instructions as to how the trustee is to handle the trust property.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A settlor may establish an inter vivos trust as a revocable trust <b>or</b> an irrevocable trust. When a trust is revocable, the settlor retains the right to change the terms of the trust or to dissolve the trust. When a trust is irrevocable, the settlor may not change or revoke the trust.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Typically, the terms of a <b>testamentary</b> trust are included in the settlor’s will. For this reason, a testamentary trust must comply with the applicable wills statute to be valid.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">An inter vivos trust or a living trust is a trust that takes effect during the settlor’s lifetime. In contrast to a living trust, a testamentary trust is a trust that takes effect at the settlor’s death.</p><p class=\"explanations\"><b>Learning Objective: 12G. Describe reasons for establishing a trust and distinguish among various types of trust.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_156'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_157';
objQuestion.questionID = 117122;
objQuestion.item = 'LOMA_311_PPQ2020_157';
objQuestion.primaryLO = '12H';
objQuestion.textref = 'c. 12, p. 16';
objQuestion.textbook = 0;
objQuestion.chapter = 12;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '12H';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">One type of individual life insurance settlement option is the fixed period option. Under this settlement option, the</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "policy proceeds are temporarily left on deposit with the insurer and the interest earned is paid out annually, semiannually, quarterly, or monthly";
arrAnsChoices[1] = "insurer pays the policy proceeds and interest in a series of annual or more frequent installments for a preselected period";
arrAnsChoices[2] = "insurer uses the policy proceeds and interest to pay a preselected sum in a series of annual or more frequent installments for as long as the proceeds and interest last";
arrAnsChoices[3] = "insurer uses the policy proceeds and interest to pay a series of annual or more frequent installments over the entire lifetime of the person designated to receive the policy benefits";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473570;
arrAnsIDs[1] = 473571;
arrAnsIDs[2] = 473572;
arrAnsIDs[3] = 473573;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The settlement option described here is the <b>interest option</b>, which is a common settlement option offered in individual life insurance policies.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Although life insurance policy proceeds usually are paid in a single lump sum following the insured’s death, policies provide other methods of payment, including the fixed period option. Most states require individual life insurance policies to include a settlement options provision, which grants the policyowner or beneficiary several choices as to how the insurer will pay the policy proceeds.</p><p class=\"explanations\"><b>Learning Objective: 12H. Identify the typical settlement options that a life insurance policy provides and describe the rights of beneficiaries and payees in regard to settlement options.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The settlement option described here is the <b>fixed amount option</b>, which is a common settlement option offered in individual life insurance policies.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The settlement option described here is the <b>life income option</b>, which is a common settlement option offered in individual life insurance policies.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_157'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_158';
objQuestion.questionID = 117123;
objQuestion.item = 'LOMA_311_PPQ2020_158';
objQuestion.primaryLO = '12H';
objQuestion.textref = 'c. 12, pp. 17-18';
objQuestion.textbook = 0;
objQuestion.chapter = 12;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '12H';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">A spendthrift clause provision can be included in a life insurance policy for the benefit of the policy beneficiary. With regard to the effects of a typical spendthrift clause, it is correct to say</p><ol type=\"A\" class=\"combo\"><li>That a beneficiary can change the terms on which the policy proceeds are payable</li><li>That the creditors of a beneficiary cannot reach the policy proceeds even after the insurer has paid those proceeds to the beneficiary</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473574;
arrAnsIDs[1] = 473575;
arrAnsIDs[2] = 473576;
arrAnsIDs[3] = 473577;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is incorrect. When a life insurance policy includes a spendthrift clause, the beneficiary is <b>prohibited</b> from changing the terms on which the policy proceeds are payable.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is incorrect. When a life insurance policy includes a spendthrift clause, the beneficiary’s creditors cannot reach any money that is held by the insurer. However, after an insurer pays money to a beneficiary, those funds <b>can</b> be reached by the beneficiary’s creditors.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Both statements are incorrect. When a life insurance policy includes a spendthrift clause, the policy beneficiary is <b>prohibited </b>from assigning or otherwise transferring her interest in the policy proceeds and from changing the terms on which the policy proceeds are payable. </p><p class=\"explanations\">The beneficiary’s creditors cannot reach any money that is held by the insurer. However, after the insurer pays money to a beneficiary, those funds <b>can </b>be reached by the beneficiary’s creditors.</p><p class=\"explanations\"><b>Learning Objective: 12H. Identify the typical settlement options that a life insurance policy provides and describe the rights of beneficiaries and payees in regard to settlement options.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_158'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['12A'] = "12A. Identify ways in which the owner of a life insurance policy can transfer ownership of the policy to another person.";
arrlotext['12B'] = "12B. Distinguish between an assignee’s rights under an absolute assignment and a collateral assignment.";
arrlotext['12C'] = "12C. Describe how the rights of a policy beneficiary under an assignment vary according to the type of assignment and the type of beneficiary designation.";
arrlotext['12D'] = "12D. Distinguish between a viatical settlement and a life settlement.";
arrlotext['12E'] = "12E. Explain the rights that creditors of a life insurance policyowner or beneficiary have in the policy.";
arrlotext['12F'] = "12F. Identify the parties to a trust agreement and describe the duties of the trustee and the rights of the trust beneficiary.";
arrlotext['12G'] = "12G. Describe reasons for establishing a trust and distinguish among various types of trust.";
arrlotext['12H'] = "12H. Identify the typical settlement options that a life insurance policy provides and describe the rights of beneficiaries and payees in regard to settlement options.";
