var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2020';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 311 Practice Questions, Chapter 10";
var coursename = 'LOMA 311';
var modulenumber = 4;
var title = "LOMA_311_PPQ2020_0_10";
var intNumPools = 1;
var numQ = 10;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Business Law for Insurance Professionals (2020)";
arrNumChap[0] = 1;
var thisChap = '10';

objPool = new Object(); 
objPool.intSelectCount = 10;
objPool.formID = 2380;
objPool.formName = 'PPQ2020_0_10';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_311_PQ_126';
arrPoolQuestions[1] = 'LOMA_311_PQ_127';
arrPoolQuestions[2] = 'LOMA_311_PQ_128';
arrPoolQuestions[3] = 'LOMA_311_PQ_129';
arrPoolQuestions[4] = 'LOMA_311_PQ_130';
arrPoolQuestions[5] = 'LOMA_311_PQ_131';
arrPoolQuestions[6] = 'LOMA_311_PQ_132';
arrPoolQuestions[7] = 'LOMA_311_PQ_133';
arrPoolQuestions[8] = 'LOMA_311_PQ_134';
arrPoolQuestions[9] = 'LOMA_311_PQ_135';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_126';
objQuestion.questionID = 117091;
objQuestion.item = 'LOMA_311_PPQ2020_126';
objQuestion.primaryLO = '10A';
objQuestion.textref = 'c. 10, p. 3';
objQuestion.textbook = 0;
objQuestion.chapter = 10;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '10A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Bryan Levin recently applied for and was issued a life insurance policy covering his life by the Plantation Life Insurance Company. The formation of Mr.&nbsp;Levin’s life insurance contract involved the following steps:</p><ul class=\"examul\"><li><b>Step 1</b>: Mr.&nbsp;Levin completed an application and submitted it, along with the initial premium payment, based on a standard premium rate, to Plantation</li><li><b>Step 2</b>: Plantation classified Mr.&nbsp;Levin as a substandard risk, issued the policy at a higher-than-standard premium rate, and delivered the policy to Mr.&nbsp;Levin.</li><li><b>Step 3</b>: Mr.&nbsp;Levin took delivery of the policy and paid the additional premium to Plantation.</li></ul><p class=\"stem\">In this situation, an offer was made in</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Step 1 and Step 3";
arrAnsChoices[1] = "Step 1, and an acceptance was made in Step 2";
arrAnsChoices[2] = "Step 1, and a counteroffer was made in Step 2";
arrAnsChoices[3] = "Step 3, and an acceptance was made in Step 1";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473442;
arrAnsIDs[1] = 473443;
arrAnsIDs[2] = 473444;
arrAnsIDs[3] = 473445;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that Mr.&nbsp;Levin made an offer in Step 1 when he submitted a completed policy application and the initial premium to Plantation. However, an <b>acceptance</b>, not an offer, was made in Step 3.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that Mr.&nbsp;Levin made an offer in Step 1 when he submitted a completed policy application and the initial premium to Plantation. However, because Plantation issued a policy that contained terms different from those in Mr.&nbsp;Levin’s offer, Plantation did <b>not </b>accept Mr.&nbsp;Levin’s offer to contract in Step 2.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">In Step 1, Mr.&nbsp;Levin made an offer to contract with Plantation. In Step 2, Plantation rejected Mr.&nbsp;Levin’s offer and made a counteroffer by issuing and delivering to Mr.&nbsp;Levin a policy on terms other than those he applied for. In this case, Plantation is now the party making the offer—the offeror—and Mr.&nbsp;Levin is now the offeree. In Step 3, Mr.&nbsp;Levin chose to accept Plantation’s offer of coverage at a higher-than-standard premium rate by accepting delivery of the policy and paying the additional premium.</p><p class=\"explanations\"><b>Learning Objective: 10A. Analyze the process of offer and acceptance and identify other requirements the parties must meet to form a valid life insurance contract.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">An <b>acceptance</b>, not an offer, was made in Step 3. In addition, an <b>offer</b>, not an acceptance, was made in Step 1.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_126'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_127';
objQuestion.questionID = 117092;
objQuestion.item = 'LOMA_311_PPQ2020_127';
objQuestion.primaryLO = '10A';
objQuestion.textref = 'c. 10, p. 5';
objQuestion.textbook = 0;
objQuestion.chapter = 10;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '10A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">In the case of a life insurance contract, the legally adequate consideration given by the applicant in return for the insurer’s promise to pay policy benefits consists of the applicant’s</p><ol type=\"A\" class=\"combo\"><li>Submission of an application for insurance</li><li>Payment of the initial premium</li><li>Promise to pay renewal premiums</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A, B, and C";
arrAnsChoices[1] = "A and B only";
arrAnsChoices[2] = "B and C only";
arrAnsChoices[3] = "A only";
arrAnsChoices[4] = "B only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473446;
arrAnsIDs[1] = 473447;
arrAnsIDs[2] = 473448;
arrAnsIDs[3] = 473449;
arrAnsIDs[4] = 473450;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these elements is not considered to be legally adequate consideration for the formation of a life insurance contract.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Life insurance contracts are unilateral contracts in which only the insurer makes a legally enforceable promise—that it will pay policy benefits upon the occurrence of the events insured against. Thus, the applicant must pay adequate consideration in exchange for the insurer’s contractual promises. Legally adequate consideration for a life insurance contract consists of the applicant’s submission of an application for insurance and the payment of the initial premium.</p><p class=\"explanations\"><b>Learning Objective: 10A. Analyze the process of offer and acceptance and identify other requirements the parties must meet to form a valid life insurance contract.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">At least one of these elements is not considered to be legally adequate consideration for the formation of a life insurance contract.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Element A is one element of legally adequate consideration, but it is <b>not</b> the only element needed to meet the requirement for legally adequate consideration.</p>";
arrAnswerFeedback[4] = "<p class=\"explanations\">Statement B is one element of legally adequate consideration, but it is <b>not </b>the only element needed to meet the requirement for legally adequate consideration.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_127'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_128';
objQuestion.questionID = 117093;
objQuestion.item = 'LOMA_311_PPQ2020_128';
objQuestion.primaryLO = '10A';
objQuestion.textref = 'c. 10, p. 5';
objQuestion.textbook = 0;
objQuestion.chapter = 10;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '10A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">In the United States, insurance contracts entered into by a minor who lives in a state that has not enacted any specific laws regarding minors and insurance contracts generally are</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "void";
arrAnsChoices[1] = "voidable by the insurer only";
arrAnsChoices[2] = "voidable by the minor only";
arrAnsChoices[3] = "valid and enforceable by both the minor and the insurer";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473451;
arrAnsIDs[1] = 473452;
arrAnsIDs[2] = 473453;
arrAnsIDs[3] = 473454;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">According to the common law, insurance contracts entered into by a minor are not<b> </b>void because a minor can enforce the contract against the other party to the contract—in this case, the insurer. A void contract is an agreement that was never enforceable<b> </b>by law.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Insurers that are licensed to conduct business within the applicable state have the legal capacity to enter into insurance contracts in the state. Because insurers have contractual capacity to conduct insurance business, insurance contracts entered into by a minor generally are <b>not </b>voidable by the insurer.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Because the law does not consider insurance a necessity, courts have held that by default insurance contracts entered into by a minor generally are voidable by the minor. When a minor decides to avoid an insurance contract, she is entitled to a refund of the premiums she paid. As a result, the minor benefits from the insurance coverage in existence before she avoided the contract and pays nothing for it. Most states modified this common law rule by enacting laws that enable minors of a stated minimum age to enter into enforceable life insurance contracts.</p><p class=\"explanations\"><b>Learning Objective: 10A. Analyze the process of offer and acceptance and identify other requirements the parties must meet to form a valid life insurance contract.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">According to the common law, a minor can enforce a contract against the other party to the contract—in this case, the insurer. However, the other party—the insurer—<b>cannot </b>enforce the contract against the minor.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_128'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_129';
objQuestion.questionID = 117094;
objQuestion.item = 'LOMA_311_PPQ2020_129';
objQuestion.primaryLO = '10B';
objQuestion.textref = 'c. 10, p. 7';
objQuestion.textbook = 0;
objQuestion.chapter = 10;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '10B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Alex Dorsey purchased an insurance policy on the life of his minor child, Jen, and named himself as the policy beneficiary. With regard to the general rule regarding insurable interest requirements in most U.S. states, it is correct to say that, for the insurance contract to be valid, Alex must have an insurable interest in Jen’s life</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "only if Jen consented to the issuance of the policy";
arrAnsChoices[1] = "only at the time of contracting";
arrAnsChoices[2] = "only at the time of Jen’s death";
arrAnsChoices[3] = "continuously from the time of contracting until Jen’s death";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473455;
arrAnsIDs[1] = 473456;
arrAnsIDs[2] = 473457;
arrAnsIDs[3] = 473458;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Most states presume that an insurable interest exists between certain close family members, including between parents and children. In addition, most states require a proposed insured to consent to the issuance of a policy on her life. As an exception to this rule, a parent generally is permitted to insure the life of a minor child without the child’s consent.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">In most states, an insurable interest is presumed to exist between certain close family members. Thus, an insured’s spouse, mother, father, child, grandparent, grandchild, brother, and sister are presumed to have an insurable interest in the life of the insured. The insurable interest must exist only at the time of contracting and is not required to continue throughout the life of the policy.</p><p class=\"explanations\"><b>Learning Objective: 10B. Explain the significance of the insurable interest requirement and the consent requirement, and describe how the parties meet these requirements.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The insurable interest must exist only at the time of contracting and is <b>not </b>required to continue throughout the life of the policy.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The insurable interest must exist only at the time of contracting and is <b>not </b>required to continue throughout the life of the policy.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_129'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_130';
objQuestion.questionID = 117095;
objQuestion.item = 'LOMA_311_PPQ2020_130';
objQuestion.primaryLO = '10B';
objQuestion.textref = 'c. 10, p. 7';
objQuestion.textbook = 0;
objQuestion.chapter = 10;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '10B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Business relationships may give someone a financial interest in another person’s continued life. The following statement(s) can correctly be made about insurable interest and business relationships:</p><ol type=\"A\" class=\"combo\"><li>A creditor has an insurable interest in the lives of its debtors.</li><li>An employer has an insurable interest in the lives of its key employees.</li><li>Business partners are each considered to have an insurable interest in the lives of the other partners.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A, B, and C";
arrAnsChoices[1] = "A and B only";
arrAnsChoices[2] = "A and C only";
arrAnsChoices[3] = "B only";
arrAnsChoices[4] = "C only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473459;
arrAnsIDs[1] = 473460;
arrAnsIDs[2] = 473461;
arrAnsIDs[3] = 473462;
arrAnsIDs[4] = 473463;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Anyone other than a close relative must demonstrate that she has a financial interest in the continued life of the insured to satisfy the insurable interest requirement. An individual who is not a close relative of an insured may be financially dependent on the insured and, thus, would be harmed if the insured died. Business relationships—employers, creditors, and partners—also may give someone a financial interest in another person’s continued life.</p><p class=\"explanations\"><b>Learning Objective: 10B. Explain the significance of the insurable interest requirement and the consent requirement, and describe how the parties meet these requirements.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statements A and B are correct. However, Statement C is also correct.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statements A and C are correct. However, Statement B is also correct.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Statement B is correct, but it is not the only correct response.</p>";
arrAnswerFeedback[4] = "<p class=\"explanations\">Statement C is correct, but it is not<b> </b>the only correct response.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_130'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_131';
objQuestion.questionID = 117096;
objQuestion.item = 'LOMA_311_PPQ2020_131';
objQuestion.primaryLO = '10C';
objQuestion.textref = 'c. 10, p. 9';
objQuestion.textbook = 0;
objQuestion.chapter = 10;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '10C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">On September 3, Jackie Seeley applied for an individual insurance policy on her life and paid the initial premium for policy coverage. On September 13, the insurer issued the policy as applied for and mailed it to the insurance producer for delivery to Ms.&nbsp;Seeley. However, the producer never received the policy. The insurer mailed a second copy of the policy to the insurance producer, who received it on September 21. Ms.&nbsp;Seeley died on September 24, before the producer was able to deliver the policy to her. According to the general rule, the earliest date on which Ms.&nbsp;Seeley’s policy is considered to have been constructively delivered is</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "September 3";
arrAnsChoices[1] = "September 13";
arrAnsChoices[2] = "September 21";
arrAnsChoices[3] = "September 24";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473464;
arrAnsIDs[1] = 473465;
arrAnsIDs[2] = 473466;
arrAnsIDs[3] = 473467;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Constructive delivery did <b>not </b>occur on September 3. </p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Sometimes a policy is considered to have been delivered even though it never actually reached the policyowner. Delivery in such cases is called constructive delivery, which is a legally adequate delivery of a life insurance policy that occurs when the insurer parts with control of the policy and intends to be bound to the terms of the contract. In this case, the policy never actually reached the policyowner. However, Ms.&nbsp;Seeley’s policy would be considered effective, and the insurer would be liable to pay the policy death benefit.</p><p class=\"explanations\"><b>Learning Objective: 10C. Determine in a given situation whether an insurance policy would be considered to have been delivered to the policyowner.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Constructive delivery did <b>not </b>occur on September 21.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Constructive delivery did <b>not </b>occur on September 24</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_131'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_132';
objQuestion.questionID = 117097;
objQuestion.item = 'LOMA_311_PPQ2020_132';
objQuestion.primaryLO = '10D';
objQuestion.textref = 'c. 10, pp. 9-10';
objQuestion.textbook = 0;
objQuestion.chapter = 10;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '10D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Stellar Life Insurance Company, a U.S. insurance company, is not a fraternal insurer. With regard to open contracts and closed contracts, the individual life insurance policies that Stellar issues most likely are considered to be (<b>open / closed</b>) contracts. The entire contract provision of such contracts states that (<b>all / only some</b>) of the documents that constitute the contract must be attached to the policy.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "open / all";
arrAnsChoices[1] = "open / only some";
arrAnsChoices[2] = "closed / all";
arrAnsChoices[3] = "closed / only some";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473468;
arrAnsIDs[1] = 473469;
arrAnsIDs[2] = 473470;
arrAnsIDs[3] = 473471;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that, under the entire contract provision, all documents that constitute the contract must be attached to the policy. However, only fraternal insurers issue open contracts. Stellar is not a fraternal insurer; therefore, its life insurance policies are closed contracts.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Only fraternal insurers issue open contracts. Stellar is not a fraternal insurer; therefore, its life insurance policies are closed contracts and the entire contract provision specifies that <b>all</b> documents which constitute the contract must be attached to the policy.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">With the exception of fraternal insurers, U.S. insurers issue individual life insurance policies that are closed contracts. A closed contract is a contract for which only those terms and conditions that are printed in—or attached to—the contract are considered to be part of the contract. In a closed life insurance contract, the entire contract provision states that the contract consists of the policy, any attached riders and endorsements, and the attached copy of the application.</p><p class=\"explanations\"><b>Learning Objective: 10D. Distinguish between a closed contract and an open contract, and identify the documents that constitute the entire contract between the insurer and the policyowner.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that, with the exception of fraternal insurers, U.S. insurers issue individual life insurance policies that are closed contracts. However, the entire contract provision states that the contract consists of the policy, any attached riders and endorsements, and the attached copy of the application. This requirement means that <b>all </b>documents that constitute the contract must be attached to the policy.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_132'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_133';
objQuestion.questionID = 117098;
objQuestion.item = 'LOMA_311_PPQ2020_133';
objQuestion.primaryLO = '10E';
objQuestion.textref = 'c. 10, p. 14';
objQuestion.textbook = 0;
objQuestion.chapter = 10;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '10E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">On April 16, Kendra Bloom applied for an insurance policy on her life by submitting an application and initial premium payment to the Mont Insurance Company, a U.S. insurer. On this same date, Mont issued to Ms.&nbsp;Bloom a premium receipt that included a temporary insurance agreement. According to the terms of this agreement, temporary insurance coverage on Ms.&nbsp;Bloom’s life became effective on April 16, and the coverage would remain effective until the earliest of the following occurrences: (1) Mont issues Ms.&nbsp;Bloom a policy, (2) Mont declines Ms.&nbsp;Bloom’s application, (3) Mont terminates or suspends coverage under the receipt, or (4) a time period of 45 days expires. This information indicates that Ms.&nbsp;Bloom received a type of premium receipt known as</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "an approval premium receipt";
arrAnsChoices[1] = "a binding premium receipt";
arrAnsChoices[2] = "an insurability premium receipt";
arrAnsChoices[3] = "a conditional premium receipt";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473472;
arrAnsIDs[1] = 473473;
arrAnsIDs[2] = 473474;
arrAnsIDs[3] = 473475;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">An approval premium receipt is a premium receipt that provides temporary insurance coverage only when the insurer approves<b> </b>the proposed insured as a standard or preferred risk. Ms.&nbsp;Bloom’s coverage became effective immediately under the premium receipt she received.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A binding premium receipt provides temporary insurance coverage that becomes effective on the date specified in the receipt. Compared to the terms of other types of premium receipts, the terms of binding premium receipts are more advantageous to applicants and less advantageous to insurers because the insurer provides insurance coverage before it has had the opportunity to evaluate whether the proposed insured is insurable.</p><p class=\"explanations\"><b>Learning Objective: 10E Analyze the various types of temporary insurance agreements, and explain how courts apply the doctrine of reasonable expectations to interpret premium receipts.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">An insurability premium receipt is a premium receipt that provides temporary insurance coverage on condition that the insurer finds the proposed insured to be insurable<b> </b>as a standard or preferred risk. Ms.&nbsp;Bloom’s coverage became effective immediately without the need to meet any specified conditions.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A conditional premium receipt provides temporary insurance coverage only if specified conditions are met. Ms.&nbsp;Bloom’s coverage became effective immediately.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_133'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_134';
objQuestion.questionID = 117099;
objQuestion.item = 'LOMA_311_PPQ2020_134';
objQuestion.primaryLO = '10F';
objQuestion.textref = 'c. 10, p. 16';
objQuestion.textbook = 0;
objQuestion.chapter = 10;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '10F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about the requirements that must be met to create a valid annuity contract. Three statements are true, and one statement is false. Select the answer choice containing the <B>FALSE</B> statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Insurable interest requirements are typically imposed in creating a valid annuity contract.";
arrAnsChoices[1] = "The parties to an annuity contract create a valid contract by meeting the same four requirements as do the parties to any informal contract.";
arrAnsChoices[2] = "Both parties to an annuity contract must have contractual capacity.";
arrAnsChoices[3] = "The applicant for an annuity usually pays all or a part of the consideration required to pay for the annuity when he submits the application.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473476;
arrAnsIDs[1] = 473477;
arrAnsIDs[2] = 473478;
arrAnsIDs[3] = 473479;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">This is a false statement; therefore, it is the correct response. Unlike life insurance, an annuity usually does not present the opportunity for the applicant to wager on someone’s life or for someone to benefit from another person’s death. Thus, insurable interest requirements are not imposed. As long as no illegal purposes are involved, the creation of an annuity contract meets the lawful purpose requirement.</p><p class=\"explanations\"><b>Learning Objective: 10F Identify the steps involved in the formation of annuity contracts.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">This is a true statement; therefore, it is <b>not</b> the correct response.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">This is a true statement; therefore, it is <b>not</b> the correct response.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">This is a true statement; therefore, it is <b>not</b> the correct response.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_134'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_135';
objQuestion.questionID = 117100;
objQuestion.item = 'LOMA_311_PPQ2020_135';
objQuestion.primaryLO = '10G';
objQuestion.textref = 'c. 10, p. 18';
objQuestion.textbook = 0;
objQuestion.chapter = 10;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '10G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">An insurance agent’s authority to act on behalf of an insurer typically includes the actual authority to perform the following activities:</p><ol type=\"A\" class=\"combo\"><li>Accept initial premium payments on behalf of the insurer</li><li>Accept renewal premium payments on behalf of the insurer</li><li>Enter into binding insurance contracts on behalf of the insurer</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A, B, and C";
arrAnsChoices[1] = "A and B only";
arrAnsChoices[2] = "B and C only";
arrAnsChoices[3] = "A only";
arrAnsChoices[4] = "C only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473480;
arrAnsIDs[1] = 473481;
arrAnsIDs[2] = 473482;
arrAnsIDs[3] = 473483;
arrAnsIDs[4] = 473484;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these activities is <b>not </b>within the scope of an insurance agent’s actual authority. </p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">At least one of these activities is <b>not </b>within the scope of an insurance agent’s actual authority.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">At least one of these activities is <b>not </b>within the scope of an insurance agent’s actual authority.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">As the principal in an agency relationship, an insurer has the right to determine the scope of the agent’s authority, and the scope of that authority is spelled out in the agency agreement. Insurance agents typically have actual authority to accept initial premium payments on behalf of an insurer. Insurance agents, however, generally do not have actual authority to accept renewal premium payments. In addition, with the exception of binding an insurer to providing temporary coverage under a premium receipt, an agent does not have actual authority to enter into binding life insurance contracts on an insurer’s behalf.</p><p class=\"explanations\"><b>Learning Objective: 10G Describe the types of activities that agency agreements typically authorize insurance agents to perform on behalf of an insurer.</b></p>";
arrAnswerFeedback[4] = "<p class=\"explanations\">With the exception of binding an insurer to providing temporary coverage under a premium receipt, an agent who sells life insurance does <b>not</b> have actual authority to enter into binding life insurance contracts on an insurer’s behalf.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_135'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['10A'] = "10A. Analyze the process of offer and acceptance and identify other requirements the parties must meet to form a valid life insurance contract.";
arrlotext['10B'] = "10B. Explain the significance of the insurable interest requirement and the consent requirement, and describe how the parties meet these requirements.";
arrlotext['10C'] = "10C. Determine in a given situation whether an insurance policy would be considered to have been delivered to the policyowner.";
arrlotext['10D'] = "10D. Distinguish between a closed contract and an open contract, and identify the documents that constitute the entire contract between the insurer and the policyowner.";
arrlotext['10E'] = "10E Analyze the various types of temporary insurance agreements, and explain how courts apply the doctrine of reasonable expectations to interpret premium receipts.";
arrlotext['10F'] = "10F Identify the steps involved in the formation of annuity contracts.";
arrlotext['10G'] = "10G Describe the types of activities that agency agreements typically authorize insurance agents to perform on behalf of an insurer.";
