var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2020';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 311 Practice Questions, Chapter 14";
var coursename = 'LOMA 311';
var modulenumber = 4;
var title = "LOMA_311_PPQ2020_0_14";
var intNumPools = 1;
var numQ = 11;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Business Law for Insurance Professionals (2020)";
arrNumChap[0] = 1;
var thisChap = '14';

objPool = new Object(); 
objPool.intSelectCount = 11;
objPool.formID = 2380;
objPool.formName = 'PPQ2020_0_14';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_311_PQ_170';
arrPoolQuestions[1] = 'LOMA_311_PQ_171';
arrPoolQuestions[2] = 'LOMA_311_PQ_172';
arrPoolQuestions[3] = 'LOMA_311_PQ_173';
arrPoolQuestions[4] = 'LOMA_311_PQ_174';
arrPoolQuestions[5] = 'LOMA_311_PQ_175';
arrPoolQuestions[6] = 'LOMA_311_PQ_176';
arrPoolQuestions[7] = 'LOMA_311_PQ_177';
arrPoolQuestions[8] = 'LOMA_311_PQ_178';
arrPoolQuestions[9] = 'LOMA_311_PQ_179';
arrPoolQuestions[10] = 'LOMA_311_PQ_180';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_170';
objQuestion.questionID = 117135;
objQuestion.item = 'LOMA_311_PPQ2020_170';
objQuestion.primaryLO = '14A';
objQuestion.textref = 'c. 14, p. 3';
objQuestion.textbook = 0;
objQuestion.chapter = 14;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '14A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Many annuity contract owners select annuitized payout options. One such payout option provides payments that continue for the lifetime of the annuitant or for a certain period specified in the contract, whichever is longer. This type of annuitized payout option is known as a</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "straight life annuity";
arrAnsChoices[1] = "joint and survivor life annuity";
arrAnsChoices[2] = "life annuity with period certain";
arrAnsChoices[3] = "life with refund annuity";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473625;
arrAnsIDs[1] = 473626;
arrAnsIDs[2] = 473627;
arrAnsIDs[3] = 473628;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Under a straight life annuity payout option, payments continue for the lifetime of the annuitant and cease at the annuitant’s death. Payments are not guaranteed for a specific period.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Under a joint and survivor life annuity payout option, payments continue for the lifetime of the last surviving annuitant and cease at the death of the last surviving annuitant.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Under a life annuity with period certain, payments continue for the lifetime of the annuitant or for a certain period specified in the contract, whichever is longer. If the annuitant dies before the end of the period certain, the insurer will make payments to a beneficiary for the remainder of the period certain.</p><p class=\"explanations\"><b>Learning Objective: 14A. Explain an insurer’s duties to perform annuity contracts according to the most common annuitized payout options as well as the terms of structured settlement agreements.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A life with refund annuity specifies that, if the annuitant dies before the payee receives payments that total at least the purchase price of the annuity contract, the insurer refunds to the payee or a beneficiary named by the contract owner the difference between the purchase price and the amount that has been paid out.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_170'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_171';
objQuestion.questionID = 117136;
objQuestion.item = 'LOMA_311_PPQ2020_171';
objQuestion.primaryLO = '14A';
objQuestion.textref = 'c. 14, pp. 3-5';
objQuestion.textbook = 0;
objQuestion.chapter = 14;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '14A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Sometimes annuities are purchased as a result of a structured settlement of a civil lawsuit. The following statements are about a typical structured settlement in the United States. Select the answer choice containing the correct statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "The payee who receives payments under a structured settlement is required to be the plaintiff in a civil lawsuit.";
arrAnsChoices[1] = "In the United States, periodic payments received by a payee from a structured settlement usually are not subject to federal income taxation.";
arrAnsChoices[2] = "Structured settlements generally result from a court judgment rather than from out-of-court negotiations between a plaintiff and defendant and their respective attorneys.";
arrAnsChoices[3] = "The payee of a structured settlement that is funded by an annuity contract can sell the annuity contract to another party at any time.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473629;
arrAnsIDs[1] = 473630;
arrAnsIDs[2] = 473631;
arrAnsIDs[3] = 473632;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The payee of a structured settlement can be the plaintiff of the civil action <b>or another person</b>. A structured settlement can require a defendant to make payments to someone other than the person who was directly harmed by the defendant’s actions.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Structured settlements usually result from out-of-court negotiations between a plaintiff and a defendant and their respective attorneys. Only the person specified in the structured settlement agreement as the payee can be named as a payee on periodic payment checks, and periodic payments cannot be accelerated or increased. Because the terms of the settlement agreement are put into a court order, that order must be followed. In the United States, periodic payments received by a payee from a structured settlement usually are not subject to federal income taxation.</p><p class=\"explanations\"><b>Learning Objective: 14A. Explain an insurer’s duties to perform annuity contracts according to the most common annuitized payout options as well as the terms of structured settlement agreements.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Structured settlements usually result from <b>out-of-court negotiations </b>between a plaintiff and defendant and their respective attorneys. After the parties agree on the terms, the settlement agreement is incorporated into the trial court’s judgment.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The payee of an annuity contract that funds a structured settlement is not the owner of the annuity, and he <b>cannot </b>sell the annuity contract to another party. However, he can assign the periodic payments he receives from a structured settlement to another party, if he obtains a court order approving the transaction.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_171'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_172';
objQuestion.questionID = 117137;
objQuestion.item = 'LOMA_311_PPQ2020_172';
objQuestion.primaryLO = '14A';
objQuestion.textref = 'c. 14, pp. 4-5';
objQuestion.textbook = 0;
objQuestion.chapter = 14;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '14A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Marietta Corporation, the defendant in a civil lawsuit, entered into a structured settlement agreement with Will Gaul, the plaintiff, in which Marietta agreed to make periodic payments to Mr.&nbsp;Gaul for his lifetime. Immediately after entering into the structured settlement agreement, Marietta assigned its payment obligations to a third-party assignment company, the Lloyd Group. Lloyd then purchased an annuity from the Hoffman Life Insurance Company to fund the periodic payments. In this situation, the party that owns the annuity contract is</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "the Marietta Corporation";
arrAnsChoices[1] = "Mr.&nbsp;Gaul";
arrAnsChoices[2] = "the Lloyd Group";
arrAnsChoices[3] = "the Hoffman Life Insurance Company";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473633;
arrAnsIDs[1] = 473634;
arrAnsIDs[2] = 473635;
arrAnsIDs[3] = 473636;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Marietta assigned its payment obligations to Lloyd, and Lloyd subsequently purchased an annuity to fund the payments. Therefore, Marietta is <b>not </b>the owner of the annuity.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Mr.&nbsp;Gaul is the <b>payee</b>, not the owner, of the annuity contract.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">When the defendant of a civil lawsuit assigns payment obligations to a third-party assignment company, the assignment company—often referred to as a factoring company—becomes the owner of the annuity. A third-party assignment company typically purchases an annuity contract from an affiliated life insurance company to fund the periodic payments. Structured settlement agreements typically require the contract owner to irrevocably assign the periodic payments to the payee specified in the structured settlement agreement.</p><p class=\"explanations\"><b>Learning Objective: 14A. Explain an insurer’s duties to perform annuity contracts according to the most common annuitized payout options as well as the terms of structured settlement agreements.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">In this situation, Hoffman is the <b>issuer </b>of the annuity contract, not the owner.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_172'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_173';
objQuestion.questionID = 117138;
objQuestion.item = 'LOMA_311_PPQ2020_173';
objQuestion.primaryLO = '14B';
objQuestion.textref = 'c. 14, p. 7';
objQuestion.textbook = 0;
objQuestion.chapter = 14;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '14B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">After determining that a life insurance claim is valid, an insurer identifies the proper payee of the policy proceeds. If the insurer pays policy proceeds to a payee who is not entitled to them, and the proper payee later asserts a valid claim to the proceeds, the insurer (<b>will / will not</b>) be obligated to pay the claim again. If an insurer pays policy proceeds to the wrong payee, the insurer (<b>can / cannot</b>) seek to recover from the wrong payee the amount paid in error.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "will / can";
arrAnsChoices[1] = "will / cannot";
arrAnsChoices[2] = "will not / can";
arrAnsChoices[3] = "will not / cannot";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473637;
arrAnsIDs[1] = 473638;
arrAnsIDs[2] = 473639;
arrAnsIDs[3] = 473640;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">If an insurer pays policy proceeds to a payee who is not entitled to them, the proper payee can later assert a valid claim to the proceeds, and the insurer will be obligated to pay the claim again. In this case, the insurer can seek to recover from the wrong payee the amount paid in error. However, pursuing repayment can be difficult and costly for an insurer.</p><p class=\"explanations\"><b>Learning Objective: 14B. List the tasks that make up the standard claim procedures insurers follow when processing life insurance claims.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that the insurer will be obligated to pay the claim again if the proper payee asserts a valid claim to the proceeds. However, in this case, the insurer <b>can </b>seek to recover from the wrong payee the amount paid in error.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is correct to say that, if an insurer pays policy proceeds to the wrong payee, the insurer can seek to recover from the wrong payee the amount paid in error. However, if the proper payee asserts a valid claim to the proceeds, the insurer <b>will </b>be obligated to pay the claim again.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">If the proper payee asserts a valid claim to the policy proceeds, the insurer <b>will </b>be obligated to pay the claim again. Also, if an insurer pays policy proceeds to the wrong payee, the insurer <b>can </b>seek to recover from the wrong payee the amount paid in error.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_173'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_174';
objQuestion.questionID = 117139;
objQuestion.item = 'LOMA_311_PPQ2020_174';
objQuestion.primaryLO = '14C';
objQuestion.textref = 'c. 14, p. 8';
objQuestion.textbook = 0;
objQuestion.chapter = 14;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '14C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Jean Bishop was the policyowner-insured of a life insurance policy that named her husband, Clay, as the primary beneficiary, and her daughter, Melody, as the contingent beneficiary. The policy did not contain a short-term survivorship provision, and Jean resided in a state that has a typical simultaneous death act. While the policy was in force, Jean and Clay died in an automobile accident, and it was impossible to determine who died first. In this situation, the proceeds of Jean’s policy most likely were payable to</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Jean’s estate";
arrAnsChoices[1] = "Clay’s estate";
arrAnsChoices[2] = "Melody";
arrAnsChoices[3] = "no one";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473641;
arrAnsIDs[1] = 473642;
arrAnsIDs[2] = 473643;
arrAnsIDs[3] = 473644;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A simultaneous death act states that, if the insured and the beneficiary die at the same time or under circumstances that make it impossible to determine which of them died first, the insured is deemed to have survived the beneficiary, and the policy proceeds are payable as though the insured outlived the beneficiary, unless the policy provides otherwise. In this situation, the simultaneous death act most likely would provide that Jean outlived Clay, but her estate would <b>not </b>be entitled to the policy proceeds.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A simultaneous death act states that, if the insured and the beneficiary die at the same time or under circumstances that make it impossible to determine which of them died first, the insured is deemed to have survived the beneficiary, and the policy proceeds are payable as though the insured outlived the beneficiary, unless the policy provides otherwise. In this situation, the simultaneous death act most likely would provide that Clay predeceased Jean; therefore, his estate would <b>not </b>be entitled to the policy proceeds.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A simultaneous death act states that, if the insured and the beneficiary die at the same time or under circumstances that make it impossible to determine which of them died first, the insured is deemed to have survived the beneficiary, and the policy proceeds are payable as though the insured outlived the beneficiary, unless the policy provides otherwise. In this situation, the simultaneous death act most likely would provide that Jean survived Clay, and the policy proceeds are payable to Melody, the contingent beneficiary.</p><p class=\"explanations\"><b>Learning Objective: 14C. Describe how insurers determine the proper payee of life insurance policy proceeds in situations involving conflicting claimants, common disasters, and short-term survivorship.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The policy proceeds would be payable in this situation.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_174'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_175';
objQuestion.questionID = 117140;
objQuestion.item = 'LOMA_311_PPQ2020_175';
objQuestion.primaryLO = '14D';
objQuestion.textref = 'c. 14, pp. 9-10';
objQuestion.textbook = 0;
objQuestion.chapter = 14;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '14D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Ann Laskaw, the insured under a $200,000 life insurance policy, died while the policy was in force, and the policy beneficiary submitted a claim for the policy proceeds. The insurer determined that the claim was valid and that Ms.&nbsp;Laskaw’s death was the result of an accident. The following amounts pertained to the policy at the time of Ms.&nbsp;Laskaw’s death:</p><ul class=\"examul\"><li>$100,000 accidental death benefit</li><li>$250 premium due and unpaid</li><li>$500 in accumulated policy dividends</li><li>$5,000 unpaid policy loan</li><li>$500 in accrued policy loan interest</li></ul><p class=\"stem\">In this situation, the total amount of policy proceeds payable is equal to</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "$106,250";
arrAnsChoices[1] = "$294,750";
arrAnsChoices[2] = "$296,250";
arrAnsChoices[3] = "$306,250";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473645;
arrAnsIDs[1] = 473646;
arrAnsIDs[2] = 473647;
arrAnsIDs[3] = 473648;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">When determining the amount of policy proceeds payable, an insurer typically adds the following amounts to a policy’s face amount: accidental death benefits and accumulated policy dividends. The insurer subtracts the following amounts to obtain the total amount payable: premiums due and unpaid at the time of the insured’s death, unpaid policy loans, and accrued policy loan interest.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">When determining the amount of policy proceeds payable, an insurer typically adds the following amounts to a policy’s face amount: accidental death benefits and accumulated policy dividends. The insurer subtracts the following amounts to obtain the total amount payable: premiums due and unpaid at the time of the insured’s death, unpaid policy loans, and accrued policy loan interest.</p><p class=\"explanations\"><b>Learning Objective: 14D. Calculate the amount of policy proceeds payable under a life insurance policy.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">When determining the amount of policy proceeds payable, an insurer typically adds the following amounts to a policy’s face amount: accidental death benefits and accumulated policy dividends. The insurer subtracts the following amounts to obtain the total amount payable: premiums due and unpaid at the time of the insured’s death, unpaid policy loans, and accrued policy loan interest.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">When determining the amount of policy proceeds payable, an insurer typically adds the following amounts to a policy’s face amount: accidental death benefits and accumulated policy dividends. The insurer subtracts the following amounts to obtain the total amount payable: premiums due and unpaid at the time of the insured’s death, unpaid policy loans, and accrued policy loan interest.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_175'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_176';
objQuestion.questionID = 117141;
objQuestion.item = 'LOMA_311_PPQ2020_176';
objQuestion.primaryLO = '14E';
objQuestion.textref = 'c. 14, pp. 13-14';
objQuestion.textbook = 0;
objQuestion.chapter = 14;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '14E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about the typical suicide exclusion provision included in most life insurance policies. Select the answer choice containing the correct statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "In the United States, laws in most states limit the length of the suicide exclusion period to a maximum of five years.";
arrAnsChoices[1] = "If the facts of a person’s death can be interpreted in more than one way, a court usually will presume that the insured did not take his own life.";
arrAnsChoices[2] = "When a claimant sues an insurer that has denied a claim based on the suicide exclusion provision, the claimant has the burden of proving that the insured did not commit suicide.";
arrAnsChoices[3] = "Laws in most states specify that a person must have been insane at the time of the act for a death to be considered a suicide.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473649;
arrAnsIDs[1] = 473650;
arrAnsIDs[2] = 473651;
arrAnsIDs[3] = 473652;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Laws in most states limit the length of the suicide exclusion period to a specified maximum, usually <b>two </b>years. After the expiration of the suicide exclusion period, the death of the insured as a result of suicide is covered by the policy and the insurer must pay the full policy benefit.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Most jurisdictions have developed a strong presumption against suicide—that is, the law presumes that a person’s death did not result from suicide. The insurer has the burden of proving that the insured’s death was caused by suicide during the policy’s suicide exclusion period.</p><p class=\"explanations\"><b>Learning Objective: 14E. Explain how insurers handle life insurance claim situations that may involve fraud as well as those that involve policy exclusions, disappearance of the insured, disqualification of the beneficiary, and accidental death benefits.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">When an insurer refuses to pay a policy’s face amount based on the suicide exclusion provision and the claimant later sues the insurer, the <b>insurer </b>has the burden of proving that the insured’s death was caused by suicide during the policy’s suicide exclusion period.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">According to laws in most states, suicide requires that the person must have intended to kill herself. A person who is insane <b>cannot </b>form the necessary intent to commit suicide. Therefore, the typical suicide exclusion provision states that the insurer is not liable to pay the policy proceeds if the insured died during the suicide exclusion period as a result of suicide or self-inflicted injury, while sane or insane.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_176'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_177';
objQuestion.questionID = 117142;
objQuestion.item = 'LOMA_311_PPQ2020_177';
objQuestion.primaryLO = '14E';
objQuestion.textref = 'c. 14, pp. 14-15';
objQuestion.textbook = 0;
objQuestion.chapter = 14;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '14E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Lily Hewitt was the insured of a life insurance policy that named Allen Dean as the policy beneficiary. On September 8, 2012, Ms.&nbsp;Hewitt mysteriously disappeared and was not heard from again. On September 15, 2019, Mr.&nbsp;Dean asked a court to declare Ms.&nbsp;Hewitt dead. The court issued an order on October 3, 2019, declaring Ms.&nbsp;Hewitt to be dead. The court order did not state the day on which Ms.&nbsp;Hewitt was presumed to have died. With regard to the date on which Ms.&nbsp;Hewitt was presumed to have died and to the date until which Ms.&nbsp;Hewitt’s policy must remain in force in order for proceeds to be payable, it is correct to say that Ms.&nbsp;Hewitt’s presumed date of death is</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "September 8, 2012, and the policy must have remained in force only until September 8, 2012, in order for the policy proceeds to be payable";
arrAnsChoices[1] = "September 8, 2012, but the policy must have remained in force until October 3, 2019, in order for the policy proceeds to be payable";
arrAnsChoices[2] = "October 3, 2019, but the policy must have remained in force only until September 8, 2012, in order for the policy proceeds to be payable";
arrAnsChoices[3] = "October 3, 2019, and the policy must have remained in force until October 3, 2019, in order for the policy proceeds to be payable";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473653;
arrAnsIDs[1] = 473654;
arrAnsIDs[2] = 473655;
arrAnsIDs[3] = 473656;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">When a court declares an insured to be dead but does not specify the date of death for the insured, the insured is presumed to have died on the date of the <b>court order</b>. When an insured disappears, in order for policy proceeds to be payable, the contract owner or other interested party must keep the policy in force until the court issues an order<b> </b>declaring the insured dead.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that the policy must have remained in force until the court order was issued on October 3, 2019, in order for the policy proceeds to be payable. However, when a court declares an insured to be dead but does not specify the date of death for the insured, the insured is presumed to have died on the date of the <b>court order</b>, not on the date of the insured’s disappearance.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that Ms.&nbsp;Hewitt’s presumed date of death is October 3, 2019 because, when the court order does not state a date of death, the person is presumed to have died on the date of the court order. However, when an insured disappears, the contract owner or other interested party must keep the policy in force until the court issues an order declaring the insured dead.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">When a court declares an insured to be dead but does not specify the date of death for the insured, the insured is presumed to have died on the date of the court order. Therefore, in this situation, Ms.&nbsp;Hewitt’s presumed date of death is October 3, 2019. The contract owner or other interested party must keep the policy in force until the court issues an order declaring the insured dead. Therefore, premiums must be paid or the policy must be continued under a nonforfeiture option such as the extended term insurance option. If the policy lapses for nonpayment of premiums before the date of the court order, the insurer is not liable to pay the policy proceeds.</p><p class=\"explanations\"><b>Learning Objective: 14E. Explain how insurers handle life insurance claim situations that may involve fraud as well as those that involve policy exclusions, disappearance of the insured, disqualification of the beneficiary, and accidental death benefits.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_177'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_178';
objQuestion.questionID = 117143;
objQuestion.item = 'LOMA_311_PPQ2020_178';
objQuestion.primaryLO = '14E';
objQuestion.textref = 'c. 14, pp. 15-16';
objQuestion.textbook = 0;
objQuestion.chapter = 14;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '14E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Chris Winkler, a United States resident, purchased an insurance policy on the life of Alexa Cole, his business partner. Mr.&nbsp;Winkler named himself as the primary beneficiary of the policy and another business partner, Melissa Holland as the contingent beneficiary. Six months after he purchased the policy, Mr.&nbsp;Winkler killed Ms.&nbsp;Cole and was convicted in a criminal proceeding of murdering her. The insurer proved that Mr.&nbsp;Winkler purchased the insurance policy with the intent of causing Ms.&nbsp;Cole’s death. In this situation, the proceeds of the policy most likely are payable to</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Mr.&nbsp;Winkler";
arrAnsChoices[1] = "Ms.&nbsp;Cole’s estate";
arrAnsChoices[2] = "Ms.&nbsp;Holland";
arrAnsChoices[3] = "no one, but the insurer must return all policy premiums plus any interest, less any outstanding policy loans and loan interest, to Mr.&nbsp;Winkler";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473657;
arrAnsIDs[1] = 473658;
arrAnsIDs[2] = 473659;
arrAnsIDs[3] = 473660;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">In most states, a beneficiary who is convicted in a criminal proceeding of murdering the insured is disqualified from receiving the policy proceeds. Because Mr.&nbsp;Winkler was convicted of murdering Ms.&nbsp;Cole, he is disqualified from receiving policy proceeds.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">If an insurer proves that a beneficiary obtained a life insurance contract with the intent of causing the insured’s death, the contract is void from its inception. An insurer is not liable to pay the policy proceeds to an insured’s estate when the policy is considered to be void.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">If an insurer proves that a beneficiary obtained a life insurance contract with the intent of causing the insured’s death, the contract is void from its inception. An insurer is not liable to pay the policy proceeds to a contingent beneficiary when the policy is considered to be void. In this situation, Ms.&nbsp;Holland would have received the policy proceeds only if the insurer had been unable to prove that Mr.&nbsp;Winkler purchased the policy with the intent of killing Ms.&nbsp;Cole.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">If an insurer proves that a beneficiary obtained a life insurance contract with the intent of causing the insured’s death, the contract is void from its inception. Because the contract is not valid, the insurer is not liable to pay policy proceeds and is responsible only for returning policy premiums—plus any interest, less any outstanding policy loans along with unpaid interest on those loans—to the policyowner.</p><p class=\"explanations\"><b>Learning Objective: 14E. Explain how insurers handle life insurance claim situations that may involve fraud as well as those that involve policy exclusions, disappearance of the insured, disqualification of the beneficiary, and accidental death benefits.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_178'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_179';
objQuestion.questionID = 117144;
objQuestion.item = 'LOMA_311_PPQ2020_179';
objQuestion.primaryLO = '14E';
objQuestion.textref = 'c. 14, pp. 16-17';
objQuestion.textbook = 0;
objQuestion.chapter = 14;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '14E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statement(s) can correctly be made about accidental death benefits:</p><ol type=\"A\" class=\"combo\"><li>When a claim is made for accidental death benefits, the insurer usually requires the claimant to submit information in addition to a death certificate to show proof of the claim.</li><li>When a claimant sues an insurer over the denial of accidental death benefits, and the cause of death was not excluded from coverage, the claimant has the burden of proving that the insured’s death was caused by an accident.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473661;
arrAnsIDs[1] = 473662;
arrAnsIDs[2] = 473663;
arrAnsIDs[3] = 473664;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Both statements are correct. An insurer may require a claimant to provide an autopsy report in addition to a death certificate in order to determine whether the insured’s death was accidental as defined by the terms of the life insurance contract. The claimant has the burden of proving that the insured’s death was caused by an accident, which is a question of fact.</p><p class=\"explanations\"><b>Learning Objective: 14E. Explain how insurers handle life insurance claim situations that may involve fraud as well as those that involve policy exclusions, disappearance of the insured, disqualification of the beneficiary, and accidental death benefits.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct. However, Statement B is also correct.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is correct. However, Statement A is also correct.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_179'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_311_PQ_180';
objQuestion.questionID = 117145;
objQuestion.item = 'LOMA_311_PPQ2020_180';
objQuestion.primaryLO = '14F';
objQuestion.textref = 'c. 14, p. 19';
objQuestion.textbook = 0;
objQuestion.chapter = 14;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '14F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Rick Connell purchased an insurance policy on his life from the Robinson Insurance Company, which is domiciled in State N. Mr.&nbsp;Connell paid the initial premium at the time of application, and the policy was delivered to his residence in State M. The policy did not contain a choice of laws provision. Mr.&nbsp;Connell later moved to State O, where he died while the policy was still in force. The policy beneficiary, a resident of State P, submitted a claim for the policy proceeds, but Robinson denied the claim. The beneficiary subsequently filed a lawsuit against Robinson for breach of the insurance contract. According to conflict of laws rules, the substantive laws that apply to the issues in this lawsuit are the laws of</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "State M";
arrAnsChoices[1] = "State N";
arrAnsChoices[2] = "State O";
arrAnsChoices[3] = "State P";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 473665;
arrAnsIDs[1] = 473666;
arrAnsIDs[2] = 473667;
arrAnsIDs[3] = 473668;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">When an insurance contract does not contain a choice of laws provision, the general rule of contract law provides that any question concerning the validity of the contract or the interpretation of any provision of the contract is to be determined in accordance with the law of the state in which the contract is made. As a rule, a contract is made in the state where the last act necessary to complete the contract occurs. A life insurance contract typically is considered made in the state in which the policy is delivered or the initial premium is paid, whichever occurs later. If the contract contains a choice of laws provision, then the courts typically will enforce the contract provision.</p><p class=\"explanations\"><b>Learning Objective: 14F. Describe how insurers can settle claim disputes through compromise settlements, and explain how conflict of laws rules apply in civil actions involving life insurance policies.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">When an insurance contract does not contain a choice of laws provision, the general rule of contract law provides that any question concerning the validity of the contract or the interpretation of any provision of the contract is to be determined in accordance with the law of the state in which the contract is made. As a rule, a contract is made in the state where the last act necessary to complete the contract occurs. A life insurance contract typically is considered made in the state in which the policy is delivered or the initial premium is paid, whichever occurs later.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">When an insurance contract does not contain a choice of laws provision, the general rule of contract law provides that any question concerning the validity of the contract or the interpretation of any provision of the contract is to be determined in accordance with the law of the state in which the contract is made. As a rule, a contract is made in the state where the last act necessary to complete the contract occurs. A life insurance contract typically is considered made in the state in which the policy is delivered or the initial premium is paid, whichever occurs later.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">When an insurance contract does not contain a choice of laws provision, the general rule of contract law provides that any question concerning the validity of the contract or the interpretation of any provision of the contract is to be determined in accordance with the law of the state in which the contract is made. As a rule, a contract is made in the state where the last act necessary to complete the contract occurs. A life insurance contract typically is considered made in the state in which the policy is delivered or the initial premium is paid, whichever occurs later.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_311_PQ_180'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['14A'] = "14A. Explain an insurer’s duties to perform annuity contracts according to the most common annuitized payout options as well as the terms of structured settlement agreements.";
arrlotext['14B'] = "14B. List the tasks that make up the standard claim procedures insurers follow when processing life insurance claims.";
arrlotext['14C'] = "14C. Describe how insurers determine the proper payee of life insurance policy proceeds in situations involving conflicting claimants, common disasters, and short-term survivorship.";
arrlotext['14D'] = "14D. Calculate the amount of policy proceeds payable under a life insurance policy.";
arrlotext['14E'] = "14E. Explain how insurers handle life insurance claim situations that may involve fraud as well as those that involve policy exclusions, disappearance of the insured, disqualification of the beneficiary, and accidental death benefits.";
arrlotext['14F'] = "14F. Describe how insurers can settle claim disputes through compromise settlements, and explain how conflict of laws rules apply in civil actions involving life insurance policies.";
