var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2019';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 335 Practice Questions, Chapter 3";
var coursename = 'LOMA 335';
var modulenumber = 0;
var title = "LOMA_335_PPQ2019_0_3";
var intNumPools = 1;
var numQ = 18;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Operational Excellence for Insurance Professionals (2019)";
arrNumChap[0] = 1;
var thisChap = '3';

objPool = new Object(); 
objPool.intSelectCount = 18;
objPool.formID = 2062;
objPool.formName = 'PPQ2019_0_3';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_335_PQ_017';
arrPoolQuestions[1] = 'LOMA_335_PQ_018';
arrPoolQuestions[2] = 'LOMA_335_PQ_019';
arrPoolQuestions[3] = 'LOMA_335_PQ_020';
arrPoolQuestions[4] = 'LOMA_335_PQ_021';
arrPoolQuestions[5] = 'LOMA_335_PQ_022';
arrPoolQuestions[6] = 'LOMA_335_PQ_023';
arrPoolQuestions[7] = 'LOMA_335_PQ_024';
arrPoolQuestions[8] = 'LOMA_335_PQ_025';
arrPoolQuestions[9] = 'LOMA_335_PQ_026';
arrPoolQuestions[10] = 'LOMA_335_PQ_027';
arrPoolQuestions[11] = 'LOMA_335_PQ_028';
arrPoolQuestions[12] = 'LOMA_335_PQ_029';
arrPoolQuestions[13] = 'LOMA_335_PQ_030';
arrPoolQuestions[14] = 'LOMA_335_PQ_031';
arrPoolQuestions[15] = 'LOMA_335_PQ_032';
arrPoolQuestions[16] = 'LOMA_335_PQ_033';
arrPoolQuestions[17] = 'LOMA_335_PQ_034';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_017';
objQuestion.questionID = 109305;
objQuestion.item = 'LOMA_335_PPQ2019_017';
objQuestion.primaryLO = '3A';
objQuestion.textref = 'c. 3, p. 2';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '3A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statement(s) can correctly be made about the corporate culture and the leadership roles within organizations:</p><ol type=\"A\" class=\"combo\"><li>The corporate culture can promote or discourage certain behaviors in the workplace and directly influence the success or failure of corporate strategies.</li><li>Generally, informal leadership refers to a person’s ability to influence the behavior of others through the authority conveyed on the person by the company.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441749;
arrAnsIDs[1] = 441750;
arrAnsIDs[2] = 441751;
arrAnsIDs[3] = 441752;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct. A corporate culture comprises the attitudes, values, perceptions, beliefs, and experiences shared by a company’s employees and instilled in new employees when they join the company. An insurance company needs effective leaders who can create a corporate culture that aligns with corporate strategies and motivates employees. </p><p class=\"explanations\">Statement B is incorrect because a person’s ability to influence the behavior of others through the formal authority conveyed on that person by the company is known as <b>formal </b>leadership. Informal leadership is the ability to influence the behavior of others by means other than the formal authority that an organization has conferred.</p><p class=\"explanations\"><b>Learning Objective: 3A. Explain the importance of trust in effective leadership and ways that leaders build trust and use power in the workplace.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is incorrect. Formal<b> </b>leadership refers to a person’s ability to influence the behaviors of others through the formal authority conveyed on that person by the company. Informal leadership is the ability to influence the behaviors of others by means other than the formal authority that an organization has conferred.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_017'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_018';
objQuestion.questionID = 109306;
objQuestion.item = 'LOMA_335_PPQ2019_018';
objQuestion.primaryLO = '3A';
objQuestion.textref = 'c. 3, p. 3';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '3A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Trust refers to a belief in the integrity, character, or ability of others. Within this definition, <i>ability </i>means that an individual</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "acts in ways that are consistent with his beliefs";
arrAnsChoices[1] = "cares about and supports other people";
arrAnsChoices[2] = "possesses the technical skills or knowledge to get a job done";
arrAnsChoices[3] = "possesses the force that gives purpose and direction to his behavior";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441753;
arrAnsIDs[1] = 441754;
arrAnsIDs[2] = 441755;
arrAnsIDs[3] = 441756;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Trust refers to a belief in the integrity, character, or ability of others. Within this definition, <b>integrity </b>means that an individual acts in ways that are consistent with their beliefs.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Trust refers to a belief in the integrity, character, or ability of others. Within this definition, <b>character</b> refers to an individual’s<b> </b>care and support for other people.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Trust refers to a belief in the integrity, character, or ability of others. Within this definition, integrity means that an individual acts in ways that are consistent with his beliefs; character refers to an individual’s care and support for other people; and ability refers to an individual’s possession of the technical skills or knowledge to get the job done.</p><p class=\"explanations\"><b>Learning Objective: 3A. Explain the importance of trust in effective leadership and ways that leaders build trust and use power in the workplace.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\"><b>Motivation</b> is the force that gives purpose and direction to an individual’s behavior.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_018'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_019';
objQuestion.questionID = 109307;
objQuestion.item = 'LOMA_335_PPQ2019_019';
objQuestion.primaryLO = '3A';
objQuestion.textref = 'c. 3, pp. 5-6';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '3A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Consider the types of organizational power exercised by the following individuals:</p><ul class=\"examul\"><li>Linda Andre influences the behavior of her employees because they respect and admire her, and also because they desire her approval.</li><li>John Davenport uses threats and various types of punishment to maintain power over his subordinates.</li></ul><p class=\"stem\">Select the response that correctly identifies the types of power that Ms.&nbsp;Andre and Mr.&nbsp;Davenport possess based on these descriptions.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[-1] = "<u>Ms.&nbsp;Andre</u></div><div class=\"anshead\"><u>Mr.&nbsp;Davenport</u>";
arrAnsChoices[0] = "referent power</div><div class=\"anscell\" onclick=\"recordAns(1);\">expert power";
arrAnsChoices[1] = "referent power</div><div class=\"anscell\" onclick=\"recordAns(2);\">coercive power";
arrAnsChoices[2] = "reward power</div><div class=\"anscell\" onclick=\"recordAns(3);\">expert power";
arrAnsChoices[3] = "reward power</div><div class=\"anscell\" onclick=\"recordAns(4);\">coercive power";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441758;
arrAnsIDs[1] = 441759;
arrAnsIDs[2] = 441760;
arrAnsIDs[3] = 441761;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is correct to say that Ms.&nbsp;Andre possesses referent power; however, Mr.&nbsp;Davenport does <b>not </b>possess expert power in this situation. Expert power is power that results from a person’s skills, knowledge, or expertise.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Ms.&nbsp;Andre has referent power, which results from the loyalty, respect, or admiration of others. Referent power can result from a person’s own qualities that inspire loyalty and respect, or from that person’s connections to another. For example, having a close relationship with the company’s president might give a person referent power. Mr.&nbsp;Davenport has coercive power, which results from a person’s ability to discipline others for poor performance. The use of coercive power tends to result in decreased employee satisfaction with the organization.</p><p class=\"explanations\"><b>Learning Objective: 3A. Explain the importance of trust in effective leadership and ways that leaders build trust and use power in the workplace.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Reward power results from a person’s ability to allocate incentives to others based on behaviors or performance. Ms.&nbsp;Andre does <b>not </b>possess reward power in this situation. Expert power results from a person’s skills, knowledge, or expertise. Mr.&nbsp;Davenport does <b>not </b>possess expert power in this situation.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is correct to say that Mr.&nbsp;Davenport possesses coercive power; however, Ms.&nbsp;Andre does <b>not </b>possess reward power in this situation. Reward power arises from a person’s ability to allocate incentives to others based on behaviors or performance.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_019'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_020';
objQuestion.questionID = 109308;
objQuestion.item = 'LOMA_335_PPQ2019_020';
objQuestion.primaryLO = '3B';
objQuestion.textref = 'c. 3, p. 8';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '3B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">When Eric Sack wanted to persuade his manager to change a departmental policy, Mr.&nbsp;Sack used ingratiating tactics in an attempt to influence his manager’s decision. This information indicates that Mr.&nbsp;Sack most likely tried to influence his manager by</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "targeting his manager’s emotions, values, or ideals";
arrAnsChoices[1] = "presenting a detailed plan and logical information to convince the manager";
arrAnsChoices[2] = "offering to complete extra work in return for his manager’s compliance with his request";
arrAnsChoices[3] = "using flattery, praise, or humbling behavior";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441762;
arrAnsIDs[1] = 441763;
arrAnsIDs[2] = 441764;
arrAnsIDs[3] = 441765;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Targeting the emotions, values, or ideals of others to gain support for an alternative is a description of <b>inspirational appeals</b>, not ingratiating tactics.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Using logic, reason, education, or a detailed plan to convince others that a certain point of view is best is a description of <b>rational persuasion</b>, not ingratiating tactics.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Using the rule of reciprocation—something is given with the expectation that something will be received in return—is a description of <b>exchange tactics</b>, not ingratiating tactics.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Effective leaders develop certain tactics for influencing others to act in specified ways, and such leaders also recognize that certain tactics work better in some situations than others. Overall, the most effective influence tactics tend to be rational persuasion and consultation.</p><p class=\"explanations\"><b>Learning Objective: 3B. Describe the types of influence tactics leaders use in the workplace.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_020'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_021';
objQuestion.questionID = 109309;
objQuestion.item = 'LOMA_335_PPQ2019_021';
objQuestion.primaryLO = '3C';
objQuestion.textref = 'c. 3, p. 11';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '3C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = 1;
objQuestion.strStem = "<p class=\"stem\">Behavior modification generally seeks to manage the antecedents or consequences of employee behavior. With regard to these situations it is correct to say that Ms.&nbsp;Chen acted to manage <i>antecedents</i> in</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "both Situation 1 and Situation 2";
arrAnsChoices[1] = "Situation 1 only";
arrAnsChoices[2] = "Situation 2 only";
arrAnsChoices[3] = "neither Situation 1 nor Situation 2";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441766;
arrAnsIDs[1] = 441767;
arrAnsIDs[2] = 441768;
arrAnsIDs[3] = 441769;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Ms.&nbsp;Chen managed <b>consequences </b>rather than antecedents in at least one of these situations.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">An antecedent is an environmental cue that prompts a person to act in a particular manner. Antecedents come first; behavior follows. Because Ms.&nbsp;Chen praised the employee after observing the behavior, Situation 1 is an example of managing <b>consequences</b> rather than antecedents.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">An antecedent is an environmental cue that prompts a person to act in a particular manner. Antecedents come first; behavior follows. A manager is managing <b>consequences</b> rather than antecedents when she ignored a behavior.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">An antecedent is an environmental cue that prompts a person to act in a particular manner. Antecedents come first; behavior follows. Because Ms.&nbsp;Chen praised the employee after observing the behavior, Situation 1 is an example of managing <b>consequences</b> rather than antecedents. In Situation 2, Ms.&nbsp;Chen managed <b>consequences</b> rather than antecedents when she ignored a behavior.</p><p class=\"explanations\"><b>Learning Objective: 3C. Describe how individuals can modify their own behavior and that of others by using the eight practices of effective leaders and managing antecedents and consequences in the workplace.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_021'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_022';
objQuestion.questionID = 109310;
objQuestion.item = 'LOMA_335_PPQ2019_022';
objQuestion.primaryLO = '3C';
objQuestion.textref = 'c. 3, p. 12';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '3C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = 1;
objQuestion.strStem = "<p class=\"stem\">With regard to the strategy of behavior modification Ms.&nbsp;Chen used in each situation and whether it was used to encourage or discourage a behavior, it is correct to say that Ms.&nbsp;Chen used</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "negative reinforcement in Situation 1 to encourage a specific behavior";
arrAnsChoices[1] = "positive reinforcement in Situation 1 to discourage a specific behavior";
arrAnsChoices[2] = "extinction in Situation 2 to discourage a specific behavior";
arrAnsChoices[3] = "punishment in Situation 2 to discourage a specific behavior";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441770;
arrAnsIDs[1] = 441771;
arrAnsIDs[2] = 441772;
arrAnsIDs[3] = 441773;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is correct to say that Ms.&nbsp;Chen encouraged a specific behavior in Situation 1; however, she did <b>not </b>use negative reinforcement. Negative reinforcement is the process of encouraging a specific behavior by immediately withdrawing or terminating something that an individual finds unpleasant or negative. In Situation 1, Ms.&nbsp;Chen provided something the individual would find pleasing.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is correct to say that Ms.&nbsp;Chen used positive reinforcement in Situation 1 by following a specific behavior with a consequence that the individual finds pleasing or positive. However, positive reinforcement is used to <b>encourage </b>a specific behavior.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Strategies used to discourage a specific behavior include extinction (ignoring a specific behavior) and punishment (presenting an undesirable consequence or removing something desirable).</p><p class=\"explanations\">Strategies used to encourage a specific behavior include positive reinforcement (immediately following the behavior with a consequence that the individual finds pleasing or positive) and negative reinforcement (withdrawing or termination something that an individual finds unpleasant or negative).</p><p class=\"explanations\"><b>Learning Objective: 3C. Describe how individuals can modify their own behavior and that of others by using the eight practices of effective leaders and managing antecedents and consequences in the workplace.</b>Click here to enter text.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is correct to say that Ms.&nbsp;Chen discouraged a specific behavior in Situation 2; however, she did <b>not </b>use punishment. Punishment involves presenting an undesirable consequence or removing something desirable. In Situation 2, Ms.&nbsp;Chen ignored the behavior.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_022'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_023';
objQuestion.questionID = 109311;
objQuestion.item = 'LOMA_335_PPQ2019_023';
objQuestion.primaryLO = '3D';
objQuestion.textref = 'c. 3, p. 14';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '3D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Self-determination theory (SDT) is a motivation theory that describes the effects of intrinsic rewards and extrinsic rewards. SDT also classifies motivation as autonomous motivation or controlled motivation. According to SDT, autonomous motivation arises primarily from <b>(intrinsic rewards</b> / <b>extrinsic rewards)</b>. When autonomous motivation is involved, a person typically <b>(is</b> / <b>is not)</b> highly motivated. </p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "intrinsic rewards / is";
arrAnsChoices[1] = "intrinsic rewards / is not ";
arrAnsChoices[2] = "extrinsic rewards / is";
arrAnsChoices[3] = "extrinsic rewards / is not";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441774;
arrAnsIDs[1] = 441775;
arrAnsIDs[2] = 441776;
arrAnsIDs[3] = 441777;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">SDT proposes that people have three basic psychological needs: competence, relatedness, and autonomy. Autonomous motivation arises primarily from intrinsic rewards affiliated with needs for competence, relatedness, and autonomy. When autonomous motivation is involved, a person is highly motivated to engage in an activity. Controlled motivation primarily involves extrinsic rewards. </p><p class=\"explanations\"><b>Learning Objective: 3D. Explain self-determination theory and expectancy theory and describe the role of motivation in work performance.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is correct to say that, according to SDT, autonomous motivation arises primarily from intrinsic rewards; however, when autonomous motivation is involved, a person typically <b>is</b> highly motivated.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is correct to say that, when autonomous motivation is involved, a person typically is highly motivated; however, autonomous motivation arises primarily from <b>intrinsic</b> rewards.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Autonomous motivation arises primarily from <b>intrinsic</b> rewards. Also, when autonomous motivation is involved, a person typically <b>is</b> highly motivated.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_023'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_024';
objQuestion.questionID = 109312;
objQuestion.item = 'LOMA_335_PPQ2019_024';
objQuestion.primaryLO = '3D';
objQuestion.textref = 'c. 3, pp. 14-15';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '3D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about expectancy theory. Three statements are true, and one statement is false. Select the answer choice containing the <B>FALSE </B>statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Expectancy theory states that the strength of an individual’s tendency to act in a certain way depends on the individual’s expectancy that the act will be followed by a given outcome.";
arrAnsChoices[1] = "According to expectancy theory, an individual must believe that his effort will result in a reward.";
arrAnsChoices[2] = "According to expectancy theory, employees must have the skills and knowledge necessary for performance.";
arrAnsChoices[3] = "Expectancy theory states that the reward does not have to be important to the individual.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441778;
arrAnsIDs[1] = 441779;
arrAnsIDs[2] = 441780;
arrAnsIDs[3] = 441781;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">This is a true statement; therefore, it is <b>not</b> the correct response. </p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">This is a true statement; therefore, it is <b>not</b> the correct response. </p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">This is a true statement; therefore, it is <b>not</b> the correct response. </p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">This statement is false; therefore, it is the correct response. The reward <b>must</b> be important to the individual. Expectancy theory suggests that an individual’s motivation depends on effort, performance, and reward. If any of these three components is lacking, an employee is less motivated to perform. </p><p class=\"explanations\"><b>Learning Objective: 3D. Explain self-determination theory and expectancy theory and describe the role of motivation in work performance.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_024'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_025';
objQuestion.questionID = 109313;
objQuestion.item = 'LOMA_335_PPQ2019_025';
objQuestion.primaryLO = '3E';
objQuestion.textref = 'c. 3, pp. 16, 18';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '3E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statement(s) can correctly be made about the performance evaluation methods known as a 360-degree review and management by objectives (MBO):</p><ol type=\"A\" class=\"combo\"><li>Although not appropriate for all positions, a 360-degree review can help avoid bias.</li><li>One advantage of a 360-degree review is that it significantly reduces the amount of time that companies spend on performance evaluation.</li><li>One disadvantage of MBO is that supervisors meet with their employees only once per year—when they communicate the results of the performance evaluation.</li><li>For MBO to be effective, goals must be specific and measurable so that employees know what they must do.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A, B, C, and D";
arrAnsChoices[1] = "A and B only";
arrAnsChoices[2] = "A and D only";
arrAnsChoices[3] = "B and C only";
arrAnsChoices[4] = "D only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441782;
arrAnsIDs[1] = 441783;
arrAnsIDs[2] = 441784;
arrAnsIDs[3] = 441785;
arrAnsIDs[4] = 441786;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct because, in a 360-degree review, opinions about an employee’s performance are solicited from several sources, such as the employee, peers, subordinates, and customers. When multiple ratings are combined, the overall results are much more likely to be accurate.</p><p class=\"explanations\">Statement B is incorrect. The downside to a 360-degree review that it can be <b>time-consuming</b>.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">In a 360-degree review, opinions about an employee’s performance are solicited from several sources, such as the employee, peers, subordinates, and customers. When multiple ratings are combined, the overall results are much more likely to be accurate. The downside to this approach is that it can be time-consuming.</p><p class=\"explanations\">With MBO, the employee and supervisor work together to (1) set clear and attainable goals for the appraisal period and (2) develop a plan for achieving those goals. Ideally, each employee meets with a supervisor regularly during the evaluation period to assess the employee’s progress in achieving goals and to determine if the employee needs any assistance in order to meet the goals. At the end of the evaluation period, typically annually, the employee and supervisor evaluate the employee’s overall success in meeting established goals and set goals for the next evaluation period. A problem with MBO is that an effective MBO program is time-consuming for the supervisor to manage. </p><p class=\"explanations\"><b>Learning Objective: 3E. Describe the performance evaluation process, its role in motivating employees, and problems often encountered during performance evaluation.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Statement B is incorrect. The downside to a 360-degree review is that it can be <b>time-consuming</b>. Statement C is incorrect because, ideally, each employee meets with a supervisor regularly during the evaluation period to assess the employee’s progress in achieving goals and to determine if the employee needs any assistance in order to meet the goals.</p>";
arrAnswerFeedback[4] = "<p class=\"explanations\">Statement D is correct; however, it is not the only correct statement.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_025'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_026';
objQuestion.questionID = 109314;
objQuestion.item = 'LOMA_335_PPQ2019_026';
objQuestion.primaryLO = '3E';
objQuestion.textref = 'c. 3, p. 17';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '3E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Mentoring is a process for developing employee talent over the long term. Mentoring relationships can be formal or informal. In general, <b>(formal / informal)</b> arrangements tend to be more effective. In effective mentoring relationships, the mentor usually <b>(is / is not)</b> the employee’s immediate supervisor.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "formal / is";
arrAnsChoices[1] = "formal / is not";
arrAnsChoices[2] = "informal / is";
arrAnsChoices[3] = "informal / is not";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441787;
arrAnsIDs[1] = 441788;
arrAnsIDs[2] = 441789;
arrAnsIDs[3] = 441790;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Formal mentoring—a mentoring arrangement officially endorsed by the organization—is <b>not</b> typically the more effective arrangement. Also, in an effective mentoring relationship, the mentor usually is<b> not </b>the employee’s immediate supervisor.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is correct to say that, in an effective mentoring relationship, the mentor usually is not the employee’s immediate supervisor. However, formal mentoring—a mentoring arrangement officially endorsed by the organization—is <b>not</b> typically the more effective arrangement.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is correct to say that informal mentoring—a mentoring arrangement that develops outside of official channels—tends to be more effective than formal mentoring. However, in an effective mentoring relationship, the mentor usually is <b>not </b>the employee’s immediate supervisor.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Formal mentoring is a mentoring arrangement officially endorsed by the organization, whereas informal mentoring refers to a mentoring arrangement that develops outside of official channels. Informal arrangements—in which a senior employee may begin informally mentoring a new employee on his own—tend to be more effective than formal ones.</p><p class=\"explanations\"><b>Learning Objective: 3E. Describe the performance evaluation process, its role in motivating employees, and problems often encountered during performance evaluation.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_026'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_027';
objQuestion.questionID = 109315;
objQuestion.item = 'LOMA_335_PPQ2019_027';
objQuestion.primaryLO = '3E';
objQuestion.textref = 'c. 3, p. 18';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '3E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Sandra Tiller, a manager, feels that punctuality is very important and considers punctual employees to be efficient and hardworking. One of Ms.&nbsp;Tiller’s subordinates, Pam Senter, is at her desk on time every morning and always arrives early for meetings. As a result, Ms.&nbsp;Tiller gave Ms.&nbsp;Senter an excellent performance review, even though Ms.&nbsp;Senter’s performance was not excellent in some other areas. Ms.&nbsp;Tiller’s tendency to think that Ms.&nbsp;Senter’s overall performance is excellent because of her excellence in one area of evaluation demonstrates a cognitive bias known as</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "recency error";
arrAnsChoices[1] = "similarity error";
arrAnsChoices[2] = "the halo effect";
arrAnsChoices[3] = "the fundamental attribution error";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441791;
arrAnsIDs[1] = 441792;
arrAnsIDs[2] = 441793;
arrAnsIDs[3] = 441794;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">In recency error, the evaluator places more emphasis on recent events and minimizes, or even ignores, events that occurred further in the past. When performance evaluations are conducted annually and employees do not receive ongoing performance feedback, recency error can be significant. However, this situation illustrates another type of bias.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">With similarity error, an evaluator gives higher ratings to employees who seem similar in some way to the evaluator. Although it is likely that Ms.&nbsp;Tiller and Ms.&nbsp;Senter are both punctual, this question specifically focuses on the fact that Ms.&nbsp;Senter’s excellent performance in one area affected Ms.&nbsp;Tiller’s evaluation of her overall performance.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The halo effect refers to the tendency to evaluate someone who is excellent in one area of performance as excellent in all areas of evaluation. It also refers to the tendency to give someone a poor evaluation across all areas because of one unfavorable trait or behavior.</p><p class=\"explanations\"><b>Learning Objective: 3E. Describe the performance evaluation process, its role in motivating employees, and problems often encountered during performance evaluation.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The fundamental attribution error, also known as the self-serving bias, is the tendency to take credit for success but assign blame to others for failure. In the context of performance evaluation, fundamental attribution error is a type of <b>employee</b> bias in performance evaluation. However, this question illustrates a bias that occurs in the mind of the <b>evaluator</b>.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_027'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_028';
objQuestion.questionID = 109316;
objQuestion.item = 'LOMA_335_PPQ2019_028';
objQuestion.primaryLO = '3F';
objQuestion.textref = 'c. 3, p. 21';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '3F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Azalea Company adopted a performance-based compensation system. Azalea’s primary goal in designing this system most likely was to link employee compensation to</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "each employee’s attainment of a specified level of proficiency in certain skills";
arrAnsChoices[1] = "the amount of sales an employee makes";
arrAnsChoices[2] = "the achievement of a company-wide goal such as profits or sales";
arrAnsChoices[3] = "a specific example of an employee’s exceptional performance or accomplishment";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441795;
arrAnsIDs[1] = 441796;
arrAnsIDs[2] = 441797;
arrAnsIDs[3] = 441798;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A <b>skills-based pay </b>may reward employees for developing and improving job skills. For example, after attaining a certification or a specified level of proficiency, an employee’s pay is automatically increased.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A <b>sales commission</b> is an amount of money, usually a percentage of the sale amount, paid to someone for selling a product or service.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Performance-based compensation ties employee pay to a company-wide goal such as profits or sales, or perhaps a nonfinancial goal such as improved customer service levels. Companies sometimes use performance-based compensation in conjunction with merit-based compensation so that a portion of an employee’s compensation is merit-based and a portion is performance-based.</p><p class=\"explanations\"><b>Learning Objective: 3F. Identify different types of compensation and explain how companies link performance evaluation to compensation systems to motivate employees.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A <b>spot bonus</b> is a one-time payment made to an employee immediately after the employee performs in an exceptional way on the job or achieves a level of proficiency. Evidence suggests that a spot bonus can be effective in reinforcing a specific behavior or level of performance. </p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_028'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_029';
objQuestion.questionID = 109317;
objQuestion.item = 'LOMA_335_PPQ2019_029';
objQuestion.primaryLO = '3G';
objQuestion.textref = 'c. 3, p. 22';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '3G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">For this question, select the answer choice containing the terms that correctly complete the blanks labeled <B>A</B> and <B>B</B> in the paragraph below.</p><p class=\"stem\">Researchers Hackman and Oldham proposed a job characteristics model that describes five core dimensions of work: skill variety, task identity, task significance, autonomy, and feedback. The core dimension known as <u><b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</b></u> is the degree to which a job requires the completion of a whole and identifiable piece of work. The core dimension known as <u><b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;B&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</b></u> is the degree to which carrying out job activities leads to direct and clear information about an employee’s performance.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[-1] = "<u><b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</b></u></div><div class=\"anshead\"><u><b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;B&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</b></u>";
arrAnsChoices[0] = "skill variety</div><div class=\"anscell\" onclick=\"recordAns(1);\">task significance";
arrAnsChoices[1] = "task identity</div><div class=\"anscell\" onclick=\"recordAns(2);\">feedback";
arrAnsChoices[2] = "task significance</div><div class=\"anscell\" onclick=\"recordAns(3);\">autonomy";
arrAnsChoices[3] = "autonomy</div><div class=\"anscell\" onclick=\"recordAns(4);\">task identity";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441800;
arrAnsIDs[1] = 441801;
arrAnsIDs[2] = 441802;
arrAnsIDs[3] = 441803;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Skill variety is the degree to which a job requires a variety of different activities. Task significance is the degree to which a job affects the lives of other people.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">When a knowledge worker has overall authority and responsibility for an entire project, the job has high task identity. The motivating potential for feedback varies, depending on whether the feedback is positive, negative, the manner in which the feedback is provided, and if the person is ready to receive the feedback.</p><p class=\"explanations\"><b>Learning Objective: 3G. Describe the dimensions of a job and approaches to job design and work arrangements that companies use to motivate employees.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Task significance is the degree to which a job affects the lives of other people. Autonomy is the degree to which a job allows a worker freedom, independence, and discretion in scheduling the work and in determining how to carry it out.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Autonomy is the degree to which a job allows a worker freedom, independence, and discretion in scheduling the work and in determining how to carry it out. Task identity is the degree to which the job requires completion of a whole and identifiable piece of work.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_029'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_030';
objQuestion.questionID = 109318;
objQuestion.item = 'LOMA_335_PPQ2019_030';
objQuestion.primaryLO = '3G';
objQuestion.textref = 'c. 3, p. 23';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '3G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statement(s) can correctly be made about job design and motivation:</p><ol type=\"A\" class=\"combo\"><li>Job rotation is appropriate for routine tasks in which shifting employees relieves the monotony of doing one repetitive task.</li><li>Job enlargement typically results in jobs that have only one specialized task at which the employee excels.</li><li>Job enrichment is the process of redesigning a job by decreasing workers’ control over how they perform their work tasks.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A, B, and C";
arrAnsChoices[1] = "A and B only";
arrAnsChoices[2] = "B and C only";
arrAnsChoices[3] = "A only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441804;
arrAnsIDs[1] = 441805;
arrAnsIDs[2] = 441806;
arrAnsIDs[3] = 441807;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct. Job rotation consists of periodically shifting an employee from one task to another task with similar skill requirements. However, Statement B is incorrect because job enlargement involves creating a new job by <b>combining two or more </b>specialized tasks to add more variety.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is incorrect because job enlargement involves creating a new job by <b>combining two or more </b>specialized tasks to add more variety. Statement C is incorrect because job enrichment involves allowing workers <b>more</b> control over how they perform their work tasks.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Statement A is correct. Job rotation consists of periodically shifting an employee from one task to another task with similar skill requirements. Job rotation allows a company to address unpredictable worker demand by shifting workers to areas where current demand is greatest.</p><p class=\"explanations\">Statement B is incorrect because job enlargement involves creating a new job by combining two or more specialized tasks to add more variety. Statement C is incorrect because job enrichment involves allowing workers more control over how they perform their work tasks.</p><p class=\"explanations\"><b>Learning Objective: 3G. Describe the dimensions of a job and approaches to job design and work arrangements that companies use to motivate employees.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_030'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_031';
objQuestion.questionID = 109319;
objQuestion.item = 'LOMA_335_PPQ2019_031';
objQuestion.primaryLO = '3H';
objQuestion.textref = 'c. 3, p. 26';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '3H';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Effectiveness and productivity is generally higher in cohesive groups. One way for a manager to increase group cohesiveness is to</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "give financial incentives based on individual performance rather than group performance";
arrAnsChoices[1] = "increase the size of the group";
arrAnsChoices[2] = "decrease the amount of time that group spends together";
arrAnsChoices[3] = "set specific goals or directives for the group";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441808;
arrAnsIDs[1] = 441809;
arrAnsIDs[2] = 441810;
arrAnsIDs[3] = 441811;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">To encourage group cohesiveness, a manager should base rewards on the <b>group’s collective performance </b>rather than individual performance.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\"><b>Smaller </b>groups are more cohesive than larger groups. A group of seven to 15 participants is ideal for coordinating tasks or solving problems.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\"><b>Increasing </b>the time that group members spend interacting with each other is a way to increase group participation, which increase group cohesiveness.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Groups with specific goals or directives are more cohesive because everyone is working for the same purpose. A group without clear and understood goals has no direction, and group members must make decisions about what they think is right, often with very differing opinions about the direction for the group.</p><p class=\"explanations\"><b>Learning Objective: 3H. Describe workgroups, the characteristics of cohesive groups, and the group development process.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_031'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_032';
objQuestion.questionID = 109320;
objQuestion.item = 'LOMA_335_PPQ2019_032';
objQuestion.primaryLO = '3H';
objQuestion.textref = 'c. 3, p. 27';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '3H';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Experts suggest that groups go through distinct stages of development: the forming stage, the norming stage, the storming stage, the performing stage, and the adjourning stage. <b>(Not all</b> / <b>All)</b> groups are able to move past the storming stage. In the <b>(norming stage</b> / <b>storming stage)</b>, a group is most subject to groupthink. </p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Not all / norming stage";
arrAnsChoices[1] = "Not all / storming stage";
arrAnsChoices[2] = "All / norming stage";
arrAnsChoices[3] = "All / storming stage";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441812;
arrAnsIDs[1] = 441813;
arrAnsIDs[2] = 441814;
arrAnsIDs[3] = 441815;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">In the storming stage, group members strive to identify a leader and establish responsibilities. Group members have a basic understanding of the group’s task but an increased need for clarification about everything, such as who is responsible for what. The identified leaders must provide clarification and attempt to resolve any hidden disagreements and personality conflicts so that the group can move on to the next stage. </p><p class=\"explanations\"><b>Learning Objective: 3H. Describe workgroups, the characteristics of cohesive groups, and the group development process.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is correct to say that not all groups are able to move past the storming stage. However, a group is most subject to groupthink in the <b>norming stage</b>. </p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is correct to say that a group is most subject to groupthink in the norming stage. However, <b>not all</b> groups are able to move past the storming stage. </p>";
arrAnswerFeedback[3] = "<p class=\"explanations\"><b>Not all</b> groups are able to move past the storming stage. In addition, a group is most subject to groupthink in the <b>norming stage</b>. </p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_032'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_033';
objQuestion.questionID = 109321;
objQuestion.item = 'LOMA_335_PPQ2019_033';
objQuestion.primaryLO = '3I';
objQuestion.textref = 'c. 3, pp. 28-29';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '3I';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statement(s) can correctly be made about employee engagement:</p><ol type=\"A\" class=\"combo\"><li>Research shows that employees are more engaged in their jobs when their own values align with organizational values.</li><li>An employee value proposition (EVP) allows a company to clarify what aspects of a job make employees happy and then work on creating or improving those aspects. </li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441816;
arrAnsIDs[1] = 441817;
arrAnsIDs[2] = 441818;
arrAnsIDs[3] = 441819;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Employee engagement refers to an individual’s involvement with, satisfaction with, and enthusiasm for the work she does. Organizations with higher-than-average levels of employee engagement have higher levels of customer satisfaction, are more productive, have higher profits, and experience lower turnover than do companies with less engaged employees. </p><p class=\"explanations\">An employee value proposition (EVP) is a formal statement of what sets a company apart from other companies and identifies what employees value most about working for the company. The EVP explains why employees would want to join and stay with a company.</p><p class=\"explanations\"><b>Learning Objective: 3I. Describe the benefits of employee engagement and how companies can enhance employee engagement.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct; however, it is not the only correct statement.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is correct; however, it is not the only correct statement.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of the statements is correct. </p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_033'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_034';
objQuestion.questionID = 109322;
objQuestion.item = 'LOMA_335_PPQ2019_034';
objQuestion.primaryLO = '3J';
objQuestion.textref = 'c. 3, pp. 29-30';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '3J';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The followings statements are about workplace bullying and sexual harassment. Three statements are true, and one statement is false. Select the answer choice containing the <B>FALSE</B> statement. </p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Taking credit for the work of others is not considered to be workplace bullying.";
arrAnsChoices[1] = "Sexual harassment includes, but is not limited to, offensive gestures, joking, and language.";
arrAnsChoices[2] = "Bystanders should try to diffuse an uncomfortable situation without drawing direct attention to themselves. ";
arrAnsChoices[3] = "In situations where a bystander suspects something might have happened but is uncertain, the bystander can talk to the victim privately.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441820;
arrAnsIDs[1] = 441821;
arrAnsIDs[2] = 441822;
arrAnsIDs[3] = 441823;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">This statement is false; therefore, it is the correct response. A bully may withhold needed information, purposely provide incorrect information, <b>or take credit</b> for the work of others. </p><p class=\"explanations\"><b>Learning Objective: 3J. Explain the role of organizational values in encouraging trust, respect, and openness in the workplace and ways that companies can discourage bullying and sexual harassment.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response. </p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response. </p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_034'] = objQuestion;



arrMinicases[1] = "<p class=\"caseinfo\">Use the following information to answer questions 5 and 6.</p><p class=\"caseinfo\">Diane Chen is a contact center manager at the Magnolia Insurance Company. Consider the following situations with regard to Ms.&nbsp;Chen’s use of behavior-modification strategies:</p><ul class=\"examul\"><li><b>Situation 1</b>—Ms.&nbsp;Chen praised an employee for making no errors in a given batch of transactions.</li><li><b>Situation 2</b>—Ms.&nbsp;Chen ignored an employee’s continuous complaining about the rudeness of customers calling the company’s call center.</li></ul>";


var arrlotext = new Array(); 
arrlotext['3A'] = "3A. Explain the importance of trust in effective leadership and ways that leaders build trust and use power in the workplace.";
arrlotext['3B'] = "3B. Describe the types of influence tactics leaders use in the workplace.";
arrlotext['3C'] = "3C. Describe how individuals can modify their own behavior and that of others by using the eight practices of effective leaders and managing antecedents and consequences in the workplace.";
arrlotext['3D'] = "3D. Explain self-determination theory and expectancy theory and describe the role of motivation in work performance.";
arrlotext['3E'] = "3E. Describe the performance evaluation process, its role in motivating employees, and problems often encountered during performance evaluation.";
arrlotext['3F'] = "3F. Identify different types of compensation and explain how companies link performance evaluation to compensation systems to motivate employees.";
arrlotext['3G'] = "3G. Describe the dimensions of a job and approaches to job design and work arrangements that companies use to motivate employees.";
arrlotext['3H'] = "3H. Describe workgroups, the characteristics of cohesive groups, and the group development process.";
arrlotext['3I'] = "3I. Describe the benefits of employee engagement and how companies can enhance employee engagement.";
arrlotext['3J'] = "3J. Explain the role of organizational values in encouraging trust, respect, and openness in the workplace and ways that companies can discourage bullying and sexual harassment.";
