var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2019';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 335 Practice Questions, Chapter 1";
var coursename = 'LOMA 335';
var modulenumber = 0;
var title = "LOMA_335_PPQ2019_0_1";
var intNumPools = 1;
var numQ = 7;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Operational Excellence for Insurance Professionals (2019)";
arrNumChap[0] = 1;
var thisChap = '1';

objPool = new Object(); 
objPool.intSelectCount = 7;
objPool.formID = 2062;
objPool.formName = 'PPQ2019_0_1';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_335_PQ_001';
arrPoolQuestions[1] = 'LOMA_335_PQ_002';
arrPoolQuestions[2] = 'LOMA_335_PQ_003';
arrPoolQuestions[3] = 'LOMA_335_PQ_004';
arrPoolQuestions[4] = 'LOMA_335_PQ_005';
arrPoolQuestions[5] = 'LOMA_335_PQ_006';
arrPoolQuestions[6] = 'LOMA_335_PQ_007';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_001';
objQuestion.questionID = 109289;
objQuestion.item = 'LOMA_335_PPQ2019_001';
objQuestion.primaryLO = '1A';
objQuestion.textref = 'c. 1, pp. 3-4';
objQuestion.textbook = 0;
objQuestion.chapter = 1;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '1A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Insurance company stakeholders include</p><ol type=\"A\" class=\"combo\"><li>Owners</li><li>Vendors</li><li>Governments</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A, B, and C";
arrAnsChoices[1] = "A and B only";
arrAnsChoices[2] = "A and C only";
arrAnsChoices[3] = "B and C only";
arrAnsChoices[4] = "A only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441683;
arrAnsIDs[1] = 441684;
arrAnsIDs[2] = 441685;
arrAnsIDs[3] = 441686;
arrAnsIDs[4] = 441687;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A stakeholder is any party to an organization that has an interest in how the company conducts its business. Stakeholders can be external or internal to an organization. They affect and can be affected by the organization’s decisions and include customers, owners, employees, governments, suppliers, vendors, and partners.</p><p class=\"explanations\"><b>Learning Objective: 1A. Describe the stakeholders in an insurance company and how the primary tenets of operations management apply to insurance operations.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is correct to say that owners and vendors are insurance company stakeholders, but they are not the only stakeholders listed.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is correct to say that owners and governments are insurance company stakeholders, but they are not the only stakeholders listed.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is correct to say that vendors and governments are insurance company stakeholders, but they are not the only stakeholders listed.</p>";
arrAnswerFeedback[4] = "<p class=\"explanations\">It is correct to say that owners are insurance company stakeholders, but they are not the only stakeholders listed.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_001'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_002';
objQuestion.questionID = 109290;
objQuestion.item = 'LOMA_335_PPQ2019_002';
objQuestion.primaryLO = '1B';
objQuestion.textref = 'c. 1, pp. 5-6';
objQuestion.textbook = 0;
objQuestion.chapter = 1;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '1B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Insurance company operations can be categorized as primary operations or support operations. Select the answer choice that correctly identifies an example of primary operations and an example of support operations.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[-1] = "<u>Primary operations</u></div><div class=\"anshead\"><u>Support operations</u>";
arrAnsChoices[0] = "underwriting</div><div class=\"anscell\" onclick=\"recordAns(1);\">sales and distribution";
arrAnsChoices[1] = "customer retention</div><div class=\"anscell\" onclick=\"recordAns(2);\">accounting";
arrAnsChoices[2] = "internal control</div><div class=\"anscell\" onclick=\"recordAns(3);\">product development and implementation";
arrAnsChoices[3] = "human resources</div><div class=\"anscell\" onclick=\"recordAns(4);\">information technology";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441689;
arrAnsIDs[1] = 441690;
arrAnsIDs[2] = 441691;
arrAnsIDs[3] = 441692;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is correct to say that underwriting is an example of primary insurance company operations; however, sales and distribution are <b>not</b> an example of support operations.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Insurers create profits through the sale of intangible products and services. Insurance products consist of an insurer’s contractual financial commitments as well as services such as claim payments, interest payments, and expert and friendly customer assistance. Primary operations include product development and implementation; sales and distribution; underwriting; policy issue and new business; policy administration; customer service; customer retention; and claims. </p><p class=\"explanations\">Support operations include marketing research, information technology, human resources, accounting/auditing, internal control, and other general administration. Primary and support operations both contribute to the overall success and profitability of the insurance company. </p><p class=\"explanations\"><b>Learning Objective: 1B. Distinguish between primary and support operations and describe the broad functions of operations employees.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Internal control is an example of <b>support</b> operations. Also, product development and implementation is an example of <b>primary</b> operations.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is correct to say that information technology is an example of support operations; however, human resources is <b>not</b> an example of primary operations.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_002'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_003';
objQuestion.questionID = 109291;
objQuestion.item = 'LOMA_335_PPQ2019_003';
objQuestion.primaryLO = '1C';
objQuestion.textref = 'c. 1, p. 8';
objQuestion.textbook = 0;
objQuestion.chapter = 1;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '1C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statement(s) can correctly be made about transactional work and knowledge workers:</p><ol type=\"A\" class=\"combo\"><li>Transactional work often allows a great deal of flexibility in how processes are completed.</li><li>Knowledge workers tend to be self-managing and continuously innovating.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441693;
arrAnsIDs[1] = 441694;
arrAnsIDs[2] = 441695;
arrAnsIDs[3] = 441696;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is incorrect because transactional work refers to routine and repetitive tasks with <b>little</b> flexibility in how processes are completed. </p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement A is incorrect because transactional work refers to routine and repetitive tasks with little flexibility in how processes are completed.</p><p class=\"explanations\">Statement B is correct. Knowledge workers can interpret information within a specific, yet broad, domain; use skills and knowledge to define problems; and identify alternative solutions to problems. Companies that effectively employ knowledge workers can earn a competitive edge in the marketplace. </p><p class=\"explanations\"><b>Learning Objective: 1C. Describe transactional work and knowledge workers and explain how intellectual capital benefits a company.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct. </p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_003'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_004';
objQuestion.questionID = 109292;
objQuestion.item = 'LOMA_335_PPQ2019_004';
objQuestion.primaryLO = '1D';
objQuestion.textref = 'c. 1, p. 9';
objQuestion.textbook = 0;
objQuestion.chapter = 1;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '1D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The value chain, proposed by Michael Porter, refers to a set of activities that a company carries out to create stakeholder value. This model consists of three main parts: resource inputs, transformative processes, and outputs. Examples of <i>outputs </i>for insurance companies generally include</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "goodwill";
arrAnsChoices[1] = "claim processing";
arrAnsChoices[2] = "technology";
arrAnsChoices[3] = "investment management";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441697;
arrAnsIDs[1] = 441698;
arrAnsIDs[2] = 441699;
arrAnsIDs[3] = 441700;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">According to Porter, a company exists to generate value for customers and profits for owners. How well a company carries out value chain activities determines costs and affects profits. According to this model, goodwill is an output. Other outputs are satisfied customers, satisfied employees, profits, and investment growth.</p><p class=\"explanations\"><b>Learning Objective: 1D. Describe the elements in a value chain and explain how value chains are used in operations management.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">According to this model, claim processing is categorized as a <b>transformative process</b>.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">According to this model, technology is categorized as a <b>resource</b> <b>input</b>. </p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">According to this model, investment management is categorized as a <b>transformative process</b>. </p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_004'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_005';
objQuestion.questionID = 109293;
objQuestion.item = 'LOMA_335_PPQ2019_005';
objQuestion.primaryLO = '1E';
objQuestion.textref = 'c. 1, p. 12';
objQuestion.textbook = 0;
objQuestion.chapter = 1;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '1E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Insurance company operations are subject to a host of internal and external risks. The potential for financial losses resulting from inadequate or failed company processes and controls is known as </p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "regulatory risk, which is a type of internal risk";
arrAnsChoices[1] = "regulatory risk, which is a type of external risk";
arrAnsChoices[2] = "operational risk, which is a type of internal risk";
arrAnsChoices[3] = "operational risk, which is a type of external risk";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441701;
arrAnsIDs[1] = 441702;
arrAnsIDs[2] = 441703;
arrAnsIDs[3] = 441704;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The potential for financial losses resulting from inadequate or failed company processes and controls is <b>not</b> known as regulatory risk. Also, regulatory risk is a type of <b>external</b> risk.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is correct to say that regulatory risk is a type of external risk; however, the potential for financial losses resulting from inadequate or failed company processes and controls is <b>not</b> known as regulatory risk.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Operational risk is the potential for financial losses resulting from inadequate or failed internal processes and controls, people, or systems. Investment risks, regulatory risks, fraud risks, and cybersecurity risks are examples of external risks with potential to create significant financial and nonfinancial losses for insurance companies. </p><p class=\"explanations\"><b>Learning Objective: 1E. Define enterprise risk management (ERM) and explain the ERM process.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is correct to say that the potential for financial losses resulting from inadequate or failed company processes and controls is known as operational risk; however, operational risk is a type of <b>internal</b> risk.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_005'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_006';
objQuestion.questionID = 109294;
objQuestion.item = 'LOMA_335_PPQ2019_006';
objQuestion.primaryLO = '1F';
objQuestion.textref = 'c. 1, pp. 16-17, 20';
objQuestion.textbook = 0;
objQuestion.chapter = 1;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '1F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about the changing operating environment for insurers. Three statements are true, and one statement is false. Select the answer choice containing the <B>FALSE</B> statement. </p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Insurers are analyzing every aspect of their value chains to see how they might use new technologies to realign operations and deliver greater customer value. ";
arrAnsChoices[1] = "The most common operational problem insurers face in connection with technological change is whether to modify or replace legacy systems. ";
arrAnsChoices[2] = "The goal of artificial intelligence (AI) is to automate transactional tasks that normally require human intervention.";
arrAnsChoices[3] = "Fraud detection and prevention in life insurance company operations are increasingly important. ";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441705;
arrAnsIDs[1] = 441706;
arrAnsIDs[2] = 441707;
arrAnsIDs[3] = 441708;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">This statement is false; therefore, it is the correct response. Artificial intelligence (AI) is the area of computer science that emphasizes the development of intelligent machines that work, “learn,” and react like humans. The goal of AI is to go beyond automation and design processes for activities that previously required human intelligence. </p><p class=\"explanations\"><b>Learning Objective: 1F. Describe changes in the insurance company operating environment and strategies that insurers are implementing in response to these changes.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_006'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_007';
objQuestion.questionID = 109295;
objQuestion.item = 'LOMA_335_PPQ2019_007';
objQuestion.primaryLO = '1F';
objQuestion.textref = 'c. 1, pp. 20-23';
objQuestion.textbook = 0;
objQuestion.chapter = 1;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '1F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about new market competitors, the changing workforce, regulations, and the economic environment, which impact insurance operations management. Select the answer containing the correct statement. </p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "According to the three-box solution proposed by Vijay Govindarajan, a Dartmouth College professor, Box 1 requires companies to discontinue activities or even lines of business that might be successful today but are unlikely to be successful in the future.";
arrAnsChoices[1] = "Millennials are active participants in the gig economy. ";
arrAnsChoices[2] = "Although the political environment remains volatile, regulatory uncertainty is likely to go away. ";
arrAnsChoices[3] = "Because future investment income is likely to be much higher than anticipated, insurers will more easily be able to manage benefit payments.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441709;
arrAnsIDs[1] = 441710;
arrAnsIDs[2] = 441711;
arrAnsIDs[3] = 441712;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">According to Vijay Govindarajan’s three-box solution, <b>Box 2</b> requires companies to discontinue activities or even lines of business that might be successful today but are unlikely to be successful in the future. </p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Workforce demographics have changed, and these changes present challenges for operations management. The Millennial population has now surpassed the baby boom population as the largest living population segment. Millennials, as a whole, have been slow to adopt many of the markers commonly associated with baby boomer adulthood, such as permanent employment, home ownership, or marriage. </p><p class=\"explanations\">A gig economy is an environment in which an on-demand labor force is utilized to fill temporary or short-term jobs, and there is no formal employer-employee relationship between the independent worker and the employer.</p><p class=\"explanations\"><b>Learning Objective: 1F. Describe changes in the insurance company operating environment and strategies that insurers are implementing in response to these changes.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">As the political environment remains volatile, regulatory uncertainly <b>will</b> continue. </p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Insurers must invest funds cautiously to ensure that they will have the funds available should benefit payments be greater than expected. As a result, insurers invest conservatively, with a significant amount of funds in interest-bearing bonds such as U.S. Treasury bonds. Since the Great Recession in 2008, bond interest rates have been at historic lows. Insurers sold products during the 1970s, 1980s, and even 1990s with a pricing structure that assumed a much higher interest rate for investment income than was actually earned. With investment income <b>lower</b> than anticipated, insurers need to operate more efficiently and less expensively in order to remain profitable. </p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_007'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['1A'] = "1A. Describe the stakeholders in an insurance company and how the primary tenets of operations management apply to insurance operations.";
arrlotext['1B'] = "1B. Distinguish between primary and support operations and describe the broad functions of operations employees.";
arrlotext['1C'] = "1C. Describe transactional work and knowledge workers and explain how intellectual capital benefits a company.";
arrlotext['1D'] = "1D. Describe the elements in a value chain and explain how value chains are used in operations management.";
arrlotext['1E'] = "1E. Define enterprise risk management (ERM) and explain the ERM process.";
arrlotext['1F'] = "1F. Describe changes in the insurance company operating environment and strategies that insurers are implementing in response to these changes.";
