var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2019';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 361 Practice Questions, Chapter 1";
var coursename = 'LOMA 361';
var modulenumber = 1;
var title = "LOMA_361_PPQ2019_0_1";
var intNumPools = 1;
var numQ = 8;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Accounting and Financial Reporting in Life Insurance Companies, Second Edition (2019)";
arrNumChap[0] = 1;
var thisChap = '1';

objPool = new Object(); 
objPool.intSelectCount = 8;
objPool.formID = 2103;
objPool.formName = 'PPQ2019_0_1';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_361_PQ_001';
arrPoolQuestions[1] = 'LOMA_361_PQ_002';
arrPoolQuestions[2] = 'LOMA_361_PQ_003';
arrPoolQuestions[3] = 'LOMA_361_PQ_004';
arrPoolQuestions[4] = 'LOMA_361_PQ_005';
arrPoolQuestions[5] = 'LOMA_361_PQ_006';
arrPoolQuestions[6] = 'LOMA_361_PQ_007';
arrPoolQuestions[7] = 'LOMA_361_PQ_008';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_001';
objQuestion.questionID = 110187;
objQuestion.item = 'LOMA_361_PPQ2019_001';
objQuestion.primaryLO = '1A';
objQuestion.textref = 'c. 1, pp. 4-6';
objQuestion.textbook = 0;
objQuestion.chapter = 1;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '1A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Internal and external users of an insurer’s financial information can have a direct financial interest or an indirect financial interest in the insurer. Select the individual user of the Scout Life Insurance Company’s financial information who is an <i>external</i> user with an <i>indirect</i> financial interest in Scout.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Rita Myrick works in Scout’s underwriting division.";
arrAnsChoices[1] = "Cole Nance works for a rating agency that compiles data about Scout and other life insurance companies.";
arrAnsChoices[2] = "Sonya Oram owns stock in Scout.";
arrAnsChoices[3] = "Tom Phan serves on Scout’s board of directors.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445322;
arrAnsIDs[1] = 445323;
arrAnsIDs[2] = 445324;
arrAnsIDs[3] = 445325;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A company’s <b>internal</b> users—including Scout employees such as Ms.&nbsp;Myrick, and officers and directors—typically have a <b>direct</b> financial interest in the company because they can gain or lose money as a result of the company’s financial performance.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Internal users of a company’s financial information include the company’s employees, directors, and officers. Internal users typically have a direct financial interest in the company, which means they can gain or lose money as a result of the company’s financial performance.</p><p class=\"explanations\">External users of a company’s financial information are people and organizations outside the company who use the company’s financial information to make various decisions about the company. These users can have either a direct financial interest or an indirect financial interest in the company’s performance. External users who have an indirect financial interest in a company’s financial information are seeking a company’s financial information on behalf of others.</p><p class=\"explanations\">Sometimes an individual or entity is both an internal user and external user, such as an individual who is both an employee and a policyowner, insured, or stockholder of the insurer. An external user may have a direct financial interest and an indirect financial interest in the insurer, such as an individual who is both a beneficiary of a policy issued by an insurer and an employee of the state insurance department that oversees that insurer.</p><p class=\"explanations\"><b>Learning Objective: 1A. Categorize typical internal and external users of financial information.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that a company’s stockholders are external users of the company’s financial information. However, Scout company stockholders such as Ms.&nbsp;Oram have a <b>direct </b>financial interest in the company because they can gain or lose money as a result of the company’s financial performance.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A company’s internal users—including Scout <b>directors</b> such as Mr.&nbsp;Phan, and employees and officers—typically have a <b>direct</b> financial interest in the company, because they can gain or lose money as a result of the company’s financial performance.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_001'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_002';
objQuestion.questionID = 110188;
objQuestion.item = 'LOMA_361_PPQ2019_002';
objQuestion.primaryLO = '1B';
objQuestion.textref = 'c. 1, pp. 8, 12';
objQuestion.textbook = 0;
objQuestion.chapter = 1;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '1B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Two major fields of accounting are financial accounting and management accounting. Financial accounting focuses primarily on reporting a company’s financial information to meet the needs of the company’s <b>(internal / external)</b> users. The field of accounting that focuses primarily on identifying, measuring, analyzing, and communicating financial information to a company’s internal users, so they can decide how to best use the company’s resources, is <b>(financial / management)</b> accounting.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "internal / financial";
arrAnsChoices[1] = "internal / management";
arrAnsChoices[2] = "external / financial";
arrAnsChoices[3] = "external / management";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445326;
arrAnsIDs[1] = 445327;
arrAnsIDs[2] = 445328;
arrAnsIDs[3] = 445329;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Financial accounting focuses primarily on reporting a company’s financial information to meet the needs of the company’s <b>external</b> users. Also, <b>management</b> accounting focuses primarily on identifying, measuring, analyzing, and communicating financial information to a company’s internal users, particularly company managers, so they can decide how to best use the company’s resources.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that management accounting focuses primarily on identifying, measuring, analyzing, and communicating financial information to a company’s internal users, particularly company managers, so they can decide how to best use the company’s resources. However, financial accounting mainly focuses on reporting a company’s financial information to meet the needs of the company’s <b>external</b> users.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that financial accounting focuses primarily on reporting a company’s financial information to meet the needs of the company’s external users. However, <b>management</b> accounting focuses primarily on identifying, measuring, analyzing, and communicating financial information to a company’s internal users, particularly company managers, so they can decide how to best use the company’s resources.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Using financial accounting, a company’s accountants communicate the results of the company’s numerous business transactions on financial statements. Unlike management accounting, financial accounting is subject to specific accounting standards and is required by law. Financial accounting focuses on evaluating a company’s past performance.</p><p class=\"explanations\">Management accounting focuses on planning the company’s future performance. Management accounting activities help to analyze operating costs, oversee budgets, and evaluate the profitability of various products and services.</p><p class=\"explanations\"><b>Learning Objective: 1B. Distinguish between financial accounting and management accounting, and between generally accepted accounting principles (GAAP) and statutory accounting principles (SAP).</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_002'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_003';
objQuestion.questionID = 110189;
objQuestion.item = 'LOMA_361_PPQ2019_003';
objQuestion.primaryLO = '1B';
objQuestion.textref = 'c. 1, pp. 4, 9, 13-14';
objQuestion.textbook = 0;
objQuestion.chapter = 1;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '1B';
arrLOs[1] = '1D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Many U.S. insurers currently prepare two sets of financial statements—one set based on U.S. generally accepted accounting principles (GAAP), and a second set based on statutory accounting principles (SAP). U.S. insurers must follow <b>(GAAP / SAP)</b> to prepare the Annual Statement. The Annual Statement presents information about an insurer’s financial performance, with an emphasis on demonstrating the insurer’s <b>(profitability / solvency)</b>. The insurer’s employees who prepare financial accounting reports and statements, including the Annual Statement, for external users are known as <b>(public / private)</b> accountants.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "GAAP / profitability / public";
arrAnsChoices[1] = "GAAP / solvency / private";
arrAnsChoices[2] = "SAP / profitability / public";
arrAnsChoices[3] = "SAP / solvency / private";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445330;
arrAnsIDs[1] = 445331;
arrAnsIDs[2] = 445332;
arrAnsIDs[3] = 445333;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">U.S. insurers must follow <B>SAP</B> to prepare the Annual Statement. Also, the Annual Statement focuses on demonstrating an insurer’s <b>solvency</b>, and the insurer’s employees who prepare the Annual Statement are known as <b>private</b> accountants.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that the Annual Statement focuses on demonstrating an insurer’s solvency, and that the insurer’s employees who prepare the Annual Statement are known as private accountants. However, U.S. insurers must follow <B>SAP</B> to prepare the Annual Statement.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that U.S. insurers must follow SAP to prepare the Annual Statement. However, the Annual Statement focuses on demonstrating an insurer’s <b>solvency</b>, and the insurer’s employees who prepare the Annual Statement are known as <b>private</b> accountants.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">GAAP are a set of financial accounting standards, conventions, and rules that all publicly traded companies must follow when summarizing transactions and preparing their financial statements. GAAP focuses on a company’s profitability—the overall degree of success a company has in generating positive returns for its owners—such as the company’s ability to generate profits and increase value.</p><p class=\"explanations\">SAP are accounting standards that all life insurers in the United States must follow when preparing the Annual Statement and other specified financial reports that they submit to state insurance regulators. SAP focuses on a company’s solvency, which is a company’s ability to meet its financial obligations when they become due. Generally, a company is considered solvent if it owns more than it owes.</p><p class=\"explanations\">Public accounting is performed by public accountants, who work for, or are affiliated with, a public accounting company or governmental regulatory authority. Private accounting is performed by company-employed accountants who prepare financial accounting reports and statements for the company’s external users and management accounting reports for the company’s internal users.</p><p class=\"explanations\"><b>Learning Objective: (1) 1B. Distinguish between financial accounting and management accounting, and between generally accepted accounting principles (GAAP) and statutory accounting principles (SAP); (2) 1D. Distinguish between private and public accounting and describe how the role of the controller has changed in recent years.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_003'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_004';
objQuestion.questionID = 110190;
objQuestion.item = 'LOMA_361_PPQ2019_004';
objQuestion.primaryLO = '1C';
objQuestion.textref = 'c. 1, p. 11';
objQuestion.textbook = 0;
objQuestion.chapter = 1;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '1C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statement(s) can correctly be made about the impact of the set of global accounting standards known as IFRS Standards on life insurers in the United States and around the world:</p><ol type=\"A\" class=\"combo\"><li>Companies that issue publicly traded securities in countries that have adopted IFRS Standards must prepare their financial statements according to IFRS Standards.</li><li>Currently, the United States generally does not require the use of IFRS Standards for domestic companies with publicly traded securities.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445334;
arrAnsIDs[1] = 445335;
arrAnsIDs[2] = 445336;
arrAnsIDs[3] = 445337;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Statement A is correct. For years, international companies had to comply with separate, and sometimes conflicting, financial reporting requirements in each country in which they conducted business. In response, the International Accounting Standards Board (IASB) developed IFRS Standards to promote consistency, comparability, and more complete disclosure of the information contained in corporate financial statements.</p><p class=\"explanations\">Statement B is correct. Foreign companies whose stock is traded in the United States are now permitted—but not required—to use IFRS Standards. A U.S. insurer may be required to use IFRS Standards in certain situations, such as if the insurer is a subsidiary of a foreign company, or if it plans to raise capital from other countries.</p><p class=\"explanations\"><b>Learning Objective: 1C. Explain the impact of the set of global accounting standards known as IFRS Standards on life insurers in the United States and around the world.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct; however, Statement B is also correct.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is correct; however, Statement A is also correct.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_004'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_005';
objQuestion.questionID = 110191;
objQuestion.item = 'LOMA_361_PPQ2019_005';
objQuestion.primaryLO = '1E';
objQuestion.textref = 'c. 1, pp. 15-16';
objQuestion.textbook = 0;
objQuestion.chapter = 1;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '1E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following insurers operate in the United States:</p><ul class=\"examul\"><li>The Persimmon Mutual Life Insurance Company sells term life insurance products, whole life insurance products, and variable annuities.</li><li>The Quince Life Insurance Company, a stock insurer, sells term life insurance products, whole life insurance products, and fixed immediate annuities.</li></ul><p class=\"stem\">Select the answer choice that correctly identifies whether Persimmon and Quince are subject to regulation by the Securities and Exchange Commission (SEC).</p>";
var arrAnsChoices = new Array();
arrAnsChoices[-1] = "<u>Persimmon</u></div><div class=\"anshead\"><u>Quince</u>";
arrAnsChoices[0] = "no</div><div class=\"anscell\" onclick=\"recordAns(1);\">yes";
arrAnsChoices[1] = "no</div><div class=\"anscell\" onclick=\"recordAns(2);\">no";
arrAnsChoices[2] = "yes</div><div class=\"anscell\" onclick=\"recordAns(3);\">yes";
arrAnsChoices[3] = "yes</div><div class=\"anscell\" onclick=\"recordAns(4);\">no";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445339;
arrAnsIDs[1] = 445340;
arrAnsIDs[2] = 445341;
arrAnsIDs[3] = 445342;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that Quince is subject to SEC regulation because Quince is a publicly traded company. However, Persimmon is also subject to SEC regulation because Persimmon sells variable annuities. Variable annuities are investment products as well as insurance products; therefore, an insurer that sells variable products is subject to SEC regulation. Under this test, mutual insurers and fraternal insurers that sell variable products are subject to SEC regulation, even though they are not publicly traded stock companies.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Both Persimmon and Quince are subject to SEC regulation. Persimmon is subject to SEC regulation because Persimmon sells variable annuities. Quince is subject to SEC regulation because Quince is a publicly traded company. Variable annuities are investment products as well as insurance products; therefore, an insurer that sells variable products is subject to SEC regulation. Under this test, mutual insurers and fraternal insurers that sell variable products are subject to SEC regulation, even though they are not publicly traded stock companies.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Insurers are subject to SEC regulations if they meet the following tests: (1) all publicly traded companies, including stock insurers; and (2) all insurers that sell variable products, such as variable life insurance and variable annuities. Because variable products are investment products as well as insurance products, an insurer that sells variable products is subject to SEC regulation. Under this test, mutual insurers and fraternal insurers that sell variable products are subject to SEC regulation, even though they are not publicly traded stock companies.</p><p class=\"explanations\">Insurers that are subject to SEC regulation generally must submit U.S. GAAP financial statements to the SEC. However, the SEC now accepts a non-U.S. company’s financial statements that were prepared according to IFRS Standards without requiring the company to restate its financial statements according to U.S.&nbsp;GAAP. Currently, U.S. mutual insurers and fraternal insurers that sell variable products can submit statutory financial statements to the SEC.</p><p class=\"explanations\"><b>Learning Objective: 1E. Describe the roles of various governmental and professional organizations in the regulation of accounting and financial reporting.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that Persimmon is subject to SEC regulation because Persimmon sells variable annuities. Variable annuities are investment products as well as insurance products; therefore, an insurer that sells variable products is subject to SEC regulation. Under this test, mutual insurers and fraternal insurers that sell variable products are subject to SEC regulation, even though they are not publicly traded stock companies. However, Quince is also subject to SEC regulation because Quince is a publicly traded company.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_005'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_006';
objQuestion.questionID = 110192;
objQuestion.item = 'LOMA_361_PPQ2019_006';
objQuestion.primaryLO = '1E';
objQuestion.textref = 'c. 1, pp. 16, 17-18';
objQuestion.textbook = 0;
objQuestion.chapter = 1;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '1E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statement(s) can correctly be made about regulatory agencies and organizations that have a significant impact on accounting and financial reporting for life insurance companies in the United States:</p><ol type=\"A\" class=\"combo\"><li>The National Association of Insurance Commissioners (NAIC) specifies the format and content of the Annual Statement.</li><li>The SEC has delegated its responsibility for establishing U.S. GAAP to the Financial Accounting Standards Board (FASB).</li><li>The purpose of the Internal Revenue Service (IRS) is to protect the interests of investors by ensuring that audit reports are informative, fair, and independent.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A, B, and C";
arrAnsChoices[1] = "A and B only";
arrAnsChoices[2] = "A and C only";
arrAnsChoices[3] = "B and C only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445343;
arrAnsIDs[1] = 445344;
arrAnsIDs[2] = 445345;
arrAnsIDs[3] = 445346;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct. The<b> </b>NAIC, a private, non-profit association of the commissioners of all 50 states, the District of Columbia, and the U.S. territories, promotes uniformity of state regulation by developing model laws and regulations that serve as guidelines for the states. Although the NAIC has no legislative power, its recommendations and actions strongly influence the individual state insurance commissioners, the state legislatures, and the insurance industry.</p><p class=\"explanations\">Statement B is correct. The primary role of the FASB is to establish and promote the use of U.S. GAAP.</p><p class=\"explanations\">Statement C is incorrect. The Public Company Auditing Oversight Board (PCAOB) is a private-sector, nonprofit corporation that sets the auditing standards for external auditors of public companies to ensure that audit reports are informative, fair, and independent.</p><p class=\"explanations\">The IRS, a part of the U.S. Department of the Treasury, is the governmental agency responsible for enforcing the provisions of laws and regulations concerning income taxes. The IRS significantly influences the way in which insurers in the United States conduct business.</p><p class=\"explanations\"><b>Learning Objective: 1E. Describe the roles of various governmental and professional organizations in the regulation of accounting and financial reporting.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement A is correct; however, Statement C is incorrect.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Statement B is correct; however, Statement C is incorrect.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_006'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_007';
objQuestion.questionID = 110193;
objQuestion.item = 'LOMA_361_PPQ2019_007';
objQuestion.primaryLO = '1F';
objQuestion.textref = 'c. 1, pp. 20-21';
objQuestion.textbook = 0;
objQuestion.chapter = 1;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '1F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">In the United States, the NAIC has established a solvency framework of financial tools that enable state regulators to measure and monitor insurer solvency. An important component of this framework is the Insurance Regulatory Information System (IRIS), which consists of two phases: the statistical phase and the analytical phase. One characteristic of IRIS is that</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "the statistical phase of IRIS involves using statutory data from every insurer’s Annual Statement to calculate 12 financial ratios";
arrAnsChoices[1] = "the 12 financial ratios calculated during the statistical phase test an insurer’s financial solvency, but not its profitability";
arrAnsChoices[2] = "the analytical phase of IRIS involves a five-year history analysis of every insurer’s Annual Statement";
arrAnsChoices[3] = "only large insurers are subject to the statistical phase of IRIS";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445347;
arrAnsIDs[1] = 445348;
arrAnsIDs[2] = 445349;
arrAnsIDs[3] = 445350;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The first eight ratios are tests of an insurer’s solvency and profitability. The remaining four ratios assess the insurer’s operations by measuring changes in premiums, product mix, asset mix, and reserving. The ratio results are then compiled in a report.</p><p class=\"explanations\">In the analytical phase, the analyst team evaluates the IRIS ratio results of specified insurance companies. An NAIC working group determines the criteria to be used in targeting specific insurers for the analyst team review. After reviewing the results, the analyst team designates certain insurers as “Level A” (highest priority), “Level B” (lower priority), or “Reviewed, no level” (lowest priority), to identify those insurers in greatest need of regulatory attention.</p><p class=\"explanations\"><b>Learning Objective: 1F. Describe financial tools that regulators in the United States use to evaluate insurer solvency.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">During the statistical phase, the IRIS ratio application extracts data from each insurer’s electronically filed Annual Statement and automatically calculates the results of 12 financial ratios for each insurer. The first eight ratios are tests of an insurer’s <b>solvency and</b> <b>profitability</b>. The remaining four ratios assess the insurer’s operations by measuring changes in premiums, product mix, asset mix, and reserving.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">In the analytical phase, the analyst team evaluates the IRIS ratio results of <b>specified insurance companies</b>. An NAIC working group determines the criteria to be used in targeting specific insurers for the analyst team review.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\"><b>All </b>insurance companies that operate in the U.S. are subject to the statistical phase of IRIS.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_007'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_008';
objQuestion.questionID = 110194;
objQuestion.item = 'LOMA_361_PPQ2019_008';
objQuestion.primaryLO = '1F';
objQuestion.textref = 'c. 1, pp. 23-24';
objQuestion.textbook = 0;
objQuestion.chapter = 1;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '1F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">In the United States, one tool that insurance regulators use to monitor the solvency of insurers is the financial condition examination. The following statements are about this examination. Three statements are true, and one statement is false. Select the answer choice containing the <B>FALSE</B> statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Examination results are submitted to both state regulators and the insurance company’s officers.";
arrAnsChoices[1] = "Most states require that an insurer domiciled in the state be examined routinely once per year.";
arrAnsChoices[2] = "Financial condition examinations investigate the insurer’s financial and business activities to ensure that they do not contribute to the insurer’s insolvency.";
arrAnsChoices[3] = "Most financial condition examinations are classified as association examinations.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445351;
arrAnsIDs[1] = 445352;
arrAnsIDs[2] = 445353;
arrAnsIDs[3] = 445354;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response. The results of a financial condition examination are summarized in an examination report, which is submitted to state regulators and the insurance company’s officers.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">This statement is false; therefore, it is the correct response. In most U.S. states, each insurer domiciled in the state must undergo a financial condition examination once every three to five years by the state insurance department. More frequent examinations are conducted if the state insurance commissioner believes they are warranted. The insurer usually bears the cost of a financial condition examination.</p><p class=\"explanations\">One increasingly important source of information for examiners is the Own Risk and Solvency Assessment (ORSA), an insurer’s internal assessment of the risks associated with its current business plan and the adequacy of its capital resources to support those risks. The NAIC typically requires insurers to undergo an ORSA on at least an annual basis.</p><p class=\"explanations\"><b>Learning Objective: 1F. Describe financial tools that regulators in the United States use to evaluate insurer solvency.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response. In a financial condition examination, examiners verify the operating results reported in the insurer’s Annual Statement; examine the insurer’s accounting records to determine whether the insurer is operating on a sound and lawful basis; and investigate the insurer’s financial and business activities to ensure that they do not contribute to the insurer’s insolvency.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response. Working through the NAIC, the states have developed a zone system to oversee the examinations of multistate insurers. According to this system, each insurance company is domiciled within one of four geographic zones in the United States. For any insurer that operates in more than one zone or in more than three states, the NAIC recommends that the insurer undergo an association examination. In an association examination, also known as a coordinated exam, examiners representing various states in the geographic zones in which the insurer is licensed participate in examining the insurer.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_008'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['1A'] = "1A. Categorize typical internal and external users of financial information.";
arrlotext['1B'] = "1B. Distinguish between financial accounting and management accounting, and between generally accepted accounting principles (GAAP) and statutory accounting principles (SAP).";
arrlotext['1C'] = "1C. Explain the impact of the set of global accounting standards known as IFRS Standards on life insurers in the United States and around the world.";
arrlotext['1D'] = "1D. Distinguish between private and public accounting and describe how the role of the controller has changed in recent years.";
arrlotext['1E'] = "1E. Describe the roles of various governmental and professional organizations in the regulation of accounting and financial reporting.";
arrlotext['1F'] = "1F. Describe financial tools that regulators in the United States use to evaluate insurer solvency.";
