var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2019';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 361 Practice Questions, Chapter 3";
var coursename = 'LOMA 361';
var modulenumber = 1;
var title = "LOMA_361_PPQ2019_0_3";
var intNumPools = 1;
var numQ = 8;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Accounting and Financial Reporting in Life Insurance Companies, Second Edition (2019)";
arrNumChap[0] = 1;
var thisChap = '3';

objPool = new Object(); 
objPool.intSelectCount = 8;
objPool.formID = 2103;
objPool.formName = 'PPQ2019_0_3';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_361_PQ_018';
arrPoolQuestions[1] = 'LOMA_361_PQ_019';
arrPoolQuestions[2] = 'LOMA_361_PQ_020';
arrPoolQuestions[3] = 'LOMA_361_PQ_021';
arrPoolQuestions[4] = 'LOMA_361_PQ_022';
arrPoolQuestions[5] = 'LOMA_361_PQ_023';
arrPoolQuestions[6] = 'LOMA_361_PQ_024';
arrPoolQuestions[7] = 'LOMA_361_PQ_025';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_018';
objQuestion.questionID = 110204;
objQuestion.item = 'LOMA_361_PPQ2019_018';
objQuestion.primaryLO = '3A';
objQuestion.textref = 'c. 3, pp. 3-4';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">A company that uses the going-concern concept in preparing its financial statements assumes that the company</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "is about to be liquidated";
arrAnsChoices[1] = "follows a fiscal year of September through August";
arrAnsChoices[2] = "will continue to operate for an indefinite period of time";
arrAnsChoices[3] = "will pay its liabilities in full during the current accounting period";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445392;
arrAnsIDs[1] = 445393;
arrAnsIDs[2] = 445394;
arrAnsIDs[3] = 445395;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The going-concern concept states that a company’s accounting records must reflect that the company is <b>not</b> facing liquidation. Liquidation is the process of selling all company assets for cash and using that cash to pay the company’s debts; any funds remaining are distributed to the owners of the business.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The going-concern concept is <b>not</b> related to a company’s fiscal year, which is a 12-month accounting period chosen by the company for financial reporting purposes. A company may select a fiscal year—such as September through August—other than the calendar year for financial reporting purposes. However, insurance regulators typically require that insurers use the calendar year—January 1 through December&nbsp;31—as the fiscal year for financial statements and reports submitted for regulatory purposes.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The going-concern concept states that a company’s accounting records must reflect that the company is not facing liquidation. Liquidation is the process of selling all company assets for cash and using that cash to pay the company’s debts; remaining funds are distributed to company owners. The going-concern concept is an underlying premise of GAAP; it is not, however, entirely presumed under SAP, which follows a modified going-concern concept.</p><p class=\"explanations\">The entity concept states that a company must account separately for the business activities of each business unit. An entity is the basic business unit for which a company keeps separate accounting records and prepares reports. A company can identify and define its own accounting entities, and only those transactions that relate to these entities typically will appear on the company’s financial statements.</p><p class=\"explanations\"><b>Learning Objective: 3A. Explain two key financial statement concepts—the entity concept and the going-concern concept.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The going-concern concept assumes that the company will <b>pay off its liabilities over time as scheduled</b>, instead of paying them in full immediately or during the current accounting period.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_018'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_019';
objQuestion.questionID = 110205;
objQuestion.item = 'LOMA_361_PPQ2019_019';
objQuestion.primaryLO = '3B';
objQuestion.textref = 'c. 3, p. 5';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Because insurance companies enter into long-term contracts with their customers, they must be able to anticipate future revenues and expenses as accurately as possible. The predictive quality of a company’s accounting information is vital to this purpose. Strong predictive quality relies in part on specified qualitative characteristics, including relevance, reliability, consistency, comparability, materiality, and conservatism. In this context, accounting information is defined as <i>reliable</i> when it is</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "accurate, objective, and free from bias and misrepresentation";
arrAnsChoices[1] = "based on the same accounting policies and procedures from one accounting period to the next, unless a valid reason to make a change exists";
arrAnsChoices[2] = "significant, in that, if its reporting, the lack of its reporting, or its misrepresentation could affect decisions made by interested users";
arrAnsChoices[3] = "useful, timely, and likely to affect an interested user’s decisions about a company";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445396;
arrAnsIDs[1] = 445397;
arrAnsIDs[2] = 445398;
arrAnsIDs[3] = 445399;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The International Accounting Standards Board (IASB) has referred to reliability as “faithful representation.” Reliable accounting information fairly represents a company’s financial strength or profitability. In most situations, preparers compile objective information using a standardized measurement method.</p><p class=\"explanations\">Further, the company must record and report accounting information in such a manner that outside experts, such as external auditors and regulators, can verify that the information is truthful and based on objective measurements. Objective measurements are based on source documents and explicitly forbid bias or personal opinion.</p><p class=\"explanations\"><b>Learning Objective: 3B. Demonstrate an understanding of the qualitative characteristics of accounting information and the key concepts that guide account maintenance.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">In accounting, the characteristics of comparability and consistency are interrelated. The characteristic of<b> comparability</b> requires a company’s financial statements to be presented in such a way that interested users can identify similarities and differences in financial information across accounting periods and among different companies. The characteristic of <b>consistency</b> means that a company applies the same accounting policies and procedures to the accounting information in its financial statements from one accounting period to the next, unless there is a sound reason for changing a specified policy or procedure.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">In accounting, the characteristic of <b>materiality</b> means that companies must report all significant information in their financial statements. Generally, information is significant or material if its reporting, the lack of its reporting, or its misrepresentation could affect decisions made by interested users.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">In accounting, the characteristic of <b>relevance</b> means that accounting information is required to be useful, timely, and likely to affect an interested user’s decisions about a company.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_019'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_020';
objQuestion.questionID = 110206;
objQuestion.item = 'LOMA_361_PPQ2019_020';
objQuestion.primaryLO = '3B';
objQuestion.textref = 'c. 3, pp. 8-9';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">In contrast to GAAP-based accounting, under SAP, a life insurance company must report its accounting information in a conservative manner. Consider the following activities performed by the Vinca Life Insurance Company:</p><ul class=\"examul\"><li><b>Activity A</b>—Vinca reports gains only when they actually occur.</li><li><b>Activity B</b>—Vinca records expenses only when they are incurred.</li><li><b>Activity C</b>—Vinca typically reports account values based on higher expense rates for each block of policies, compared to typical expense rates for similar blocks of policies.</li><li><b>Activity D</b>—Vinca typically reports account values based on higher mortality rates for annuity contracts, compared to typical mortality rates for annuity contracts.</li></ul><p class=\"stem\">With regard to whether these activities demonstrate the accounting concept of conservatism, it is correct to say that Vinca demonstrates the quality of conservatism in</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Activities A, B, C, and D";
arrAnsChoices[1] = "Activities A, B, and C only";
arrAnsChoices[2] = "Activity A and Activity D only";
arrAnsChoices[3] = "Activity B and Activity C only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445400;
arrAnsIDs[1] = 445401;
arrAnsIDs[2] = 445402;
arrAnsIDs[3] = 445403;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Activities A, B, and C demonstrate the concept of conservatism. However, Activity D does <b>not </b>demonstrate this quality. Under conservatism, insurers typically report account values based on <b>lower</b> mortality rates for annuity contracts, compared to typical mortality rates for annuity contracts.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">According to SAP, conservatism is a prudent reaction for dealing with uncertainty in accounting records and reports. Insurers record revenues only when they are certain, record expenses when they are incurred, report losses immediately, and report gains only when they actually occur.</p><p class=\"explanations\">In addition, as compared with other information qualities, insurers typically report account values based on higher mortality rates for life insurance policies, lower mortality rates for annuity contracts, higher expense rates for each block of policies, and lower interest rates for investment earnings on assets that support life insurance policy reserves and annuity reserves.</p><p class=\"explanations\">Under SAP, insurers apply conservative accounting methods only if they do not violate other accounting qualities, such as relevance or reliability. In contrast, under U.S. GAAP, conservatism is considered biased and inconsistent with qualitative characteristics such as reliability and comparability.</p><p class=\"explanations\"><b>Learning Objective: 3B. Demonstrate an understanding of the qualitative characteristics of accounting information and the key concepts that guide account maintenance.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that Activity A demonstrates conservatism. However, Activity D does <b>not </b>demonstrate this concept. Under conservatism, insurers typically report account values based on <b>lower</b> mortality rates for annuity contracts, compared to typical mortality rates for annuity contracts.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that Activity B and Activity C demonstrate the concept of conservatism. However, these are <b>not</b> the only activities listed that demonstrate conservatism.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_020'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_021';
objQuestion.questionID = 110207;
objQuestion.item = 'LOMA_361_PPQ2019_021';
objQuestion.primaryLO = '3B';
objQuestion.textref = 'c. 3, p. 11';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Seven years ago, an insurer paid $850,000 for an office building. The building’s current market value is $1,000,000. The account maintenance concept that requires the insurer to report the value of the building at $850,000 on its balance sheet is called the</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "time-period concept";
arrAnsChoices[1] = "full-disclosure concept";
arrAnsChoices[2] = "cost-effectiveness concept";
arrAnsChoices[3] = "cost concept";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445404;
arrAnsIDs[1] = 445405;
arrAnsIDs[2] = 445406;
arrAnsIDs[3] = 445407;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The <b>time-period concept</b> states that a company’s financial statements should report the company’s business operations during a specified fiscal period, usually referred to as an accounting period.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The <b>full-disclosure concept</b> states that a financial statement must contain all material information about a company and that the company must disclose any additional information or fact that, by its omission, could mislead an interested user of the company’s financial information.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">In the context of materiality, the accounting quality of <b>cost-effectiveness</b> means that a company considers the money spent to achieve the desired goals. Although it is critical for insurers to report all material information, they should capture this information in a cost-effective manner. A company should not incur huge expenses to record and report material accounting information.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The cost concept, also called the historical-cost concept, the cost principle, the initial-recording concept, and the acquisition-cost concept, states that companies should report items on the balance sheet and income statement on the basis of their historical cost, which is their original purchase price on the date of purchase.</p><p class=\"explanations\">An asset’s historical cost provides a reliable measure of the asset’s value, because the historical cost is a verifiable figure that will not change. However, an asset’s historical cost may lack relevance because the asset may have significantly increased or decreased in value over time. Companies often use other valuation methods to report the value of assets.</p><p class=\"explanations\"><b>Learning Objective: 3B. Demonstrate an understanding of the qualitative characteristics of accounting information and the key concepts that guide account maintenance.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_021'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_022';
objQuestion.questionID = 110208;
objQuestion.item = 'LOMA_361_PPQ2019_022';
objQuestion.primaryLO = '3C';
objQuestion.textref = 'c. 3, pp. 13-14';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">With regard to the recognition of revenues and expenses, one characteristic of U.S. GAAP is that a life insurance company should recognize</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "all incurred expenses in the current accounting period";
arrAnsChoices[1] = "insurance premiums as they are earned over the lifetime of the insurance policy or annuity contract";
arrAnsChoices[2] = "all paid expenses during the current accounting period";
arrAnsChoices[3] = "revenues and expenses only when the company receives cash or disburses cash";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445408;
arrAnsIDs[1] = 445409;
arrAnsIDs[2] = 445410;
arrAnsIDs[3] = 445411;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Under U.S. GAAP, the matching principle states that a company should <b>recognize expenses as the company earns the revenues related to those expenses</b>, regardless of when the company receives payment for the revenues earned and regardless of when the company actually paid the expenses.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Under U.S. GAAP, the realization principle and the matching principle work in tandem. A company reports earned revenue under the realization principle. The company also identifies the expenses it incurred to earn that specified revenue and records these expenses under the matching principle.</p><p class=\"explanations\">The realization principle states that a company should recognize revenue when it is earned, regardless of when the company receives the actual payment, so long as a legal and reasonable expectation exists that the customer will remit payment in full. For life insurance companies, revenue recognition applies primarily to the receipt of life insurance or annuity premiums. The matching principle states that a company should recognize expenses as the company earns the revenues related to those expenses, regardless of when the company receives payment for the revenues earned and regardless of when the company actually paid the expenses.</p><p class=\"explanations\"><b>Learning Objective: 3C. Describe the realization principle and the matching principle in accrual-basis accounting.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Under U.S. GAAP, the matching principle states that a company should <b>recognize expenses as the company earns the revenues related to those expenses</b>, regardless of when the company receives payment for the revenues earned and regardless of when the company actually paid the expenses.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">This answer choice describes <b>cash-basis accounting</b>, which is an accounting system in which a company recognizes revenues or expenses only when it receives cash or disburses cash.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_022'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_023';
objQuestion.questionID = 110209;
objQuestion.item = 'LOMA_361_PPQ2019_023';
objQuestion.primaryLO = '3C';
objQuestion.textref = 'c. 3, p. 15';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Balm Insurance Company incurred $12,000 in expenses for employee training costs that cannot be attributed to any revenues earned by the company. Therefore, Balm reported the entire $12,000 expense during the current accounting period. Under U.S. GAAP, the approach to expense recognition that Balm used in this situation is known as</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "immediate recognition";
arrAnsChoices[1] = "systematic and rational allocation";
arrAnsChoices[2] = "associating cause and effect";
arrAnsChoices[3] = "salvage value";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445412;
arrAnsIDs[1] = 445413;
arrAnsIDs[2] = 445414;
arrAnsIDs[3] = 445415;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Generally, U.S. GAAP permits three approaches to expense recognition: (1) associating cause and effect, (2) systematic and rational allocation, and (3) immediate recognition. Under immediate recognition, a company recognizes all costs as expenses during the current accounting period. In contrast, under SAP, life insurers generally must use immediate recognition to recognize all incurred expenses—not just expenses for which the insurer cannot match revenues—in the current accounting period, rather than spread these expenses over the accounting periods in which premium income was earned.</p><p class=\"explanations\">Under systematic and rational allocation, a company spreads an asset’s cost over its estimated useful life, regardless of when the company receives revenues from the asset. According to the approach of associating cause and effect, expenses that have a direct relationship to specified future revenues are charged to future accounting periods instead of being charged to the current accounting period.</p><p class=\"explanations\"><b>Learning Objective: 3C. Describe the realization principle and the matching principle in accrual-basis accounting.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Balm is <b>not </b>using systematic and rational allocation in this situation. Under systematic and rational allocation, a company spreads an asset’s cost over its estimated useful life, regardless of when the company receives revenues from the asset.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Balm is <b>not </b>using associating cause and effect in this situation. According to the approach of associating cause and effect, expenses that have a direct relationship to specified future revenues are charged to future accounting periods instead of being charged to the current accounting period.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Balm is <b>not </b>using salvage value in this situation. Salvage value is the residual value or selling price of an asset at the end of its useful life.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_023'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_024';
objQuestion.questionID = 110210;
objQuestion.item = 'LOMA_361_PPQ2019_024';
objQuestion.primaryLO = '3D';
objQuestion.textref = 'c. 3, p. 18';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Two major accounting bases are accrual-basis accounting and cash-basis accounting. The realization principle and the matching principle apply under <b>(both accounting bases / accrual-basis accounting only)</b>. Accounting regulations generally mandate the use of <b>(accrual-basis / cash-basis)</b> accounting for financial reporting purposes.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "both accounting bases / accrual-basis";
arrAnsChoices[1] = "both accounting bases / cash-basis";
arrAnsChoices[2] = "accrual-basis accounting only / accrual-basis";
arrAnsChoices[3] = "accrual-basis accounting only / cash-basis";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445416;
arrAnsIDs[1] = 445417;
arrAnsIDs[2] = 445418;
arrAnsIDs[3] = 445419;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that accounting regulations generally mandate the use of accrual-basis<b> </b>accounting for financial reporting purposes. Although the realization principle and the matching principle apply under accrual-basis accounting, <b>neither </b>the realization principle <b>nor </b>the matching principle applies under <b>cash-basis </b>accounting.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Although the realization principle and the matching principle apply under accrual-basis accounting, <b>neither</b> the realization principle <b>nor </b>the matching principle applies under <b>cash-basis </b>accounting. In addition, accounting regulations generally mandate the use of <b>accrual-basis </b>accounting for financial reporting purposes.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Under accrual-basis accounting, a company records revenues when they are earned and expenses when they are incurred, even if the company has not yet received the revenues or paid the expenses. Revenues are recorded according to the realization principle and expenses according to the matching principle.</p><p class=\"explanations\">Under cash-basis accounting, a company recognizes revenues or expenses only when it receives cash or disburses cash. In contrast, under accrual-basis accounting, a company’s financial statements must report cash and non-cash transactions—such as purchases on account—that occur during the accounting period.</p><p class=\"explanations\"><b>Learning Objective: 3D. Distinguish between accrual-basis accounting and cash-basis accounting.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that the realization principle and the matching principle apply under accrual-basis accounting only. However, accounting regulations generally mandate the use of <b>accrual-basis </b>accounting for financial reporting purposes.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_024'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_025';
objQuestion.questionID = 110211;
objQuestion.item = 'LOMA_361_PPQ2019_025';
objQuestion.primaryLO = '3D';
objQuestion.textref = 'c. 3, pp. 18-19';
objQuestion.textbook = 0;
objQuestion.chapter = 3;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '3D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statement(s) can correctly be made about cash-basis accounting and accrual-basis accounting:</p><ol type=\"A\" class=\"combo\"><li>Cash receipts and cash disbursements are the most important components under cash-basis accounting.</li><li>The purpose of accrual-basis accounting is to record a business transaction when a company incurs a financial obligation or expects to receive a payment.</li><li>Companies that use cash-basis accounting generally must also make adjusting entries to their accounting records at the end of each accounting period to record pending revenues or expenses.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A, B, and C";
arrAnsChoices[1] = "A and B only";
arrAnsChoices[2] = "A and C only";
arrAnsChoices[3] = "B and C only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445420;
arrAnsIDs[1] = 445421;
arrAnsIDs[2] = 445422;
arrAnsIDs[3] = 445423;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct. Under cash-basis accounting, a company records a cash receipt in the same accounting period in which it receives the cash and a cash disbursement in the same accounting period in which it remits payment. Cash-basis accounting provides an accurate summary of a company’s current cash flows, but does not provide accurate a picture of that company’s obligations or income in the immediate future, which may be significant. Today, accounting software makes it much easier for insurers to maintain their accounting records simultaneously on both a cash basis and an accrual basis.</p><p class=\"explanations\">Statement B is correct. Accrual-basis accounting enables interested users of a company’s financial information to view the consequences of a company’s activities, including the company’s earning potential and financial performance. For this reason, accrual-basis accounting is generally regarded as relevant, compared to cash-basis accounting.</p><p class=\"explanations\">Statement C is incorrect. Generally, companies that use accrual-basis also must make adjusting entries to their accounting records at the end of each accounting period to match revenues and expenses in their financial statements for that accounting period. In a pure cash-basis system, a company makes no accounting entries to record pending revenues or expenses or non-cash transactions. Instead, the company calculates its net income by subtracting paid expenses from received revenues.</p><p class=\"explanations\"><b>Learning Objective: 3D. Distinguish between accrual-basis accounting and cash-basis accounting.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement A is correct; however, Statement C is incorrect.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Statement B is correct; however, Statement C is incorrect.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_025'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['3A'] = "3A. Explain two key financial statement concepts—the entity concept and the going-concern concept.";
arrlotext['3B'] = "3B. Demonstrate an understanding of the qualitative characteristics of accounting information and the key concepts that guide account maintenance.";
arrlotext['3C'] = "3C. Describe the realization principle and the matching principle in accrual-basis accounting.";
arrlotext['3D'] = "3D. Distinguish between accrual-basis accounting and cash-basis accounting.";
