var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2019';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 361 Practice Questions, Chapter 2";
var coursename = 'LOMA 361';
var modulenumber = 1;
var title = "LOMA_361_PPQ2019_0_2";
var intNumPools = 1;
var numQ = 9;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Accounting and Financial Reporting in Life Insurance Companies, Second Edition (2019)";
arrNumChap[0] = 1;
var thisChap = '2';

objPool = new Object(); 
objPool.intSelectCount = 9;
objPool.formID = 2103;
objPool.formName = 'PPQ2019_0_2';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_361_PQ_009';
arrPoolQuestions[1] = 'LOMA_361_PQ_010';
arrPoolQuestions[2] = 'LOMA_361_PQ_011';
arrPoolQuestions[3] = 'LOMA_361_PQ_012';
arrPoolQuestions[4] = 'LOMA_361_PQ_013';
arrPoolQuestions[5] = 'LOMA_361_PQ_014';
arrPoolQuestions[6] = 'LOMA_361_PQ_015';
arrPoolQuestions[7] = 'LOMA_361_PQ_016';
arrPoolQuestions[8] = 'LOMA_361_PQ_017';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_009';
objQuestion.questionID = 110195;
objQuestion.item = 'LOMA_361_PPQ2019_009';
objQuestion.primaryLO = '2A';
objQuestion.textref = 'c. 2, p. 2';
objQuestion.textbook = 0;
objQuestion.chapter = 2;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '2A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">An insurance company typically maintains a numbered or alphabetical list of all the company’s account names. By definition, this list is known as</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "an accounting entry";
arrAnsChoices[1] = "a journal entry";
arrAnsChoices[2] = "a source document";
arrAnsChoices[3] = "a chart of accounts";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445355;
arrAnsIDs[1] = 445356;
arrAnsIDs[2] = 445357;
arrAnsIDs[3] = 445358;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">An accounting entry, also called a journal entry, is a record of a business transaction that includes at least one debit and one credit and shows the monetary value of the transaction in balance.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A journal entry is another name for an accounting entry, which is a record of a business transaction that includes at least one debit and one credit and shows the monetary value of the transaction in balance.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Source documents are the various business papers and electronic forms that contain original information about a company’s business transactions that verify that a business transaction occurred. These documents include details, such as the transaction date, monetary amount, and who approved the transaction.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Developing and maintaining the chart of accounts is typically under the controller’s span of control. Account titles and numbering schemes vary from insurer to insurer.</p><p class=\"explanations\"><b>Learning Objective: 2A. List and describe the five major account classifications in the context of the basic accounting equation.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_009'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_010';
objQuestion.questionID = 110196;
objQuestion.item = 'LOMA_361_PPQ2019_010';
objQuestion.primaryLO = '2A';
objQuestion.textref = 'c. 2, pp. 3-4';
objQuestion.textbook = 0;
objQuestion.chapter = 2;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '2A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Dulcimer Life Insurance Company listed the following assets on its balance sheet:</p><ul class=\"examul\"><li>Cash equivalents = $150,000</li><li>Real estate = $300,000</li><li>Treasury bills = $100,000</li><li>Cash = $500,000</li><li>Equipment = $80,000</li></ul><p class=\"stem\">This information indicates that Dulcimer’s total short-term assets are equal to</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "$500,000";
arrAnsChoices[1] = "$600,000";
arrAnsChoices[2] = "$650,000";
arrAnsChoices[3] = "$750,000";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445359;
arrAnsIDs[1] = 445360;
arrAnsIDs[2] = 445361;
arrAnsIDs[3] = 445362;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that Dulcimer’s short-term assets include cash. However, cash is <b>not</b> the only short-term asset on Dulcimer’s balance sheet.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that Dulcimer’s short-term assets include Treasury bills and cash. However, these assets are <b>not</b> the only short-term assets on Dulcimer’s balance sheet.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that Dulcimer’s short-term assets include cash and cash equivalents. However, these assets are <b>not</b> the only short-term assets on Dulcimer’s balance sheet.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Short-term assets, also called current assets, are assets that a company expects to readily convert into cash or consume within the current accounting period, typically one year. Short-term assets generally have high liquidity. Examples of short-term assets include cash, cash equivalents, and Treasury bills. In this situation, Dulcimer’s total short-term assets are equal to $150,000 + $100,000 + $500,000 = $750,000.</p><p class=\"explanations\">Long-term assets, also called noncurrent assets, are assets that a company plans to hold indefinitely or for a long time—generally longer than one year—to generate income. Compared to short-term assets, long-term assets usually take longer to convert to cash and are generally illiquid (the opposite of liquid). Examples of long-term assets include equipment and real estate.</p><p class=\"explanations\"><b>Learning Objective: 2A. List and describe the five major account classifications in the context of the basic accounting equation.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_010'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_011';
objQuestion.questionID = 110197;
objQuestion.item = 'LOMA_361_PPQ2019_011';
objQuestion.primaryLO = '2A';
objQuestion.textref = 'c. 2, pp. 4-5';
objQuestion.textbook = 0;
objQuestion.chapter = 2;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '2A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Liabilities represent the monetary value of a company’s current and future obligations. An insurer’s liabilities consist <i>primarily</i> of</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "agent commissions payable";
arrAnsChoices[1] = "contractual reserves for future obligations";
arrAnsChoices[2] = "bonds that an insurer issues";
arrAnsChoices[3] = "the insurer’s investments that are available for sale";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445363;
arrAnsIDs[1] = 445364;
arrAnsIDs[2] = 445365;
arrAnsIDs[3] = 445366;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Although agent commissions payable is a significant liability for insurers, an insurer’s liabilities do <b>not</b> consist primarily of agent commissions payable, which is a short-term liability for insurers.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">An insurer’s contractual reserves for future obligations are the amounts it expects to pay its policyowners, annuity contract owners, and beneficiaries. An insurer’s investments that are available for sale are assets.</p><p class=\"explanations\">Insurers may categorize their liabilities as either short term or long term. Short-term liabilities, also called current liabilities, are financial obligations that a company must pay in one year or less. Long-term liabilities, also called noncurrent liabilities, are liabilities that a company does not have to pay in full during the current accounting period—usually one year. For an insurer, agent commissions payable is a short-term liability; bonds that the insurer issues—rather than purchases—are a long-term liability.</p><p class=\"explanations\"><b>Learning Objective: 2A. List and describe the five major account classifications in the context of the basic accounting equation.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">An insurer’s liabilities do <b>not</b> consist primarily of bonds issued by the insurer. For an insurer, bonds that the insurer issues—rather than purchases—are an example of a long-term liability.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">An insurer’s investments that are available for sale are assets, <b>not</b> liabilities. Investments may be tangible (physical), such as real estate, or intangible (not physical), such as securities, which include bonds and stocks that an insurer owns and that are available for sale.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_011'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_012';
objQuestion.questionID = 110198;
objQuestion.item = 'LOMA_361_PPQ2019_012';
objQuestion.primaryLO = '2A';
objQuestion.textref = 'c. 2, p. 5';
objQuestion.textbook = 0;
objQuestion.chapter = 2;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '2A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about the account classification known as owners’ equity. Select the answer choice containing the correct statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Owners’ equity represents all owner investments—which are residual claims against a company’s assets—in the company.";
arrAnsChoices[1] = "A company’s owners’ equity is the sum of the company’s assets and its liabilities.";
arrAnsChoices[2] = "Mutual insurers and fraternal insurers have no <i>Surplus</i> accounts on their balance sheets.";
arrAnsChoices[3] = "Under statutory accounting principles (SAP), the capital portion of owners’ equity is defined as the cumulative monetary amount that remains in the company over time.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445367;
arrAnsIDs[1] = 445368;
arrAnsIDs[2] = 445369;
arrAnsIDs[3] = 445370;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">If a company goes out of business, its owners—that is, the stockholders of a stock insurer or the policyowners of a mutual insurer or fraternal insurer—are entitled to whatever remains of the company’s assets after all creditor claims and policyowner claims have been paid. In this sense, owners’ equity is the difference between a company’s assets and its liabilities in the basic accounting equation.</p><p class=\"explanations\">Sometimes, insurance companies replace the term owners’ equity with capital and surplus. Because mutual insurers and fraternal insurers do not have stockholders, they have do not have capital accounts. Therefore, they replace the term owners’ equity with surplus in the basic accounting equation.</p><p class=\"explanations\"><b>Learning Objective: 2A. List and describe the five major account classifications in the context of the basic accounting equation.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The amount of a company’s owners’ equity is the <b>difference </b>between the company’s assets and its liabilities: Owners’ Equity = Assets – Liabilities.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Because mutual insurers and fraternal insurers do not have stockholders, they do <b>not</b> have capital accounts. Thus, for mutual insurers and fraternal insurers, <b>surplus</b> (not capital and surplus) is the difference<b> </b>between an insurer’s assets and its liabilities: Surplus = Assets – Liabilities.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">To comply with statutory financial reporting requirements, insurance companies use the <i>Surplus</i> account. <b>Surplus</b> is the cumulative amount of money—calculated as an insurance company’s assets minus its liabilities and capital—that remains in the company over time. Stock insurers use the <i>Retained Earnings</i> account instead of the <i>Surplus</i> account when preparing GAAP financial reports.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_012'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_013';
objQuestion.questionID = 110199;
objQuestion.item = 'LOMA_361_PPQ2019_013';
objQuestion.primaryLO = '2A';
objQuestion.textref = 'c. 2, pp. 6-7';
objQuestion.textbook = 0;
objQuestion.chapter = 2;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '2A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Expenses, also known as costs, are the amounts that a company spends in the course of conducting business. The act of paying a policy claim <b>(increases / decreases)</b> the insurer’s cash. Any money that results from an excess of the insurer’s total revenues over its total expenses during a specified period is known as <b>(a net loss / net income)</b>.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "increases / a net loss";
arrAnsChoices[1] = "increases / net income";
arrAnsChoices[2] = "decreases / a net loss";
arrAnsChoices[3] = "decreases / net income";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445371;
arrAnsIDs[1] = 445372;
arrAnsIDs[2] = 445373;
arrAnsIDs[3] = 445374;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The act of paying a policy claim <b>decreases</b> the insurer’s cash. Also, if total revenues exceed total expenses, then the result is <b>net income</b>.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that, if total revenues exceed total expenses, then the result is net income. However, the act of paying a policy claim <b>decreases</b> the insurer’s cash.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that the act of paying a policy claim decreases the insurer’s cash. However, if total revenues exceed total expenses, then the result is <b>net income</b>.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Expenses are a necessary part of doing business, because an insurer cannot generate revenues without incurring expenses. Typical insurer expenses include investment expenses, contractual benefit expenses, and operating expenses. Unlike revenues, which ultimately increase a company’s assets, expenses ultimately decrease the company assets. For example, the act of paying a policy claim (an expense) decreases cash (an asset).</p><p class=\"explanations\">The relationship between an insurer’s revenues and expenses determines the insurer’s net income or net loss. Net income, or net profit, is any money that results from an excess of total revenues over total expenses during a specified period. For example, a net loss is the amount of a company’s total expenses that exceeds its total revenues during a specified period.</p><p class=\"explanations\"><b>Learning Objective: 2A. List and describe the five major account classifications in the context of the basic accounting equation.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_013'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_014';
objQuestion.questionID = 110200;
objQuestion.item = 'LOMA_361_PPQ2019_014';
objQuestion.primaryLO = '2A';
objQuestion.textref = 'c. 2, pp. 8-10';
objQuestion.textbook = 0;
objQuestion.chapter = 2;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '2A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Oxeye Mutual Life Insurance Company is a mutual insurance company. The basic accounting equation for Oxeye and other mutual insurance companies is correctly expressed as</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Assets = Liabilities + Surplus";
arrAnsChoices[1] = "Assets = Liabilities + Capital";
arrAnsChoices[2] = "Owners’ Equity = Assets + Liabilities";
arrAnsChoices[3] = "Assets = Liabilities – Surplus";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445375;
arrAnsIDs[1] = 445376;
arrAnsIDs[2] = 445377;
arrAnsIDs[3] = 445378;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The basic accounting equation, sometimes called the balance sheet equation, expresses the relationship among the three key account classifications that a company reports on its balance sheet: Assets = Liabilities + Owners’ Equity. At the end of an accounting period, the insurer closes out all revenue accounts and expense accounts on the income statement and transfers the net income or net loss for the accounting period to the <i>Owners’ Equity</i> account on the balance sheet. Therefore, the basic accounting equation can be expanded to include an insurer’s revenues and expenses: Assets = Liabilities + Owners’ Equity + (Revenues – Expenses).</p><p class=\"explanations\">For stock insurance companies, Capital and Surplus can be substituted for Owners’ Equity in the basic accounting equation: Assets = Liabilities + Capital and Surplus. Because mutual insurers and fraternal insurers have no capital accounts, the basic accounting equation for these types of insurers can be simplified as follows: Assets = Liabilities + Surplus.</p><p class=\"explanations\"><b>Learning Objective: 2A. List and describe the five major account classifications in the context of the basic accounting equation.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Mutual insurers and fraternal insurers do <b>not</b> have capital accounts. Therefore, the basic accounting equation: Assets = Liabilities + Capital and Surplus, can be simplified for mutual insurers and fraternal insurers as: Assets = Liabilities + Surplus.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The basic accounting equation, sometimes called the balance sheet equation, is the formula that expresses the relationship among the three key account classifications that a company reports on its balance sheet: <b>Assets = Liabilities + Owners’ Equity</b>.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The basic accounting equation, sometimes called the balance sheet equation, is the formula that expresses the relationship among the three key account classifications that a company reports on its balance sheet: <b>Assets = Liabilities + Owners’ Equity</b>.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_014'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_015';
objQuestion.questionID = 110201;
objQuestion.item = 'LOMA_361_PPQ2019_015';
objQuestion.primaryLO = '2B';
objQuestion.textref = 'c. 2, pp. 11-13';
objQuestion.textbook = 0;
objQuestion.chapter = 2;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '2B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">In accounting terminology, funds flowing into a company are a source of funds and funds flowing out of the company are a use of funds. Typical <i>sources of funds</i> for an insurance company include</p><ol type=\"A\" class=\"combo\"><li>Premium income</li><li>Policy dividends</li><li>Agent commissions</li><li>Investment income</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A, B, and D only";
arrAnsChoices[1] = "A and D only";
arrAnsChoices[2] = "B and C only";
arrAnsChoices[3] = "A only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445379;
arrAnsIDs[1] = 445380;
arrAnsIDs[2] = 445381;
arrAnsIDs[3] = 445382;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that premium income and investment income are typical sources of funds for an insurance company. However, paying policy dividends is a typical <b>use of funds</b>.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Typical sources of funds for an insurer are the revenues—premium income, investment income, and fee income—generated from the insurer’s core business activities. An insurer’s primary uses of funds include paying current contractual benefits; paying policy dividends; and paying various operating expenses, such as agent commissions and salaries, taxes, licenses, and fees.</p><p class=\"explanations\"><b>Learning Objective: 2B. Describe the operating cycle and identify the primary sources and uses of funds for a life insurance company.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Paying policy dividends and agent commissions are typical <b>uses of funds</b> for an insurance company.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that premium income is a typical source of funds for an insurance company. However, it is not the only typical source of funds.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_015'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_016';
objQuestion.questionID = 110202;
objQuestion.item = 'LOMA_361_PPQ2019_016';
objQuestion.primaryLO = '2C';
objQuestion.textref = 'c. 2, pp. 17-18';
objQuestion.textbook = 0;
objQuestion.chapter = 2;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '2C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">A closing entry can correctly be defined as an accounting entry that an insurer makes to</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "transfer its net income or net loss for a given period to a revenue account or an expense account";
arrAnsChoices[1] = "start the next accounting period with a zero balance in its temporary accounts";
arrAnsChoices[2] = "record accruals for revenues and expenses, unearned revenues, and prepaid expenses";
arrAnsChoices[3] = "record a business transaction in which the debit amounts are greater than the credit amounts";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445383;
arrAnsIDs[1] = 445384;
arrAnsIDs[2] = 445385;
arrAnsIDs[3] = 445386;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A company makes a closing entry at the end of each accounting period to start the next accounting period with a zero balance in its temporary accounts. Temporary accounts, also called nominal accounts, are income statement accounts— revenue accounts and expense accounts—that are closed out to a permanent account at the end of the accounting period and have a <b>zero balance</b> at the beginning of the next period.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">In accounting, accounts are either permanent or temporary. Permanent accounts are balance sheet accounts—asset accounts, liability accounts, and owners’ equity accounts—that have a balance at the beginning of each accounting period. Temporary accounts, also called nominal accounts, are income statement accounts— revenue account and expense accounts—that are closed out to a permanent account at the end of each accounting period and have a zero balance at the beginning of the next period.</p><p class=\"explanations\">Revenues and expenses must be closed out at the end of each accounting period because a revenue earned or an expense incurred in one period pertains only to that period. Therefore, it cannot also be a revenue or an expense in another accounting period. Insurers use closing entries to move the balances in their temporary accounts to permanent accounts at the end of each accounting period. Most temporary accounts are closed out to an owners’ equity account, such as <i>Retained Earnings</i> (GAAP) or <i>Surplus</i> (SAP).</p><p class=\"explanations\"><b>Learning Objective: 2C. Differentiate between permanent accounts and temporary accounts and identify the normal balances for the five major account classifications.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A company makes an <b>adjusting entry</b> to record accruals for revenues and expenses, unearned revenues, and prepaid expenses. Accruals allow an insurer to record expenses incurred but not yet paid and to record revenues earned but not yet received. Other adjusting entries include depreciation, changes made to reserve accounts, and corrections to previous accounting periods. These adjusting entries typically apply to transactions for which a company has knowledge but lacks the appropriate source documents.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">All companies, including insurance companies, use double-entry accounting to record business transactions in their accounting systems. With double-entry accounting, every accounting entry must (1) have at least one debit and one credit, (2) have an <b>equal monetary amount of debits and credits</b>, and (3) maintain the balance of the basic accounting equation. The cornerstone of double-entry accounting is the <b>dual concept</b>, which states that every business transaction has two aspects—<b>debits and credits</b>—that <b>always</b> <b>equal</b> each<b> </b>other in monetary amount.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_016'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_017';
objQuestion.questionID = 110203;
objQuestion.item = 'LOMA_361_PPQ2019_017';
objQuestion.primaryLO = '2C';
objQuestion.textref = 'c. 2, pp. 21-22';
objQuestion.textbook = 0;
objQuestion.chapter = 2;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '2C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">In accounting, an account’s normal balance is the side of the account, either debit or credit, to which increases to the account are recorded. Select the answer choice that correctly identifies a major account classification that has a normal debit balance and a major account classification that has a normal credit balance at the end of the accounting period.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[-1] = "<u>Normal debit balance</u></div><div class=\"anshead\"><u>Normal credit balance</u>";
arrAnsChoices[0] = "expense</div><div class=\"anscell\" onclick=\"recordAns(1);\">revenue";
arrAnsChoices[1] = "expense</div><div class=\"anscell\" onclick=\"recordAns(2);\">asset";
arrAnsChoices[2] = "asset</div><div class=\"anscell\" onclick=\"recordAns(3);\">expense";
arrAnsChoices[3] = "liability</div><div class=\"anscell\" onclick=\"recordAns(4);\">asset";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445388;
arrAnsIDs[1] = 445389;
arrAnsIDs[2] = 445390;
arrAnsIDs[3] = 445391;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Because increases are recorded as debits to both assets and expenses, these accounts typically have a normal debit balance. Because increases are recorded as credits to liabilities, owners’ equity, and revenues, these accounts typically have a normal credit balance.</p><p class=\"explanations\">Use the expanded basic accounting equation to recall an account’s normal balance: Assets = Liabilities + Owners’ Equity + Revenues – Expenses. Add Expenses to both sides of the expanded basic accounting equation: Assets + Expenses = Liabilities + Owners’ Equity + Revenues. Accounts to the left of the equal sign have a normal debit balance; accounts to the right of the equal sign have a normal credit balance.</p><p class=\"explanations\"><b>Learning Objective: 2C. Differentiate between permanent accounts and temporary accounts and identify the normal balances for the five major account classifications.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that expense accounts typically have a normal debit balance at the end of the accounting period. However, asset accounts also typically have a normal <b>debit </b>balance at the end of the accounting period.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that asset accounts typically have a normal debit balance at the end of the accounting period. However, expense accounts also typically have a normal <b>debit </b>balance at the end of the period.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Liability accounts typically have a normal <b>credit </b>balance at the end of the accounting period. In addition, asset accounts typically have a normal <b>debit</b> balance at the end of the accounting period.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_017'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['2A'] = "2A. List and describe the five major account classifications in the context of the basic accounting equation.";
arrlotext['2B'] = "2B. Describe the operating cycle and identify the primary sources and uses of funds for a life insurance company.";
arrlotext['2C'] = "2C. Differentiate between permanent accounts and temporary accounts and identify the normal balances for the five major account classifications.";
