var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2019';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 361 Practice Questions, Chapter 4";
var coursename = 'LOMA 361';
var modulenumber = 1;
var title = "LOMA_361_PPQ2019_0_4";
var intNumPools = 1;
var numQ = 8;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Accounting and Financial Reporting in Life Insurance Companies, Second Edition (2019)";
arrNumChap[0] = 1;
var thisChap = '4';

objPool = new Object(); 
objPool.intSelectCount = 8;
objPool.formID = 2103;
objPool.formName = 'PPQ2019_0_4';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_361_PQ_026';
arrPoolQuestions[1] = 'LOMA_361_PQ_027';
arrPoolQuestions[2] = 'LOMA_361_PQ_028';
arrPoolQuestions[3] = 'LOMA_361_PQ_029';
arrPoolQuestions[4] = 'LOMA_361_PQ_030';
arrPoolQuestions[5] = 'LOMA_361_PQ_031';
arrPoolQuestions[6] = 'LOMA_361_PQ_032';
arrPoolQuestions[7] = 'LOMA_361_PQ_033';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_026';
objQuestion.questionID = 110212;
objQuestion.item = 'LOMA_361_PPQ2019_026';
objQuestion.primaryLO = '4A';
objQuestion.textref = 'c. 4, pp. 4-5; c. 2, pp. 8-10';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '2A';
arrLOs[1] = '4A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = 1;
objQuestion.strStem = "<p class=\"stem\">According to the basic accounting equation, on December 31, Montage’s owners’ equity was equal to</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "$54 million";
arrAnsChoices[1] = "$192 million";
arrAnsChoices[2] = "$218 million";
arrAnsChoices[3] = "$408 million";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445424;
arrAnsIDs[1] = 445425;
arrAnsIDs[2] = 445426;
arrAnsIDs[3] = 445427;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">According to the basic accounting equation, the monetary amount of an insurer’s total assets must equal the combined monetary amounts of its total liabilities and total owners’ equity: Assets = Liabilities + Owners’ Equity. Therefore, Montage’s owners’ equity is equal to the difference between its assets and its liabilities: Assets – Liabilities = Owners’ Equity = $300 million – $108 million = $192 million.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">According to the basic accounting equation, the monetary amount of an insurer’s total assets must equal the combined monetary amounts of its total liabilities and total owners’ equity: Assets = Liabilities + Owners’ Equity. Therefore, Montage’s owners’ equity is equal to the difference between its assets and its liabilities: Assets – Liabilities = Owners’ Equity = $300 million – $108 million = $192 million.</p><p class=\"explanations\"><b>Learning Objective: (1) 4A. Describe an insurer’s key financial statements and list the account classifications that appear on each financial statement; (2) 2A. List and describe the five major account classifications in the context of the basic accounting equation.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">According to the basic accounting equation, the monetary amount of an insurer’s total assets must equal the combined monetary amounts of its total liabilities and total owners’ equity: Assets = Liabilities + Owners’ Equity. Therefore, Montage’s owners’ equity is equal to the difference between its assets and its liabilities: Assets – Liabilities = Owners’ Equity = $300 million – $108 million = $192 million.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">According to the basic accounting equation, the monetary amount of an insurer’s total assets must equal the combined monetary amounts of its total liabilities and total owners’ equity: Assets = Liabilities + Owners’ Equity. Therefore, Montage’s owners’ equity is equal to the difference between its assets and its liabilities: Assets – Liabilities = Owners’ Equity = $300 million – $108 million = $192 million.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_026'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_027';
objQuestion.questionID = 110213;
objQuestion.item = 'LOMA_361_PPQ2019_027';
objQuestion.primaryLO = '4A';
objQuestion.textref = 'c. 4, pp. 5-6; c. 2, pp. 6-7';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '2A';
arrLOs[1] = '4A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = 1;
objQuestion.strStem = "<p class=\"stem\">This information indicates that Montage’s year-end income statement showed that Montage experienced</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "net income of $26 million";
arrAnsChoices[1] = "a net loss of $26 million";
arrAnsChoices[2] = "net income of $54 million";
arrAnsChoices[3] = "a net loss of $54 million";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445428;
arrAnsIDs[1] = 445429;
arrAnsIDs[2] = 445430;
arrAnsIDs[3] = 445431;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The income statement shows whether a life insurer is profitable. For a specific accounting period, an insurer experiences either net income—Net Income = Total Revenues > Total Expenses—or a net loss—Net Loss = Total Revenues < Total Expenses. In this situation, Montage experienced net income because its total revenues exceeded its total expenses: $40 million – $14 million = $26 million.</p><p class=\"explanations\"><b>Learning Objective: (1) 4A. Describe an insurer’s key financial statements and list the account classifications that appear on each financial statement; (2) 2A. List and describe the five major account classifications in the context of the basic accounting equation.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The income statement shows whether a life insurer is profitable. For a specific accounting period, an insurer experiences either net income—Net Income = Total Revenues > Total Expenses—or a net loss—Net Loss = Total Revenues < Total Expenses. In this situation, Montage experienced net income because its total revenues exceeded its total expenses: $40 million – $14 million = $26 million.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The income statement shows whether a life insurer is profitable. For a specific accounting period, an insurer experiences either net income—Net Income = Total Revenues > Total Expenses—or a net loss—Net Loss = Total Revenues < Total Expenses. In this situation, Montage experienced net income because its total revenues exceeded its total expenses: $40 million – $14 million = $26 million.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The income statement shows whether a life insurer is profitable. For a specific accounting period, an insurer experiences either net income—Net Income = Total Revenues > Total Expenses—or a net loss—Net Loss = Total Revenues < Total Expenses. In this situation, Montage experienced net income because its total revenues exceeded its total expenses: $40 million – $14 million = $26 million.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_027'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_028';
objQuestion.questionID = 110214;
objQuestion.item = 'LOMA_361_PPQ2019_028';
objQuestion.primaryLO = '4A';
objQuestion.textref = 'c. 4, pp. 3-4, 14-15';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '4A';
arrLOs[1] = '4C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">One key financial statement shows a company’s financial condition or position by summarizing the company’s assets, liabilities, and owners’ equity as of a specified date. By definition, this financial statement is known as</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "an income statement, which is considered to be a static report";
arrAnsChoices[1] = "an income statement, which is considered to be a dynamic report";
arrAnsChoices[2] = "a balance sheet, which is considered to be a static report";
arrAnsChoices[3] = "a balance sheet, which is considered to be a dynamic report";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445432;
arrAnsIDs[1] = 445433;
arrAnsIDs[2] = 445434;
arrAnsIDs[3] = 445435;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">An income statement is a financial statement that reports an insurer’s <b>revenues and expenses</b> during a specified accounting period and indicates whether the insurer experienced net income or a net loss during that period. Also, the income statement is considered to be a <b>dynamic</b> report because it presents the flow of a company’s transactions during a specified accounting period, rather than as of a specified date.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that an income statement is considered to be a dynamic report. However, an income statement is a financial statement that reports an insurer’s <b>revenues and expenses</b> during a specified accounting period and indicates whether the insurer experienced net income or a net loss during that period.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The balance sheet shows a user what a life insurer owns (its assets), what it owes (its liabilities), and what it has retained (its owners’ equity). A company’s balance sheet is considered to be a static report because it provides a “snapshot” of the company’s financial position as of a specified date.</p><p class=\"explanations\">A company’ interested users examine the income statement to identify how an insurer is earning funds (its revenues), as well as how it is spending them (its expenses). The income statement, cash flow statement, and statement of owners’ equity are considered to be dynamic reports because they present the flow of a company’s transactions during a specified accounting period, rather than as of a specified date.</p><p class=\"explanations\"><b>Learning Objectives: (1) 4A. Describe an insurer’s key financial statements and list the account classifications that appear on each financial statement; (2) 4C. Distinguish between static and dynamic financial statements and describe the relationships among the financial statements.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that the financial statement described is a balance sheet. However, a balance sheet is considered to be a <b>static</b> report of the company’s financial condition because it provides a “snapshot” of the company’s financial position as of a specified date. A dynamic report presents the <b>movement or flow</b> of a company’s financial transactions during a specified accounting period, rather than as of a specified date.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_028'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_029';
objQuestion.questionID = 110215;
objQuestion.item = 'LOMA_361_PPQ2019_029';
objQuestion.primaryLO = '4A';
objQuestion.textref = 'c. 4, pp. 6-8';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '4A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements can correctly be made about the statement of comprehensive income:</p><ol type=\"A\" class=\"combo\"><li>According to the FASB, under U.S. GAAP, a life insurer has two options for reporting unrealized capital gains and losses on its invested assets: (1) in its income statement or (2) in a separate statement of comprehensive income, which immediately follows the insurer’s income statement.</li><li>Comprehensive income (CI) is the total change in equity for a reporting period, excluding changes resulting from investments by owners and distributions to owners.</li><li>Because other comprehensive income (OCI) is not reported on an insurer’s income statement, it is not included in the calculation of the insurer’s net income.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A, B, and C";
arrAnsChoices[1] = "A and B only";
arrAnsChoices[2] = "A and C only";
arrAnsChoices[3] = "B and C only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445436;
arrAnsIDs[1] = 445437;
arrAnsIDs[2] = 445438;
arrAnsIDs[3] = 445439;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Statement A is correct. Life insurers can have substantial capital gains and losses on their invested assets, and these capital gains and losses can be categorized as either realized or unrealized. Realized capital gains and losses on invested assets must be reported on an insurer’s GAAP income statement.</p><p class=\"explanations\">Statement B is correct. CI, which measures the changes in equity that result from non-owner transactions, is the sum of net income and other items—known as other comprehensive income (OCI)—that are not reported on the income statement because they have not been realized: CI = Net income + OCI.</p><p class=\"explanations\">Statement C is correct. Components of OCI generally come from non-core business operations and onetime or unusual transactions. Examples of OCI include unrealized capital gains and losses on certain investments, gains and losses resulting from translating the financial statements of foreign subsidiaries, and actuarial gains and losses related to pensions and other postretirement benefits. If these components were added to net income, the resulting amount could present an inaccurate view of an insurer’s operating performance. To prevent this result, OCI accumulates on the statement of owners’ equity in a section called “accumulated other comprehensive income” or “AOCI.”</p><p class=\"explanations\"><b>Learning Objective: 4A. Describe an insurer’s key financial statements and list the account classifications that appear on each financial statement.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A and Statement B are correct; however, Statement C is also correct.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement A and Statement C are correct; however, Statement B is also correct.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Statement B and Statement C are correct; however, Statement A is also correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_029'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_030';
objQuestion.questionID = 110216;
objQuestion.item = 'LOMA_361_PPQ2019_030';
objQuestion.primaryLO = '4A';
objQuestion.textref = 'c. 4, p. 8';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '4A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">One important financial statement prepared by insurers is the cash flow statement. The primary purpose of the cash flow statement is to</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "show changes in the insurer’s equity that resulted from changes in net income and surplus";
arrAnsChoices[1] = "indicate whether the insurer has experienced a net loss or net income during an accounting period";
arrAnsChoices[2] = "provide information about changes in the insurer’s owners’ equity accounts between two sequential balance sheets";
arrAnsChoices[3] = "demonstrate how a company manages its cash over time";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445440;
arrAnsIDs[1] = 445441;
arrAnsIDs[2] = 445442;
arrAnsIDs[3] = 445443;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">This answer choice describes the primary purpose of a <b>statement of policyholders’ equity</b>, also called a statement of policyowners’ equity, which is prepared by mutual insurers and fraternal insurers for their customers. Because they do not issue common stock, mutual insurers and fraternal insurers typically experience changes in owners’ equity only as a result of changes in net income and surplus.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">This answer choice describes the primary purpose of an <b>income statement</b>, which reports an insurer’s revenues and expenses during a specified accounting period and indicates whether the insurer experienced net income or a net loss during that period.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">This answer choice describes the primary purpose of a <b>statement of owners’ equity</b>. Stock insurers typically refer to the statement of owners’ equity as the statement of stockholders’ equity.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A cash flow statement, also called a statement of cash flows, is a dynamic financial statement that shows a company’s cash receipts, cash disbursements, and the net change in cash during a specified accounting period. It provides information about a company’s change in cash between the company’s current balance sheet and its previous balance sheet.</p><p class=\"explanations\"><b>Learning Objective: 4A. Describe an insurer’s key financial statements and list the account classifications that appear on each financial statement.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_030'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_031';
objQuestion.questionID = 110217;
objQuestion.item = 'LOMA_361_PPQ2019_031';
objQuestion.primaryLO = '4B';
objQuestion.textref = 'c. 4, pp. 10-11';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '4B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Last year, the Cooper Life Insurance Company experienced cash flows from the following activities:</p><ul class=\"examul\"><li><b>Activity A</b>—Cooper received $23 million in premium income and paid $18 million in contractual benefits.</li><li><b>Activity B</b>—Cooper paid $110,000 in cash dividends to stockholders.</li><li><b>Activity C</b>—Cooper received $195,000 of principal on loan repayments.</li><li><b>Activity D</b>—Cooper purchased $237,000 of bonds.</li></ul><p class=\"stem\">Changes in an insurer’s cash inflows and cash outflows occur as a result of three activities: operating activities, investing activities, and financing activities. With regard to Cooper’s activities, the activity that represents a cash <i>outflow</i> from an <i>investing</i> activity is</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Activity A";
arrAnsChoices[1] = "Activity B";
arrAnsChoices[2] = "Activity C";
arrAnsChoices[3] = "Activity D";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445444;
arrAnsIDs[1] = 445445;
arrAnsIDs[2] = 445446;
arrAnsIDs[3] = 445447;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Activity A represents a <b>cash inflow</b> from <b>operating activities</b>. Operating activities are transactions that involve a company’s core business operations and that directly determine the company’s net income. In Activity A, Cooper’s cash inflow of premium income exceeded the cash outflow of contractual benefit payments, resulting in a $5 million net cash inflow from operating activities.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that Activity B represents a cash outflow; however, this cash outflow resulted from a <b>financing activity</b>. Financing activities are transactions that involve borrowed funds and cash payments to or from a company’s owners—Cooper’s stockholders, in this situation. In Activity B, cash dividends to Cooper’s stockholders resulted in a $110,000 cash outflow from a financing activity.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that Activity C represents an investing activity; however, this investing activity is a <b>cash inflow</b>, a movement of cash into an organization, which includes the receipt of an amount of principal on a loan repayment. In Activity C, Cooper received a loan repayment, which resulted in a $195,000 cash inflow from investing activities.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A cash flow is any movement of cash into or out of an organization. In the context of accounting, a cash inflow is a movement of cash into an organization; cash inflows are sources of funds. Examples include premium income, investment income, and fee income. A cash outflow is a movement of cash out of an organization; cash outflows are uses of funds. Examples include payments for contractual policy benefits, ongoing business expenses, and investment purchases, such as Cooper’s bond purchase in Activity D.</p><p class=\"explanations\">Changes in an insurer’s cash flows occur as a result of three activities. Operating activities are transactions that involve a company’s core business operations and that directly determine the company’s net income. Investing activities are transactions that involve a company’s purchases or sales of long-term assets and its lending funds to other companies. Investing activities involve the securities of other companies. Financing activities are transactions that involve borrowed funds and cash payments to or from a company’s owners. Financing activities involve the company’s own securities.</p><p class=\"explanations\"><b>Learning Objective: 4B. Classify transactions that affect an insurer’s cash flows as one of three types of activities: operating activities, investing activities, or financing activities.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_031'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_032';
objQuestion.questionID = 110218;
objQuestion.item = 'LOMA_361_PPQ2019_032';
objQuestion.primaryLO = '4C';
objQuestion.textref = 'c. 4, pp. 18-19';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '4C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">In the context of financial statements, financial statement integration means that a company’s financial statements are interrelated. All other factors remaining equal, when an insurer pays contractual benefits or agent commissions, these transactions <b>(decrease / increase)</b> the insurer’s expenses and <b>(decrease / increase)</b> its cash.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "decrease / decrease";
arrAnsChoices[1] = "decrease / increase";
arrAnsChoices[2] = "increase / decrease";
arrAnsChoices[3] = "increase / increase";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445448;
arrAnsIDs[1] = 445449;
arrAnsIDs[2] = 445450;
arrAnsIDs[3] = 445451;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that, when the insurer pays contractual benefits or agent commissions, these transactions generally decrease the insurer’s cash (balance sheet). However, these transactions generally <b>increase</b> the insurer’s expenses (income statement).</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">When the insurer pays contractual benefits or agent commissions, these transactions generally <b>increase</b> the insurer’s expenses (income statement) and <b>decrease</b> the insurer’s cash (balance sheet).</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Changes in the accounts on an insurer’s income statement ultimately affect accounts on the insurer’s balance sheet. An increase in an insurer’s revenues (income statement) generally results in an increase in the insurer’s assets (balance sheet), assuming income was received in the same accounting period in which it was earned. Likewise, an increase in an insurer’s expenses (income statement) generally results in a decrease in the insurer’s assets (usually cash on the balance sheet). The amount of a company’s net income or net loss reported on the income statement and the statement of owners’ equity is reflected in the owners’ equity portion of the company’s balance sheet.</p><p class=\"explanations\">The cash flow statement is also linked to the balance sheet. For a given accounting period, the final entry on the cash flow statement—”Cash and cash equivalents as of end of year”—is equal to the amount listed in the <i>Cash and cash equivalents</i> account on the insurer’s balance sheet. Similarly, the statement of owners’ equity (for stock insurers: the statement of stockholders’ equity) is linked to the balance sheet. The end-of-year balances for common stock, retained earnings, accumulated other comprehensive income (AOCI), and total stockholders’ equity match those shown on the balance sheet for each account.</p><p class=\"explanations\"><b>Learning Objective: 4C. Distinguish between static and dynamic financial statements and describe the relationships among the financial statements.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that, when an insurer pays contractual benefit expenses or agent commissions, these transactions generally increase the insurer’s expenses (income statement). However, these transactions also generally <b>decrease</b> the insurer’s cash (balance sheet).</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_032'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_361_PQ_033';
objQuestion.questionID = 110219;
objQuestion.item = 'LOMA_361_PPQ2019_033';
objQuestion.primaryLO = '4D';
objQuestion.textref = 'c. 4, pp. 21-22';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '4D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">In the United States, insurers must submit a specific document that includes the insurer’s financial information to the NAIC and the insurance regulatory organization in each state in which the insurer conducts business. This document, which must be prepared using statutory accounting principles (SAP), contains data that regulators need to evaluate a company’s solvency and compliance with insurance regulations, is known as the</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "statement of operations";
arrAnsChoices[1] = "Annual Report";
arrAnsChoices[2] = "Annual Statement";
arrAnsChoices[3] = "statement of owners’ equity";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 445452;
arrAnsIDs[1] = 445453;
arrAnsIDs[2] = 445454;
arrAnsIDs[3] = 445455;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A statement of operations is another name for an income statement, which is a financial statement that reports an insurer’s revenues and expenses during a specified accounting period and indicates whether the insurer experienced net income or a net loss during the accounting period.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">In the United States, all publicly traded companies, including stock insurers, must publish an Annual Report for their stockholders. In addition, mutual insurers and fraternal insurers that offer variable products are required to publish an Annual Report for their policyowners.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The NAIC and most state insurance departments require insurers to file the Annual Statement electronically. Although regulators are the primary audience for the Annual Statement, other users include rating agencies, investment analysts, and insurance company’s managers. For example, company managers use Annual Statement data to compare their company’s performance to that of other companies.</p><p class=\"explanations\"><b>Learning Objective: 4D. Differentiate between the Annual Report and the Annual Statement in terms of their purpose and primary audience.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A statement of owners’ equity is a financial statement that provides information about changes in owners’ equity accounts between two sequential balance sheets.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_361_PQ_033'] = objQuestion;



arrMinicases[1] = "<p class=\"caseinfo\">Use the following information to answer questions 1 and 2.</p><p class=\"caseinfo\">The Montage Life Insurance Company reported the following financial information on December 31:</p><ul class=\"examul\"><li>Total assets = $300,000,000</li><li>Total revenues = $40,000,000</li><li>Total liabilities = $108,000,000</li><li>Total expenses = $14,000,000</li></ul>";


var arrlotext = new Array(); 
arrlotext['2A'] = "2A. List and describe the five major account classifications in the context of the basic accounting equation.";
arrlotext['4A'] = "4A. Describe an insurer’s key financial statements and list the account classifications that appear on each financial statement.";
arrlotext['4B'] = "4B. Classify transactions that affect an insurer’s cash flows as one of three types of activities: operating activities, investing activities, or financing activities.";
arrlotext['4C'] = "4C. Distinguish between static and dynamic financial statements and describe the relationships among the financial statements.";
arrlotext['4D'] = "4D. Differentiate between the Annual Report and the Annual Statement in terms of their purpose and primary audience.";
