var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2020';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 357 Practice Questions, Chapter 7";
var coursename = 'LOMA 357';
var modulenumber = 3;
var title = "LOMA_357_PPQ2019_0_7";
var intNumPools = 1;
var numQ = 12;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Institutional Investing: Principles and Practices (2019)";
arrNumChap[0] = 1;
var thisChap = '7';

objPool = new Object(); 
objPool.intSelectCount = 12;
objPool.formID = 2139;
objPool.formName = 'PPQ2019_0_7';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_357_PQ_069';
arrPoolQuestions[1] = 'LOMA_357_PQ_070';
arrPoolQuestions[2] = 'LOMA_357_PQ_071';
arrPoolQuestions[3] = 'LOMA_357_PQ_072';
arrPoolQuestions[4] = 'LOMA_357_PQ_073';
arrPoolQuestions[5] = 'LOMA_357_PQ_074';
arrPoolQuestions[6] = 'LOMA_357_PQ_075';
arrPoolQuestions[7] = 'LOMA_357_PQ_076';
arrPoolQuestions[8] = 'LOMA_357_PQ_077';
arrPoolQuestions[9] = 'LOMA_357_PQ_078';
arrPoolQuestions[10] = 'LOMA_357_PQ_079';
arrPoolQuestions[11] = 'LOMA_357_PQ_080';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_069';
objQuestion.questionID = 111076;
objQuestion.item = 'LOMA_357_PPQ2019_069';
objQuestion.primaryLO = '7A';
objQuestion.textref = 'c. 7, pp. 2, 4, 5-6';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about portfolio construction. Three statements are true, and one statement is false. Select the answer choice containing the <B>FALSE</B> statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A portfolio’s strategic asset allocation (SAA) should incorporate the expected returns and standard deviations of returns of each asset class.";
arrAnsChoices[1] = "A portfolio’s strategic asset allocation (SAA) reflects the expert judgment of investment professionals on the most effective asset-class weightings.";
arrAnsChoices[2] = "Investment professionals can select any asset class that meets the IPS’s specific return requirements, regardless of the investor’s risk tolerance.";
arrAnsChoices[3] = "Within an asset class, investment professionals use sub-asset classes to further customize a given portfolio’s risk profile.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448934;
arrAnsIDs[1] = 448935;
arrAnsIDs[2] = 448936;
arrAnsIDs[3] = 448937;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response. If a portfolio needs to earn at least a certain rate of return each year, investment professionals must assign an appropriate weighting to asset classes that are capable of generating sufficient returns and can be reasonably expected to do so.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response. Professionals design the SAA to give a portfolio the proper exposures to systematic risks, as well as to balance those risks in the best proportions for the portfolio.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">This statement is false; therefore, it is the correct response. An IPS can include limitations on which asset classes are acceptable for a given portfolio. In addition to return requirements, investment professionals must take into account requirements related to risk appetite, risk tolerance, risk limits, and restrictions on investment practices. Investment professionals typically work with an institution to determine the asset classes and sub-asset classes that are approved and appropriate for a given portfolio.</p><p class=\"explanations\"><b>Learning Objective: 7A. Describe the planning process for institutional investment portfolios, including the role of portfolio construction.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response. Investment professionals select each asset class in a portfolio for the particular risk and return features that it contributes to the overall portfolio. Sub-asset classes help investors diversify their holdings within an asset class and further customize a given portfolio’s risk profile.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_069'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_070';
objQuestion.questionID = 111077;
objQuestion.item = 'LOMA_357_PPQ2019_070';
objQuestion.primaryLO = '7B';
objQuestion.textref = 'c. 7, pp. 6-8';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Consider a portfolio with two asset classes: Class&nbsp;A and Class&nbsp;B. Whenever the return on Class&nbsp;A increases by one percent, the return on Class&nbsp;B decreases by one percent. This information indicates that the strength of the correlation between Class&nbsp;A and Class&nbsp;B is</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "modest positive correlation";
arrAnsChoices[1] = "perfect positive correlation";
arrAnsChoices[2] = "perfect negative correlation";
arrAnsChoices[3] = "absent";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448938;
arrAnsIDs[1] = 448939;
arrAnsIDs[2] = 448940;
arrAnsIDs[3] = 448941;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">In investment markets, finding a pair of asset classes with perfect positive correlation or perfect negative correlation is extremely unlikely in practice. Investment professionals most likely encounter aspects of modest positive correlation or modest negative correlation. However, in this situation, the strength of the correlation between Class&nbsp;A and Class&nbsp;B is <b>not</b> modest positive correlation.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Perfect positive correlation between a pair of asset classes exists if an <b>exactly equal increase</b> in the values of one asset class corresponds to an <b>exactly equal increase </b>in the values of the other asset class, or an exactly equal decrease in the values of one asset class corresponds to an exactly equal decrease in the values of the other asset class. In this situation, the strength of the correlation between Class&nbsp;A and Class&nbsp;B is <b>not</b> perfect positive correlation.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Two asset classes are correlated when a change in the market value of one asset class corresponds to a change in the market value of another asset class. If the correlation is positive, the values of the asset classes move in the same direction; if the correlation is negative, the values of the asset classes move in the opposite direction.</p><p class=\"explanations\">Perfect positive correlation between a pair of asset classes exists if an exactly equal increase in the values of one asset class corresponds to an exactly equal increase in the values of the other asset class, or an exactly equal decrease in the values of one asset class corresponds to an exactly equal decrease in the values of the other asset class. Perfect negative correlation between a pair of asset classes is an inverse relationship that exists if an exactly equal increase in the values of one asset class corresponds to an exactly equal decrease in the values of the other asset class, or an exactly equal decrease in the values of one asset class corresponds to an exactly equal increase in the values of the other asset class.</p><p class=\"explanations\">Perfect positive correlation or perfect negative correlation can occur in theoretical or virtual portfolios. However, in investment markets, finding a pair of asset classes with perfect positive correlation or perfect negative correlation is extremely unlikely. Investment professionals most likely encounter aspects of modest positive correlation or modest negative correlation.</p><p class=\"explanations\"><b>Learning Objective: 7B. Explain how investment professionals use correlation coefficients and the asset-class correlation matrix in correlation analysis.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Two asset classes are correlated when a change in the market value of one asset class corresponds to a change in the market value of another asset class. In this situation, correlation is <b>present</b> between Class&nbsp;A and Class&nbsp;B.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_070'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_071';
objQuestion.questionID = 111078;
objQuestion.item = 'LOMA_357_PPQ2019_071';
objQuestion.primaryLO = '7B';
objQuestion.textref = 'c. 7, pp. 6-8';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Noah Irby, a portfolio manager, is reviewing an asset-class correlation matrix to gain diversification benefits by adding a new asset class during construction of the Fruitful Portfolio. Mr.&nbsp;Irby noted the following four asset classes and their correlation coefficients from the asset-class correlation matrix:</p><table class=\"tbexam\" align=\"center\"><tr><td style=\"vertical-align: middle; text-align: left; background-color: #DCDCDC;\"><b>Asset Class</b></td><td style=\"vertical-align: middle; text-align: left; background-color: #DCDCDC;\"><b>Correlation Coefficient</b></td></tr><tr><td style=\"vertical-align: middle; text-align: center; background-color: #F8F8FF;\">Class A</td><td style=\"vertical-align: middle; text-align: center; background-color: #F8F8FF;\">–0.85</td></tr><tr><td style=\"vertical-align: middle; text-align: center; background-color: #F8F8FF;\">Class B</td><td style=\"vertical-align: middle; text-align: center; background-color: #F8F8FF;\">+0.12</td></tr><tr><td style=\"vertical-align: middle; text-align: center; background-color: #F8F8FF;\">Class C</td><td style=\"vertical-align: middle; text-align: center; background-color: #F8F8FF;\">+0.57</td></tr><tr><td style=\"vertical-align: middle; text-align: center; background-color: #F8F8FF;\">Class D</td><td style=\"vertical-align: middle; text-align: center; background-color: #F8F8FF;\">+0.94</td></tr></table><p class=\"stem\">This information indicates that Mr.&nbsp;Irby most likely would achieve the <i>greatest </i>diversification benefits by adding to the Fruitful Portfolio the asset class called</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Class A";
arrAnsChoices[1] = "Class B";
arrAnsChoices[2] = "Class C";
arrAnsChoices[3] = "Class D";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448942;
arrAnsIDs[1] = 448943;
arrAnsIDs[2] = 448944;
arrAnsIDs[3] = 448945;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The correlation coefficient indicates how closely movements in two asset classes track one another. Correlation coefficient values range from –1, which represents perfect negative correlation, to +1, which represents perfect positive correlation. The stronger the positive correlation, the more the investor could potentially lose; pairing asset classes with negative correlations reduces the volatility of the portfolio’s overall returns.</p><p class=\"explanations\">Any two asset classes with a correlation coefficient lower than +1 will provide some diversification benefits to a portfolio. However, investors obtain the greatest diversification benefits by holding a pair of asset classes having some degree of negative correlation. In this situation, Class A has a correlation coefficient of –0.85; Mr.&nbsp;Irby most likely would achieve the greatest<i> </i>diversification benefits by adding Class A to the Fruitful Portfolio.</p><p class=\"explanations\"><b>Learning Objective: 7B. Explain how investment professionals use correlation coefficients and the asset-class correlation matrix in correlation analysis.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Any two asset classes with a correlation coefficient of <b>lower than +1</b> will provide some diversification benefits to a portfolio. However, investors obtain the greatest diversification benefits by holding a pair of asset classes having some degree of <b>negative correlation</b>. In this situation, Class B has a correlation coefficient of +0.12. Class B is <b>not</b> the asset class that most likely would allow Mr.&nbsp;Irby to achieve the <i>greatest </i>diversification benefits.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Any two asset classes with a correlation coefficient of <b>lower than +1</b> will provide some diversification benefits to a portfolio. However, investors obtain the greatest diversification benefits by holding a pair of asset classes having some degree of <b>negative correlation</b>. In this situation, Class C has a correlation coefficient of +0.57. Class C is <b>not</b> the asset class that most likely would allow Mr.&nbsp;Irby to achieve the greatest diversification benefits.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Any two asset classes with a correlation coefficient of <b>lower than +1</b> will provide some diversification benefits to a portfolio. However, investors obtain the greatest diversification benefits by holding a pair of asset classes having some degree of <b>negative correlation</b>. In this situation, Class D has a correlation coefficient of +0.94, nearly +1: perfect positive correlation. Class D is <b>not</b> the asset class that most likely would allow Mr.&nbsp;Irby to achieve the <i>greatest </i>diversification benefits.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_071'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_072';
objQuestion.questionID = 111079;
objQuestion.item = 'LOMA_357_PPQ2019_072';
objQuestion.primaryLO = '7C';
objQuestion.textref = 'c. 7, pp. 8-10';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Investment professionals use mean variance optimization (MVO) to identify portfolio asset allocations that represent the most efficient portfolios. The following statement(s) can correctly be made about MVO:</p><ol type=\"A\" class=\"combo\"><li>The efficient frontier is a downward-sloping curve that incorporates only the most efficient portfolios generated by MVO modeling for a range of risk levels.</li><li>In the context of the risk-return trade-off, for each efficient portfolio on the efficient frontier, an investor cannot reduce portfolio risk without decreasing the expected return.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448946;
arrAnsIDs[1] = 448947;
arrAnsIDs[2] = 448948;
arrAnsIDs[3] = 448949;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is incorrect. The efficient frontier—the set of <b>all</b> hypothetical portfolios having the greatest expected return, each for a specified level of risk—is an <b>upward-sloping</b> curve that incorporates <b>every</b> efficient portfolio calculated by MVO modeling.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement A is incorrect. The efficient frontier—the set of all hypothetical portfolios having the greatest expected return, each for a specified level of risk—is an upward-sloping curve that incorporates every efficient portfolio calculated by MVO modeling.</p><p class=\"explanations\">Statement B is correct. One way to interpret the efficient frontier is as the visual representation of the risk-return trade-off, in the context of portfolio asset allocations. For each efficient portfolio on the efficient frontier, an investor cannot add assets to the portfolio to obtain a higher expected return without increasing portfolio risk, and cannot reduce portfolio risk without decreasing the expected return. The efficient portfolio’s asset allocations become the template for the investment portfolio’s SAA.</p><p class=\"explanations\"><b>Learning Objective: 7C. Explain how investment professionals can use mean variance optimization (MVO) and Monte Carlo modeling when creating a portfolio’s strategic asset allocation (SAA).</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_072'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_073';
objQuestion.questionID = 111080;
objQuestion.item = 'LOMA_357_PPQ2019_073';
objQuestion.primaryLO = '7D';
objQuestion.textref = 'c. 7, pp. 12-13';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Jun He is a portfolio manager who plans a 55% allocation to stocks and a 45% allocation to bonds for a particular investment portfolio. In selecting a portfolio benchmark, which she will use to evaluate the portfolio’s performance, Ms.&nbsp;He most likely would select a</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "stock market index only, because the portfolio has more stocks than bonds";
arrAnsChoices[1] = "blended benchmark—an unweighted combination of a stock index (50%) and a bond index (50%)";
arrAnsChoices[2] = "blended benchmark—a weighted combination of a stock index (55%) and a bond index (45%)";
arrAnsChoices[3] = "market index that reports the performance of more than 85% of the world’s largest companies";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448950;
arrAnsIDs[1] = 448951;
arrAnsIDs[2] = 448952;
arrAnsIDs[3] = 448953;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">In this situation, Ms.&nbsp;He most likely would create a blended benchmark that is a weighted combination of a stock index (55%), such as the S&P 500 Index, and a bond index (45%), such as the Barclays US Aggregate Bond Index, calculated as 0.55 × S&P 500 Index + 0.45 × Barclays US Aggregate Bond Index.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">In this situation, Ms.&nbsp;He most likely would create a blended benchmark that is a weighted combination of a stock index (55%), such as the S&P 500 Index, and a bond index (45%), such as the Barclays US Aggregate Bond Index, calculated as 0.55 × S&P 500 Index + 0.45 × Barclays US Aggregate Bond Index.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Once investment professionals have selected the asset classes and the SAA for a given portfolio, they select the portfolio’s benchmark, which will be used to evaluate the portfolio’s performance. Investment professionals first identify the market index associated with each asset class used in the portfolio. Then, the asset class benchmarks are weighted according to the portfolio’s SAA, in the proportion that each asset class will be held in a given portfolio. A blended benchmark provides investment professionals with an effective performance standard by which to measure a portfolio that holds several asset classes.</p><p class=\"explanations\">In this situation, Ms.&nbsp;He most likely would create a blended benchmark that is a weighted combination of a stock index (55%), such as the S&P 500 Index, and a bond index (45%), such as the Barclays US Aggregate Bond Index, calculated as 0.55 × S&P 500 Index + 0.45 × Barclays US Aggregate Bond Index.</p><p class=\"explanations\"><b>Learning Objective: 7D. Describe how investment professionals create blended benchmarks and explain their benefits.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">In this situation, Ms.&nbsp;He most likely would create a blended benchmark that is a weighted combination of a stock index (55%), such as the S&P 500 Index, and a bond index (45%), such as the Barclays US Aggregate Bond Index, calculated as 0.55 × S&P 500 Index + 0.45 × Barclays US Aggregate Bond Index.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_073'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_074';
objQuestion.questionID = 111081;
objQuestion.item = 'LOMA_357_PPQ2019_074';
objQuestion.primaryLO = '7E';
objQuestion.textref = 'c. 7, pp. 13-15';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Investment professionals use a variety of factors to identify, evaluate, and select assets in specified proportions to fit a portfolio’s asset allocation. Common factors include the asset’s sector and industry, ratings, liquidity, transaction costs, and environmental, social, and governance (ESG) factors. One correct statement that can be made about these factors is that</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "alternative investments have low transaction costs; therefore, this factor is not an important consideration in selecting alternative investments";
arrAnsChoices[1] = "a large number of illiquid assets is appropriate in a portfolio, regardless of an investor’s time horizon";
arrAnsChoices[2] = "few investment professionals consider ESG factors in selecting assets for institutional portfolios";
arrAnsChoices[3] = "insurance companies are subject to regulations concerning ratings that affect the securities they can own";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448954;
arrAnsIDs[1] = 448955;
arrAnsIDs[2] = 448956;
arrAnsIDs[3] = 448957;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Alternative investments have <b>relatively high transaction costs</b>, which limits their attractiveness to some investors. Because transaction costs reduce the amount of money that can be invested, investment professionals strive to minimize transaction costs so a portfolio can earn the best possible returns.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The time horizon is <b>important</b> when assessing the factor of liquidity. For investors with short time horizons, holding a large number of<b> </b>illiquid assets in their portfolios would be inappropriate. Investors with long time horizons are less concerned with asset liquidity because they do not need to convert their portfolio holdings into cash in the near future.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\"><b>More</b> investment professionals are considering ESG factors—in addition to the traditional financial metrics—to identify the best investments for institutional portfolios. Companies that score higher on ESG factors tend to be more conscientious about managing risks, increasing value for all stakeholders, and promoting long-term profitability. Academic research also suggests that these companies demonstrate stronger long-term financial performance than companies with lower scores on the same factors.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">In the United States, state regulators may restrict life insurers from investing in bonds that do not achieve a specific Securities Valuation Office (SVO) designation. Rating agencies provide assessments on the quality of individual securities, security issuers, and funds. Investment professionals may use these ratings to supplement their own research.</p><p class=\"explanations\"><b>Learning Objective: 7E. Describe some of the common criteria that investment professionals use to select assets for portfolios—such as sector and industry, ratings, liquidity, transaction costs, and environmental, social, and governance (ESG) factors.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_074'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_075';
objQuestion.questionID = 111082;
objQuestion.item = 'LOMA_357_PPQ2019_075';
objQuestion.primaryLO = '7E';
objQuestion.textref = 'c. 7, pp. 16-19';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Ariana Mendez, a portfolio manager for a life insurer, is selecting assets for a new investment portfolio to support life insurance general account products. For each asset type, the investment team has performed research and identified potential investments that will position the portfolio to meet the insurer’s risk and return objectives. For example, the investment team provided Ms.&nbsp;Mendez with the following information on four common stocks:</p><table class=\"tbexam\" align=\"center\"><tr><td style=\"vertical-align: middle; text-align: left; background-color: #DCDCDC;\"><b>Criteria</b></td><td style=\"vertical-align: middle; text-align: center; background-color: #DCDCDC;\"><b>Stock A</b></td><td style=\"vertical-align: middle; text-align: center; background-color: #DCDCDC;\"><b>Stock B</b></td><td style=\"vertical-align: middle; text-align: center; background-color: #DCDCDC;\"><b>Stock C</b></td><td style=\"vertical-align: middle; text-align: center; background-color: #DCDCDC;\"><b>Stock D</b></td></tr><tr><td style=\"vertical-align: middle; text-align: left;\">10-year rate of return</td><td style=\"vertical-align: middle; text-align: center;\">10%</td><td style=\"vertical-align: middle; text-align: center;\">7.0%</td><td style=\"vertical-align: middle; text-align: center;\">8%</td><td style=\"vertical-align: middle; text-align: center;\">17.8%</td></tr><tr><td style=\"vertical-align: middle; text-align: left;\">10-year standard deviation</td><td style=\"vertical-align: middle; text-align: center;\">12.5</td><td style=\"vertical-align: middle; text-align: center;\">6.5</td><td style=\"vertical-align: middle; text-align: center;\">9</td><td style=\"vertical-align: middle; text-align: center;\">14.3</td></tr><tr><td style=\"vertical-align: middle; text-align: left;\">Dividend yield</td><td style=\"vertical-align: middle; text-align: center;\">3.5%</td><td style=\"vertical-align: middle; text-align: center;\">3.3%</td><td style=\"vertical-align: middle; text-align: center;\">3.7%</td><td style=\"vertical-align: middle; text-align: center;\">--</td></tr><tr><td style=\"vertical-align: middle; text-align: left;\">P/E ratio</td><td style=\"vertical-align: middle; text-align: center;\">31.7</td><td style=\"vertical-align: middle; text-align: center;\">18.2</td><td style=\"vertical-align: middle; text-align: center;\">17.4</td><td style=\"vertical-align: middle; text-align: center;\">22.4</td></tr></table><p class=\"stem\">Ms.&nbsp;Mendez is seeking the common stock with the best combination of a high rate of return, low standard deviation, high dividend yield, and low P/E ratio value to add to the portfolio. This information indicates that the stock that Ms.&nbsp;Mendez most likely would select for the portfolio is</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Stock A";
arrAnsChoices[1] = "Stock B";
arrAnsChoices[2] = "Stock C";
arrAnsChoices[3] = "Stock D";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448958;
arrAnsIDs[1] = 448959;
arrAnsIDs[2] = 448960;
arrAnsIDs[3] = 448961;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Compared to the other stocks, Stock A has a high 10-year rate of return, but its returns are more volatile, as indicated by its high 10-year standard deviation. Stock A also has the lowest dividend yield and the highest P/E ratio, which may mean that its shares are comparatively more expensive. Therefore, Ms.&nbsp;Mendez most likely would <b>not</b> select Stock A for the new investment portfolio.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Compared to the other stocks, Stock B has the lowest 10-year rate of return, lowest dividend yield. Stock&nbsp;B also has a high P/E ratio, which may mean that its shares are comparatively more expensive. Therefore, Ms.&nbsp;Mendez most likely would <b>not</b> select Stock B for the investment portfolio.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Compared to the other stocks, Stock A has a high 10-year rate of return, but its returns are more volatile, as indicated by its high 10-year standard deviation. Stock A also has the lowest dividend yield and the highest P/E ratio, which may mean that its shares are relatively more expensive. Compared to the other stocks, Stock B has the lowest 10-year rate of return and lowest dividend yield. Stock B also has a high P/E ratio, which may mean that its shares are comparatively more expensive.</p><p class=\"explanations\">Compared to other stocks, Stock D has the highest 10-year rate of return and highest 10-year standard deviation, which may indicate the highest volatility over the same period. Also, Stock D does not pay a dividend and it has a high P/E ratio, which may mean that its shares are comparably more expensive. Therefore, Ms.&nbsp;Mendez most likely would not select Stock A, Stock B, or Stock D for the portfolio.</p><p class=\"explanations\">Stock B and Stock C have similar values for their P/E ratios. Compared to Stock B, Stock C has a higher 10-year standard deviation, a higher 10-year rate of return, and a slightly higher dividend yield. In this situation, Ms.&nbsp;Mendez most likely would determine that the potential rewards are worth the additional return volatility; therefore, she would select Stock C for the portfolio.</p><p class=\"explanations\"><b>Learning Objective: 7E. Describe some of the common criteria that investment professionals use to select assets for portfolios—such as sector and industry, ratings, liquidity, transaction costs, and environmental, social, and governance (ESG) factors.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Compared to other stocks, Stock D has the highest 10-year rate of return and highest 10-year standard deviation, which may indicate the highest volatility over the same period. Also, Stock D does not pay a dividend and it has a high P/E ratio, which may mean that its shares are comparably more expensive. Therefore, Ms.&nbsp;Mendez most likely would <b>not</b> select Stock D for the investment portfolio.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_075'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_076';
objQuestion.questionID = 111083;
objQuestion.item = 'LOMA_357_PPQ2019_076';
objQuestion.primaryLO = '7F';
objQuestion.textref = 'c. 7, p. 22';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Investment professionals usually classify funds according to observable characteristics, although some characteristics can seem subjective or arbitrary. In this context, an absolute return fund seeks to</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "offer a guaranteed minimum rate of return plus the potential for excess interest crediting";
arrAnsChoices[1] = "produce a pattern of performance similar to that of a specified market index";
arrAnsChoices[2] = "automatically change the asset allocation over time to support an investor’s goal of accumulating a specified amount of money by a specified date";
arrAnsChoices[3] = "achieve positive returns in all market conditions by investing in a variety of asset classes and employing alternative investment management techniques";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448962;
arrAnsIDs[1] = 448963;
arrAnsIDs[2] = 448964;
arrAnsIDs[3] = 448965;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A <b>stable value fund</b> is a conservative fund that focuses on capital preservation and offers a guaranteed minimum rate of return plus the potential for excess interest crediting.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">An <b>index fund</b> is a passively-managed fund that is constructed to produce a pattern of performance similar to that of a specified market index.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A <b>target-date fund</b>, also known as a lifecycle fund, invests in various asset classes and automatically changes the asset allocation over a period of time. The fund’s main objective is to support an investor’s goal of accumulating a specified amount of money by a specified date.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Funds can be classified by asset classes and sub-asset classes. In addition to absolute return funds, two other common classifications by asset class are equity funds and fixed-income funds. The assets of equity funds, also called stock funds, typically consist of common stocks, but also may include preferred stocks or real estate. Equity funds are often categorized by market cap, industry sector, and/or geographic location. Fixed-income funds typically consist of specified debt instruments and are categorized by the specified type of debt instrument. Further classifications include type of debt instrument held, average term to maturity of held assets, credit quality, and geographic location.</p><p class=\"explanations\"><b>Learning Objective: 7F. Identify the ways that investment professionals can classify funds—including asset class, management approach, investment style, market capitalization, asset allocation, geography, and sector.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_076'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_077';
objQuestion.questionID = 111084;
objQuestion.item = 'LOMA_357_PPQ2019_077';
objQuestion.primaryLO = '7F';
objQuestion.textref = 'c. 7, pp. 23-24';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Common fund classification by investment style includes value funds, growth funds, and core funds. With regard to dividend payments and volatility, it is correct to say that the stocks in (<b>value</b> / <b>growth</b>) funds often pay little or no dividends, and (<b>value</b> / <b>growth</b>) funds typically have lower price volatility.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "value / value";
arrAnsChoices[1] = "value / growth";
arrAnsChoices[2] = "growth / value";
arrAnsChoices[3] = "growth / growth";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448966;
arrAnsIDs[1] = 448967;
arrAnsIDs[2] = 448968;
arrAnsIDs[3] = 448969;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is correct to say that value funds usually have lower price volatility. However, <b>growth funds</b> typically pay little or no dividends.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\"><b>Growth funds</b> typically pay little or no dividends. Also, <b>value funds</b> usually have lower price volatility.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Growth funds invest in the stocks of companies with the potential for above-average growth, resulting in capital appreciation. Growth stocks typically have high price/earnings (P/E) ratios. Growth funds usually outperform value funds during periods of economic expansion.</p><p class=\"explanations\">Value funds invest in the stocks of companies that are undervalued in relation to the overall market, and that often pay significant dividends. Value stocks generally are associated with patient investors who will wait for a stock’s market price to rise to the value they believe it deserves. Value funds tend to outperform growth funds during economic recessions.</p><p class=\"explanations\">Core funds, or blend funds, seek growth and value stocks. Some fund providers also use the term “core fund” to indicate funds that can invest in both stocks and bonds.</p><p class=\"explanations\"><b>Learning Objective: 7F. Identify the ways that investment professionals can classify funds—including asset class, management approach, investment style, market capitalization, asset allocation, geography, and sector.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is correct to say that growth funds typically pay little or no dividends. However, <b>value funds</b> usually have lower price volatility.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_077'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_078';
objQuestion.questionID = 111085;
objQuestion.item = 'LOMA_357_PPQ2019_078';
objQuestion.primaryLO = '7F';
objQuestion.textref = 'c. 7, pp. 25-26';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following Morningstar Style Box is a profile of the Parade Fund:</p><table class=\"tbexam\" align=\"center\"><tr><td style=\"vertical-align: middle; text-align: left; background-color: transparent; border: none;\">&nbsp;</td><td colspan=\"3\" style=\"vertical-align: middle; text-align: center; background-color: #DCDCDC;\"><b>Duration</b></td></tr><tr><td style=\"vertical-align: middle; text-align: left; background-color: #DCDCDC;\"><b>Credit Rating</b></td><td style=\"vertical-align: middle; text-align: left; background-color: #DCDCDC;\"><b>Short</b></td><td style=\"vertical-align: middle; text-align: left; background-color: #DCDCDC;\"><b>Medium</b></td><td style=\"vertical-align: middle; text-align: left; background-color: #DCDCDC;\"><b>Long</b></td></tr><tr><td style=\"vertical-align: middle; text-align: left;\">High</td><td style=\"vertical-align: middle; text-align: left;\">&nbsp;</td><td style=\"vertical-align: middle; text-align: left;\">&nbsp;</td><td style=\"vertical-align: middle; text-align: left; background-color: #000000;\">&nbsp;</td></tr><tr><td style=\"vertical-align: middle; text-align: left;\">Medium</td><td style=\"vertical-align: middle; text-align: left;\">&nbsp;</td><td style=\"vertical-align: middle; text-align: left;\">&nbsp;</td><td style=\"vertical-align: middle; text-align: left;\">&nbsp;</td></tr><tr><td style=\"vertical-align: middle; text-align: left;\">Low</td><td style=\"vertical-align: middle; text-align: left;\">&nbsp;</td><td style=\"vertical-align: middle; text-align: left;\">&nbsp;</td><td style=\"vertical-align: middle; text-align: left;\">&nbsp;</td></tr></table><p class=\"stem\">This information indicates that the Parade Fund most likely is a</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "large-cap fixed-income fund";
arrAnsChoices[1] = "large-cap equity fund";
arrAnsChoices[2] = "long-duration fixed-income fund";
arrAnsChoices[3] = "long-duration equity fund";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448970;
arrAnsIDs[1] = 448971;
arrAnsIDs[2] = 448972;
arrAnsIDs[3] = 448973;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is correct to say that the Morningstar Style Box depicts a fixed-income fund. However, the grid does <b>not</b> depict a large-cap fund, which is a category typically used for equity funds.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The Morningstar Style Box depicts a <b>fixed-income fund</b>. In addition, the grid does <b>not</b> depict a large-cap fund, which is a category typically used for equity funds.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The Morningstar Style Box is a nine-square grid that provides a graphical representation of a fund’s investment style. The appropriate grid is blackened or checked to provide a quick visual cue as to the fund’s basic style classification. The Equity Fund Style Box grid typically depicts growth fund, value fund, and core fund investment styles and market capitalization—large-cap, mid-cap, and small-cap.</p><p class=\"explanations\">The Fixed-Income Fund Style Box grid typically depicts high, medium, and low credit ratings and short, medium, and long duration. In this situation, the profile of the Parade Fund is a Fixed-Income Style Box. The grid is blackened for a fixed-income fund with a high credit rating and long duration.</p><p class=\"explanations\"><b>Learning Objective: 7F. Identify the ways that investment professionals can classify funds—including asset class, management approach, investment style, market capitalization, asset allocation, geography, and sector.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is correct to say that the fund has a long duration. However, the Morningstar Style Box depicts a <b>fixed-income fund</b>.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_078'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_079';
objQuestion.questionID = 111086;
objQuestion.item = 'LOMA_357_PPQ2019_079';
objQuestion.primaryLO = '7G';
objQuestion.textref = 'c. 7, pp. 26-27, 22-23';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Investment professionals evaluate a variety of factors—such as management team, portfolio turnover rate, and expense ratio—before selecting fund options for portfolios for life insurance subaccount menus. The following statement(s) can correctly be made about these factors:</p><ol type=\"A\" class=\"combo\"><li>An active management strategy, which attempts to earn the average market return earned by fund peers, is characterized by a low portfolio turnover rate.</li><li>Investment professionals, who often compare a particular fund’s expense ratio to those of other funds in its peer group, generally prefer funds with low expense ratios.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448974;
arrAnsIDs[1] = 448975;
arrAnsIDs[2] = 448976;
arrAnsIDs[3] = 448977;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is incorrect. In the context of fund investing, an active management strategy attempts to outperform the average market return earned by fund peers. A <b>passive management strategy</b> attempts to earn the average market return earned by fund peers. This is characterized by a <b>low portfolio turnover rate</b>, which is the rate at which the fund buys or sells securities, expressed as a percentage of average total assets.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement A is incorrect. In the context of fund investing, an active management strategy attempts to outperform the average market return earned by fund peers. A passive management strategy, also known as a buy-and-hold strategy, attempts to earn the average market return earned by fund peers. This strategy is characterized by a low portfolio turnover rate, which is the rate at which the fund buys or sells securities, expressed as a percentage of average total assets. For example, an active manager may trade a bond before maturity if the bond’s current price is above par value, whereas a passive manager usually intends to hold a bond to maturity.</p><p class=\"explanations\">Statement B is correct. A fund’s expense ratio expresses the fund’s total annual operating expenses during a given period as a percentage of the fund’s average net assets during the same period. In general, actively managed funds have higher expense ratios than passively managed funds. Actively managed funds charge higher management fees to compensate for the additional resources used in pursuit of market outperformance. Compared to active management, passive management typically involves longer holding periods and less frequent trading, which results in lower transaction costs.</p><p class=\"explanations\"><b>Learning Objective: 7G. Explain how investment professionals evaluate fund classifications, investment styles, management teams, expense ratios, and ratings to select the fund options offered to an institution’s customers.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_079'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_080';
objQuestion.questionID = 111087;
objQuestion.item = 'LOMA_357_PPQ2019_080';
objQuestion.primaryLO = '7H';
objQuestion.textref = 'c. 7, p. 27';
objQuestion.textbook = 0;
objQuestion.chapter = 7;
objQuestion.module = 3;
var arrLOs = new Array();
arrLOs[0] = '7H';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about scorecards that investment analysts use to analyze or compare various funds. Three statements are true, and one statement is false. Select the answer choice containing the <B>FALSE</B> statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Scorecards grade a group of funds on a set of measures, such as the expense ratio or 5-year return.";
arrAnsChoices[1] = "Investment professionals must assign only numerical rankings on scorecards.";
arrAnsChoices[2] = "Investment professionals periodically repeat the scoring and ranking process.";
arrAnsChoices[3] = "Investment professionals use scorecards for analysis of a company’s existing fund options and for screening new funds for possible inclusion in a company’s menu of fund options.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448978;
arrAnsIDs[1] = 448979;
arrAnsIDs[2] = 448980;
arrAnsIDs[3] = 448981;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response. For each criterion, funds are ranked from best to worst based on their score.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">This statement is false; therefore, it is the correct response. Scorecards grade a group of funds on a set of measures, such as the expense ratio or 5-year return. For each criterion, funds are ranked from best to worst based on their score. Some scorecards assign funds a numerical ranking; others assign a letter grade or multiple stars.</p><p class=\"explanations\">Investment professionals typically compare a fund’s performance to the performance of a benchmark index, such as a market index. They also compare the total returns of a particular fund to the total returns of other funds in the same peer group. Through these comparisons, investment professionals can evaluate a fund’s relative performance.</p><p class=\"explanations\"><b>Learning Objective: 7H. Describe how investment professionals use benchmarks, peer groups, and scorecards to compare funds.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response. Investment professionals use scorecards for ongoing monitoring of a company’s menu of fund options as well as part of identifying fund option candidates.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response. When screening new funds, the relative rankings can quickly identify funds that are unsuitable for inclusion in a company’s menu of fund options.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_080'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['7A'] = "7A. Describe the planning process for institutional investment portfolios, including the role of portfolio construction.";
arrlotext['7B'] = "7B. Explain how investment professionals use correlation coefficients and the asset-class correlation matrix in correlation analysis.";
arrlotext['7C'] = "7C. Explain how investment professionals can use mean variance optimization (MVO) and Monte Carlo modeling when creating a portfolio’s strategic asset allocation (SAA).";
arrlotext['7D'] = "7D. Describe how investment professionals create blended benchmarks and explain their benefits.";
arrlotext['7E'] = "7E. Describe some of the common criteria that investment professionals use to select assets for portfolios—such as sector and industry, ratings, liquidity, transaction costs, and environmental, social, and governance (ESG) factors.";
arrlotext['7F'] = "7F. Identify the ways that investment professionals can classify funds—including asset class, management approach, investment style, market capitalization, asset allocation, geography, and sector.";
arrlotext['7G'] = "7G. Explain how investment professionals evaluate fund classifications, investment styles, management teams, expense ratios, and ratings to select the fund options offered to an institution’s customers.";
arrlotext['7H'] = "7H. Describe how investment professionals use benchmarks, peer groups, and scorecards to compare funds.";
