var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2020';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 357 Practice Questions, Chapter 11";
var coursename = 'LOMA 357';
var modulenumber = 4;
var title = "LOMA_357_PPQ2019_0_11";
var intNumPools = 1;
var numQ = 7;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Institutional Investing: Principles and Practices (2019)";
arrNumChap[0] = 1;
var thisChap = '11';

objPool = new Object(); 
objPool.intSelectCount = 7;
objPool.formID = 2139;
objPool.formName = 'PPQ2019_0_11';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_357_PQ_108';
arrPoolQuestions[1] = 'LOMA_357_PQ_109';
arrPoolQuestions[2] = 'LOMA_357_PQ_110';
arrPoolQuestions[3] = 'LOMA_357_PQ_111';
arrPoolQuestions[4] = 'LOMA_357_PQ_112';
arrPoolQuestions[5] = 'LOMA_357_PQ_113';
arrPoolQuestions[6] = 'LOMA_357_PQ_114';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_108';
objQuestion.questionID = 111115;
objQuestion.item = 'LOMA_357_PPQ2019_108';
objQuestion.primaryLO = '11A';
objQuestion.textref = 'c. 11, pp. 1-3';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '11A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statement(s) can correctly be made about ethical standards in financial services companies:</p><ol type=\"A\" class=\"combo\"><li>A reputation for high ethical standards can be a competitive advantage for a company in the financial services industry.</li><li>Regulations can anticipate every situation with the potential for professional misconduct and describe how the professional should behave in every situation.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 449093;
arrAnsIDs[1] = 449094;
arrAnsIDs[2] = 449095;
arrAnsIDs[3] = 449096;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct. Because many financial services customers do not recognize the differences between similar products, a company can distinguish itself based on its reputation for quality and fairness. Thus, ethical standards can help companies attract and retain customers.</p><p class=\"explanations\">Statement B is incorrect. Although regulations are designed to ensure that financial services professionals conduct business with customers in a fair manner, they cannot anticipate every situation with the potential for professional misconduct or describe how a professional should behave in every situation.</p><p class=\"explanations\"><b>Learning Objective: 11A. Define <i>ethics</i> and explain why ethical standards are important for financial services companies.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is incorrect. Although regulations are designed to ensure that financial services professionals conduct business with customers in a fair manner, they <b>cannot</b> anticipate every situation with the potential for professional misconduct or describe how a professional should behave in every situation.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_108'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_109';
objQuestion.questionID = 111116;
objQuestion.item = 'LOMA_357_PPQ2019_109';
objQuestion.primaryLO = '11B';
objQuestion.textref = 'c. 11, pp. 3-5';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '11B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">To promote consistent ethical behaviors among particular groups of professionals, some organizations designate sets of shared ethical standards, such as a code of conduct. The following statements are about a company’s code of conduct. Three statements are true, and one statement is false. Select the answer choice containing the <B>FALSE</B> statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A corporate code of conduct typically illustrates situations that employees might encounter in their work environment.";
arrAnsChoices[1] = "Financial services companies typically have one code of conduct that applies to all the employees in the company.";
arrAnsChoices[2] = "At times, regulations and ethical guidelines overlap to affect the behavior of investment professionals.";
arrAnsChoices[3] = "A code of conduct often provides guidelines for investment professionals with regard to conflicts of interest or the acceptance of gifts.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 449097;
arrAnsIDs[1] = 449098;
arrAnsIDs[2] = 449099;
arrAnsIDs[3] = 449100;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response. A corporate code of conduct helps employees evaluate the appropriateness of various responses to a given situation.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">This statement is false; therefore, it is the correct response. Financial services companies usually have <b>several</b> codes of conduct. For instance, an insurance company may have (1) a general code for all employees and (2) supplemental codes tailored to employees working in specific functions, such as the investment function.</p><p class=\"explanations\"><b>Learning Objective: 11B. Describe how codes of conduct promote ethical behavior among professionals.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response. Generally, regulations are rules that instruct you on what you must or must not do, and ethical standards are guidelines that advise you on what you should or should not do. However, they sometimes overlap. For instance, investment professionals that act as fiduciaries have regulatory and ethical considerations.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response. Many ethical guidelines for investment professionals describe how to avoid or address conflicts of interest. Therefore, professionals should make every effort to avoid conflicts that tempt them to put their interests ahead of their clients’ interests.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_109'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_110';
objQuestion.questionID = 111117;
objQuestion.item = 'LOMA_357_PPQ2019_110';
objQuestion.primaryLO = '11C';
objQuestion.textref = 'c. 11, pp. 7-9';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '11C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">A soft-dollar arrangement is a situation in which an investment professional directs client trades to a broker-dealer in exchange for receiving soft dollars, which the professional uses to obtain products or services—often research services—from the broker-dealer.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "True";
arrAnsChoices[1] = "False";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 449101;
arrAnsIDs[1] = 449102;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Soft-dollar arrangements cause ethical issues when a client, whose trades are generating commissions for a particular broker-dealer, does not benefit from the services that the investment professional receives by using soft dollars. Because soft dollars are incorporated into trade expenses, clients may not be aware of their true transaction costs.</p><p class=\"explanations\">Although soft-dollar arrangements are legal in many jurisdictions, the CFA Institute and securities regulators have guidelines regarding the use and disclosure of these arrangements. Some jurisdictions even consider a soft-dollar arrangement a breach of fiduciary duty when the clients involved pay more than the lowest available commission rate.</p><p class=\"explanations\">The SEC generally considers brokerage services as ineligible for soft-dollar arrangements unless the situation meets certain requirements. An investment professional should be able to demonstrate to the SEC that soft dollars paid for services that ultimately benefitted the clients whose transactions generated those dollars. Otherwise, the SEC could take regulatory action against the investment professional.</p><p class=\"explanations\"><b>Learning Objective: 11C. Explain how conflicts of interest affect investment professionals and identify some common conflicts for investment professionals.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">This statement is <b>true</b>. Investment professionals often purchase research and other services from brokerage firms. If they pay for such services directly, they are said to use hard dollars. In contrast, paying for brokerage services through a soft-dollar arrangement represents a conflict of interest.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_110'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_111';
objQuestion.questionID = 111118;
objQuestion.item = 'LOMA_357_PPQ2019_111';
objQuestion.primaryLO = '11D';
objQuestion.textref = 'c. 11, pp. 13-15';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '11D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Consider the following insider trading activities engaged in by two investment professionals:</p><ul class=\"examul\"><li><b>Activity 1</b>—A broker purchased a large block of a particular security based on advance knowledge of several large pending orders of the same security from clients.</li><li><b>Activity 2</b>—A trader allowed several investors to sell mutual funds at their closing prices after U.S. stock markets had closed.</li></ul><p class=\"stem\">Select the answer choice that correctly identifies whether the insider trader violation described in Activity 1 and Activity 2.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[-1] = "<u>Activity 1</u></div><div class=\"anshead\"><u>Activity 2</u>";
arrAnsChoices[0] = "front running</div><div class=\"anscell\" onclick=\"recordAns(1);\">trading ahead of research";
arrAnsChoices[1] = "front running</div><div class=\"anscell\" onclick=\"recordAns(2);\">late trading";
arrAnsChoices[2] = "collusion</div><div class=\"anscell\" onclick=\"recordAns(3);\">trading ahead of research";
arrAnsChoices[3] = "collusion</div><div class=\"anscell\" onclick=\"recordAns(4);\">late trading";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 449104;
arrAnsIDs[1] = 449105;
arrAnsIDs[2] = 449106;
arrAnsIDs[3] = 449107;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is correct to say that Activity 1 is an example of front running. However, Activity 2 is <b>not</b> an example of trading ahead of research, which occurs when, prior to the release of a research report, the trading operation of an investment management firm uses nonpublic information in a research report as a basis for increasing or decreasing its inventory position in a particular security.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Some notable unethical trading practices are insider trading, trading ahead of research, front running, late trading, and collusion. Front running, a type of insider trading, involves the unethical trade of a security by an investment professional based on advance knowledge of large pending client orders of the security.</p><p class=\"explanations\">Late trading is a type of illegal preferential treatment given to some investors who are allowed to trade securities—typically open-end mutual funds—after a stock market closes using that day’s closing prices. Late trading enables certain investors to use the day’s closing prices to conduct transactions, which, in turn, are based on information that became available only after the market’s close. Late trading is illegal in the United States because investors use information that was not available when markets were open to gain an unfair advantage over other participants in the market.</p><p class=\"explanations\"><b>Learning Objective: 11D. Explain why insider trading, trading ahead of research, front running, late trading, and collusion are unethical trading practices.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Activity 1 is <b>not</b> an example of collusion, which, in general, is an agreement between two or more people to defraud another person of his rights. In the context of investing, collusion generally gives market participants an unfair advantage by discouraging competition. Also, Activity 2 is <b>not</b> an example of trading ahead of research, which occurs when, prior to the release of a research report, the trading operation of an investment management firm uses nonpublic information in a research report as a basis for increasing or decreasing its inventory position in a particular security.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is correct to say that Activity 2 is an example of late trading. However, Activity 1 is <b>not</b> an example of collusion, which, in general, is an agreement between two or more people to defraud another person of his rights. In the context of investing, collusion generally gives market participants an unfair advantage by discouraging competition.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_111'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_112';
objQuestion.questionID = 111119;
objQuestion.item = 'LOMA_357_PPQ2019_112';
objQuestion.primaryLO = '11E';
objQuestion.textref = 'c. 11, pp. 17-20';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '11E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Ethical guidelines typically outline the responsibilities that investment professionals have towards their clients. For instance, investment professionals should have an established process for making prudent, informed investment decisions. Select the answer choice that describes an investment professional who best demonstrates responsibility toward a client.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Bibi Rincon prepares a portfolio performance report for clients, in which she includes only the date ranges in which her investment decisions outperformed the portfolio’s benchmark.";
arrAnsChoices[1] = "Judd Sorg buys 10,000 shares of a stock at the time of an initial public offering, and allocates the most shares to the portfolios of clients who pay the highest management fees.";
arrAnsChoices[2] = "Margie Tason borrows cash from one of her client accounts to pay her monthly mortgage payment, and manipulates the account to cover her tracks; when she has saved enough money to cover the borrowed amount, she returns the money to the client’s account.";
arrAnsChoices[3] = "Geoff Udell offers three service levels—basic, standard, and premium—to all his clients, who are aware of and can purchase any service level he offers.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 449108;
arrAnsIDs[1] = 449109;
arrAnsIDs[2] = 449110;
arrAnsIDs[3] = 449111;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Disclosures to clients should give clients a complete understanding of how their assets are being managed and how their portfolios are performing. Ms.&nbsp;Rincon engaged in <b>misleading performance reporting</b>, which can give investors an incomplete sense of portfolio performance.</p><p class=\"explanations\">Selectively picking periods of performance to portray investment decisions in the most flattering manner is <b>unethical</b>. For this reason, many investment professionals adhere to a set of reporting standards, such as the CFA Institute’s Global Investment Performance Standards (GIPS).</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Investment professionals are responsible for treating client portfolios fairly, which is a practice known as <b>fair dealing</b>. In other words, an investment professional should not favor one client over another—regardless of the (1) size of a client’s portfolio, (2) amount of revenue the client’s portfolio generates, or (3) quality of the investment professional’s personal relationship with the client.</p><p class=\"explanations\">In this situation, Mr.&nbsp;Sorg is <b>not</b> engaging in fair dealing, because specific client portfolios are receiving <b>preferential treatment</b> based on the fees that they generate. Instead, Mr.&nbsp;Sorg could allocate the shares proportionally based on a specific factor, such as the portfolio’s total asset size. Thus, the portfolios with the largest amounts of total assets would receive the most shares, and so forth.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">In this situation, Ms.&nbsp;Tason has misappropriated funds because she used her access to client funds to pay her mortgage payment. Misappropriation of funds is a fraud that occurs when an individual authorized to handle a customer’s funds illegally alters documents or electronic files to divert funds for personal use, even if the use is on a temporary basis.</p><p class=\"explanations\">Ms.&nbsp;Tason also used her position to alter the client’s records, thus deceiving anyone who needed to see how much cash the account held. Stealing from and defrauding clients are practices that are both <b>unethical and illegal</b>.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Investment professionals are responsible for ensuring that investment actions taken on behalf of a particular client’s portfolio are appropriate for that client; understanding a portfolio’s investment policy statement (IPS) before making decisions that affect its investments; regularly disclosing relevant information to clients; protecting the privacy and confidentiality of their clients; properly handling client funds and safeguarding client assets; and treating clients and client portfolios fairly, which is a practice known as fair dealing.</p><p class=\"explanations\">Fair dealing does not require treating all client accounts equally, however. Investment professionals, such as Mr.&nbsp;Udell, can offer premium services—such as access to specialized alternative investment strategies—to clients as long as all clients are aware of the different service levels and have an opportunity to purchase the additional services offered.</p><p class=\"explanations\"><b>Learning Objective: 11E. Describe some of the responsibilities that investment professionals have to their clients.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_112'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_113';
objQuestion.questionID = 111120;
objQuestion.item = 'LOMA_357_PPQ2019_113';
objQuestion.primaryLO = '11F';
objQuestion.textref = 'c. 11, pp. 23-24';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '11F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">An insurer’s board of directors establishes corporate policies, such as the audit policy, that guide business practices and support internal controls to anticipate and prevent problems. Two types of corporate policies that affect the investment function are investment policies and risk policies. The following statement(s) can correctly be made about these policies:</p><ol type=\"A\" class=\"combo\"><li>An audit policy describes the insurer’s process for systematically examining, testing, and evaluating the insurer’s compliance with one or more specified sets of standards.</li><li>A duration policy typically states the minimum monetary amount of cash and near-cash assets the insurer must hold over a specified period to support its liabilities.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 449112;
arrAnsIDs[1] = 449113;
arrAnsIDs[2] = 449114;
arrAnsIDs[3] = 449115;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct. The audit committee of an insurer’s board of directors assists the board in overseeing the internal audit function, independent external auditors, financial reporting practices, internal controls, ethics, and compliance. Other insurers maintain a separate compliance committee. Regardless of an insurer’s committee structure, the insurer’s board develops a corporate audit policy, which describes the insurer’s control framework for conducting audits—including audits of the asset-liability management (ALM) and investment functions.</p><p class=\"explanations\">Statement B is incorrect. One responsibility of asset-liability management (ALM) is to set policies that constrain investment risk taking. Two such policies are the liquidity policy and the duration policy. A liquidity policy typically states the minimum monetary amount of cash and near-cash assets an insurer must hold over a specified period to support its liabilities. A duration policy specifies a numerical target for an insurer’s duration gap value and a numerical range of acceptable values around the target value. Within the investment function, managers may establish additional risk policies for investment portfolios.</p><p class=\"explanations\"><b>Learning Objective: 11F. Explain how corporate policies—such as an insurer’s investment policies and risk policies—affect the investment function’s activities.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is incorrect. One responsibility of asset-liability management (ALM) is to set policies that constrain investment risk taking. Two such policies are the liquidity policy and the duration policy. A <b>liquidity</b> policy typically states the minimum monetary amount of cash and near-cash assets an insurer must hold over a specified period to support its liabilities. A duration policy specifies a numerical target for an insurer’s duration gap value and a numerical range of acceptable values around the target value. Within the investment function, managers may establish additional risk policies for investment portfolios.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_113'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_114';
objQuestion.questionID = 111121;
objQuestion.item = 'LOMA_357_PPQ2019_114';
objQuestion.primaryLO = '11G';
objQuestion.textref = 'c. 11, p. 24';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '11G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Conducting periodic audits is one part of effective corporate governance. Corporate audit staff perform different types of audits. By definition, a compliance audit is designed to</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "verify that an insurer’s actions adhere to applicable laws and regulatory requirements and to the insurer’s own policies and procedures";
arrAnsChoices[1] = "measure an insurer’s progress toward achieving management objectives for a particular function or goal";
arrAnsChoices[2] = "evaluate whether an insurer’s financial statements are a fair and consistent depiction of the insurer’s financial condition and performance";
arrAnsChoices[3] = "include recommendations on features to add to an insurer’s products to differentiate them from competitive products";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 449116;
arrAnsIDs[1] = 449117;
arrAnsIDs[2] = 449118;
arrAnsIDs[3] = 449119;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">An audit is an examination of a company’s records and operations to evaluate the accuracy of the records and the effectiveness of the company’s operational policies and procedures.</p><p class=\"explanations\">A financial audit evaluates whether an insurer’s financial information, financial statements, and source documents comply with accounting standards and are a fair and consistent depiction of the company’s financial condition and performance. A compliance audit verifies that an insurer’s actions adhere to applicable laws and regulatory requirements and to the company’s own policies and procedures. A performance audit measures and evaluates an insurer’s progress toward achieving management objectives for a particular function or goal and typically includes recommendations for process improvement.</p><p class=\"explanations\"><b>Learning Objective: 11G. Identify the responsibilities of the audit function and describe its role in insurance company compliance.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A <b>performance audit</b> measures and evaluates an insurer’s progress toward achieving management objectives for a particular function or goal and typically includes recommendations for process improvement.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A <b>financial audit</b> evaluates whether an insurer’s financial information, financial statements, and source documents comply with accounting standards and are a fair and consistent depiction of the insurer’s financial condition and performance.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\"><b>Commoditization</b> is the process by which a product reaches a point in its development where it has no features that differentiate it from competitive products other than price. An audit would not address how to market an insurer’s products.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_114'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['11A'] = "11A. Define <i>ethics</i> and explain why ethical standards are important for financial services companies.";
arrlotext['11B'] = "11B. Describe how codes of conduct promote ethical behavior among professionals.";
arrlotext['11C'] = "11C. Explain how conflicts of interest affect investment professionals and identify some common conflicts for investment professionals.";
arrlotext['11D'] = "11D. Explain why insider trading, trading ahead of research, front running, late trading, and collusion are unethical trading practices.";
arrlotext['11E'] = "11E. Describe some of the responsibilities that investment professionals have to their clients.";
arrlotext['11F'] = "11F. Explain how corporate policies—such as an insurer’s investment policies and risk policies—affect the investment function’s activities.";
arrlotext['11G'] = "11G. Identify the responsibilities of the audit function and describe its role in insurance company compliance.";
