var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2019';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 335 Practice Questions, Chapter 5";
var coursename = 'LOMA 335';
var modulenumber = 0;
var title = "LOMA_335_PPQ2019_0_5";
var intNumPools = 1;
var numQ = 13;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Operational Excellence for Insurance Professionals (2019)";
arrNumChap[0] = 1;
var thisChap = '5';

objPool = new Object(); 
objPool.intSelectCount = 13;
objPool.formID = 2062;
objPool.formName = 'PPQ2019_0_5';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_335_PQ_044';
arrPoolQuestions[1] = 'LOMA_335_PQ_045';
arrPoolQuestions[2] = 'LOMA_335_PQ_046';
arrPoolQuestions[3] = 'LOMA_335_PQ_047';
arrPoolQuestions[4] = 'LOMA_335_PQ_048';
arrPoolQuestions[5] = 'LOMA_335_PQ_049';
arrPoolQuestions[6] = 'LOMA_335_PQ_050';
arrPoolQuestions[7] = 'LOMA_335_PQ_051';
arrPoolQuestions[8] = 'LOMA_335_PQ_052';
arrPoolQuestions[9] = 'LOMA_335_PQ_053';
arrPoolQuestions[10] = 'LOMA_335_PQ_054';
arrPoolQuestions[11] = 'LOMA_335_PQ_055';
arrPoolQuestions[12] = 'LOMA_335_PQ_056';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_044';
objQuestion.questionID = 109332;
objQuestion.item = 'LOMA_335_PPQ2019_044';
objQuestion.primaryLO = '5A';
objQuestion.textref = 'c. 5, pp. 2-3';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '5A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statement(s) can correctly be made about the characteristics of a project:</p><ol type=\"A\" class=\"combo\"><li>A project must have clearly defined objectives.</li><li>A project is an ongoing series of operations or work activities.</li><li>The aspects of a project are likely to change over time.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A, B, and C";
arrAnsChoices[1] = "A and B only";
arrAnsChoices[2] = "A and C only";
arrAnsChoices[3] = "B and C only";
arrAnsChoices[4] = "C only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441860;
arrAnsIDs[1] = 441861;
arrAnsIDs[2] = 441862;
arrAnsIDs[3] = 441863;
arrAnsIDs[4] = 441864;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct; however, Statement B is incorrect. A project is a <b>temporary</b>, planned undertaking to achieve a specified result. A project has a beginning point and an ending point. A <b>process</b> is an ongoing series of operations or work activities.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Clearly defined objectives are perhaps the most important precursor to project success. When a project’s team members do not understand what the project is supposed to accomplish, the project is likely to fail. Unlike a process, which is an ongoing series of operations or work activities, a project is a temporary, planned undertaking to achieve a specified end-result. The aspects of a project are likely to change over time, such as initial assumptions. </p><p class=\"explanations\"><b>Learning Objective: 5A. Explain the characteristics of a project and the role of project managers.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Statement C is correct; however, Statement B is incorrect. A project is a <b>temporary</b>, planned undertaking to achieve a specified result. A project has a beginning point and an ending point. A <b>process</b> is an ongoing series of operations or work activities.</p>";
arrAnswerFeedback[4] = "<p class=\"explanations\">Statement C is correct; however, it is not the only correct statement.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_044'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_045';
objQuestion.questionID = 109333;
objQuestion.item = 'LOMA_335_PPQ2019_045';
objQuestion.primaryLO = '5A';
objQuestion.textref = 'c. 5, pp. 3, 6, 9';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '5A';
arrLOs[1] = '5B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The individuals described below have specific roles on a project team assembled to design a new underwriting administration system for the Bayview Insurance Company:</p><ul class=\"examul\"><li>David Avren, Senior Vice President, Individual Life, authorized this project, provides supportive resources for it, and communicates project information up the organizational chain of command.</li><li>Judy Lynch is responsible for overseeing the project team. Ms.&nbsp;Lynch is accountable for planning, organizing, directing, and controlling resources to achieve the project’s established goals.</li></ul><p class=\"stem\">The following statement(s) can correctly be made about this situation:</p><ol type=\"A\" class=\"combo\"><li>In terms of project roles, Mr.&nbsp;Avren is the project manager and Ms.&nbsp;Lynch is the project sponsor.</li><li>Both Mr.&nbsp;Avren and Ms.&nbsp;Lynch are project stakeholders.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441865;
arrAnsIDs[1] = 441866;
arrAnsIDs[2] = 441867;
arrAnsIDs[3] = 441868;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is incorrect because <b>Ms.&nbsp;Lynch</b> is the project manager and <b>Mr.&nbsp;Avren</b> is the project sponsor.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement A is incorrect because <b>Ms.&nbsp;Lynch</b> is the project manager and <b>Mr.&nbsp;Avren</b> is the project sponsor.</p><p class=\"explanations\">Statement B is correct because project stakeholders are internal and external parties who have an interest in a project and expect to benefit from it. Other examples of project stakeholders are employees whose duties are associated with the project, members of a department that gains a new capability, a customer who gains a new service, and a vendor who sells services involved in completing the project.</p><p class=\"explanations\"><b>Learning Objective: (1) 5A. Explain the characteristics of a project and the role of project managers; (2) 5B. Define the phases of a project lifecycle and describe activities involved in each phase.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_045'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_046';
objQuestion.questionID = 109334;
objQuestion.item = 'LOMA_335_PPQ2019_046';
objQuestion.primaryLO = '5B';
objQuestion.textref = 'c. 5, pp. 7, 11';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '5B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The managers responsible for a project need to establish a <b>(business case / baseline)</b>, which is a justification for a proposed project that highlights how a project’s benefits to the company will outweigh its costs and risks. Project planning begins with <b>(a scope statement / an activity analysis)</b>, which is a report that clearly states the limits on the project by specifying the project size, resources, limitations, and deliverables. </p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "business case / a scope statement";
arrAnsChoices[1] = "business case / an activity analysis";
arrAnsChoices[2] = "baseline / a scope statement";
arrAnsChoices[3] = "baseline / an activity analysis";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441869;
arrAnsIDs[1] = 441870;
arrAnsIDs[2] = 441871;
arrAnsIDs[3] = 441872;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Larger or complex projects need a business case to convince the key decision maker that the project is worth pursuing. The management responsible for the team or unit proposing the project usually develops the business case. The project manager, project sponsor, project team members, and other stakeholders can all contribute to the information in a scope statement.</p><p class=\"explanations\"><b>Learning Objectives: 5B. Define the phases of a project lifecycle and describe activities involved in each phase.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is correct to say that a business case is a justification for a proposed project that highlights how a project’s benefits to the company will outweigh its costs and risks. However, the report that clearly states the limits on the project by specifying the project size, resources, limitations, and deliverables is <b>not </b>known as an activity analysis. An activity analysis is a report that documents the expected tasks and estimated time for completing a given activity, based on observation of or interviews with an individual performing the activity.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is correct to say that a scope statement clearly states the limits on the project by specifying the project size, resources, limitations, and deliverables. However, a justification for a proposed project that highlights how a project’s benefits to the company will outweigh its costs and risks is <b>not </b>a baseline. A project baseline is a measurable starting point agreed upon by various stakeholders as performance standards for a project.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A justification for a proposed project that highlights how a project’s benefits to the company will outweigh its costs and risks is <b>not </b>a baseline. A project baseline is a measurable starting point agreed upon by various stakeholders as performance standards for a project.</p><p class=\"explanations\">Also, a report that clearly states limits on the project by specifying the project size, resources, limitations, and deliverables is <b>not </b>known as an activity analysis. An activity analysis is a report that documents the expected tasks and estimated time for completing a given activity, based on observation of or interviews with an individual performing the activity.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_046'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_047';
objQuestion.questionID = 109335;
objQuestion.item = 'LOMA_335_PPQ2019_047';
objQuestion.primaryLO = '5B';
objQuestion.textref = 'c. 5, p. 8';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '5B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Fountain Insurance Company executed a document that formally authorizes a project to take place and appoints a project manager. This document identifies the business purpose of the project and grants appropriate authority to the project manager to move the project to the planning phase. This document is known as a</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "project schedule";
arrAnsChoices[1] = "project objective";
arrAnsChoices[2] = "project charter";
arrAnsChoices[3] = "work breakdown structure (WBS)";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441873;
arrAnsIDs[1] = 441874;
arrAnsIDs[2] = 441875;
arrAnsIDs[3] = 441876;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A project schedule is a document that shows links between project elements, notes dependencies, and shows a sequence that satisfies time and other constraints. </p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A project objective is a statement about how the company will accomplish the project goal. </p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Once a business case receives approval, the project takes its formal identity from either the project charter or a contractual agreement, depending on whether the project is internal or encompasses more than one business entity. For a project performed under contract by an external vendor, a contractual agreement covers the rights and obligations of the parties. For an internal project, companies use project charters.</p><p class=\"explanations\"><b>Learning Objective: 5B. Define the phases of a project lifecycle and describe activities involved in each phase.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A work breakdown structure (WBS) is a graphical display of project elements that often includes an estimate of the labor effort required for each project activity. A detailed WBS might include the availability and cost for each required resource. </p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_047'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_048';
objQuestion.questionID = 109336;
objQuestion.item = 'LOMA_335_PPQ2019_048';
objQuestion.primaryLO = '5B';
objQuestion.textref = 'c. 5, pp. 11, 13, 28, 30';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '5B';
arrLOs[1] = '5G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about the project management lifecycle. Three statements are true, and one statement is false. Select the answer choice containing the <B>FALSE</B> statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A project deliverable is a measurable outcome from a project.";
arrAnsChoices[1] = "The driving constraint identified within a project plan represents the least important obstacle to project success or the most flexible measure.";
arrAnsChoices[2] = "A project manager will negotiate project changes with project stakeholders and revise the schedule whenever significant new schedule-related information becomes available.";
arrAnsChoices[3] = "During the closure phase, most team members have transitioned to other projects, leaving the project manager to wrap up.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441877;
arrAnsIDs[1] = 441878;
arrAnsIDs[2] = 441879;
arrAnsIDs[3] = 441880;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">This statement is false; therefore, it is the correct response. The driving constraint is the number-one priority and the driving force behind the success of the project. The project will fail if the team does not meet this constraint. The <b>weak </b>constraint represents the least important (lowest-priority) obstacle to project success or the most flexible measure.</p><p class=\"explanations\"><b>Learning Objectives: (1) 5B. Define the phases of a project lifecycle and describe activities involved in each phase; (2) 5G. Describe alternative approaches to execution and control including agile management and earned value management.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_048'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_049';
objQuestion.questionID = 109337;
objQuestion.item = 'LOMA_335_PPQ2019_049';
objQuestion.primaryLO = '5B';
objQuestion.textref = 'c. 5, p. 14';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '5B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Project managers sometimes conduct an activity analysis to determine how the activities in a project relate. A minimum time for each major activity <b>(is / is not)</b> necessary to create a project schedule. Activities that cannot be started until other activities have been completed are <b>(dependent / independent) </b>activities. </p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "is / dependent ";
arrAnsChoices[1] = "is / independent ";
arrAnsChoices[2] = "is not / dependent ";
arrAnsChoices[3] = "is not / independent ";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441881;
arrAnsIDs[1] = 441882;
arrAnsIDs[2] = 441883;
arrAnsIDs[3] = 441884;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The minimum time required to complete a project is the sum of the minimum durations for all project activities. Therefore, a minimum time for each major activity is necessary to create a project schedule. Relationships between project activities help establish the order of the activities in the schedule. For this reason, scheduling requires a project manager to determine whether activities are independent or dependent. </p><p class=\"explanations\">Pairs of activities that can progress concurrently with no change to resource needs are called independent activities. Activities that cannot be started until other activities have been completed are dependent activities.</p><p class=\"explanations\"><b>Learning Objective: 5B. Define the phases of a project lifecycle and describe activities involved in each phase.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is correct to say that a minimum time for each major activity is necessary to create a project schedule; however, activities that cannot be started until other activities have been completed are <b>dependent activities</b>. Independent activities are pairs of activities that can progress concurrently with no change to resource needs.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is correct to say that activities that cannot be started until other activities have been completed are dependent activities; however, a minimum time for each major activity <b>is</b> necessary to create a project schedule.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A minimum time for each major activity <b>is</b> necessary to create a project schedule. Also, activities that cannot be started until other activities have been completed are <b>dependent activities</b>. Independent activities are pairs of activities that can progress concurrently with no change to resource needs </p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_049'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_050';
objQuestion.questionID = 109338;
objQuestion.item = 'LOMA_335_PPQ2019_050';
objQuestion.primaryLO = '5C';
objQuestion.textref = 'c. 5, p. 16';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '5C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">A flow chart shows the systematic progression of a series of activities using connecting lines and conventional symbols. For instance, an <i>oval </i>symbol in a flow chart represents</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "an important activity";
arrAnsChoices[1] = "the flow of a project";
arrAnsChoices[2] = "a starting or stopping point";
arrAnsChoices[3] = "a yes/no decision point";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441885;
arrAnsIDs[1] = 441886;
arrAnsIDs[2] = 441887;
arrAnsIDs[3] = 441888;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A <b>box</b> represents an important activity.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">An<b> arrow</b> represents the flow of a project.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">An oval represents a starting or stopping point in a process. A box represents an important activity. A diamond indicates a yes/no decision point. A circle represents a point at which the flow chart connects with another process. An arrow represents the flow of a project.</p><p class=\"explanations\"><b>Learning Objective: 5C. Describe tools used in project planning, including Gantt charts, baselines, and schedules.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A <b>diamond</b> indicates a yes/no decision point.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_050'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_051';
objQuestion.questionID = 109339;
objQuestion.item = 'LOMA_335_PPQ2019_051';
objQuestion.primaryLO = '5C';
objQuestion.textref = 'c. 5, pp. 19, 27';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '5C';
arrLOs[1] = '5G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statement(s) can correctly be made about project management tools:</p><ol type=\"A\" class=\"combo\"><li>Earned Value Management (EVM) involves expressing physical progress toward project completion in monetary units.</li><li>On a stoplight Gantt chart, a yellow (or amber) stoplight indicates that a project is receiving corrective action from the project manager.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441889;
arrAnsIDs[1] = 441890;
arrAnsIDs[2] = 441891;
arrAnsIDs[3] = 441892;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct. Using EVM, a project team can quickly grasp the summary aspects of feedback expressed in monetary units. Moreover, project managers and team members can gauge a current project’s performance by comparing its monetary values against those produced by past projects.</p><p class=\"explanations\">Statement B is incorrect because a yellow (or amber) stoplight indicates that a project is perhaps not entirely on schedule, but has not met criteria for intervention. A <b>red </b>stoplight indicates that a project is receiving corrective action from the project manager. A green stoplight indicates that a row for an activity is on schedule or ahead of schedule.</p><p class=\"explanations\"><b>Learning Objective: (1) 5C. Describe tools used in project planning, including Gantt charts, baselines, and schedules; (2) 5G. Describe alternative approaches to execution and control including agile management and earned value management.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is incorrect because a yellow stoplight indicates that a project is perhaps not entirely on schedule, but has not met criteria for intervention. A <b>red </b>stoplight indicates that a project is receiving corrective action from the project manager. </p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_051'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_052';
objQuestion.questionID = 109340;
objQuestion.item = 'LOMA_335_PPQ2019_052';
objQuestion.primaryLO = '5D';
objQuestion.textref = 'c. 5, pp. 19-20';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '5D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Kim Blask is calculating the expected time for a project activity. Ms.&nbsp;Blask developed the following time estimates:</p><table align=\"center\" cellspacing=\"0\" width=\"95%\" class=\"indent\"><tr><td valign=\"top\">Optimistic time (<i>t<SUB STYLE=\"VERTICAL-ALIGN: BASELINE; POSITION: RELATIVE; TOP: 0.4EM; LINE-HEIGHT: 0EM; FONT-SIZE: 0.8EM;\">O</SUB></i>) = 7 days</td></tr><tr><td valign=\"top\">Most probable time (<i>t<SUB STYLE=\"VERTICAL-ALIGN: BASELINE; POSITION: RELATIVE; TOP: 0.4EM; LINE-HEIGHT: 0EM; FONT-SIZE: 0.8EM;\">M</SUB></i>) = 24 days</td></tr><tr><td valign=\"top\">Pessimistic time (<i>t<SUB STYLE=\"VERTICAL-ALIGN: BASELINE; POSITION: RELATIVE; TOP: 0.4EM; LINE-HEIGHT: 0EM; FONT-SIZE: 0.8EM;\">P</SUB></i>) = 29 days</td></tr></table><p class=\"stem\">For this project activity, the expected time (<i>t<SUB STYLE=\"VERTICAL-ALIGN: BASELINE; POSITION: RELATIVE; TOP: 0.4EM; LINE-HEIGHT: 0EM; FONT-SIZE: 0.8EM;\">E</SUB></i>) is approximately</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "20.0 days";
arrAnsChoices[1] = "22.0 days";
arrAnsChoices[2] = "24.5 days";
arrAnsChoices[3] = "44.0 days";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441893;
arrAnsIDs[1] = 441894;
arrAnsIDs[2] = 441895;
arrAnsIDs[3] = 441896;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The expected time (<i>t<SUB STYLE=\"VERTICAL-ALIGN: BASELINE; POSITION: RELATIVE; TOP: 0.4EM; LINE-HEIGHT: 0EM; FONT-SIZE: 0.8EM;\">E</SUB></i>) for an activity is a weighted average of the optimistic time, most probable time, and the pessimistic time. It is called the <i>weighted</i> average because the most probable time is given more <i>weight</i> than the other two less probable values. The most probable time (<i>t<SUB STYLE=\"VERTICAL-ALIGN: BASELINE; POSITION: RELATIVE; TOP: 0.4EM; LINE-HEIGHT: 0EM; FONT-SIZE: 0.8EM;\">M</SUB></i>) is <b>multiplied by 4 </b>to give it a greater weight in the results. When calculating the average, remember to <b>divide by 6 </b>to properly reflect the total number of items used to calculate the average.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The expected time (<i>t<SUB STYLE=\"VERTICAL-ALIGN: BASELINE; POSITION: RELATIVE; TOP: 0.4EM; LINE-HEIGHT: 0EM; FONT-SIZE: 0.8EM;\">E</SUB></i>) for an activity is a weighted average of the optimistic time, most probable time, and the pessimistic time. In this formula, [<i>t<SUB STYLE=\"VERTICAL-ALIGN: BASELINE; POSITION: RELATIVE; TOP: 0.4EM; LINE-HEIGHT: 0EM; FONT-SIZE: 0.8EM;\">O</SUB></i> + 4<i>t<SUB STYLE=\"VERTICAL-ALIGN: BASELINE; POSITION: RELATIVE; TOP: 0.4EM; LINE-HEIGHT: 0EM; FONT-SIZE: 0.8EM;\">M</SUB></i> + <i>t<SUB STYLE=\"VERTICAL-ALIGN: BASELINE; POSITION: RELATIVE; TOP: 0.4EM; LINE-HEIGHT: 0EM; FONT-SIZE: 0.8EM;\">P</SUB></i>] / 6, the most probable time (<i>t<SUB STYLE=\"VERTICAL-ALIGN: BASELINE; POSITION: RELATIVE; TOP: 0.4EM; LINE-HEIGHT: 0EM; FONT-SIZE: 0.8EM;\">M</SUB></i>), is multiplied by 4 to give it a greater weight in the results. Thus, [7 + 4(24) + 29] / 6, or 22 days.</p><p class=\"explanations\"><b>Learning Objective: 5D. Estimate the expected time for an activity using a weighted average method to blend an optimistic, a most probable, and a pessimistic estimate.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The expected time (<i>t<SUB STYLE=\"VERTICAL-ALIGN: BASELINE; POSITION: RELATIVE; TOP: 0.4EM; LINE-HEIGHT: 0EM; FONT-SIZE: 0.8EM;\">E</SUB></i>) for an activity is a weighted average of the optimistic time, most probable time, and the pessimistic time. It is called the <i>weighted</i> average because the most probable time is given more <i>weight</i> than the other two less probable values. The most probable time (<i>t<SUB STYLE=\"VERTICAL-ALIGN: BASELINE; POSITION: RELATIVE; TOP: 0.4EM; LINE-HEIGHT: 0EM; FONT-SIZE: 0.8EM;\">M</SUB></i>) is <b>multiplied by 4 </b>to give it a greater weight in the results. When calculating the average, remember to <b>divide by 6 </b>to properly reflect the total number of items used to calculate the average.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The expected time (<i>t<SUB STYLE=\"VERTICAL-ALIGN: BASELINE; POSITION: RELATIVE; TOP: 0.4EM; LINE-HEIGHT: 0EM; FONT-SIZE: 0.8EM;\">E</SUB></i>) for an activity is a weighted average of the optimistic time, most probable time, and the pessimistic time. It is called the <i>weighted</i> average because the most probable time is given more <i>weight</i> than the other two less probable values. The most probable time (<i>t<SUB STYLE=\"VERTICAL-ALIGN: BASELINE; POSITION: RELATIVE; TOP: 0.4EM; LINE-HEIGHT: 0EM; FONT-SIZE: 0.8EM;\">M</SUB></i>) is <b>multiplied by 4 </b>to give it a greater weight in the results. When calculating the average, remember to <b>divide by 6 </b>to properly reflect the total number of items used to calculate the average.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_052'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_053';
objQuestion.questionID = 109341;
objQuestion.item = 'LOMA_335_PPQ2019_053';
objQuestion.primaryLO = '5E';
objQuestion.textref = 'c. 5, pp. 20-22';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '5E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = 2;
objQuestion.strStem = "<p class=\"stem\">Select the answer choice that correctly identifies the critical path and the number of days needed to complete the critical path.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[-1] = "<u>Critical path</u></div><div class=\"anshead\"><u>Number of days</u>";
arrAnsChoices[0] = "A-B-C-D-F-G-H</div><div class=\"anscell\" onclick=\"recordAns(1);\">50";
arrAnsChoices[1] = "A-B-C-D-F-G-H</div><div class=\"anscell\" onclick=\"recordAns(2);\">85";
arrAnsChoices[2] = "A-B-E-G-H</div><div class=\"anscell\" onclick=\"recordAns(3);\">50";
arrAnsChoices[3] = "A-B-E-G-H</div><div class=\"anscell\" onclick=\"recordAns(4);\">85";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441898;
arrAnsIDs[1] = 441899;
arrAnsIDs[2] = 441900;
arrAnsIDs[3] = 441901;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">There are two paths in this model. To find the critical path, calculate the sum of expected time for activities on each network path to determine the total expected time for completion of each alternative network path. The network path with the longest expected time is the critical path. In this network model, the sum of the expected times for A-B-C-D-F-G-H is 50 days, and the sum of the expected times for A-B-E-G-H is 85 days.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">There are two paths in this model. To find the critical path, calculate the sum of expected time for activities on each network path to determine the total expected time for completion of each alternative network path. The network path with the longest expected time is the critical path. In this network model, the sum of the expected times for A-B-C-D-F-G-H is 50 days, and the sum of the expected times for A-B-E-G-H is 85 days.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">There are two paths in this model. To find the critical path, calculate the sum of expected time for activities on each network path to determine the total expected time for completion of each alternative network path. The network path with the longest expected time is the critical path. In this network model, the sum of the expected times for A-B-C-D-F-G-H is 50 days, and the sum of the expected times for A-B-E-G-H is 85 days.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">There are two paths in this model. To find the critical path, calculate the sum of expected time for activities on each network path to determine the total expected time for completion of each alternative network path. The network path with the longest expected time is the critical path. In this network model, the sum of the expected times for A-B-C-D-F-G-H is 50 days, and the sum of the expected times for A-B-E-G-H is 85 days.</p><p class=\"explanations\"><b>Learning Objective: 5E. Interpret a network model using network analysis, including finding a critical path and calculating float for noncritical paths.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_053'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_054';
objQuestion.questionID = 109342;
objQuestion.item = 'LOMA_335_PPQ2019_054';
objQuestion.primaryLO = '5E';
objQuestion.textref = 'c. 5, p. 23';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '5E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = 2;
objQuestion.strStem = "<p class=\"stem\">With regard to the amount of float in this project, it is correct to say that</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "there is no float in this network model";
arrAnsChoices[1] = "there is no float in path A-B-C-D-F-G-H";
arrAnsChoices[2] = "the float for path A-B-C-D-F-G-H is 35 days";
arrAnsChoices[3] = "the float for path A-B-E-G-H is 35 days";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441902;
arrAnsIDs[1] = 441903;
arrAnsIDs[2] = 441904;
arrAnsIDs[3] = 441905;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Float, also known as slack time, is the length of time that an activity can be delayed without delaying the entire project. No activity on the critical path can have float, but any other network activity can have float. One of these paths has float.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Float, also known as slack time, is the length of time that an activity can be delayed without delaying the entire project. No activity on the critical path can have float, but any other network activity can have float. In this case, A-B-C-D-F-G-H is not the critical path and <b>does </b>have float.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Float, also known as slack time, is the length of time that an activity can be delayed without delaying the entire project. No activity on the critical path can have float, but any other network activity can have float. In this situation, A-B-C-D-F-G-H is not the critical path and does have float. The time for path A-B-C-D-F-G-H is 50 days, and the time for the critical path is 85 days; therefore, the float is 85 – 50 = 35.</p><p class=\"explanations\"><b>Learning Objective: 5E. Interpret a network model using network analysis, including finding a critical path and calculating float for noncritical paths.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Float, also known as slack time, is the length of time that an activity can be delayed without delaying the entire project. No activity on the critical path can have float, but any other network activity can have float. In this situation, A-B-E-G-H is the <b>critical path </b>and, therefore, cannot have float.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_054'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_055';
objQuestion.questionID = 109343;
objQuestion.item = 'LOMA_335_PPQ2019_055';
objQuestion.primaryLO = '5F';
objQuestion.textref = 'c. 5, p. 28';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '5F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">A project sometimes experiences scope creep. The presence of scope creep most likely indicates that the</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "driving constraint for the project has been misidentified";
arrAnsChoices[1] = "features and objectives of the project have been modified, but these changes have not been formally addressed and negotiated with project stakeholders";
arrAnsChoices[2] = "project was initiated without creating a project charter";
arrAnsChoices[3] = "project manager has identified a schedule variance within the project";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441906;
arrAnsIDs[1] = 441907;
arrAnsIDs[2] = 441908;
arrAnsIDs[3] = 441909;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Prioritizing the constraints correctly is an important part of project planning, but it is <b>not </b>related to scope creep.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Scope creep refers to gradually modifying features of a project and its objectives without formally addressing and negotiating changes with project stakeholders. When a project moves too far beyond its original plans, boundaries become difficult to maintain. A lack of defined boundaries makes it harder to achieve project goals. To minimize scope creep, changes in project objectives or constraints should be negotiated, approved, and reflected in the project plan documents.</p><p class=\"explanations\"><b>Learning Objective: 5F. Provide examples of reasons for project change and give strategies for managing project changes.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">For an internal project, a project charter is a document that formally authorizes the project to take place and appoints a project manager. A project charter identifies the business purpose of the project and grants appropriate authority to the project management to move the project to the planning phase. Although a project charter is important, the absence of a project charter is <b>not </b>described as scope creep.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A schedule variance is the difference between the scheduled finish date for an activity and the actual finish date. Scope creep describes a different type of project management problem.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_055'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_056';
objQuestion.questionID = 109344;
objQuestion.item = 'LOMA_335_PPQ2019_056';
objQuestion.primaryLO = '5H';
objQuestion.textref = 'c. 5, p. 32';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '5H';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statement(s) can correctly be made about the project portfolio management (PPM) approach:</p><ol type=\"A\" class=\"combo\"><li>In a PPM approach, a committee analyses a project for both its intrinsic benefits to the organization and for its relative fit with the organization’s existing resources, processes, and projects.</li><li>Under the PPM approach, a project cannot be ended before its completion even if expected benefits do not seem to outweigh expected costs.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441910;
arrAnsIDs[1] = 441911;
arrAnsIDs[2] = 441912;
arrAnsIDs[3] = 441913;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct. The PPM approach consists of treating all company projects as a project portfolio and coordinating all projects with one another across the company.</p><p class=\"explanations\">Statement B is incorrect because, under the PPM approach, a project could be ended before its completion if expected benefits do not seem to outweigh expected costs. The PPM approach advocates ending an ongoing project before its completion if, during project implementation, circumstances change so that the project becomes less attractive than it once seemed.</p><p class=\"explanations\"><b>Learning Objective: 5H. Explain the value of using the project portfolio management approach to project management.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is incorrect because, under the PPM approach, a project <b>could</b> be ended before its completion if expected benefits do not seem to outweigh expected costs.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct. </p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_056'] = objQuestion;



arrMinicases[2] = "<p class=\"caseinfo\">Use the following information to answer questions 10 and 11.</p><p class=\"caseinfo\">Todd Lester developed the following network model to analyze a project:</p><p class=\"caseinfo\" style=\"text-align: center\"><img alt=\"\" src=\"media/imgs/LOMA_335_PPQ2019_English_01.png\" /></p>";


var arrlotext = new Array(); 
arrlotext['5A'] = "5A. Explain the characteristics of a project and the role of project managers.";
arrlotext['5B'] = "5B. Define the phases of a project lifecycle and describe activities involved in each phase.";
arrlotext['5C'] = "5C. Describe tools used in project planning, including Gantt charts, baselines, and schedules.";
arrlotext['5D'] = "5D. Estimate the expected time for an activity using a weighted average method to blend an optimistic, a most probable, and a pessimistic estimate.";
arrlotext['5E'] = "5E. Interpret a network model using network analysis, including finding a critical path and calculating float for noncritical paths.";
arrlotext['5F'] = "5F. Provide examples of reasons for project change and give strategies for managing project changes.";
arrlotext['5G'] = "5G. Describe alternative approaches to execution and control including agile management and earned value management.";
arrlotext['5H'] = "5H. Explain the value of using the project portfolio management approach to project management.";
