var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2019';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 335 Practice Questions, Chapter 6";
var coursename = 'LOMA 335';
var modulenumber = 0;
var title = "LOMA_335_PPQ2019_0_6";
var intNumPools = 1;
var numQ = 8;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Operational Excellence for Insurance Professionals (2019)";
arrNumChap[0] = 1;
var thisChap = '6';

objPool = new Object(); 
objPool.intSelectCount = 8;
objPool.formID = 2062;
objPool.formName = 'PPQ2019_0_6';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_335_PQ_057';
arrPoolQuestions[1] = 'LOMA_335_PQ_058';
arrPoolQuestions[2] = 'LOMA_335_PQ_059';
arrPoolQuestions[3] = 'LOMA_335_PQ_060';
arrPoolQuestions[4] = 'LOMA_335_PQ_061';
arrPoolQuestions[5] = 'LOMA_335_PQ_062';
arrPoolQuestions[6] = 'LOMA_335_PQ_063';
arrPoolQuestions[7] = 'LOMA_335_PQ_064';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_057';
objQuestion.questionID = 109345;
objQuestion.item = 'LOMA_335_PPQ2019_057';
objQuestion.primaryLO = '6A';
objQuestion.textref = 'c. 6, pp. 2, 3';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '6A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Quality is one of the primary tenets of successful operations management. The following statement(s) can correctly be made about quality: </p><ol type=\"A\" class=\"combo\"><li>A customer often associates the quality of an insurance product with the experts who help the customer navigate the consequences of a loss. </li><li>Having the attributes of quality generally is enough to differentiate one insurance company from the next when it comes to customer satisfaction.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441914;
arrAnsIDs[1] = 441915;
arrAnsIDs[2] = 441916;
arrAnsIDs[3] = 441917;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct. Every product or service must have few failures and have the right features to satisfy customer needs. When it comes to insurance, the customer’s greatest need often occurs at the time of a loss. </p><p class=\"explanations\">Statement B is incorrect. Customers expect insurers to demonstrate certain attributes of quality. Therefore, having these attributes does <b>not</b> differentiate one company from the next. </p><p class=\"explanations\"><b>Learning Objective: 6A. Identify the prevailing quality management standards and the seven principles of quality management.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is incorrect. Customers expect insurers to demonstrate certain attributes of quality. Therefore, having these attributes does <b>not</b> differentiate one company from the next.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct. </p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_057'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_058';
objQuestion.questionID = 109346;
objQuestion.item = 'LOMA_335_PPQ2019_058';
objQuestion.primaryLO = '6A';
objQuestion.textref = 'c. 6, pp. 3-4';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '6A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The International Organization for Standardization (ISO) 9000 bases its standards on seven principles of quality management. By definition, a company is adhering to the principle of leadership when the company</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "focuses on continuous improvement in all areas";
arrAnsChoices[1] = "strives to exceed customer expectations in all customer interactions";
arrAnsChoices[2] = "establishes a clear vision and inspires a company-wide commitment to quality";
arrAnsChoices[3] = "knows who its stakeholders are and establishes strong relationships with them";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441918;
arrAnsIDs[1] = 441919;
arrAnsIDs[2] = 441920;
arrAnsIDs[3] = 441921;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The principle of <b>improvement</b> focuses on continuous improvement. Quality is unsustainable without continuous improvement because a company’s internal and external environments change constantly.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">According to the principle of <b>customer focus</b>, quality is about (1) meeting customer needs and (2) aiming to exceed customer expectations in all company interactions.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Effective leaders use their people skills to establish a clear vision and inspire a company-wide commitment to quality. Effective leadership also ensures that employees have the training and resources necessary for them to deliver their best work. </p><p class=\"explanations\"><b>Learning Objective</b>: <b>6A. Identify the prevailing quality management standards and the seven principles of quality management.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The principle of <b>relationship management</b> requires companies to know who their stakeholders are and establish strong stakeholder relationships. </p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_058'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_059';
objQuestion.questionID = 109347;
objQuestion.item = 'LOMA_335_PPQ2019_059';
objQuestion.primaryLO = '6B';
objQuestion.textref = 'c. 6, p. 6';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '6B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Several attributes of service quality are common to all types of customer service. The following statements describe quality standards that measure specific attributes of service quality. Select the statement that best represents a quality standard for the attribute of first contact resolution.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "95% of cases should be completed by only one employee in a single conversation.";
arrAnsChoices[1] = "No more than 0.05% of medical services claims denied should be incorrectly denied.";
arrAnsChoices[2] = "There should be a maximum of 14 days from policy application to policy issue.";
arrAnsChoices[3] = "No more than 15% of life insurance applications should be received in new business with incomplete paperwork.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441922;
arrAnsIDs[1] = 441923;
arrAnsIDs[2] = 441924;
arrAnsIDs[3] = 441925;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A company must set standards for its products and services; deliver, track, and evaluate results; and take actions to correct identified defects. </p><p class=\"explanations\"><b>Learning Objective: 6B. Describe the phases of the quality control cycle and explain some of the activities involved during each phase.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">This statement represents a quality standard for the attribute of <b>accuracy</b>. </p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">This statement represents a quality standard for the attribute of <b>wait time for policy issue</b>.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">This statement represents a quality standard for the attribute of <b>accuracy</b>.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_059'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_060';
objQuestion.questionID = 109348;
objQuestion.item = 'LOMA_335_PPQ2019_060';
objQuestion.primaryLO = '6B';
objQuestion.textref = 'c. 6, p. 8';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '6B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">One way to establish accountability is by using quality circles (QCs). With regard to whether QCs are permanent or temporary and whether membership in the group is designated or voluntary, it is correct to say that QCs are often</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "permanent and designated";
arrAnsChoices[1] = "permanent and voluntary";
arrAnsChoices[2] = "temporary and designated";
arrAnsChoices[3] = "temporary and voluntary";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441926;
arrAnsIDs[1] = 441927;
arrAnsIDs[2] = 441928;
arrAnsIDs[3] = 441929;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Quality circles are often <b>temporary</b> and <b>voluntary</b>.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is correct to say that quality circles are often voluntary; however, they are often<b> temporary</b>. </p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is correct to say that quality circles are often temporary; however, they are often <b>voluntary</b>.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A quality circle (QC) is a problem-solving group of five to 10 employees who meet regularly to discuss quality improvement, suggest ways to reduce costs, and present recommendations to management. QCs make decisions by consensus, which is an approach that requires all group members to understand and accept a solution before jointly choosing the course of action. </p><p class=\"explanations\"><b>Learning Objective: 6B. Describe the phases of the quality control cycle and explain some of the activities involved during each phase.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_060'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_061';
objQuestion.questionID = 109349;
objQuestion.item = 'LOMA_335_PPQ2019_061';
objQuestion.primaryLO = '6C';
objQuestion.textref = 'c. 6, p. 9';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '6C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Performance indicators typically found on a performance dashboard for an insurance company include business process metrics, financial metrics, and new business metrics. One example of a <i>financial metric</i> is </p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "new product sales as a percentage of new business";
arrAnsChoices[1] = "underwriting response time";
arrAnsChoices[2] = "the number of claims paid daily";
arrAnsChoices[3] = "cash on hand";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441930;
arrAnsIDs[1] = 441931;
arrAnsIDs[2] = 441932;
arrAnsIDs[3] = 441933;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">New product sales as a percentage of new business is an example of a <b>new business metric</b>.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Underwriting response time is an example of a <b>business process metric</b>.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The number of claims paid daily is an example of a <b>business process metric</b>.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Examples of financial metrics are cash on hand, economic capital, and uncommitted capital.</p><p class=\"explanations\"><b>Learning Objective: 6C. Explain how performance dashboards can be linked to reports such as cascading reports, parent reports, child reports, and control charts to deliver information to various levels of an organization.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_061'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_062';
objQuestion.questionID = 109350;
objQuestion.item = 'LOMA_335_PPQ2019_062';
objQuestion.primaryLO = '6D';
objQuestion.textref = 'c. 6, pp. 14-15';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '6D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Pareto analysis and a fishbone diagram are two quality tools that companies can use to identify and analyze quality defects. According to the Pareto principle, <b>(not all</b> / <b>all)</b> factors in a situation contribute equally to an outcome. In a fishbone diagram that arranges the problem chronologically, the most recent potential cause is closest to the <b>(fish head / fish tail)</b>. </p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "not all / fish head";
arrAnsChoices[1] = "not all / fish tail";
arrAnsChoices[2] = "all / fish head";
arrAnsChoices[3] = "all / fish tail";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441934;
arrAnsIDs[1] = 441935;
arrAnsIDs[2] = 441936;
arrAnsIDs[3] = 441937;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The Pareto principle states that a small percentage of causes contributes to a large percentage of the results. A similar guideline, the 80-20 principle, expands the Pareto principle to other situations and states that, in any given situation, 20 percent of the components of a situation account for 80 percent of the outcome. As a result, when faced with a problem, a person or company should focus on the causes that contribute most to the problem. Resolving the most significant contributing cause or causes will produce a reasonably effective, if not perfect, solution. </p><p class=\"explanations\">The fish head in a fishbone diagram is labeled with a name for the problem to be analyzed. The fish bones that extend diagonally behind the fish head represent potential causes of the problem, presented either in chronological order or in some other order logically suggested by the nature of the problem. A fishbone diagram can offer a focal point in quality circle meetings. The structure helps employees remain focused on the causes of problems rather than the symptoms.</p><p class=\"explanations\"><b>Learning Objective: 6D. Describe quality tools that a company can use to identify and analyze quality defects, including PDCA/DMAIC/DMADV, Pareto analysis, and the fishbone diagram.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is correct to say that, according to the Pareto principle, not all factors in a situation contribute equally to an outcome. However, in a fishbone diagram that arranges the problem chronologically, the most recent potential cause is closest to the <b>fish head</b>. The earliest cause of the problem is closest to the fish tail.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is correct to say that, in a fishbone diagram that arranges the problem chronologically, the most recent potential cause is closest to the fish head. However, according to the Pareto principle, <b>not all</b> factors in a situation contribute equally to an outcome. The Pareto principle states that a small percentage of causes contributes to a large percentage of the results.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">According to the Pareto principle, <b>not all</b> factors in a situation contribute equally to an outcome. The Pareto principle states that a small percentage of causes contributes to a large percentage of the results. In addition, in a fishbone diagram that arranges a problem chronologically, the most recent potential cause is closest to the <b>fish head</b>. The earliest cause of the problem is closest to the fish tail.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_062'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_063';
objQuestion.questionID = 109351;
objQuestion.item = 'LOMA_335_PPQ2019_063';
objQuestion.primaryLO = '6E';
objQuestion.textref = 'c. 6, p. 18';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '6E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Total quality management (TQM) is one quality management approach. One true statement about TQM is that it</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "does not require close supervision or control to be successful ";
arrAnsChoices[1] = "integrates the psychological needs of customers into initial product design";
arrAnsChoices[2] = "makes continuous improvement a way of life";
arrAnsChoices[3] = "focuses on large-scale innovation";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441938;
arrAnsIDs[1] = 441939;
arrAnsIDs[2] = 441940;
arrAnsIDs[3] = 441941;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The primary drawback of TQM is its rigidity. TQM <b>relies</b> on upper management for close control and supervision.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\"><b>Kansei engineering</b> is an approach to improve quality by integrating the psychological needs of customers into initial product design. </p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">TQM is a specific, process-oriented approach to quality management for creating an organization culture committed to continuous improvement. Generally, TQM requires strict adherence to four principles: (1) Doing things right the first time, (2) Being customer-centric, (3) Building teamwork, and (4) Making continuous improvement a way of life. The primary advantage of TQM is that it provides a gradual way for companies to improve the quality of their operations, products, and services. </p><p class=\"explanations\"><b>Learning Objective: 6E. Distinguish between quality management and total quality management, and provide examples of quality management approaches.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">TQM’s emphasis on risk mitigation can <b>discourage</b> agile thinking and large-scale innovation. </p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_063'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_064';
objQuestion.questionID = 109352;
objQuestion.item = 'LOMA_335_PPQ2019_064';
objQuestion.primaryLO = '6F';
objQuestion.textref = 'c. 6, pp. 20-21';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '6F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Companies can differentiate themselves from other high-quality competitors by </p><ol type=\"A\" class=\"combo\"><li>Improving internal culture</li><li>Establishing a purpose-driven brand</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441942;
arrAnsIDs[1] = 441943;
arrAnsIDs[2] = 441944;
arrAnsIDs[3] = 441945;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">In the past, customers saw the brand that a company wanted them to see. Today, a company’s internal culture influences its brand. The social sphere has created employees who reflect their work experiences to the outside world. As a result, customers today have access to a company’s internal culture. A company with a reputation for a positive internal culture will garner greater respect and, ultimately, more customer loyalty.</p><p class=\"explanations\">Today’s customers want their money connected to positive impact. As a result, they are wary of brands whose only purpose is financial. Above all, customers need to believe the business purpose, which means a company’s values have to ripple throughout the organization and into the world. </p><p class=\"explanations\"><b>Learning Objective: 6F. Describe strategies that help companies stand out among other quality-focused organizations.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Improving internal culture is one method for companies to differentiate themselves from other high-quality competitors; however, it is not the only method.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Establishing a purpose-driven brand is one method for companies to differentiate themselves from other high-quality competitors; however, it is not the only method. </p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Companies can differentiate themselves from other high-quality competitors by at least one of these methods.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_064'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['6A'] = "6A. Identify the prevailing quality management standards and the seven principles of quality management.";
arrlotext['6B'] = "6B. Describe the phases of the quality control cycle and explain some of the activities involved during each phase.";
arrlotext['6C'] = "6C. Explain how performance dashboards can be linked to reports such as cascading reports, parent reports, child reports, and control charts to deliver information to various levels of an organization.";
arrlotext['6D'] = "6D. Describe quality tools that a company can use to identify and analyze quality defects, including PDCA/DMAIC/DMADV, Pareto analysis, and the fishbone diagram.";
arrlotext['6E'] = "6E. Distinguish between quality management and total quality management, and provide examples of quality management approaches.";
arrlotext['6F'] = "6F. Describe strategies that help companies stand out among other quality-focused organizations.";
