var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2019';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 335 Practice Questions, Chapter 4";
var coursename = 'LOMA 335';
var modulenumber = 0;
var title = "LOMA_335_PPQ2019_0_4";
var intNumPools = 1;
var numQ = 9;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Operational Excellence for Insurance Professionals (2019)";
arrNumChap[0] = 1;
var thisChap = '4';

objPool = new Object(); 
objPool.intSelectCount = 9;
objPool.formID = 2062;
objPool.formName = 'PPQ2019_0_4';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_335_PQ_035';
arrPoolQuestions[1] = 'LOMA_335_PQ_036';
arrPoolQuestions[2] = 'LOMA_335_PQ_037';
arrPoolQuestions[3] = 'LOMA_335_PQ_038';
arrPoolQuestions[4] = 'LOMA_335_PQ_039';
arrPoolQuestions[5] = 'LOMA_335_PQ_040';
arrPoolQuestions[6] = 'LOMA_335_PQ_041';
arrPoolQuestions[7] = 'LOMA_335_PQ_042';
arrPoolQuestions[8] = 'LOMA_335_PQ_043';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_035';
objQuestion.questionID = 109323;
objQuestion.item = 'LOMA_335_PPQ2019_035';
objQuestion.primaryLO = '4A';
objQuestion.textref = 'c. 4, pp. 2-3';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '4A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Successful business processes are effective and efficient for the company and its customers. In the context of business processes, <i>effectiveness</i> is a term that means</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "getting things done right";
arrAnsChoices[1] = "getting the right things done";
arrAnsChoices[2] = "eliminating opportunity costs";
arrAnsChoices[3] = "completing an activity with minimal waste of human or financial resources";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441824;
arrAnsIDs[1] = 441825;
arrAnsIDs[2] = 441826;
arrAnsIDs[3] = 441827;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">In the context of business processes, <b>efficiency</b> means getting things done right.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Companies can continuously monitor business processes to ensure they work well. Effectiveness means completing the activities necessary to achieve the desired outcome. In simple terms, effectiveness is getting the right things done. Efficiency means completing an activity with minimal waste of human or financial resources. In simple terms, efficiency means getting things done right.</p><p class=\"explanations\"><b>Learning Objective: 4A. Define process management and identify the basic steps in a process improvement initiative.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">An opportunity cost is a benefit that a decision maker forfeits or gives up in choosing one decision alternative over another. Effectiveness does <b>not</b> mean eliminating opportunity costs.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">In the context of business processes, <b>efficiency </b>means completing an activity with minimal waste of human or financial resources.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_035'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_036';
objQuestion.questionID = 109324;
objQuestion.item = 'LOMA_335_PPQ2019_036';
objQuestion.primaryLO = '4B';
objQuestion.textref = 'c. 4, p. 5';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '4B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">A company develops a process charter after the company has identified the process that it wishes to improve. The primary function of a process charter is to </p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "establish the authority and accountability of a process team";
arrAnsChoices[1] = "graphically represent the process using symbols";
arrAnsChoices[2] = "design processes that can adjust to changes in volume without losing efficiency or effectiveness";
arrAnsChoices[3] = "identify each activity’s end value to the customer";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441828;
arrAnsIDs[1] = 441829;
arrAnsIDs[2] = 441830;
arrAnsIDs[3] = 441831;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A process charter usually contains a scope statement, a business case, an estimate of the process costs, a goal statement, a plan, a list of participants with assigned roles, and an explanation of the researched needs of process stakeholders. </p><p class=\"explanations\"><b>Learning Objective: 4B. Describe process mapping and methods for process analysis.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A <b>process map</b> graphically represents business processes, typically using a recognized set of graphical symbols. </p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A <b>scalable process </b>can adjust to changes in volume without losing efficiency or effectiveness.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A <b>value stream map</b> identifies each activity’s end value to the customer.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_036'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_037';
objQuestion.questionID = 109325;
objQuestion.item = 'LOMA_335_PPQ2019_037';
objQuestion.primaryLO = '4C';
objQuestion.textref = 'c. 4, pp. 7-8';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '4C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about process analysis and process control. Select the answer choice containing the correct statement. </p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Value stream maps elaborate upon simple process maps by identifying which parties are responsible for each activity. ";
arrAnsChoices[1] = "Swim lane diagrams help identify the parts of a process that are slowing down the continuous flow process of value creation. ";
arrAnsChoices[2] = "To identify appropriate benchmarks, companies often look at industry benchmarks or at universal benchmarks.";
arrAnsChoices[3] = "A value stream is the same as a value chain, because both of them focus on organizational functions.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441832;
arrAnsIDs[1] = 441833;
arrAnsIDs[2] = 441834;
arrAnsIDs[3] = 441835;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\"><b>Swim lane diagrams</b> elaborate upon simple process maps by identifying which parties are responsible for each activity.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\"><b>Value stream maps</b> help identify the parts of a process that are slowing down the continuous flow process of value creation.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Benchmarking is a formal program for measuring company performance results, identifying best practices for the same performance areas, and emulating best practices for company processes. A benchmark is a performance standard that a company aspires to achieve. Industry benchmarks are high performance standards achieved by other companies in the same industry, and universal benchmarks are positive results achieved by another company performing the same process, regardless of industry. </p><p class=\"explanations\"><b>Learning Objective: 4C. Describe benchmarks, balanced scorecards, and key performance indicators, and explain their role in process control.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A value stream is <b>different</b> from a value chain, in part because a value chain focuses on organizational functions, whereas a value stream usually focuses on cross-functional processes.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_037'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_038';
objQuestion.questionID = 109326;
objQuestion.item = 'LOMA_335_PPQ2019_038';
objQuestion.primaryLO = '4D';
objQuestion.textref = 'c. 4, p. 11';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '4D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statement(s) can correctly be made about the process improvement approach known as kaizen:</p><ol type=\"A\" class=\"combo\"><li>Generally, kaizen leads to immediate results.</li><li>Kaizen process improvements tend to be complex and expensive to implement.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441836;
arrAnsIDs[1] = 441837;
arrAnsIDs[2] = 441838;
arrAnsIDs[3] = 441839;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these statements is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is incorrect. One drawback of kaizen is that it does <b>not</b> lead to immediate results. </p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is incorrect. Kaizen process improvements tend to be <b>simple</b> and <b>inexpensive</b> to implement. </p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Kaizen is a gradual and continuous approach to process improvement using a series of modest changes and feedback from process team members. For kaizen to work, companies need to create open communication at every level. This can challenge companies whose employees do not often work collaboratively or share ideas. The simplicity of kaizen makes kaizen a useful addition to other process improvement approaches.</p><p class=\"explanations\"><b>Learning Objective: 4D. Understand how insurers can apply business process reengineering, kaizen, Six Sigma, Lean management, Lean Six Sigma, and agile management to improve business processes.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_038'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_039';
objQuestion.questionID = 109327;
objQuestion.item = 'LOMA_335_PPQ2019_039';
objQuestion.primaryLO = '4D';
objQuestion.textref = 'c. 4, pp. 12, 20, 21';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '4D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements describe different applications of technology for process management. Select the answer choice that best describes an example of straight-through processing (STP).</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "The Vista Insurance Company uses a system that provides process modeling tools for business analysts, developer tools for system integration, dashboards for measuring, monitoring, and control; and user interaction to facilitate work. ";
arrAnsChoices[1] = "At the Lake Company, sales agents submit an insurance application electronically. When the application appears in the system, the system can automatically conduct all of the required steps, issue the contract to the customer, and arrange the commission payment to the agent without any manual intervention.";
arrAnsChoices[2] = "Oasis Financial uses a system that automatically prioritizes, schedules, distributes, triggers and even completes some process steps. The system coordinates the flow of documents between process steps.";
arrAnsChoices[3] = "The Castle Insurance Company uses a system in its customer contact center that models and analyzes the work processes affected by waiting lines and establishes rules for automatically routing customer service items to service representatives.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441840;
arrAnsIDs[1] = 441841;
arrAnsIDs[2] = 441842;
arrAnsIDs[3] = 441843;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">This answer choice describes the type of technology known as a <b>business process management system</b>.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Straight-through processing (STP) refers to a fully automated process in which the steps in a specified transaction type are conducted without human intervention. A company new to STP might have to invest in new technology.</p><p class=\"explanations\"><b>Learning Objective: 4D. Understand how insurers can apply business process reengineering, kaizen, Six Sigma, Lean management, Lean Six Sigma, and agile management to improve business processes.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">This answer choice describes the type of technology known as an <b>automated</b> <b>workflow system</b>.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">This answer choice describes the type of technology known as a <b>queuing management system</b>.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_039'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_040';
objQuestion.questionID = 109328;
objQuestion.item = 'LOMA_335_PPQ2019_040';
objQuestion.primaryLO = '4D';
objQuestion.textref = 'c. 4, p. 12';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '4D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Common methodologies for continuous process improvement include agile management, Six Sigma, kaizen, and Lean management. Of these methodologies, the one for which the primary focus is the elimination of defects is</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "agile management";
arrAnsChoices[1] = "Six Sigma";
arrAnsChoices[2] = "kaizen";
arrAnsChoices[3] = "Lean management";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441844;
arrAnsIDs[1] = 441845;
arrAnsIDs[2] = 441846;
arrAnsIDs[3] = 441847;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Agile management is an approach to business effectiveness focused on finding and seizing opportunities to improve operations and processes.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Six Sigma is a disciplined approach for defining, measuring, analyzing, improving, and controlling quality be reducing process defects so that results fall within established parameters. A defect refers to anything that produces waste. <i>Sigma</i> is a measure of how close performance is to specifications. <i>Six</i> refers to the possible performance levels a company can achieve.</p><p class=\"explanations\"><b>Learning Objective: 4D. Understand how insurers can apply business process reengineering, kaizen, Six Sigma, Lean management, Lean Six Sigma, and agile management to improve business processes.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Kaizen is a gradual and continuous approach to business process improvement using a modest series of modest changes and feedback from process team members. </p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Lean management is a continuous process improvement approach that emphasizes creating a value stream comprising Lean processes with minimal waste.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_040'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_041';
objQuestion.questionID = 109329;
objQuestion.item = 'LOMA_335_PPQ2019_041';
objQuestion.primaryLO = '4E';
objQuestion.textref = 'c. 4, p. 16';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '4E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Epiphany Insurance Company recently implemented a formal program for fundamentally redesigning its business processes, structures, and software with the goal of substantially improving cost, quality, service levels, and speed. This information indicates that Epiphany engaged in the process of</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "scrum";
arrAnsChoices[1] = "process management";
arrAnsChoices[2] = "continuous process improvement";
arrAnsChoices[3] = "business process reengineering (BPR)";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441848;
arrAnsIDs[1] = 441849;
arrAnsIDs[2] = 441850;
arrAnsIDs[3] = 441851;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">In agile management, a common approach is scrum—a framework for managing the processes involved in software development. Agile management focuses on finding and seizing opportunities to <b>improve existing</b> operations and processes. </p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Process management is a formal method of defining, documenting, evaluating, and improving resources and workflow so that processes better achieve the tasks they were designed to accomplish. Process management is associated with the <b>improvement</b> of existing processes rather than process redesign.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Continuous process improvement uses strategic initiatives to make ongoing, <b>incremental improvements</b> in processes and technology. Continuous process improvement involves incremental change of existing processes, whereas BPR advocates major—if not total—reinvention </p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Business process reengineering (BPR) is a formal program for fundamentally redesigning business processes, structures, and software with the goal of substantially improving cost, quality, service levels, and speed. For reengineering to be justified, it should lead to significantly better, faster, or less expensive processing.</p><p class=\"explanations\"><b>Learning Objective: 4E. Define business process reengineering and explain when it might be appropriate for a company to use business process reengineering instead of continuous process improvement.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_041'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_042';
objQuestion.questionID = 109330;
objQuestion.item = 'LOMA_335_PPQ2019_042';
objQuestion.primaryLO = '4E';
objQuestion.textref = 'c. 4, pp. 17-18';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '4E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statement(s) can correctly be made about business process reengineering (BPR):</p><ol type=\"A\" class=\"combo\"><li>BPR involves greater operational risk than does continuous process improvement.</li><li>An effective BPR undertaking should take the mistake-proofing approach.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441852;
arrAnsIDs[1] = 441853;
arrAnsIDs[2] = 441854;
arrAnsIDs[3] = 441855;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Implementation of the new design should consist of significant analysis, simulation, prototyping, and training. After implementation, team members review the process by monitoring benchmarks and KPIs. Employee and customer attitudes toward the new design are prime indicators of performance. The mistake-proofing (fail-safe design) approach designs with the awareness that humans are fallible and a process will not always conform to the plan. </p><p class=\"explanations\"><b>Learning Objective: 4E. Define business process reengineering and explain when it might be appropriate for a company to use business process reengineering instead of continuous process improvement.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct; however, it is not the only correct statement.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is correct; however, it is not the only correct statement.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct. </p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_042'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_335_PQ_043';
objQuestion.questionID = 109331;
objQuestion.item = 'LOMA_335_PPQ2019_043';
objQuestion.primaryLO = '4F';
objQuestion.textref = 'c. 4, p. 20';
objQuestion.textbook = 0;
objQuestion.chapter = 4;
objQuestion.module = 0;
var arrLOs = new Array();
arrLOs[0] = '4F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Companies use a variety of methods for controlling against information security risks. The method that monitors system traffic and alerts administrators to potential security issues is known as</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "a rules engine";
arrAnsChoices[1] = "the cloud";
arrAnsChoices[2] = "intrusion detection software";
arrAnsChoices[3] = "machine learning";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 441856;
arrAnsIDs[1] = 441857;
arrAnsIDs[2] = 441858;
arrAnsIDs[3] = 441859;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Rules engines are software-based repositories of key business process rules that can be consistently applied in specified circumstances to produce the desired results. </p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The cloud is a virtual data storage system that maintains digital data on multiple connected servers owned and managed by a hosting company. </p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Other methods for controlling against security risks include the use of intranets, extranets, virtual private networks, and firewalls.</p><p class=\"explanations\"><b>Learning Objective: 4F. Discuss technologies used in process management and explain how they can improve process efficiency.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Artificial intelligence involves machine learning, which allows computers to identify patterns without being told expressly where or how to find them. </p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_335_PQ_043'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['4A'] = "4A. Define process management and identify the basic steps in a process improvement initiative.";
arrlotext['4B'] = "4B. Describe process mapping and methods for process analysis.";
arrlotext['4C'] = "4C. Describe benchmarks, balanced scorecards, and key performance indicators, and explain their role in process control.";
arrlotext['4D'] = "4D. Understand how insurers can apply business process reengineering, kaizen, Six Sigma, Lean management, Lean Six Sigma, and agile management to improve business processes.";
arrlotext['4E'] = "4E. Define business process reengineering and explain when it might be appropriate for a company to use business process reengineering instead of continuous process improvement.";
arrlotext['4F'] = "4F. Discuss technologies used in process management and explain how they can improve process efficiency.";
