var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2020';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 357 Practice Questions, Chapter 1";
var coursename = 'LOMA 357';
var modulenumber = 1;
var title = "LOMA_357_PPQ2019_0_1";
var intNumPools = 1;
var numQ = 9;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Institutional Investing: Principles and Practices (2019)";
arrNumChap[0] = 1;
var thisChap = '1';

objPool = new Object(); 
objPool.intSelectCount = 9;
objPool.formID = 2139;
objPool.formName = 'PPQ2019_0_1';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_357_PQ_001';
arrPoolQuestions[1] = 'LOMA_357_PQ_002';
arrPoolQuestions[2] = 'LOMA_357_PQ_003';
arrPoolQuestions[3] = 'LOMA_357_PQ_004';
arrPoolQuestions[4] = 'LOMA_357_PQ_005';
arrPoolQuestions[5] = 'LOMA_357_PQ_006';
arrPoolQuestions[6] = 'LOMA_357_PQ_007';
arrPoolQuestions[7] = 'LOMA_357_PQ_008';
arrPoolQuestions[8] = 'LOMA_357_PQ_009';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_001';
objQuestion.questionID = 111008;
objQuestion.item = 'LOMA_357_PPQ2019_001';
objQuestion.primaryLO = '1A';
objQuestion.textref = 'c. 1, pp. 3, 4, 5-6';
objQuestion.textbook = 0;
objQuestion.chapter = 1;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '1A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about saving, investing, speculating, and gambling. Select the answer choice containing the correct statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Saving typically provides the opportunity to increase an accumulation of funds faster than investing.";
arrAnsChoices[1] = "Investing involves assessing the risk associated with an investment and only accepting the risk if the anticipated return is suitable for the level of risk assumed.";
arrAnsChoices[2] = "Speculating is based on the mistaken belief that random events become less random—and more predictable—the more frequently certain outcomes are observed.";
arrAnsChoices[3] = "Gambling requires a careful examination of an asset’s current or projected value over a long time.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448655;
arrAnsIDs[1] = 448656;
arrAnsIDs[2] = 448657;
arrAnsIDs[3] = 448658;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Because of the potential for investment gains and income, <b>investing</b> offers the opportunity to accumulate funds faster than saving.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Investing differs from saving, speculating, and gambling. Savers’ funds typically accumulate through additional contributions to savings and/or interest income. Investors’ funds typically accumulate through investment gains, investment income, and/or additional contributions of money.</p><p class=\"explanations\">Unlike investors, speculators generally are willing to take on larger risks in return for the chance of larger rewards. Compared to speculators and investors, gamblers have the least amount of control in preventing the loss of committed capital. Speculators and investors can sell assets before they lose all their committed capital.</p><p class=\"explanations\"><b>Learning Objective: 1A. Describe investing and distinguish investing from saving, speculating, and gambling.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The <b>gambler’s fallacy</b>, also known as the Monte Carlo fallacy, is the mistaken belief that random events become less random—and more predictable—the more frequently certain outcomes are observed. In a financial context, speculation is the practice of engaging in a financial transaction—particularly, a risky transaction—with the intent of benefitting from a short-term fluctuation in an asset’s price.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\"><b>Investing</b> typically involves conducting research and analysis to determine the fundamental value of assets, and then carefully purchasing assets that are intended to create additional value or wealth. Gambling is the act of wagering something of value—such as money—on the outcome of an event involving chance.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_001'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_002';
objQuestion.questionID = 111009;
objQuestion.item = 'LOMA_357_PPQ2019_002';
objQuestion.primaryLO = '1B';
objQuestion.textref = 'c. 1, pp. 7-9';
objQuestion.textbook = 0;
objQuestion.chapter = 1;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '1B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Two main types of investors are retail investors and institutional investors. Select the answer choice that correctly identifies, based on their skills and resources, whether retail investors or institutional investors are considered sophisticated investors, and which type of investors typically have the ability to negotiate trading fees.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[-1] = "<u>Sophisticated investors</u></div><div class=\"anshead\"><u>Ability to negotiate trading fees</u>";
arrAnsChoices[0] = "retail investors</div><div class=\"anscell\" onclick=\"recordAns(1);\">institutional investors";
arrAnsChoices[1] = "retail investors</div><div class=\"anscell\" onclick=\"recordAns(2);\">retail investors";
arrAnsChoices[2] = "institutional investors</div><div class=\"anscell\" onclick=\"recordAns(3);\">institutional investors";
arrAnsChoices[3] = "institutional investors</div><div class=\"anscell\" onclick=\"recordAns(4);\">retail investors";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448660;
arrAnsIDs[1] = 448661;
arrAnsIDs[2] = 448662;
arrAnsIDs[3] = 448663;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is correct to say that institutional investors typically have the ability to negotiate trading fees. However, retail investors are considered “unsophisticated investors” because they usually do <b>not</b> have the skills or resources to conduct extensive investment research and analysis on their own.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Retail investors are considered “unsophisticated investors” because they usually do <b>not</b> have the skills or resources to conduct extensive investment research and analysis on their own. In addition, because they typically do <b>not</b> have the ability to negotiate trading fees, retail investors usually pay a flat fee rate to broker-dealers, regardless of the size of their trade.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Retail investors are considered “unsophisticated investors” because they usually lack the skills or resources to conduct extensive investment research and analysis on their own. Because of trading costs, retail investors usually trade less frequently than institutional investors, and typically pay a flat fee rate to broker-dealers, regardless of the size of their trade.</p><p class=\"explanations\">Examples of institutional investors include insurance companies, mutual funds, endowment funds, private foundations, retirement plans, and pension funds. Institutional investors can employ investment professionals who specialize in specific areas of investment research and analysis. They also have the ability to negotiate trading fees, and typically pay varying fee rates that depend on the size of their trades.</p><p class=\"explanations\"><b>Learning Objective: 1B. Explain the differences between retail investors and institutional investors.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is correct to say that those institutional investors are considered “sophisticated investors.” However, because retail investors typically do <b>not</b> have the ability to negotiate trading fees, they usually pay a flat fee rate to broker-dealers, regardless of the size of their trade.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_002'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_003';
objQuestion.questionID = 111010;
objQuestion.item = 'LOMA_357_PPQ2019_003';
objQuestion.primaryLO = '1C';
objQuestion.textref = 'c. 1, pp. 12-14';
objQuestion.textbook = 0;
objQuestion.chapter = 1;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '1C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">An insurer divides its assets into two main types of accounts—a general account and one or more separate accounts. With regard to an insurer’s general account and separate accounts, it typically is correct to say that, for the <i>separate account</i>, the insurer</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "bears the investment risk and the risk attached to paying the insurance benefits or other product guarantees to customers";
arrAnsChoices[1] = "sets up an individual account linked to the customer and tracks the market value of the subaccounts the customer selects";
arrAnsChoices[2] = "invests in and maintains assets that support all of the insurer’s contractual obligations for guaranteed insurance products";
arrAnsChoices[3] = "pays insurance benefit amounts based on contractual guarantees to customers, rather than the market values of invested assets in subaccounts";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448664;
arrAnsIDs[1] = 448665;
arrAnsIDs[2] = 448666;
arrAnsIDs[3] = 448667;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">For the <b>general account</b>, the insurance company bears the investment risk and the risk attached to paying the insurance benefits or other product guarantees to customers.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Insurers use separate accounts to support nonguaranteed products such as variable life insurance and variable annuities. For a separate account product, an insurer sets up an individual account linked to the customer, and the customer has a direct interest in the investment performance of the assets supporting the account. The customer typically elects to allocate her premium payments into at least one of several investment fund options, called subaccounts.</p><p class=\"explanations\">A general account, also called a general account portfolio, is a life insurance company investment account in which the insurer maintains assets that support all of the insurer’s contractual obligations for guaranteed insurance products, such as whole life insurance or fixed annuity products. Unlike general account products, the customer—not the insurer—bears most or all of the risk for assets held in separate accounts.</p><p class=\"explanations\"><b>Learning Objective: 1C. Identify the types of insurance products supported by general account and separate account assets and describe the movement of funds in and out of general and separate accounts.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A <b>general account</b>, also called a general account portfolio, is a life insurance company investment account in which the insurer maintains assets that support all of the insurer’s contractual obligations for guaranteed insurance products, such as whole life insurance or fixed annuity products. General account assets also support any guarantees found in variable products.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">For a separate account product, the insurer tracks the <b>market value</b> of the subaccounts, and the customer’s account value rises or falls in accordance with the change in the market values of the subaccounts the customer selected. Therefore, the benefit amount of a variable product typically depends directly on the investment performance of the assets in the customer’s account. When a policy’s benefits come due, the insurer typically draws funds from the separate account assets to pay the benefits. Money for a guaranteed benefit would come from the general account instead of the separate account.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_003'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_004';
objQuestion.questionID = 111011;
objQuestion.item = 'LOMA_357_PPQ2019_004';
objQuestion.primaryLO = '1D';
objQuestion.textref = 'c. 1, pp. 16-17';
objQuestion.textbook = 0;
objQuestion.chapter = 1;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '1D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Consider the roles of the following investment professionals employed by the Nimble Life Insurance Company:</p><ul class=\"examul\"><li>Bea Gower is responsible for monitoring issuers of securities and making trading recommendations to Nimble’s portfolio managers; she also provides research and insights that support their investment decisions.</li><li>Jamil Hashmi executes purchases and sales of publicly traded securities under instructions from Nimble’s portfolio managers.</li></ul><p class=\"stem\">Select the answer choice that correctly identifies Ms.&nbsp;Gower and Mr.&nbsp;Hashmi with regard to their roles as investment professionals.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[-1] = "<u>Ms.&nbsp;Gower</u></div><div class=\"anshead\"><u>Mr.&nbsp;Hashmi</u>";
arrAnsChoices[0] = "investment analyst</div><div class=\"anscell\" onclick=\"recordAns(1);\">asset-liability manager";
arrAnsChoices[1] = "investment analyst</div><div class=\"anscell\" onclick=\"recordAns(2);\">trader";
arrAnsChoices[2] = "trade settlement specialist</div><div class=\"anscell\" onclick=\"recordAns(3);\">asset-liability manager";
arrAnsChoices[3] = "trade settlement specialist</div><div class=\"anscell\" onclick=\"recordAns(4);\">trader";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448669;
arrAnsIDs[1] = 448670;
arrAnsIDs[2] = 448671;
arrAnsIDs[3] = 448672;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is correct to say that Ms.&nbsp;Gower is an investment analyst. However, Mr.&nbsp;Hashmi is <b>not</b> an asset-liability manager, who helps a company manage risk for a given product line by (1) tracking product line cash flows and (2) projecting mismatches between the assets and investments that support the product line and the product line’s liabilities.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Ms.&nbsp;Gower is an investment analyst, sometimes called a securities analyst or financial analyst. Some analysis are generalists, whereas others specialize in a specific asset type or industry. Mr.&nbsp;Hashmi is a trader, who also constantly monitors financial markets to ensure that he execute trades at the best possible prices, thus maximizing the benefits of the portfolio manager’s investment decisions.</p><p class=\"explanations\"><b>Learning Objective: 1D. List the professional roles found in the investment function of financial services companies and describe each role’s general responsibilities.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Ms.&nbsp;Gower is <b>not</b> a trade settlement specialist, who monitors executed trades ensure that the exchange of securities and cash is completed with trading partners in a timely manner. Also, Mr.&nbsp;Hashmi is <b>not </b>an asset-liability manager, who helps a company manage risk for a given product line by (1) tracking product line cash flows and (2) projecting mismatches between the assets and investments supporting the product line and the product line’s liabilities.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is correct to say that Mr.&nbsp;Hashmi is a trader. However, Ms.&nbsp;Gower is <b>not</b> a trade settlement specialist, who monitors executed trades to ensure that the exchange of securities and cash is completed with trading partners in a timely manner.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_004'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_005';
objQuestion.questionID = 111012;
objQuestion.item = 'LOMA_357_PPQ2019_005';
objQuestion.primaryLO = '1E';
objQuestion.textref = 'c. 1, pp. 19-20';
objQuestion.textbook = 0;
objQuestion.chapter = 1;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '1E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Attentive Financial Company divides its investment function into front-office operations, middle-office operations, and back-office operations. If Attentive’s use of this configuration is typical, then Attentive’s <i>front-office </i>operations most likely include</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "asset trading";
arrAnsChoices[1] = "portfolio performance reporting";
arrAnsChoices[2] = "investment information technology";
arrAnsChoices[3] = "data governance and security";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448673;
arrAnsIDs[1] = 448674;
arrAnsIDs[2] = 448675;
arrAnsIDs[3] = 448676;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Front-office operations typically include investment operations activities that deal directly with the securities marketplace, trade negotiations, and trading securities. Front-office functions encompass portfolio management, asset management, asset trading, investment analysis, and investment research.</p><p class=\"explanations\">Middle-office operations typically include trade-support operations, such as investment forecasting, securities regulatory compliance, trade settlements, funds disbursement, investment risk management, and portfolio performance reporting.</p><p class=\"explanations\">Back-office operations typically include official company record-keeping operations, such as investment accounting, investment reporting, investment information technology, data governance and security, and management of vendor relationships. Some companies consider middle-office activities as part of back-office operations.</p><p class=\"explanations\"><b>Learning Objective: 1E. Differentiate between a financial services company’s front-office, middle-office, and back-office investment operations.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Within an investment function’s organizational structure, portfolio performance reporting typically is classified as a <b>middle-office operation</b> in companies that include middle-office operations.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Within an investment function’s organizational structure, investment information technology typically is classified as a <b>back-office</b> <b>operation</b>.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Within an investment function’s organizational structure, data governance and security typically is classified as a <b>back-office</b> <b>operation</b>.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_005'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_006';
objQuestion.questionID = 111013;
objQuestion.item = 'LOMA_357_PPQ2019_006';
objQuestion.primaryLO = '1F';
objQuestion.textref = 'c. 1, pp. 22-23';
objQuestion.textbook = 0;
objQuestion.chapter = 1;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '1F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Many functional areas within an insurance company interact with and provide important support to the investment function. The following statement(s) can correctly be made about these interactions:</p><ol type=\"A\" class=\"combo\"><li>A company’s investment marketing function is responsible primarily for the marketing and sales of investment services to potential institutional investment clients.</li><li>To create a product’s financial design, a life insurance company’s actuaries and other product development team members require information and input from investment professionals.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448677;
arrAnsIDs[1] = 448678;
arrAnsIDs[2] = 448679;
arrAnsIDs[3] = 448680;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Statement A is correct. The investment marketing function develops all information used in product or service descriptions and promotional information about the company’s institutional investment management services. Employees in this function may also support training programs for an institutional investment product, such as the different subaccounts available to variable annuity customers.</p><p class=\"explanations\">Statement B is correct. During product planning and development, investment professionals identify the types of assets that are available to match the characteristics of a given product. Investment professionals also evaluate any product design assumptions involving the assets that back a product and support the long-term matching of assets with a product’s liabilities.</p><p class=\"explanations\"><b>Learning Objective: 1F. Identify and describe specific insurance company functions that interact with the investment function.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct, but it is not the only correct statement.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is correct, but it is not the only correct statement.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_006'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_007';
objQuestion.questionID = 111014;
objQuestion.item = 'LOMA_357_PPQ2019_007';
objQuestion.primaryLO = '1G';
objQuestion.textref = 'c. 1, pp. 23-24, 25, 18';
objQuestion.textbook = 0;
objQuestion.chapter = 1;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '1G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">For this question, if answer choices (1) through (3) are all correct, select answer choice (4). Otherwise, select the one correct answer choice.</p><p class=\"stem\">Reasons that a financial services company may outsource investment management duties to external vendors include</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "acquiring, organizing, and/or analyzing external data";
arrAnsChoices[1] = "obtaining expertise in managing specific types of assets";
arrAnsChoices[2] = "complying with the need for internal controls with regard to custodial tasks";
arrAnsChoices[3] = "all of the above";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448681;
arrAnsIDs[1] = 448682;
arrAnsIDs[2] = 448683;
arrAnsIDs[3] = 448684;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Financial services companies may outsource investment management duties to external vendors to acquire, organize, and/or analyze external data. However, this is <b>not</b> the only correct response.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Financial services companies may outsource investment management duties to external vendors to obtain expertise in managing specific types of assets. However, this is <b>not</b> the only correct response.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Financial services companies may outsource investment management duties to external vendors to comply with the need for internal controls with regard to custodial tasks. However, this is <b>not</b> the only correct response.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">An institutional investor that employs multiple investment analysts can deploy them to gather large quantities of data. However, many companies find it more efficient to use external vendors to acquire data for their analysts. Some vendors also provide services to organize and analyze the data they collect.</p><p class=\"explanations\">Outsourcing is particularly attractive to companies that lack the internal expertise to manage specific types of assets. An effective internal control system separates the custodial, authorization, and accounting tasks associated with a company’s assets. Institutional investors often use an external provider for custodial tasks to comply with the need for internal controls.</p><p class=\"explanations\"><b>Learning Objective: 1G. Explain why financial services companies may outsource investment management duties to external vendors.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_007'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_008';
objQuestion.questionID = 111015;
objQuestion.item = 'LOMA_357_PPQ2019_008';
objQuestion.primaryLO = '1H';
objQuestion.textref = 'c. 1, p. 25';
objQuestion.textbook = 0;
objQuestion.chapter = 1;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '1H';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The investment function uses several types of information systems. One type of investment system supports general ledger processing, reporting to clients, and compliance with internal and external controls. This system also generates sales proposals to institutional clients. The type of system that performs these functions is known as</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "a trade management system";
arrAnsChoices[1] = "a portfolio management system";
arrAnsChoices[2] = "a risk management and analysis system";
arrAnsChoices[3] = "an investment accounting system";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448685;
arrAnsIDs[1] = 448686;
arrAnsIDs[2] = 448687;
arrAnsIDs[3] = 448688;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Trade management systems, also known as order management systems, are associated with trading platforms and support the processes of trade initiation, trade execution, and transaction recording. These systems allow traders to monitor and execute trades electronically in real time.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Portfolio management systems support investment management activities, display cash balances and portfolio holdings, monitor investment transactions, track asset and portfolio market values, support portfolio performance measurement and analysis, generate investment reports, and comply with internal policies and external regulations.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Risk management and analysis systems support the processes for risk management, asset analysis, asset-liability management, and scenario analysis. Many risk analysis systems are dedicated to a single type of asset instead of all asset types.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The volume and complexity of investment data requires financial services companies to merge information from multiple internal and external data sources.</p><p class=\"explanations\"><b>Learning Objective: 1H. Describe the sources and uses of investment data and how investment professionals manage and analyze data.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_008'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_357_PQ_009';
objQuestion.questionID = 111016;
objQuestion.item = 'LOMA_357_PPQ2019_009';
objQuestion.primaryLO = '1I';
objQuestion.textref = 'c. 1, pp. 27-29';
objQuestion.textbook = 0;
objQuestion.chapter = 1;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '1I';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about data governance, which is the process of establishing organizational ownership and accountability for data so that business processes are optimized and data are secure and protected. Three statements are true, and one statement is false. Select the answer choice containing the <B>FALSE</B> statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Cybersecurity encompasses measures undertaken to protect a company’s computer networks, systems, and data from unauthorized access.";
arrAnsChoices[1] = "Successful data governance requires oversight from senior managers to support efforts at the functional level and ensure close coordination with the information technology (IT) unit.";
arrAnsChoices[2] = "A comprehensive cybersecurity policy excludes the monitoring of vendors.";
arrAnsChoices[3] = "For financial institutions, the unauthorized intrusion into a company’s information systems to engage in any activities that could disrupt financial markets is of great concern.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 448689;
arrAnsIDs[1] = 448690;
arrAnsIDs[2] = 448691;
arrAnsIDs[3] = 448692;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response. Companies engage in cybersecurity to fend off malicious cyberattacks.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response. Data governance provides a framework for organizational decisions about how to manage data, realize value from it, minimize its cost and complexity, manage risk, and ensure compliance with ever-growing external requirements for information.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">External vendors pose a significant risk to a company’s cybersecurity. Even if a financial services company is vigilant about protecting its data, the company cannot assume that its business partners are exercising the same level of care. Therefore, a comprehensive cybersecurity policy should encompass vendor monitoring, which includes examining each vendor’s security practices and establishing procedures for a coordinated response to cyberattacks to contain the damage of successful breaches.</p><p class=\"explanations\"><b>Learning Objective: 1I. Describe important elements in data governance and information security for financial services companies.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response. The investment function is a particularly attractive target for cyber criminals who wish to steal funds or information, disrupt normal business operations, and destroy public confidence in financial markets.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_357_PQ_009'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['1A'] = "1A. Describe investing and distinguish investing from saving, speculating, and gambling.";
arrlotext['1B'] = "1B. Explain the differences between retail investors and institutional investors.";
arrlotext['1C'] = "1C. Identify the types of insurance products supported by general account and separate account assets and describe the movement of funds in and out of general and separate accounts.";
arrlotext['1D'] = "1D. List the professional roles found in the investment function of financial services companies and describe each role’s general responsibilities.";
arrlotext['1E'] = "1E. Differentiate between a financial services company’s front-office, middle-office, and back-office investment operations.";
arrlotext['1F'] = "1F. Identify and describe specific insurance company functions that interact with the investment function.";
arrlotext['1G'] = "1G. Explain why financial services companies may outsource investment management duties to external vendors.";
arrlotext['1H'] = "1H. Describe the sources and uses of investment data and how investment professionals manage and analyze data.";
arrlotext['1I'] = "1I. Describe important elements in data governance and information security for financial services companies.";
