// Chapter 5 Alt Text/Transcripts
altText['figure5-1'] = {'title':'Opposing Forces Affecting Product Development','content':'<p>Four pairs of concepts, each one pushing against the other.</p><p>Concept Pair 1: Rapid Innovation vs. Limited Operational and Financial Resources</p><p>Concept Pair 2: Market Forces vs. Need for Disciplined Pricing</p><p>Concept Pair 3: Rapid Speed vs. Regulatory Compliance</p><p>Concept Pair 4: Customer Needs vs. Insurer Priorities and Capabilities</p>'};
altText['figure5-2'] = {'title':'Shelf Life of Life Insurance and Annuity Products','content':'<p>A bar chart showing average shelf life of insurance and annuity projects.</p><p>Insurance:</p><p>Indexed universal life 1.25 years</p><p>Term life 1.5 years</p><p>Variable universal life 3.5 years</p><p>Whole life 4.7 years</p><p>Annuity:</p><p>Indexed annuity 1.4 years</p><p>Variable annuity 1.6 years</p><p>Fixed annuity 4.8 years</p>'};
altText['figure5-3'] = {'title':'Product Complexity','content':'<p>A figure of three text boxes.</p><p>Box 1: Established Products, Generally Well Understood; generally lower risk</p><p>Yearly renewable term life insurance</p><p>Multiple-year term life insurance</p><p>Fixed whole life insurance</p><p>Universal life insurance</p><p>Single-premium immediate annuities</p><p>Box 2: Newer, Complex Products and Features; generally greater risk</p><p>Variable universal life insurance with secondary guarantee riders</p><p>Variable annuities with secondary death benefit guarantee riders</p><p>Variable annuities with secondary living benefit guarantee riders</p><p>Indexed annuities</p><p>Box 3: Combination Products; risk level varies.</p><p>Term life insurance with disability income insurance</p><p>Hybrid life and long-term care insurance products</p><p>Annuities with long-term care insurance</p>'};
altText['figure5-4'] = {'title':'Life Insurance Product Development Time by Product and Product Complexity','content':'<p>Chart showing average product development time.</p><p>Term life products: </p><p>Rate change: 18 weeks</p><p>Revisions: 29 weeks</p><p>New product: 35 weeks</p><p>Whole life products:</p><p>Rate change: 22 weeks</p><p>Revisions: 31 weeks</p><p>New product: 45 weeks</p><p>Variable UL products:</p><p>Rate change: 27 weeks</p><p>Revisions: 44 weeks</p><p>New product: 50 weeks</p>'};
altText['figure5-5'] = {'title':'Product Development Process','content':'<p>Arrows link the five steps of the product development process into an ongoing cycle.</p><p>Product Planning</p><p>Comprehensive Business Analysis</p><p>Technical Product Design</p><p>Product Introduction</p><p>Monitoring, Evaluation, and Feedback</p>'};
altText['figure5-6'] = {'title':'Product Planning in Product Development','content':'<p>Shows the product development cycle. The Product Planning step is highlighted with a list of the following subcategories:</p><p>Idea Generation </p><p>Idea Screening</p>'};
altText['figure5-7'] = {'title':'Comprehensive Business Analysis in Product Development','content':'<p>Shows the product development cycle. The Comprehensive Business Analysis step is highlighted with a list of the following subcategories:</p><p>Market Analysis</p><p>Product Design Objectives</p><p>Feasibility Study</p><p>Marketing Plan</p><p>Marketing Projections</p><p>Product Proposal</p>'};
altText['video5-1'] = {'title':'Product Portfolios and Product Mixes','content':'<p>Many insurance companies have similar, but not identical, product portfolios. Let’s take a look at two sample companies.</p><p>Spinward’s product portfolio contains multiple types of life insurance and annuity products.</p><p><strong>Product Portfolio</strong></p><p><strong>Life Insurance:</strong></p><p>Term life insurance</p><p>Whole life insurance</p><p><strong>Annuities:</strong></p><p>Fixed deferred annuities</p><p>Immediate annuities</p><p>Upriver’s product portfolio is similar to Spinward’s, but not exactly the same. </p><p><strong>Product Portfolio</strong></p><p><strong>Life Insurance:</strong></p><p>Term life insurance</p><p><strong>Annuities</strong></p><p>Fixed deferred annuities</p><p>Variable deferred annuities</p><p>Immediate annuities</p><p>The product mix for each company measures the volume for each line of business, such as by the proportion of reserves set aside for each.</p><p><strong>Product Mix (Spinward)</strong></p><p><strong>Life Insurance:</strong></p><p>34% in term life insurance reserves</p><p>14% in whole life insurance reserves</p><p><strong>Annuities</strong></p><p>46% in fixed deferred annuity reserves</p><p>6% in immediate annuity reserves</p><p><strong>Product Mix (Upriver)</strong></p><p><strong>Life Insurance:</strong></p><p>20% in term life insurance reserves</p><p><strong>Annuities</strong></p><p>35% in fixed deferred annuity reserves</p><p>42% in variable deferred annuity reserves</p><p>3% in immediate annuity reserves</p><p>So we can see that a product portfolio tells us what a company offers, while the product mix also measures how much.</p>'};
// Chapter 6 Alt Text/Transcripts
altText['figure6-1'] = {'title':'Technical Product Design in Product Development','content':'<p>Shows the product development cycle. The Technical Product Design step is highlighted with a list of the following subcategories:</p><p>Establishing a Financial Design, including Components of the Financial Design </p><p>Testing a Financial Design</p><p>Budgeting and Scheduling</p>'};
altText['figure6-2'] = {'title':'Calculating Premium Amounts','content':'<p>A visual equation: Charge for operating expenses + contribution to company earnings + charge for cost of benefits – investment earnings = required premiums and other considerations from customers</p>'};
altText['figure6-3'] = {'title':'Product Introduction in Product Development','content':'<p>Shows the product development cycle. The Product Introduction step is highlighted with a list of the following subcategories:</p><p>Product Implementation, including Day 1 Functionality and Day 2 Functionality</p><p>Product Launch</p>'};
altText['figure6-4'] = {'title':'Monitoring, Evaluation, and Feedback in Product Development','content':'<p>Shows the product development cycle. The Monitoring, Evaluation, and Feedback step is highlighted. There are no subcategories.</p>'};
altText['figure6-5'] = {'title':'Sources of Adverse and Favorable Deviations','content':'<p>Graphic representation of when deviations are favorable or adverse.</p><p>When actual values for company revenues are greater than assumed, the deviation is favorable. When actual values for company revenues are lower than assumed, the deviation is adverse.</p><p>When actual values for benefit payments are greater than assumed, the deviation is adverse. When actual values for benefit payments are lower than assumed, the deviation is favorable.</p><p>When actual values for company expenses are greater than assumed, the deviation is adverse. When actual values for company expenses are lower than assumed, the deviation is favorable.</p>'};
altText['video6-1'] = {'title':'Before and After Product Launch','content':'<p class="vid-desc">[A rocket sits on a launch pad.]</p><p>Product implementation and product launch are separate phases in the product introduction process — but they’re not completely separate. </p><p class="vid-desc">[Two engineers in hardhats look at a blueprint.]</p><p>Product implementation begins early, as a company prepares everything it needs to launch the product, from information systems to advertising.</p><p class="vid-desc">[A person sits at a control console with a headset on. He’s talking into the headset and moving dials on the console.]</p><p class="vid-desc">[The rocket launches. The person at the console celebrates.]</p><p>However, product implementation doesn’t end when the product is launched. For example, a product might not be approved in some states at the time of launch, receiving approval in those states later.</p><p class="vid-desc">[The rocket flies past a satellite dish.]</p><p>The implementation phase lasts as long as is necessary — just hopefully not too long! </p>'};
