var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2021';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 371 Practice Questions, Chapter 6";
var coursename = 'LOMA 371';
var modulenumber = 2;
var title = "LOMA_371_PPQ2021_0_6";
var intNumPools = 1;
var numQ = 9;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Risk Management and Product Design for Insurance Companies, Third Edition (2020)";
arrNumChap[0] = 1;
var thisChap = '6';

objPool = new Object(); 
objPool.intSelectCount = 9;
objPool.formID = 2617;
objPool.formName = 'PPQ2021_0_6';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_371_PQ_052';
arrPoolQuestions[1] = 'LOMA_371_PQ_053';
arrPoolQuestions[2] = 'LOMA_371_PQ_054';
arrPoolQuestions[3] = 'LOMA_371_PQ_055';
arrPoolQuestions[4] = 'LOMA_371_PQ_056';
arrPoolQuestions[5] = 'LOMA_371_PQ_057';
arrPoolQuestions[6] = 'LOMA_371_PQ_058';
arrPoolQuestions[7] = 'LOMA_371_PQ_059';
arrPoolQuestions[8] = 'LOMA_371_PQ_060';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_052';
objQuestion.questionID = 121329;
objQuestion.item = 'LOMA_371_PPQ2021_052';
objQuestion.primaryLO = '6A';
objQuestion.textref = 'c. 6, p. 2';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '6A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Activities that take place during the technical product design stage of product development include</p><ol type=\"A\" class=\"combo\"><li>Establishing a financial design</li><li>Testing a financial design</li><li>Budgeting and scheduling</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A, B, and C";
arrAnsChoices[1] = "A and B only";
arrAnsChoices[2] = "B and C only";
arrAnsChoices[3] = "A only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490664;
arrAnsIDs[1] = 490665;
arrAnsIDs[2] = 490666;
arrAnsIDs[3] = 490667;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">For life insurance products, technical product design begins with setting a product’s financial design. Once the design has been established and tested, the development team creates a budget and schedule for the implementation process.</p><p class=\"explanations\"><b>Learning Objective: 6A. Describe typical objectives of technical product design.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that establishing and testing a financial design occur during the technical product design stage of product development. However, this is <b>not</b> the correct answer choice.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that testing a financial design and budgeting and scheduling occur during the technical product design stage of product development. However, this is <b>not</b> the correct answer choice.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that establishing a financial design occurs during the technical product design stage of product development. However, this is <b>not</b> the correct answer choice.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_052'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_053';
objQuestion.questionID = 121330;
objQuestion.item = 'LOMA_371_PPQ2021_053';
objQuestion.primaryLO = '6A';
objQuestion.textref = 'c. 6, p. 2';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '6A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">When designing new life insurance or annuity products, insurers focus on key objectives, which&nbsp;include:</p><ol type=\"A\" class=\"combo\"><li>Delivering benefits to customers on a timely basis</li><li>Generating profit for the insurer</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490668;
arrAnsIDs[1] = 490669;
arrAnsIDs[2] = 490670;
arrAnsIDs[3] = 490671;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Other important objectives of technical product design include: establishing a level of future benefits that the company can be certain to deliver under unknown future economic and demographic conditions; covering the company’s expenses of supporting the product; providing adequate future investment income to support the company’s financial obligations for products; understanding specific product risks in terms of the company’s risk standards; identifying pricing and commission structures that will succeed in the marketplace; providing an adequate return to the company’s owners; enhancing competitive positioning in the marketplace; and addressing untapped or under-targeted consumer needs.</p><p class=\"explanations\"><b>Learning Objective: 6A. Describe typical objectives of technical product design.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct. However, Statement B is also correct.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is correct. However, Statement A is also correct.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_053'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_054';
objQuestion.questionID = 121331;
objQuestion.item = 'LOMA_371_PPQ2021_054';
objQuestion.primaryLO = '6A';
objQuestion.textref = 'c. 6, pp. 2, 10-11';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '6A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The stage of the product development process in which a company most likely would develop a product development budget and a project schedule is the</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "monitoring, evaluation, and feedback stage";
arrAnsChoices[1] = "technical product design stage";
arrAnsChoices[2] = "product planning stage";
arrAnsChoices[3] = "product introduction stage";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490672;
arrAnsIDs[1] = 490673;
arrAnsIDs[2] = 490674;
arrAnsIDs[3] = 490675;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A product’s monitoring, evaluation, and feedback stage occurs after a company has launched the product for sale. This stage creates an ongoing feedback process.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">In terms of managing risk, technical product design is the most important stage of product development. During technical product design, a company decides how to maximize benefits by fine-tuning specific product features or processes that pose risks or challenges to the company.</p><p class=\"explanations\">The budgeting and scheduling process for new products typically consists of (1) preparing a budget for the human, financial, and computer resources needed to implement the product and (2) developing a project&nbsp;schedule.</p><p class=\"explanations\"><b>Learning Objective: 6A. Describe typical objectives of technical product design.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Development of individual life insurance and annuity products usually begins with product planning. Product planning consists of two main activities: idea generation and idea screening. These activities are designed to identify possible new products and evaluate their potential.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At product introduction, the company implements the plans and product design and then offers the product for sale. Product introduction can be broken into two phases: product implementation and product launch. Product implementation consists of establishing the administrative processes necessary to offer the product for sale; product launch occurs when the company finally offers the product for sale.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_054'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_055';
objQuestion.questionID = 121332;
objQuestion.item = 'LOMA_371_PPQ2021_055';
objQuestion.primaryLO = '6B';
objQuestion.textref = 'c. 6, pp. 6-7';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '6B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">When actuaries design a new life insurance or annuity product, they must estimate the cost of benefits. Generally, the projected cost of a single insurance benefit for a given policy year equals the</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "earnings from using investments in derivative securities to control volatility in the investment portfolio that supports the insurance product";
arrAnsChoices[1] = "potential benefit amount payment multiplied by the probability that the benefit will be payable";
arrAnsChoices[2] = "amount by which the product will meet or exceed the insurer’s profit target for the product";
arrAnsChoices[3] = "estimate of operating expenses—without allowances for future inflation—incurred in supporting the product";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490676;
arrAnsIDs[1] = 490677;
arrAnsIDs[2] = 490678;
arrAnsIDs[3] = 490679;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A new product’s complex design features may require an insurer to use support from hedging programs using investments in derivative securities in order to reduce the overall riskiness, or volatility, of the asset mix in the insurer’s portfolio. A hedging program involves <b>hedge costs</b>, which are expenses for trading and holding derivative securities.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The cost of benefits, sometimes known as the cost of insurance, is the value of the contractually required benefits that a product promises to pay. A single product may offer numerous benefits, and the projected cost of all benefits is the sum of the individual benefit costs. For life insurance products, the insurer’s benefit obligations for a given policy year are equal to the death benefit amount multiplied by the mortality rate plus any nonforfeiture benefit and estimated costs associated with available riders.</p><p class=\"explanations\">For annuity contracts in the accumulation phase, the main benefit is a contract’s accumulation value. Annuity contracts in the accumulation phase may include surrender charges as well as the costs for any riders elected by the contract owner. For these products, the element of mortality applies to secondary death benefits, such as those provided under a guaranteed minimum death benefit (GMDB) provision.</p><p class=\"explanations\">For straight life annuity contracts in the distribution phase, in simple terms, annuity benefits for a given period are equal to the periodic annuity benefit payment multiplied by the annuitant’s probability of living for that period. Other payout options require different approaches for finding the cost of benefits.</p><p class=\"explanations\"><b>Learning Objective: 6B. Describe important components of financial design for life insurance and annuity products, including company expenses, the cost of benefits, and investment earnings.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">For a stochastically modeled product design, companies focus on the probability that the product will meet or exceed the company’s <b>profit target</b>. The company’s risk processes generally determine, in advance, the minimum acceptable profit for a product. The resulting product design is acceptable if the percentage of stochastic scenarios that meet or exceed the company’s profit target is greater than or equal to the minimum percentage.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Actuaries calculate the amount to charge for an insurer’s operating expenses in product design by estimating the costs—<b>excluding</b> the cost of benefits, <b>with</b> allowances for future inflation—the insurer will incur in supporting the product.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_055'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_056';
objQuestion.questionID = 121333;
objQuestion.item = 'LOMA_371_PPQ2021_056';
objQuestion.primaryLO = '6C';
objQuestion.textref = 'c. 6, p. 9';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '6C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">One type of premium structure an insurance company may offer for individual life insurance products is the indeterminate pricing structure, which, by definition, is a pricing structure that</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "divides premium rate structures into standard, substandard, and preferred risk classes and applies different premium rates based on the insured’s risk characteristics";
arrAnsChoices[1] = "charges less in total premiums to a customer who purchases a high face amount in one policy than to a customer who purchases the same total face amount in multiple policies";
arrAnsChoices[2] = "allows the company to periodically reset premium rates on individual life insurance products while guaranteeing customers that premiums will not exceed a maximum specified level";
arrAnsChoices[3] = "requires higher premiums for life insurance policies that have extra benefits, or that are more likely to be paid out sooner";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490680;
arrAnsIDs[1] = 490681;
arrAnsIDs[2] = 490682;
arrAnsIDs[3] = 490683;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Premium structures may apply different premium rates based on the insured’s <b>risk characteristics</b>. For example, premium rates may vary depending on an insured’s sex, age, and tobacco use behavior.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">An insurance company may grade premium rate structures by the <b>policy face amount</b>. In effect, purchasing a high face amount in a single policy—rather than purchasing the same total face amount in multiple policies—is a form of volume discount. This variation is most applicable for individual term life insurance policies.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">For these individual life insurance products, the contract language includes a scale of guaranteed maximum premiums. This premium structure allows the company to adjust product charges to reflect anticipated future interest and mortality experience. The company must adhere to the scale of guaranteed maximum premiums included in the contract language.</p><p class=\"explanations\"><b>Learning Objective: 6C. Explain premium structures for individual life insurance, such as a contingency pricing structure and an indeterminate premium structure.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A premium structure defines the conditions under which the premium rates for a product may <b>vary from customer to customer</b>, and sets a range for those rates. For example, a premium structure typically requires higher premiums for life insurance policies that have extra benefits, or that are more likely to be paid out sooner.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_056'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_057';
objQuestion.questionID = 121334;
objQuestion.item = 'LOMA_371_PPQ2021_057';
objQuestion.primaryLO = '6D';
objQuestion.textref = 'c. 6, pp. 9-10';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '6D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">During modeling and testing for technical product design, the profitability objective (<b>is / is not</b>) the only objective tested. If initial testing of the product design produces unsatisfactory results, one change actuaries can make to a model’s assumed values that ordinarily would improve the model’s profitability, all other factors remaining the same, is to (<b>decrease / increase</b>) charges to customers.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "is / decrease";
arrAnsChoices[1] = "is / increase";
arrAnsChoices[2] = "is not / decrease";
arrAnsChoices[3] = "is not / increase";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490684;
arrAnsIDs[1] = 490685;
arrAnsIDs[2] = 490686;
arrAnsIDs[3] = 490687;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The profitability objective <b>is not</b> the only objective tested in product design. In addition, one change actuaries can make to a model’s assumed values that ordinarily would improve the model’s profitability is to <b>increase</b> charges to customers.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that one change actuaries can make to a model’s assumed values that ordinarily would improve the model’s profitability is to <b>increase</b> charges to customers. However, the profitability objective <b>is not</b> the only objective tested in product design.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that the profitability objective is not the only objective tested in product design. However, one change actuaries can make to a model’s assumed values that ordinarily would improve the model’s profitability is to <b>increase</b> charges to customers.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Once an insurer has created a product design, it must test and validate the design. Tests typically examine whether the product’s profitability, assets, reserves, and cash flows are adequate; tests also can examine interest-rate sensitivity and surplus strain. Actuaries can change some assumed values entered into the model—provided the new values are realistic and actuarially sound—if initial test results are inadequate.</p><p class=\"explanations\">Examples of changes that ordinarily would improve a product model’s profitability, all other factors remaining the same, include a decrease in benefit costs, a decrease in product expenses, an increase in charges to customers, and an increase in assumed investment earnings. The insurer’s real-world operations must be able to support any design adjustment that an actuary makes to the product design.</p><p class=\"explanations\"><b>Learning Objective: 6D. Describe modeling and testing for technical product design and explain how actuaries can improve the financial results of a product model.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_057'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_058';
objQuestion.questionID = 121335;
objQuestion.item = 'LOMA_371_PPQ2021_058';
objQuestion.primaryLO = '6E';
objQuestion.textref = 'c. 6, pp. 15-16';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '6E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">All of the following activities typically occur during the product introduction stage of the product development process <B>EXCEPT</B> for</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "developing and putting in place all systems needed to market and administer the product";
arrAnsChoices[1] = "tracking the performance of existing products and their impact on the company’s performance";
arrAnsChoices[2] = "training sales and administrative staff, and disseminating training and educational materials";
arrAnsChoices[3] = "placing advertising in appropriate media";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490688;
arrAnsIDs[1] = 490689;
arrAnsIDs[2] = 490690;
arrAnsIDs[3] = 490691;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Activities such as developing and putting in place all systems needed to market and administer the product typically <b>occur</b> during the product introduction&nbsp;stage.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">At the product introduction stage, product implementation consists of establishing the administrative processes necessary to offer the product for sale; product launch occurs when the company finally offers the product for sale. Many product implementation activities begin as early as the technical product design stage, and occur concurrently through technical product design. To speed up the implementation process, companies generally divide product implementation activities into two categories.</p><p class=\"explanations\">Day 1 functionality (the day of product launch) refers to product administration and IT elements that a company must have in place and functioning when the product is first made available for sale. Day 2 functionality (the general period after Day 1) refers to product administration and IT elements that are necessary at some future date to service and administer an insurance product, but which can be implemented after product launch.</p><p class=\"explanations\"><b>Learning Objective: 6E. Describe the activities required for product implementation and launch, differentiating between Day 1 functionality and Day 2 functionality.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Activities such as training sales and administrative staff and disseminating training and educational materials typically <b>occur</b> during the product introduction&nbsp;stage.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Activities such as placing advertising in appropriate media typically <b>occur</b> during the product introduction stage.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_058'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_059';
objQuestion.questionID = 121336;
objQuestion.item = 'LOMA_371_PPQ2021_059';
objQuestion.primaryLO = '6F';
objQuestion.textref = 'c. 6, pp. 18-19';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '6F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">In product operations, (<b>an adverse / a favorable</b>) deviation produces a decrease in actual product profitability relative to assumed product profitability. Generally, (<b>an adverse / a favorable</b>) deviation requires no corrective action.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "an adverse / an adverse";
arrAnsChoices[1] = "an adverse / a favorable";
arrAnsChoices[2] = "a favorable / an adverse";
arrAnsChoices[3] = "a favorable / a favorable";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490692;
arrAnsIDs[1] = 490693;
arrAnsIDs[2] = 490694;
arrAnsIDs[3] = 490695;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that an adverse deviation produces a decrease in actual product profitability relative to assumed product profitability. However, a <b>favorable</b> deviation generally requires no corrective action.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">An adverse deviation is a difference between actual and assumed (or expected) product values that produces a decrease in actual product profitability compared to assumed product profitability. If large adverse deviations develop, then the insurer must try to identify the reasons for them and, if possible, take corrective action, such as cutting operating expenses.</p><p class=\"explanations\">A favorable deviation is a difference between actual and assumed (or expected) product values that produces an increase in actual product profitability relative to assumed product profitability. Although a favorable deviation requires no corrective action, further study may indicate ways that future product design can capitalize on such deviations.</p><p class=\"explanations\">After accumulating experience with a product, an insurer can create and compare tables of actual and expected values, then conduct actual-to-expected (A/E) analysis for different financial variables, such as the cost of benefits and company expenses. A reliable A/E analysis requires years of data; therefore, an insurer may sell a product for years before reliably learning whether the deviations are favorable or not.</p><p class=\"explanations\"><b>Learning Objective: 6F. Describe the typical activities of product monitoring, evaluation, and feedback.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">An adverse deviation produces a <b>decrease</b> in actual product profitability relative to assumed product profitability. In addition, a <b>favorable</b> deviation generally requires no corrective&nbsp;action.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that, a favorable deviation generally requires no corrective action. However, an adverse deviation produces a <b>decrease</b> in actual product profitability relative to assumed product profitability.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_059'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_060';
objQuestion.questionID = 121337;
objQuestion.item = 'LOMA_371_PPQ2021_060';
objQuestion.primaryLO = '6F';
objQuestion.textref = 'c. 6, pp. 18-19';
objQuestion.textbook = 0;
objQuestion.chapter = 6;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '6F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">In comparisons of actual and expected product values, a difference between the values is a deviation. Deviations can be favorable or adverse. In general, a <i>favorable </i>deviation occurs when the product’s actual benefit payments are (<b>greater / lower</b>) than assumed benefit payments, and an <i>adverse </i>deviation occurs when actual product expenses are (<b>greater / lower</b>) than assumed product expenses.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "greater / greater";
arrAnsChoices[1] = "greater / lower";
arrAnsChoices[2] = "lower / greater";
arrAnsChoices[3] = "lower / lower";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490696;
arrAnsIDs[1] = 490697;
arrAnsIDs[2] = 490698;
arrAnsIDs[3] = 490699;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that an adverse deviation occurs when actual product expenses are greater than assumed. However, a favorable deviation occurs when a product’s actual benefit payments are <b>lower</b> than assumed.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A <b>favorable</b> deviation occurs when actual product expenses are lower than assumed. In addition, an <b>adverse</b> deviation occurs when a product’s actual benefit payments are greater than assumed.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">An adverse deviation occurs whenever a specific product result differs from the modeled assumptions so that actual product revenue is lower than assumed, actual benefits payments are greater than assumed, and/or actual product expenses are greater than assumed. Any amount included in the assumption values to provide an allowance for unexpected negative outcomes is known as a provision for adverse deviation (PAD). Adverse deviations are the reason for including PADs in a deterministic product design.</p><p class=\"explanations\">A favorable deviation occurs whenever a specific product result differs from the modeled assumptions so that actual product revenue is greater than assumed, actual benefits payments are lower than assumed, and/or actual product expenses are lower than assumed. Although a favorable deviation requires no corrective action, further study may indicate how future product design can capitalize on such deviations.</p><p class=\"explanations\"><b>Learning Objective: 6F. Describe the typical activities of product monitoring, evaluation, and feedback.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that a favorable deviation occurs when a product’s actual benefit payments are lower than assumed. However, a <b>favorable</b> deviation occurs when actual product expenses are lower than assumed.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_060'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['6A'] = "6A. Describe typical objectives of technical product design.";
arrlotext['6B'] = "6B. Describe important components of financial design for life insurance and annuity products, including company expenses, the cost of benefits, and investment earnings.";
arrlotext['6C'] = "6C. Explain premium structures for individual life insurance, such as a contingency pricing structure and an indeterminate premium structure.";
arrlotext['6D'] = "6D. Describe modeling and testing for technical product design and explain how actuaries can improve the financial results of a product model.";
arrlotext['6E'] = "6E. Describe the activities required for product implementation and launch, differentiating between Day 1 functionality and Day 2 functionality.";
arrlotext['6F'] = "6F. Describe the typical activities of product monitoring, evaluation, and feedback.";
