var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2021';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 371 Practice Questions, Chapter 5";
var coursename = 'LOMA 371';
var modulenumber = 2;
var title = "LOMA_371_PPQ2021_0_5";
var intNumPools = 1;
var numQ = 10;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Risk Management and Product Design for Insurance Companies, Third Edition (2020)";
arrNumChap[0] = 1;
var thisChap = '5';

objPool = new Object(); 
objPool.intSelectCount = 10;
objPool.formID = 2617;
objPool.formName = 'PPQ2021_0_5';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_371_PQ_042';
arrPoolQuestions[1] = 'LOMA_371_PQ_043';
arrPoolQuestions[2] = 'LOMA_371_PQ_044';
arrPoolQuestions[3] = 'LOMA_371_PQ_045';
arrPoolQuestions[4] = 'LOMA_371_PQ_046';
arrPoolQuestions[5] = 'LOMA_371_PQ_047';
arrPoolQuestions[6] = 'LOMA_371_PQ_048';
arrPoolQuestions[7] = 'LOMA_371_PQ_049';
arrPoolQuestions[8] = 'LOMA_371_PQ_050';
arrPoolQuestions[9] = 'LOMA_371_PQ_051';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_042';
objQuestion.questionID = 121319;
objQuestion.item = 'LOMA_371_PPQ2021_042';
objQuestion.primaryLO = '5A';
objQuestion.textref = 'c. 5, pp. 3-4';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '5A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The most basic new product risk is that a new product never earns a profit at all. Potential causes of inadequate profits, or even losses, include</p><ol type=\"A\" class=\"combo\"><li>Inadequate pricing</li><li>Incorrect underwriting standards</li><li>Poor sales volume</li><li>A product design that quickly becomes obsolete</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "A, B, C, and D";
arrAnsChoices[1] = "A, B, and C only";
arrAnsChoices[2] = "A and B only";
arrAnsChoices[3] = "C and D only";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490624;
arrAnsIDs[1] = 490625;
arrAnsIDs[2] = 490626;
arrAnsIDs[3] = 490627;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">When developing a new product, a company incurs costs that it must recover, while perhaps losing the opportunity to develop an alternative product or products that might have been more profitable. For new products, however, there is no history. Without relevant experience data, the actuarial staff must invest more time learning about the new product during product design.</p><p class=\"explanations\">Many risks comprise new product risk. To manage new product risk, insurers consider many factors, including the product development strategy, product portfolio and product mix, shelf life, product complexity, customer experience, product management and control, regulatory factors, and other environmental pressures.</p><p class=\"explanations\"><b>Learning Objective: 5A. Discuss the risks associated with launching new products.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Inadequate pricing, incorrect underwriting standards, and poor sales volume are potential causes of inadequate profits associated with new product risk. However, this is <b>not</b> the correct answer choice.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Inadequate pricing and incorrect underwriting standards are potential causes of inadequate profits associated with new product risk. However, this is <b>not</b> the correct answer choice.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Poor sales volume and a product design that quickly becomes obsolete are potential causes of inadequate profits associated with new product risk. However, this is <b>not</b> the correct answer choice.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_042'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_043';
objQuestion.questionID = 121320;
objQuestion.item = 'LOMA_371_PPQ2021_043';
objQuestion.primaryLO = '5B';
objQuestion.textref = 'c. 5, pp. 4-5';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '5B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Life insurers carefully consider how to position their products for success by employing product development strategies early in the product development process. Select the answer choice that is an example of the product development strategy known as a focused differentiation, or niche strategy.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "The Cantata Life Insurance Company aims to be the first to offer new variable life insurance products, and the first to capture and retain the largest share of the market for those products.";
arrAnsChoices[1] = "The Daybreak Life Insurance Company markets its life insurance product with a long-term-care insurance rider only to pre-retirees and early retirees.";
arrAnsChoices[2] = "Edifice Insurers creates improved deferred annuity products before its competitors; product improvements appeal to a larger portion of potential customers than competing products.";
arrAnsChoices[3] = "The Fanfare Insurance Company markets its basic term life insurance product during times of slow economic growth, when customers with tighter budgets carefully consider all costs.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490628;
arrAnsIDs[1] = 490629;
arrAnsIDs[2] = 490630;
arrAnsIDs[3] = 490631;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Cantata is using a first mover strategy in this situation. In a <b>first mover strategy</b>, a company attempts to be the first to enter a new market or the first to enter a current market with an innovative product. A first mover strategy is often referred to as a market leader strategy, because the first company to enter a market has a reasonable chance of capturing and retaining the largest share of that market.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Examples of product development strategies include cost leadership; focused differentiation, or niche strategy; first mover strategy; and fast follower strategy. Not all insurers have a clearly defined strategy for product development. For example, an insurer may offer several products designed with a cost leadership strategy, yet also develop a new product with a focused differentiation or niche strategy.</p><p class=\"explanations\">If the company has the resources and knowledge base to support multiple product development strategies, it can offer a more diverse range of products and therefore appeal to a broader market. This product diversification also aids solvency: when one product line is underperforming, the insurer may still have the revenues from other product lines to help meet its obligations.</p><p class=\"explanations\"><b>Learning Objective: 5B. Describe common product development strategies.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Edifice is using a fast follower strategy in this situation. In a <b>fast follower strategy</b>, a company quickly imitates and improves a competitor’s innovation, or is the first to introduce a similar product into an expanded market. Although similar to the first mover product, the fast follower product has improvements that appeal to a larger portion of potential customers, or refinements based on emerging experience. In the insurance industry, the fast follower strategy often focuses on taking technological innovations and adapting them to product design.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Fanfare is using a <b>cost leadership strategy</b> in this situation. In a cost leadership strategy, a company offers a product at a lower cost than the average cost in the market, or lower than the cost of comparable products offered by competitors. For insurers, this strategy requires careful expense control. Actuaries must ensure that lower-cost products can still be profitable even if revenues are lower than&nbsp;expected.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_043'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_044';
objQuestion.questionID = 121321;
objQuestion.item = 'LOMA_371_PPQ2021_044';
objQuestion.primaryLO = '5C';
objQuestion.textref = 'c. 5, pp. 5-6';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '5C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Consider the descriptions of the product offerings of the following two companies:</p><ul class=\"examul\"><li>The Able Life Insurance Company collects 70% of its total premiums from term life insurance products, 18% from immediate annuity products, and 12% from variable deferred annuity&nbsp;products</li><li>The Butte Life Insurance Company offers term life insurance, fixed deferred annuities, variable deferred annuities, and immediate annuities</li></ul><p class=\"stem\">With regard to the marketing concept known as the product mix, it is correct to say that a product mix is represented by the description of</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "both Able’s and Butte’s product offerings";
arrAnsChoices[1] = "Able’s product offerings only";
arrAnsChoices[2] = "Butte’s product offerings only";
arrAnsChoices[3] = "neither Able’s nor Butte’s product offerings";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490632;
arrAnsIDs[1] = 490633;
arrAnsIDs[2] = 490634;
arrAnsIDs[3] = 490635;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">At least one of these descriptions is incorrect.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The description of Able’s product offerings represents the company’s product mix, which is a company’s total assortment of products within each line of business according to a monetary measure of business volume, such as premiums collected, reserves—or, in the case of life insurance, face amount in force. An insurer typically measures its product mix by proportion.</p><p class=\"explanations\">The description of Butte’s product offerings represents the company’s product portfolio, which is the array of all products a company offers for sale, categorized by line of business. For example, an insurer might have a life insurance portfolio and an annuity portfolio.</p><p class=\"explanations\">When launching a new product, a company adds to its product portfolio and alters the proportions of its product mix. For example, a new annuity product would broaden the product portfolio, but would also alter the proportionate amount of reserves held for annuities as a whole.</p><p class=\"explanations\"><b>Learning Objective: 5C. Explain the importance of a product mix and differentiate it from a product portfolio.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The description of Butte’s product offerings represents the company’s <b>product portfolio</b>, which is the array of all products a company offers for sale, categorized by line of business.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these descriptions is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_044'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_045';
objQuestion.questionID = 121322;
objQuestion.item = 'LOMA_371_PPQ2021_045';
objQuestion.primaryLO = '5D';
objQuestion.textref = 'c. 5, p. 6';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '5D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">In the context of product development, shelf life refers to how long an insurer can offer a product in the marketplace before it becomes obsolete and needs to be revised, repriced, or retired. With regard to an industry survey on the shelf life of variable universal life insurance products, term life insurance products, and whole life insurance products, it is correct to say that</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "variable universal life insurance products have the shortest shelf life";
arrAnsChoices[1] = "indexed universal life insurance products have the longest shelf life";
arrAnsChoices[2] = "term life insurance products have the longest shelf life";
arrAnsChoices[3] = "whole life insurance products have the longest shelf life";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490636;
arrAnsIDs[1] = 490637;
arrAnsIDs[2] = 490638;
arrAnsIDs[3] = 490639;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">According to an industry survey, whole life insurance products have a shelf life of 4.7 years, followed by variable universal life insurance at 3.4 years, term life insurance at 1.5 years, and indexed universal life insurance at 1.25 years.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">According to an industry survey, whole life insurance products have a shelf life of 4.7 years, followed by variable universal life insurance at 3.4 years, term life insurance at 1.5 years, and indexed universal life insurance at 1.25 years.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">According to an industry survey, whole life insurance products have a shelf life of 4.7 years, followed by variable universal life insurance at 3.4 years, term life insurance at 1.5 years, and indexed universal life insurance at 1.25 years.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">In the United States, most insurance and annuity products have a shelf life between one and five years. Generally, whole life insurance, life insurance products with riders, and fixed annuities tend to have longer shelf lives (nearly five years) than term life insurance products (less than two years).</p><p class=\"explanations\">According to an industry survey, whole life insurance products have a shelf life of 4.7 years, followed by variable universal life insurance at 3.4 years, and term life insurance at 1.5 years. Indexed products, such as indexed universal life insurance products and indexed annuity products, are the most prone to revision or retirement, with an average shelf life of about one to two years.</p><p class=\"explanations\"><b>Learning Objective: 5D. Identify a product’s average shelf life.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_045'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_046';
objQuestion.questionID = 121323;
objQuestion.item = 'LOMA_371_PPQ2021_046';
objQuestion.primaryLO = '5E';
objQuestion.textref = 'c. 5, pp. 6-8';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '5E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Companies can distinguish between product development projects based on their complexity. For example, a (<b>rate change</b> / <b>new product</b>) project is typically less complex than a product revision project. One example of a (<b>rate</b> <b>change</b> / <b>product revision</b>) project is the addition of a rider to an existing&nbsp;product.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "rate change / rate change";
arrAnsChoices[1] = "rate change / product revision";
arrAnsChoices[2] = "new product / rate change";
arrAnsChoices[3] = "new product / product revision";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490640;
arrAnsIDs[1] = 490641;
arrAnsIDs[2] = 490642;
arrAnsIDs[3] = 490643;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that a rate change project is typically less complex than a product revision project. However, the addition of a rider to an existing product is an example of a <b>product revision</b> project.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The more complex a product development project is, the more time the product takes to get to market. Rate change projects require planning, pricing, and possibly changing administration processes, pre-sales illustrations, and testing tools.</p><p class=\"explanations\">Product revision projects involve changes to an existing product that are more complex than rate change projects, and involve regulatory rate filings to reflect the changes. A new product project requires a full-scale effort in all phases of the product development process, including the development of new product features and the preparation of comprehensive regulatory filings.</p><p class=\"explanations\"><b>Learning Objective: 5E. Distinguish between product development projects on the basis of their complexity, and describe the effect complexity has on speed to market.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A new product project is the <b>most</b> complex type of product development project. Also, the addition of a rider to an existing product is an example of a <b>product revision</b> project.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that the addition of a rider to an existing product is an example of a product revision project. However, a new product project is the <b>most</b> complex type of product development project.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_046'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_047';
objQuestion.questionID = 121324;
objQuestion.item = 'LOMA_371_PPQ2021_047';
objQuestion.primaryLO = '5F';
objQuestion.textref = 'c. 5, p. 8';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '5F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Wonder Insurance Company attempts to deliver an exceptional customer experience (CX) by providing a seamless, high-quality experience across multiple communication platforms, such as the telephone, internet, mobile devices, social media, wearable devices, and in-person contacts. This information indicates that Wonder uses the type of customer experience strategy known as</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "a cross-functional team strategy";
arrAnsChoices[1] = "an omnichannel service strategy";
arrAnsChoices[2] = "a competitive intelligence strategy";
arrAnsChoices[3] = "a market analysis strategy";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490644;
arrAnsIDs[1] = 490645;
arrAnsIDs[2] = 490646;
arrAnsIDs[3] = 490647;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">In product development, an insurer typically assembles cross-functional teams. A <b>cross-functional team</b> comprises representatives from different functional areas of the company, such as investments, underwriting, actuarial, marketing, and information technology (IT).</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Customer experience (frequently abbreviated as CX) has become a vital part of doing business in all industries, including the life insurance industry. CX is the impression of a company that a customer forms as a result of every interaction the customer has with the company and its representatives. Customer expectations are so high that delivering an exceptional CX must be a priority for a life insurer.</p><p class=\"explanations\">To promote a stronger CX, insurers are developing more customizable products that allow customers to match their individual needs. Insurers can use the information collected from omnichannel services to assess customer risk profiles and to tailor new products and policies. This strategy seeks to provide a positive experience at each potential point of contact that a customer might have with the company.</p><p class=\"explanations\"><b>Learning Objective: 5F. Describe how changes in customer experience impact product development.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">New product ideas can come from research performed by a company’s competitive intelligence unit, usually a subdivision of the company’s product development team. <b>Competitive intelligence</b> is the systematic collection and analysis of publicly available information about competitors and ongoing developments in the marketing&nbsp;environment.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A <b>market analysis</b>, which is an element included in a comprehensive business analysis, documents an evaluation of all environmental factors that might affect sales of a proposed product. In essence, it represents the company’s effort to demonstrate that market demand exists to support a proposed product.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_047'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_048';
objQuestion.questionID = 121325;
objQuestion.item = 'LOMA_371_PPQ2021_048';
objQuestion.primaryLO = '5G';
objQuestion.textref = 'c. 5, pp. 9-10';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '5G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">As part of its product development process, the Orchard Life Insurance Company established a senior management group whose primary role is to provide overall guidance and control of enterprise risk management (ERM) efforts. This type of senior management group is known as a</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "legal and tax review committee";
arrAnsChoices[1] = "product development team";
arrAnsChoices[2] = "marketing committee";
arrAnsChoices[3] = "risk committee";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490648;
arrAnsIDs[1] = 490649;
arrAnsIDs[2] = 490650;
arrAnsIDs[3] = 490651;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Similar to a feasibility study, a <b>legal and tax review</b> evaluates any legal or tax concerns associated with a new&nbsp;product.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">An insurer’s <b>product development team</b> usually performs hands-on development of a new product.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">The <b>marketing committee</b> is a senior management group whose primary role is to provide overall guidance and control of the product development process.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Generally, the risk committee must ensure that all functional units have appropriately understood, measured, and arranged to manage all the risks associated with a new product. Specifically, the group reviews all risk exposures, risk policies, risk standards, and risk limits associated with a new product. The risk committee must express its support for any new product before the product can be launched.</p><p class=\"explanations\"><b>Learning Objective: 5G. Describe the teams that usually participate in the product development process.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_048'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_049';
objQuestion.questionID = 121326;
objQuestion.item = 'LOMA_371_PPQ2021_049';
objQuestion.primaryLO = '5H';
objQuestion.textref = 'c. 5, pp. 11-12';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '5H';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statement(s) can correctly be made about external factors that directly affect the market for a new product:</p><ol type=\"A\" class=\"combo\"><li>Different demographics have different purchasing patterns.</li><li>The overall state of the economy affects a person’s willingness to spend money.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490652;
arrAnsIDs[1] = 490653;
arrAnsIDs[2] = 490654;
arrAnsIDs[3] = 490655;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Statement A is correct. For example, older customers might favor researching services electronically but purchasing them in face-to-face transactions. As demographics shift, product development teams must consider what product features would have greater appeal for the growing sections of the market.</p><p class=\"explanations\">Statement B is correct. For example, when inflation outpaces wage growth, consumer budgets become more limited, and fewer consumers see insurance as a priority. In such an environment, a basic product with lower premiums is likely to be more attractive than an advanced product with higher premiums.</p><p class=\"explanations\"><b>Learning Objective: 5H. Identify external pressures that influence product development.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct. However, Statement B is also correct.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is correct. However, Statement A is also correct.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_049'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_050';
objQuestion.questionID = 121327;
objQuestion.item = 'LOMA_371_PPQ2021_050';
objQuestion.primaryLO = '5I';
objQuestion.textref = 'c. 5, p. 16';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '5I';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">In the product planning stage of product development, a team quickly and inexpensively evaluates new product ideas to separate workable ideas from those that have little or no potential This activity is known as</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "marketing projection";
arrAnsChoices[1] = "policy filing";
arrAnsChoices[2] = "idea generation";
arrAnsChoices[3] = "idea screening";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490656;
arrAnsIDs[1] = 490657;
arrAnsIDs[2] = 490658;
arrAnsIDs[3] = 490659;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\"><b>Marketing projections</b> are preliminary sales and financial forecasts that include estimates of potential unit sales, revenues, costs, and profits for a proposed product. A projection specifies an expected or a most likely value—rather than a best-case value or a worst-case value—for an unknown future value, to provide a realistic expectation for a product’s performance.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">To demonstrate compliance with regulatory requirements, an insurer makes a policy filing for each of its products. A <b>policy filing</b> is the act of submitting a policy contract form and any other legally required forms and documents to the appropriate state insurance department for approval.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\"><b>Idea generation</b> involves searching for new product ideas, as well as product revisions or product rate changes that are consistent with the needs of the company’s target markets and the company’s overall product development strategy.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Many companies apply a predetermined set of screening criteria. Insurance companies use the following criteria for screening new product concepts: alignment with the company’s corporate goals, strategies, and current market position; potential profitability; ability to meet customer needs; compatibility with the regulatory environment; and compatibility with the company’s corporate image, current systems, and existing or proposed distribution&nbsp;channels.</p><p class=\"explanations\"><b>Learning Objective: 5I. Explain the product planning stage of product development, including idea generation and idea screening.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_050'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_051';
objQuestion.questionID = 121328;
objQuestion.item = 'LOMA_371_PPQ2021_051';
objQuestion.primaryLO = '5J';
objQuestion.textref = 'c. 5, pp. 17-19';
objQuestion.textbook = 0;
objQuestion.chapter = 5;
objQuestion.module = 2;
var arrLOs = new Array();
arrLOs[0] = '5J';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The Vector Insurance Life Company is preparing product design objectives as part of a comprehensive business analysis for a proposed life insurance product. Vector’s product design objectives most likely include</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "rough projections of future sales volume, sales revenue, expenses, and profit";
arrAnsChoices[1] = "a presentation of a product idea to an internal team that decides whether to allocate company resources toward developing the product idea";
arrAnsChoices[2] = "the product’s basic characteristics, such as benefits, special features, and settlement options; and the product’s underwriting, risk, marketing, and technology specifications";
arrAnsChoices[3] = "an evaluation of how the product implementation will compete for resources with other company initiatives and how this interaction might affect the product’s speed to&nbsp;market";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490660;
arrAnsIDs[1] = 490661;
arrAnsIDs[2] = 490662;
arrAnsIDs[3] = 490663;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\"><b>Marketing projections</b> are defined in terms of sales volume—the number of units of product sold—and sales revenue—the total dollar volume of sales. Sale revenue is calculated by multiplying the sales volume by the average price per unit. To project important sales figures, marketers define expenses as the administrative costs the company incurs to support a product, plus the periodic income payments, cash surrenders, and other benefits the company will pay out.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A <b>product proposal</b>, or business plan, is used to present a product idea to an internal team that decides whether to allocate company resources toward developing the product idea. A product proposal that receives full management approval serves as an overall guide for technical product design and product&nbsp;introduction.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A comprehensive business analysis includes product design objectives, a feasibility study, a marketing plan, marketing projections, and—if the comprehensive business analysis indicates strong potential for the proposed product—a product proposal. Comprehensive business analysis asks: Given the factors potentially affecting the product, is this product a viable option for the company?</p><p class=\"explanations\">In general, product design objectives document a product’s basic characteristics, special features, and specifications, which serve as guidelines during technical design of the product.</p><p class=\"explanations\"><b>Learning Objective: 5J. Describe the elements of the comprehensive business analysis stage of product development, including a market analysis, product design objectives, a feasibility study, a marketing plan, marketing projections, and a product proposal.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A <b>feasibility study</b> evaluates whether the company has the capability to take a new product to market. Specifically, a feasibility study evaluates whether a product can be structured to be competitive and profitable; accommodated by the insurer’s operating and distribution systems; supported by the insurer’s current resources, employees, and technological capacity; and can comply with the company’s risk tolerance, underwriting policies, and reinsurance retention strategy.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_051'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['5A'] = "5A. Discuss the risks associated with launching new products.";
arrlotext['5B'] = "5B. Describe common product development strategies.";
arrlotext['5C'] = "5C. Explain the importance of a product mix and differentiate it from a product portfolio.";
arrlotext['5D'] = "5D. Identify a product’s average shelf life.";
arrlotext['5E'] = "5E. Distinguish between product development projects on the basis of their complexity, and describe the effect complexity has on speed to market.";
arrlotext['5F'] = "5F. Describe how changes in customer experience impact product development.";
arrlotext['5G'] = "5G. Describe the teams that usually participate in the product development process.";
arrlotext['5H'] = "5H. Identify external pressures that influence product development.";
arrlotext['5I'] = "5I. Explain the product planning stage of product development, including idea generation and idea screening.";
arrlotext['5J'] = "5J. Describe the elements of the comprehensive business analysis stage of product development, including a market analysis, product design objectives, a feasibility study, a marketing plan, marketing projections, and a product proposal.";
