var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2021';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 371 Practice Questions, Chapter 1";
var coursename = 'LOMA 371';
var modulenumber = 1;
var title = "LOMA_371_PPQ2021_0_1";
var intNumPools = 1;
var numQ = 8;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Risk Management and Product Design for Insurance Companies, Third Edition (2020)";
arrNumChap[0] = 1;
var thisChap = '1';

objPool = new Object(); 
objPool.intSelectCount = 8;
objPool.formID = 2621;
objPool.formName = 'PPQ2021_0_1';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_371_PQ_001';
arrPoolQuestions[1] = 'LOMA_371_PQ_002';
arrPoolQuestions[2] = 'LOMA_371_PQ_003';
arrPoolQuestions[3] = 'LOMA_371_PQ_004';
arrPoolQuestions[4] = 'LOMA_371_PQ_005';
arrPoolQuestions[5] = 'LOMA_371_PQ_006';
arrPoolQuestions[6] = 'LOMA_371_PQ_007';
arrPoolQuestions[7] = 'LOMA_371_PQ_008';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_001';
objQuestion.questionID = 121328;
objQuestion.item = 'LOMA_371_PPQ2021_001';
objQuestion.primaryLO = '1A';
objQuestion.textref = 'c. 1, pp. 2-3, 4-5';
objQuestion.textbook = 0;
objQuestion.chapter = 1;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '1A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The two primary goals of any insurer are to ensure solvency and increase profitability. In general, an insurer seeks to earn a level of profit that will both satisfy immediate financial needs and enhance the company’s long-term profitability goals. For an insurer, the long-term benefits of having strong profitability include all of the following <B>EXCEPT</B> for</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "higher interest rates on borrowed funds";
arrAnsChoices[1] = "higher ratings from rating agencies";
arrAnsChoices[2] = "greater ability to price products competitively";
arrAnsChoices[3] = "greater growth and capacity to serve more customers";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490668;
arrAnsIDs[1] = 490669;
arrAnsIDs[2] = 490670;
arrAnsIDs[3] = 490671;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Some benefits of strong solvency overlap benefits of strong profitability. However, profitability goals—such as investing enough assets to increase the probability of a strong return—sometimes conflict with solvency goals—such as retaining assets to pay possible liabilities.</p><p class=\"explanations\">Insurers must be especially careful about the risks they take when pursuing profitability because (1) the purpose of the insurance industry is to provide financial protection for customers, and the promises made by insurance companies may span many decades and (2) the various regulatory requirements placed on insurance companies demand financial strength and stability.</p><p class=\"explanations\"><b>Learning Objective: 1A. Describe the strengths of strong solvency and strong profitability.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">For an insurer, higher quality ratings from rating agencies <b>is </b>a long-term benefit of having strong&nbsp;profitability.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">For an insurer, greater ability to price products competitively <b>is</b> a long-term benefit of having strong&nbsp;profitability.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">For an insurer, greater growth and capacity to serve more customers <b>is</b> a long-term benefit of having strong&nbsp;profitability.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_001'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_002';
objQuestion.questionID = 121329;
objQuestion.item = 'LOMA_371_PPQ2021_002';
objQuestion.primaryLO = '1B';
objQuestion.textref = 'c. 1, pp. 3-4';
objQuestion.textbook = 0;
objQuestion.chapter = 1;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '1B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">According to the risk-return tradeoff, with regard to the risk of an investment and the potential return on that investment, it is correct to say that, all other factors being equal, the</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "greater the risk associated with the investment, the lower the potential return on the investment";
arrAnsChoices[1] = "greater the risk associated with the investment, the greater the potential return on the&nbsp;investment";
arrAnsChoices[2] = "riskiness of the investment does not affect the investment’s potential rate of return";
arrAnsChoices[3] = "greatest potential return on an investment results from an investment that has no risk associated with it";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490672;
arrAnsIDs[1] = 490673;
arrAnsIDs[2] = 490674;
arrAnsIDs[3] = 490675;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">According to the risk-return tradeoff, all other factors being equal, the greater the risk associated with an investment, the <b>greater</b> the potential return on the investment.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">To ensure strong solvency, an insurer must maintain capital and manage risk. To maintain strong profitability, an insurer must invest capital and take risk. A responsible investment balances the risk incurred with the potential return.</p><p class=\"explanations\">If a company holds on to too much capital rather than making investments, it cannot expect strong returns. A company that invests heavily in a risky venture accepts higher risks to its solvency to pursue higher expected returns. Conversely, a company that invests in a conservative venture accepts lower risks and lower expected returns.</p><p class=\"explanations\"><b>Learning Objective: 1B. Identify the characteristics of high-risk and low-risk investments.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">According to the risk-return tradeoff, all other factors being equal, the greater the risk associated with an investment, the <b>greater</b> the potential return on the investment and, the lower the risk associated with an investment, the <b>lower</b> the potential return on the investment.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">If a company holds on to too much capital rather than making investments, it <b>cannot</b> expect strong returns. According to the risk-return tradeoff, all other factors being equal, the <b>greater</b> the risk associated with an investment, the greater the potential return on the investment.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_002'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_003';
objQuestion.questionID = 121330;
objQuestion.item = 'LOMA_371_PPQ2021_003';
objQuestion.primaryLO = '1C';
objQuestion.textref = 'c. 1, pp. 7-8';
objQuestion.textbook = 0;
objQuestion.chapter = 1;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '1C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Establishing a risk management culture includes defining a company’s risk appetite and risk tolerance. One common definition of (<b>risk appetite</b> / <b>risk&nbsp;tolerance</b>) is that it refers to the amount and type of risk that a company is prepared to seek in the pursuit of profits or other strategic objectives. Risk tolerance is a (<b>quantitative / qualitative</b>) expression of a company’s risk appetite.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "risk appetite / quantitative";
arrAnsChoices[1] = "risk appetite / qualitative";
arrAnsChoices[2] = "risk tolerance / quantitative";
arrAnsChoices[3] = "risk tolerance / qualitative";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490676;
arrAnsIDs[1] = 490677;
arrAnsIDs[2] = 490678;
arrAnsIDs[3] = 490679;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">One key method of establishing a risk management culture is enterprise risk management (ERM), which focuses on operations throughout a company, to the point that ERM becomes part of company culture.</p><p class=\"explanations\">Another part of establishing a risk management culture is defining a company’s risk appetite and risk tolerance. Risk tolerance is a company’s willingness and readiness to bear a risk to achieve its objectives; this tolerance usually is expressed as the company’s stated limits on risk-taking in specified categories. Under this two-tiered approach, risk appetite is a qualitative concept that describes a company’s attitude toward risk, while risk tolerance becomes the quantitative expression of the company’s risk appetite.</p><p class=\"explanations\"><b>Learning Objective: 1C. Explain the relationship between a risk management culture and product development.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that risk appetite refers to the amount and type of risk that a company is prepared to seek in the pursuit of profits or other strategic objectives. However, risk tolerance is a <b>quantitative</b> expression of a company’s risk appetite.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that risk tolerance is a quantitative expression of a company’s risk appetite. However, <b>risk tolerance</b> is a company’s willingness and readiness to bear a risk to achieve its objectives; this tolerance usually is expressed as the company’s stated limits on risk-taking in specified categories.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\"><b>Risk tolerance</b> is a company’s willingness and readiness to bear a risk to achieve its objectives; this tolerance usually is expressed as the company’s stated limits on risk-taking in specified categories. In addition, risk tolerance is a <b>quantitative</b> expression of a company’s risk appetite.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_003'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_004';
objQuestion.questionID = 121331;
objQuestion.item = 'LOMA_371_PPQ2021_004';
objQuestion.primaryLO = '1D';
objQuestion.textref = 'c. 1, pp. 9-11';
objQuestion.textbook = 0;
objQuestion.chapter = 1;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '1D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Advances in technology have enabled insurers to collect and analyze big data to help them better understand customer needs and preferences. To analyze big data, insurers are increasingly hiring data scientists as well as actuaries. With regard to comparisons between the typical roles of data scientists and actuaries in analyzing big data, it is generally true that</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "data scientists specialize in using traditional, retrospective methods to predict future outcomes";
arrAnsChoices[1] = "data scientists have more experience with probability and the financial impacts of analysis";
arrAnsChoices[2] = "actuaries have a stronger focus on risk and must adhere to strictly regulated methods and tests";
arrAnsChoices[3] = "actuaries tend to focus on new techniques and the search for potential opportunities";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490680;
arrAnsIDs[1] = 490681;
arrAnsIDs[2] = 490682;
arrAnsIDs[3] = 490683;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\"><b>Actuaries</b> generally specialize in using traditional, retrospective methods to predict future outcomes.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\"><b>Actuaries</b> generally have more experience in constructing financial models to provide more accurate estimations with probability and the financial impacts of analysis.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Compared to data scientists, actuaries generally have more experience with probability and financial modeling and the financial ramifications and impacts of analysis; use past experience and established, retrospective methods to project future outcomes; are required to adhere to strictly regulated methods and tests; and have a stronger focus on risk. A notable aspect of actuarial work is the effort to anticipate circumstances beyond the company’s control by modeling unexpected outcomes and their impacts.</p><p class=\"explanations\">Compared to actuaries, data scientists typically have more experience with computer science and use new methods and techniques—such as neural networks and natural language processing—and explore prospective approaches; focus more on the search for potential opportunities; and answer primarily to company management.</p><p class=\"explanations\"><b>Learning Objective: 1D. Explain the actuary’s role in risk management and technical product design and differentiate between actuaries and data scientists.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\"><b>Data scientists</b> typically have more experience with computer science and specialize in new techniques such as neural networks and natural language processing.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_004'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_005';
objQuestion.questionID = 121332;
objQuestion.item = 'LOMA_371_PPQ2021_005';
objQuestion.primaryLO = '1E';
objQuestion.textref = 'c. 1, pp. 11-12';
objQuestion.textbook = 0;
objQuestion.chapter = 1;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '1E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">A control cycle is a repetitive process designed to ensure that all areas of a company adhere to the company’s performance standards. Specifically, the actuarial control cycle is a process of three repeated steps. Select the answer choice that correctly places these three steps in order, beginning with the first step.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "design the solution &rarr; define the need &rarr; monitor the results";
arrAnsChoices[1] = "design the solution &rarr; monitor the results &rarr; define the need";
arrAnsChoices[2] = "define the need &rarr; design the solution &rarr; monitor the results";
arrAnsChoices[3] = "define the need &rarr; monitor the results &rarr; design the solution";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490684;
arrAnsIDs[1] = 490685;
arrAnsIDs[2] = 490686;
arrAnsIDs[3] = 490687;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The three steps of the actuarial control cycle are define the need (or sometimes define the problem), design the solution, and monitor the results, which is an ongoing step. The cycle then repeats, beginning with the first step.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">The three steps of the actuarial control cycle are define the need (or sometimes define the problem), design the solution, and monitor the results, which is an ongoing step. The cycle then repeats, beginning with the first step.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Actuarial functions generally involve applying the actuarial control cycle to a specific discipline or problem. In the context of new product development, the three steps of the actuarial control cycle begin with the first two steps: define the need (or sometimes define the problem)—by determining a customer need that is not being satisfied—and design the solution—by creating a product that will serve that customer need.</p><p class=\"explanations\">Once the product is on the market, the company conducts the third step: monitor the results—by seeing how the product’s lapse rates, expenses, number of claims, and other variables are performing compared to the assumptions made during technical product design—which is an ongoing step. The actuarial control cycle then repeats, beginning with the first step.</p><p class=\"explanations\"><b>Learning Objective: 1E. Describe the actuarial control cycle.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The three steps of the actuarial control cycle are define the need (or sometimes define the problem), design the solution, and monitor the results, which is an ongoing step. The cycle then repeats, beginning with the first step.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_005'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_006';
objQuestion.questionID = 121333;
objQuestion.item = 'LOMA_371_PPQ2021_006';
objQuestion.primaryLO = '1F';
objQuestion.textref = 'c. 1, pp. 12-13';
objQuestion.textbook = 0;
objQuestion.chapter = 1;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '1F';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Jonas Evert, an outside consultant, is an actuary whose job responsibilities include preparing actuarial reports for insurers and reviewing the assumptions behind proposed products. He is expected to provide impartial advice to clients. Mr.&nbsp;Evert met the qualification standards set by the American Academy of Actuaries to be eligible for this position. This information indicates that Mr.&nbsp;Evert most likely is the type of actuary known as</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "a risk actuary";
arrAnsChoices[1] = "a finance and investment actuary";
arrAnsChoices[2] = "a resource and environmental actuary";
arrAnsChoices[3] = "an appointed actuary";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490688;
arrAnsIDs[1] = 490689;
arrAnsIDs[2] = 490690;
arrAnsIDs[3] = 490691;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A <b>risk actuary</b> typically is involved in a company’s enterprise risk management (ERM) processes.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A <b>finance and investment actuary</b> typically works with bonds, stocks, real estate, and other investments.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A <b>resource and environmental actuary</b> typically studies the effects of various environmental risks—such as climate change—on the financial and business world, and then develops appropriate responses to these risks.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">Most actuaries work in the insurance industry as employees or outside consultants. Some specialize in a function; others have a variety of responsibilities. Although these categories are not mutually exclusive, the following are some of the most common types of actuaries: insurance actuaries, risk actuaries, financial and investment actuaries, pension actuaries, and appointed actuaries.</p><p class=\"explanations\">The designation of appointed actuary, also called a valuation actuary or qualified actuary, has more to do with qualifications than a line of specific work. Qualification standards vary by country. Appointed actuaries may be employees of an insurer, or contracted consultants from third-party firms.</p><p class=\"explanations\"><b>Learning Objective: 1F. Distinguish between types of actuaries.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_006'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_007';
objQuestion.questionID = 121334;
objQuestion.item = 'LOMA_371_PPQ2021_007';
objQuestion.primaryLO = '1G';
objQuestion.textref = 'c. 1, p. 15';
objQuestion.textbook = 0;
objQuestion.chapter = 1;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '1G';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statement(s) can correctly be made about the potential advantages gained from an insurer’s analysis of experience data:</p><ol type=\"A\" class=\"combo\"><li>By comparing experience data to the actuarial assumptions used in an insurer’s models, actuaries can determine whether these assumptions properly reflect changing conditions.</li><li>If an insurer can understand its customer lapse patterns, the insurer can design products so that actual lapse rates are more likely to meet the insurer’s targeted lapse rates.</li></ol>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "Both A and B";
arrAnsChoices[1] = "A only";
arrAnsChoices[2] = "B only";
arrAnsChoices[3] = "Neither A nor B";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490692;
arrAnsIDs[1] = 490693;
arrAnsIDs[2] = 490694;
arrAnsIDs[3] = 490695;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">Statement A and Statement B are correct. A key actuarial responsibility is experience analysis, which involves testing actuarial assumptions against past experience by analyzing experience data. Experience analysis also may involve industry-wide data sources and consultants. One example of experience data is a company’s sales, premium payment, and lapse records for an insurance product line. An insurer’s records or accounting systems maintain experience data.</p><p class=\"explanations\"><b>Learning Objective: 1G. Identify potential advantages gained from analyzing experience data.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Statement A is correct. However, Statement B is also correct.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Statement B is correct. However, Statement A is also correct.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">At least one of these statements is correct.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_007'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_008';
objQuestion.questionID = 121335;
objQuestion.item = 'LOMA_371_PPQ2021_008';
objQuestion.primaryLO = '1H';
objQuestion.textref = 'c. 1, pp. 17-18';
objQuestion.textbook = 0;
objQuestion.chapter = 1;
objQuestion.module = 1;
var arrLOs = new Array();
arrLOs[0] = '1H';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The following statements are about the opportunities and challenges associated with an insurer’s use of big data. Three statements are true, and one statement is false. Select the answer choice containing the <B>FALSE</B> statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "The actuarial skillset in fraud analytics contributes to an insurer’s efforts to detect fraud, such as by building predictive models using a variety of data sources.";
arrAnsChoices[1] = "The existence of big data quickly enables smaller insurers to find the most relevant, credible data in areas such as underwriting, risk assessment, and product development.";
arrAnsChoices[2] = "The potential of automated underwriting and the development of artificial intelligence for financial applications are examples of insurtech, short for “insurance technology.”";
arrAnsChoices[3] = "The increasing complexity of financial models means that actuaries often must provide more documentation for models, and the models require additional testing and annual re-testing.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 490696;
arrAnsIDs[1] = 490697;
arrAnsIDs[2] = 490698;
arrAnsIDs[3] = 490699;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response. As fraud methods—such as account takeover—become more sophisticated, actuaries play an increasingly important role in fraud analytics.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Big data provides the opportunity for even greater accuracy in areas such as underwriting, risk assessment, and product development. However, the high complexity and volume of big data make it difficult to quickly find the most relevant and credible data.</p><p class=\"explanations\">One challenge of big data is determining what to do with it. Actuaries, often in tandem with data scientists, face the challenge of determining not only what data is most germane to an insurer’s goals, but also understanding the relationships between the many variables involved.</p><p class=\"explanations\"><b>Learning Objective: 1H. Describe the opportunities and challenges of big data.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response. Insurtech has the potential to render many old ways of doing business obsolete, which may provide both positive opportunities—such as reaching customer needs—and negative consequences, such as the costs associated with rapid, exhaustive&nbsp;change.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">This statement is true; therefore, it is <b>not</b> the correct response. An appointed actuary generally must verify the assumptions underlying financial models. For example, a single financial model may require a complicated set of permissions that detail who can change the model, request a change to the model, or approve a change to the model.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_008'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['1A'] = "1A. Describe the strengths of strong solvency and strong profitability.";
arrlotext['1B'] = "1B. Identify the characteristics of high-risk and low-risk investments.";
arrlotext['1C'] = "1C. Explain the relationship between a risk management culture and product development.";
arrlotext['1D'] = "1D. Explain the actuary’s role in risk management and technical product design and differentiate between actuaries and data scientists.";
arrlotext['1E'] = "1E. Describe the actuarial control cycle.";
arrlotext['1F'] = "1F. Distinguish between types of actuaries.";
arrlotext['1G'] = "1G. Identify potential advantages gained from analyzing experience data.";
arrlotext['1H'] = "1H. Describe the opportunities and challenges of big data.";
