var intPassingScore = 70;
var randomize = 0;
var feedbacktype = 'answerlevel';
var arrQuestions = new Object();
var arrJ = new Object();
var arrPools = new Array();
var objPool;
var arrPoolQuestions;
var arrMinicases = new Array();
var objQuestion;
var arrChoices;
var arrCorrectChoices;
var strTestLocaleId = 'en-US';
var strCopyright = '2021';
var mediatype = 'Practice Questions';
var mediashort = 'PPQ'; //use this in name of state status
var coursetype = 'pdf';

var quizname = "LOMA 371 Practice Questions, Chapter 11";
var coursename = 'LOMA 371';
var modulenumber = 4;
var title = "LOMA_371_PPQ2021_0_11";
var intNumPools = 1;
var numQ = 6;
var numTexts = 1;
var numChap = 1;
var arrTexts = new Array();
var arrNumChap = new Array();
var duration = 0;
arrTexts[0] = "Risk Management and Product Design for Insurance Companies, Third Edition (2020)";
arrNumChap[0] = 1;
var thisChap = '11';

objPool = new Object(); 
objPool.intSelectCount = 6;
objPool.formID = 2621;
objPool.formName = 'PPQ2021_0_11';
arrPoolQuestions = new Array();
arrPoolQuestions[0] = 'LOMA_371_PQ_107';
arrPoolQuestions[1] = 'LOMA_371_PQ_108';
arrPoolQuestions[2] = 'LOMA_371_PQ_109';
arrPoolQuestions[3] = 'LOMA_371_PQ_110';
arrPoolQuestions[4] = 'LOMA_371_PQ_111';
arrPoolQuestions[5] = 'LOMA_371_PQ_112';
objPool.arrPoolQuestions = arrPoolQuestions;
arrPools[0] = objPool;

objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_107';
objQuestion.questionID = 121434;
objQuestion.item = 'LOMA_371_PPQ2021_107';
objQuestion.primaryLO = '11A';
objQuestion.textref = 'c. 11, pp. 5-6';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '11A';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">The benefits offered by deferred annuities usually differ between the accumulation period and the payout period. One type of annuity benefit that may be payable during the payout period, but usually would <i>not</i> be payable during the accumulation period, is a</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "withdrawal benefit";
arrAnsChoices[1] = "surrender benefit";
arrAnsChoices[2] = "death benefit";
arrAnsChoices[3] = "periodic income payment";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 491100;
arrAnsIDs[1] = 491101;
arrAnsIDs[2] = 491102;
arrAnsIDs[3] = 491103;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A withdrawal benefit is payable during the accumulation period, but usually is <b>not </b>payable during the payout period, of an annuity.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A surrender benefit is payable during the accumulation period, but usually is <b>not </b>payable during the payout period, of an annuity.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A death benefit is payable during the accumulation period, but usually is <b>not</b> payable during the payout period, of an annuity, unless the payout option contains a death benefit component.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">One way to look at the benefits under annuities is by annuity type. For instance, fixed immediate annuities have a payout period, but no accumulation period. Therefore, such annuities do not pay death benefits or surrender or withdrawal benefits. Because fixed-rate and variable deferred annuities have an accumulation period, they have the potential to pay death benefits, surrender benefits, and or withdrawal&nbsp;benefits.</p><p class=\"explanations\"><b>Learning Objective: 11A. Differentiate between types of annuities, including immediate annuities, deferred annuities, fixed annuities, fixed indexed annuities, and variable annuities.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_107'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_108';
objQuestion.questionID = 121435;
objQuestion.item = 'LOMA_371_PPQ2021_108';
objQuestion.primaryLO = '11B';
objQuestion.textref = 'c. 11, pp. 6-7, 7-8, 9-12';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '11B';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Insurers estimate annuity benefits and the cost considerations for each benefit cost. Annuity benefits include future annuity death benefits, surrender benefits, withdrawal benefits, and periodic income payments. The following statements are about how insurers estimate the cost of future deferred annuity death benefits. Select the answer choice containing the correct statement.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "The amount of a future death benefit depends only on the amount of premiums paid on the&nbsp;contract.";
arrAnsChoices[1] = "Insurers ignore expected surrenders when determining the number of death benefits payable each year.";
arrAnsChoices[2] = "Withdrawal rates for deferred annuities are usually the lowest during the early years of the accumulation period.";
arrAnsChoices[3] = "For guaranteed annuity payout options, the cost of future payments at the start of the payout period equals the contract’s accumulated value at the maturity date.";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 491104;
arrAnsIDs[1] = 491105;
arrAnsIDs[2] = 491106;
arrAnsIDs[3] = 491107;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">The amount of a deferred annuity’s death benefit generally depends on the <b>accumulated value</b> of the contract at the time of the annuitant’s death rather than on the amount of premiums paid on the contract. However, certain contracts offer a return of premium death benefit as part of the contract, allowing for the greater of the accumulation value or premiums paid less withdrawals.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Insurers typically <b>subtract</b> the expected number of surrenders from the number of in-force contracts at the beginning of the contract&nbsp;year. When estimating the cost of deferred annuity surrender benefits, insurers assume that surrender benefits will be paid at the beginning of each year. They also use mortality rates to estimate the number of annuitants at the beginning of any given year during the accumulation&nbsp;period.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\"><b>Surrender</b> rates for deferred annuities are usually the lowest during the early years of the accumulation period, and spike after the end of the contract’s surrender charge period; such spikes in surrender rates are known as shock lapses. Insurers use the contractually specified withdrawal rate percents—usually 5-10 percent of the contract’s accumulated value each year—to determine the cost of withdrawals for each year during the accumulation period. As with surrenders, insurers sum the withdrawal values for each year of the accumulation period to determine the total value of withdrawals.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">The total cost of benefits for an annuity equals the sum of the present value of each potential benefit multiplied by the expected probability that each benefit will be payable. The process used to estimate the cost of future deferred annuity death benefits is similar to that used to estimate the cost of life insurance death benefits. In addition, the formula for determining annuity premiums is similar to that for determining life insurance premiums: the charge for cost of benefits + the charge for operating expenses + the provision for adverse deviation or contributions to earnings – investment earnings.</p><p class=\"explanations\">Insurers estimate the cost of surrender benefits for a future year based on the number of in-force contracts at the beginning of the year, the expected surrender rate for each year, and the surrender value per unit. Insurers assume that surrender benefits will be paid at the beginning of each year. Insurers use the contractually specified withdrawal rate percents—usually 5-10 percent of the contract’s accumulated value each year—to determine the cost of withdrawals for each year during the accumulation period. Then, insurers sum the annual surrender benefits and the withdrawal values for each year during the accumulation period to determine the total value of the surrenders and withdrawals.</p><p class=\"explanations\">Insurers generally calculate the present values (PVs) of their future payments and sum the PVs to estimate the total cost of periodic income payments. For guaranteed annuity payout options, the insurer’s cost of future payments at the start of the payout period equals a deferred annuity contract’s accumulated value at the maturity date, or conversion date, when the contract is annuitized. Life annuity payout options expose insurers to mortality risk because calculations for life annuities rely on the mortality experience of a population of annuitants. Insurers must estimate the cost of the lifetime guarantees based on the life expectancies of the&nbsp;annuitants.</p><p class=\"explanations\"><b>Learning Objective: 11B. Describe how insurance companies estimate the cost of future annuity death benefits, surrender benefits, withdrawal benefits, and periodic income payments.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_108'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_109';
objQuestion.questionID = 121436;
objQuestion.item = 'LOMA_371_PPQ2021_109';
objQuestion.primaryLO = '11C';
objQuestion.textref = 'c. 11, pp. 9-10';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '11C';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Portia Stroud chose a life annuity payout option that guarantees periodic income payments throughout her lifetime and that periodic income payments will continue for at least 10 years. When Ms.&nbsp;Stroud died after receiving periodic income payments for seven years, the insurer continued to make periodic income payments to Ms.&nbsp;Stroud’s beneficiary for three years. This information indicates that Ms.&nbsp;Stroud chose the type of annuity payout option known as a</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "single life annuity with period certain";
arrAnsChoices[1] = "joint life annuity";
arrAnsChoices[2] = "joint and last survivorship annuity";
arrAnsChoices[3] = "single life with refund annuity";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 491108;
arrAnsIDs[1] = 491109;
arrAnsIDs[2] = 491110;
arrAnsIDs[3] = 491111;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 1;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A single life annuity with period certain guarantees periodic income payments throughout the lifetime of the annuitant and also guarantees that the payments will continue for at least a specified period. If the annuitant dies before the end of the specified period, the insurer provides the periodic income payments to the beneficiary until the end of the period. If the annuitant dies after the end of the specified period, the beneficiary does not receive any periodic income payments.</p><p class=\"explanations\"><b>Learning Objective: 11C. Describe and differentiate between the types of guaranteed annuity payout options and life annuity payout options.</b></p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">A joint life annuity typically <b>covers more than one life</b> and guarantees periodic income payments until one of the annuitants dies, and then pays nothing more.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A joint and survivor (J&S) annuity, also known as a joint and last survivorship annuity, is a payout option that guarantees a series of periodic income payments to two or more annuitants until both or <b>all of the annuitants die</b>. The insurer bases periodic income payments on the life expectancies of the annuitants. Depending on the terms of the annuity, payments may decrease after the first annuitant dies.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">A single life with refund annuity guarantees specified periodic income payments throughout the lifetime of the annuitant and also guarantees that the insurer will <b>provide a refund</b> if the annuitant dies before the total periodic income payments made to the annuitant equals the amount paid for the annuity. In such a scenario, the contract’s beneficiary receives the refund, which is the difference between the amount the contract owner paid for the annuity and the total amount of periodic income payments paid to the annuitant prior to her death. The refund of the remaining premium can be paid to the beneficiary as a lump sum (cash refund) or in payments (installment refund).</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_109'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_110';
objQuestion.questionID = 121437;
objQuestion.item = 'LOMA_371_PPQ2021_110';
objQuestion.primaryLO = '11D';
objQuestion.textref = 'c. 11, pp. 15-16, 17-18';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '11D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Admiral Insurance issued a fixed indexed annuity (FIA) that has a 90% participation percentage, a 7% cap, and no yield spread. For the most recent period, the reference index increased by 8%. In this situation, the amount of interest that Admiral credits to the FIA contract’s accumulated value is</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "6.3%";
arrAnsChoices[1] = "6.5%";
arrAnsChoices[2] = "7.0%";
arrAnsChoices[3] = "7.2%";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 491112;
arrAnsIDs[1] = 491113;
arrAnsIDs[2] = 491114;
arrAnsIDs[3] = 491115;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 3;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">In this situation, for a period in which the reference index increased by 8%, a participation percentage of 90% reduces the growth rate credited to the FIA contract’s accumulated value to 7.2%. Because the FIA contract has a 7% cap, the amount of interest that Admiral credits to the contract’s accumulated value is limited to the 7% cap rate.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">In this situation, for a period in which the reference index increased by 8%, a participation percentage of 90% reduces the growth rate credited to the FIA contract’s accumulated value to 7.2%. Because the FIA contract has a 7% cap, the amount of interest that Admiral credits to the contract’s accumulated value is limited to the 7% cap rate.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">A participation percentage provision stipulates the rate at which the insurer shares the reference index’s growth with the contract owner. A cap is an upper limit on the amount of a reference index’s gain in value that the insurer credits to the annuity contract as interest. The insurer limits the percentage amount of interest it credits to the contract to the capped rate.</p><p class=\"explanations\">In this situation, for a period in which the reference index increased by 8%, a participation percentage of 90% reduces the growth rate credited to the FIA contract’s accumulated value to 7.2%. Because the FIA contract has a 7% cap, the amount of interest that Admiral credits to the contract’s accumulated value is limited to the 7% cap rate.</p><p class=\"explanations\"><b>Learning Objective: 11D. Identify the fixed indexed annuity provisions that pertain to indexed crediting and explain the methods for calculating index credits, including the annual reset method, the point-to-point method, and the high water mark method.</b></p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">In this situation, for a period in which the reference index increased by 8%, a participation percentage of 90% reduces the growth rate credited to the FIA contract’s accumulated value to 7.2%. Because the FIA contract has a 7% cap, the amount of interest that Admiral credits to the contract’s accumulated value is limited to the 7% cap rate.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_110'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_111';
objQuestion.questionID = 121438;
objQuestion.item = 'LOMA_371_PPQ2021_111';
objQuestion.primaryLO = '11D';
objQuestion.textref = 'c. 11, pp. 16-17';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '11D';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Wanda Hubley purchased a fixed indexed annuity (FIA) contract with a single premium of $200,000. The FIA has a 75% participation percentage, a 10% cap, and no yield spread. Ms.&nbsp;Hubley chose the method of calculating index growth in which the value of the reference index at the end of each contract year is compared to the value of the index at the start of the year. For Ms.&nbsp;Hubley’s FIA, the reference index equaled 750 at the beginning of Year 1, 800 at the end of Year 1, and 875 at the end of Year 2. Select the answer choice that correctly identifies the method that Ms.&nbsp;Hubley chose for calculating index growth and the accumulated value of Ms.&nbsp;Hubley’s FIA at the end of Year 2.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[-1] = "<u>Index credit calculation method</u></div><div class=\"anshead\"><u>FIA value, end of Year 2</u>";
arrAnsChoices[0] = "annual reset method</div><div class=\"anscell\" onclick=\"recordAns(1);\">$210,000";
arrAnsChoices[1] = "annual reset method</div><div class=\"anscell\" onclick=\"recordAns(2);\">$224,763";
arrAnsChoices[2] = "high water mark method</div><div class=\"anscell\" onclick=\"recordAns(3);\">$210,000";
arrAnsChoices[3] = "high water mark method</div><div class=\"anscell\" onclick=\"recordAns(4);\">$224,763";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 491117;
arrAnsIDs[1] = 491118;
arrAnsIDs[2] = 491119;
arrAnsIDs[3] = 491120;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 2;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">It is true that Ms.&nbsp;Hubley chose the annual reset method for calculating index growth. However, the accumulated value of Ms.&nbsp;Hubley’s FIA at the end of Year 2 is <b>not</b> $210,000.</p><p class=\"explanations\">To calculate the growth of Ms.&nbsp;Hubley’s FIA at the end of Year 1, calculate how much the reference index grew: (800 – 750) ÷ 750 = 6.67% at the end of Year 1. Adjusting the 6.67% growth in the index by the 75% participation percentage results in (6.67% × 0.75) = 5% interest. Because 5% is less than the 10% cap, the interest rate to apply to the FIA contract value at the end of Year 1 is 5%. The accumulated value of the FIA is $200,000 × 1.05 = $210,000, which is the FIA contract value at the beginning of Year 2.</p><p class=\"explanations\">At the end of Year 2, the reference index grew by (875 – 800) ÷ 800 = 9.38%. Adjusting the growth in the index by the 75% participation percentage results in (9.38% × 0.75) = 7.03% interest. Because 7.03% is less than the 10% cap, the interest rate to apply to the FIA contract value at the end of Year 1 is 7.03%. The accumulated value of the FIA is $210,000 × 1.0703 = $224,763 at the end of Year 2, which is the FIA contract value at the beginning of Year 3.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">Under the annual reset method, also known as the ratchet method, index values are reset at the beginning of each contract year during the term of the contract. The annual reset method allows the contract owner to lock in gains each year and avoid losses. When the market goes up, the contract owner earns excess interest. When the market remains stable or goes down, the contract neither gains nor loses value.</p><p class=\"explanations\">To calculate the growth of Ms.&nbsp;Hubley’s FIA at the end of Year 1, calculate how much the reference index grew: (800 – 750) ÷ 750 = 6.67% at the end of Year 1. Adjusting the 6.67% growth in the index by the 75% participation percentage results in (6.67% × 0.75) = 5% interest. Because 5% is less than the 10% cap, the interest rate to apply to the FIA contract value at the end of Year 1 is 5%. The accumulated value of the FIA is $200,000 × 1.05 = $210,000, which is the FIA contract value at the beginning of Year 2.</p><p class=\"explanations\">At the end of Year 2, the reference index grew by (875 – 800) ÷ 800 = 9.38%. Adjusting the growth in the index by the 75% participation percentage results in (9.38% × 0.75) = 7.03% interest. Because 7.03% is less than the 10% cap, the interest rate to apply to the FIA contract value at the end of Year 1 is 7.03%. The accumulated value of the FIA is $210,000 × 1.0703 = $224,763 at the end of Year 2, which is the FIA contract value at the beginning of Year 3.</p><p class=\"explanations\">The point-to-point, annual reset, and high water mark methods allow the contract owner to take advantage of index gains without being subject to index losses. The advantage of using high water marks instead of methods that use term-end or year-end values is that earnings are not dependent on index growth at the end of each term (point-to-point method) or contract year (annual reset method). Under the high water mark method, the index need only show growth on any contract anniversary date to earn index credits.</p><p class=\"explanations\"><b>Learning Objective: 11D. Identify the fixed indexed annuity provisions that pertain to indexed crediting and explain the methods for calculating index credits, including the annual reset method, the point-to-point method, and the high water mark method.</b></p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">Ms.&nbsp;Hubley did <b>not</b> choose the high water mark method for calculating index growth. In addition, the accumulated value of Ms.&nbsp;Hubley’s FIA at the end of Year 2 is <b>not</b> $210,000.</p><p class=\"explanations\">To calculate the growth of Ms.&nbsp;Hubley’s FIA at the end of Year 1, calculate how much the reference index grew: (800 – 750) ÷ 750 = 6.67% at the end of Year 1. Adjusting the 6.67% growth in the index by the 75% participation percentage results in (6.67% × 0.75) = 5% interest. Because 5% is less than the 10% cap, the interest rate to apply to the FIA contract value at the end of Year 1 is 5%. The accumulated value of the FIA is $200,000 × 1.05 = $210,000, which is the FIA contract value at the beginning of Year 2.</p><p class=\"explanations\">At the end of Year 2, the reference index grew by (875 – 800) ÷ 800 = 9.38%. Adjusting the growth in the index by the 75% participation percentage results in (9.38% × 0.75) = 7.03% interest. Because 7.03% is less than the 10% cap, the interest rate to apply to the FIA contract value at the end of Year 1 is 7.03%. The accumulated value of the FIA is $210,000 × 1.0703 = $224,763 at the end of Year 2, which is the FIA contract value at the beginning of Year 3.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">It is true that the accumulated value of Ms.&nbsp;Hubley’s FIA at the end of Year 2 is $224,763. However, Ms.&nbsp;Hubley did <b>not</b> choose the high water mark method for calculating index growth.</p><p class=\"explanations\">To calculate the growth of Ms.&nbsp;Hubley’s FIA at the end of Year 1, calculate how much the reference index grew: (800 – 750) ÷ 750 = 6.67% at the end of Year 1. Adjusting the 6.67% growth in the index by the 75% participation percentage results in (6.67% × 0.75) = 5% interest. Because 5% is less than the 10% cap, the interest rate to apply to the FIA contract value at the end of Year 1 is 5%. The accumulated value of the FIA is $200,000 × 1.05 = $210,000, which is the FIA contract value at the beginning of Year 2.</p><p class=\"explanations\">At the end of Year 2, the reference index grew by (875 – 800) ÷ 800 = 9.38%. Adjusting the growth in the index by the 75% participation percentage results in (9.38% × 0.75) = 7.03% interest. Because 7.03% is less than the 10% cap, the interest rate to apply to the FIA contract value at the end of Year 1 is 7.03%. The accumulated value of the FIA is $210,000 × 1.0703 = $224,763 at the end of Year 2, which is the FIA contract value at the beginning of Year 3.</p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_111'] = objQuestion;


objQuestion = new Object();
objQuestion.strID = 'LOMA_371_PQ_112';
objQuestion.questionID = 121439;
objQuestion.item = 'LOMA_371_PPQ2021_112';
objQuestion.primaryLO = '11E';
objQuestion.textref = 'c. 11, p. 24';
objQuestion.textbook = 0;
objQuestion.chapter = 11;
objQuestion.module = 4;
var arrLOs = new Array();
arrLOs[0] = '11E';
objQuestion.arrLOs = arrLOs;
objQuestion.strType = 'choice';
objQuestion.intMinicase = -1;
objQuestion.strStem = "<p class=\"stem\">Various annuity guarantee riders—including guaranteed minimum death benefit riders and living benefit riders—are available to variable annuity contract owners. Two living benefit riders are the guaranteed minimum income benefit (GMIB) and the guaranteed minimum accumulation benefit (GMAB). The GMIB guarantees a minimum protected value that can be converted into annuity periodic income payments—usually after a waiting period of seven to ten years—(<b>but not if / even&nbsp;if</b>) the variable annuity’s accumulated value declines because of poor investment performance. Under a GMAB, the contract owner (<b>is / is not</b>) required to annuitize the contract.</p>";
var arrAnsChoices = new Array();
arrAnsChoices[0] = "but not if / is";
arrAnsChoices[1] = "but not if / is not";
arrAnsChoices[2] = "even if / is";
arrAnsChoices[3] = "even if / is not";
objQuestion.arrAnsChoices = arrAnsChoices;
var arrAnsIDs = [];
arrAnsIDs[0] = 491121;
arrAnsIDs[1] = 491122;
arrAnsIDs[2] = 491123;
arrAnsIDs[3] = 491124;
objQuestion.arrAnsIDs = arrAnsIDs;
objQuestion.intCR = 4;
var arrAnswerFeedback = new Array();
arrAnswerFeedback[0] = "<p class=\"explanations\">A GMIB can be converted into annuity periodic income payments, <b>even if </b>the variable annuity’s accumulated value declines because of poor investment performance. In addition, under a GMAB, the contract owner <b>is not </b>required to annuitize the contract.</p>";
arrAnswerFeedback[1] = "<p class=\"explanations\">It is true that, under a GMAB, the contract owner is not required to annuitize the contract. However, a GMIB can be converted into annuity periodic income payments, <b>even if </b>the variable annuity’s accumulated value declines because of poor investment performance.</p>";
arrAnswerFeedback[2] = "<p class=\"explanations\">It is true that a GMIB can be converted into annuity periodic income payments, even if the variable annuity’s accumulated value declines because of poor investment performance. However, under a GMAB, the contract owner <b>is not </b>required to annuitize the&nbsp;contract.</p>";
arrAnswerFeedback[3] = "<p class=\"explanations\">For variable annuities, the contract owner bears the investment risk for subaccount performance. Variable annuity premiums allocated to subaccounts are managed through an insurer’s separate accounts. Variable annuity owners that seek to mitigate their investment risk can obtain guaranteed benefits in the form of riders. Because the insurer guarantees variable annuity rider benefits, the insurer administers variable annuity riders within its general account, as it does with fixed annuities.</p><p class=\"explanations\">Some of the variable annuity guarantee riders available to contract owners include types of guaranteed minimum death benefit riders and living benefit riders. A guaranteed minimum death benefit (GMDB) generally guarantees that the variable annuity death benefit will at least equal a specified minimum amount. Newer forms of GMDBs, which are more expensive than traditional forms, generally result in higher guaranteed death benefits. These newer forms of GMDBs include annually compounded death benefits, ratcheted death benefits, and highest anniversary value death benefits.</p><p class=\"explanations\">Variable annuity guarantee living benefits can be referred to as “GLBs.” The contract essentially has two values: the accumulated value and the living benefit value. Because living benefits are guaranteed, insurers must establish reserves for them and make benefit payments as they become due. Most variable annuity contracts offer one or more of the following living benefit riders: a guaranteed minimum income benefit (GMIB) rider, a guaranteed minimum withdrawal benefit (GMWB) rider, a guaranteed lifetime withdrawal benefit (GLWB) rider, and a guaranteed minimum accumulation benefit (GMAB) rider.</p><p class=\"explanations\"><b>Learning Objective: 11E. Describe and differentiate among the types of variable annuity guarantee riders, including guaranteed minimum death benefit riders and living benefit riders.</b></p>";
objQuestion.arrAnswerFeedback = arrAnswerFeedback;
arrQuestions['LOMA_371_PQ_112'] = objQuestion;





var arrlotext = new Array(); 
arrlotext['11A'] = "11A. Differentiate between types of annuities, including immediate annuities, deferred annuities, fixed annuities, fixed indexed annuities, and variable annuities.";
arrlotext['11B'] = "11B. Describe how insurance companies estimate the cost of future annuity death benefits, surrender benefits, withdrawal benefits, and periodic income payments.";
arrlotext['11C'] = "11C. Describe and differentiate between the types of guaranteed annuity payout options and life annuity payout options.";
arrlotext['11D'] = "11D. Identify the fixed indexed annuity provisions that pertain to indexed crediting and explain the methods for calculating index credits, including the annual reset method, the point-to-point method, and the high water mark method.";
arrlotext['11E'] = "11E. Describe and differentiate among the types of variable annuity guarantee riders, including guaranteed minimum death benefit riders and living benefit riders.";
